### PR TITLE
 Add DOG DAD logo and info

### PR DESCRIPTION
**Pull request by thank-tp**
https://bscscan.com/tx/0x13211ecdb64256edecc2eb4eac4a94907a6a655c4efbf7649e70452da51c66f8

### CODE REVIEW

**Comment by thank-tp** [comment]
@sammvio   Please check it for me. Thank you

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3579750034

**Comment by sammvio** [comment]
Please refer to the tutorial, and re-submit your files in the correct format.

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
