### PR TITLE
add Energy logo and info

### PR DESCRIPTION
**Pull request by Energysevice**
https://bscscan.com/tx/0x6dc941bd4b7d1dba5484d983e0cb44b9e8ec640ae128e5a3f034ccbc92a9c449

### CODE REVIEW

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563代提代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by opera0001** [comment]
Abnormal transaction status

**Comment by Energysevice** [comment]
> Abnormal transaction status
https://bscscan.com/tx/0x6dc941bd4b7d1dba5484d983e0cb44b9e8ec640ae128e5a3f034ccbc92a9c449

Which deal failed

**Comment by Energysevice** [comment]
> 

My transaction hash submission is wrong. The following is correct

https://bscscan.com/tx/0x95c7d1da30039f474c02d00a513a07fa359529709ebeda5e8578bad8d4d2bda6

**Pull request closed without merging**
