### PR TITLE
add Gin info and logo

### PR DESCRIPTION
**Pull request by hailang47923**
https://hecoinfo.com/tx/0x9a5b4eef0455bea15d8bea2216121718cd2b7db7ed4906d475885da91db77b65

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Please re-submit your files to heco folder

**Comment by hailang47923** [comment]
> Please re-submit your files to heco folder

It has been resubmitted to heco folder. https://github.com/TP-Lab/tokens/pull/4078

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
