### PR TITLE
Add ZGL2 logo and info

### PR DESCRIPTION
**Pull request by smithrobert1419**
BSC-WZGL2-0xB6B149BF6BE92fedf792c74BF2aDB3FDc45eb9A8-https://bscscan.com/tx/0xc13553190c6549c52fa7ab2796ab2a511c63306f1e0cab836dbb4f15d951cafe

### CODE REVIEW

**Comment by smithrobert1419** [comment]
Then we need to provide an invoice.

opera0001 ***@***.***> 于2022年7月18日周一 15:01写道：

**Comment by smithrobert1419** [comment]
https://bscscan.com/tx/0xc13553190c6549c52fa7ab2796ab2a511c63306f1e0cab836dbb4f15d951cafe

This is our billing record.

Robert Smith ***@***.***> 于2022年7月19日周二 13:20写道：

**Comment by opera0001** [comment]
It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

**Comment by smithrobert1419** [comment]
*Add WZGL2 logo and info*
[image: Add WZGL2 logo and info.png]


The code submitted for review was not open source and was rejected. We have
re-released the new contract address and open sourced it. Please manage and
approve it, thank you.

opera0001 ***@***.***> 于2022年7月22日周五 23:10写道：

**Comment by smithrobert1419** [comment]
The submission I submitted has been open source, and the following address has been submitted on github. Please manage and approve it, thank you.


https://github.com/TP-Lab/tokens/pull/7849/commits/0a7c93e82bf2779d3a96e52260dc192ccb3f3108


Add WZGL2 logo and info



https://bscscan.com/tx/0xc13553190c6549c52fa7ab2796ab2a511c63306f1e0cab836dbb4f15d951cafe







BSC-WZGL2-0x9005441C2206D0C2FCf15792cD24e0e8fAEb0bcC-https://bscscan.com/tx/0xc13553190c6549c52fa7ab2796ab2a511c63306f1e0cab836dbb4f15d951cafe

**Pull request closed without merging**
