### PR TITLE
Add CryptobearClub NFT logo and info

### PR DESCRIPTION
**Pull request by ArviterLiu**
30000TPT：
https://bscscan.com/tx/0xf818fd39621496540ccf69071011b89d032434eef3384cb4b073c4a221cbf609
TxHash：
https://bscscan.com/tx/0x0d78d1a22f398b4bed0cac23c8b3948221474117bca684b253c26529d939f566

it is erc-721 token.

### CODE REVIEW

**Comment by opera0001** [comment]
It is detected that the contract address is not open source. In addition to possible potential risks, the picture content in NFT cannot be viewed in the wallet after the logo is included.

**Comment by ArviterLiu** [comment]
Received, we are validating the contract。
I will notify you when verification is complete, thank you very much

**Comment by ArviterLiu** [comment]
Hello, the contract code has been verified. Please have a look again. Thank you very much @opera0001

**Comment by ArviterLiu** [comment]
https://bscscan.com/address/0xDBfe087f8F56D81eF7741D65B99D6E7109CfF16a#code

**Pull request merged**
