### PR TITLE
Add NFTS logo and info

### PR DESCRIPTION
**Pull request by JYL22**
TPT:https://bscscan.com/tx/0x370198cbd092e5c11c198c964c8e2a66f54966c0c2145e2bad3d84878ae6b935 BNB:https://bscscan.com/tx/0xd37baadbf26f14e182c5d509f838b5b9c7c864a78fd6a6b6201fba4fdc072b83?utm_source=tokenpocket

### CODE REVIEW

**Comment by opera0001** [comment]
It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

**Comment by JYL22** [comment]
> It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

The token contract code is disclosed now.Thanks!

**Comment by JYL22** [comment]
I need to change the token logo, we made some adjustments, how can I do it？
Tks!

opera0001 ***@***.***> 于2022年9月26日周一 08:00写道：

**Comment by JYL22** [comment]
It is disclosed now.Thanks!

opera0001 ***@***.***> 于2022年9月22日周四 22:24写道：

**Pull request merged**
