### PR TITLE
Add ETHQ info and logo

### PR DESCRIPTION
**Pull request by zeevduke801577**
https://bscscan.com/tx/0x0a9933d5f6141ef23cd34879380f1717aa1c9d7b789157828ea63f8d63b84004

### CODE REVIEW

**Comment by tiaojiaotubiaobaoguo** [comment]
24小时提交logo包过，加QQ：2980874528

**Comment by sammvio** [comment]
The contract didn’t verify and publish. (No open-source)

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
