### PR TITLE
Add DissDAO logo and info

### PR DESCRIPTION
**Pull request by DissDAO**
https://bscscan.com/tx/0x04d30f48852a73f27b152a0334d205ced0998b260bd21dd36b3d395180ea93c6

### CODE REVIEW

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by opera0001** [comment]
The submitted logo contains insulting contents and words. Please re adjust and submit the logo.

**Comment by DissDAO** [comment]
@opera0001 hello, the logo have been updated, pls check again, thanks

**Comment by DissDAO** [comment]
https://bscscan.com/tx/0x4b3400ed006787018dc17a85559a9f3815ce764f376a9440ee1a8ededccc929c

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request merged**
