### PR TITLE
Add MSP logo and info

### PR DESCRIPTION
**Pull request by Metaverseswap**
交易3000TPT哈希: 0x12192c5eba14d8738e80d0c7da6c0a6dbd23e30156b6b042dd4218fa8164a041

https://bscscan.com/tx/0x12192c5eba14d8738e80d0c7da6c0a6dbd23e30156b6b042dd4218fa8164a041

### CODE REVIEW

**Comment by opera0001** [comment]
1. The submitted URL is incorrect
2. No liquidity pool is found, and there are certain risks in private transactions.
Please re submit the token logo for approval after adjustment. Thank you for your support for tokenpocket.

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
