### PR TITLE
delete repeat EB EBC logo and info

### PR DESCRIPTION
**Pull request by EBMetaverse**
https://bscscan.com/tx/0x0fc9b6b94457b682b347d76bdf0e9efb1ae76dc805ab1c9a3aa93ebda78b35fb
https://bscscan.com/tx/0x36df8fc095fb6cbbf57a673dc4d8c50452ba2349e7d9a21cae7448aecb08f241

EB token  0xECb38bb9c34AAd567B3Ec578c7Ef5BD7CA0DfbCb  ==> 0x52Bf8ccD76Aa5d117324750B8F1187FCA4E5332a
EBC token 0x9eFdF8a5769cc51e5fb15F22d816cA40dA07cbF4 ==> 0x4a4649Cd5866491CdF33555dCF843EF71c8b5311

### CODE REVIEW

**Comment by opera0001** [comment]
1. No liquidity pool
2. More concentrated token address
Please re submit the logo after adjustment or optimization. Thank you for your support for tokenpocket.

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
