### PR TITLE
上传logo

### PR DESCRIPTION
**Pull request by xwd1314191**
{
 "name": "Gamesquare Esports Inc (GSQ)",
 "website": "https://www.gamesquare.com/",
 "description": "Currency information introduction: Gamesquare helps brands and esports play together.",
 "explorer": "https://bscscan.com/token/0xd71ffc69902264e6240f84eed8532457fdd9381f ",
 "type": "BEP20",
 "symbol": "GSQ",
 "decimals": 18,
 "status": "active",
 "id": "0xD71fFc69902264E6240f84EEd8532457fdD9381F"
logo
}

### CODE REVIEW

**Comment by xwd1314191** [comment]
> { "name": "Gamesquare Esports Inc (GSQ)", "website": "https://www.gamesquare.com/", "description": "Currency information introduction: Gamesquare helps brands and esports play together.", "explorer": "https://bscscan.com/token/0xd71ffc69902264e6240f84eed8532457fdd9381f ", "type": "BEP20", "symbol": "GSQ", "decimals": 18, "status": "active", "id": "0xD71fFc69902264E6240f84EEd8532457fdD9381F" }
logo

**Comment by xwd1314191** [comment]
> { "name": "Gamesquare Esports Inc (GSQ)", "website": "https://www.gamesquare.com/", "description": "Currency information introduction: Gamesquare helps brands and esports play together.", "explorer": "https://bscscan.com/token/0xd71ffc69902264e6240f84eed8532457fdd9381f ", "type": "BEP20", "symbol": "GSQ", "decimals": 18, "status": "active", "id": "0xD71fFc69902264E6240f84EEd8532457fdD9381F" }
logo

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3076439606

**Comment by sammvio** [comment]
Please re-submit these tokens separately and attach the TPT transfer links on [Commit changes].

**Comment by xwd1314191** [comment]
怎么每次不帮我过呀

**Pull request closed without merging**
