### PR TITLE
Add ZEUS logo and info

### PR DESCRIPTION
**Pull request by sazuky**
Sample

### CODE REVIEW

**Comment by sazuky** [comment]
TPT贡献哈希链接 https://bscscan.com/address/0xf489923b778b66e7271cc1095509ce02c05afc72；
BNB签名链接 https://bscscan.com/tx/0x55fde317a01cbd679a3b975cb201c790070424e21ff233e2c7d4d9b75d0a6c56

**Comment by opera0001** [comment]
It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

**Comment by sazuky** [comment]
https://bscscan.com/address/0xf489923B778b66E7271cc1095509Ce02C05aFc72#code
Hello, the contract code is open source. Please check! Our company is a type of additional issuance.

**Comment by sazuky** [comment]
https://bscscan.com/address/0xf489923B778b66E7271cc1095509Ce02C05aFc72#code
Hello, the contract code is open source.

**Comment by sazuky** [comment]
https://bscscan.com/address/0xf489923B778b66E7271cc1095509Ce02C05aFc72#code
Hello, the contract code is open source.

**Comment by sazuky** [comment]
https://bscscan.com/tx/0x55fde317a01cbd679a3b975cb201c790070424e21ff233e2c7d4d9b75d0a6c56

**Pull request merged**
