### PR TITLE
UpDate PirateCoin info and logo

### PR DESCRIPTION
**Pull request by TangGuaTnag**
Transaction Hash: 0x5068fdc84ea52f36e4890f7e1609532652a00125a328ebb0611a4b4c3c3dadb5
https://bscscan.com/tx/0x5068fdc84ea52f36e4890f7e1609532652a00125a328ebb0611a4b4c3c3dadb5

Pirate coin have been included by CMC and CG. And the beta version of the 3D game is already online. In Pirate Coin We Trust. Let’s get Rich Together! The ultimate NFT GAME METAVERSE on the Binance Smart Chain. Our objective is to contribute to many organizations that clean marine litter to save our planet.

### CODE REVIEW

**Comment by TangGuaTnag** [comment]
UpDate info and logo

**Comment by TangGuaTnag** [comment]
@giki0318 @zhujiayu03 @guoxintongsam 
Hello, help you see if there are any problems with the project, how long will it take to merge the information into the main trunk?

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
