### PR TITLE
Add DOGEFOOD logo and info

### PR DESCRIPTION
**Pull request by Deepdarkforest**
sample

### CODE REVIEW

**Comment by Deepdarkforest** [comment]
0xb2e69ff026c5ddef26285ff4451e3cef37e479933e8fa51a48f7b55aa79f2931

**Comment by Deepdarkforest** [comment]
please Merge the updated one for the info 
93c921feda0f2f6988cf761aa3867dbdfee42325

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3579750034

**Comment by Deepdarkforest** [comment]
231c823fc2f457c3ee490c995a82a893f6c81e06 
Please merge the dogefood file

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request merged**
