### PR TITLE
ADD FuckStarbucks logo and info

### PR DESCRIPTION
**Pull request by holyhi**
https://bscscan.com/tx/0xf7b423069dc282bb538b253538c5a1769fa7840fe8d67c2df222f948e3e01243  https://bscscan.com/tx/0x4f888ecfea118ab5f4f2730152b6a4dbe815b4391a0cf4abf4afcb899125f9d4

### CODE REVIEW

**Comment by opera0001** [comment]
1. Low token liquidity pool
2. The logo provided is not 256x256 pixels
Please submit the token logo application after readjustment or optimization. Thank you for your support for tokenpocket.

**Comment by holyhi** [comment]
logo

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
