### PR TITLE
 Add GOCP logo and currency transfer infor , TPT transmission link

### PR DESCRIPTION
**Pull request by tl2215689**
TPT Outgoing address  :  https://hecoinfo.com/tx/0x648116310f95512abbe6cda4f2f8dd99d554b0e11ea5362d1ed58584b4eff089

Transaction hash：0x648116310f95512abbe6cda4f2f8dd99d554b0e11ea5362d1ed58584b4eff089

### CODE REVIEW

**Review by tl2215689 — COMMENTED** [review]
TPT  transmission :linkhttps://hecoinfo.com/tx/0x648116310f95512abbe6cda4f2f8dd99d554b0e11ea5362d1ed58584b4eff089

Transaction hash ：0x648116310f95512abbe6cda4f2f8dd99d554b0e11ea5362d1ed58584b4eff089

**Comment by zhujiayu03** [comment]
Please re-submit your files to HECO folder

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
