### PR TITLE
Add CPC and STB logo and info

### PR DESCRIPTION
**Pull request by Lsylsy1321**
Add CPC logo and info
https://hecoinfo.com/tx/0x3abd4ce259acb75372bf7cbf4281153d93a1c3430bf9226c7614d64e3146db24
Add STB logo and info
https://hecoinfo.com/tx/0x6c9c3558010f744e8565ce15c757903c7d74ebb91affac7cd0bbad907db84942

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Please re-submit your files to heco folder

**Comment by Lsylsy1321** [comment]
Both have been submitted separately. Please review as soon as possible

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
