### PR TITLE
Add NAOS Finance logo and info

### PR DESCRIPTION
**Pull request by WesleyLiu0717**
ETH List Payment:
https://bscscan.com/tx/0x90f2017c9f65fd638a123c603b490030b584da16640003f3404d41b53175608a
BSC List Payment:
https://bscscan.com/tx/0xe8a8122be20dab23a6812dad28009daef5dc4e598b559bd95756ca1f2ddc83a7

### CODE REVIEW

**Comment by opera0001** [comment]
0x4a615bB7166210CCe20E6642a6f8Fb5d4D044496--Done

0x758d08864fB6cCE3062667225ca10b8F00496cc2--
If the ownership of the contract is not abandoned, there may be some risks, such as issuing additional tokens.

**Comment by WesleyLiu0717** [comment]
0x758d08864fB6cCE3062667225ca10b8F00496cc2
This contract is owned by anyswap crosschain bridge. 
This is for user to bridge their tokens from ETH to BSC.

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request merged**
