### PR TITLE
add AK logo and info

### PR DESCRIPTION
**Pull request by gitlg2**
https://bscscan.com/tx/0xcebce00d29c372869ac96fba7e67fef03960acee464cfa2c8e3cb0439a384470

### CODE REVIEW

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by opera0001** [comment]
1. Abnormal token transaction status
2. Token contract does not relinquish ownership
3. Blacklist function may exist

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
