### PR TITLE
Add GBFE logo and

### PR DESCRIPTION
**Pull request by hujun918**
https://hecoinfo.com/tx/0xc09c14091d6b57cfb8e9aad55c899f03e92453a3ef09e62eb915d51dae9d15a8

### CODE REVIEW

**Comment by hujun918** [comment]
Add GBFE logo and info

**Comment by zhujiayu03** [comment]
Please re-submit your files to heco folder

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
