### PR TITLE
Add logo and info for Our Token

### PR DESCRIPTION
**Pull request by shuaidie**
TPT:   https://bscscan.com/tx/0x03243c2d38cb94b05ccfdd6ff405669232eb9f4bb3c3357c5703d1846f246a34
BNB:   https://bscscan.com/tx/0x358791929831ebcfdb8f9e95f1b54c46dd5f6e65c159ebcf095b6ac0ec7eaccd

### CODE REVIEW

**Comment by shuaidie** [comment]
0x03243c2d38cb94b05ccfdd6ff405669232eb9f4bb3c3357c5703d1846f246a34

**Comment by shuaidie** [comment]
Our token named BDD which contract is TM4xFuTPxwVRZSRRTJmWbUrmfCYsg5UxgZ

**Comment by shuaidie** [comment]
https://bscscan.com/tx/0x03243c2d38cb94b05ccfdd6ff405669232eb9f4bb3c3357c5703d1846f246a34

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Pull request merged**
