### PR TITLE
Add BGC logo and info

### PR DESCRIPTION
**Pull request by RRR1024**
https://bscscan.com/tx/0x27e8a2b6ac047e8314891bb45d365f05a64c40a1f29d01e9011c7dd8c9c36e2a

### CODE REVIEW

**Comment by opera0001** [comment]
Detected hidden owner permissions in the token contract, which is a highly risky configuration. Unless you can provide a code security certificate issued by a reputable company, the token logo cannot be added for you.

**Comment by RRR1024** [comment]
> Collaborator

Do you mean: Should I discard the token with the manager's permission or do you suspect that there is a hidden owner's permission in the token? I did not set the hidden owner during the development, can you verify for me? Or do you recommend several so-called credible institutions for me to submit the code for review

**Comment by opera0001** [comment]
The hidden owner's permissions will not become invalid due to the abandonment of control permissions by the token contract. It is also possible that the code of the token contract is copied and used through other channels, so the risk is still significant. Another scenario is that the detection data of Goplus may not be accurate enough. You can also try contacting them for reevaluation at https://gopluslabs.io/.

**Comment by opera0001** [comment]
Dear, I need to close the order as it has been quite a few days. If you have resolved these issues, feel free to contact me through the issues section to continue this order.

https://github.com/TP-Lab/tokens/issues

**Comment by RRR1024** [comment]
> 隐藏所有者的权限不会因代币合约放弃控制权限而失效。也有可能代币合约的代码被其他渠道复制使用，所以风险还是很大的。另一种情况是Goplus的检测数据可能不够准确。您还可以尝试通过https://gopluslabs.io/联系他们进行重新评估。

**Comment by Rico31415926** [comment]
Now I want to issue a new token to replace this failed token. May I ask if the fee that has been submitted can be reused

**Comment by RRR1024** [comment]
Now I want to issue a new token to replace this failed token. May I ask if the fee that has been submitted can be reused

**Pull request closed without merging**
