### PR TITLE
Add Burn logo and info

### PR DESCRIPTION
**Pull request by Burnedfi**
https://bscscan.com/tx/0xa14815ef0edf08f381ee424070b63a051bb2ccc252aaa44081440226db5a1f28

### CODE REVIEW

**Comment by Burnedfi** [comment]
Sir, please help me add to BSC, thank you

**Comment by opera0001** [comment]
Hidden owner permissions were detected in the token contract address, posing significant risks.

**Comment by Burnedfi** [comment]
> Hidden owner permissions were detected in the token contract address, posing significant risks.

No, the contract is secure，Liquidity has been pumped into the black hole address ，Please check again

**Comment by Burnedfi** [comment]
Dear Sir, how do I get my application approved?    The contract is secure and the TPT payment has been completed

**Comment by Burnedfi** [comment]
https://bscscan.com/tx/0x8b1bb9d2b93258c90e953f1d75788b572d890aa1f546cc9e75845543ffe1fa26

**Comment by Burnedfi** [comment]
https://bscscan.com/tx/0x8b1bb9d2b93258c90e953f1d75788b572d890aa1f546cc9e75845543ffe1fa26

**Comment by Burnedfi** [comment]
https://bscscan.com/tx/0x8b1bb9d2b93258c90e953f1d75788b572d890aa1f546cc9e75845543ffe1fa26

https://bscscan.com/tx/0xa14815ef0edf08f381ee424070b63a051bb2ccc252aaa44081440226db5a1f28

**Pull request merged**
