### PR TITLE
Add PHT logo and info

### PR DESCRIPTION
**Pull request by DissFree**
https://bscscan.com/tx/0x42a55a786d1ef380f0bfb4c353cc27b8a9c9b6a819685037daa53293f4cdfb12

### CODE REVIEW

**Comment by opera0001** [comment]
What is the old contract address? Was it submitted by this github account?

**Comment by opera0001** [comment]
Two different addresses and the same logo are provided in the json, which contract address do I need to remove the logo from? Which contract address needs to be used to add the new logo?

**Comment by DissFree** [comment]
> json中提供了两个不同的地址和同一个logo，我需要从哪个合约地址去掉logo？添加新标识需要使用哪个合约地址？

Remove logo 0x9d08F8c8Efb54CcaF85E88083a62857F379299d1 from this address, and add new logo need to use this address 0x2D136b1F830Ef58Ba66ED2dDa910854480Cbf0f9, sorry for causing you trouble

**Comment by DissFree** [comment]
Remove logo 0x9d08F8c8Efb54CcaF85E88083a62857F379299d1 from this address, and add new logo need to use this address 0x2D136b1F830Ef58Ba66ED2dDa910854480Cbf0f9, sorry for causing you trouble

**Comment by opera0001** [comment]
0x2D136b1F830Ef58Ba66ED2dDa910854480Cbf0f9

It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

**Comment by DissFree** [comment]
The contract has been made public, please review

**Pull request merged**
