### PR TITLE
Add XYG logo and info

### PR DESCRIPTION
**Pull request by TUBOOS**
https://bscscan.com/tx/0x5c810b7a31204ef2219668bdf2048537981aafe1686cc676d4d4e1a96946b3e0

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token

**Comment by TUBOOS** [comment]
XYG&nbsp;token&nbsp;Submitted


---Original---
From: ***@***.***&gt;
Date: Wed, Jul 28, 2021 18:06 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] Add XYG logo and info (#1731)




 
Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token
 
&mdash;

**Comment by TUBOOS** [comment]
XYG&nbsp;logo&nbsp;and&nbsp;info&nbsp;(#1731)
Token&nbsp;is&nbsp;listed,&nbsp;please&nbsp;merge&nbsp;logo
thanks


---Original---
From: ***@***.***&gt;
Date: Wed, Jul 28, 2021 18:06 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] Add XYG logo and info (#1731)




 
Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token
 
&mdash;

**Comment by TUBOOS** [comment]
Please&nbsp;update&nbsp;the&nbsp;logo


---Original---
From: ***@***.***&gt;
Date: Thu, Jul 29, 2021 16:43 PM
To: ***@***.******@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [TP-Lab/tokens] Add XYG logo and info (#1731)


XYG&nbsp;logo&nbsp;and&nbsp;info&nbsp;(#1731)
Token&nbsp;is&nbsp;listed,&nbsp;please&nbsp;merge&nbsp;logo
thanks


---Original---
From: ***@***.***&gt;
Date: Wed, Jul 28, 2021 18:06 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] Add XYG logo and info (#1731)




 
Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token
 
&mdash;

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
