### PR TITLE
Add UP logo and info

### PR DESCRIPTION
**Pull request by Atudouzige**
https://bscscan.com/tx/0x9b91473aef966b6652727be521e4c02e618b344ebe4a201f725360a167cfbf63

### CODE REVIEW

**Comment by opera0001** [comment]
1. detecting the existence of a function to suspend token transactions.
2. detecting the function that token trading rates can be modified, please explain their use.

**Comment by Atudouzige** [comment]
In order to stabilize the market, the transaction will be closed from 12:00 p.m. to 8:00 a.m. in the early stage to prevent someone from smashing the market at night. The tax rate is changed to reduce the transaction fee in the later stage.



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 08/31/2022 10:05 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [TP-Lab/tokens] Add UP logo and info (PR #8129) |

detecting the existence of a function to suspend token transactions.
detecting the function that token trading rates can be modified, please explain their use.

**Comment by opera0001** [comment]
if you have questions you can go to issues and contact me.

https://github.com/TP-Lab/tokens/issues

**Comment by Atudouzige** [comment]
Should market issues not be under the official management of TP? After paying 50,000 TPT, should I help you pass the avatar?



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 09/02/2022 21:13 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [TP-Lab/tokens] Add UP logo and info (PR #8129) |

Regarding the fact that tokens can be suspended from trading and according to what you said will be temporarily suspended depending on the time, I don't think this is in line with the market and it is not a good way to apply it.

**Pull request merged**
