### PR TITLE
ADD TDR info and logo

### PR DESCRIPTION
**Pull request by lcwypn**
https://bscscan.com/tx/0xc4de2c26470e46afc7c1ba0a3c8ce83feb70ce49fb1c0c39a3cd234a24ce8733
https://bscscan.com/tx/0x52f07bed19d0d40209514194cd5ae23fe4c07500b360451a7a49e772f7518c69

### CODE REVIEW

**Comment by lcwypn** [comment]
Change name and contract

**Comment by opera0001** [comment]
I'm sorry, dear. Your last order submission was 5 days ago, so now you can change your logo, but you cannot change the contract address because your logo has already been displayed for 5 days, making it a valid inclusion action.

**Comment by opera0001** [comment]
Yes, submitting a new token logo for inclusion requires providing a new order.

**Comment by lcwypn** [comment]
image
This is a new project

**Pull request merged**
