### PR TITLE
Add FLASH logo and info

### PR DESCRIPTION
**Pull request by inhobok509**
捐赠hash:  https://bscscan.com/tx/0x6cec0b43011ed152269e49e169753b1d5d3c872fcfec1ce0cc23d4aaee1d5448
验证hash:  https://bscscan.com/tx/0x0a1974e9a2fb8d934e890875e6739a91e6fc5bcc4d8dde69a511ba3e406f3ecd

### CODE REVIEW

**Comment by inhobok509** [comment]
The TPT hash was copied by user #7081, you can see the from address of the TPT Hash and the verification hash

**Comment by inhobok509** [comment]
Through TPT Hash 、 verify the from address of the hash, you can know that my side is right, add FLASH logo and info according to my help

**Comment by opera0001** [comment]
Please transfer 0.000513 bnbs to 0x7837ae9e4fd6e967f1b8c8824d6288ece6e730f9 for verification. Thank you.

**Comment by inhobok509** [comment]
https://bscscan.com/tx/0xb3fac68d4fdfb9bb792d129dd8f1519d68b3391a268e9ddc3e7445065997d00e

**Comment by opera0001** [comment]
image
Token contracts have a lot of rights, and there will be some risks.

**Comment by inhobok509** [comment]
Purchase: Deduct 15% (5% is destroyed, 10% is accumulated to the FLASH contract address)
Sell: Deduct 15% (5% is destroyed, 10% + buy accumulated FLASH to exchange USDT for dividends)

**Comment by opera0001** [comment]
A control switch that can stop the transaction is detected.

**Pull request closed without merging**
