### PR TITLE
Add ROW logo and info

### PR DESCRIPTION
**Pull request by RowGames**
https://bscscan.com/tx/0x2b12d1305d84e4620f040e14228f7a29f98c345962479017e9d604b0c40ef6f7?utm_source=tokenpocket

### CODE REVIEW

**Comment by opera0001** [comment]
The vision of the project is very rich, but there are no other operations after the issuance of tokens, so it is impossible to check whether there are risks; It is impossible to predict the token circulation mode without a working capital pool. It is recommended to resubmit the token logo application after adjustment or optimization. Thank you for your support for tokenpocket.

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
