### PR TITLE
Add MarsHome logo and info

### PR DESCRIPTION
**Pull request by haatcode**
Add MarsHome logo and info

### CODE REVIEW

**Comment by opera0001** [comment]
Abnormal token circulation, high risk.

**Comment by haatcode** [comment]
tpt hash : https://bscscan.com/tx/0x89b911e07c99275cea84a483974060377057221493c812ca612d991d45787453

**Comment by haatcode** [comment]
> Abnormal token circulation, high risk.
this token is now in buy to destroy mode

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Pull request merged**
