### PR TITLE
Add EKTA logo and info

### PR DESCRIPTION
**Pull request by ektachina**
BSC - TPT - 0xeca41281c24451168a37211f0bc2b8645af45092 - https://bscscan.com/tx/0x93728f76665b621b4f39412942c7f0981e90f3d4a681b42e41562fe49e9ef2c0

### CODE REVIEW

**Comment by opera0001** [comment]
Agency contract detected, high risk, please check.

**Comment by ektachina** [comment]
Would be great appreciated if you can give us some guidance, how could I solve the issue?

**Comment by opera0001** [comment]
It is a proxy contract, may be potential upgrade and replacement risks  

Please solve this problem

**Comment by ektachina** [comment]
Did we pass the approval? or shall I re-submit a new pull request with token name 'EKTA v2", please?

**Pull request closed without merging**
