### PR TITLE
Create info.json

### PR DESCRIPTION
**Pull request by usddvip**
Add UD logo and info

### CODE REVIEW

**Comment by usddvip** [comment]
1

**Comment by guoxintongsam** [comment]
Please re-submit the TPT transfer link on [Commit changes].

**Comment by usddvip** [comment]
Sorry for so late respond.Hv re-submitted the transfer link,pls check it.

**Comment by usddvip** [comment]
Dear sir,
The logo has not been issued yet,what can we do pls?

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
