### PR TITLE
Add MJGSHIB logo and info

### PR DESCRIPTION
**Pull request by MahjongShiba**
https://bscscan.com/tx/0x49bec23fd62f676f1c1d65e77a6099085063bd48ee2dea943ad533376ed175a6

### CODE REVIEW

**Comment by nenrgy** [comment]
专业提交logo,代币，白皮书，诚住经营，值得信赖，价格全网最优！QQ:2099728898

**Comment by giki0318** [comment]
involved in scam

**Comment by MahjongShiba** [comment]
> involved in scam
Please reconfirm that this token can be bought and sold normally, the formal marketing campaign has not yet started

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
