### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by sunny-veto**
{ 
"name": " SUPER HERO",
"website": "https://www.superironman.org/",
"description": "Super Hero aims to combine the physical industry with the digital economy, shape the new superhero Yuan universe space, break the "island effect" between different fields, integrate it into a whole The drainage mechanism prompts more users to participate in the experience of our superhero. ",
"explorer": "https://bscscan.com/token/0xe30fa338f2a620fa7824d567046b4a9ef6a3c6e9",
"type": "BEP20",
"symbol": "IRON",
"decimals": 18,
"status": "active",
"id": "0xe30fa338f2a620fa7824d567046b4a9ef6a3c6e9"
}
https://bscscan.com/tx/0xcf7df7bfa4e310d12177e393b62a216d14d01530aeba456bb25979fa522cf013

### CODE REVIEW

**Comment by opera0001** [comment]
image
Please readjust the json file

1. If you detect a setting where tokens can be added to the issue, please explain the situation.

2、The setting that can suspend trading is detected, please explain the situation.

3、The setting that cannot be sold 100% is detected, please explain how to make all holders aware of it?

4. A setting is detected that the transaction rate can be modified, please explain the situation.

**Comment by sunny-veto** [comment]
A new info file has been submitted；For the safety of the funds of the lp pool, we have set the possibility to suspend the transaction；Can not sell 100%, need to reserve 0.01 tokens, we have full-time preachers to explain the situation to the holders；

**Comment by opera0001** [comment]
Please clarify any other questions.

**Comment by opera0001** [comment]
I didn't see your reply after 2 days, so the order needs to be closed. If you have any questions, you can contact me by leaving a message in issues.

https://github.com/TP-Lab/tokens/issues

**Comment by sunny-veto** [comment]
A new info file has been submitted；For the safety of the funds of the lp pool, we have set the possibility to suspend the transaction；Can not sell 100%, need to reserve 0.01 tokens, we have full-time preachers to explain the situation to the holders；Adjustable transaction rates allow us to better control token prices；We don't know about other issues with tokens

**Pull request closed without merging**
