### PR TITLE
add Reunion dog and info

### PR DESCRIPTION
**Pull request by yutianmr**

### CODE REVIEW

**Comment by opera0001** [comment]
1. The submitted URL is incorrect（0xf16e42B93b7cD862422C36e8642BB57Db8B95F7C、0x71CCe0035d82c21Cf4b908bcd8F1117fFf0Fa623）
2. The token may have blacklist function, which has certain risks
3. 0xB4C41f17F2fA3a8101aC0928e9298a6BcAC76Ba9 --Done
Please re submit the token logo for approval after adjustment. Thank you for your support for tokenpocket.

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
