### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by BishokuMaster**
https://bscscan.com/tx/0x6679d7ecbe64c1567728ea134017035428be06978a743fbc5c76c31a3f5aa267

### CODE REVIEW

**Review by BishokuMaster — COMMENTED** [review]
https://bscscan.com/tx/0x6679d7ecbe64c1567728ea134017035428be06978a743fbc5c76c31a3f5aa267

**Comment by zhujiayu03** [comment]
Unqualified image, please resend your request.

**Comment by BishokuMaster** [comment]
https://github.com/TP-Lab/tokens/pull/845

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
