### PR TITLE
Add MW logo and info

### PR DESCRIPTION
**Pull request by Bobmeta7**
Looking forward to  successful addition.

If something wrong,plz e-mail me. or let me know on Github. THANK U A LOT!
stevenallen1016@gmail.com

image
this is my info.json file screenshots

### CODE REVIEW

**Comment by opera0001** [comment]
This address: 0xa6660E62c223Df2D9Aff0Ba188f1371087fa3Dd6 was not submitted by this github account. Modifying the contract or logo requires the original submitted github account for the operation. Please check.

**Comment by Bobmeta7** [comment]
Should I resubmit the JSON file?

**Comment by opera0001** [comment]
> Should I resubmit the JSON file?

No, you need to remove the logo of the contract address of the history of the submission of the github account to apply a little.

**Comment by opera0001** [comment]
The logo requested by 0x154d746794449B6CF534FA11A2Cf7FfF5C968977 has been completed for inclusion.

**Comment by Bobmeta7** [comment]
> This address: 0xa6660E62c223Df2D9Aff0Ba188f1371087fa3Dd6 was not submitted by this github account. Modifying the contract or logo requires the original submitted github account for the operation. Please check.

this contract is not mine ,i have no idea why it will show up in my json file.

**Comment by Bobmeta7** [comment]
> 

Thank u so much!!! Your assistance is greatly appreciated

**Pull request closed without merging**
