### PR TITLE
Add CHD logo and info

### PR DESCRIPTION
**Pull request by CharityDaoDev**
https://bscscan.com/tx/0x9810b7309c2298b699395b7070866c11437e9f96794601f95b1441706380b71c
https://bscscan.com/tx/0x1811aeba2c3a90e6d5d9f7c127ed9eda06e89ea9e5d437436959336821bcd8bb

### CODE REVIEW

**Comment by opera0001** [comment]
It is detected that the token contract has no open source.

**Comment by CharityDaoDev** [comment]
> It is detected that the token contract has no open source.
Now, the token contract is open source.

**Comment by opera0001** [comment]
image
The submitted file is not saved in the BSC directory, please adjust it again.

**Comment by CharityDaoDev** [comment]
okay,adjusted

**Pull request closed without merging**
