### PR TITLE
ADD MT-C LOGO和信息

### PR DESCRIPTION
**Pull request by allenliusy**

### CODE REVIEW

**Comment by opera0001** [comment]
Please provide the hash value link for the TPT donation.

**Comment by allenliusy** [comment]
Please wait, donate within this week

**Comment by opera0001** [comment]
After making a donation, please leave a message here. If your order remains unupdated for an extended period, it may be closed. Thank you.

**Comment by opera0001** [comment]
After 3 days without seeing your message or any changes, the order needs to be closed. You can reach out to me through issues to provide the TPT link for further communication.

https://github.com/TP-Lab/tokens/issues"

**Pull request closed without merging**
