### PR TITLE
Add JXRY logo and info

### PR DESCRIPTION
**Pull request by laopowan**
https://bscscan.com/tx/0xe11cb2b719f596ba5effa078db405aedd25bf7b21a2819a0885930f133dca9cf

### CODE REVIEW

**Review by laopowan — COMMENTED** [review]
https://bscscan.com/tx/0xe11cb2b719f596ba5effa078db405aedd25bf7b21a2819a0885930f133dca9cf

**Comment by laopowan** [comment]
https://bscscan.com/tx/0xe11cb2b719f596ba5effa078db405aedd25bf7b21a2819a0885930f133dca9cf

**Comment by opera0001** [comment]
The submitted TPT donation hash value has been #6155 used and included. Other token collections need a new donation hash value. At the same time, please don't use a GitHub account to submit multiple logos at one time.

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
