### PR TITLE
0x444Fb3e7eF331f3A3F6E82052616b0c5B92D57BD

### PR DESCRIPTION
**Pull request by atlantisdapp**
0x19eda55f786da5370cdc6a8afea2d9da188112d8bd0cccabd8ad72f07adda8a5

### CODE REVIEW

**Comment by opera0001** [comment]
image
The submitted file is not saved in the BSC directory, please adjust it again.

**Comment by atlantisdapp** [comment]
> 圖片 提交的文件沒有保存在BSC目錄下，請重新調整。

在哪调整啊？

**Comment by atlantisdapp** [comment]
Can you give me a tutorial? i won't change










At 2023-01-17 17:30:32, "opera0001" ***@***.***> wrote:


The submitted file is not saved in the BSC directory, please adjust it again.

**Comment by opera0001** [comment]
This needs to be adjusted by yourself, or you can only resubmit github orders.

**Pull request merged**
