### PR TITLE
Add BabyDoge logo and info

### PR DESCRIPTION
**Pull request by babydogecoingg**
https://cn.etherscan.com/tx/0xa264c414b8c81ecd6d35ffe26d430e101090b959285d9a4e5c75dd3fc06abf2f

### CODE REVIEW

**Comment by babydogecoingg** [comment]
I had checksum Ethereum address to the correct one using your link.

**Comment by zhujiayu03** [comment]
图标侵权

**Comment by babydogecoingg** [comment]
Hi zhujiayu,

The picture is design by our own design team, no copyright issue, we are
listed on coin market cap, coingecko and other using this picture.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
