### PR TITLE
Add WAP logo and info

### PR DESCRIPTION
**Pull request by ww0031**

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Please submit the detailed token info.

**Comment by ww0031** [comment]
{
 "name": "World Animal Protection",
 "website": "-",
 "description": "-",
 "explorer": "https://bscscan.com/token/0x6f16ad4c00a7eb064b5c39080dafa35f788ca331",
 "type": "BEP20",
 "symbol": "WAP",
 "decimals": 18,
 "status": "active",
 "id": "0x6f16ad4c00a7eb064b5c39080dafa35f788ca331"
}

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
