### PR TITLE
Add SMART logo and info

### PR DESCRIPTION
**Pull request by guoxiaobie**
BSC - https://bscscan.com/tx/0xc054b38775974a4ab48f7c510295222aae000d3bfac7731d65148f04a481d7da
TPT - https://bscscan.com/tx/0x392a59c8828626b6a634080c43b0e82b75801df25070769c7b669f450730685a

### CODE REVIEW

**Comment by opera0001** [comment]
The token contract seems to contain hidden owenr permissions, which is a very dangerous built-in feature, please explain what it does?

**Comment by guoxiaobie** [comment]
Owner permission is granted to assist our community users and our DAPP users in conducting cross-chain token swap operations more efficiently. We will not use this permission to modify anything.

**Comment by opera0001** [comment]
> Owner permission is granted to assist our community users and our DAPP users in conducting cross-chain token swap operations more efficiently. We will not use this permission to modify anything.

What can prove that the data?

**Comment by guoxiaobie** [comment]
> > Owner permission is granted to assist our community users and our DAPP users in conducting cross-chain token swap operations more efficiently. We will not use this permission to modify anything.
> 
> What can prove that the data?

You can browse our official Twitter and community, we are guiding users to perform cross-chain swaps. Currently, many users in the community are not familiar with the process of performing cross-chain swaps, and we will assist them in completing the process and transferring tokens to their specified wallets.

**Pull request merged**
