### PR TITLE
Add MCA logo and info

### PR DESCRIPTION
**Pull request by mca1011**
https://bscscan.com/tx/0x6e4e18c35e0ec80e51e48aaf9958d53ece62a64ac47376a51aa971c41109ec93 https://bscscan.com/tx/0x847fbf730cd7c85e6d00d59c9291e89b03666a142ad47e4635f05c5161641f19

### CODE REVIEW

**Comment by mca1011** [comment]
We are in the process of final testing. We need logo online. Please help us. Thank you very much.

**Comment by opera0001** [comment]
> We are in the process of final testing. We need logo online. Please help us. Thank you very much.

Please be advised that if the token you are currently submitting is a test token, after the logo is included, if there is a need to change the token contract or logo in the future, you will need to make a new donation. Therefore, please verify the tokens you need to include carefully.

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Comment by mca1011** [comment]
Please help us to review as soon as possible. Thank you very much.

**Pull request merged**
