### PR TITLE
add TPT logo and info

### PR DESCRIPTION
**Pull request by weimob321**
bsc-weimob-0xe0d443CAf64498573b375239D6cbf17B660Fb8B2-https://bscscan.com/tx/0x893aa280ab416e794254c05e06c47359db433182da03c40acd13308b77d478a7

### CODE REVIEW

**Comment by opera0001** [comment]
The token contract code is not open source and cannot detect the security. If it cannot be disclosed for special reasons, the audit report of the security audit institution needs to be issued.

Did you also submit #6565?

**Comment by weimob321** [comment]
Hello, how come the logo with my contract address 0xe0d443caf64498573b375239d6cbf17b660fb8b2 will not be displayed?
------- Original Message -------

**Comment by weimob321** [comment]
Hello, how come the logo with my contract address 0xe0d443caf64498573b375239d6cbf17b660fb8b2 will not be displayed?

**Comment by weimob321** [comment]
Hello, the token name we submitted is weimob, the contract address is 0xe0d443caf64498573b375239d6cbf17b660fb8b2, and the transfer TPT record ishttps://bscscan.com/tx/0x893aa280ab416e794254c05e06c47359db433182da03c40acd13308b77d478a7,Verify link is https://bscscan.com/tx/0x8f3150afe95b4185c7c22656a3e2435382c8b189209f05503927d9003635a5a9。 Our contract is open source,Logo and info JSON file is in the attachment, please check it, thank you!
------- Original Message -------

**Pull request closed without merging**
