### PR TITLE
Add TPT logo and info

### PR DESCRIPTION
**Pull request by defiAngel**
1000 TPT: https://bscscan.com/tx/0x8b64e955e5e4c9784d44d2f73e7ec6fa21e65d56b0bbdc57e936a78f1bd91870
0 BNB: https://bscscan.com/tx/0x740b5e0f57bb0c91f03f283eb1b9f4b94c71509bc2c24bb19355702f13dc4008

Please try to display the following additional information:

Official website: https://www.angel-token.finance/
Release time: 2021-08-17 16:01:55
Total issuance: 1000000000000000
Project introduction: Angel investment is the pioneer of venture capital. Belief people empower Angel, Angel gives wealth to the belief.

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token

**Comment by defiAngel** [comment]
has submited, please process.

**Comment by defiAngel** [comment]
your document no need first submit in token pocket, why?

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Pull request closed without merging**
