### PR TITLE
Add BEE logo and info

### PR DESCRIPTION
**Pull request by jdd-1986**
https://bscscan.com/tx/0xcbc2d8fee5f4814cc2b0c80a2590d5bcdd558a5c068f4c8b51a89e042974aabb

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Please submit your logo in the correct size.

**Comment by jdd-1986** [comment]
BEE logo has been resubmitted.
Please help with it, thank you.
https://github.com/TP-Lab/tokens/pull/1952




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TP-Lab/tokens"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月30日(星期五) 中午11:45
***@***.***&gt;;
抄送:&nbsp;"Jedda ***@***.******@***.***&gt;;
主题:&nbsp;Re: [TP-Lab/tokens] Add BEE logo and info (#1774)





 
Please submit your logo in the correct size.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by daibilogo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
