### PR TITLE
Add BMW logo and info

### PR DESCRIPTION
**Pull request by XiangBin520**

### CODE REVIEW

**Comment by opera0001** [comment]
Now, 30000 TPT donation fee is required to submit the logo application. Please supplement the difference and submit the hash value link to GitHub.

A GitHub account can only submit one logo application at a time

**Comment by XiangBin520** [comment]
我之前转过3000TPT怎么还要转
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TP-Lab/tokens"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月12日(星期六) 下午3:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TP-Lab/tokens] Add BMW logo and info (PR #6121)





 
Now, 30000 TPT donation fee is required to submit the logo application. Please supplement the difference and submit the hash value link to GitHub.
 
A GitHub account can only submit one logo application at a time
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by opera0001** [comment]
The old TPT donation hash value can be submitted after supplementing the difference.

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
