### PR TITLE
Add NB logo

### PR DESCRIPTION
**Pull request by Marlysnb**
https://bscscan.com/tx/0x77ad34ca5b1b5cb905d340e3d268ffc8f0bb334e6d0ca59357a5aa5862546bc1

### CODE REVIEW

**Comment by opera0001** [comment]
image
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Comment by opera0001** [comment]
Please hurry to Revise, the order will be closed tonight.

**Comment by opera0001** [comment]
I don't see your reply or change after 3 days, so the order needs to be closed, you can contact me in issues if you need to communicate, thanks.

https://github.com/TP-Lab/tokens/issues

**Comment by Marlysnb** [comment]
Could you please tell me how I should modify it?

**Pull request closed without merging**
