### PR TITLE
add DSC info and logo

### PR DESCRIPTION
**Pull request by tosndfo**

### CODE REVIEW

**Comment by tosndfo** [comment]
transefer TPT txid:0x23c43429415d8acf3b69703e5037a8497a64883f2217eb8b34b8444982c83f94

**Comment by zhujiayu03** [comment]
0x5751548af950c9b12bdfbb52f1fd0274250b8e6f

**Comment by zhujiayu03** [comment]
Please re-submit your files attached TPT transfer link on [Commit changes].

**Comment by zhujiayu03** [comment]
Please refer to the tutorial and use the checksum contract address as the file name.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Pull request closed without merging**
