### PR TITLE
Add Gin logo and info

### PR DESCRIPTION
**Pull request by hailang47923**

### CODE REVIEW

**Comment by tiaojiaotubiaobaoguo** [comment]
代提交logo，24小时内包过，加QQ：2980874528

**Comment by sammvio** [comment]
Please donate 3000 TPT as required and submit the transfer link on [Commit changes].

**Comment by hailang47923** [comment]
https://hecoinfo.com/tx/0x9a5b4eef0455bea15d8bea2216121718cd2b7db7ed4906d475885da91db77b65

**Comment by hailang47923** [comment]
I resubmitted the merge request (https://github.com/TP-Lab/tokens/pull/4292), and attached a 3000TPT donation link, please help us review it. This token logo has been haunting us for more than a month, thank you.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月26日(星期五) 晚上8:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TP-Lab/tokens] Add Gin logo and info (PR #4078)





 
Please donate 3000 TPT as required and submit the transfer link on [Commit changes].
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
