### PR TITLE
Add ACP LOGO and info

### PR DESCRIPTION
**Pull request by acpTOKEN**
Add ACP LOGO and info
https://bscscan.com/tx/0x781e0b930d71074312097437332aa1a3291ef016ecf43313b6875fe5b2dfc038

### CODE REVIEW

**Comment by opera0001** [comment]
The detection of a proxy contract setting within the token contract is highly concerning. To demonstrate that it poses no harm, it is advisable to provide a report from a reputable code security auditing company.

**Comment by acpTOKEN** [comment]
The ordinary token is the internal disk currency in the DAPP, which does not go to the centralized exchange, is not affected by the transaction, and is not a proxy contract, which may be detected incorrectly

**Comment by acpTOKEN** [comment]
So he doesn't have to say that he hurts anyone, he is only an inner currency, and he won't open it

**Comment by acpTOKEN** [comment]
Hope to review it soon

**Comment by opera0001** [comment]
We will refer to the detection results from goplus, so if you have any questions about this detection, you can contact goplus first and modify the detection results: https://gopluslabs.io/

**Comment by acpTOKEN** [comment]
This contract code does use the proxy contract because he is not circulating in the DEX but in DAPP, so he will display it like this and modify the economic model and mechanism, I hope to review it, thank you very much

**Comment by acpTOKEN** [comment]
And it does not come with any mode, nor will it be upgraded to an agent contract, which is completely safe

**Comment by acpTOKEN** [comment]
There have been similar tokens like this kind of tokens before, and we have submitted such projects, and we have also added a new LOGO

**Comment by opera0001** [comment]
This would be a risky undertaking, so it should not be simply documented. It is recommended to engage in technical communication with GoPlus. Thank you.

**Comment by acpTOKEN** [comment]
I don't think communication is meaningful, because the contract code name of the token is the proxy contract, and the project guarantees that it will not upgrade the contract and cause the impact of the token, because they had a project that was also like this before, and successfully updated the LOGO on TP, I hope you will update it as soon as possible, otherwise how to deal with this matter?

**Comment by acpTOKEN** [comment]
I consulted gopluslabs.io and his reply was: Thats just an attention item.  We didn't clarify it as risky.
    This is just a hint and does not mean that he is at risk

**Comment by acpTOKEN** [comment]
https://docs.gopluslabs.io/reference/response-details

**Comment by acpTOKEN** [comment]
…]()

**Comment by acpTOKEN** [comment]
Please the moderator review and update the LOGO as soon as possible, I have had a technical exchange with GoPlus, there is a chat log, he said that this is just a concern, it does not mean that the token is not safe

**Pull request merged**
