### PR TITLE
ADD MVT logo and info

### PR DESCRIPTION
**Pull request by MVTVIP**

### CODE REVIEW

**Comment by MVTVIP** [comment]
TPT transfer hash

**Comment by MVTVIP** [comment]
BSC  -  MVT  -  0x1F48ccB475ab42235E1FAaaDb0743cADFdD27C35  -  0xa2b39e758cfe278fa37493116536ad31912909b0cdbfe5b5dc09efb12cb327fb

**Comment by MVTVIP** [comment]
https://bscscan.com/tx/0xa2b39e758cfe278fa37493116536ad31912909b0cdbfe5b5dc09efb12cb327fb

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:2980874528

**Comment by sammvio** [comment]
Please re-submit your files to bsc folder

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
