### PR TITLE
Add  Pocket Doge Token Logo

### PR DESCRIPTION
**Pull request by kikigugu**
0xc3cd0cf3371eed8205093b7887d4d026900ec17b533a483c0771d01d959c9ca3

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Please re-submit your files attached TPT transfer link on [Commit changes].

**Comment by kikigugu** [comment]
> Please re-submit your files attached TPT transfer link on [Commit changes].

https://bscscan.com/tx/0xc3cd0cf3371eed8205093b7887d4d026900ec17b533a483c0771d01d959c9ca3

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
