### PR TITLE
Add BTV logo and info

### PR DESCRIPTION
**Pull request by BTVcoin**
https://bscscan.com/tx/0xf6de00f2c1ba792ed432c18851c79bfc06676f96041da33abfef16eb6b7e7aa6

### CODE REVIEW

**Comment by opera0001** [comment]
The submitted logo has size issues and needs to be revised. Please provide it in 256x256 pixels PNG format.

**Comment by BTVcoin** [comment]
I have updated it, please help me check if it is OK. Thank you.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: opera0001 ***@***.***>
发送时间: Friday, June 28, 2024 10:15:21 AM
收件人: TP-Lab/tokens ***@***.***>
抄送: BTVcoin ***@***.***>; Author ***@***.***>
主题: Re: [TP-Lab/tokens] Add BTV logo and info (PR #10752)


The submitted logo has size issues and needs to be revised. Please provide it in 256x256 pixels PNG format.

―

**Comment by BTVcoin** [comment]
Hello, I see the logo has not been displayed, please help me update it, thank you.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Ngan Spinelli ***@***.***>
发送时间: Sunday, June 30, 2024 10:16:47 PM
收件人: TP-Lab/tokens ***@***.***>; TP-Lab/tokens ***@***.***>
抄送: Author ***@***.***>
主题: Re: [TP-Lab/tokens] Add BTV logo and info (PR #10752)

I have updated it, please help me check if it is OK. Thank you.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: opera0001 ***@***.***>
发送时间: Friday, June 28, 2024 10:15:21 AM
收件人: TP-Lab/tokens ***@***.***>
抄送: BTVcoin ***@***.***>; Author ***@***.***>
主题: Re: [TP-Lab/tokens] Add BTV logo and info (PR #10752)


The submitted logo has size issues and needs to be revised. Please provide it in 256x256 pixels PNG format.

―

**Comment by BTVcoin** [comment]
Thanks a lot.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: opera0001 ***@***.***>
发送时间: Monday, July 1, 2024 9:47:16 PM
收件人: TP-Lab/tokens ***@***.***>
抄送: BTVcoin ***@***.***>; Author ***@***.***>
主题: Re: [TP-Lab/tokens] Add BTV logo and info (PR #10752)


Merged #10752<https://github.com/TP-Lab/tokens/pull/10752> into master.

―

**Pull request merged**
