### PR TITLE
ADD GCC LOGO  AND  INFO

### PR DESCRIPTION
**Pull request by GCCtp2**
https://bscscan.com/tx/0x6288eb5da454de7ce829e0cf818604901359b31dea81d8aaabb6bf2a71a4fe7c 0x2b877161b2e746899c0604ca015121ff6cc67b49c0b4d5e972ae90b7f86977fa

### CODE REVIEW

**Comment by GCCtp2** [comment]
I apologize for submitting an incorrect logo earlier, I would like to have it corrected.

**Comment by opera0001** [comment]
I'm very sorry, dear. The order you submitted has already been recorded for a long time, so you can't use this hash value to make new updates.

**Comment by GCCtp2** [comment]
I did reply to you a couple days ago. I had sent you an email when the results appeared, but you did not reply to my email.

**Comment by GCCtp2** [comment]
I just need to adjust "logo.png". Please tell me what to do

**Comment by opera0001** [comment]
Sure, all you need to provide me with is the token contract address and the new logo.

**Comment by GCCtp2** [comment]
logo

0x40c4c2d99347282be92518bc4b4420a1a6b457c4

Above, my contract address and new logo. Please help to replace it. Thank you very much.

**Pull request merged**
