### PR TITLE
add cname info and logo

### PR DESCRIPTION
**Pull request by chloepnc**
thank you

### CODE REVIEW

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by opera0001** [comment]
It is suggested to give up the management authority of the token, and it is detected that there may be a switch setting to control the token transaction.

**Comment by chloepnc** [comment]
what do you mean by   give up the management authority of the token,

opera0001 ***@***.***> 于2022年3月15日周二 10:57写道：

**Comment by chloepnc** [comment]
你个比
你他么
你骗了我qian haiyaolai1

麻痹猪狗不如

542132364 ***@***.***> 于2022年3月18日周五 00:17写道：

**Comment by chloepnc** [comment]
Hey Team,

Thank you for listing cname's logo and info on tp.

We love using tp. 很喜欢使用tp

im cloudname's official personnel. the rest of the listings are not.

By the way, i just got scammed due to last email sent by
***@***.*** for 150usdt. Please fix the loophole where fakers
can know my email address and this email. so that others won't get scammed.

[image: image.png]

Feel free to ask any questions.

Love.

Chloe

posy chen ***@***.***> 于2022年3月15日周二 12:48写道：

**Pull request merged**
