### PR TITLE
Add  GMC  logo

### PR DESCRIPTION
**Pull request by dfsfsgsjh**
https://bscscan.com/tx/0xe03a6d7fa8acc0e41a22aff3c9d54b7992ba96157b2bdf2125fb6668d34a0dc0

### CODE REVIEW

**Comment by nenrgy** [comment]
专业提交logo,代币，白皮书，诚住经营，值得信赖，价格全网最优！QQ:2099728898
Professional submit logo, scrip, white paper, honestly live operation, reliable, the optimal price cut! QQ: 2099728898

**Comment by sammvio** [comment]
Please re-submit your files to bsc folder

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
