### PR TITLE
Add  DRDA logo and info

### PR DESCRIPTION
**Pull request by yuyao8**
https://bscscan.com/tx/0x23b865d60c858608af944dee4e6ace65711c70c7cddb10d1e4145803c83d8883

https://bscscan.com/tx/0x22d2e0d5913838b78801ec885c1bf211fb658ed639681787fb29b661f1023314

### CODE REVIEW

**Comment by opera0001** [comment]
What are the functions of these features?

1. Trading tax can be modified
2. Trading can be suspended
3. Has whitelist feature

**Comment by yuyao8** [comment]
Because I haven't given up my permission yet, and because I haven't started trading yet, it will be normal after opening on the 19th

**Comment by yuyao8** [comment]
May I ask what I should do next?
May I ask if my submission has not been approved?

**Comment by yuyao8** [comment]
This is the first time we have created this avatar. I apologize for not being clear about the process, but after we initiate the transaction, we will discard all permissions

**Pull request merged**
