### PR TITLE
Add NE logo and info 

### PR DESCRIPTION
**Pull request by NEdevelop**
付款哈希 ：https://bscscan.com/tx/0x5df3deb5cc6a4df05f53a12773a6a02be3761c7d24e724eebd10d2f7d5bce737

### CODE REVIEW

**Review by chineseifc — APPROVED** [review]

**Comment by NEdevelop** [comment]
验证哈希：BSC - NE - 0x8a9e646679b9e104d1de8a1e234bfcb5c8e5705f - https://bscscan.com/tx/0x5df3deb5cc6a4df05f53a12773a6a02be3761c7d24e724eebd10d2f7d5bce737

**Comment by NEdevelop** [comment]
验证哈希：https://bscscan.com/tx/0x79a99ed228a809be425ff95595a0e8bb4edbd385ef46b35e3aad9834f88a5518

**Comment by chineseifc** [comment]
@opera0001 please pull it.

**Comment by opera0001** [comment]
image
The submitted file is not saved in the BSC directory, please adjust it again.

**Comment by NEdevelop** [comment]
1

**Comment by NEdevelop** [comment]
> 图像提交的文件未保存在 BSC 目录中，请重新调整。

new pull :https://github.com/TP-Lab/tokens/pull/8605

**Pull request closed without merging**
