### PR TITLE
Add HUNU logo and info

### PR DESCRIPTION
**Pull request by Zhangxh1011**
https://hecoinfo.com/tx/0xbc633bb2515d7bce50fc7d88f005a1a6c2a06657b77d9bfaffa5684da8ab6e10

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:2980874528

**Comment by sammvio** [comment]
Please re-submit your files to bsc folder

**Comment by Zhangxh1011** [comment]
已经重新提交了，请审核一下

**Comment by Zhangxh1011** [comment]
Add logo and info #4725

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
