### PR TITLE
Add TPT logo and info

### PR DESCRIPTION
**Pull request by tanyecong**
https://bscscan.com/tx/0x47d71f44c6df0d8dcfeb214fe11a302a40de82930d563296dc292423f605b348 https://bscscan.com/tx/0x74fdad558b5777bc6a3cbb24169f45f51235a9a71449ecda77be94c7d470cb07

### CODE REVIEW

**Comment by tanyecong** [comment]
在 2023年3月10日 ***@***.***> 写道：


It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

**Comment by tanyecong** [comment]
Token contract code has been made public

**Comment by opera0001** [comment]
The contract address 0xB385cF66FD3AEFd70605E297A79825471E89d32F is not open source, so I cannot check if there are any risks associated with it.

**Comment by opera0001** [comment]
The token contract is still not open source, so unfortunately I have to inform you that the order needs to be closed. You can contact me through issues after you open source it, and remember to include the GitHub order number in your remarks.

https://github.com/TP-Lab/tokens/issues

**Pull request closed without merging**
