### PR TITLE
Add CoinShop logo and info

### PR DESCRIPTION
**Pull request by Csstore**
https://hecoinfo.com/tx/0x3c971a0492eadf11e86bbb31d05249115bc6d9b8c5b7646ac9e8a7f12c825b8a

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Please re-submit the TPT transfer link on [Commit changes].

**Comment by Csstore** [comment]
Why was it closed? what reason？

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
