### PR TITLE
Add TTE logo and info

### PR DESCRIPTION
**Pull request by fightForTornothThunder**
https://bscscan.com/tx/0x13e35361dc22743fd3dac76870937c38e3c7f15d089b9bd2c940fb1f05b2402f

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:2980874528

**Comment by sammvio** [comment]
The contract didn’t verify and published. (No open-source)

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
