### PR TITLE
Add   Monzo  logo

### PR DESCRIPTION
**Pull request by monzo1**
0x0f0a3d149272f4bc3d9179058e903db4beead769af3e1067ec6f1dd2add730af

### CODE REVIEW

**Comment by nenrgy** [comment]
专业提交logo,代币，白皮书，诚住经营，值得信赖，价格全网最优！QQ:2099728898
Professional submit logo, scrip, white paper, honestly live operation, reliable, the optimal price cut! QQ: 2099728898

**Comment by sammvio** [comment]
Please refer to the tutorial and use the checksum contract address.

**Comment by sammvio** [comment]
Please refer to the tutorial, and re-submit your files in the correct format.

**Comment by sammvio** [comment]
Please refer to the tutorial, and re-submit your files in the correct format.

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
