### PR TITLE
add FistKing Logo and info

### PR DESCRIPTION
**Pull request by YFIQ-VIP**
https://bscscan.com/tx/0xd4c6d82bb8f6c253ab167adb43a484296b60328a9a58604bc551da62415ea97c

### CODE REVIEW

**Comment by opera0001** [comment]
1. Low token liquidity
2. It is found that there may be a control transaction switch
3. It is found that there may be retrievable permission codes
Please re submit the logo after adjustment or optimization. Thank you for your support for tokenpocket.

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
