### PR TITLE
Add BOSS logo and info

### PR DESCRIPTION
**Pull request by BOSSUN9999**
BSC-BOSS-0xAE478986C89AFA9203ACBb753c3DfE139C999999-https://bscscan.com/tx/0x065a94980a9eb6afdd044a3ecfa1d969bd95ec40055637796095c94556b19b95

### CODE REVIEW

**Comment by opera0001** [comment]
1. The purchase fee in the token contract is detected to be 100%, please provide an explanation for this.
2. Please remove the extra JSON and logo sections submitted, as they will prevent the order from being merged successfully.
image

**Comment by opera0001** [comment]
image

**Comment by BOSSUN9999** [comment]
The cost of purchasing BOSS tokens is 100%. It is a new business model designed by the bossun project team that only increases but does not decrease.

BOSS tokens are tokens in the bossun project (each participating project address can obtain the smallest unit of BOSS coins). Use BOSS tokens and USDT (Binance) to build LP in pancake. When purchasing LP and withdrawing LP, BOSS coins will be 100% destroyed.

The above is why the fee for purchasing tokens is 100%.

In addition, you mentioned that extra JSON and LOGO need to be deleted. I don't understand what you mean? Do I need to resubmit the request?

Looking forward to your reply.

**Comment by Dictators** [comment]
He said that you should remove the ICONS on the outside of the folder and only keep the two files in the folder named after the contract address

**Pull request closed without merging**
