### PR TITLE
add AVZilla logo and info

### PR DESCRIPTION
**Pull request by LBabyDay**
add AVZilla logo and info

### CODE REVIEW

**Comment by LBabyDay** [comment]
BSC-VDS-0x6ec6a2970a64a7b766f72e68b3a02831dad12069-https://bscscan.com/tx/0x220b80fcc706f8dcca13e2332a0005429e9f686ef5272271eb0258dfa0aa27b6

**Comment by guoxintongsam** [comment]
Please re-submit these tokens separately and attach the TPT transfer link on [Commit changes].

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
