### PR TITLE
ADD SYD logo and info

### PR DESCRIPTION
**Pull request by WZHong666**
SafetyDAO is a set of highly integrated and precise organizational structure, the bottom layer is the protocol layer, the top is the DAO organizational structure layer, then the industry platform layer, the business ecological layer, and the top is the distributed application layer, covering the entire WEB3.0 industry. The core link is completely advanced in all aspects of WEB3.0 from the kernel to the application, from the finance to the industry-----------------https://bscscan.com/tx/0x878770794f172df000b0f6d5a1e5adb41e724000ffa64d10c7fe9b98d879a743----------------0xaf30c2216fd6c34eec0b812d6166b368d141e6239e84d58297aacc73d8e249dc

### CODE REVIEW

**Comment by opera0001** [comment]
It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

**Comment by opera0001** [comment]
I haven't seen your reply after 3 days, so the order needs to be closed, you can contact me through issue.
https://github.com/TP-Lab/tokens/issues

**Comment by WZHong666** [comment]
https://docs.qq.com/pdf/DUEFiSElzV0dJU0l0

**Comment by WZHong666** [comment]
> 3天后我还没有看到你的回复，所以需要关闭订单，你可以通过issue联系我。 https://github.com/TP-Lab/tokens/issues

https://docs.qq.com/pdf/DUEFiSElzV0dJU0l0

**Pull request closed without merging**
