### PR TITLE
Add NEB logo and info

### PR DESCRIPTION
**Pull request by nebgame66**
https://bscscan.com/tx/0x716184d749bce6f5cd9dad1e5353a8de9cf257469b4455833ef359e052442ccd

### CODE REVIEW

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563代提代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by opera0001** [comment]
The token contract source code is not open, so it is impossible to check whether it is secure or provide the security report provided by the security audit. Please adjust and the order will be closed in 24 hours.

**Pull request closed without merging**
