### PR TITLE
Add GSHIB logo and info

### PR DESCRIPTION
**Pull request by cellenkilar**
https://bscscan.com/tx/0x8362fe3da834ec40e0f6e8cde085f6b376a7063c54a69d55cd03aba7ea2520fc

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3076439606

**Comment by sammvio** [comment]
Please submit the checksum address that includes uppercase and lowercase characters.

**Comment by cellenkilar** [comment]
New submit  #4865 thanks！

**Comment by cellenkilar** [comment]
> Please submit the checksum address that includes uppercase and lowercase characters.

0xaA8129726a3cAb188bFAa3993eB7047e9B35aeb2

**Comment by cellenkilar** [comment]
> 请提交包含大小写字符的校验和地址。

New has been submitted #4865 Thanks!

**Comment by cellenkilar** [comment]
> Please submit the checksum address that includes uppercase and lowercase characters.

New has been submitted #4865 Thanks!

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
