### PR TITLE
Add SB logo and info

### PR DESCRIPTION
**Pull request by scarybunnybsc**
https://bscscan.com/tx/0x412ce8bacebc3e856ec7a9a9d7fb5cf30097995fa8be8a4d4eba4349740c01c1 https://bscscan.com/tx/0x115b8309ed9c1d81c4bb658c889ff729d4f0b95c7d3b91d3d8904fe9eca3227a

### CODE REVIEW

**Comment by scarybunnybsc** [comment]
We launching on this SUNDAY

**Comment by scarybunnybsc** [comment]
please update our logo

**Comment by opera0001** [comment]
Please tell me whose address this is: 0x318d9F1Dbd15d9cC8c1C04e0a3a55f17e5490180，It and the black hole address hold 100 percent of the tokens.

**Comment by scarybunnybsc** [comment]
its safu  dev from pinksale
and  token on presale and will launch 15 utc at 13 novmber its mean tomorrow 
https://www.pinksale.finance/launchpad/0x318d9f1dbd15d9cc8c1c04e0a3a55f17e5490180?chain=BSC

**Comment by scarybunnybsc** [comment]
lauched please update it 
https://www.dextools.io/app/en/bnb/pair-explorer/0xe5e45eec4513dd3fe087512b5dba1509e894cd60

**Pull request merged**
