### PR TITLE
ADD COSK LGON AND INFO

### PR DESCRIPTION
**Pull request by XieLong1**
https://bscscan.com/tx/0xf66d0e6cce197ddcb454f3e2d711d5e0c2c5a13089607296fd8db54da0511147

### CODE REVIEW

**Comment by TokenPocket-JAN** [comment]
Speed ​​up the trial. Please reply to the email if you need.
QQ112831047

**Comment by opera0001** [comment]
The ownership of token contract has not been given up, and there is a switch that can control the transaction. Please hurry up and leave us a message on GitHub after adjustment.

**Comment by opera0001** [comment]
1. Administrator privileges are not discarded
2. The transaction can be suspended

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request merged**
