### PR TITLE
Add CD logo and info

### PR DESCRIPTION
**Pull request by zb305107**
转账链接：https://bscscan.com/tx/0x1cd5375fdd051bc2a58b0d711d4779fb60319d7d9a593421ae68af970490c4da
确认链接：https://bscscan.com/tx/0x0b4e32c09b120d9f18c75e153572004d8e9c64b9d4f07bb328ba9b3ded4c8e04

### CODE REVIEW

**Comment by opera0001** [comment]
It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

**Comment by zb305107** [comment]
> It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

已开源
https://polygonscan.com/address/0xcdc1d4304b5c88a1e40f0fa68241bf5dd1816ee4#code

**Comment by opera0001** [comment]
1、Mint function
The contract may contain additional issuance functions, which could maybe generate a large number of tokens, resulting in significant fluctuations in token prices. It is recommended to confirm with the project team whether it complies with the token issuance instructions.

2、Hidden owner
The token has a hidden owner address.For contract with a hidden owner, developer can still manipulate the contract even if the ownership has been abandoned.

3、Tax can be modified
The contract owner may contain the authority to modify the transaction tax. If the transaction tax is increased to more than 49%, the tokens will not be able to be traded (honeypot risk).

**Comment by zb305107** [comment]
> 1、Mint function The contract may contain additional issuance functions, which could maybe generate a large number of tokens, resulting in significant fluctuations in token prices. It is recommended to confirm with the project team whether it complies with the token issuance instructions.
> 
> 2、Hidden owner The token has a hidden owner address.For contract with a hidden owner, developer can still manipulate the contract even if the ownership has been abandoned.
> 
> 3、Tax can be modified The contract owner may contain the authority to modify the transaction tax. If the transaction tax is increased to more than 49%, the tokens will not be able to be traded (honeypot risk).

1、代币计划发布1亿，初始发布100万，剩余的由特定合约根据凭证产出，最多mint至1亿。
2、ower权限仅限于初始设置一次mint权限合约地址(仅限初始化的时候设置一次，由once限制)，以及修改手续费接收地址和分发地址。
3、费率无法变更，合约中没有任何可修改费率的接口。

**Comment by opera0001** [comment]
Please show the code and instructions for hiding the owner permissions section. Thank you.

**Comment by zb305107** [comment]
> Please show the code and instructions for hiding the owner permissions section. Thank you.

```
    function grantOperatorRole(address[2] memory accounts) public onlyRole(DEFAULT_ADMIN_ROLE) {
        require(!once, 'Only once!');
        operators[accounts[0]] = true;
        operators[accounts[1]] = true;
        once = true;
    }

    function setFromDelivers(address[] memory addrs, bool flag) public onlyRole(DEFAULT_ADMIN_ROLE) {
        for(uint i;i<addrs.length;i++){
            isFromDelivers[addrs[i]] = flag;
        }
    }

    function setToDelivers(address[] memory addrs, bool flag) public onlyRole(DEFAULT_ADMIN_ROLE) {
        for(uint i;i<addrs.length;i++){
            isToDelivers[addrs[i]] = flag;
        }
    }

    function setAddress(address _dividend, address _management, address _foundation, address[] memory pools) public onlyRole(DEFAULT_ADMIN_ROLE) {
        dividend = _dividend;
        management = _management;
        foundation = _foundation;
        for(uint i;i<pools.length;i++){
            isFromDelivers[pools[i]] = true;
            isToDelivers[pools[i]] = true;
        }
    }
```
DEFAULT_ADMIN_ROLE 拥有4个权限
grantOperatorRole 初始设置一次mint权限合约地址(仅限初始化的时候设置一次，由once限制)
setFromDelivers 设置分发免手续费地址
setToDelivers 设置接收免手续费地址
setAddress 修改手续费接收地址及设置分发地址

**Pull request merged**
