### PR TITLE
Add SHIBM logo and info

### PR DESCRIPTION
**Pull request by shibaInuMother**
https://hecoinfo.com/tx/0x7c97018e02c19775d45271e28d0122beeba9ca28925c6cb911e3c391a401725f

### CODE REVIEW

**Comment by zhujiayu03** [comment]
logo infringement, please resend your image

**Comment by shibaInuMother** [comment]
Sorry, our logo is designed by ourselves. Where is the infringement? Do you have more detailed information?



---Original---
From: ***@***.***&gt;
Date: Tue, Aug 3, 2021 15:21 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] Add SHIBM logo and info (#1951)




 
logo infringement, please resend your image
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shibaInuMother** [comment]
The picture has been uploaded again. Please review it. Thank you!

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Pull request closed without merging**
