### PR TITLE
Add Father logo and info

### PR DESCRIPTION
**Pull request by dogefa**
https://bscscan.com/tx/0xa3926055d47d1c2e9345a62d649ee89f8fdb2cd6128abfa7b002611891b94e2b

### CODE REVIEW

**Comment by opera0001** [comment]
Token transaction status is abnormal, others meet the requirements, please check.

Please re submit the logo application after adjustment or optimization. Thank you for your support for tokenpocket.

**Comment by dogefa** [comment]
> Token transaction status is abnormal, others meet the requirements, please check.
> 
> Please re submit the logo application after adjustment or optimization. Thank you for your support for tokenpocket.

What is "Token transaction status is abnormal"

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
