### PR TITLE
update info miniShib and logo

### PR DESCRIPTION
**Pull request by jamwili1986**
update info miniShib and logo

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Please re-submit your files attached TPT transfer link on [Commit changes].

**Comment by jamwili1986** [comment]
Fee had pay in here scan, pls check info payment
https://bscscan.com/tx/0x0eb7b170eff08fe92abd69cb3f5feee7f254ccb31f0dca39cde0bc5809a8b18e

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
