### PR TITLE
Add TGR logo and info

### PR DESCRIPTION
**Pull request by jingyukxy**
https://bscscan.com/tx/0xd7d872b39e8c33193ccb14d47cada367e57ad6b080e39f4c35032775f9cf8377 https://bscscan.com/tx/0x3f41925552d62fa155772e5dfd76bec95c5c7fa23d4427a7c2f80c02c9c49218

### CODE REVIEW

**Comment by opera0001** [comment]
Detected that tokens can increase issuance, please explain what it does.

**Comment by jingyukxy** [comment]
the owner privileges already dropped on this token contract , so please check again, thanks

**Comment by jingyukxy** [comment]
> increase

the owner privileges already dropped on this token contract , so please check again, thanks

**Comment by jingyukxy** [comment]
> Detected that tokens can increase issuance, please explain what it does.

the owner privileges already dropped on this token contract , so please check again, thanks

**Pull request merged**
