### PR TITLE
Add RPO logo and info

### PR DESCRIPTION
**Pull request by 15896209474**
https://hecoinfo.com/tx/0x1200d070ff98f8930e0813ff1a89ab16246dab261690efa71db737e1169f1d37

### CODE REVIEW

**Comment by tubiaoyingji** [comment]
专业加快提交LOGO，20分钟内审核包过，QQ：1450001284

**Comment by sammvio** [comment]
Please re-submit these tokens separately and attach the TPT transfer link on [Commit changes].

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
