### PR TITLE
Add PIGKING logo and info

### PR DESCRIPTION
**Pull request by htlotto**
https://bscscan.com/tx/0xfe5bd5daedc45af00a5c945c5343a1b6ed01434f32884dd5eaaa3bd84d26585d

### CODE REVIEW

**Comment by opera0001** [comment]
1. Suspected blacklist permissions found
2. The ownership is suspected to be copied and there are potential safety hazards
Please resubmit the logo application after modification or optimization. Thank you for your support for tokenpocket.

**Comment by htlotto** [comment]
> 1. Suspected blacklist permissions found
> 2. The ownership is suspected to be copied and there are potential safety hazards
>    Please resubmit the logo application after modification or optimization. Thank you for your support for tokenpocket.

Hello, I have given up ownership and have no permission to set a blacklist.
Renounce Ownership link: https://bscscan.com/tx/0x79f0a7a94d722e237a7e5bdd2553b3f3b911b93579b4cb4b25a43002c1ed880b[](https://github.com/htlotto)

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
