### PR TITLE
ADD BES LOGO AND INFO

### PR DESCRIPTION
**Pull request by ArnoWl**
This is the transaction link address for the donation TPT record
https://bscscan.com/tx/0x6ecb8fefbf21052255a7586ad371bfec625c735c7493416a0d06e0be95fca7cc

### CODE REVIEW

**Comment by opera0001** [comment]
Please check the number of TPT donations.

**Comment by ArnoWl** [comment]
Export quantity 1000TPT
WechatIMG633
WechatIMG634

**Comment by ArnoWl** [comment]
tpt: https://bscscan.com/tx/0x6ecb8fefbf21052255a7586ad371bfec625c735c7493416a0d06e0be95fca7cc
bnb:https://bscscan.com/tx/0x3b3c9ab401926ea24941e9d1cc9674fbaf84bef0b511f978f99cb65d70fd86e7

**Comment by ArnoWl** [comment]
> Please check the number of TPT donations.

https://bscscan.com/tx/0x6ecb8fefbf21052255a7586ad371bfec625c735c7493416a0d06e0be95fca7cc
https://bscscan.com/tx/0x3b3c9ab401926ea24941e9d1cc9674fbaf84bef0b511f978f99cb65d70fd86e7

**Comment by opera0001** [comment]
CN：https://help.tokenpocket.pro/cn/developer/submit-logo

EN：https://help.tokenpocket.pro/en/developer/how-to-submit-a-token-logo#steps-of-adding-a-token-logo-info

Please check the tutorial for the TPT quantity requirements. Thank you.

**Comment by ArnoWl** [comment]
TPT：https://bscscan.com/tx/0x65e4bbb996824327f88f7fef605cd689880e3d267acb640c7efe05cfb710f873
BNB：https://bscscan.com/tx/0x51b2e8f615e372d267ce1f4ee8079930e7c4e14a3f20e33b7761b2f8697c5cd2

**Comment by ArnoWl** [comment]
> CN：https://help.tokenpocket.pro/cn/developer/submit-logo
> 
> EN：https://help.tokenpocket.pro/en/developer/how-to-submit-a-token-logo#steps-of-adding-a-token-logo-info
> 
> Please check the tutorial for the TPT quantity requirements. Thank you.

TPT：https://bscscan.com/tx/0x65e4bbb996824327f88f7fef605cd689880e3d267acb640c7efe05cfb710f873
BNB：https://bscscan.com/tx/0x51b2e8f615e372d267ce1f4ee8079930e7c4e14a3f20e33b7761b2f8697c5cd2

**Pull request merged**
