### PR TITLE
Add GFI logo and info

### PR DESCRIPTION
**Pull request by GameFoxSpace**
https://bscscan.com/tx/0x46ee8403d486268dd32b274cccdaf08659d9347521a67554061dd87641016bbe

### CODE REVIEW

**Comment by tiaojiaotubiaobaoguo** [comment]
代提交logo，24小时内包过，加QQ：2980874528

**Comment by sammvio** [comment]
Please refer to the tutorial, and re-submit your files in the correct format.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
