### PR TITLE
Add PNC logo and info

### PR DESCRIPTION
**Pull request by anthonycolj4y**
BSC-PNC-0xaac8A6e94F62F8Bd0aF54863D4C19100B7401C78-https://bscscan.com/tx/0xe516a077f6380c81ca057ac3a72cbb37c6dc0e92e9a54752caf2684d1fe51219

### CODE REVIEW

**Comment by opera0001** [comment]
image

The submission location here is still incorrect. Please adjust it and place the JSON and PNG files in the token contract address folder, then upload them to the BSC directory.

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Comment by anthonycolj4y** [comment]
BSC-PNC-0xaac8A6e94F62F8Bd0aF54863D4C19100B7401C78-https://bscscan.com/tx/0xe516a077f6380c81ca057ac3a72cbb37c6dc0e92e9a54752caf2684d1fe51219

PNC Contract Address 0xaac8A6e94F62F8Bd0aF54863D4C19100B7401C78

________________________________

**Comment by anthonycolj4y** [comment]
https://github.com/anthonycolj4y/tokens/commit/2deff1f378d8ab919a2972b54c7671abfc1c2ef3
[https://opengraph.githubassets.com/ee3e6b10707854f7f646328033c235d5576cc2c6e3e04354e14c888c9307d0e7/anthonycolj4y/tokens/commit/2deff1f378d8ab919a2972b54c7671abfc1c2ef3]<https://github.com/anthonycolj4y/tokens/commit/2deff1f378d8ab919a2972b54c7671abfc1c2ef3>
Add PNC logo and info · ***@***.***<https://github.com/anthonycolj4y/tokens/commit/2deff1f378d8ab919a2972b54c7671abfc1c2ef3>
BSC-PNC-0xaac8A6e94F62F8Bd0aF54863D4C19100B7401C78-https://bscscan.com/tx/0xe516a077f6380c81ca057ac3a72cbb37c6dc0e92e9a54752caf2684d1fe51219
github.com

________________________________

**Pull request merged**
