### PR TITLE
Add mxdao and info

### PR DESCRIPTION
**Pull request by ABCERT1**

### CODE REVIEW

**Comment by opera0001** [comment]
The project does not give up administrative privileges, there also seems to be a design logic that you can get back after giving up privileges, and there is also a setting that tokens can be suspended, please check and explain the situation.

**Comment by ABCERT1** [comment]
Then what should I do to submit successfully and display the logo




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TP-Lab/tokens"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月18日(星期四) 下午4:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TP-Lab/tokens] Add mxdao and info (PR #8042)





 
The project does not give up administrative privileges, there also seems to be a design logic that you can get back after giving up privileges, and there is also a setting that tokens can be suspended, please check and explain the situation.

**Comment by opera0001** [comment]
Check the code according to the problem that prompted you, this problem needs to be adjusted from your side.

**Comment by opera0001** [comment]
I don't see a reply or change after 2 days, so the order needs to be closed, you can contact me through issues, thanks.

Link: https://github.com/TP-Lab/tokens/issues

**Comment by ABCERT1** [comment]
我现在提交的是代码错误吗 还是合约的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TP-Lab/tokens"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月20日(星期六) 中午12:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TP-Lab/tokens] Add mxdao and info (PR #8042)





 
根据提示你的问题检查代码，这个问题需要你自己调整。
 
—
直接回复此邮件，在 GitHub 上查看，或取消订阅。
您收到此消息是因为您编写了该主题。Message ID: ***@***.***&gt;

**Pull request closed without merging**
