### PR TITLE
Add LittlePony logo and info

### PR DESCRIPTION
**Pull request by LittlePonyOfficial**
https://www.bscscan.com/tx/0x81184f5e977d9e422e5ca8d4c36ffb3aee9942bee4b2f3476c882af8d2fad4e7

### CODE REVIEW

**Comment by LittlePonyOfficial** [comment]
https://www.bscscan.com/tx/0x81184f5e977d9e422e5ca8d4c36ffb3aee9942bee4b2f3476c882af8d2fad4e7

**Comment by zhujiayu03** [comment]
Please refer to the tutorial and use the checksum contract address.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
