### PR TITLE
ADD FLB logo and info

### PR DESCRIPTION
**Pull request by fishinglifenft**
https://bscscan.com/tx/0x637f5c1e97e71110ba05db1da94525fc256a0168544aa13b73ea36918a468275

### CODE REVIEW

**Comment by logobaoguo** [comment]
专业提交logo！加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by sammvio** [comment]
Please refer to the tutorial, and re-submit your files in the correct format.

**Comment by fishinglifenft** [comment]
What's wrong with the file?

SS ***@***.***> 于2022年1月15日周六 09:53写道：

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
