### PR TITLE
Add DRU logo and info

### PR DESCRIPTION
**Pull request by DenDengDenDengDen**
https://bscscan.com/tx/0x1a4ae0060485b58ce57b197a94bb39b09b2934d8e88c43fab1381e65e8acfad7/

### CODE REVIEW

**Comment by DenDengDenDengDen** [comment]
https://bscscan.com/tx/0x1a4ae0060485b58ce57b197a94bb39b09b2934d8e88c43fab1381e65e8acfad7

**Comment by logobaoguo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by sammvio** [comment]
The contract doesn’t verify and published. (No open-source)

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
