### PR TITLE
Add PECA logo and info

### PR DESCRIPTION
**Pull request by cwf404**
BSC-TPT-0x47b5733b6714396397f5d861a5256933240b06587d113240247c727a4f054d5e-https://bscscan.com/tx/0x47b5733b6714396397f5d861a5256933240b06587d113240247c727a4f054d5e

### CODE REVIEW

**Comment by opera0001** [comment]
image
1、The submitted file is not saved in the BSC directory, please adjust it again.
2、It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

**Comment by cwf404** [comment]
Updated, please review

**Comment by opera0001** [comment]
The submitted file is not saved in the BSC directory, please adjust it again.

**Comment by opera0001** [comment]
I don't see a reply or change after 2 days, so the order needs to be closed, you can contact me through issues, thanks.

Link: https://github.com/TP-Lab/tokens/issues

**Pull request closed without merging**
