### PR TITLE
Add SW Logo and Info

### PR DESCRIPTION
**Pull request by doylek309**
TPT:
https://bscscan.com/tx/0xb60dbc58b297af8e469cde3671c33f7ef47c95761bd78f52313d7033ae8e1151
BNB:
https://bscscan.com/tx/0xe6ea255e23b2d460acb61e518dbab384fb631a6000765fb9251f022b30952775

### CODE REVIEW

**Comment by doylek309** [comment]
Hi admin, this pull request has last for 2 days, could you plz help to review it? Thanks for your help.

**Comment by opera0001** [comment]
It is detected in the token contract that there may be a switch setting to control the circulation of tokens. Please explain.

**Comment by doylek309** [comment]
Hi admin, reply as below, plz review again:

1. The first time the project opened due to the high popularity of the project, 17 robots entered, so the project party could not add the pool, but the holding address has reached 30,000 + the contract address is 0x384d7df8bfd93c96d5059ab678ecbe4d9f0563bc
2. After the contract was exchanged, the pool was added in advance, and then the transaction was opened directly at the time. In this case, the time of adding the pool can be queried.
3. SW Token is the blue ocean ecological application token, and there will be no suspension of transactions during the process.
4. 0x81afd511565cfd8384679fcec1b39ba9798de543 sw is the second token of the blue ocean ecology after KW, because the application value of kw is very high, and then sw plans to enter the game landing entity in the next step, so there is bound to be a relatively high value-added space.

Thank you.

**Comment by doylek309** [comment]
Hi admin, could you plz check this request again? Looking forward to your reply.

**Comment by opera0001** [comment]
Sorry, this is a very risky decision, so we choose to reject the collection. If you can discard the administrator permission later, you can apply again. The TPT hash value you submitted can be reused in future submissions.

**Pull request closed without merging**
