### PR TITLE
Add AFPT logo and info

### PR DESCRIPTION
**Pull request by mikechen1635**
Add AFPT logo and info

### CODE REVIEW

**Comment by opera0001** [comment]
Please check the TPT quantity.

**Comment by mikechen1635** [comment]
I have sent 5000 TPTs, right?

**Comment by opera0001** [comment]
Yes, please check the specific tutorial content.

CN：https://tphelp.gitbook.io/cn/wallet-operation/submit-token
EN：https://help.tokenpocket.pro/en/developer/how-to-submit-a-token-logo#steps-of-adding-a-token-logo-info

**Comment by mikechen1635** [comment]
It has been submitted, address:
https://github.com/mikechen1635/tokens/commit/0d0d8dcb1593df765e9658fb6116ccf7c31dfa73

**Comment by mikechen1635** [comment]
I has been resubmitted

**Pull request closed without merging**
