### PR TITLE
 Add Info and Logo

### PR DESCRIPTION
**Pull request by TokenLogos**
https://bscscan.com/tx/0x4cde9bf7a2b7d9bbb77c511610257ce4311b30e5abaf52c64574bf3280f90b53

### CODE REVIEW

**Comment by TokenLogos** [comment]
1. This contract should used in Dapp, So need control to setting excluded Fees
    Dapp’s website is 'https://www.bj1913.com'.

2. Dapp is lp earn BJ and USDT.
    So dapp should the user's CAKE-LP permission and deposit lp to dapp’s contract.

3. Because Dapp’s contract should excluded Fees from BJ, So need control to setting excluded Fees.

**Comment by giki0318** [comment]
According to the DAO, the donation amount for a logo update has been updated to 30,000 TPT. [Click here for Details](https://snapshot.org/#/tptdao.eth/proposal/0x781abc1ade2ebd082aec4f57b7199d472a2b2850b3df46c8ec37e3b6a1a243c2)

**Comment by TokenPocket-JAN** [comment]
Professional expedited review. Please reply to the email if you need.
QQ112831047

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
