### PR TITLE
add Sdoge info and logo

### PR DESCRIPTION
**Pull request by DOUSENCAI**
TPT https://bscscan.com/tx/0x47ed7e470fa41972eeee42a8cc0f114e1e9a5cdb9c91cdec7d482d5c61260bf9
BNB https://bscscan.com/tx/0x1e427cb4869b361f8763aed537997f3459092fcc01335715fb62c074c18a5f2f

### CODE REVIEW

**Comment by DOUSENCAI** [comment]
BSC-Sdoge-0x413561e212de90a870debf83ae149f307ec2ba45-https://bscscan.com/tx/0x47ed7e470fa41972eeee42a8cc0f114e1e9a5cdb9c91cdec7d482d5c61260bf9

**Comment by DOUSENCAI** [comment]
Sdoge:
BSC-Sdoge-0x413561e212de90a870debf83ae149f307ec2ba45-https://bscscan.com/tx/0x47ed7e470fa41972eeee42a8cc0f114e1e9a5cdb9c91cdec7d482d5c61260bf9

**Comment by DOUSENCAI** [comment]
https://github.com/DOUSENCAI/tokens/blob/master/bsc/0x413561e212dE90A870DEbf83aE149F307Ec2BA45/logo.png?raw=true-Sdoge-https://bscscan.com/tx/0x47ed7e470fa41972eeee42a8cc0f114e1e9a5cdb9c91cdec7d482d5c61260bf9

**Comment by DOUSENCAI** [comment]
https://github.com/DOUSENCAI/tokens/blob/master/bsc/0x413561e212dE90A870DEbf83aE149F307Ec2BA45/logo.png?raw=true-Sdoge-https://bscscan.com/tx/0x47ed7e470fa41972eeee42a8cc0f114e1e9a5cdb9c91cdec7d482d5c61260bf9

**Comment by zhujiayu03** [comment]
Added

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Pull request closed without merging**
