### PR TITLE
Add LilFloki logo and info

### PR DESCRIPTION
**Pull request by a5550452**
https://bscscan.com/tx/0xa793fbbb2e7e8e8cb7f473c2a408f3af0d9235df6587c2a352db95f1d2a931f8

### CODE REVIEW

**Comment by a5550452** [comment]
Note：Add LilFloki logo and info

1000TPT-https://bscscan.com/tx/0xa793fbbb2e7e8e8cb7f473c2a408f3af0d9235df6587c2a352db95f1d2a931f8

contract MyToken
{
 "name": "LilFloki Token",
 "website": "https://bscscan.com/token/0xff558dfae37f988daa06b8b8cfd0fb8956e931a0",
 "description": "LilFloki TOKEN.",
 "explorer": "https://bscscan.com/token/0xff558dfae37f988daa06b8b8cfd0fb8956e931a0",
 "type": "BEP20",
 "symbol": "LNG",
 "decimals": 4,
 "status": "active",
 "id": "0xff558dfae37f988daa06b8b8cfd0fb8956e931a0"
}

Thank you for your

**Comment by tubiaoyingji** [comment]
专业加快提交LOGO，20分钟内审核包过，QQ：1450001284

**Comment by sammvio** [comment]
Please donate 3000 TPT as required and submit the transfer link on [Commit changes].

**Comment by a5550452** [comment]
> Please donate 3000 TPT as required and submit the transfer link on [Commit changes].

hello I am paying 3000 TPT now. Can you help me get through? Or do I need to resubmit it?

**Comment by a5550452** [comment]
> Please donate 3000 TPT as required and submit the transfer link on [Commit changes].

To resubmit 3000 TPT-https://bscscan.com/tx/0x0a7e64b48dbbac72904396ed4276dde26232a512a86aa4b4a3bda4d527eccf54

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
