### PR TITLE
Add DEM logo and info

### PR DESCRIPTION
**Pull request by crazyfarm345**
https://bscscan.com/tx/0x8a7d4c2ac984b1b5bcf52cf6ab6071ff3ec76e3fad961b216c148ec3d3309f3c

### CODE REVIEW

**Comment by opera0001** [comment]
1. 99.99% of LP liquidity is provided by one address, which is unlocked and may be at risk
2. The capital pool is not locked, which may be at risk
Please submit the token logo application after readjustment or optimization. Thank you for your support for tokenpocket.

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
