### PR TITLE
Add GOCP logo and currency transfer information

### PR DESCRIPTION
**Pull request by tl2215689**
Add GOCP logo and info
Official contact email ：gocp@gocp.xyz
Social profile:
Reddit： https://www.reddit.com/r/popular/
Facebook： https://m.facebook.com/profile.php
telegraph：https://t.me/AgSwapDex
Twitter：https://mobile.twitter.com/home

logo

[GOCP生态链 白皮书 EN.pdf](https://github.com/TP-Lab/tokens/files/6950412/GOCP.EN.pdf)

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Please re-submit your files attached TPT transfer link on [Commit changes].

**Comment by tl2215689** [comment]
好的


 
---Original---
From: ***@***.***&gt;
Date: Thu, Aug 12, 2021 10:56 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] Add GOCP logo and currency transfer information (#2257)




 
Please re-submit your files attached TPT transfer link on [Commit changes].
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tl2215689** [comment]
那个tpt转账记录提交了，麻烦审核通过下


 
---Original---
From: ***@***.***&gt;
Date: Thu, Aug 12, 2021 10:56 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] Add GOCP logo and currency transfer information (#2257)




 
Please re-submit your files attached TPT transfer link on [Commit changes].
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tl2215689** [comment]
你好，那个tpt的转账记录发过去了，什么时候可以审核通过啊


 
---Original---
From: ***@***.***&gt;
Date: Thu, Aug 12, 2021 10:56 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] Add GOCP logo and currency transfer information (#2257)




 
Please re-submit your files attached TPT transfer link on [Commit changes].
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
