### PR TITLE
Add SER logo and info

### PR DESCRIPTION
**Pull request by serchats**
https://bscscan.com/tx/0x7b0c6c2f9059a85c50b64cea83b43b013868a87956f961f6fec298a5951695b0

### CODE REVIEW

**Comment by opera0001** [comment]
1. Contract not open source
2. No capital flow pool found
Please submit the token logo application after readjustment or optimization. Thank you for your support for tokenpocket.

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
