### PR TITLE
Add OSK logo and info

### PR DESCRIPTION
**Pull request by mangoshen**
https://bscscan.com/tx/0x5282e3c6a39c680d1689b84289367e449fac6e4238770424ece623b865735ebd

### CODE REVIEW

**Comment by opera0001** [comment]
A GitHub account can only submit one logo application, and the logo of Tron cannot be included temporarily.
0x04fA9Eb295266d9d4650EDCB879da204887Dc3Da--
The token contract control right is not discarded, and there is a function that can retrieve the control right. Please explain or adjust.

**Comment by mangoshen** [comment]
这个是bep20呀，TPT都已经转了
请明确说明问题所在



---Original---
From: ***@***.***&gt;
Date: Sun, Mar 6, 2022 09:10 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] Add OSK logo and info (PR #6030)




 
A GitHub account can only submit one logo application, and the logo of Tron cannot be included temporarily.
 0x04fA9Eb295266d9d4650EDCB879da204887Dc3Da--
 The token contract control right is not discarded, and there is a function that can retrieve the control right. Please explain or adjust.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mangoshen** [comment]
一个管理员权限，因代币规则最好持仓为1000枚，管理员用于添加白名单



---Original---
From: ***@***.***&gt;
Date: Sun, Mar 6, 2022 09:10 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] Add OSK logo and info (PR #6030)




 
A GitHub account can only submit one logo application, and the logo of Tron cannot be included temporarily.
 0x04fA9Eb295266d9d4650EDCB879da204887Dc3Da--
 The token contract control right is not discarded, and there is a function that can retrieve the control right. Please explain or adjust.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mangoshen** [comment]
Apply to update the token logo to bep20 non tronThe administrator explained that the maximum position of tokens is 1000Therefore, the administrator is required to add the white list



---Original---
From: ***@***.***&gt;
Date: Sun, Mar 6, 2022 09:10 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] Add OSK logo and info (PR #6030)




 
A GitHub account can only submit one logo application, and the logo of Tron cannot be included temporarily.
 0x04fA9Eb295266d9d4650EDCB879da204887Dc3Da--
 The token contract control right is not discarded, and there is a function that can retrieve the control right. Please explain or adjust.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mangoshen** [comment]
拉去多了，OSK是本次需要提交的，请管理员看到回复

**Comment by opera0001** [comment]
The logo is very similar to the main body of the OSK icon on Tron. Please explain or replace other logos.

**Comment by opera0001** [comment]
The logo is very similar to the main body of the OSK icon on Tron. Please explain or replace other logos.

**Comment by mangoshen** [comment]
TRON cannot meet the expansion demand, so BEP20 needs to be prepared in advance as the later migration plan.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TP-Lab/tokens"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月8日(星期二) 下午5:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TP-Lab/tokens] Add OSK logo and info (PR #6030)





 
The logo is very similar to the main body of the OSK icon on Tron. Please explain or replace other logos.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by opera0001** [comment]
The reputation of OSK is not very good now, which may involve some laws and regulations, so we consider not including it for the time being. I'm very sorry.

**Comment by opera0001** [comment]
The management authority of token contract is not discarded, which may pose a certain risk.

**Pull request closed without merging**
