### PR TITLE
Add Catking logo and info 

### PR DESCRIPTION
**Pull request by dhz5980089**
https://bscscan.com/tx/0x6784acb2da19e3308809f86713c0aa2110ff896ec06b8fd359130385dce245dc

### CODE REVIEW

**Comment by opera0001** [comment]
1. Insufficient liquidity of capital pool
2. There are no other operations after the issuance of tokens, and the liquidity channel of tokens is unclear
3. The logo icon has obvious deformation, which is very unsightly
Please re submit the logo application after adjustment or optimization. Thank you for your support for tokenpocket

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
