### PR TITLE
Add SNFT logo and info

### PR DESCRIPTION
**Pull request by soulnftx**
BSC-SNFT-0x2F5d726C2c8c939FA17e1EA36406877e4D53594b- https://bscscan.com/tx/0x9ca07e26a54435ebf4ed4ecef8f22798c4cc0657e81e83cbfe5df1b18ef0e00f

### CODE REVIEW

**Comment by opera0001** [comment]
1. Contract control is not discarded
2. Transaction discovery can be controlled
3. Find a function that can retrieve ownership
4. TPT donation needs to supplement the difference
Please adjust

**Comment by soulnftx** [comment]
Hello, please tell me, 1-2-3, what does it all mean? In addition, I paid 3000 TPT, do I still need to pay? How much TPT do I need to pay? thanks

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

------- Original Message -------
2022年3月2日 星期三 上午 11:20，opera0001 ***@***.***> 来信：

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
