### PR TITLE
add MIST LOGO and info 

### PR DESCRIPTION
**Pull request by huayi198**
https://bscscan.com/tx/0xd0500a8125eafb0f3f354b01062aa8081c8d65bfa2eca2fe79d8a51e7d2778ad

Is on the BSC chain

### CODE REVIEW

**Review by huayi198 — COMMENTED** [review]
add CMPY logo

**Comment by huayi198** [comment]
please         add CMPY logo       and     add    MIST  logo     
thank you

**Comment by guoxintongsam** [comment]
Please re-submit these tokens separately and attach the TPT transfer link on [Commit changes].

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
