### PR TITLE
Add PPL logo and info

### PR DESCRIPTION
**Pull request by PinkPantherOfficial**
https://bscscan.com/tx/0xfd4c3dc4d7cd14c489858ab2d6835ff2d55b6fb61af6ceee5502f060c20820e0
https://bscscan.com/tx/0xd91656e5cd41b4888b56c3b6cf456a4afa7844036cf4a25ee072090ba76aa3ff

### CODE REVIEW

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Comment by inmefinance** [comment]
why this token mark risk ?

**Comment by inmefinance** [comment]
why you mark this token risk ? if its 100% clean ?

**Comment by inmefinance** [comment]
https://www.pinksale.finance/pinklock/detail/0xf642f0851f27ef4351183363c7e3d0ae7e1b7700?chain=BSC

proof of lock

**Comment by inmefinance** [comment]
proof of contract clean 100 %
https://gopluslabs.io/token-security/56/0x8b6da8506623aa995faf3e604ba512b511ec0b65

**Comment by VENOOfficial** [comment]
pls deal with it soon, and remove the risky mark, the token is safu, why it has risky mark?

**Comment by VENOOfficial** [comment]
pls deal with the logo soon, thx very much

**Comment by PinkPantherOfficial** [comment]
pls deal with the logo soon, thx very much

**Pull request merged**
