### PR TITLE
Add CML-T logo and info

### PR DESCRIPTION
**Pull request by Yantaiowig2**
https://bscscan.com/tx/0x816c5498a54c6d5e9bc08fb30370cebfa3ea6c50efcdfe74465d94e0db974d0b https://bscscan.com/tx/0xb9f9684b1cdc0c6ad603b519a959d13beb15c30d5e4d28de763be10045ddfe8f

### CODE REVIEW

**Comment by opera0001** [comment]
It has been detected that the contract contains a function to increase the token supply. Please provide an explanation for this.

**Comment by Yantaiowig2** [comment]
Project tokens are minted slowly, not all at the beginning.

**Comment by Yantaiowig2** [comment]
> 已经检测到该合约包含增加代币供应量的功能。请对此提供解释。

Project tokens are minted slowly, not all at the beginning.

**Comment by Yantaiowig2** [comment]
> It has been detected that the contract contains a function to increase the token supply. Please provide an explanation for this.

The current circulation of tokens is only 30, which were issued during the test period.

**Comment by Yantaiowig2** [comment]
> It has been detected that the contract contains a function to increase the token supply. Please provide an explanation for this.

Project tokens are minted slowly, not all at the beginning.
The current circulation of tokens is only 30, which were issued during the test period.

**Pull request merged**
