### PR TITLE
add benz token and info

### PR DESCRIPTION
**Pull request by zzz131519**
BSC-BENZ-0xAcFA30bB44BCEdDE6bF9b5cAC8BC2841e7ed1A82-0x4c6ef0b69bb46719201dff6e32afb3e19aad762f89ab97c637bdfb203428b9b0

### CODE REVIEW

**Comment by opera0001** [comment]
The submitted logo is suspected of infringement and is not recommended.

**Comment by jjjgjk** [comment]
你好

**Comment by tplogotijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
