### PR TITLE
Add DFT logo and info

### PR DESCRIPTION
**Pull request by DragonFruit001**
https://bscscan.com/tx/0xef5b327feb19f759cfc35255d1c9e6f0d47c384e5c289c8f7206dedfbbe4f549

https://bscscan.com/tx/0x15a1f956abf9b18f825fe796d0302d92e9b5e73207c3f20b8ea43f817fef9cc5

### CODE REVIEW

**Comment by DragonFruit001** [comment]
thanks

**Comment by DragonFruit001** [comment]
please review

**Comment by opera0001** [comment]
The presence of a function to suspend token transactions is detected, please explain what he does.

**Comment by DragonFruit001** [comment]
> 

Trading is suspended to prevent bots while adding pools.  After the information is updated, we will drop permissions

**Comment by DragonFruit001** [comment]
> The presence of a function to suspend token transactions is detected, please explain what he does.

The trading suspension is mainly used to solve the problem of adding a liquidity pool to prevent robots from brushing orders


The information on the BSC chain has not been updated, and the management authority will be discarded after the update is completed.

**Pull request merged**
