### PR TITLE
Captain Punk logo

### PR DESCRIPTION
**Pull request by dohouse**
paid 3000 TPT link:  https://bscscan.com/tx/0x7fd155aa7fcbda88e3fbf37f159f3ef8a182afee427e22f1e999c6684800218b

### CODE REVIEW

**Comment by tiaojiaotubiaobaoguo** [comment]
代提交logo，24小时内包过，加QQ：2980874528

**Comment by dohouse** [comment]
非常感谢. 我弄好基本点信息后给您联系.
Tianqi (TQ) Wang Email: ***@***.*** 

    On Saturday, November 20, 2021, 04:56:58 AM EST, tiaojiaotubiaobaoguo ***@***.***> wrote:  
 
 


代提交logo，24小时内包过，加QQ：2980874528

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by dohouse** [comment]
太好了。非常感谢。需要支付多少个TPT？


发自 iPhone 版 Yahoo 邮箱


星期日, 三月 13, 2022, 7:35 下午 于 touxiangtijiao ***@***.***>写道：




快速提交tp头像2小时内包过，需要联系QQ：2651964563

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request merged**
