### PR TITLE
Add AMC logo and info

### PR DESCRIPTION
**Pull request by AIMetaClub**

### CODE REVIEW

**Comment by AIMetaClub** [comment]
Arbitrum Setp5 TX Hash Link: https://bscscan.com/tx/0xf1402e41f7d324bea0c3dedbb0d6cfa41add7e36e9c2ccb992dba596e8409eb0

BSC Setp5 TX Hash Link: https://bscscan.com/tx/0x3455e0522811716a37b15316e9997821aebe0d5e847eb15fab27d30dfa832230

**Comment by opera0001** [comment]
The submitted Arbitrum token contract is not open source, please check.

**Comment by opera0001** [comment]
The submitted Arbitrum token contract is not open source, please check.

**Comment by opera0001** [comment]
One account can only submit one token logo application, bsc's token logo has been included, please submit Arbitrum's token again, thank you.

**Pull request merged**
