### PR TITLE
Add MAT logo and info

### PR DESCRIPTION
**Pull request by mattoken**
https://bscscan.com/tx/0x21f5f04f00b2ecd080cb152458bb4c956323d0216c219328e52d7f91ac3c9805

### CODE REVIEW

**Comment by tiaojiaotubiaobaoguo** [comment]
代提交logo，24小时内包过，加QQ：2980874528

**Comment by sammvio** [comment]
The contract didn’t verify and publish. (No open-source)

**Comment by mattoken** [comment]
> The contract didn’t verify and publish. (No open-source)

sorry , I forgot it , it's opened now!!! ,please again, thanks

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
