### PR TITLE
Upload POTC logo and info

### PR DESCRIPTION
**Pull request by SMN999**
https://bscscan.com/tx/0x913a158ee9f1b2768ef49ffe29dbfc6cec6e9348a1b7d7e7677553cc1af256e8 
We have implemented a mechanism where tokens are sourced from gifts and are not encouraged to buy or sell, so tokens are only allowed to buy in small quantities. Please review! 
Thanks.

### CODE REVIEW

**Comment by opera0001** [comment]
Haven't started trading yet?

**Comment by Fma999** [comment]
The transaction has already started.

**Comment by opera0001** [comment]
The buying cost requires a 90% slippage, why is that?

**Comment by Fma999** [comment]
The buying cost requires a 90% slippage, We have implemented a mechanism where tokens come from gifts and are not encouraged to be purchased, so tokens are only allowed to be purchased in small quantities.
Thanks.

**Pull request closed without merging**
