### PR TITLE
Add 1HT logo And info

### PR DESCRIPTION
**Pull request by TaurusCoin988**
https://hecoinfo.com/tx/0xada65e471d82102f0f1f3c056deb8bb0f2ceae56cd81f68fb6ae850cfa581eac

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Please re-submit your files to heco folder

**Comment by TaurusCoin988** [comment]
I've added it to the heco folder




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月3日(星期五) 中午12:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TP-Lab/tokens] Add 1HT logo And info (#3014)





 
Please re-submit your files to heco folder
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
