### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by gcy1105**

### CODE REVIEW

**Comment by gcy1105** [comment]
logo update

**Comment by gcy1105** [comment]
Add logo & json

**Comment by gcy1105** [comment]
https://bscscan.com/tx/0x02b6e376ced5be31ee00e88b3ace2c79c54368f43504c36faaa308f6fdccad9d

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Pull request merged**
