### PR TITLE
Add BOSEBIT Logo and info.json

### PR DESCRIPTION
**Pull request by Leo900805**
https://bscscan.com/tx/0x9338eb6880a08f351456db56aa2d07f6483880eebcdd9347fc623beb62fdefa2

### CODE REVIEW

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Comment by ZHIHAN1987** [comment]
{ 
"name": "btc2100w",
"website": "www.btc2100w.com",
"description": "btc2100w的诞生是为了致敬比特币创始人中本聪而创建，总量2100万亿枚质押挖矿50%周期至2100年1月3号，每笔交易都将自动销毁1%手续费，总量会随着时间减少从而达到通缩的目的，25%空投给bsc社区，50%打入流动池，我们坚信比特币在2100年之前会到达2100万一枚一亿倍的创世纪涨幅，同时我们将比特币拆分一亿倍增加9个0成为一种每个人都能随意打赏的小费代币，这符合比特币经济学原理创世纪涨幅一亿倍和拆分一亿倍",
"explorer": "https://bscscan.com/token/0x50AF4C1345F23bC31fD9fCea7566051E1824dE93",
"type": "BEP20",
"symbol": "btc2100w",
"decimals": 18,
"status": "active",
"id": "0x50AF4C1345F23bC31fD9fCea7566051E1824dE93"
}
20231024_200338_mh1702533339850

**Comment by Leo900805** [comment]
??

**Comment by Leo900805** [comment]
Are there any problems currently?

**Pull request merged**
