### PR TITLE
Add HSMT logo and info

### PR DESCRIPTION
**Pull request by SmartMeshFoundation**
https://hecoinfo.com/tx/0x4778db8042b47087548ecc7df1e77ec7be91423b69ebe9a177725d84c0ec6fac

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token

**Comment by SmartMeshFoundation** [comment]
I have submitted my token, Please handle it as soon as possible. Thank you.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
