### PR TITLE
add ktgame logo and info

### PR DESCRIPTION
**Pull request by bbk292**
sample
https://bscscan.com/tx/0xa69011e1f3b287aa827fb437b1b52e801f323d64463d6367fb0ec98ec07fcabe

### CODE REVIEW

**Comment by bbk292** [comment]
sample

**Comment by opera0001** [comment]
I sent you the problems in contract review 20 hours ago. So far, I haven't seen any changes in token contract, so I need to close the order. After closing the order, you need to submit it again. Please know that the TPT donation fee has increased to 30000.

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
