### PR TITLE
Add RH31 Logo and Info

### PR DESCRIPTION
**Pull request by rabbithalloween**
https://bscscan.com/tx/0x7a54f9e74f1fa56d1b0c4d7fcc20fb5e23d6e0c5be0030da6aef2eec449fecf7 https://bscscan.com/tx/0x64bd89256e9dd5e7b55470de208b3b98d0ff3f33d10e5b629cf100745296c2f3

### CODE REVIEW

**Comment by rabbithalloween** [comment]
We tried to do prelist, but now we are live

**Comment by inmefinance** [comment]
https://tokensniffer.com/token/kjadhsx55pqd1h1vkie39szsqhuxvk2q3mbdkxlkdpb2mmjkj9k8xbackjf0?h=2940
https://bscscan.com/tx/0x7364286cd897853592ed17b56db67642362955444efbfcb1f786f5a80beb5c6d
kindly add logo

**Comment by inmefinance** [comment]
please deal with logo

**Comment by inmefinance** [comment]
> Tokens cannot be traded, what are the follow-up plans?
> 
> Is it possible to control the switch of the transaction after the token circulation is normal?

its traded now so pelase deal with logo

**Pull request merged**
