### PR TITLE
add Grke logo and info

### PR DESCRIPTION
**Pull request by xiaoku123a111**
sample

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Please re-submit your files attached TPT transfer link on [Commit changes], and refer to the tutorial, and re-submit your files in the correct format.

**Comment by xiaoku123a111** [comment]
> 请在【提交更改】上重新提交您的文件附加 TPT 传输链接，并参考教程，并以正确的格式重新提交您的文件。

提交了

**Comment by xiaoku123a111** [comment]
> 请在【提交更改】上重新提交您的文件附加 TPT 传输链接，并参考教程，并以正确的格式重新提交您的文件。

https://hecoinfo.com/tx/0xf35eeeb42b6b2cf790c95d46ba72556e65178d688702f2824117984d0c32da00

**Comment by xiaoku123a111** [comment]
https://hecoinfo.com/tx/0xf35eeeb42b6b2cf790c95d46ba72556e65178d688702f2824117984d0c32da00&nbsp; &nbsp;这是tpt传输记录


---Original---
From: ***@***.***&gt;
Date: Tue, Aug 24, 2021 17:41 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] add Grke logo and info (#2769)




 
Please re-submit your files attached TPT transfer link on [Commit changes], and refer to the tutorial, and re-submit your files in the correct format.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Review by xiaoku123a111 — COMMENTED** [review]
https://hecoinfo.com/tx/0xf35eeeb42b6b2cf790c95d46ba72556e65178d688702f2824117984d0c32da00

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Pull request closed without merging**
