### PR TITLE
Create 0xae57fe379494B30Ec1E085Fb8a87d9C2FdcbcA2a

### PR DESCRIPTION
**Pull request by goodgoodstudy8daydayup**
转账 50000TPT hash:  https://bscscan.com/tx/0x283f8509819069773535915b000c98bfe8df9467bddba92788c539c437bbe5f1

验证hash:   https://bscscan.com/tx/0x6589f471129186e80d02df32f9e15e844722b175205cb744cfe083a9c8f9043f

### CODE REVIEW

**Comment by goodgoodstudy8daydayup** [comment]
[info.json](https://github.com/user-attachments/files/16398143/info.json)
logo

**Comment by opera0001** [comment]
Please follow the official tutorial content for submission.

CN：https://help.tokenpocket.pro/cn/developer/submit-logo
EN：https://help.tokenpocket.pro/en/developer/how-to-submit-a-token-logo#steps-of-adding-a-token-logo-info

**Comment by goodgoodstudy8daydayup** [comment]
> https://bscscan.com/tx/0x283f8509819069773535915b000c98bfe8df9467bddba92788c539c437bbe5f1

**Comment by goodgoodstudy8daydayup** [comment]
> Please follow the official tutorial content for submission.
> 
> CN：https://help.tokenpocket.pro/cn/developer/submit-logo EN：https://help.tokenpocket.pro/en/developer/how-to-submit-a-token-logo#steps-of-adding-a-token-logo-info

转账 50000TPT hash: https://bscscan.com/tx/0x283f8509819069773535915b000c98bfe8df9467bddba92788c539c437bbe5f1

验证hash: https://bscscan.com/tx/0x6589f471129186e80d02df32f9e15e844722b175205cb744cfe083a9c8f9043f

**Comment by opera0001** [comment]
Dear, please submit according to the official tutorial. The JSON content you submitted is invalid, and the JSON and logo are not stored in the same folder.

**Comment by goodgoodstudy8daydayup** [comment]
> Dear, please submit according to the official tutorial. The JSON content you submitted is invalid, and the JSON and logo are not stored in the same folder

thank you,

**Pull request closed without merging**
