### PR TITLE
Unicorn自定义Logo

### PR DESCRIPTION
**Pull request by vendersen**
代币信息和其他描述：{
 "name": "Unicorn",
 "website": "https://unio.red",
 "description": "添加薄饼流动性,每日赚取USDT分红",
 "explorer": "https://www.bscscan.com/token/0x728Ddfe6078df2717eeC321caa1Ec0036d862198",
 "type": "BEP20",
 "symbol": "Unio",
 "decimals": 18,
 "status": "active",
 "id": "0x728Ddfe6078df2717eeC321caa1Ec0036d862198"
}
TPT 的交易Hash链接：https://bscscan.com/tx/0xd9bbb9c619bad4db16d9c0ec1441bd12a3dccb143e9c6b256a1893ea62355d07
验证后的哈希值链接：https://bscscan.com/tx/0xd5b89e20d6a61a3f038b57cad896fd08580f6f776e0437eea5bfcb7a7e61f389

### CODE REVIEW

**Comment by vendersen** [comment]
小伙伴们辛苦了，加油加油加油到目前为止我已经1天1夜没合眼了，好困啊！！！！ 希望一次通过，爱你哦 木木哒 哈哈哈哈哈 笑死我了

**Comment by giki0318** [comment]
According to the DAO, the donation amount for a logo update has been updated to 30,000 TPT. [Click here for Details](https://snapshot.org/#/tptdao.eth/proposal/0x781abc1ade2ebd082aec4f57b7199d472a2b2850b3df46c8ec37e3b6a1a243c2)

**Comment by TokenPocket-JAN** [comment]
Professional expedited review. Please reply to the email if you need.
QQ112831047

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
