### PR TITLE
Add DAO logo and info

### PR DESCRIPTION
**Pull request by daoswap002**
30000TPT transaction link: https://bscscan.com/tx/0x5ce80ea624ff214697fea274532cc76edf3bd0139f40779fd7fdd7a394edb4d1
step 5 hash link: https://bscscan.com/tx/0xa936662b6fa122ad83dac8864f79b115b2a3f0dd5911f928d0ad1158345c504c

### CODE REVIEW

**Comment by opera0001** [comment]
It is detected that the contract address has the setting of control transaction switch, which is of great risk.

**Comment by opera0001** [comment]
If there is a switch to control transactions, the circulation of tokens will become risky.

**Comment by opera0001** [comment]
> > It is detected that the contract address has the setting of control transaction switch, which is of great risk.
> 
> What is the problem with this? The same token has been submitted and passed on HECO, and the contract is consistent, #5716

If there is a switch to control transactions, the circulation of tokens will become risky.

**Comment by daoswap002** [comment]
> 

The contract code is understood, can you help me to complete the commit?

**Comment by opera0001** [comment]
If you can, it is recommended that you give up the management permission of the contract address, which is safer.

**Comment by daoswap002** [comment]
> management

What does management permission specifically refer to?

**Comment by opera0001** [comment]
That is, the management authority of the token is discarded

**Comment by daoswap002** [comment]
Does management authority of the token specifically mean that can't mint and burn?

**Comment by daoswap002** [comment]
@opera0001 Does the management authority of tokens specifically mean that they cannot be minted and burned? Or some other function? Please be specific, thank you

**Pull request closed without merging**
