### PR TITLE
add wx logo and info

### PR DESCRIPTION
**Pull request by jasonz1987**
BSC-WX-0x79D31412db49F8Edc25f6Db26C2544f1e2bFCd51-0x823bff520d1f5adaa4a8611e768cf6f6c522fdd910e3755e79aea34b7177144e

### CODE REVIEW

**Comment by guoxintongsam** [comment]
The contract didn’t verify and publish.

**Comment by jasonz1987** [comment]
The contract is now open source ,please review again, tks~

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
