### PR TITLE
Add  BTCP Logo And Info

### PR DESCRIPTION
**Pull request by liaoff6767**
Bitcoin Private is a private, decentralized, high-speed and open-source community-led cryptocurrency. Bitcoin Private, like Bitcoin, supports direct transactions between individuals without intermediary. All transaction payments will be verified by each network node through cryptography and archived in the public bookkeeping.

### CODE REVIEW

**Comment by liaoff6767** [comment]
1000枚tpt交易哈希地址：https://hecoinfo.com/tx/0xee4d8cfa3bf0d59c5fe7f1af7db89ac77cf9dec2553abed4ec03a3d7617dc746

**Comment by werx111fds** [comment]
btcp请尽快审核谢谢

**Comment by zhujiayu03** [comment]
代币信息文件提交有误。

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
