### PR TITLE
BCPT

### PR DESCRIPTION
**Pull request by bcp888**
名称：BCPT。（全称：BCP Token）。总量100亿
 1000 TPT 的交易ID链接：0x4c715e6756e75fa78969c4e31aa26c566df9afb93c5a73ebbf6bf1a58cb7ad1e

### CODE REVIEW

**Comment by bcp888** [comment]
上传BCPT的LOGO以及信息

**Comment by zhujiayu03** [comment]
Please re-submit your files to bsc folder

**Comment by bcp888** [comment]
按照之前的重新提交一遍吗？那两个文件图标和币的应用



---Original---
From: ***@***.***&gt;
Date: Thu, Aug 12, 2021 11:26 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] BCPT (#2269)




 
Please re-submit your files to bsc folder
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
