### PR TITLE
Add ZongZi logo and info

### PR DESCRIPTION
**Pull request by ZongZi01**
Txn hash: 
0x6ee0ab663804404b84db0dbc75e69da8052056143743a1cf639e9fd60189a7b3

### CODE REVIEW

**Comment by opera0001** [comment]
The contract address seems to contain hidden owner permissions. Please check.

**Comment by ZongZi01** [comment]
> The contract address seems to contain hidden owner permissions. Please check.

Contract privileges have been modified, please review.
Already listing

**Comment by ZongZi01** [comment]
Contract privileges have been modified, please review.

Txn hash:
0x6ee0ab663804404b84db0dbc75e69da8052056143743a1cf639e9fd60189a7b3

**Comment by ZongZi01** [comment]
The contract is open source, please help to advance the logo, thanks!

**Pull request merged**
