### PR TITLE
add cwt v2 logo and info

### PR DESCRIPTION
**Pull request by dante202201**
[cwt v2 logo and info](https://bscscan.com/tx/0x4845dcd41882a80f85aa043968a3ff99cd08c061931419fda2c53daf433e48f9)

### CODE REVIEW

**Comment by dante202201** [comment]
the transaction:https://bscscan.com/tx/0x4845dcd41882a80f85aa043968a3ff99cd08c061931419fda2c53daf433e48f9

**Comment by logobaoguo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by opera0001** [comment]
done

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request merged**
