### PR TITLE
Add LFG token and info

### PR DESCRIPTION
**Pull request by lfgswapfinance**
https://bscscan.com/tx/0xc10f10b5eb65bf23dc774c52b0d251f55c6825324a68eed73dfb89992450e8a3

### CODE REVIEW

**Comment by opera0001** [comment]
A token increment issue setting has been detected. Please explain what it does.

**Comment by lfgswapfinance** [comment]
Since it is produced by mining, it will be additionally issued, It has not been released until IDO is over.

We are in the process of completing the Certik audit.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: opera0001 ***@***.***>
发送时间: Monday, March 27, 2023 4:29:45 PM
收件人: TP-Lab/tokens ***@***.***>
抄送: lfgswapfinance ***@***.***>; Author ***@***.***>
主题: Re: [TP-Lab/tokens] Add LFG token and info (PR #9196)


A token increment issue setting has been detected. Please explain what it does.

―

**Comment by lfgswapfinance** [comment]
LFGSwap<https://app.lfgswap.finance/> is a community-driven organization built to solve the liquidity problem. The product includes decentralized exchange, Yield Instruments, AMM Framework, and Staking Derivatives


Business Development:

LFGSwap is the leading DEX on both the EthereumPow and CoreDAO. The $LFG (Arbitrum) will be launching IDO on March 26th, and the trading will start on March 30th


Data:

· 25 million views on the official website

· 350,000+ Telegram and Discord followers

· 310,000+ Twitter followers

· Worldwide community including Nigeria, Indonesia, China and more


Market Performance:

$LFG tokens raised 400,000 $CORE during the 16x Overflow IDO on CoreDAO public chain, with an approximate value of $1,400,000 USDT. And the token price went up to 50x the price of IDO


Security:

LFGSwap was audited twice by CertiK with High-Security level and is secured with Skynet services.


Highlight:

CZ, CEO at Binance ***@***.***_binance) tweeted the LFGSwap Wolf of Wall Street NFT on his personal Twitter on March 18th.

https://twitter.com/cz_binance/status/1637103059598753792


┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈

📍LFGSwap Links：


✅Github<https://github.com/LfgSwap>|✅Official website<https://app.lfgswap.finance/>|✅WhitePaper<https://lfgswap.gitbook.io/lfgswap/>|✅Twitter<https://twitter.com/LfgSwap>|✅Certik<https://www.certik.com/projects/lfgswap>|✅Audit Report<https://github.com/LfgSwap/lfg-protocol/tree/main/audit>


获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: finance lfgswap ***@***.***>
发送时间: Monday, March 27, 2023 11:59:00 PM
收件人: TP-Lab/tokens ***@***.***>; TP-Lab/tokens ***@***.***>
抄送: Author ***@***.***>
主题: Re: [TP-Lab/tokens] Add LFG token and info (PR #9196)

Since it is produced by mining, it will be additionally issued, It has not been released until IDO is over.

We are in the process of completing the Certik audit.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: opera0001 ***@***.***>
发送时间: Monday, March 27, 2023 4:29:45 PM
收件人: TP-Lab/tokens ***@***.***>
抄送: lfgswapfinance ***@***.***>; Author ***@***.***>
主题: Re: [TP-Lab/tokens] Add LFG token and info (PR #9196)


A token increment issue setting has been detected. Please explain what it does.

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Comment by lfgswapfinance** [comment]
Ok, I hope you can review it as soon as possible. Thank you.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: opera0001 ***@***.***>
发送时间: Tuesday, March 28, 2023 1:03:06 PM
收件人: TP-Lab/tokens ***@***.***>
抄送: lfgswapfinance ***@***.***>; Author ***@***.***>
主题: Re: [TP-Lab/tokens] Add LFG token and info (PR #9196)


The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

―

**Comment by lfgswapfinance** [comment]
Hello, I see that our token logo has not been displayed in your wallet. How long will it take to review?

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: finance lfgswap ***@***.***>
发送时间: Tuesday, March 28, 2023 2:23:40 PM
收件人: TP-Lab/tokens ***@***.***>
主题: Re: [TP-Lab/tokens] Add LFG token and info (PR #9196)

Ok, I hope you can review it as soon as possible. Thank you.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: opera0001 ***@***.***>
发送时间: Tuesday, March 28, 2023 1:03:06 PM
收件人: TP-Lab/tokens ***@***.***>
抄送: lfgswapfinance ***@***.***>; Author ***@***.***>
主题: Re: [TP-Lab/tokens] Add LFG token and info (PR #9196)


The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

―

**Comment by lfgswapfinance** [comment]
Do you still have a three day rest period

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: finance lfgswap ***@***.***>
发送时间: Wednesday, March 29, 2023 12:16:10 PM
收件人: TP-Lab/tokens ***@***.***>
主题: Re: [TP-Lab/tokens] Add LFG token and info (PR #9196)

Hello, I see that our token logo has not been displayed in your wallet. How long will it take to review?

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: finance lfgswap ***@***.***>
发送时间: Tuesday, March 28, 2023 2:23:40 PM
收件人: TP-Lab/tokens ***@***.***>
主题: Re: [TP-Lab/tokens] Add LFG token and info (PR #9196)

Ok, I hope you can review it as soon as possible. Thank you.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: opera0001 ***@***.***>
发送时间: Tuesday, March 28, 2023 1:03:06 PM
收件人: TP-Lab/tokens ***@***.***>
抄送: lfgswapfinance ***@***.***>; Author ***@***.***>
主题: Re: [TP-Lab/tokens] Add LFG token and info (PR #9196)


The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

―

**Pull request merged**
