### PR TITLE
ADD Asking info and logo

### PR DESCRIPTION
**Pull request by ZHANGMAZ1**
https://bscscan.com/tx/0x18edd3475262b39f8876dc70232b5901ae3afa936986011f704a393f50b2b601

### CODE REVIEW

**Comment by ZHANGMAZ1** [comment]
https://bscscan.com/tx/0x18edd3475262b39f8876dc70232b5901ae3afa936986011f704a393f50b2b601

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3579750034

**Comment by ZHANGMAZ1** [comment]
https://bscscan.com/tx/0x8f323dc3b1cee7eb55b6a9fb3b0f13d911656c0ce64ca722555d0c6fb084632e

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by L402325810** [comment]
你好

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request merged**
