### PR TITLE
Add ZuoZhuang logo and info

### PR DESCRIPTION
**Pull request by lunoob**
30,000 TPT 交易 ID 链接:
https://bscscan.com/tx/0x6e58c21dee8828550a9dc9abcd370078f699168ee2d7039581d497ddf985c5e2
验证 hash 链接:
https://bscscan.com/tx/0x581636c3532e1afafc66ae0806f364c911d147be143ded438329fd0e89d4e4d3

### CODE REVIEW

**Comment by lunoob** [comment]
now token transcation is normal, please check again. thanks

**Comment by lunoob** [comment]
now buy rate about 14%, may be a few points higher

**Comment by lunoob** [comment]
website: https://zzdao.me/

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request merged**
