### PR TITLE
Add SWAN22 logo and info

### PR DESCRIPTION
**Pull request by orexzon**
TPT-3000 tranfer from 0x72a4Cfbd21BF175ca61B149ff1566855D56b102E

HECO-TPT-0x3DD95A6fc933d41493263DF988798F2b488659d3-https://hecoinfo.com/tx/0x3DD95A6fc933d41493263DF988798F2b488659d3

HECO-TPT-0x3DD95A6fc933d41493263DF988798F2b488659d3-https://hecoinfo.com/token/0x3DD95A6fc933d41493263DF988798F2b488659d3

### CODE REVIEW

**Comment by tubiaoyingji** [comment]
专业加快提交LOGO，20分钟内审核包过，QQ：1450001284

**Comment by orexzon** [comment]
hi,sir
regarding about my SWAN22 token logo and info submitted,
when can viewers on public on tp wallet,please check with me.
thank you!

best regards

tubiaoyingji ***@***.***> 于 2021年11月28日周日 11:53写道：

**Comment by orexzon** [comment]
> 专业加快提交LOGO，20分钟内审核包过，QQ：1450001284

请问你们20分钟内审核包过是什么？

**Comment by orexzon** [comment]
How to merge, it's only showing ready to merge not merged

**Comment by sammvio** [comment]
Please refer to the tutorial, and re-submit your files in the correct format.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
