### PR TITLE
Add BMW logo and info

### PR DESCRIPTION
**Pull request by XiangBin520**

### CODE REVIEW

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by opera0001** [comment]
It is suggested to give up the management authority of the token, and it is detected that there may be a switch setting to control the token transaction.

**Comment by XiangBin520** [comment]
我这令牌已经上主网了，目前大量流通中，不能更改合约


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TP-Lab/tokens"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月15日(星期二) 上午10:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TP-Lab/tokens] Add BMW logo and info (PR #6172)





 
It is suggested to give up the management authority of the token, and it is detected that there may be a switch setting to control the token transaction.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
