### PR TITLE
add cdc token logo and info

### PR DESCRIPTION
**Pull request by guodayang007**
two transactions
5000TPT
txID: https://bscscan.com/tx/0xe42c47b1177a050de6d10d12fafb4f31901c688a798b90cc45611cca8a33d1ae
45,000 TPT
txID :https://bscscan.com/tx/0x85727aeb49d31c4e8497a472487ef07c85ac52130e6fbc60d3b203399943d212

These two coin transactions were not approved when I submitted them earlier. You said you could use another token to submit them

### CODE REVIEW

**Comment by opera0001** [comment]
The donated amount from tpt in the hash value you submitted is incorrect. Please double-check or provide additional details for my review. Thank you.

**Comment by guodayang007** [comment]
I have two transactions that were not approved before. You said they can be used again


45,000 TPT
txID :https://bscscan.com/tx/0x85727aeb49d31c4e8497a472487ef07c85ac52130e6fbc60d3b203399943d212

5000TPT
txID: https://bscscan.com/tx/0xe42c47b1177a050de6d10d12fafb4f31901c688a798b90cc45611cca8a33d1ae

My two transactions add up to a total of 50000 TPT

**Comment by guodayang007** [comment]
Previously, you said the amount verification was completed. I withdrew the submission because I had written the wrong token address before

https://github.com/TP-Lab/tokens/pull/10149

**Comment by guodayang007** [comment]
> 您提交的哈希值中tpt的捐赠金额不正确。请仔细检查或提供更多详细信息以供我审核。谢谢。

Previously, you said the amount verification was completed. I withdrew the submission because I had written the wrong token address before

https://github.com/TP-Lab/tokens/pull/10149

**Pull request merged**
