### PR TITLE
Add MI logo and info

### PR DESCRIPTION
**Pull request by GGlow**
Add MI logo and info,

### CODE REVIEW

**Review by GGlow — COMMENTED** [review]
https://bscscan.com/tx/0x9af8bd0859c30df3c3396f7066562e2b2c4ff62124f9fae5afafba3d9e95be61

**Comment by tubiaoyingji** [comment]
专业加快提交LOGO，20分钟内审核包过，QQ：1450001284

**Comment by sammvio** [comment]
The contract didn’t verify and publish. (No open-source)

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Pull request closed without merging**
