### PR TITLE
Add PK logo and info

### PR DESCRIPTION
**Pull request by dewht**
0x3c5b9808290377fee02188cebf937f7466d5e7cc4bacd1bdd69e5a91ddb38c2f

### CODE REVIEW

**Comment by dewht** [comment]
0x3c5b9808290377fee02188cebf937f7466d5e7cc4bacd1bdd69e5a91ddb38c2f

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Comment by dewht** [comment]
> 订单申请已收到，请耐心等待审核。不要轻信任何非官方信息，谨防上当受骗。
0xd3f218835bc784e31a70188ff4d3db79d7e44ea1

**Comment by dewht** [comment]
> 订单申请已，请耐心等待审核。不要轻信任何非官方信息，谨防上当受骗。
This is the contract address where the avatar needs to be displayed. Thank you 0xd3f218835bc784e31a70188ff4d3db79d7e44ea1

**Pull request merged**
