### PR TITLE
Add logo and info

### PR DESCRIPTION
**Pull request by Lidity**
0xd80d24402b1a8e2f0cf5a2686b2226a2fb90e8e32b87d5bff5f52dd1e82a132e

### CODE REVIEW

**Comment by Lidity** [comment]
0x348f15744fb45d4268a69b7fedd222043155a844380024bc04bea9e0efa53f93
0x0b17e3f0487f5bcb0be565216e193fc340e82c9311eb61b59f65563e4a056e05

**Comment by logobaoguo** [comment]
专业提交logo！加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by sammvio** [comment]
Please re-submit your files to bsc folder

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
