### PR TITLE
Add BABYMATIC logo and info 

### PR DESCRIPTION
**Pull request by armyonfire**
BSC - TPT - 0xb2ce41b71d93d7f5878f985c3e1a87a6229019be - https://bscscan.com/tx/0xc3ec311fa0e88e4365e925ef53799fed2f78673d16d4cb762d91ccb4282edbc1

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Please re-submit your files to bsc folder

**Comment by armyonfire** [comment]
How do i submit to BSC folder? i do not know how to submit it there. it
says i cannot upload file.

**Comment by armyonfire** [comment]
i resubmit again and i have submit to BSC folder now. 2191 now. can you
please add the logo now?

[image: image.png]

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Pull request closed without merging**
