### PR TITLE
Add VR logo and info

### PR DESCRIPTION
**Pull request by Adley1987**
sample

### CODE REVIEW

**Comment by opera0001** [comment]
No TPT donation hash value found

**Comment by Adley1987** [comment]
> No TPT donation hash value found

This is a donation hash, thank you
:0x30d855f92356a5a300304f20c373a98e0e489dbf55aab4e2d19ef314ebe386f5

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
