### PR TITLE
Add SUDC log and info

### PR DESCRIPTION
**Pull request by LIYI99**
https://bscscan.com/tx/0xef48185a76c7ba816c507f4bbd207481a4d75af906eb20a1be7da0b609532b3a

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token

**Comment by LIYI99** [comment]
Hi:

&nbsp;&nbsp; Why isn't my icon on the shelf? I've been paying for a long time. Here is my payment record.

&nbsp;&nbsp; https://bscscan.com/tx/0xef48185a76c7ba816c507f4bbd207481a4d75af906eb20a1be7da0b609532b3a








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TP-Lab/tokens"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月15日(星期四) 下午2:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TP-Lab/tokens] Add SUDC log and info (#1275)





 
Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
