### PR TITLE
Modify Logo

### PR DESCRIPTION
**Pull request by LuckyFortuneDog**
Please modify 256x256Logo for our LFD, Logo address: https://postimg.cc/Z0b0gcTQ

### CODE REVIEW

**Comment by LuckyFortuneDog** [comment]
https://bscscan.com/tx/0xb163ba1e50f9036341e494c7150d7d649e1ffd2079489474c16e3cdbfa7ce295
The logo size of the TP wallet has been modified, and the size displayed by the Android system and the Apple system is inconsistent.

**Comment by zhujiayu03** [comment]
Please refer to the tutorial, and re-submit your files in the correct format.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
