### PR TITLE
Adding BABYFD logo and info

### PR DESCRIPTION
**Pull request by BabyFlokiDoge**

### CODE REVIEW

**Comment by tiaojiaotubiaobaoguo** [comment]
代提交logo，24小时内包过，加QQ：2980874528

**Comment by sammvio** [comment]
Please donate 3000 TPT as required and submit the transfer link on [Commit changes].

**Comment by BabyFlokiDoge** [comment]
ok can you please let me know where to send it and i will send it asap.

**Comment by BabyFlokiDoge** [comment]
Please see
https://bscscan.com/tx/0x207acb78b5da3ec58bccf9d7108d646c1304458c272e398aaf56cbcaaa10948e

They said they paid and you can see in that transaction link.

Ill send you BNB personally if you want - i just need that LOGO up as
soon as possible sir.

Thank you,

Chris

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
