### PR TITLE
Add DCE logo and info

### PR DESCRIPTION
**Pull request by eivac**
https://bscscan.com/tx/0xa8e2b9f1f9dc0f9bba5df65464d819721c23fd8c975ade30c562905058b07714

### CODE REVIEW

**Comment by opera0001** [comment]
It is found that there may be settings to control token transactions. Please check and explain the situation.

**Comment by eivac** [comment]
> 发现可能有控制代币交易的设置。请检查并说明情况。



> It is found that there may be settings to control token transactions. Please check and explain the situation.

DCE, as the only token jointly circulated by bitdce and bitdex, is also the governance token of the two platforms It can not only enjoy various services of the platform, such as value-added services, exclusive activities, preferential experience and many other rights and interests, but also serve as a communication bridge between digital assets and traditional assets, individual traders and professional traders, price recipients and market makers, exchanges and their partners.

**Comment by opera0001** [comment]
You just introduced the token, but did not explain the function of the switch that can control the transaction!

**Comment by opera0001** [comment]
I haven't seen your reply after 21 hours, so I will help you close the order first. If you need to leave a message, please go to https://github.com/TP-Lab/tokens/issues Initiate proposals. thank you.

**Pull request closed without merging**
