### PR TITLE
provide PolyFeg infomation

### PR DESCRIPTION
**Pull request by kassidyliberty**

### CODE REVIEW

**Comment by zhuroujuan** [comment]
未提交转账哈希

**Comment by kassidyliberty** [comment]
> 未提交转账哈希

please check this
0x42bf81354e30a2120f8fff632e85bfeee8dfd18c5df4f4902f7fb5547208e456

**Comment by zhujiayu03** [comment]
Website info incorrect.

**Comment by kassidyliberty** [comment]
@zhujiayu03 please check https://github.com/TP-Lab/tokens/pull/1323

**Pull request closed without merging**
