### PR TITLE
PANDA-0x577fd39fcd328336b0d3728660bc4dd371758830

### PR DESCRIPTION
**Pull request by Q22004801XIAO**
TPT:0xfb102f9355b4a81c4d48018017f17abf058fc42083643ec312246055fba333c6 BNB:0x298da9aa2f965d9c5f88269c46bab4777cb00336098d9b5d967029c9e7f314e1

### CODE REVIEW

**Comment by Q22004801XIAO** [comment]
麻烦审核一下，谢谢

**Comment by opera0001** [comment]
image
The submitted file is not saved in the BSC directory, please adjust it again.

**Comment by opera0001** [comment]
image

The order cannot be pulled and merged, so you need to resubmit it. Please make sure to save the submitted files in the BSC directory.

**Comment by Q956796289** [comment]
> 图像 提交的文件没有保存在BSC目录下，请重新调整。
好的谢谢

**Comment by Q22004801XIAO** [comment]
已经改过，

**Review by Q956796289 — APPROVED** [review]

**Comment by opera0001** [comment]
image

It still has issues, so please resubmit. Please submit strictly according to the requirements in the tutorial.

CN: https://tphelp.gitbook.io/cn/wallet-operation/submit-token
EN: https://help.tokenpocket.pro/en/developer/how-to-submit-a-token-logo#steps-of-adding-a-token-logo-info

**Comment by Q22004801XIAO** [comment]
已经更改

**Pull request closed without merging**
