### PR TITLE
Add OKF logo and info

### PR DESCRIPTION
**Pull request by opppisme**
OKFarm is a game focused on Simulation business in the NFT format.

### CODE REVIEW

**Comment by opppisme** [comment]
https://bscscan.com/tx/0x65f5ad32a356d80f7c416f9767719dadf44f86b1dbf4187f638ea5ca1326596a

**Comment by zhujiayu03** [comment]
logo infringement, please resend your image

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
