### PR TITLE
Add PPOLL info and logo

### PR DESCRIPTION
**Pull request by pancakepolldev**
BSC - PPOLL - 0xc29000A4b1eCD326b6DafAE17bDA636475FeA1e7 - https://bscscan.com/tx/0x37a9db5b96a867235a9f0ca61d1b9536a6e7f2e4cd50b41a8f07ffcec7799714

### CODE REVIEW

**Comment by tubiaoyingji** [comment]
专业加快提交LOGO，20分钟内审核包过，QQ：1450001284

**Comment by pancakepolldev** [comment]
BSC - PPOLL - 0xc29000A4b1eCD326b6DafAE17bDA636475FeA1e7 - https://bscscan.com/tx/0x37a9db5b96a867235a9f0ca61d1b9536a6e7f2e4cd50b41a8f07ffcec7799714

**Comment by pancakepolldev** [comment]
BSC - PPOLL - 0xc29000A4b1eCD326b6DafAE17bDA636475FeA1e7 - https://bscscan.com/tx/0x37a9db5b96a867235a9f0ca61d1b9536a6e7f2e4cd50b41a8f07ffcec7799714

**Comment by pancakepolldev** [comment]
@sammvio please check and merge, payment is already made

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request merged**
