### PR TITLE
Add FYM logo and info

### PR DESCRIPTION
**Pull request by xuzhi5858**
https://bscscan.com/tx/0xe890e4fcc977a112b1a6932203d08d345f430ef9e567559aa8c4734800745336

### CODE REVIEW

**Comment by opera0001** [comment]
Detect can modify tokens interchange fees, what is its function?

**Comment by xuzhi5858** [comment]
Adjust tax rate, up to 15

**Comment by opera0001** [comment]
Ok, please wait patiently for a review, is usually about 3 days.

**Comment by xuzhi5858** [comment]
Okay, looking forward to the review passing

**Pull request merged**
