### PR TITLE
Add MUSIC logo and info

### PR DESCRIPTION
**Pull request by htwang1134**
50000TPT转账地址链接：https://bscscan.com/tx/0x2bb0ce890cd7aebfed84bc00ebe030f1f1d422e0603fd1333f1e90a28b7d5258
步骤5验证哈希链接：https://bscscan.com/tx/0x767cfb8ddef88f156245ccfc0a87b6714d502d6acb63eed9040643aac0150cd6

### CODE REVIEW

**Comment by opera0001** [comment]
Anomalies detected in the circulation of tokens may be related to not starting a transaction, please explain the situation.

**Comment by htwang1134** [comment]
This token has a basic pool and has been locked for 3 years. Other tokens need to be generated through on-chain games and cannot be purchased directly on DEX. DEX only provides sell transactions. To obtain tokens, they must be generated through games.

> Anomalies detected in the circulation of tokens may be related to not starting a transaction, please explain the situation.

**Comment by htwang1134** [comment]
> 

The only thing that can be purchased on the chain is the address specified in the game, which is purchased and then destroyed. Other ordinary users will directly destroy the tokens if they purchase in the DEX.

**Comment by htwang1134** [comment]
Please admin update the token icon

**Pull request merged**
