### PR TITLE
Add New Logo and Info

### PR DESCRIPTION
**Pull request by TokenLogos**
TPT:
https://bscscan.com/tx/0xbcf86c49f112274ad02625d8acdca9f6348fabf8328cff857f99d5e18501ddff

BNB:
https://bscscan.com/tx/0x92c70cfbb7fc61072afb1572aaa385ac59ac863cd45025472dda68a81b4fa5d8

暂停池子买卖功能用于开盘前锁池子，防止用户提前加池子

### CODE REVIEW

**Comment by opera0001** [comment]
image

**Comment by TokenLogos** [comment]
The external contract is what we use to control the kill bots.  Is that OK?

**Comment by TokenLogos** [comment]
External contract is open source

**Comment by opera0001** [comment]
Is it possible to provide relevant data?

**Comment by TokenLogos** [comment]
External contract address: 0x33251C60d690684cFE296A951691666d58FDCB08

**Pull request merged**
