### PR TITLE
add anti logo and info

### PR DESCRIPTION
**Pull request by manwei2022**
30,000 TPT的交易ID：0xa54adbcb86ea97b789fa3163495bcf56deaf12e5d2b8bc40c478e8c3c2ad1fed
验证的哈希值链接：0x25e503f2c21b3dbd3f69d29f75ba47f982075fc6cb4c2860916afe490dd1153d

### CODE REVIEW

**Comment by opera0001** [comment]
image
Please use this submitted account to apply for deleting the logo.

**Comment by manwei2022** [comment]
IceCattle001，这个账号我不认识，已被你们tp合并了，我怎么去删除。。。

难道就这样不人性化？我提交的就再也不能更新信息了？

**Comment by manwei2022** [comment]
@opera0001

**Comment by manwei2022** [comment]
@opera0001

**Pull request merged**
