### PR TITLE
ADD NWD LOGO AND INFO

### PR DESCRIPTION
**Pull request by Zhangsanfeng123789**
BSC-NWD-0xC553578FB98B3857104247538E185a3F773e1F99-https://bscscan.com/tx/0x4263345f71580f61a043972144747b4d4f387c420acead6523564d8f1d8ee017

### CODE REVIEW

**Comment by Zhangsanfeng123789** [comment]
0xC553578FB98B3857104247538E185a3F773e1F99

**Comment by Zhangsanfeng123789** [comment]
BSC-NWD-0xC553578FB98B3857104247538E185a3F773e1F99-https://bscscan.com/tx/0x4263345f71580f61a043972144747b4d4f387c420acead6523564d8f1d8ee017

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:2980874528

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
