### PR TITLE
Add SDOGE logo and info

### PR DESCRIPTION
**Pull request by AQscoutdoge**
BSC-SDOGE-0x9e551b430b7ab145c96c6ede72a34ec2a90d4eca-
https://bscscan.com/token/0x9e551b430b7ab145c96c6ede72a34ec2a90d4eca
3000TPT-https://bscscan.com/tx/0x885639d83ef151b67e9e2e656d6b43fb668c8cebe667e2682e2546b2f140add5

### CODE REVIEW

**Comment by AQscoutdoge** [comment]
{
"name": "Scout Doge Token",
"website": "https://bscscan.com/token/0x9e551b430b7ab145c96c6ede72a34ec2a90d4eca",
"description": "Scout Doge TOKEN.",
"explorer": "https://bscscan.com/token/0x9e551b430b7ab145c96c6ede72a34ec2a90d4eca",
"type": "BEP20",
"symbol": "SDOGE",
"decimals": 9,
"status": "active",
"id": "0x9e551b430b7ab145c96c6ede72a34ec2a90d4eca"
}

BSC-SDOGE-0x9e551b430b7ab145c96c6ede72a34ec2a90d4eca-
3000TPT-https://bscscan.com/tx/0x885639d83ef151b67e9e2e656d6b43fb668c8cebe667e2682e2546b2f140add5

Thank you very much

**Comment by sammvio** [comment]
Please donate 3000 TPT per logo as required and submit the transfer link on [Commit changes].

**Comment by AQscoutdoge** [comment]
> 请按要求为每个 logo 捐赠 3000 TPT，并在 [Commit changes] 上提交转让链接。

3000TPT- https://bscscan.com/tx/0x885639d83ef151b67e9e2e656d6b43fb668c8cebe667e2682e2546b2f140add5
I've already donated 3,000 TPT,!!!!!!!

**Comment by AQscoutdoge** [comment]
3000TPT- https://bscscan.com/tx/0x885639d83ef151b67e9e2e656d6b43fb668c8cebe667e2682e2546b2f140add5
I've already donated 3,000 TPT,!!!!!!!

**Comment by AQscoutdoge** [comment]
> Please donate 3000 TPT per logo as required and submit the transfer link on [Commit changes].

3000TPT- https://bscscan.com/tx/0x885639d83ef151b67e9e2e656d6b43fb668c8cebe667e2682e2546b2f140add5
I've already donated 3,000 TPT,!!!!!!!

**Pull request closed without merging**
