### PR TITLE
Add LaEeb logo & info

### PR DESCRIPTION
**Pull request by tylercevansdos**
TPT - https://bscscan.com/tx/0x4c406f844948181292bdefd7123540acdb7c79c6c5a40442f7d394b94e241b54
BNB - https://bscscan.com/tx/0xce3e1f20cc53e123bb0f749de300864f7ab2bcdfd569d38f6ad9929282d68cd2

### CODE REVIEW

**Comment by opera0001** [comment]
The theme of the logo is highly consistent with that of the order #7215 submission, and the name of the token is the same. If there is a design manuscript or copyright of the logo, please provide it to us. Thank you.

**Comment by LaeebProject** [comment]
We submitted our logo without copying the others and aware on the similarity with the other. Please let us know what shall we do?

**Comment by LaeebProject** [comment]
@opera0001

**Comment by tylercevansdos** [comment]
What shall we do? We did not copy the other or aware on the similarity before this.

**Comment by tylercevansdos** [comment]
logo png

**Comment by tylercevansdos** [comment]
@opera0001 if the logo is too similar please can we change it to this?

**Comment by tylercevansdos** [comment]
@opera0001 Hi any update?

**Comment by opera0001** [comment]
It is recommended to modify the logo again. Its main elements are still obvious. Sorry

**Comment by tylercevansdos** [comment]
logo png

**Comment by tylercevansdos** [comment]
@opera0001 I hope this is ok now

**Pull request merged**
