### PR TITLE
Add logo kshib and info 

### PR DESCRIPTION
**Pull request by KaiKenShiba**
Add logo Kshib and info
BSC - KSHIB
https://bscscan.com/tx/0xb981babf9cd6fcd394203304e7b8a1ca06f7a502be0f652e0b62472c92fca7c5

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Please re-submit your files to bsc folder

**Comment by KaiKenShiba** [comment]
Can you help me do this? I sent it to the bsc folder before

**Comment by KaiKenShiba** [comment]
https://github.com/TP-Lab/tokens/pull/2309

**Comment by KaiKenShiba** [comment]
[image: Ảnh chụp Màn hình 2021-08-09 lúc 16.12.27.png]

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
