### PR TITLE
Add Gold logo and info

### PR DESCRIPTION
**Pull request by Darklightbscs**
https://bscscan.com/tx/0x4fda355b8a37e47511c918c05234222a9fdeac442237c9725f872e4885792111

### CODE REVIEW

**Comment by opera0001** [comment]
There is agency contract in token contract, and the risk is high.

**Comment by opera0001** [comment]
Now you need 30000 TPT donations to apply for logo inclusion. Please supplement the difference and submit the hash value corresponding to the supplemented difference to us through GitHub. Thank you.

**Comment by Darklightss** [comment]
https://bscscan.com/tx/0x52b579fa0fe035361c04be0bbf8df11d557a05b9cd8a40a8613d1a98470c92dc

**Comment by Darklightss** [comment]
> 现在您需要 30000 TPT 捐款才能申请徽标收录。请补差，并将补差对应的hash值通过GitHub提交给我们。谢谢你。

https://bscscan.com/tx/0x52b579fa0fe035361c04be0bbf8df11d557a05b9cd8a40a8613d1a98470c92dc

**Comment by jjjgjk** [comment]
你好

**Comment by tplogotijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
