### PR TITLE
ADD HappyDoge logo and info

### PR DESCRIPTION
**Pull request by csskd**
https://bscscan.com/tx/0xf2e88ecac34e6f5961c32513baf107a91427cfb32a1647c87dcf1e8eb3da7162

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3579750034

**Comment by sammvio** [comment]
Wrong explorer link.

**Comment by csskd** [comment]
> 

why? it can be query in BSC! 
https://bscscan.com/tx/0xf2e88ecac34e6f5961c32513baf107a91427cfb32a1647c87dcf1e8eb3da7162
0xf2e88ecac34e6f5961c32513baf107a91427cfb32a1647c87dcf1e8eb3da7162

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
