### PR TITLE
add DT logo and info

### PR DESCRIPTION
**Pull request by Hanggi**

### CODE REVIEW

**Comment by opera0001** [comment]
No TPT donation hash value found

**Comment by Hanggi** [comment]
We already sent donation and bnb 
https://bscscan.com/tx/0xb858de323c90a60dfa58f66153ad653b3a5ce9355f2c5c7c5b05291ef90adfad

And also sent BNB data block with:
BSC - DT -  0x07652BC724A8aE4331c94F0871648202e5E68AD3 - https://bscscan.com/tx/0xb858de323c90a60dfa58f66153ad653b3a5ce9355f2c5c7c5b05291ef90adfad

Please check again @opera0001

**Comment by Hanggi** [comment]
@opera0001 Please reopen this pull request and check again.
Thank you.

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
