### PR TITLE
Add logo and info for LIFE(BEP20)

### PR DESCRIPTION
**Pull request by LifeInfinityMetaverse**
This is a request to add logo and info for Life Infintiy Token(LIFE).

### CODE REVIEW

**Review by LifeInfinityMetaverse — COMMENTED** [review]
update info

**Comment by opera0001** [comment]
1. No TPT donation hash value link found
2. There are no other operations after the token is issued, and the security cannot be determined
3. 
Please re submit the logo after adjustment or optimization. Thank you for your support for tokenpocket.

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
