### PR TITLE
Add SafeMoon logo and info

### PR DESCRIPTION
**Pull request by zhao199579**
https://bscscan.com/tx/0x8d086a7ee7437269ced3a185b43754ef062de3dfd40c40c9f8bbba89dd6ef2da

### CODE REVIEW

**Comment by zhao199579** [comment]
Hard work management review as soon as possible, thank you

**Comment by opera0001** [comment]
No TPT donation hash value submitted

**Comment by zhao199579** [comment]
> No TPT donation hash value submitted

https://bscscan.com/tx/0x50875fb3f6e43c8809413e5d05ca863aef5c1a7f8b646ce1d15e9edadb3101dd

**Comment by zhao199579** [comment]
> No TPT donation hash value submitted

Please verify the donation hash value.

**Comment by opera0001** [comment]
Has passed the preliminary review, please wait patiently for the collection.

**Comment by zhao199579** [comment]
> Has passed the preliminary review, please wait patiently for the collection.

Thank you. How long will it take to display the logo?

**Comment by zhao199579** [comment]
> 已通过初审，请耐心等待收藏。

Excuse me, do I need to prepare anything else?

**Comment by zhao199579** [comment]
How long can I wait after the preliminary examination to display logo?

**Comment by opera0001** [comment]
It is expected to be completed tomorrow.

**Comment by zhao199579** [comment]
Can logo be displayed online today?

**Comment by zhao199579** [comment]
> The same name as other tokens is misleading (safemoon is famous)

How do I solve this problem?

**Comment by zhao199579** [comment]
> The same name as other tokens is misleading (safemoon is famous)

Its tokens are all capitalized, doesn't it conflict with mine?

**Comment by zhao199579** [comment]
> The same name as other tokens is misleading (safemoon is famous)

How should I solve this problem now?

**Pull request closed without merging**
