### PR TITLE
Upload Logo for ARC

### PR DESCRIPTION
**Pull request by ucbitex**
TPT: https://bscscan.com/tx/0xaa60857e651c953176dbc640049af1617f0073298c09e772eb45b180df627382
BNB: https://bscscan.com/tx/0x1608449419c40d2228408087a6faceb333b6fe71a54d93ebadfe167b2ae16ae1

### CODE REVIEW

**Comment by opera0001** [comment]
A proxy contract has been detected. We're sorry, but we cannot list such a high-risk setup. Perhaps you have an audit report from a security company?

**Comment by ucbitex** [comment]
Our Audit is still ongoing

**Comment by opera0001** [comment]
Alright, dear. You can let me know after the audit is completed, and we can start the process again.

**Comment by ucbitex** [comment]
Please check our audit report
[Uploading ARC_0x8689de8f26d044Ac4FdD9198Fb21034Fc0f00538.pdf…]()

**Comment by ucbitex** [comment]
The previous attachment didn't seem working, please check this link @opera0001 
https://github.com/SpyWolfNetwork/Smart_Contract_Audits/blob/main/August_2024/ARC_0x8689de8f26d044Ac4FdD9198Fb21034Fc0f00538.pdf

**Pull request merged**
