### PR TITLE
Add BLWA logo and info

### PR DESCRIPTION
**Pull request by BLWA**
https://bscscan.com/tx/0x45a329bce083ee12bd267eed53d6d2421c4d61ff861f5f90c083be87d1d4e282

### CODE REVIEW

**Comment by qq2871019009** [comment]
快速提交logo，一天内包过，不过全额退款。加QQ：2871019009

**Comment by BLWA** [comment]
When will the logo be reviewed? Started several days, many users have a bad impact

**Comment by tubiaoyingji** [comment]
专业加快提交LOGO，20分钟内审核包过，QQ：1450001284

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request merged**
