### PR TITLE
Add FreeMars logo and info

### PR DESCRIPTION
**Pull request by FreeMarsToken**
Free Mars tokens are the investment tool to purchase virtual land on Free Mars, which will mimic a real world positioned in a very real quadrant of the mars.

TX ID：0x58c3ffd51dd21f406eadd66948892f5851e26f4fa3ad47f11cd60c2323245064

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:2980874528

**Comment by sammvio** [comment]
Please refer to the tutorial, and re-submit your files in the correct format.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
