### PR TITLE
Add CPD logo and info

### PR DESCRIPTION
**Pull request by Kingdata01**
Thank you very much

### CODE REVIEW

**Comment by giki0318** [comment]
Please attach your TPT donation hash. We will close this PR within 48 hrs.

**Comment by Kingdata01** [comment]
image
image

**Comment by jjjgjk** [comment]
1212在吗

**Comment by jjjgjk** [comment]
你好

**Comment by tplogotijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request merged**
