### PR TITLE
Add TTS logo and info

### PR DESCRIPTION
**Pull request by ghsdfvs**
https://bscscan.com/tx/0xeac296ef963646e314d4f3453ad976ef005dfa4942880a78806531b4e4ed171c

### CODE REVIEW

**Comment by TokenPocket-JAN** [comment]
Speed ​​up the trial. Please reply to the email if you need.
QQ112831047

**Comment by opera0001** [comment]
1、The ownership of token contract has not been given up, and there is a switch that can control the transaction. Please hurry up and leave us a message on GitHub after adjustment.

2、Now the token logo application needs 30,000 TPT donations. Please add the difference and leave a message to us on GitHub.

**Comment by opera0001** [comment]
We haven't seen the supplementary TPT donation hash value after 22 hours, so we temporarily close the order and need to resubmit it after you supplement the TPT quota. Thank you for your support for tokenpocket.

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
