### PR TITLE
Add GM logo and info

### PR DESCRIPTION
**Pull request by 473880**
https://bscscan.com/tx/0x06fe8a6858b8fbf1fb752b4a2af0c944fb6db80a2c64396d95193e036666b4d8

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Please re-submit your files to bsc folder

**Comment by 473880** [comment]
能不能把资料发给你，帮忙上传可以吗？



At 2021-09-24 11:51:52, "guoxintongsam" ***@***.***> wrote:

Closed #3243.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 473880** [comment]
已经再次提交了，请尽快处理下，谢谢
















At 2021-09-24 11:51:52, "guoxintongsam" ***@***.***> wrote:

Closed #3243.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
