### PR TITLE
Add BabyDog logo and info

### PR DESCRIPTION
**Pull request by duanzhiguang**
BSC-BabyDog-0x9256e522bdd8e7bd52eddfb89a1e8b4691673448-https://bscscan.com/tx/0x08f46bc1f6cd04527e30e5cbb5ef82b28a24042e016b4b2b3c1c271f34f6e690

### CODE REVIEW

**Comment by duanzhiguang** [comment]
add BabyDog logo and info   
 BSC-BabyDog-0x9256e522bdd8e7bd52eddfb89a1e8b4691673448-https://bscscan.com/tx/0x08f46bc1f6cd04527e30e5cbb5ef82b28a24042e016b4b2b3c1c271f34f6e690

**Comment by zhujiayu03** [comment]
Please refer to the tutorial, and use the contract address in the checksum format.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
