### PR TITLE
Add CHY logo and info

### PR DESCRIPTION
**Pull request by ConcernPovertyChain**
Add CHY logo and info

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Please add TPT transfer link

**Comment by ConcernPovertyChain** [comment]
ERC-CHY-0x35a23bc27c345b36dee700a256f69c6334030971-https://bscscan.com/tx/0x85fd94d1252543e35540f686c3e10baed6fe4599c4c344ae9e02ba0bc6d6d3d4

Do you not check the transaction records of the wallet?

**Comment by ConcernPovertyChain** [comment]
> 请添加TPT转移链接

ERC-CHY-0x35a23bc27c345b36dee700a256f69c6334030971- https://bscscan.com/tx/0x85fd94d1252543e35540f686c3e10baed646e40d6e4e40d6ae40d6ae309d6

**Comment by ConcernPovertyChain** [comment]
ERC-CHY-0x35a23bc27c345b36dee700a256f69c6334030971-
https://bscscan.com/tx/0x85fd94d1252543e35540f686c3e10baed6fe4599c4c344ae9e02ba0bc6d6d3d4

zhujiayu03 ***@***.***> 于2021年7月9日周五 下午8:37写道：

**Comment by ConcernPovertyChain** [comment]
https://bscscan.com/tx/0xcd32e4bde7c13ecfc51c34dcfb3b5465be3ac4a1b0d137b4fda074cb083aff77

BNB transfer hash

Atlantic Philanthropies ***@***.***> 于2021年7月10日周六
下午11:49写道：

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Pull request closed without merging**
