### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by TAXI80**
https://bscscan.com/tx/0xdceba9efeac0648d02f09d043dde626edfa08886195ad4a8ac9802e83786ac8c?utm_source=tokenpocket

### CODE REVIEW

**Comment by opera0001** [comment]
1、Detect the existence of token increase issuance function, please explain its role
2、Detected the existence of the transaction suspension setting, please explain its role.

**Comment by TAXI80** [comment]
合约里最大铸造是3亿枚，首发只有3000万，其余的2.7亿都需要铸造，总量最多到3亿，超过是增发不了的，等生态上线后会立刻丢掉权限。

**Comment by opera0001** [comment]
I don't see your reply after 2 days, so the order needs to be closed, and you can contact us in Issues if you have questions.

**Comment by TAXI80** [comment]
你好，我上面给你们回复了，这个如果要在上logo，是需要单独的提交吗

**Comment by TAXI80** [comment]
你好，这个是需要重新提交上logo吗 ？  
合约里最大铸造是3亿枚，首发只有3000万，其余的2.7亿都需要铸造，总量最多到3亿，超过是增发不了的













在 2022-07-22 23:16:53，"opera0001" ***@***.***> 写道：

Closed #7804.

**Pull request closed without merging**
