### PR TITLE
Add UnicornCharacter info and logo

### PR DESCRIPTION
**Pull request by fabianvogels**
BSC - UnicornCharacter - 0xd350b4f8322eA54b3bB317C42548fB1933C2fB76 - https://bscscan.com/tx/0xec682b129d70b74515ce91dbea5bc02cfa0c4a37980e062068ad06e7dc50f9f5

### CODE REVIEW

**Comment by opera0001** [comment]
The logo pixel of the token is not 256x256, please modify and resubmit.

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
