### PR TITLE
Add TotoroKitty logo and info

### PR DESCRIPTION
**Pull request by signlogo**
https://bscscan.com/tx/0xea1c25580805a146abf762e592ba61b2797293390b546eba37502c189a334d48

### CODE REVIEW

**Comment by opera0001** [comment]
Abnormal token transaction status

**Comment by opera0001** [comment]
I sent you the problems in contract review 19 hours ago. So far, I haven't seen any changes in token contract, so I need to close the order. After closing the order, you need to submit it again. Please know that the TPT donation fee has increased to 30000.

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
