### PR TITLE
Add Freedom logo and info

### PR DESCRIPTION
**Pull request by bestblockchain**
https://bscscan.com/tx/0x983435b4c2e1a5f028a58c033a3dcf2987072adca4c64affb96450a6cef9c688

### CODE REVIEW

**Comment by opera0001** [comment]
TPNDxw8Y7cnSYX33Az9d3jC2Kt2bqvTTDz--The logo collection of Tron is not supported for the time being.

0x9428978304e5c5428741CaC400411f32b6Ee52DE--done

0x9C960E60AF4801E8393A075b60c8E9Ce508BF167--
The contractual control right has not been abandoned, and there may be control switch function.

**Comment by opera0001** [comment]
I sent you the problems in contract review 8 hours ago. So far, I haven't seen any changes in token contract, so I need to close the order. After closing the order, you need to submit it again. Please know that the TPT donation fee has increased to 30000.

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
