### PR TITLE
Add Aronia logo and info

### PR DESCRIPTION
**Pull request by Alfred131419**
https://bscscan.com/tx/0x002260d438a951a343a1785a6aa186cc1f14baf1ec7da839dd458a8c32520f66

### CODE REVIEW

**Comment by opera0001** [comment]
Detected the presence of a setting in the contract for increasing token issuance; please explain its purpose.

**Comment by Alfred131419** [comment]
> Detected the presence of a setting in the contract for increasing token issuance; please explain its purpose.

The total issuance amount is fixed and immutable, 90% of which is unissued and used for user transaction incentive rewards. There is no additional issuance in the total amount.

**Comment by Alfred131419** [comment]
The total issuance amount is fixed and immutable, 90% of which is unissued and used for user transaction incentive rewards. There is no additional issuance in the total amount.

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Pull request merged**
