### PR TITLE
Add Ascle logo and info

### PR DESCRIPTION
**Pull request by warmbzz**
https://hecoinfo.com/tx/0xfafc2e04552d9145586fda19b5cd3d6aadc5f3d4111b61cbed6d1c68d06bd62c

### CODE REVIEW

**Comment by tiaojiaotubiaobaoguo** [comment]
代提交logo，24小时内包过，加QQ：2980874528

**Comment by sammvio** [comment]
Please donate 3000 TPT as required and submit the transfer link on [Commit changes].

**Review by Linge19494492 — COMMENTED** [review]
https://hecoinfo.com/tx/0xe9676756c07fc8fedc208f63ef2bd20b002fe6750ae91d528a8957ca4e8aaa7a

**Comment by warmbzz** [comment]
> 请按要求捐赠3000 TPT并在【Commit changes】提交转账链接。

https://hecoinfo.com/tx/0xe9676756c07fc8fedc208f63ef2bd20b002fe6750ae91d528a8957ca4e8aaa7a

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
