### PR TITLE
Add SSoca logo and info

### PR DESCRIPTION
**Pull request by Scffre**
Transaction ID link:https://bscscan.com/tx/0x981212e4d9fa8b0a9d890b0a06ccb99246caf343527b79e601a2011bbd90fd2a
Verify the address link:https://bscscan.com/tx/0x84da52ae4efd94c67ce779b8a71af397eefe5cde8dab96708338dd4ae7325dd9

### CODE REVIEW

**Comment by giki0318** [comment]
Your donation hash is from 7days ago. And from a different address. You will be banned from this repo.

**Comment by jjjgjk** [comment]
1212在吗

**Comment by jjjgjk** [comment]
你好

**Comment by tplogotijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
