### PR TITLE
Add SWAN22 logo and info

### PR DESCRIPTION
**Pull request by orexzon**
https://hecoinfo.com/tx/0x8d4ba90aa247d694ebe380c4df77f46644681c0ccee59884237197a39fdc0be5

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3579750034

**Comment by orexzon** [comment]
hi
regarding about my submitted SWAN22 logo and info.

What should i do and what happen for my request. Please response me as soon
as possible.Thank you.

jiasutijiao ***@***.***> 于 2021年12月11日周六 12:17写道：

**Comment by sammvio** [comment]
Please donate 3000 TPT as required and submit the transfer link on [Commit changes].

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Pull request closed without merging**
