### PR TITLE
SPOOKYSHIBA

### PR DESCRIPTION
**Pull request by ChessPeace**
The #1 Horror genre token on the Binance Smart Chain. Not your typical Meme token! 
Stealth Launched 10/28/2021.  SpookySwap, P2E Game, NFT Marketplace and much more to come.
SpookySeasonNeverEnds.  

http://www.spookyshibabsc.com 
tw: @Shibaspooky
TG: t.me/spookyshibaOfficial 
BSC CA: 0xed74bc5dc139356e08de28143996f5ef6e4334a4

https://bscscan.com/tx/0x06f7c9cce6e887f33bf416cb5b13d1a26041aa7a157df4b79d7d1ae044d986be

### CODE REVIEW

**Comment by ChessPeace** [comment]
Please Update SpookyShiba logo ASAP!

**Comment by sammvio** [comment]
Please submit the checksum address that includes uppercase and lowercase characters.

**Comment by ChessPeace** [comment]
SpookyShiba checksum address
*0xed74bc5dc139356e08de28143996f5ef6e4334a4*

**Review by ChessPeace — COMMENTED** [review]
all looks good. when will token logo get updated?

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
