### PR TITLE
Add SUNGOD logo and info

### PR DESCRIPTION
**Pull request by SUNGODToken**
https://bscscan.com/tx/0xe72594bd79fde42bb10c6e09baf7bd55cd0f152fc5dd916a9ddf3ee565b4ae00?utm_source=tokenpocket

### CODE REVIEW

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by opera0001** [comment]
1. Contractual control not waived
2. Insufficient working capital pool
3. Abnormal token transaction status
If it is a new project, please re adjust or optimize it and submit the logo application again. Thank you for your support for tokenpocket.

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
