### PR TITLE
Add VTC logo and info

### PR DESCRIPTION
**Pull request by oneusdt**
https://hecoinfo.com/tx/0x0cc97c41ec7c424dc0357da8e86f6c313ae3808d343e95bd27ae20158645ce54

### CODE REVIEW

**Comment by TokenPocket-JAN** [comment]
Speed ​​up the trial. Please reply to the email if you need.
QQ112831047

**Comment by opera0001** [comment]
Now you need 30000 TPT donation fees to submit the token logo collection. Please supplement and send the hash value to the message of GitHub.

**Comment by oneusdt** [comment]
> 现在您需要 30000 TPT 捐赠费用来提交令牌徽标集合。请补充并发送哈希值到 GitHub 的消息中。

I turned 3000tpt once before, but failed. The last hash is used this time

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request merged**
