### PR TITLE
Add ASC logo and info

### PR DESCRIPTION
**Pull request by armedsquirrel**
BSC - ASC - 0xA5852c1C00AE9D7596bc13526e6Ca096c681E3c8 - https://bscscan.com/tx/0x0f3ad9c7b852d2d3456f237b6049186a38258c0a09aa861e1572d17b45582bae

### CODE REVIEW

**Comment by opera0001** [comment]
Token contract ownership is not discarded, and there is a switch that can control the transaction, which is risky.

Please take the time to modify or discard contract ownership.

**Comment by giki0318** [comment]
your website cannot be accessed while we are reviewing the token.

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
