### PR TITLE
Add WPC logo and info

### PR DESCRIPTION
**Pull request by klaus558**
https://bscscan.com/tx/0x34be9fb9be072ff6c077de4db0378209c956b96785b6898db8d43e270106737c

### CODE REVIEW

**Comment by opera0001** [comment]
It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

**Comment by klaus558** [comment]
> It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

I saw that the instructions for submitting the TP icon did not mention a requirement for the contract to be open-source or to provide an audit report. Is this a mandatory requ?

**Comment by opera0001** [comment]
Yes, because non-open-source code might contain risks. If you can provide the code security audit results from a security company, then it would be acceptable.

**Comment by opera0001** [comment]
Sure, here's the translation:

---

The token contract audit must be open-source to be reviewed. This is, of course, for everyone's safety. If you have special mechanisms that you do not want others to imitate, you can provide a safety statement or certificate from a security company that has audited the code.

**Pull request closed without merging**
