### PR TITLE
ADD CNNB logo and info

### PR DESCRIPTION
**Pull request by LANAO123**
ADD CNNB logo and info

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Please re-submit your files attached TPT transfer link on [Commit changes].

**Review by LANAO123 — COMMENTED** [review]
https://bscscan.com/tx/0x2d28bf87810f867da35c8f340ffcde8fc64a8afa91f99d8381c1b6bccd4a3632

**Comment by LANAO123** [comment]
https://bscscan.com/tx/0x2d28bf87810f867da35c8f340ffcde8fc64a8afa91f99d8381c1b6bccd4a3632

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Pull request closed without merging**
