### PR TITLE
add vpc logo

### PR DESCRIPTION
**Pull request by likedier**
https://bscscan.com/tx/0xd14361dce9b23f4bd2f889e90e4dd6c4b388bd06cc77755972e961a2c721d38c

### CODE REVIEW

**Comment by likedier** [comment]
add vpc logo

**Comment by zhujiayu03** [comment]
Please refer to the tutorial and use the checksum contract address.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
