### PR TITLE
Add EDAO logo and info

### PR DESCRIPTION
**Pull request by ajianggood**
Add EDAO logo and info

### CODE REVIEW

**Comment by ajianggood** [comment]
Add EDAO logo and info

**Comment by ajianggood** [comment]
Add EDAO logo and info

**Comment by opera0001** [comment]
TPT hash value submission not found, please supplement.

**Comment by ajianggood** [comment]
BSC - EDAO - 0x99EEc9a942Dd7cFfe324f52F615c37db3696d4Ba - https://bscscan.com/tx/0xb8b5df718422b6f5cc41faeacff0af94018df69bbbb67a9ec05121762051c793

**Pull request merged**
