### PR TITLE
Add WFP logo and info

### PR DESCRIPTION
**Pull request by qq11001308**
HT-TPT-0x4dFd2f7C0dDeb15735b7C0F554A18d5ECbA08CF7
The chain of the Token submission:HECO
Smart contract of the Token submission:Symbol：WFP
Transaction ID for 1000 TPT:https://hecoinfo.com/tx/0x8b2f80ff67ede6869a7268a667195715521ede61e04ee23df8aba7ccb21600fa
Transaction ID for 0.000001 HT:https://hecoinfo.com/tx/0xe3f2c8879a27f37932dee904d5e1d4eb94cc45e910ff9c43e26ba5b4529a4d91

### CODE REVIEW

**Review by qq11001308 — COMMENTED** [review]
已经快半个月了 麻烦客服大大通过下 急死了...

**Comment by zhujiayu03** [comment]
请提交文件至heco文件夹

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
