### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by tcpglobalc**
BSC - TCP - 0xc26a2bb245e0bced2c2a2671391507fae3630846 - https://bscscan.com/tx/0xbb0054161ace242d378f9e0f70695223ac2dd65349c50f8df7b37c30197a4348

### CODE REVIEW

**Comment by opera0001** [comment]
The hash value is the same as \7477. Please explain. If it is your own hash value, please transfer 0.0000615 BNB to 0x7837ae9e4fd6e967f1b8c8824d6288ece6e730f9 for verification.

**Comment by tcpglobalc** [comment]
> The hash value is the same as #7477. Please explain. If it is your own hash value, please transfer 0.0000615 BNB to 0x7837ae9e4fd6e967f1b8c8824d6288ece6e730f9 for verification.

sent tx：
https://bscscan.com/tx/0x6ee81d13e35b857ae4afe23c4a176fa2f1b2984410df19efdf22270063979cee

**Comment by opera0001** [comment]
Sorry, the logo you submitted is similar to that of tokenpocket and PayPal, so I suggest you adjust it. Thank you.

**Comment by opera0001** [comment]
After 2 days, I didn't see any reply that would change, so I closed the order. If there is a problem, I can go to https://github.com/TP-Lab/tokens/issues contact us.

**Pull request closed without merging**
