### PR TITLE
Add Bitcoin-314 logo and info

### PR DESCRIPTION
**Pull request by xuewest**
0x9b8bb7d07a926311f4c315ff2aef5d5b5217b509051b1beb187ce37235a2ddad

### CODE REVIEW

**Comment by opera0001** [comment]
image
The submitted file is not saved in the BSC directory, please adjust it again.

**Comment by xuewest** [comment]
How do I save this file to the Bsc directory?

**Comment by xuewest** [comment]
0x9b8bb7d07a926311f4c315ff2aef5d5b5217b509051b1beb187ce37235a2ddad

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Comment by xuewest** [comment]
Please arrange TP on your profile picture as soon as possible

**Comment by xuewest** [comment]
Please arrange avatar business as soon as possible

**Comment by xuewest** [comment]
您好，代币符号为Bitcoin-314的代币信息已提交并确认无误，请贵公司尽快通过

**Pull request merged**
