### PR TITLE
Add WOD Logo and Info

### PR DESCRIPTION
**Pull request by axieslp**
代币：WOD
代币合约地址：0x2340eF64a595dfF2c7B2F01fcD3C0D42295b312C
twitter：@WODParallel
代币简介：
The world's first aggregated decentralized trading application with features such as multi chain, multi scenario, and multi application. It adopts AISmart AMM intelligent market makers to effectively solve the pain points of chain listing value. Driven by DAO autonomy and incentive layers, it achieves steady growth in market value and K-line. 
50,000 TPT 的交易ID链接:
https://bscscan.com/tx/0x9803dca3a33920504feccc642809c9d6551566038f50cd3defb44116d4877f3a 
步骤5中验证后的哈希值链接:
https://bscscan.com/tx/0xd288d9984ae2f39868f41c67144070d0e0cad8d1d440aa13343963dbbeca76b2

### CODE REVIEW

**Comment by opera0001** [comment]
image
1. The data was not stored in the BSC directory, so you need to rearrange it.
2. The submitted logo is not 256x256 pixels, please make the necessary changes.
3. External method calls have been detected, which may pose a risk.
4. The detected transactions are not active.

**Comment by axieslp** [comment]
Is there a problem with “The detected transactions are not active.” referring to "步骤5中验证后的哈希值链接: https://bscscan.com/tx/0xd288d9984ae2f39868f41c67144070d0e0cad8d1d440aa13343963dbbeca76b2"?

**Comment by axieslp** [comment]
I fixed all the label 1, 2, 4 issues. For 3, this is the code of the contract https://bscscan.com/token/0x2340ef64a595dff2c7b2f01fcd3c0d42295b312c#code, which is currently only used for testing and not for actual transactions. Please pass the merge request.

**Comment by axieslp** [comment]
Are there any other issues that must be addressed?

**Pull request merged**
