### PR TITLE
Add AMO logo and info

### PR DESCRIPTION
**Pull request by Amo6666**
Hash:
50000TPT:
https://bscscan.com/tx/0x078586a1b155463a090cf4949dc1532a4412475d902dfa85d46d74c99a711feb
BNB:
https://bscscan.com/tx/0x0b39159c10ba60191f7e318103068dd7806c3c56138fbe0b4bb2823746f1ba5a

### CODE REVIEW

**Comment by Amo6666** [comment]
logo

**Comment by Amo6666** [comment]
@Opera0001 Hi, sir, I have made the token contract token public. Please check it

**Comment by opera0001** [comment]
1. Detect the existence of tokens to increase the setting of the issue
2、Detect the setting that can suspend the transaction

Please explain what they do

**Comment by opera0001** [comment]
I did not see your reply after 3 days, so the order needs to be closed and the problem is still not solved, please go to issues and give us feedback.

https://github.com/TP-Lab/tokens/issues

**Pull request closed without merging**
