### PR TITLE
logo & info ( BSC & ERC )

### PR DESCRIPTION
**Pull request by imnotsosmart**

### CODE REVIEW

**Comment by zhujiayu03** [comment]
No 100TPT transfer record

**Comment by imnotsosmart** [comment]
> No 100TPT transfer record

There is ????? 

Let me drop the txid

**Comment by imnotsosmart** [comment]
https://bscscan.com/tx/0x26413c564f2364b62e835c780a0d250ebec15fea2991115910327e7b838bc305

https://bscscan.com/tx/0x9b03b5da0252f24276129cb630e5b41709fe87673935f7d088fa2db4eeb19840

——

https://bscscan.com/tx/0xaa123082d17285d22e99327cb9f51eb86de80a42b6a570b7e586de707ab93cb8

https://bscscan.com/tx/0x7ac5d9a71eda77f78cc444ef160c0732678175cc1cc12da84818f1655079ff0e

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
