### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by vcbvcb83**
https://bscscan.com/tx/0x9afc95be669ad12c646c306ab849893616ea001c8597ee03f63a2033a59f09ff?utm_source=tokenpocket

### CODE REVIEW

**Comment by opera0001** [comment]
We suggest you remove the Chinese characters from the logo as it may be tempting, thanks.

**Comment by vcbvcb83** [comment]
您好，如果不删除可以上传不，还是必须删除。

**Comment by opera0001** [comment]
Delete the re-upload, it does not affect the order number you submitted.

**Comment by vcbvcb83** [comment]
logo

**Comment by vcbvcb83** [comment]
您好，这种可以不

**Pull request merged**
