### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by mikechen1635**
BSC - AFPT - 0x3d8cf39ca44005ff515927f4f4c60dff5c6eca5b - https://bscscan.com/tx/0xa9cbb53b9c060fecf224f1c365f6384c8515f2de9e596b43c997f70f9e0383a3

### CODE REVIEW

**Comment by opera0001** [comment]
Please check the number of TPT submissions.

**Comment by mikechen1635** [comment]
I transferred 5000 tpt, the amount is enough, why do you say the amount is not enough?
https://bscscan.com/tx/0xa9cbb53b9c060fecf224f1c365f6384c8515f2de9e596b43c997f70f9e0383a3

**Comment by mikechen1635** [comment]
I transferred 5000 tpt, the amount is enough, why do you say the amount is not enough?
https://bscscan.com/tx/0xa9cbb53b9c060fecf224f1c365f6384c8515f2de9e596b43c997f70f9e0383a3

**Comment by opera0001** [comment]
Please check the number of tpt

**Comment by mikechen1635** [comment]
How many tpt do you need? I already transferred 5000 tpt,
https://bscscan.com/tx/0xa9cbb53b9c060fecf224f1c365f6384c8515f2de9e596b43c997f70f9e0383a3

**Comment by opera0001** [comment]
Please check the requirements for quantity in the tutorial carefully, thank you.
https://tphelp.gitbook.io/cn/wallet-operation/submit-token

**Pull request closed without merging**
