### PR TITLE
ODT-0x0aE0C11EdFE96111e6e5Cb17f1494C68fBdbbE6b

### PR DESCRIPTION
**Pull request by oumou1234**
https://bscscan.com/tx/0x3a5964c1d6534d93dcc9baef73c92c6c2c55a5134eae936ec860c2e5179e6c4b

### CODE REVIEW

**Comment by oumou1234** [comment]
add ODT logo and info

**Comment by qq2871019009** [comment]
快速提交logo，一天内包过，不过全额退款。加QQ：2871019009

**Comment by oumou1234** [comment]
https://bscscan.com/tx/0x3a5964c1d6534d93dcc9baef73c92c6c2c55a5134eae936ec860c2e5179e6c4b

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request merged**
