### PR TITLE
Submit MVC Token logo

### PR DESCRIPTION
**Pull request by mvcfinance**
0x0e47605bf9a38458e2d344b7bba83ef0971ef839e1e98b5ec4629a57bd68a779

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3579750034

**Comment by sammvio** [comment]
Please refer to the tutorial, and re-submit your files in the correct format.
Please donate 3000 TPT as required and submit the transfer link on [Commit changes].

**Comment by mvcfinance** [comment]
Re-submitted files & tx hash of 3000 TPT & BNB as requiredMVC logo submitted
 #4486

Please check & add MVC logo.

Thank you,
Tara

**Comment by mvcfinance** [comment]
how can we use this? 加速审核2小时内包过！
how's the cost?

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
