### PR TITLE
Add WE logo and info

### PR DESCRIPTION
**Pull request by bisuhjf**
0x396d5163aa8ec0aafb0e1839fdc3c7c87b9bde00328eca0251a975f7ecb08409
0x7b0394552a34929e217df051dbef7ae3bcb0eaea0f19afd23464f6d1c0648f90

### CODE REVIEW

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by opera0001** [comment]
The contract is not open source and its security cannot be viewed. Please re submit the logo application after adjustment.

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
