### PR TITLE
add logo and  info

### PR DESCRIPTION
**Pull request by ccnamz**
付款链接 https://bscscan.com/tx/0x710c7586ea0f7435934ea04ea69e4cbbe8378f9135f46e0134dc72aa4fd44fc3

### CODE REVIEW

**Comment by ccnamz** [comment]
At present, the project is in its early stages, and the transaction rate can be modified to lower the rate. In order to go to the exchange in the future and lower the rate to 0, the agency contract is to add a whitelist to the pre-sale of the project. The current agency contract has been abandoned

**Comment by ccnamz** [comment]
https://github.com/Coinsult/solidity/blob/main/Coinsult_williamhillund_0x6E...CC39_Audit.pdf


this  is  contract  report

**Comment by opera0001** [comment]
Please provide this security audit official audit link.

**Comment by ccnamz** [comment]
https://coinsult.net/ 
 this  is audit official audit link

**Pull request merged**
