### PR TITLE
Add NAGA logo and info

### PR DESCRIPTION
**Pull request by New-NAGA**
HT transfer hash: https://hecoinfo.com/tx/0x91d2f03b9dbf42023e91b568398110b3ae1a54955bdd51612aa5c86e59fc52be
TPT transfer hash: https://hecoinfo.com/tx/0x1392679e1b5080d95999adb4df1222018208b692899d2b0a8795272a7412b653

### CODE REVIEW

**Comment by Naga-Service** [comment]
There was a problem with the previous token, so a new contract was changed. Can you help me remove the previous token logo
.

**Comment by New-NAGA** [comment]
Naga-Service and New-NAGA, 
It's the same person,please

**Comment by New-NAGA** [comment]
There was a problem with the previous token, so a new contract was changed. Can you help me remove the previous token logo,
please help me approve it.thank you very much

**Comment by opera0001** [comment]
The logo on the heco chain previously submitted has been removed. Please wait patiently for the review of this order.

**Comment by New-NAGA** [comment]
> The logo on the heco chain previously submitted has been removed. Please wait patiently for the review of this order.

Okay,Please Approve it  as soon as possible,thank you very much.

**Pull request merged**
