### PR TITLE
Add Mamba info and logo

### PR DESCRIPTION
**Pull request by lcwypn**
https://bscscan.com/tx/0x60e3008f4a48580948de4ae52968d35449377c4afb8cd2ec84eb564275ecf4a6 https://bscscan.com/tx/0xc3491b87f4ef02c1bde94312af5738b5ab59c21c8cbb079edd8c6116e869ef97

### CODE REVIEW

**Comment by opera0001** [comment]
The token contract has a modifiable transaction fee rate, and features for setting up blacklists and whitelists. The token contract has also added the functionality of increased issuance, and the ownership of the token contract has not been abandoned. Therefore, this carries significant risks.

**Comment by lcwypn** [comment]
The problem with our contract is that our coin holders will have dividends, dividends will call the contract, this administrator authority can not be discarded, we can not give holders dividends after discarding, thank you for understanding

**Comment by lcwypn** [comment]
> The token contract has a modifiable transaction fee rate, and features for setting up blacklists and whitelists. The token contract has also added the functionality of increased issuance, and the ownership of the token contract has not been abandoned. Therefore, this carries significant risks.

The problem with our contract is that our coin holders will have dividends, dividends will call the contract, this administrator authority can not be discarded, we can not give holders dividends after discarding, thank you for understanding

**Comment by opera0001** [comment]
If issues are discovered, they will be immediately subjected to blacklisting.

**Pull request merged**
