### PR TITLE
Add BGC AND BORG TOKEN

### PR DESCRIPTION
**Pull request by defi202**
https://www.bscscan.com/tx/0x024208b4ca8dfea4429ca5e42488e896ee9dbae8dbfe389eca31c4bb237fbd3d

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Tron token logo upload is not allowed for now.

**Comment by defi202** [comment]
Two tokens hex:
https://www.bscscan.com/tx/0x024208b4ca8dfea4429ca5e42488e896ee9dbae8dbfe389eca31c4bb237fbd3d
https://www.bscscan.com/tx/0xe5281b7d5b4479cfff6331012696d68ad0cfbb4f7a80cf18f78e03e878448388

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
