### PR TITLE
Add MBX logo and info

### PR DESCRIPTION
**Pull request by yunyou99**
https://bscscan.com/tx/0x1f88b06afea99c184bbd5f7ab6c1f7c0fa466da610274917598d4e6cf00b87ec

During the airdrop phase, Everyone needs to exchange tokens for airdrops，we need to reduced rate to a minimum。This function has now been turned off 。

### CODE REVIEW

**Comment by opera0001** [comment]
It is detected that the token contract has the function of modifying the rate. Please explain its function.

**Comment by yunyou99** [comment]
During the airdrop phase, Everyone needs to exchange tokens for airdrops，we need to reduced rate to a minimum。This function has now been turned off 。

**Comment by yunyou99** [comment]
@opera0001 During the airdrop phase, Everyone needs to exchange tokens for airdrops，we need to reduced rate to a minimum。This function has now been turned off 。

**Comment by yunyou99** [comment]
> It is detected that the token contract has the function of modifying the rate. Please explain its function.

During the airdrop phase, Everyone needs to exchange tokens for airdrops，we need to reduced rate to a minimum。This function has now been turned off 。

**Pull request merged**
