### PR TITLE
Add FINEXIA logo and info

### PR DESCRIPTION
**Pull request by ZWJKFLC**
https://bscscan.com/tx/0xe5ea6fd0e266488d935d7e9b05e19b04ff07667cd07c62bb5e3e42c24df9d5c0

### CODE REVIEW

**Comment by opera0001** [comment]
The submitted logo is not 256x256 pixels. Please adjust it accordingly.

**Comment by ZWJKFLC** [comment]
> Collaborator

The logo has been updated to 256*256

**Comment by ZWJKFLC** [comment]
> The submitted logo is not 256x256 pixels. Please adjust it accordingly.


The logo has been updated to 256*256
@opera0001

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Pull request merged**
