### PR TITLE
0x43b1571a3344e48f54145bcb77c082786f66836b

### PR DESCRIPTION
**Pull request by ZhiZiHhu**
https://bscscan.com/tx/0xb5f148970bad47a22ffd1e3c845f63c5d55cbcb4a272895500a0894dbbbe4fc0

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Please refer to the tutorial and use the checksum contract address.

**Comment by guoxintongsam** [comment]
Please refer to the tutorial and use the checksum contract address.

**Comment by guoxintongsam** [comment]
Please refer to the tutorial and use the checksum contract address.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
