### PR TITLE
Add KunPeng logo and info

### PR DESCRIPTION
**Pull request by fishclub123**
BSC-TPT-0xf8adcab4e750fc1d4092aea48b4bd3d6d11216a5-https://www.bscscan.com/tx/0xbb641bc88bf5cba5dfed77ce7d659c010da47d1bc84d3118c056743079fccf83

### CODE REVIEW

**Comment by giki0318** [comment]
According to the DAO, the donation amount for a logo update has been updated to 30,000 TPT. [Click here for Details](https://snapshot.org/#/tptdao.eth/proposal/0x781abc1ade2ebd082aec4f57b7199d472a2b2850b3df46c8ec37e3b6a1a243c2)

**Comment by TokenPocket-JAN** [comment]
Professional expedited review. Please reply to the email if you need.
QQ112831047

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
