### PR TITLE
Add SMN logo and info

### PR DESCRIPTION
**Pull request by SMN666666**
SMN:
https://bscscan.com/tx/0x20be1bdbafeebe33b017f7ed78565525e86e32431906cd917b47775538297dd8
POTC:
https://bscscan.com/tx/0xe6b6a87ae9e830b8c473db0f63bfb39a52a62344490cfbb925c2a614c4af7fd1

### CODE REVIEW

**Comment by opera0001** [comment]
The token contract has a setting that allows you to suspend transactions, please explain what it does.

A github account can only submit one json and logo application at a time, please submit them separately.

**Comment by SMN666666** [comment]
Hello, there is a set of transaction suspension in the token to avoid too much fluctuation in the token transaction price.

**Comment by SMN666666** [comment]
> The token contract has a setting that allows you to suspend transactions, please explain what it does.
> 
> A github account can only submit one json and logo application at a time, please submit them separately.

Hello, there is a set of transaction suspension in the token to avoid too much fluctuation in the token transaction price.

**Comment by opera0001** [comment]
POCT has completed the merge, the other submitted logo needs to be resubmitted for application, thanks.

**Pull request merged**
