### PR TITLE
Add logo Kshib and info

### PR DESCRIPTION
**Pull request by KaiKenShiba**
Add logo Kshib and info
BSC - KSHIB
https://bscscan.com/tx/0xb981babf9cd6fcd394203304e7b8a1ca06f7a502be0f652e0b62472c92fca7c5

### CODE REVIEW

**Comment by KaiKenShiba** [comment]
https://bscscan.com/tx/0xb981babf9cd6fcd394203304e7b8a1ca06f7a502be0f652e0b62472c92fca7c5

**Comment by KaiKenShiba** [comment]
BSC - KSHIB 
https://bscscan.com/tx/0xb981babf9cd6fcd394203304e7b8a1ca06f7a502be0f652e0b62472c92fca7c5

**Comment by zhujiayu03** [comment]
Please re-submit your files to bsc folder

**Comment by KaiKenShiba** [comment]
Ok,Thanks You

**Comment by KaiKenShiba** [comment]
I sent it back

**Comment by KaiKenShiba** [comment]
I sent it back

[image: Ảnh chụp Màn hình 2021-08-05 lúc 15.24.40.png]

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Pull request closed without merging**
