### PR TITLE
Add CatKing logo and info

### PR DESCRIPTION
**Pull request by dhz5980089**
https://bscscan.com/tx/0x6784acb2da19e3308809f86713c0aa2110ff896ec06b8fd359130385dce245dc

### CODE REVIEW

**Comment by opera0001** [comment]
1. If the ownership is not abandoned, there may be potential risks
2. The item description uses the contents of tokenpocket, which is inconsistent with the item

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
