### PR TITLE
Add FSD logo and info

### PR DESCRIPTION
**Pull request by fantasySpaceGame**
BSC - FSD - 0xf8aB4Be9b19e95B066C42F0935F2e4b1B62D8A71 - https://bscscan.com/tx/0x29dd24b2d91704a8bab3292e4610abaff2e7b50267ff6b2d4dcd03a3ca4b15fd
BSC - FSD - 0xf8aB4Be9b19e95B066C42F0935F2e4b1B62D8A71 - https://bscscan.com/tx/0x8f658ab0706c6d10dc94b9b8612d278bf04837c0e2e14989184524b4663a1810

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Please re-submit these tokens separately and attach the TPT transfer link on [Commit changes].

**Comment by fantasySpaceGame** [comment]
Hey, I have already added the transaction link in the [Commit changes] when I submitted it for the first time.

This token(BSC - FSD - 0xf8aB4Be9b19e95B066C42F0935F2e4b1B62D8A71) is divided into two transactions, one is 1,000 TPT and the other is 2,000 TPT.

The transaction hash is as follows：

1000 TPT :
https://bscscan.com/tx/0x29dd24b2d91704a8bab3292e4610abaff2e7b50267ff6b2d4dcd03a3ca4b15fd

2000 TPT :
https://bscscan.com/tx/0x8f658ab0706c6d10dc94b9b8612d278bf04837c0e2e14989184524b4663a1810

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
