### PR TITLE
Add Fire logo and info

### PR DESCRIPTION
**Pull request by dappbird**
https://bscscan.com/tx/0x52664a607c80d47909228ccd3c1fc9e97b29bef5e5ec4106a540fd78a7e27de2

### CODE REVIEW

**Comment by opera0001** [comment]
No info JSON file, please re submit the logo application after adjustment or optimization. Thank you for your support for tokenpocket.

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
