### PR TITLE
Add NyQuil logo and info

### PR DESCRIPTION
**Pull request by helloshj**
"name": "NyQuil",
 "website": "https://www.admsai.cn",
 "description": "DayQuil戴奎尔马斯克最欣赏的区块链技术天才重建安全信任诞生了NyQuil生态应用代币获得key机构信任BSC底层技术致力于生态化与区块链化拥有令牌可获得全球日分润DOGE权益10%-12%",
 "explorer": "https://bscscan.com/token/0xc86875d594f2CDF3ad15cac093A005981624C65E",
 "type": "BEP20",
 "symbol": "NyQuil",
 "decimals": 6,
 "status": "active",
 "id": "0xc86875d594f2CDF3ad15cac093A005981624C65E"

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3076439606

**Comment by sammvio** [comment]
Please donate 3000 TPT as required and submit the transfer link on [Commit changes].

**Comment by helloshj** [comment]
捐赠3000tpt链接：https://bscscan.com/tx/0xa57e9c0d6d37bf72f685de408071cb17cfcbc7357c518bd0c4134a8acd26a694

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
