### PR TITLE
addpetenicpoly

### PR DESCRIPTION
**Pull request by mehdihamedi**

### CODE REVIEW

**Comment by jjjgjk** [comment]
1212在吗

**Comment by jjjgjk** [comment]
1212在吗

**Comment by jjjgjk** [comment]
1212在吗1212在吗1314

**Comment by jjjgjk** [comment]
1212在吗

**Comment by jjjgjk** [comment]
eeeeeee

**Comment by opera0001** [comment]
1. The TPT donation hash value was not submitted, and now 30000 TPT is required
2. The token needs 256x256 pixels. Please adjust and replace it

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
