### PR TITLE
Add DoDKing logo and info

### PR DESCRIPTION
**Pull request by qys8888**
https://bscscan.com/tx/0xc88a7e9f5db858ca8d36dbe460e3e114e3ef7e6ff64efb49b787055840fea1b2?utm_source=tokenpocket

### CODE REVIEW

**Comment by opera0001** [comment]
1. Website submission risk
2. Switch setting with retrieve ownership
3. There is a token switch that cannot be traded
Please check the possible problems. The TPT donation hash value can be used for secondary use before the logo is not included.

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
