### PR TITLE
Add USDB Logo And Info

### PR DESCRIPTION
**Pull request by usdb-v2**
https://bscscan.com/tx/0xaeb45ddaa744be1b39209a51e598556a1788eac2184c5358d6f01d4956ad0a41

### CODE REVIEW

**Comment by opera0001** [comment]
The existence of hidden owner functionality and the ability to increase token issuance have been detected in the contract, both of which are highly dangerous behaviors.

**Comment by usdb-v2** [comment]
There is no problem with the hidden ones being used by operators to modify the sliding points, and the platform's requirement for additional issuance is accepted by everyone！

**Comment by opera0001** [comment]
The setting of token transaction fees does not necessarily require the use of a hidden owner, so I find this explanation invalid. The hidden owner is a highly dangerous setting.

**Comment by opera0001** [comment]
Dear, the order needs to be closed. You can contact me through issues. The donation hash value link you submitted can be used in the next order submission.

**Pull request closed without merging**
