### PR TITLE
Add PiKing logo and info

### PR DESCRIPTION
**Pull request by sduakh**
https://bscscan.com/tx/0xb46153605d665c7f38e39989a7a0714ff85e957661f980a07dded31f91d41c37

### CODE REVIEW

**Comment by opera0001** [comment]
The hash value and #6835 link submitted are the same, please check. If we find that someone else's link is stolen, we will pull the GitHub account into the blacklist, and the submitted token will not be included.

**Comment by huazai1699** [comment]
This submission is a liar

**Comment by sduakh** [comment]
> The hash value and #6835 link submitted are the same, please check. If we find that someone else's link is stolen, we will pull the GitHub account into the blacklist, and the submitted token will not be included.

I can revalidate the hash value to prove who the liar is

**Comment by sduakh** [comment]
> The hash value and #6835 link submitted are the same, please check. If we find that someone else's link is stolen, we will pull the GitHub account into the blacklist, and the submitted token will not be included.
https://bscscan.com/tx/0x8d97311230cf6268b5e7d516e143823ed16f1504f7034c7a3115921b3c77fa8f
https://bscscan.com/tx/0xbcce27550f7d91e029ac16f2a7d363c3f88ef0c7899c21a21ca3f42848beb8ae

Sorry, the transfer failed before. I resubmitted it again. Sorry
Sorry 
https://github.com/TP-Lab/tokens/pull/6835

**Pull request closed without merging**
