### PR TITLE
Add PDAO logo and info

### PR DESCRIPTION
**Pull request by ABZ44009**
TPT；https://bscscan.com/tx/0x57d49dbcc0063d39ced84bff0bc5c0438d49220deade94787056e633e5aba5e3
BNB；https://bscscan.com/tx/0x57d49dbcc0063d39ced84bff0bc5c0438d49220deade94787056e633e5aba5e3

### CODE REVIEW

**Comment by opera0001** [comment]
A setting that can be provisionally traded is detected, please explain why.

**Comment by ABZ44009** [comment]
发起团队预先添加流动池，然后募资发放对应的cake-LP以达到打散LP的目的。目前正在募集阶段，所以交易暂时未开放。

**Comment by ABZ44009** [comment]
发起团队预先提前添加流动池，然后发放募捐者对应LP的蛋糕——以达到打散LP的目的。目前正在募集阶段，所以交易暂时未开放。

**Comment by ABZ44009** [comment]
The initiating team adds the liquidity pool in advance, and then distributes the LPs corresponding to the fundraisers to achieve the purpose of breaking up the LPs. It is currently in the fundraising stage, so the transaction is not open for the time being.

**Pull request merged**
