### PR TITLE
Add BabyMatic logo and info

### PR DESCRIPTION
**Pull request by armyonfire**
BSC - BabyMatic - 0xb2ce41b71d93d7f5878f985c3e1a87a6229019be - https://bscscan.com/tx/0xc3ec311fa0e88e4365e925ef53799fed2f78673d16d4cb762d91ccb4282edbc1

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Please re-submit your files to bsc folder

**Comment by armyonfire** [comment]
how to i do it??

i've already followed all the steps and i clearly selected BSC folder. how
do u want me to do it? cant u move it for me?

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
