### PR TITLE
Add POT logo and info

### PR DESCRIPTION
**Pull request by meta-point**
https://bscscan.com/tx/0x77deaa1db12861b8e54241d5bc3bbbcebf19261606be1cff4ee552fb77617ed2

### CODE REVIEW

**Review by meta-point — COMMENTED** [review]
logo

Replace it with the latest logo

**Comment by meta-point** [comment]
Replace it with the latest logo

**Comment by opera0001** [comment]
The fees for buying are high and it was found that the rates for token trading can be modified, please explain the reasons for these things.

**Comment by meta-point** [comment]
> 

Because of development needs, rate changes are open to the public.The first week is 30%, the second week is 20%, the third week is 10%, finally adjusted to 0.75, then relinquish permission.

**Pull request merged**
