### PR TITLE
Add STE logo and info

### PR DESCRIPTION
**Pull request by nenrgycoin**
https://hecoinfo.com/tx/0xf4f94c6195335736c181e3fefcabef2f7f53b6c0d5e418acc47484008d7f3ec2

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token

**Comment by nenrgycoin** [comment]
Hello:
3933 and 3817 is a scrip, submission time to generate a new link, please help to review, 3817, thank you







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TP-Lab/tokens"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月16日(星期二) 下午2:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TP-Lab/tokens] Add STE logo and info (PR #3933)





 
Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
