### PR TITLE
Add LAND logo and info

### PR DESCRIPTION
**Pull request by SecondLand**
https://bscscan.com/tx/0x9503c399b05692c254740b05948c80e95809ff7c4e7f027a146a80ca94b0bbe3
https://bscscan.com/tx/0x5a4ab0f24b4e60d0380a0e52d3fd635d77981da47eb0a8f526c215323cfe74be

### CODE REVIEW

**Comment by opera0001** [comment]
It is detected that the function of issuing tokens and suspending token transactions can be added. Please check.

**Comment by SecondLand** [comment]
1.The tokens have the maximum supply, and all of them have been issued.
2.Administrator permissions have been destroyed, destroyed links: https://www.bscscan.com/tx/0x73F6DE718817D180BC85EB66BD51DE89566A13B02C18C0735

**Comment by opera0001** [comment]
image
The hash value you provided is a blank content. It is detected that administrator permission has not been waived.

**Comment by SecondLand** [comment]
Hi
In the token contract of $ LAND, the 『renounceOwnership()』   was not include, and it could not be destroyed to 0x00 ... 000 address.Therefore, we have transferred the management authority to the address of 0x000 ... 001

https://bscscan.com/tx/0x73f6de7188165a717d180bc85eb66ff4bd51d01de89566a1390f3b02c18c0735
image

**Comment by opera0001** [comment]
https://bscscan.com/tx/0x73f6de7188165a717d180bc85eb66ff4bd51d01de89566a1390f3b02c18c0735 This is just an ordinary transfer operation. It is not a contract management right operation, and the contract address is checked. The management right is not discarded. Now close the order, and there is a problem https://github.com/TP-Lab/tokens/issues Feedback questions.

**Pull request closed without merging**
