### PR TITLE
add Godzilla logo and info

### PR DESCRIPTION
**Pull request by Godzilla202**
0xef136433a1408b9cb37af5c8600dfa40e47303d5d70746069a1426c07f051e3e

### CODE REVIEW

**Comment by Godzilla202** [comment]
hi lady/sir, can you help to confirm weather the Godzilla icon branch can be merged? or another information need provide?

**Comment by zhujiayu03** [comment]
Incorrect json. file formate, incorrect logo size

**Comment by Godzilla202** [comment]
thks alot， will update soon！！

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
