### PR TITLE
update DAM info and logo

### PR DESCRIPTION
**Pull request by DoreamonFund**
update DAM logo

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Added

**Comment by DoreamonFund** [comment]
> Added

update ，update ，update

**Comment by DoreamonFund** [comment]
Hello, the updated token icon we submitted was rejected by customer service because it has been added, we are updated, reremit tp, trouble please re-review under the icon application address https://github.com/TP-Lab/tokens/pull/1738

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by daibilogo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
