### PR TITLE
Add MUD logo and info

### PR DESCRIPTION
**Pull request by koala107596**
ETH - MUD - 0x9DC7e4dC7F3F22A897D00DFe5B55f10C174019D5 - https://www.bscscan.com/tx/0x4622cdb92641826accc10219782574d2f748fe1cdb9e1f6bc4894c0c06b8ec3b

### CODE REVIEW

**Comment by koala107596** [comment]
What do I need to do, is there a detailed tutorial?

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Comment by ncijacky** [comment]
> The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Comment by koala107596** [comment]
receive


ncijacky ***@***.***> 于2022年12月16日周五 14:34写道：

**Comment by koala107596** [comment]
How do I need to cooperate now


Robert Z ***@***.***> 于2022年12月16日周五 14:40写道：

**Comment by koala107596** [comment]
Hello, there will be results when I ask, please give me a reply, thank you

Robert Z ***@***.***> 于2022年12月16日周五 14:46写道：

**Pull request merged**
