### PR TITLE
Update CHY info logo

### PR DESCRIPTION
**Pull request by ConcernPovertyChain**
ERC-CHY-0x35a23bc27c345b36dee700a256f69c6334030971-https://bscscan.com/tx/0x85fd94d1252543e35540f686c3e10baed6fe4599c4c344ae9e02ba0bc6d6d3d4

### CODE REVIEW

**Comment by ConcernPovertyChain** [comment]
https://bscscan.com/tx/0xcd32e4bde7c13ecfc51c34dcfb3b5465be3ac4a1b0d137b4fda074cb083aff77
BNB transfer hash

https://bscscan.com/tx/0x85fd94d1252543e35540f686c3e10baed6fe4599c4c344ae9e02ba0bc6d6d3d4
 TPT transfer hash

**Comment by zhujiayu03** [comment]
Added

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
