### PR TITLE
Add NBA logo and info

### PR DESCRIPTION
**Pull request by kalenway**
0x1609dfc208613414a92669f052024ba73825179845c713e5279c74286c964d6d

### CODE REVIEW

**Comment by kalenway** [comment]
this is Transcation Hash

**Comment by kalenway** [comment]
TPT Hash：https://bscscan.com/tx/0x1609dfc208613414a92669f052024ba73825179845c713e5279c74286c964d6d
BNBsubmitinfo Hash: https://bscscan.com/tx/0xd4876ae315da63fb27246b1713ad69380accd155166e96939966a341bbaf2f16

**Comment by opera0001** [comment]
The token has a hidden owner address. Some tokens may nominally relinquish ownership through the "hidden owner" feature, but the hidden owner still controls the token.

image
The submitted file is not saved in the BSC directory, please adjust it again.

**Comment by kalenway** [comment]
The token code cannot be modified, the token is running, can the upload path I modified be accepted?

**Comment by opera0001** [comment]
It is also possible to re-upload a message in this github order.

**Comment by opera0001** [comment]
I didn't see your reply after 3 days, so the order needs to be closed. You can contact me in issues in issues.

https://github.com/TP-Lab/tokens/issues

**Pull request closed without merging**
