### PR TITLE
upload WFBTC logo and info

### PR DESCRIPTION
**Pull request by WFBTC**
WFBTC Fantom ERC20 token offers a secure and transparent way to leverage Fantom’s DeFi opportunities with the backing of Bitcoin.

### CODE REVIEW

**Comment by opera0001** [comment]
The TPT donation hash value was not provided, and it was found that the token contract includes a setting for increasing the token supply. Please explain the reason.

**Comment by WFBTC** [comment]
Hi we are working on making the transaction for the contribution.  In regards to your inquiry (token contract includes a setting for increasing the token supply. Please explain the reason.) Our listing on FTM Scan has a few errors which we told them VIA email for them to rectify. They will soon rectify that and our information will be as it is supposed to be.

**Comment by WFBTC** [comment]
Hi we are working on making the transaction for the contribution. In regards to your inquiry (token contract includes a setting for increasing the token supply. Please explain the reason.) Our listing on FTM Scan has a few errors which we told them VIA email for them to rectify. They will soon rectify that and our information will be as it is supposed to be.

 

Regards

**Comment by opera0001** [comment]
Please inform me after the code adjustments and TPT donation have been completed.

**Comment by WFBTC** [comment]
We will Absolutely do that. WE appreciate your feedback.

 

Regards

**Comment by opera0001** [comment]
Please inform me after the code adjustments and TPT donation have been completed.

**Pull request closed without merging**
