### PR TITLE
add logo info

### PR DESCRIPTION
**Pull request by KatyEileen**
https://bscscan.com/tx/0x3945ada3f8272cbdbc30d6d47959535f87e58da8ec0990ca45e22c46d59f74e4

### CODE REVIEW

**Comment by opera0001** [comment]
The logo uses the flag element and astronaut portrait, which are not in line with the rules. Please modify them again and replace them.

**Comment by KatyEileen** [comment]
邮件已收到，真是太麻烦您了。

**Comment by KatyEileen** [comment]
Hi, this astronaut portrait is an artistic painting, not a specific person, not a photo. I don't know how the portrait should be modified, can you be more specific? Also, the flag modification is not a problem





------------------ Original ------------------
From: opera0001 ***@***.***&gt;
Date: Mon,Jun 6,2022 11:14 PM
To: TP-Lab/tokens ***@***.***&gt;
Cc: KatyEileen ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [TP-Lab/tokens] add logo info (PR #7354)





 
The logo uses the flag element and astronaut portrait, which are not in line with the rules. Please modify them again and replace them.

**Comment by KatyEileen** [comment]
If I say that I add an oxygen mask to the astronaut, covering half of the face, so can it?





------------------ Original ------------------
From: opera0001 ***@***.***&gt;
Date: Mon,Jun 6,2022 11:14 PM
To: TP-Lab/tokens ***@***.***&gt;
Cc: KatyEileen ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [TP-Lab/tokens] add logo info (PR #7354)





 
The logo uses the flag element and astronaut portrait, which are not in line with the rules. Please modify them again and replace them.

**Pull request closed without merging**
