### PR TITLE
Add Plant logo and  info

### PR DESCRIPTION
**Pull request by CDKail**
0x587b99a2e45880e578956cb289f7ec536c122a45b6c6a5054b617e85e99acb09

### CODE REVIEW

**Comment by CDKail** [comment]
TPT: https://bscscan.com/tx/0xcb0f2f125ffeaad61d1858c3478c8b11d8c84465b09478a32dc77ad039801f95
Verify: https://bscscan.com/tx/0x587b99a2e45880e578956cb289f7ec536c122a45b6c6a5054b617e85e99acb09

**Comment by opera0001** [comment]
Detect tokens exist hidden contract owner permissions, this there is a big risk.

**Comment by CDKail** [comment]
Because we still need to adjust the rate, now in the private placement stage, the project will lose all rights in July

**Comment by opera0001** [comment]
This has nothing to do with discard all permissions are, because even lost permissions, then hide the owner still can use the function, you and tokens

**Pull request merged**
