### PR TITLE
Add EDoge logo and info

### PR DESCRIPTION
**Pull request by EXPERTDOGE**
For logo and info update

### CODE REVIEW

**Comment by EXPERTDOGE** [comment]
0xafeb208b41fbca32035b00d1e6318f1078d0a712e46eecb101db8073164bf32f

**Comment by opera0001** [comment]
Please check whether the hash value is correct, and adjust it according to the requirements of the tutorial:https://tphelp.gitbook.io/cn/wallet-operation/submit-token

**Comment by EXPERTDOGE** [comment]
0x28ca438f721dcf4abc102d82887ea42463e944b7867d9839ef637d078676651d

**Comment by EXPERTDOGE** [comment]
> Please check whether the hash value is correct, and adjust it according to the requirements of the tutorial:https://tphelp.gitbook.io/cn/wallet-operation/submit-token

0x28ca438f721dcf4abc102d82887ea42463e944b7867d9839ef637d078676651d

**Comment by EXPERTDOGE** [comment]
https://bscscan.com/tx/0x28ca438f721dcf4abc102d82887ea42463e944b7867d9839ef637d078676651d

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Pull request merged**
