### PR TITLE
Add DMDOGEToken logo and info

### PR DESCRIPTION
**Pull request by So-theBys**
https://bscscan.com/tx/0x7ff52565a1287ee735118fc5fb7dd99e3bf1d48ba78066474f9b7e60d9000ece

### CODE REVIEW

**Comment by So-theBys** [comment]
logo

**Comment by zhujiayu03** [comment]
Please re-submit your files to bsc folder

**Comment by So-theBys** [comment]
This is a new pull request, please help me solve this troublesome problem, thank you my friend
Add DMDOGE Token logo and inof #1317


发自我的iPhone

------------------ Original ------------------
From: zhujiayu03 ***@***.***&gt;
Date: Mon,Jul 12,2021 2:45 PM
To: TP-Lab/tokens ***@***.***&gt;
Cc: So-theBys ***@***.***&gt;, State change ***@***.***&gt;
Subject: Re: [TP-Lab/tokens] Add DMDOGEToken logo and info (#1144)





 
Closed #1144.

**Comment by So-theBys** [comment]
This is a new pull request, please help me solve this troublesome problem, thank you my friend
Add DMDOGE Token logo and inof #1317



发自我的iPhone

------------------ Original ------------------
From: zhujiayu03 ***@***.***&gt;
Date: Mon,Jul 12,2021 2:45 PM
To: TP-Lab/tokens ***@***.***&gt;
Cc: So-theBys ***@***.***&gt;, State change ***@***.***&gt;
Subject: Re: [TP-Lab/tokens] Add DMDOGEToken logo and info (#1144)





 
Please re-submit your files to bsc folder

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
