### PR TITLE
Add Goros logo and info

### PR DESCRIPTION
**Pull request by Gudejian**
https://bscscan.com/tx/0x06a341ed7761ab9c59e284883e826ce924fce17e39b668c0aa10317d85d7341c

### CODE REVIEW

**Comment by opera0001** [comment]
image
The submitted file is not saved in the BSC directory, please adjust it again.

Token transaction detected, please state the situation

Token transaction rate detected can be modified, please explain the effect

Token cooling mechanism detected, please be sure to explain to participants

**Comment by opera0001** [comment]
I haven't seen your reply or feedback after 4 days, so the order needs to be closed. If you need feedback, you can contact me through issues.

https://github.com/TP-Lab/tokens/issues

**Comment by Gudejian** [comment]
I will give you an answer today

**Comment by Gudejian** [comment]
Can I resubmit today? Does the token description need to be written in the info.json file?

**Pull request closed without merging**
