### PR TITLE
Add VH logo and info

### PR DESCRIPTION
**Pull request by jackxukunnnn**
∨ VeChain is a video entertainment sector based on blockchain technology that circulates international digital certificates. V VeChain also commemorates Oscar movie star Audrey Hepburn.

### CODE REVIEW

**Comment by jackxukunnnn** [comment]
∨ VeChain is a video entertainment sector based on blockchain technology that circulates international digital certificates. V VeChain also commemorates Oscar movie star Audrey Hepburn.

**Comment by zhujiayu03** [comment]
Since we cannot find out the 100 TPT transfer record, please attach the record.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
