### PR TITLE
Add Shooting Star to TokenPocket

### PR DESCRIPTION
**Pull request by ShootingStarBSC**
Txn hash for 30.000 TPT: https://bscscan.com/tx/0x2d2497c59e7e3ef1686f79ebf5249f9df702afe3a9d65e6b28effc5a5a4c4c34

### CODE REVIEW

**Comment by Uche1759** [comment]
Cool

**Comment by opera0001** [comment]
Token contract has many control switches, and it is found that the function of ownership can be retrieved. There are risks. Please check and adjust.

**Comment by ShootingStarBSC** [comment]
We are aware of it. the only purpose of the function is because the dev compiled and created the contract. and for that we need to reanounce the owenership.

**Comment by opera0001** [comment]
For the sake of safety, we prefer to see your adjustment.

**Comment by ShootingStarBSC** [comment]
So what adjustment do you want to see

**Comment by opera0001** [comment]
There is an agency contract for tokens. If this is not handled well, it will be a great risk for you or users.

**Comment by ShootingStarBSC** [comment]
understandble but we i can send you a audit for that contract if you want

**Comment by opera0001** [comment]
Of course, this is the best time to start.

**Comment by ShootingStarBSC** [comment]
Audit: https://github.com/ContractChecker/audits/blob/main/Shooting%20Star%20Token%20Security%20Audit%20Report%20-%20By%20ContractChecker.pdf

**Comment by opera0001** [comment]
done

**Pull request merged**
