### PR TITLE
Add DaddyShib logo and info

### PR DESCRIPTION
**Pull request by veryfinance**
BSC - TPT - 0xeca41281c24451168a37211f0bc2b8645af45092 -  https://bscscan.com/tx/0x4b4f2bb2d741cc6c3678e3974baef717ece08604b6a0e60faba593e78403d437

### CODE REVIEW

**Comment by veryfinance** [comment]
daddyShib and luckdoge

**Comment by zhujiayu03** [comment]
Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
