### PR TITLE
Add UNC(BSC) logo and info

### PR DESCRIPTION
**Pull request by warrior21st**
BSC - UNC - 0x2542f13aC5F44B45545dF1Fa4Fe80Ec24b6Bb0a3 - https://bscscan.com/tx/0x3de299c9f6a4c5d85c9993fad0a98fb2a1bd8b9843ea16744c17695d7f3893dd

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3579750034

**Comment by sammvio** [comment]
The contract didn’t verify and publish. (No open-source)

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
