### PR TITLE
Add FITOUT logo and info

### PR DESCRIPTION
**Pull request by DiabloMT**
0x57914dae5d90fe501660af637ecbb05bc17b09612c99e0ea9c9044a288d040fd

### CODE REVIEW

**Comment by DiabloMT** [comment]
is anyone help me to check an submit my logo?

**Comment by DiabloMT** [comment]
how long time i can get result?

**Comment by opera0001** [comment]
The token contract has a variety of control switches. The token holding address is too centralized and not locked.

**Comment by DiabloMT** [comment]
》》The token contract has a variety of control switches. The token holding address is too centralized and not locked.

**Comment by DiabloMT** [comment]
> The token contract has a variety of control switches. The token holding address is too centralized and not locked.

in my contract code the control switches is used operator to set some logic not have transfer and harmful switches. so，and the holding address is use to send bonus to members with contract address. i can do what? please help me again. if the bonus ex. the locked operate is does not affect sending bonus, i can lock it.

**Pull request merged**
