### PR TITLE
Add logo for SHIBSIR

### PR DESCRIPTION
**Pull request by andrewrrogerso0**
TPT - https://bscscan.com/tx/0x8329c62424bdda7691c22b14d88aaa0cb1746e63dfdf4363281effa4a468d711
BNB - https://bscscan.com/tx/0xd389790ebff8c0cb01e5ad9549b4b62fb1692b8debdb34b996fa77cdb0927451

### CODE REVIEW

**Comment by andrewrrogerso0** [comment]
https://www.shibsir.top/ This is the correct website, I hope it is submitted correctly

**Comment by andrewrrogerso0** [comment]
@opera0001 is there any problems with the logo?

**Comment by andrewrrogerso0** [comment]
@opera0001 is there any problems with the logo?

**Comment by opera0001** [comment]
No, because I missed this order O(∩_∩)O

**Pull request merged**
