### PR TITLE
Add THB logo and info

### PR DESCRIPTION
**Pull request by ArikeGame**
3000TPT链接：https://bscscan.com/tx/0xec1195e5e19ed553d9bb4a2ad7e1b8216f71c3f5644d681ee43ae941cd21cab8
步骤5验证链接：https://bscscan.com/tx/0xfca1618b8292368aace46d5f6506c7300ba264b3df9967c763791b12b6391045

### CODE REVIEW

**Comment by opera0001** [comment]
The contract control is not discarded. There may be switch settings to control transactions. Please leave a message on GitHub after adjustment.

**Comment by opera0001** [comment]
The contract control is not discarded. There may be switch settings to control transactions. Please leave a message on GitHub after adjustment.

**Comment by opera0001** [comment]
Now the token logo collection needs to pay 30000 TPT. Please supplement the difference and submit the hash value in GitHub.

**Comment by tplogotijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request merged**
