### PR TITLE
Add AIC logo and info

### PR DESCRIPTION
**Pull request by tubiaotijao**
https://bscscan.com/tx/0x95f067c922a024c92951376dddd79f4418a01c799e6f4eaf86ff908cbf69e810

### CODE REVIEW

**Comment by TokenPocket-JAN** [comment]
Speed ​​up the trial. Please reply to the email if you need.
QQ112831047

**Comment by opera0001** [comment]
Now the token logo application needs 30,000 TPT donations. Please add the difference and leave a message to us on GitHub. Thank you.

**Comment by opera0001** [comment]
A GitHub account can only submit one logo. Please adjust it.

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
