### PR TITLE
Add TX logo and info

### PR DESCRIPTION
**Pull request by whitezhang2209**
https://etherscan.io/tx/0x755687ccb67a418a741652ef8797cf4f7bfa8de92295897868610b6c371a00bd

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Tron token logo upload is not allowed for now.

**Comment by whitezhang2209** [comment]
When can i upload tron token logo?

**Comment by whitezhang2209** [comment]
> Tron token logo upload is not allowed for now.

When can i upload tron token logo?

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
