### PR TITLE
add PGNFT bsc token

### PR DESCRIPTION
**Pull request by yuxiansegn**
0xbcb4308F59afd008424EFb23c9407Db3E6Aa0536
https://bscscan.com/tx/0x5282e3c6a39c680d1689b84289367e449fac6e4238770424ece623b865735ebd

### CODE REVIEW

**Comment by jjjgjk** [comment]
1212在吗

**Comment by jjjgjk** [comment]
121212

**Comment by yuxiansegn** [comment]
你是谁？

**Comment by opera0001** [comment]
The contract is not open source and security cannot be viewed.

**Comment by yuxiansegn** [comment]
Administrator, a big token has been re-issued to open source, the one that was not open source has been destroyed, please verify the new contract address
0x694df947a7560eb0fb5005bb2a4290e18d0c5a4e




---Original---
From: ***@***.***&gt;
Date: Sat, Mar 12, 2022 21:48 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] add PGNFT bsc token (PR #6135)




 
The contract is not open source and security cannot be viewed.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by opera0001** [comment]
It is normal for the time being, but the fund pool has not been added. Please wait patiently for approval.

**Comment by yuxiansegn** [comment]
Admin, you have worked hard, please approve as soon as possible, contract 0x694df947a7560eb0fb5005bb2a4290e18d0c5a4e This is a normal BEP20 token

**Comment by opera0001** [comment]
Please don't worry. The audit is expected tomorrow. Please wait patiently.

**Comment by yuxiansegn** [comment]
0x694DF947A7560eB0Fb5005BB2A4290E18d0c5A4e


管理员合约地址错了



---Original---
From: ***@***.***&gt;
Date: Mon, Mar 14, 2022 14:48 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] add PGNFT bsc token (PR #6135)




 
Merged #6135 into master.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yuxiansegn** [comment]
请删除错误得合约0xbcb4308F59afd008424EFb23c9407Db3E6Aa0536


正确的合约
0x694DF947A7560eB0Fb5005BB2A4290E18d0c5A4e

---Original---
From: ***@***.***&gt;
Date: Mon, Mar 14, 2022 14:48 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] add PGNFT bsc token (PR #6135)




 
Merged #6135 into master.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request merged**
