### PR TITLE
Add LAB v2 logo and info

### PR DESCRIPTION
**Pull request by LABv2**
Little Angry Bunny V2 is committed to provide a decentralized transaction network under Binance Smart Chain (BEP-20) with a maximum circulating supply of 10 septillion. There is no main owner of the LAB token. It is purely in favor to all the admins, moderators, and the community's wise decision-making.

1000 TPT transaction ID link - https://bscscan.com/tx/0xcb0b4ad27454ccc57f4ac18d95a909db2ec58ed37eb8d921a6f932312867db7a

### CODE REVIEW

**Comment by naruthon** [comment]
Hope Little Angry Bunny v2 got logo already

**Comment by zhujiayu03** [comment]
Please refer to the tutorial and use the checksum contract address as the file name.

**Comment by LABv2** [comment]
> Please refer to the tutorial and use the checksum contract address as the file name.

it is said that in ethereum only needs checksum address.can you merge it now

**Comment by LABv2** [comment]
what is the next procedure?

**Comment by LABv2** [comment]
0x07f5cEdeD6B3dba557B3663EDC8941FB37b63945 this is checksum addreess

**Review by LABv2 — COMMENTED** [review]
https://github.com/LABv2/tokens/tree/master/0x07f5cEdeD6B3dba557B3663EDC8941FB37b63945
sir i updated changes with checksum address.

please reopen my request

**Comment by LABv2** [comment]
sir this is new commit i made.

https://github.com/LABv2/tokens/commit/80f3b06662f73464fc808870cdcff39ef3d3f246


please guide me all fine? reopen request and merge logo

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Pull request closed without merging**
