### PR TITLE
Add MEV logo and info

### PR DESCRIPTION
**Pull request by crptojuson**
https://bscscan.com/tx/0x33c85f6978145950e12d9d2fb6b3e08cc8452654390fe9c534e0e4ae7a6ed6d3

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3579750034

**Comment by sammvio** [comment]
Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token

**Comment by crptojuson** [comment]
submitted

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
