### PR TITLE
Add UMH logo and info

### PR DESCRIPTION
**Pull request by bishen1019**
https://hecoinfo.com/tx/0x56775792bf4f735866355c2f5fde4ad9baf46f6851927f6e90a79045d970be90

### CODE REVIEW

**Comment by zhuroujuan** [comment]
未按要求提交

**Comment by zhujiayu03** [comment]
Please refer to the tutorial, and re-submit your files in a correct format.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
