### PR TITLE
Add koifish logo and info

### PR DESCRIPTION
**Pull request by lancesf**
https://bscscan.com/tx/0x0219b2561f85017b12bab8e670a9bede4cc8c526f0e3ffa4c24aa60d229e9012

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Unlisted token, please submit your token at, https://www.tokenpocket.pro/zh/submit/token

**Comment by lancesf** [comment]
> Unlisted token, please submit your token at, https://www.tokenpocket.pro/zh/submit/token

Okay, I've submitted it

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
