### PR TITLE
Add VIC logo and info

### PR DESCRIPTION
**Pull request by VicGithubVic**
https://bscscan.com/tx/0x5069e8012f9faf541a6af64371062637fc4146f7e9766dbada824222bef8b716
verify：https://bscscan.com/tx/0xb10992de1e82ea02cad12d3169baa956013551dd3764bf1ca0190f2298671314
the contract will be open sourced in the near future

### CODE REVIEW

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563代提代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by opera0001** [comment]
I'm very sorry. If the contract code is not open source, you can't check the risk of tokens, or if you can provide the security audit provided by the security agency, it's also OK.

**Pull request closed without merging**
