### PR TITLE
Add SPBTC logo and info

### PR DESCRIPTION
**Pull request by lenteen**
TPT link:https://bscscan.com/tx/0x4ab8a446c9a623b9b2492395134029d208368baf5916f5c6f1ce91fb721a32b0

### CODE REVIEW

**Comment by opera0001** [comment]
A hidden owner permission is detected, what does it do?

**Comment by lenteen** [comment]
Before the formal opening of the transaction, the tax-free address will be set continuously, after the formal opening of the transaction will give up the right to hide

**Comment by lenteen** [comment]
Before the transaction is officially opened, the tax-free address is constantly set up, and the hider permission will be waived after the transaction is officially opened.

**Comment by opera0001** [comment]
So why not set it up so that rates can be changed directly, but leave it hidden?

**Comment by lenteen** [comment]
Because there is no open transaction, users in the white area cannot buy now, and cannot sell with the concealer setting. The white area can buy freely, and the users who develop the transaction will give up the authority of the concealer in the future.

**Comment by lenteen** [comment]
Because there is no open transaction now, whitelisted users cannot buy or sell. Using this hider to set up a whitelist, whitelisted users can buy freely. After the transaction is opened, we will give up the hider permission.

**Pull request closed without merging**
