### PR TITLE
Add GSG logo and info

### PR DESCRIPTION
**Pull request by Kaur323**
TPT捐赠：https://bscscan.com/tx/0x5298f100bdf42dff88c2ab7bb5fa4b8ca46a1c5d7c22784d59eeaf68fd9f397f
BNB交易：https://bscscan.com/tx/0x3295a2567246b15c4a82541c0e53eff4e4bdcc603f9502427d44703248b5f05e

### CODE REVIEW

**Comment by opera0001** [comment]
image
The submitted file is not saved in the BSC directory, please adjust it again.

**Comment by Kaur323** [comment]
> image The submitted file is not saved in the BSC directory, please adjust it again.

**Comment by Kaur323** [comment]
> > 图片提交的文件没有保存在BSC目录下，请重新调整。

How can I move the file to bsc, I can't find the path.TKS!

**Comment by Kaur323** [comment]
> image The submitted file is not saved in the BSC directory, please adjust it again.

how can i move the file to bsc, i can't find the path.tks.

**Pull request closed without merging**
