### PR TITLE
Add VP logo and info

### PR DESCRIPTION
**Pull request by Torahserve**
https://hecoinfo.com/tx/0x803aacbe2c530f80182406d1359a583c83a787ca9593163b30a30c5143e2e6ac

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Please submit the checksum address that includes uppercase and lowercase characters.

**Comment by Torahserve** [comment]
> 请提交包含大写和小写字符的校验和地址。

0xDfff7b414eFd6e2d29669D157423C00c98699b8A

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
