### PR TITLE
add CMPY logo and info

### PR DESCRIPTION
**Pull request by ZHANGMAZ1**
https://bscscan.com/tx/0xf859fdc3491154878d2e3b0f6d3a57d110a4bf678c0790c9bcf22eed7fc57345

### CODE REVIEW

**Comment by ZHANGMAZ1** [comment]
https://bscscan.com/tx/0x5ad9437978acdb64297c3757ac749821852087084ab62c8cac7d1c7ff2ec33a5

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3076439606

**Comment by sammvio** [comment]
This file has conflicting files, please re-submit.

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
