### PR TITLE
Upload logo for BIB

### PR DESCRIPTION
**Pull request by BIBToken**
TPT TXN - https://bscscan.com/tx/0xb35bf5b6b5672b0c28a911cae122b4f6a2e03de398677e25cf60b8dde62815a5 BNB TXN - https://bscscan.com/tx/0x9adc3e032207300ec1e3e8f5fbcd2e40525ee395290d0f7fd171ab1924f9f18f

### CODE REVIEW

**Comment by opera0001** [comment]
Proxy contracts are detected, which can be risky.

**Comment by BIBToken** [comment]
Hi @opera0001 can you please check again for this?

**Comment by opera0001** [comment]
We are very sorry, but tokens with proxy contracts cannot be included unless there is a security audit report for the proxy contract.

**Comment by BIBToken** [comment]
@opera0001 Hi we are getting our report in short, will share it here once we receive.

**Comment by BIBToken** [comment]
[BIBToken (BIB) Token_audit (2).pdf](https://github.com/TP-Lab/tokens/files/9654232/BIBToken.BIB.Token_audit.2.pdf)
@opera0001 our audit report is here

**Comment by BIBToken** [comment]
@opera0001 would like to request can we change the logo as the previous one doesn't seem fit. Sorry for that. #8279 
logo png

**Pull request merged**
