### PR TITLE
Add HappyFcn logo and info

### PR DESCRIPTION
**Pull request by kingberQ**
sample

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Please re-submit your files attached TPT transfer link on [Commit changes].

**Comment by kingberQ** [comment]
差什么

**Comment by kingberQ** [comment]
HECO - HappyFcn - 0xB681837cb559f6763cA7C847432dde420738Fd42 - 0xaf4ae8f51c7d36eece1295b1fa789e40225ed1845e54faf2f57ce24dda0e320b

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
