### PR TITLE
ADD AIR LOGO

### PR DESCRIPTION
**Pull request by Satoshiisgod**
ADD AIR LOGO

### CODE REVIEW

**Comment by Satoshiisgod** [comment]
BSC - AIR - 0xd8a2aE43Fd061d24acd538e3866Ffc2c05151b53 - https://bscscan.com/tx/0x61854586addb0847f9ac72a7ad4ef267a11cc8faf79f5615d01cfd106cea3e36

**Comment by Satoshiisgod** [comment]
AIR info is already merged on Github, but the LOGO is not displayed in the wallet APP.

So I resubmitted a new Pull Request and donated another 3000 TPT.

Here is the AIR info in the official Repo:

 https://github.com/TP-Lab/tokens/tree/master/bsc/0xd8a2aE43Fd061d24acd538e3866Ffc2c05151b53

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:2980874528

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by lsunabc** [comment]
0xA32C746576c44dABc560C35547a3C94bCe7c11ca

**Pull request closed without merging**
