### PR TITLE
add GHTKING logo and info

### PR DESCRIPTION
**Pull request by q573927428**
TPT交易链接：https://bscscan.com/tx/0x578ea7218c7b3a9fb2b0d9ae469b5913d327a564c0bb59ecf17e23b93b10d8ea
验证链接：https://bscscan.com/tx/0x70b6d5d49c7faceb6aec0e56a325b480a1e5ca3d9a2ff876a2c4e946023f3f68

### CODE REVIEW

**Comment by opera0001** [comment]
Please check the TPT quantity, thank you.

**Comment by q573927428** [comment]
> Please check the TPT quantity, thank you.

Sorry, I didn't notice the price increase. I only transferred 30000 and still need to make up 20000. How can I make up the price difference?

**Comment by q573927428** [comment]
> Please check the TPT quantity, thank you.

Can I transfer 20000 according to the previous method and verify it?

**Comment by q573927428** [comment]
> Please check the TPT quantity, thank you.

TPT交易链接：https://bscscan.com/tx/0xb0ba4a52821e1ed66ea8b1248c1dd081edc7418e0528f4bdbe7dfb9398e6fd45
验证链接：https://bscscan.com/tx/0x07c6a346dba2181cb7d5c0c5f55bb553452cd8c7a0b2aac29edc37582ae79bc4
The price difference has been replenished, please confirm

**Pull request merged**
