### PR TITLE
add ANT logo and info

### PR DESCRIPTION
**Pull request by antdao-01**
50000TPT:
https://bscscan.com/tx/0x3dc896dc016bc0d114627164a0596a17096914419c3d259775b359e964f0f790

https://bscscan.com/tx/0x1f413ea99792c02b54ed646866d1b2cf7ebe0668fceae860880f403508b93457

name:  AntDao
symble: ANT

### CODE REVIEW

**Comment by opera0001** [comment]
1. The function that can increase the issuance of tokens is detected, please explain its function 
2.. The hidden owner permission is detected, which may have great risks

**Comment by antdao-01** [comment]
1. The total amount is fixed. At present, the token has been distributed, and there is no risk of additional issuance.
2. Hide the owner problem, because the contract has been launched, it cannot be solved temporarily, but the project party can handle this risk
3. Hope to update the logo information as soon as possible, thank you very much

**Comment by opera0001** [comment]
What does the hidden owent permission contain? Or what address does it point to?

**Comment by antdao-01** [comment]
No hidden permissions, the address pointed to is the same as the current owner
0x5672530afb9F12f09C0CA64DB9f8E7d60685389F

**Pull request merged**
