### PR TITLE
Add Odin Logo

### PR DESCRIPTION
**Pull request by OdinJoseph**
https://bscscan.com/tx/0x12a26c724c634f296ee50dae55ab640b7a11cbe29a2272e72ba47b44c9c60507

### CODE REVIEW

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by opera0001** [comment]
1. Now the donation fee of 30000 TPT is required to submit the logo. Please supplement the difference and submit the hash value in GitHub
2. Logo is not 256x256 pixels
3. The order will be closed 24 hours after the reply. Please adjust it quickly.

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
