### PR TITLE
Add STE logo and info

### PR DESCRIPTION
**Pull request by nenrgycoin**
Stone Token Ver3.1415(STE) based on fire currency development, completely on autonomous community DAO!

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Please donate 3000 TPT as required and submit the transfer link on [Commit changes].

**Comment by nenrgycoin** [comment]
您好：
　　3000 TPT的链接已提交！谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TP-Lab/tokens"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月5日(星期五) 下午3:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TP-Lab/tokens] Add STE logo and info (PR #3817)





 
Please donate 3000 TPT as required and submit the transfer link on [Commit changes].
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nenrgycoin** [comment]
您好：
　哈希链接已经提交，请帮忙审核，谢谢！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TP-Lab/tokens"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月5日(星期五) 下午3:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TP-Lab/tokens] Add STE logo and info (PR #3817)





 
Please donate 3000 TPT as required and submit the transfer link on [Commit changes].
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nenrgycoin** [comment]
您好
&nbsp; &nbsp; &nbsp; ＳＴＥ代币资料和3000ＴＰＴ都提交了两个星期了，没动静，各项工作给耽搁了，请帮忙审核通过一下！谢谢！
　　代币：ＳＴＥ
　合约：0xee01453fa85D58a275a4d1984b2cDFCb471990c9
　3000TPT链接：https://hecoinfo.com/tx/0xf4f94c6195335736c181e3fefcabef2f7f53b6c0d5e418acc47484008d7f3ec2





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TP-Lab/tokens"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月5日(星期五) 下午3:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TP-Lab/tokens] Add STE logo and info (PR #3817)





 
Please donate 3000 TPT as required and submit the transfer link on [Commit changes].
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nenrgycoin** [comment]
您好：
请问代币审核怎么样了？给您发了几份邮件！我们这边非常着急！ 请帮忙审核通过一下，非常感谢！

---Original---
From: ***@***.***&gt;
Date: Fri, Nov 5, 2021 15:48 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] Add STE logo and info (PR #3817)




 
Please donate 3000 TPT as required and submit the transfer link on [Commit changes].
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Review by nenrgycoin — COMMENTED** [review]
3000TPT链接：https://hecoinfo.com/tx/0xf4f94c6195335736c181e3fefcabef2f7f53b6c0d5e418acc47484008d7f3ec2

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
