### PR TITLE
Add SCAT logo and info

### PR DESCRIPTION
**Pull request by NongMinZC**
https://bscscan.com/tx/0xd9fa8b33dbc179b695c1ad81c4975743469d73aa95baec84eaaaa5b891b5a642?utm_source=tokenpocket

### CODE REVIEW

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by opera0001** [comment]
The management right of token contract has not been given up, and there may be some risks. Please explain and resubmit the logo application. Thank you for your support of tokenpocket.

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
