### PR TITLE
MATIFI Token has paid 1000TPT

### PR DESCRIPTION
**Pull request by lebreojames**

### CODE REVIEW

**Comment by lebreojames** [comment]
How can I find out that my logo has been approved and is in the list?

**Comment by zhujiayu03** [comment]
Please re-submit your files in the correct format.

**Comment by lebreojames** [comment]
> Please re-submit your files in the correct format.
i shoud delete this previous fork and re-submit?

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
