### PR TITLE
ADD CS logo and info

### PR DESCRIPTION
**Pull request by skyofcity88**
https://www.bscscan.com/tx/0xf7f792e034a17ad63122e05dd8137a39b4b7286e1f637383c637f5b9f895967f

### CODE REVIEW

**Comment by opera0001** [comment]
If the contract is not open source, there may be some risks. Please re submit the logo after adjustment or optimization. Thank you for your support for tokenpocket.

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
