### PR TITLE
Add cname logo and info

### PR DESCRIPTION
**Pull request by chloepnc**
thank you

### CODE REVIEW

**Comment by opera0001** [comment]
Snipaste_2022-03-08_17-11-59
The suffix of the submitted file is wrong. Please replace the content after adjustment.

**Comment by chloepnc** [comment]
Hiii so sorry about that

here you go, the attached is the json file,

Please kindly helo us.  Thank you so much.

opera0001 ***@***.***> 于2022年3月8日周二 17:13写道：

**Comment by chloepnc** [comment]
or could you tell how can i replace it

posy chen ***@***.***> 于2022年3月9日周三 14:25写道：

**Comment by opera0001** [comment]
Follow the steps at the beginning of the tutorial to pull the JSON file again and submit the order to GitHub to see if it is OK?

**Comment by tplogotijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by chloepnc** [comment]
你个比
你他么
你骗了我qian haiyaolai1

麻痹猪狗不如

542132364 ***@***.***> 于2022年3月18日周五 00:41写道：

**Pull request closed without merging**
