### PR TITLE
Add MXLY-DogeKing logo and info

### PR DESCRIPTION
**Pull request by 2705714131**
https://bscscan.com/tx/0xb160582473503046ae2e5dc687d745f73e531ec9117b8f12cd7e69f77bfcae5d

### CODE REVIEW

**Comment by opera0001** [comment]
1. Insufficient token liquidity
2. It is found that there may be blacklist function
3. It is found that there may be a function of controlling transaction switch

**Comment by 2705714131** [comment]
Too disappointed

What shall I do?

---Original---
From: ***@***.***&gt;
Date: Sat, Feb 19, 2022 16:34 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] Add MXLY-DogeKing logo and info (PR #5581)




  
Insufficient token liquidity 

It is found that there may be blacklist function 

It is found that there may be a function of controlling transaction switch 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
