### PR TITLE
SMC积分

### PR DESCRIPTION
**Pull request by 77887sad**
哈希值链接
https://bscscan.com/tx/0x854ce25be759eefebb18b533784ec980f6a16295ad83ba8736d5296190a0136f

### CODE REVIEW

**Comment by 77887sad** [comment]
舜美积分

**Comment by 77887sad** [comment]
> 舜美积分
https://bscscan.com/tx/0x854ce25be759eefebb18b533784ec980f6a16295ad83ba8736d5296190a0136f

**Comment by 77887sad** [comment]
sample

**Comment by opera0001** [comment]
1、0xa6660E62c223Df2D9Aff0Ba188f1371087fa3Dd6 
tokens need to history submit account number: openfirevip to apply

2、0x53A6D980F98009428044e55f55D7486f3518D612 
It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

**Comment by opera0001** [comment]
24 hours later did not see your reply, so you need to close the order first, subsequent questions can go to issues to contact us: https://github.com/TP-Lab/tokens/issues

**Pull request closed without merging**
