### PR TITLE
Add Uncm logo and info

### PR DESCRIPTION
**Pull request by fabianvogels**
BSC - Uncm - 0x45DC529cD122356874934Aa862C8c7E5b21C92C8 - https://bscscan.com/tx/0xee05ad2f4b04415781891a3240f468a96248fe1c270217ff97b173d0476876b2

### CODE REVIEW

**Comment by opera0001** [comment]
The logo pixel of the token is not 256x256, please modify and resubmit.

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
