### PR TITLE
Add GBC token logo info

### PR DESCRIPTION
**Pull request by tecsonchan**
BSC-GBC-0x7031f489e92481a08e212d19feedd8ef7f9f1e7a-https://bscscan.com/tx/0x29c898dc3a74af288e625538a289d898471503fe6718e4f36c46501c1955f95d

Add GBC logo Info 
The chain of the Token submission: BSC
Smart contract of the Token submission: Symbol：GBC  
Contract Address：0x7031f489e92481a08e212d19feedd8ef7f9f1e7a
Transaction ID for 1000 TPT: https://bscscan.com/tx/0x29c898dc3a74af288e625538a289d898471503fe6718e4f36c46501c1955f95d
Transaction ID for 0.000001 BNB: https://bscscan.com/tx/0x32001708a51db735cfe189b35a3e18737d683d40eb0c2d0e1f2a77ca5c5f7c63

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token

**Comment by tecsonchan** [comment]
Hi， TP-Lab team


&nbsp; we already submit our token as below:





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TP-Lab/tokens"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月21日(星期三) 中午11:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TP-Lab/tokens] Add GBC token logo info (#1505)





 
Closed #1505.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
