### PR TITLE
Add DB logo and info

### PR DESCRIPTION
**Pull request by master16236795**
https://bscscan.com/tx/0x4613daed22382560f98ea468a72d20ba0a1a8e5ea792a4df02759fda790078d5

### CODE REVIEW

**Comment by master16236795** [comment]
These functions are what we need and can be made public without any concealment

**Comment by master16236795** [comment]
The community needs tokens that can be issued, managed, and fully functional, just like USDT
________________________________
发件人: Master ***@***.***>
发送时间: 2024年3月21日 12:31
收件人: TP-Lab/tokens ***@***.***>
主题: 回复: [TP-Lab/tokens] Add DB logo and info (PR #10443)

These functions are what we need and can be made public without any concealment
________________________________
发件人: opera0001 ***@***.***>
发送时间: 2024年3月21日 12:19
收件人: TP-Lab/tokens ***@***.***>
抄送: master16236795 ***@***.***>; Author ***@***.***>
主题: Re: [TP-Lab/tokens] Add DB logo and info (PR #10443)


The contract address contains hidden owner permissions, and there is a function to increase token issuance, which can be very dangerous.

―

**Comment by master16236795** [comment]
These functions are what we need and can be made public without any concealment
________________________________
发件人: opera0001 ***@***.***>
发送时间: 2024年3月21日 12:19
收件人: TP-Lab/tokens ***@***.***>
抄送: master16236795 ***@***.***>; Author ***@***.***>
主题: Re: [TP-Lab/tokens] Add DB logo and info (PR #10443)


The contract address contains hidden owner permissions, and there is a function to increase token issuance, which can be very dangerous.

―

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Pull request closed without merging**
