### PR TITLE
 Add lianlian logo and info

### PR DESCRIPTION
**Pull request by DogeKiNG2022**
https://bscscan.com/tx/0x792d23e1bc2591fc18f8dc63d04b9503130bcce01d090891bfe9cc6ee9d4c62e

### CODE REVIEW

**Review by DogeKiNG2022 — COMMENTED** [review]
https://bscscan.com/tx/0x792d23e1bc2591fc18f8dc63d04b9503130bcce01d090891bfe9cc6ee9d4c62e

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by opera0001** [comment]
1. Abnormal token transaction status
2. The submitted logo has infringement

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
