### PR TITLE
Update oko logo and ingo

### PR DESCRIPTION
**Pull request by okoFlying**
1000TPT转账交易:  https://bscscan.com/tx/0x021d56d5c6d57ceffb83f67e09b2d9dbb7f1072075c939fb2444d10783be24e6

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Please refer to the tutorial, and re-submit your files in the correct format.

**Comment by okoFlying** [comment]
> 请参阅教程，并以正确的格式重新提交您的文件。

The format is correct. The submission has been merged before. This time, only the logo is updated. What's the problem???

**Comment by okoFlying** [comment]
> 请参阅教程，并以正确的格式提交您的文件。

Please clearly point out where the problem is and where the format is incorrect so that I can change it again

**Comment by guoxintongsam** [comment]
Please refer to the tutorial, and re-submit your files and logo in the correct format.

**Comment by okoFlying** [comment]
> 请参阅教程，并以正确的格式重新提交您的文件和徽标。

The modified submitted, please merge, thank you very much
https://github.com/TP-Lab/tokens/pull/2841

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Pull request closed without merging**
