### PR TITLE
Add babysun logo and info

### PR DESCRIPTION
**Pull request by BIGsharkX**
1000tpt:https://hecoinfo.com/tx/0x1df869f50ac3588a19b24f889abb5bd123901a28ebbd42d972ced5cabd4e96bb
heco:https://hecoinfo.com/tx/0x69164b495e6f999ab813c5cac7246191bf002d9d3d6033634124cd9444e0796f

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Please refer to the tutorial, and re-submit your files in the correct format.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
