### PR TITLE
Add JXRY logo and info

### PR DESCRIPTION
**Pull request by laopowan**
https://bscscan.com/tx/0xf0a0d5e84d492c9379238f1c550234e49dc4e7f7be583d1863437569a06768cd?utm_source=tokenpocket

### CODE REVIEW

**Comment by TokenPocket-JAN** [comment]
Speed ​​up the trial. Please reply to the email if you need.
QQ112831047

**Comment by opera0001** [comment]
Now you need 30000 TPT donation fees to submit the token logo collection. Please supplement and send the hash value to the message of GitHub.

**Comment by laopowan** [comment]
https://bscscan.com/tx/0xf0a0d5e84d492c9379238f1c550234e49dc4e7f7be583d1863437569a06768cd

**Comment by laopowan** [comment]
3000TPT早打过了，上传了好几回，都没有通过，一开始邮件说是没检测到池子，现在又说是没有打3000ＴＰＴ,麻烦处理

**Review by laopowan — COMMENTED** [review]
https://bscscan.com/tx/0xe11cb2b719f596ba5effa078db405aedd25bf7b21a2819a0885930f133dca9cf

**Comment by laopowan** [comment]
前两次没看清是30000，还以为是3000，这次麻烦尽快处理
https://bscscan.com/tx/0xe11cb2b719f596ba5effa078db405aedd25bf7b21a2819a0885930f133dca9cf

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
