### PR TITLE
Add UFO logo and info

### PR DESCRIPTION
**Pull request by kkoo102**
https://bscscan.com/tx/0xbb392dce1b6f40dd7203d0a71c79610e2e090ac7375f4df3e2fdceda575fa73c

### CODE REVIEW

**Comment by opera0001** [comment]
It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

**Comment by kkoo102** [comment]
Published contract code

**Review by kkoo102 — COMMENTED** [review]
Contract code announcement

**Review by kkoo102 — COMMENTED** [review]
Add UFO logo and info

**Pull request merged**
