### PR TITLE
KOI的BSC审核

### PR DESCRIPTION
**Pull request by jackisgit**
name：KOI
descroption ：KOI - NFTtraffic based application aggregation platform

https://www.bscscan.com/tx/0x4d924ce11ffd95b4ddeab8397624ef0f278b2a7f2a729b832f93bcdfd3c9dfe5

### CODE REVIEW

**Comment by jackisgit** [comment]
name：KOI
descroption ：KOI - NFTtraffic based application aggregation platform

https://www.bscscan.com/tx/0x4d924ce11ffd95b4ddeab8397624ef0f278b2a7f2a729b832f93bcdfd3c9dfe5

**Comment by guoxintongsam** [comment]
The contract didn’t verify and publish.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
