### PR TITLE
ADD PTG info and logo

### PR DESCRIPTION
**Pull request by pmj0812**
30000TPT hash：https://bscscan.com/tx/0x4ba277d10040cd2122806aeb36b6e647ec504635a62c0123efb14da4244471a9
info  hash:  https://bscscan.com/tx/0x0c762cbfe56007a72929c1c22990239b401d1e25c37913004ac8059d99abe00c

### CODE REVIEW

**Comment by opera0001** [comment]
The token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to open the code, the audit report of the security audit department can be provided.

**Comment by pmj0812** [comment]
I have publish my contract code and verify, please recheck my request

**Comment by opera0001** [comment]
Abnormal token circulation status

**Comment by pmj0812** [comment]
I just don't have the open transaction function for the time being, because the previous contract was conquered by scientists, so I updated the new contract, the original contract address is 0xa1c332FaaedEf59B9e16a00898A3c92278c56dC2。Do I need to wait for the transaction to open before submitting for review or other reason?

**Pull request closed without merging**
