### PR TITLE
ADD FV logo and info

### PR DESCRIPTION
**Pull request by futureverse1**
FV token is a metaverse cryptocurrency issued by FutureVerse, dedicated to incubating metaverse related tokens!

https://bscscan.com/tx/0x0d02d3c624d1d5dd2c45368485688e50e983838b0cf7f54675d6e314d6303078

### CODE REVIEW

**Comment by opera0001** [comment]
1. The contract ownership is not abandoned, and there are certain potential safety hazards
2. There may be additional issuance function

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
