### PR TITLE
 Add Info and Logo

### PR DESCRIPTION
**Pull request by TokenLogos**
https://bscscan.com/tx/0x7c2615f9ee888eba1de934c2090185f304c3f4bc3236218231b063e319ae7c3d

### CODE REVIEW

**Comment by giki0318** [comment]
pls commit your verification hash.

**Comment by TokenLogos** [comment]
1. TPT transfer hash link:
    https://bscscan.com/tx/0x7c2615f9ee888eba1de934c2090185f304c3f4bc3236218231b063e319ae7c3d
2. BNB verification hash link:
    https://bscscan.com/tx/0x2e64aa765e8cfa05dd4e420004756a2aab7ec2f241d237f47e66c5e42822c5aa

**Comment by TokenPocket-JAN** [comment]
Speed ​​up the trial. Please reply to the email if you need.
QQ112831047

**Comment by opera0001** [comment]
The ownership of token contract has not been given up, and there is a switch that can control the transaction. Please hurry up and leave us a message on GitHub after adjustment.

**Comment by TokenLogos** [comment]
1.  This contract should used in Dapp, So need  control to make some changes.
     Dapp’s website is 'https://www.bj1913.com'.
2.  Dapp is lp earn BJ and USDT.
    So dapp should user deposit lp to dapp’s contract and should the user's CAKE-LP permission.

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request merged**
