### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by PORSCHEtp**
BSC-PORSCHE-0x32ff096F0B331d4A397C70d21ED6Bf65D75d9112- https://bscscan.com/tx/0xa8f57418fce5946ed7ed9e59e3c035e33a914af4ec0a449bf7c62742e72a89f3 https://bscscan.com/tx/0xa0c80f123c461a93a4bb7046e4fe249bcecd2888a4aedfd40a226a52e5e54516

### CODE REVIEW

**Comment by opera0001** [comment]
The submitted logo involves infringement, please modify it.

**Comment by PORSCHEtp** [comment]
image

**Comment by PORSCHEtp** [comment]
you
looklook

**Comment by opera0001** [comment]
Although the letters are removed, the main content of the logo is still the same, so I'm sorry for this. Besides, the size of the logo provided later is not 256x256, please adjust it again and send it to me, thank you.

**Comment by PORSCHEtp** [comment]
logo

**Comment by PORSCHEtp** [comment]
This should be no problem

**Comment by opera0001** [comment]
Ok, we'll deal with it later. Thank you very much for your cooperation.

**Pull request merged**
