### PR TITLE
Add LaEeb logo and info

### PR DESCRIPTION
**Pull request by tangronglilaeeb123**
30000TPT ：https://bscscan.com/tx/0xeac7b5af65fad470f6daacf03dd4013260e28f307e415afa94cc3438aff323b9
写入链上：https://bscscan.com/tx/0xb9c72e5aaef51fcbd912182844996a6e0522f368d64fdb37cd319ba0edfc0e42

### CODE REVIEW

**Comment by opera0001** [comment]
The logo file is not submitted, please supplement.

**Comment by tangronglilaeeb123** [comment]
The logo file has been submitted, please review

**Comment by opera0001** [comment]
Logo body and text are not suitable

**Comment by tangronglilaeeb123** [comment]
The logo file has been submitted, please review

**Comment by opera0001** [comment]
It is recommended that you refer to the logos already included in your wallet for adjustment, because they are so similar.

**Comment by tangronglilaeeb123** [comment]
The logo file has been submitted, please review

**Comment by tangronglilaeeb123** [comment]
The logo file has been submitted, please review

**Pull request merged**
