### PR TITLE
Add DogePi logo and info

### PR DESCRIPTION
**Pull request by TPQ404544957**
30000TPT:
https://bscscan.com/tx/0xa4b7072eb253da0be98b792d0adb336f0d47bb26b591c5413737b95e8c40bb25
BnbTX:
https://bscscan.com/tx/0xd667579272a22c1f46514b2c05e14306d01e33dc0fd2a61e994481b2928deb54

### CODE REVIEW

**Comment by TPQ404544957** [comment]
@opera0001       Please check my request. Thank you

**Comment by opera0001** [comment]
The submitted TPT hash value is the same as the #6707 order. Please explain the reason.

**Comment by TPQ404544957** [comment]
Sorry, it's my mistake. I've modified it

**Comment by TPQ404544957** [comment]
30000TPT：
https://bscscan.com/tx/0x929d2cf2d42f2a3ee1f3b56a9d672c6f90267d203d4b9ed9ef0f6f991212c4f8
BnbTX：
https://bscscan.com/tx/0xf57cb5a67d630373c25028b8e3b6337cd251d7de5366d9343cc3a80fc7d57aa2


@opera0001 Please check my request. Thank you

**Comment by TPQ404544957** [comment]
@opera0001 Please check my request. Thank you

**Pull request closed without merging**
