### PR TITLE
add OKC  logo and  info

### PR DESCRIPTION
**Pull request by zhangshoushu**
HECO-OKC-0xb3a8b2e1986c113b96d6085f39a2c2c895231971-https://hecoinfo.com/tx/0xb9927b61d86f7ee0df6fded5086431df285a0e91f23dd4537a191e70c1c91560

### CODE REVIEW

**Comment by zhangshoushu** [comment]
以最后一次重新提交的信息为准，谢谢您！

**Comment by zhangshoushu** [comment]
https://github.com/TP-Lab/tokens/pull/1083/commits/7f9e75a587c26ac830311d7fc4bca964b897e85b

**Comment by zhangshoushu** [comment]
以最后一次提交的为准，辛苦您了，非常感谢！

**Comment by zhujiayu03** [comment]
Please submit your files to heco folder

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Pull request closed without merging**
