### PR TITLE
ADD HKD logo and info

### PR DESCRIPTION
**Pull request by HKDLabs**
https://bscscan.com/tx/0x673046a9dca6f6122d796b5fea081e530b415ba32cfbe6a5d22f4c6f8e1a8bd9  50000TPT
https://bscscan.com/tx/0x13160e0a8bc5ea99c48f63b0f7d0c25e73cf5c5ebee73e31d774d814b3d9a09f

### CODE REVIEW

**Comment by opera0001** [comment]
Detected that the transaction rate can be modified, please explain its function.

**Comment by HKDLabs** [comment]
Buy 0 sell 1, the tax rate is temporarily controlled for 2 minutes during launch and changed to 20 to eliminate robots

**Comment by HKDLabs** [comment]
Buy 0 sell 1, the tax rate is temporarily controlled for 2 minutes during launch and changed to 20 to eliminate robots

**Comment by HKDLabs** [comment]
audit   https://app.solidproof.io/projects/hongkongdao

**Pull request merged**
