### PR TITLE
Add DBG logo and info

### PR DESCRIPTION
**Pull request by qq1716404005**
BSC-DBG-0xE1144C736E9419A3524D1e8394F357b494D6B4C2-https://bscscan.com/tx/0x550230275c8925fa8408549b0e756640eabb99df6cb20bca6d213b01e5aa2ce2

### CODE REVIEW

**Comment by qq1716404005** [comment]
Pls check

**Comment by opera0001** [comment]
Please carefully follow the tutorial.

https://tphelp.gitbook.io/cn/wallet-operation/submit-token

**Comment by qq1716404005** [comment]
1

**Comment by qq1716404005** [comment]
Has been strictly implemented in accordance with the requirements, please review&nbsp;



---Original---
From: ***@***.***&gt;
Date: Tue, Mar 22, 2022 23:05 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] Add DBG logo and info (PR #6341)




 
Please carefully follow the tutorial.
 
https://tphelp.gitbook.io/cn/wallet-operation/submit-token

**Pull request closed without merging**
