### PR TITLE
add MetaBaby info and logo

### PR DESCRIPTION
**Pull request by asas1232**
3000tpt : https://bscscan.com/tx/0xabb8c3121de37dd657fe9921c0279dd3e0003afb14ec47d3f3448bea11c80d4b

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3579750034

**Comment by sammvio** [comment]
logo infringement, please resend your image

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
