### PR TITLE
ADD GFloki Logo and info

### PR DESCRIPTION
**Pull request by bailiyixi**
https://bscscan.com/tx/0x67ed82ce373205efcffca62f708d3d51b40fa7415b57a928babb1c9ca0fe4f17

### CODE REVIEW

**Comment by tiaojiaotubiaobaoguo** [comment]
代提交logo，24小时内包过，加QQ：2980874528

**Comment by sammvio** [comment]
Please refer to the tutorial, and re-submit your files in the correct format.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
