### PR TITLE
Add Gold logo and info

### PR DESCRIPTION
**Pull request by Darklightbscs**
3000 TPT:
https://bscscan.com/tx/0x4fda355b8a37e47511c918c05234222a9fdeac442237c9725f872e4885792111
30000 TPT:
https://bscscan.com/tx/0x59ac0a5013980f63e05a79e340dd61d07caa13d5c405e27e63780a5694f13311

### CODE REVIEW

**Comment by opera0001** [comment]
Agency contract detected, high risk.

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by Darklightbscs** [comment]
> Agency contract detected, high risk.

Because it is GAMEFI, the code cannot be open source, we have been running normally

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request merged**
