### PR TITLE
Add SNFT Logo and Info

### PR DESCRIPTION
**Pull request by soulnftx**
BSC-SNFT-0x2F5d726C2c8c939FA17e1EA36406877e4D53594b- https://bscscan.com/tx/0x9ca07e26a54435ebf4ed4ecef8f22798c4cc0657e81e83cbfe5df1b18ef0e00f

### CODE REVIEW

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by opera0001** [comment]
1. The contract does not give up ownership
2、info. Don't use Chinese for the title in JSON content
Please re submit the logo after adjustment. Thank you for your support for tokenpocket.

**Comment by opera0001** [comment]
1、The contract does not give up ownership
2、Don't use Chinese for the title in info.  JSON content
Please re submit the logo after adjustment. Thank you for your support for tokenpocket.

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
