### PR TITLE
Add DWB logo and info

### PR DESCRIPTION
**Pull request by publicBenz**
https://bscscan.com/tx/0x9e8a69d6788940a88e5084e88dcd4777a144b027d1a618fdb3fc7e4f4777d4b9; https://bscscan.com/tx/0xa4638f6b86d9c113271648371bbedda091e46624bc0d5b031d638bc8371766d3

### CODE REVIEW

**Comment by opera0001** [comment]
It has been detected that there is a hidden owner privilege in the contract, which is very dangerous.

**Comment by publicBenz** [comment]
> It has been detected that there is a hidden owner privilege in the contract, which is very dangerous.

The DWB token needs a role to manage the self-trade fee as need.

**Comment by publicBenz** [comment]
@opera0001 ？

**Comment by publicBenz** [comment]
Could you please locate the hidden dangerous parts within the constract which helps us to improve them?

**Comment by opera0001** [comment]
> Could you please locate the hidden dangerous parts within the constract which helps us to improve them?

Sorry, dear, this isn't my area of expertise. However, I've encountered similar cases with hidden owner privileges before, which can be removed from the code. Unfortunately, I don't know how to do it myself.

**Pull request closed without merging**
