### PR TITLE
Update RYB logo

### PR DESCRIPTION
**Pull request by wnwnaass**
HECO-RYB-0xDfd321E570d3B0588C16e2DEb6E70535201ea55C-https://hecoinfo.com/tx/0x858c9c28ca0b890cb1151aead8383ab1bebf0d669dfca6b3d7cc20ad9b1bda54

### CODE REVIEW

**Comment by wnwnaass** [comment]
Logo has been added before. Now just update it.

**Comment by guoxintongsam** [comment]
Please refer to the tutorial, and re-submit your files in the correct format.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
