### PR TITLE
Add TME logo and info

### PR DESCRIPTION
**Pull request by fightForTornothGold**
https://bscscan.com/tx/0x0459bdc062ada28ff0518931598e1c0e24ba8130b24e5533ea3aab666080570e

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:2980874528

**Comment by sammvio** [comment]
The contract didn’t verify and published. (No open-source)

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
