### PR TITLE
Add NFTB logo and info

### PR DESCRIPTION
**Pull request by TPinfolog**
Add NFTB logo and info

### CODE REVIEW

**Comment by TPinfolog** [comment]
Merge branch 'TP-Lab:master' into master

**Comment by TPinfolog** [comment]
Token Data Info Order
https://bscscan.com/token/0xde3dbbe30cfa9f437b293294d1fd64b26045c71a
NFTb is a complete multi-chain NFT and DeFi platform for the community. Our ultimate goal is to build a NFT and DeFi platform with the best user experience for anyone anywhere.
Transfer 3000TPT Order

**Comment by TPinfolog** [comment]
Token Data Info Order
 [ https://bscscan.com/token/0xde3dbbe30cfa9f437b293294d1fd64b26045c71a ](url)
NFTb is a complete multi-chain NFT and DeFi platform for the community. Our ultimate goal is to build a NFT and DeFi platform with the best user experience for anyone anywhere.
Transfer 3000TPT Order
the previous request was refused (1000TPT)
[https://bscscan.com/tx/0x91f242530ac4a4baed5aea566150ffdafa8661e389e61bdbe263992a30b641ed](url)
now the new donation (2000TPT)
[https://bscscan.com/tx/0x05b76e283e2248db2f92f07075b999def2182a1c827aee15e07b53f6a742158f](url)

**Comment by TPinfolog** [comment]
{
 "name": "NFTB Token",
 "website": "https://nftb.io/",
 "description": "NFTb是一个面向社区的完整多链NFT和DeFi平台，我们的最终目标是为任何地方的任何人构建一个具有最佳用户体验的NFT和DeFi平台。",
 "explorer": "https://bscscan.com/token/0xde3dbbe30cfa9f437b293294d1fd64b26045c71a",
 "type": "BEP20",
 "symbol": "NFTB",
 "decimals":18,
 "status": "active",
 "id": "0xde3dbbe30cfa9f437b293294d1fd64b26045c71a"
}

**Comment by TPinfolog** [comment]
logo

**Comment by guoxintongsam** [comment]
Please refer to the tutorial, and re-submit your files in the correct format.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
