### PR TITLE
Add TPT logo and info

### PR DESCRIPTION
**Pull request by 811700763qq20**
3000 TPT     0x778E8224A017B767bD8f42A2D6B9F2fF66724DCD

### CODE REVIEW

**Comment by 811700763qq20** [comment]
头像是否已经审核成功

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3076439606

**Comment by sammvio** [comment]
Please donate 3000 TPT as required and submit the transfer link on [Commit changes].

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
