### PR TITLE
ADD CPL logo and info

### PR DESCRIPTION
**Pull request by lcwypn**
https://bscscan.com/tx/0xb9bd85eea954fb0d8bfb5e24ea5c7288bf7f7aed760aef84161c1a20e6651ac5 https://bscscan.com/tx/0xc63c63313a022f85be34dfb158e30eed2e047c7ca22a51c0b8b3ebca7ac07477

### CODE REVIEW

**Comment by opera0001** [comment]
Hidden owner permissions detected in the token contract, please investigate.

**Comment by lcwypn** [comment]
> Hidden owner permissions detected in the token contract, please investigate.

Permission discarded

**Comment by lcwypn** [comment]
Permission discarded

**Comment by opera0001** [comment]
After relinquishing token control authority, the hidden owner may still exist and retain their influence, so you need to have the technical team reassess potential risks.

**Comment by lcwypn** [comment]
> After relinquishing token control authority, the hidden owner may still exist and retain their influence, so you need to have the technical team reassess potential risks.

Reassessed

**Comment by opera0001** [comment]
Hi dear, I'm sorry we couldn't include the logo you submitted, but your donation link can still be used in your next submission.

**Pull request closed without merging**
