### PR TITLE
Add SELO logo and info

### PR DESCRIPTION
**Pull request by SecurityLock**
Security lock is a platform token. The platform provides audit and insurance compensation services. The project settled on the platform must pay the corresponding deposit, so as to prevent and reduce fraud in the field of encryption. 
https://bscscan.com/tx/0xf1237837d346f2761a9f49b510b917e3a36c84d4306c51858578d62f80e98b9f

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3579750034

**Comment by SecurityLock** [comment]
Please review our avatar asap.

**Comment by sammvio** [comment]
Please resubmit your request with the logo.

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
