### PR TITLE
Add ODO logo and info

### PR DESCRIPTION
**Pull request by OpenDomainDAO**
https://bscscan.com/tx/0xe3a316bc9c818496d517694c654218bd29c14760e9e772a729f17d0b7599bc36
https://bscscan.com/tx/0x58c5daf4e656bb67c1e80ac6ba97408381db2ce39c2c43c3e1a78375704bc3ed

### CODE REVIEW

**Comment by OpenDomainDAO** [comment]
0xe3a316bc9c818496d517694c654218bd29c14760e9e772a729f17d0b7599bc36
0x58c5daf4e656bb67c1e80ac6ba97408381db2ce39c2c43c3e1a78375704bc3ed

**Comment by OpenDomainDAO** [comment]
0xe3a316bc9c818496d517694c654218bd29c14760e9e772a729f17d0b7599bc36
0x58c5daf4e656bb67c1e80ac6ba97408381db2ce39c2c43c3e1a78375704bc3ed

**Comment by OpenDomainDAO** [comment]
https://bscscan.com/tx/0xe3a316bc9c818496d517694c654218bd29c14760e9e772a729f17d0b7599bc36
https://bscscan.com/tx/0x58c5daf4e656bb67c1e80ac6ba97408381db2ce39c2c43c3e1a78375704bc3ed

**Comment by opera0001** [comment]
It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

**Comment by OpenDomainDAO** [comment]
Token contract code is disclosed, please check

**Comment by OpenDomainDAO** [comment]
https://bscscan.com/tx/0xe3a316bc9c818496d517694c654218bd29c14760e9e772a729f17d0b7599bc36
https://bscscan.com/tx/0x58c5daf4e656bb67c1e80ac6ba97408381db2ce39c2c43c3e1a78375704bc3ed

**Comment by OpenDomainDAO** [comment]
https://bscscan.com/address/0xE219D6dCa4D9eD325BFFaC681a50731aCb49ea09#code

**Pull request merged**
