### PR TITLE
ADD ELS token

### PR DESCRIPTION
**Pull request by etplan**
https://bscscan.com/tx/0x3a3e52d8d07c0326c1d3e5181a4a8532d6c5928e9e008f0998a23db97cd61e7b

### CODE REVIEW

**Comment by giki0318** [comment]
Your website is not accessible while we are reviewing the token

**Comment by etplan** [comment]
https://bscscan.com/tx/0x3a3e52d8d07c0326c1d3e5181a4a8532d6c5928e9e008f0998a23db97cd61e7b

processed

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
