### PR TITLE
Add FLL logo and info

### PR DESCRIPTION
**Pull request by mini666uhg**
https://bscscan.com/tx/0x3c5acdf4db5d2ff5197df498b867570c5f80ec6ca80fcd6a5cfc4271e7bb5aae

### CODE REVIEW

**Comment by opera0001** [comment]
0xFfce84f80e5c0168687e7D6d4800bdaAbdFeAF6B--The contract is not open source, no other problems.

0xcb91e4c4a08e61759ce63c2dad1312fc9c2d28ee--The logo is not 256x256 pixels. Everything else is OK.

0x06eB5112171A42901B0b34A54990Ca2680dc890D--The logo is not 256x256 pixels. Everything else is OK.

It seems that you only submitted the TPT donation hash value twice and submitted three logos. The hash value link for the validation address was not submitted.

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
