### PR TITLE
Add House logo and info

### PR DESCRIPTION
**Pull request by kevinfreeman0416**
https://bscscan.com/tx/0x9d27174ee98a392d776b7b14c2a4c2bb81a0e7e7e570c881554ea2dabffe160b

### CODE REVIEW

**Comment by opera0001** [comment]
If the ownership is not abandoned, there may be an additional issuance mechanism, with certain risks. Please re submit the logo after adjustment or optimization. Thank you for your support for tokenpocket.

**Comment by kevinfreeman0416** [comment]
hello, i have relinquished permissions
https://bscscan.com/tx/0x9d27174ee98a392d776b7b14c2a4c2bb81a0e7e7e570c881554ea2dabffe160b

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
