### PR TITLE
Add Token Chivo logo an info

### PR DESCRIPTION
**Pull request by Androidex1**
0x2f9fef79fe8efe3c6ec4ddcd7645e68c43c59afb24c860c6a34f9e5a06affc44

### CODE REVIEW

**Comment by opera0001** [comment]
image
The submitted file is not saved in the BSC directory, please adjust it again.

It is detected that a token issue can be added, please explain what it does.

**Comment by Androidex1** [comment]
hi sir, is imposible to add my file,   (Uploads are disabled.
File uploads require push access to this repository.) this is the message in bsc file.

about the issue with the token we dont have anything else to add, we just want to add the logo.  in my folder the logo just say logo.png
logo png

**Comment by Androidex1** [comment]
[info.json](https://github.com/TP-Lab/tokens/files/9795007/info.json.txt)
[logo.png](https://user-images.githubusercontent.com/115790833/196043513-afba6f0a-958d-4d28-a64d-0c59f5960dd9.png)

**Comment by Androidex1** [comment]
[logo.png](https://user-images.githubusercontent.com/115790833/196045131-98b1d6ab-5fb4-43e9-afc8-55a6740eab48.png)
[info.json](https://github.com/TP-Lab/tokens/files/9795124/info.json.txt)

**Comment by Androidex1** [comment]
hello, thank you for comunicate, i had been try to fix it, we dont want to make any change, we just want to add the logo and info to our token. i dont understan why is continuing resulting the same png.png we are following the steps given in the tp web

[logo.png](https://user-images.githubusercontent.com/115790833/196049797-8969f551-eb69-4b41-b028-7284a5bd6dbc.png)

**Comment by Androidex1** [comment]
Hello, the error is solved, thank you.

**Comment by opera0001** [comment]
image
Only the submission path for this logo is correct and the json needs to be adjusted.

**Comment by Androidex1** [comment]
image

i upload the folder in bsc file

image

try the first one

**Comment by Androidex1** [comment]
image

hello, could you tell me if you check my info.json please, i uploaded yesterday.

**Pull request merged**
