### PR TITLE
Add MarsDoge logo and info

### PR DESCRIPTION
**Pull request by MarsDogeToken**
This is related to the email received on Wed, Aug 11, 2021 at 6:27 PM TokenPocket Service <service@tokenpocket.pro> with the subject of "Re: Kind request to add Decentralized Exchange logo and info #2232"

### CODE REVIEW

**Comment by tiaojiaotubiaobaoguo** [comment]
代提交logo，24小时内包过，加QQ：2980874528

**Comment by MarsDogeToken** [comment]
> 代提交logo，24小时内包过，加QQ：2980874528

Hello @tiaojiaotubiaobaoguo, We highly appreciate it if you could send the above comment in English, if we need to do something about it. Thank you very much.

**Comment by sammvio** [comment]
Tron token logo upload is not allowed for now

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request merged**
