### PR TITLE
Add WOLF logo and info

### PR DESCRIPTION
**Pull request by Wolfkingtoken**
https://bscscan.com/tx/0x0d045cf800db972684638978548521520023015363eb9358f946c794b107fdd8

### CODE REVIEW

**Comment by Wolfkingtoken** [comment]
We can't give up the ownership of the contract. It won't cause loss to anyone

**Comment by Wolfkingtoken** [comment]
We need to change the tax address in the contract at a specific time

**Comment by Wolfkingtoken** [comment]
Please check carefully, thank you

**Comment by Wolfkingtoken** [comment]
Our roadmap plans to build our own DEX. You may also find that our contract has the function, which we need to use after deploying the DEX contract

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request merged**
