### PR TITLE
ADD ETL logo and info

### PR DESCRIPTION
**Pull request by lcwypn**
ETL

### CODE REVIEW

**Comment by opera0001** [comment]
1、Detected that the token trading rate can be modified, please explain what he does.
2、We suggest you modify the logo and replace it, because this logo is highly similar to the logo of ETH tokens, please make a distinction.

**Comment by lcwypn** [comment]
> 1、检测到可以修改代币交易率，请说明他是做什么的。 2、我们建议您修改并更换标识，因为这个标识与ETH代币的标识高度相似，请加以区分。

We will use it as an incentive before listing on the exchange. In the future, we will do community voting to make some tax adjustments. We want to seek the opinions of community users and are making adjustments to the requirements of community users.

**Comment by lcwypn** [comment]
We will use it as an incentive before listing on the exchange. In the future, we will do community voting to make some tax adjustments. We want to seek the opinions of community users and are making adjustments to the requirements of community users.

**Comment by lcwypn** [comment]
We will use it as an incentive before listing on the exchange. In the future, we will do community voting to make some tax adjustments. We want to seek the opinions of community users and are making adjustments to the requirements of community users.

**Pull request merged**
