### PR TITLE
ADD logo info

### PR DESCRIPTION
**Pull request by ISPMall**
ADD logo info

### CODE REVIEW

**Comment by ISPMall** [comment]
https://www.bscscan.com/tx/0xdf7c480405c8f06df67e0d6452f94e42f9a22b16e11bd9c41517d7d797dee162

**Comment by ISPMall** [comment]
ADD LOGIN INFO
50000tpt https://www.bscscan.com/tx/0xdf7c480405c8f06df67e0d6452f94e42f9a22b16e11bd9c41517d7d797dee162
verify https://www.bscscan.com/tx/0x96522b50f81c13cd0e4c2dcd1febbd9446d2b010822d8792536e6da583f74aeb

**Comment by opera0001** [comment]
The provided token is not 256x256 pixels; please make the necessary adjustments.

**Review by ISPMall — COMMENTED** [review]
logo

**Comment by ISPMall** [comment]
Modified

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Pull request merged**
