### PR TITLE
Add SHCQ logo and info

### PR DESCRIPTION
**Pull request by kimpace19882627**
BSC-SHCQ-
0x2cdf715199e82bc1aba3e07808d629d855fabe3e-https://bscscan.com/tx/0xbf660920c39bf8d2e36dcaed8f2589f9e21d90983672eb7498bfc2247c29d8e5

### CODE REVIEW

**Comment by opera0001** [comment]
There may be some risks if you do not give up your administrator rights. Please re submit the logo after adjustment or optimization. Thank you for your support for tokenpocket.

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
