### PR TITLE
Add DPR logo and info

### PR DESCRIPTION
**Pull request by AmadeusGB**
https://bscscan.com/tx/0x988c85c290827e0eae4ebfe193f0cb71f1cae5dba80552bce146e00c84835d08

### CODE REVIEW

**Comment by qq2871019009** [comment]
快速提交logo，一天内包过，不过全额退款。加QQ：2871019009

**Comment by sammvio** [comment]
Please refer to the tutorial, and re-submit your files in the correct format.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
