### PR TITLE
Add CCP Logo and info

### PR DESCRIPTION
**Pull request by FangYu199**
Transfer:  https://bscscan.com/tx/0xd91ce3eb7db92a5469f7c0426fde74bd44bb94ff295f6e2fed5a37a09b5f2be4
Verify:  https://bscscan.com/tx/0xd1dd4b55a369f1224bbddc42c6e5489d8a7fce43e0280bd1b7bc8fcf2263743f

### CODE REVIEW

**Comment by FangYu199** [comment]
### ps
```
这是 创建 CCP Token 的 合约验证地址 https://etherscan.io/address/0xb9b6885d0af9914d432871dcbeb20daa8282a763
调用 方法 ”createERC20Token“ 方法ID “0x34b20591”
创建交易哈希：https://etherscan.io/tx/0xbcff4cffbd05de7313a072691785e5310ce18196c0d89ad36268a8364cc52285
```

**Comment by FangYu199** [comment]
### 合约开源代码 
```
调用 0xb9b...2a763 合约的 createERC20Token 方法创建 方法ID 0x34b20591
0xb9b...2a763 合约地址：https://etherscan.io/address/0xb9b6885d0af9914d432871dcbeb20daa8282a763#code
创建合约交易记录： https://etherscan.io/tx/0xbcff4cffbd05de7313a072691785e5310ce18196c0d89ad36268a8364cc52285

```

**Comment by opera0001** [comment]
It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

**Comment by FangYu199** [comment]
已经开源了 开源地址 https://etherscan.io/address/0xb9b6885d0af9914d432871dcbeb20daa8282a763#code 
我提交的合约是通过这个 合约创建的

**Comment by FangYu199** [comment]
审计报告 
[ccp2-en.pdf](https://github.com/TP-Lab/tokens/files/9898208/ccp2-en.pdf)

**Comment by FangYu199** [comment]
Will anyone handle this PR?
This contract has been open sourced Open source address https://etherscan.io/address/0xb9b6885d0af9914d432871dcbeb20daa8282a763#code
The contract I submitted was created through this contract

Audit Report
https://github.com/TP-Lab/tokens/files/9898208/ccp2-en.pdf

**Pull request merged**
