### PR TITLE
add BSC PTP info and logo

### PR DESCRIPTION
**Pull request by woodmaxkid**
https://bscscan.com/tx/0x9e8c65690359007b11e7d5bebdea1912480f5bd0e0c9273a34c2db729dfacd35

### CODE REVIEW

**Comment by TokenPocket-JAN** [comment]
Speed ​​up the trial. Please reply to the email if you need.
QQ112831047

**Comment by opera0001** [comment]
Now you need 30000 TPT donation fees to submit the token logo collection. Please supplement and send the hash value to the message of GitHub.

**Comment by woodmaxkid** [comment]
Commit here or recreate one?

**Comment by woodmaxkid** [comment]
> Now you need 30000 TPT donation fees to submit the token logo collection. Please supplement and send the hash value to the message of GitHub.

Commit here or recreate one?

**Comment by sichuantbq** [comment]
我应该怎么提交添加头像

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
