### PR TITLE
Add Redheart logo and info

### PR DESCRIPTION
**Pull request by oelg2**
https://bscscan.com/tx/0x55cccac34155976d456dec053c8d0f2d6f2ffa465b2e76863a363447498fb680

### CODE REVIEW

**Comment by opera0001** [comment]
1. Low token liquidity

2. It is found that there may be a control transaction switch

3. It is found that there may be retrievable permission codes

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
