### PR TITLE
Add BTMOON logo and info

### PR DESCRIPTION
**Pull request by YYYYZZZZZ**
https://bscscan.com/tx/0x27bda68829d11a8e535c6f862eb46605a5cbb83eefa178ecf57ede23f6644de2

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token

**Comment by YYYYZZZZZ** [comment]
我上市了呀。是heco链的。



---Original---
From: ***@***.***&gt;
Date: Fri, Jul 16, 2021 17:50 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] Add BTMOON logo and info (#1322)




 
Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token

**Comment by YYYYZZZZZ** [comment]
> Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token

I'm listed on HECO
0xEeD991d212bf79cf51DDa195D577707928333797

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
