### PR TITLE
上传代币DTOK  logo

### PR DESCRIPTION
**Pull request by DTOK02**
TPT哈希：
0x3d88fb37ba0babf6dfcd1f37398ab5996790efb6340c9d0f0efb206c2c5d6daf

### CODE REVIEW

**Comment by opera0001** [comment]
image
1、The submitted file is not saved in the BSC directory, please adjust it again.
2、Detected the existence of tokens to increase the settings of the issue
3、Detected that the transaction rate can be modified

**Comment by DTOK02** [comment]
> 图片 1、提交的文件没有保存在BSC目录下，请重新调整。 2、检测到代币存在增加问题的设置 3、检测到交易率可以修改

Reply 2: The token adopts the token model of BABY DOGE, there is additional issuance but this function is not used
Reply 3: The token transaction rate is appropriately adjusted according to the development stage

**Comment by DTOK02** [comment]
@opera0001 hi，

**Comment by DTOK02** [comment]
@ @opera0001 please check, thanks

**Pull request merged**
