### PR TITLE
Add TPT logo and info

### PR DESCRIPTION
**Pull request by AuraSuper**
https://bscscan.com/tx/0x6073ce7b580a1f953eaf6c722cd367a750ae076f3c404c569932df28ad91e43c

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3579750034

**Comment by sammvio** [comment]
The contract didn’t verify and publish. (No open-source)

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
