### PR TITLE
Add Suica token's Info and logo

### PR DESCRIPTION
**Pull request by BitBazaarllc**
Suica Token's info& logo

### CODE REVIEW

**Comment by BitBazaarllc** [comment]
decimals error：“ decimals”：18，——》"decimals": "18",

**Comment by guoxintongsam** [comment]
Please re-submit the TPT transfer link on [Commit changes].
Please refer to the tutorial, and re-submit your files in the correct format.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
