### PR TITLE
Add BTCPi logo and info

### PR DESCRIPTION
**Pull request by BTCPiCom**
BSC - BTCPi - 0x4aAAD68BE1A2Ac9886B72b9DaE474F3eDd2132D9 - https://bscscan.com/tx/0xe9dd49aad9e45228534ccf11155c4c726cd070f64dfe2fea7823dd8a1f3371ef

https://bscscan.com/tx/0xb0eaad345164ea90954f249831db35f06f2cdb44d5e75b60d721ee21a8efde1c

### CODE REVIEW

**Comment by BTCPiCom** [comment]
BTCPi/SpacePi has added initial liquidity with a ratio of 1,200,000:30 trillion. It has been locked in Pinksale until 13:14 on June 28, 2030.

https://www.pinksale.finance/pinklock/record/1011307?chain=BSC

The contract of BTCPi Mine is basically the same as that of MDEX, which has been submitted to the audit agency Armors for audit, and the audit report will be released on July 10th.

The mining contract has been open sourced.

https://bscscan.com/address/0xc48fe252aa631017df253578b1405ea399728a50#code

**Comment by opera0001** [comment]
The logo is very similar to the BTC logo, and although the design is good, it is not the right place for it to appear, so a more varied logo still needs to be changed.

**Comment by BTCPiCom** [comment]
> The logo is very similar to the BTC logo, and although the design is good, it is not the right place for it to appear, so a more varied logo still needs to be changed.

OK, we'll redesign a logo to be compliant.

**Comment by opera0001** [comment]
After replacement, please go to https://github.com/TP-Lab/tokens/issues contact

**Pull request closed without merging**
