### PR TITLE
Add TEB logo and info

### PR DESCRIPTION
**Pull request by tebcommunity**
Thank you

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Please re-submit your files attached TPT transfer link on [Commit changes].

**Comment by tebcommunity** [comment]
真的不知道怎么操作，搞得太复杂了，太让人心累了，我很绝望

guoxintongsam ***@***.***> 于2021年8月25日周三 下午12:02写道：

**Comment by tebcommunity** [comment]
> 请在 [提交更改] 上重新提交您的文件附加 TPT 传输链接。

I don't understand what you mean. I will continue to submit new documents. If you don't explain it to me, I will submit it again and again until you explain it to me

**Comment by tebcommunity** [comment]
I don't understand what you mean. I will continue to submit new documents.
If you don't explain it to me, I will submit it again and again until you
explain it to me

guoxintongsam ***@***.***> 于2021年8月25日周三 下午12:02写道：

**Review by tebcommunity — COMMENTED** [review]
BSC-TEB-0x1326e89a4b9ab6db3c996a246606018471ac4520-https://bscscan.com/tx/0xb7b5d03e7600e92de7c5e76ec150a06828abae77d45a20e5fdc7d0c6c5a0797c

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Pull request closed without merging**
