### PR TITLE
Add BABYCORGI logo and info

### PR DESCRIPTION
**Pull request by daryl12345**
Buying and holding Baby Corgi will automatically receive Filecoin from the wallet approximately every 60 minutes.

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Please re-submit the TPT transfer link on [Commit changes].

**Comment by daryl12345** [comment]
https://bscscan.com/tx/0xe49e3db8097c064d894e0467ca82dd819f09925be97d98ad7db63b547600c1d8

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
