### PR TITLE
Add SDLM logo and info

### PR DESCRIPTION
**Pull request by SDLM123**
https://bscscan.com/tx/0x7ff08798399ac1bad7d70342659e82a155a5046a15b58e25bd8ac4a0806e156f

### CODE REVIEW

**Comment by opera0001** [comment]
1. The submitted web address cannot be opened
2. No capital flow pool found
3. There are hundreds of currency holding addresses on the chain. The token transaction method is unclear and the risk level cannot be defined.
Please re submit the logo after adjustment or optimization. Thank you for your support for tokenpocket.

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
