### PR TITLE
add BOBO logo and info

### PR DESCRIPTION
**Pull request by bobocoin123**
https://bscscan.com/tx/0x878609856f57f8d0022d0dbbb8ac140d5ff5d48a7efaf0073dc220b76292b92c

### CODE REVIEW

**Comment by opera0001** [comment]
You need to add a donation of 50,000 TPT (as the latest requirement is 100,000 TPT). After completing the transaction, you can send the new hash value here. Thank you.

**Comment by bobocoin123** [comment]
> You need to add a donation of 50,000 TPT (as the latest requirement is 100,000 TPT). After completing the transaction, you can send the new hash value here. Thank you.
https://bscscan.com/tx/0x878609856f57f8d0022d0dbbb8ac140d5ff5d48a7efaf0073dc220b76292b92c

**Comment by bobocoin123** [comment]
Why is my BOBO logo still not showing? It has already been merged.

**Comment by bobocoin123** [comment]
你好，我的logo怎么还没显示呢？都已经合并了，帮忙看看哪里出问题了，谢谢



在 2024-09-10 08:49:46，"opera0001" ***@***.***> 写道：

Merged #10950 into master.

**Comment by bobocoin123** [comment]
> 哪里



> 你好，我的logo怎么还没显示呢？都已经合并了，帮忙看看哪里出问题了，谢谢 在 2024-09-10 08:49:46，"opera0001" ***@***.***> 写道： Merged #10950 into master. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

can you help me?

**Pull request merged**
