### PR TITLE
Tpt哈希连接，提交代币logo

### PR DESCRIPTION
**Pull request by bigfish1874**
https://bscscan.com/tx/0xcfa474a7f1a95c928acc93f0f9c466b1b82951cbb0b3ea8f065884a6570f72cb

### CODE REVIEW

**Comment by opera0001** [comment]
image
This logo is not provided by this github account of yours, so you can't request to remove it.
image

You need this submission address to request deletion, and you can contact me at issues.

**Comment by bigfish1874** [comment]
> 



> 图片 这个标志不是你的这个 github 帐户提供的，所以你不能要求删除它。 图片
> 
> 你需要这个提交地址来申请删除，有问题可以联系我。

Hello, I did not ask to delete him, did I make a mistake, please pass my review as soon as possible

**Comment by bigfish1874** [comment]
> image This logo is not provided by this github account of yours, so you can't request to remove it. image
> 
> You need this submission address to request deletion, and you can contact me at issues.

Hello, I did not ask to delete him, did I make a mistake, please pass my review as soon as possible

**Comment by bigfish1874** [comment]
https://bscscan.com/tx/0x9f975b29b5c0ba62b4dddbd202f0cfe851458d4f264e1ea0c27c405094079c9b
I uploaded the logo of DY, I have not seen the logo you posted, it is not from me。
image

**Pull request closed without merging**
