### PR TITLE
Add BC logo and info

### PR DESCRIPTION
**Pull request by xdtg2016**
HECO-BC-0x2Ed0A1e821aC6EB17FE871e6fEc147BE90988A44-https://hecoinfo.com/tx/0xcb742ac39070857cac30149de5b19984b20af8f3be06b36c026566bc733bc549

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token

**Comment by xdtg2016** [comment]
这个什么意思啊 TPT也转了 文件也上传了 一直不见处理！ 能指示一下我需要怎么做吗？ 981287636 ***@***.*** 签名由 网易邮箱大师 定制 On 08/13/2021 15:08, zhujiayu03 wrote: Closed #2362. — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
