### PR TITLE
Add  BSC doge logo and info

### PR DESCRIPTION
**Pull request by liujia520**
https://bscscan.com/tx/0x663254972d3a801b27ce69acb2b9a20d47d751e07825e3e71f31bd18969156ed

### CODE REVIEW

**Comment by liujia520** [comment]
https://bscscan.com/tx/0x12805145042d74723c5cd29febe7b0bd0957732810f8a627a72cef8f64fd6b2f

**Comment by liujia520** [comment]
https://bscscan.com/tx/0x5af0e88ba136b86191fc5b215ce2d2d1f2afe582697700a693bd1d685bb59213

**Comment by zhujiayu03** [comment]
ZKN LOGO Added
SNFT Unlisted Token
BSC Doge Logo Infringement

**Comment by zhujiayu03** [comment]
ZKN LOGO Added
SNFT Unlisted Token
BSC Doge Logo Infringement

**Comment by liujia520** [comment]
请问 SNFT 是需要上交易所才会审核吗？BSC Doge的logo 侵权？ 请问如何侵权了？


Does SNFT need to be listed on the exchange to review it? BSC Doge's logo infringement? How did you infringe?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TP-Lab/tokens"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月26日(星期一) 下午5:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TP-Lab/tokens] Add  BSC doge logo and info (#1638)





 
ZKN LOGO Added
 SNFT Unlisted Token
 BSC Doge Logo Infringement

**Pull request closed without merging**
