### PR TITLE
Add Meta logo and info

### PR DESCRIPTION
**Pull request by starsky678**
add Meta logo and info
https://bscscan.com/tx/0x6699b8c285d51964b41b28fbaa0e03cbd3bda3fee93cf82c20ff4902b50c57c7

### CODE REVIEW

**Comment by qq2871019009** [comment]
快速提交logo，一天内包过，不过全额退款。加QQ：2871019009

**Comment by sammvio** [comment]
Please re-submit your files to bsc folder

**Comment by starsky678** [comment]
你好
我这边已经重新提交了Logo和信息
希望尽快审核
谢谢










At 2021-11-26 22:39:33, "SS" ***@***.***> wrote:

Closed #4183.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
