### PR TITLE
add HPC logo and info

### PR DESCRIPTION
**Pull request by MXY156018**
BSC-HPC-0x5b53632a51F5FAdA9aA459C1cc386c50FBa6d305
https://bscscan.com/tx/0x6828c6cd6b1d8113463b6c307fd2c68fbc80431f97e375a555d19dd78409254d
https://www.bscscan.com/token/0x5b53632a51F5FAdA9aA459C1cc386c50FBa6d305

### CODE REVIEW

**Comment by opera0001** [comment]
The liquidity of token fund pool is insufficient, and the currency holding address is not active

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
