### PR TITLE
add BOXC token

### PR DESCRIPTION
**Pull request by ubunt2022**

### CODE REVIEW

**Comment by ubunt2022** [comment]
https://bscscan.com/tx/0x3a6d021b6cf3038cf5630af8195b590388b1f1544546f69b535d0bd6043c7fe4 捐赠 https://bscscan.com/tx/0xecb7c9d0c400d4bce459f55e55f43ff49b75d6649adb087cf983cbfddedab12c 验证

**Comment by opera0001** [comment]
The submitted logo is not 256x256 pixels, please adjust.

**Comment by opera0001** [comment]
I don't see your changes after 4 days, so the order needs to be closed, subsequent modified logos can be contacted and sent to me via issues, thank you.

https://github.com/TP-Lab/tokens/issues

**Comment by ubunt2022** [comment]
> I don't see your changes after 4 days, so the order needs to be closed, subsequent modified logos can be contacted and sent to me via issues, thank you.
> 
> https://github.com/TP-Lab/tokens/issues

I have submit a issue, please take a look again.

**Pull request merged**
