### PR TITLE
Add Bass Token

### PR DESCRIPTION
**Pull request by MagicDeveloperDocs**

### CODE REVIEW

**Comment by MagicDeveloperDocs** [comment]
https://bscscan.com/tx/0xb46296613ea0c2ec2346ca269c07906d6424796380b2309c619b351950ce0278

BSC-BASS-0xe18b1613dB3B5b8EAe42fB1C00559F63DB4B09f1-https://bscscan.com/tx/0x3c9d0bf281eee54b028ac0bfbe121a48d8cb4317ec0127c46e4699e7084a3eaf

https://bscscan.com/tx/0x3c9d0bf281eee54b028ac0bfbe121a48d8cb4317ec0127c46e4699e7084a3eaf

**Comment by opera0001** [comment]
The presence of a transaction suspendable switch is detected, please make a note of it.

**Comment by opera0001** [comment]
Please explain the settings that can suspend trading when detected.

**Comment by opera0001** [comment]
I didn't see your reply or changes after 2 days, so I'll close the order first. Please leave us a message at https://github.com/TP-Lab/tokens/issues if you have any questions, thank you.

**Pull request closed without merging**
