### PR TITLE
Add PWC logo and info

### PR DESCRIPTION
**Pull request by ywl11010**
https://bscscan.com/tx/0x0a3bfacfb27e99adc2f3c9114b02fa2f1d2ce39183c1f55f6b732cc856ab685c

### CODE REVIEW

**Comment by ywl11010** [comment]
https://bscscan.com/tx/0x0a3bfacfb27e99adc2f3c9114b02fa2f1d2ce39183c1f55f6b732cc856ab685c

**Comment by logobaoguo** [comment]
专业提交logo！加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by sammvio** [comment]
Please re-submit your files to bsc folder

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
