### PR TITLE
add DIV logo and info

### PR DESCRIPTION
**Pull request by DIVINERGAMES**
{
2
"name": “DIV”,
3
"website": "https://diviner.io”,
4
"description": "We’ve been endeavoring to maintain the fairness of the project by avoiding external funding and keeping self-funding, in order to ensure its long-term significance. We sincerely hold that Diviner will be the cradle of cross-NFT, game, and cross-meta-universe.",
5
"explorer": "https://bscscan.com/token/0xdb18b794f33425caac6de080cd55cd0eff88b8a6?a=0xbf38a8b9cf02223b44f823e15f45219e9978b491",
6
"type": "BEP20",
7
"symbol": “DIV”,
8
"decimals": 4,
9
"status": "active",
10
"id": "0xbf38a8b9cf02223b44f823e15f45219e9978b491"
11
}

### CODE REVIEW

**Comment by DIVINERGAMES** [comment]
thanks

**Comment by DIVINERGAMES** [comment]
{
2
"name": “DIV”,
3
"website": "https://diviner.io”,
4
"description": "We’ve been endeavoring to maintain the fairness of the project by avoiding external funding and keeping self-funding, in order to ensure its long-term significance. We sincerely hold that Diviner will be the cradle of cross-NFT, game, and cross-meta-universe.",
5
"explorer": "https://bscscan.com/token/0xdb18b794f33425caac6de080cd55cd0eff88b8a6?a=0xbf38a8b9cf02223b44f823e15f45219e9978b491",
6
"type": "BEP20",
7
"symbol": “DIV”,
8
"decimals": 4,
9
"status": "active",
10
"id": "0xbf38a8b9cf02223b44f823e15f45219e9978b491"
11
}

**Comment by opera0001** [comment]
Please submit your application carefully according to the content of the tutorial. Thank you.

CN：https://tphelp.gitbook.io/cn/wallet-operation/submit-token
EN：https://help.tokenpocket.pro/en/developer/how-to-submit-a-token-logo#steps-of-adding-a-token-logo-info

**Comment by DIVINERGAMES** [comment]
Can you help me reupdate, thanks

**Comment by DIVINERGAMES** [comment]
{
"name": “DIV”,
"website": "https://diviner.io”,
"description": "We’ve been endeavoring to maintain the fairness of the project by avoiding external funding and keeping self-funding, in order to ensure its long-term significance. We sincerely hold that Diviner will be the cradle of cross-NFT, game, and cross-meta-universe.",
"explorer": "https://bscscan.com/token/0xdb18b794f33425caac6de080cd55cd0eff88b8a6?a=0xbf38a8b9cf02223b44f823e15f45219e9978b491",
"type": "BEP20",
"symbol": “DIV”,
"decimals": 4,
"status": "active",
"id": "0xbf38a8b9cf02223b44f823e15f45219e9978b491"
}

logo

**Comment by opera0001** [comment]
I'm very sorry. There are many problems with your order. Please refer to the submitted tutorial again. Everything goes well.

**Pull request closed without merging**
