### PR TITLE
Add  UNT  logo

### PR DESCRIPTION
**Pull request by sdfxcvdryg**
Hope to review and upload as soon as possible! Thank you very much!

### CODE REVIEW

**Comment by opera0001** [comment]
Two sets of logo schemes have been submitted. Which one do you use?

**Comment by sdfxcvdryg** [comment]
The second proposal submitted




---Original---
From: ***@***.***&gt;
Date: Tue, Mar 1, 2022 21:58 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] Add  UNT  logo (PR #5962)




 
Two sets of logo schemes have been submitted. Which one do you use?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sdfxcvdryg** [comment]
> 提交的第二个提案
> […](#)
> ---原创---来自：***@***.***> 日期：2022 年 3 月 1 日星期二晚上 21:58 至：***@***.***>; 抄送：***@***.******@***.***>; 主题：回复：[TP-Lab/tokens] 添加 UNT 徽标 (PR #5962 ) 已提交两组徽标方案。你用哪一个？— 直接回复此电子邮件，在 GitHub 上查看，或取消订阅。使用适用于 iOS 或 Android 的 GitHub Mobile 随时随地对通知进行分类。您收到此消息是因为您编写了该线程。消息 ID：***@***.***>

[](https://fanyi.baidu.com/translate?aldtype=16047&query=%E6%88%91%E9%80%89%E6%8B%A9%E6%9C%80%E5%90%8E%E4%B8%8A%E4%BC%A0%E7%9A%84%E8%BF%99%E4%B8%80%E5%A5%97&keyfrom=baidu&smartresult=dict&lang=auto2zh###)[](javascript:void(0);)我选择最后上传的这一套
我选择最后上传的这一套
I chose the last one to upload

> 已提交两套标志方案。你用哪一个？

I choose the second set, the last one uploaded!

**Comment by opera0001** [comment]
The logo has been added. Please check the effect. Thank you for your support for tokenpocket.

**Comment by sdfxcvdryg** [comment]
> 徽标已添加。请检查效果。感谢您对令牌口袋的支持。

I'm sorry! You uploaded an error to me! Please modify it!

**Comment by sdfxcvdryg** [comment]
Error in adding LOGO, please help to modify the second scheme we submitted!



---Original---
From: ***@***.***&gt;
Date: Tue, Mar 1, 2022 22:04 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] Add  UNT  logo (PR #5962)




 
The logo has been added. Please check the effect. Thank you for your support for tokenpocket.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sdfxcvdryg** [comment]
> 已提交两套标志方案。你用哪一个？

I'm sorry! You uploaded an error to me! Please modify it!

**Comment by opera0001** [comment]
It may be a problem with the upload order. It has been adjusted. Please check it again.

**Comment by sdfxcvdryg** [comment]
> 可能是上传顺序有问题。它已被调整。请再次检查。

I've seen it! Thank you.

**Comment by opera0001** [comment]
Thank you for your support of tokenpocket and wish you a happy life.

**Comment by sdfxcvdryg** [comment]
Ok, thank you



---Original---
From: ***@***.***&gt;
Date: Tue, Mar 1, 2022 22:08 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] Add  UNT  logo (PR #5962)




 
It may be a problem with the upload order. It has been adjusted. Please check it again.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request merged**
