### PR TITLE
Add TEA logo and info

### PR DESCRIPTION
**Pull request by aluo0796**
https://www.bscscan.com/tx/0xcc41a54fa56a46632eb00dc04556d5ed745c49f9c08052263c1babd6ded6440a

### CODE REVIEW

**Comment by opera0001** [comment]
Please submit your application carefully according to the content of the tutorial. Thank you.

CN：https://tphelp.gitbook.io/cn/wallet-operation/submit-token
EN：https://help.tokenpocket.pro/en/developer/how-to-submit-a-token-logo#steps-of-adding-a-token-logo-info

**Comment by opera0001** [comment]
Please check the TPT quantity.

**Comment by aluo0796** [comment]
提交了这么多天不知道什么个情况呢

**Comment by aluo0796** [comment]
不是转账3000TPT么

**Comment by opera0001** [comment]
Please submit your application carefully according to the content of the tutorial. Thank you.

CN：https://tphelp.gitbook.io/cn/wallet-operation/submit-token
EN：https://help.tokenpocket.pro/en/developer/how-to-submit-a-token-logo#steps-of-adding-a-token-logo-info

**Comment by aluo0796** [comment]
可以直接说一下我不能审核的原因么

**Comment by aluo0796** [comment]
我不知道哪里操作的不对，谢谢你！

**Comment by opera0001** [comment]
You can see the next tutorial

**Comment by aluo0796** [comment]
哦哦看到了是30000个，抱歉抱歉

**Comment by opera0001** [comment]
It doesn't matter. I'll help you collect it after you submit the hash value link.

**Pull request closed without merging**
