### PR TITLE
Update SDOGE logo and info

### PR DESCRIPTION
**Pull request by xiaoxiangzi360**
https://bscscan.com/tx/0xa895db4e58a90c16374a904e9735119c4d2ab8c8f73042c2535dae0e3adce45f

### CODE REVIEW

**Comment by xiaoxiangzi360** [comment]
因为上次搞错了，合约地址填错了，1000个TPT转过了，请查看

**Comment by xiaoxiangzi360** [comment]
https://bscscan.com/tx/0xa895db4e58a90c16374a904e9735119c4d2ab8c8f73042c2535dae0e3adce45f

**Comment by zhujiayu03** [comment]
Please refer to the tutorial, and re-submit your files in the correct format.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
