### PR TITLE
Add GBIT logo and info

### PR DESCRIPTION
**Pull request by gbit2022**
https://www.bscscan.com/tx/0x6a7a7434ea99c91d73e29524995b48f259827e83ae2286e1b2ff815a33226874
https://bscscan.com/tx/0x223af8cfde0e6b13626d656aef840858eda1030c0e77a8510f243fce14f04d4a

### CODE REVIEW

**Comment by opera0001** [comment]
There is no TPT donation hash value link, please hurry to supplement.

**Comment by opera0001** [comment]
The contract is not open source, so you can't view the security. Please adjust it quickly.

**Comment by gbit2022** [comment]
Hello,
Currently, our token ICON icon is not displayed in TP wallet assets. We
made changes based on TP's token submission requirements, and also
open-sourced the token contract on GitHub. Please help us put the token
ICON on GitHub as soon as possible. Show in TP wallet

Thanks!
*Service manager*
Mr LK King
*GT insurance group*

***@***.***

10 KALLANG AVENUE APERIA TOWER 2, #13-18, 339510


opera0001 ***@***.***> 于2022年3月9日周三 16:36写道：

**Comment by tplogotijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
