### PR TITLE
Add MZT logo and info

### PR DESCRIPTION
**Pull request by mozartyuanuniverse**
BSC-MZT-0x4fCC5FED1e2D42Ede94dcc5ddA8Ba7FAbBE73101

https://bscscan.com/tx/0x5b36a5c77ea4ba4d1375cb5588f5b6efbfd0ccac133a618bb825ab4d598dda80

[0x4fCC5FED1e2D42Ede94dcc5ddA8Ba7FAbBE73101.zip](https://github.com/TP-Lab/tokens/files/7783749/0x4fCC5FED1e2D42Ede94dcc5ddA8Ba7FAbBE73101.zip)

### CODE REVIEW

**Comment by mozartyuanuniverse** [comment]
0x5b36a5c77ea4ba4d1375cb5588f5b6efbfd0ccac133a618bb825ab4d598dda80

**Comment by mozartyuanuniverse** [comment]
BSC/0x4fCC5FED1e2D42Ede94dcc5ddA8Ba7FAbBE73101
0x5b36a5c77ea4ba4d1375cb5588f5b6efbfd0ccac133a618bb825ab4d598dda80

**Comment by mozartyuanuniverse** [comment]
https://bscscan.com/tx/0x5b36a5c77ea4ba4d1375cb5588f5b6efbfd0ccac133a618bb825ab4d598dda80

**Comment by mozartyuanuniverse** [comment]
> https://bscscan.com/tx/0x5b36a5c77ea4ba4d1375cb5588f5b6efbfd0ccac133a618bb825ab4d598dda80

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3579750034，审核失败的走加速审核包通过

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
