### PR TITLE
Add BEDC logo and info

### PR DESCRIPTION
**Pull request by zb305107**
https://bscscan.com/tx/0x6658e9b8b2b8dcf6a1433b377ad9e2bf2c94af4c429125ffa3a2dd26ebc2d65e

### CODE REVIEW

**Comment by opera0001** [comment]
1. No capital flow pool detected
2. Tokens are in circulation, and the transaction mode is unclear, so security cannot be defined
3. Token logo is not 256x256 pixels
Please submit the token logo application after readjustment or optimization. Thank you for your support for tokenpocket.

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
