### PR TITLE
Add ZQ logo and info

### PR DESCRIPTION
**Pull request by nunu377**
合约地址：0x2957e94C7011B94a96c900B4a4120c54034319Df
BSC-ZQ NFT-0x2957e94C7011B94a96c900B4a4120c54034319Df

BSC-TPT-https://bscscan.com/tx/0x912a90c79e1cdbdec1a1b4577f3113f357de297bf78c155594d743ce5ecbb865
BSC-BNB-https://bscscan.com/tx/0x2181c7f9003f74ac8ee47bedab757d9f0a188c891d6a2aa984d4e575fd8bdafa

### CODE REVIEW

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Comment by nunu377** [comment]
logo is already show in wallet，why nft image can't be show?
nft image is saved in ipfs with jpg format

**Comment by nunu377** [comment]
I see the logo but not the NFT image. NFT images are uploaded in ipfs. It
is in JPG format. I don't know if the TP wallet can be displayed.

opera0001 ***@***.***> 于2022年5月3日周二 10:28写道：

**Comment by nunu377** [comment]
Contract address: 0x2957e94C7011B94a96c900B4a4120c54034319Df.
I haven't seen the 3 NFT pictures of this contract address in the tp
wallet. I want to know if there is a problem with my contract or other
reasons, so I can find the problem.

C Alexander ***@***.***> 于2022年5月3日周二 17:21写道：

**Comment by nunu377** [comment]
The wallet has never shown a picture of the currently deployed NFT contract. Not sure where the problem is.
Contract address: 0x2957e94C7011B94a96c900B4a4120c54034319Df

**Comment by nunu377** [comment]
Donated TPT, but I haven't seen the NFT picture, please tell me if the
reason is a chain problem, a contract problem, or something else.

[image: 92bbe289ea19f07e3a85b975cf0f75c.png]
[image: e6f77864d34c20c690c51694a20aa6d.png]

C Alexander ***@***.***> 于2022年5月3日周二 18:19写道：

**Pull request merged**
