### PR TITLE
fix ESG logo

### PR DESCRIPTION
**Pull request by chenjianmei111**
交易Hash链接：https://bscscan.com/tx/0x669810f61005565ee8eeaa84500ac6290f5d68a5beedadd7f24c94e550c211f2
验证链接：https://bscscan.com/tx/0xd992de4d9697f4b4b046de38a3b1ff4badeb6dde45b0a6d8547b613d6dd18061

之前有提交过了，也成功了，但logo我们需要换一下，所以重新提交了一下。麻烦通过，谢谢。

### CODE REVIEW

**Comment by opera0001** [comment]
Sorry, the inclusion interval is long, so now you need to submit a new tpt hash for any logo or contract address changes.

**Comment by chenjianmei111** [comment]
交易哈希链接：https://bscscan.com/tx/0x0e683c3fc7e60630a52a175db1e721535f6b92e2a417d12ebeb43a2f0ad06e5f
验证链接：https://bscscan.com/tx/0x4a15a61de7a31011e5573af3a26ba0827de05f69ae51b8b285a21d5d672c96ab

重新提交了谢谢

**Comment by opera0001** [comment]
A hash duplicate of #7740 is used, please explain the situation.

Send 0.00000713 bnb to 0x7837ae9e4fd6e967f1b8c8824d6288ece6e730f9 address to verify and tell me the transfer hash value.

**Comment by chenjianmei111** [comment]
抱歉，已经重新捐赠TPT：

交易哈希链接：https://bscscan.com/tx/0x70b7cfcb236fca3932e5f9ec93ba7dd4d970896a1dea9ef378e2f489a8ae93d6

验证链接：https://bscscan.com/tx/0x926169f67661d6eed45bed00767e46da73dc8f887426c77b524857a409a714c9

**Pull request merged**
