### PR TITLE
Add BDD logo and info

### PR DESCRIPTION
**Pull request by shuliangfu**
https://bscscan.com/tx/0x44068d6fee72933de397675fea3faae4c1977e3557504e8bab969e7fc53ec8c2

### CODE REVIEW

**Comment by shuliangfu** [comment]
Add WOH logo and info
BSC - TPT - 0x6aD8F34d91Ec7fa785Dcdd24C2D57d486aA4E51A - https://bscscan.com/tx/0x44068d6fee72933de397675fea3faae4c1977e3557504e8bab969e7fc53ec8c2

Add HLN logo and info
BSC - TPT - 0x01074F2f213ebd00587a773e461B5BC7F7B04C3B - https://bscscan.com/tx/0x6545b3eb84549fdc4ded05a19baa4929996f658bdcd49afd2259f2afbffda0c4

**Comment by opera0001** [comment]
1. The submitted URL cannot be opened
2. Without giving up ownership, there may be additional issuance mechanism and certain risks
Please re submit the logo after adjustment or optimization. Thank you for your support for tokenpocket.

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
