### PR TITLE
Add SCC logo and info

### PR DESCRIPTION
**Pull request by tubiaotijao**
https://hecoinfo.com/tx/0x60c7a6f9b75800101d4f3b3ff24dbcc901cf2d8c89ca97689edc4b946b5074e0

### CODE REVIEW

**Comment by tiaojiaotubiaobaoguo** [comment]
代提交logo，24小时内包过，加QQ：2980874528

**Comment by sammvio** [comment]
Please re-submit these tokens separately and attach the TPT transfer link on [Commit changes].

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by logobaoguo** [comment]
专业提交logo！加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
