### PR TITLE
Add LendFlare project on ethereum chain

### PR DESCRIPTION
**Pull request by LendFlare**
Add LendFlare project

### CODE REVIEW

**Comment by opera0001** [comment]
TPT hash value link not found

**Comment by LendFlare** [comment]
@opera0001 https://etherscan.io/tx/0x18535ec4aaa26f9f4b3f1c1a530507c6b080cbde31f003f19d51eec839357b12

**Comment by opera0001** [comment]
It is detected that there may be a proxy contract in the token contract, please check.

**Comment by LendFlare** [comment]
@opera0001 Yes, we have proxy on the outside of the contract. No problem

**Comment by LendFlare** [comment]
Plz merge branch codes.

**Pull request merged**
