### PR TITLE
Add 7B logo and info

### PR DESCRIPTION
**Pull request by guodayang007**
交易ID:0xe42c47b1177a050de6d10d12fafb4f31901c688a798b90cc45611cca8a33d1ae

### CODE REVIEW

**Comment by opera0001** [comment]
image

1. The donated quantity is incorrect.
2. The submitted logo is not 256x256 pixels, please make the necessary adjustments.
3. It has been detected that the token's contract is not open-source, which poses various risk factors.

**Comment by guodayang007** [comment]
my update logo.png 256x256 pixels

two transactions
5000TPT
txID: 0xe42c47b1177a050de6d10d12fafb4f31901c688a798b90cc45611cca8a33d1ae
45,000 TPT
txID :https://bscscan.com/tx/0x85727aeb49d31c4e8497a472487ef07c85ac52130e6fbc60d3b203399943d212

**Comment by opera0001** [comment]
Detected the presence of hidden owner permissions, which can be a potentially dangerous feature. Therefore, without an official security company's audit report, the token cannot be listed. Apologies.

**Comment by opera0001** [comment]
The token contains hidden owner permissions, which is a very dangerous behavior. Therefore, if you provide the security testing results from a legitimate security audit company, I believe the token's logo cannot be included. The hash value link you submitted can be used in future new orders.

**Comment by guodayang007** [comment]
In the contract, only the burning fee is set, and we have not changed the user's balance, nor have we permission to set the user's blacklist. If the logo cannot be listed, please return our 50000 TPT

**Pull request closed without merging**
