### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by visa2021**
Hello, I add LOGO to my TOKEN
My TOKEN contract address is  0x4D18f01C2E92CAf08E1bdBfDaA3437d6C715c68b

Note
The transaction ID of my smart contract  -1000TPT  is
https://bscscan.com/tx/0xb3411fcac8fdb568b39a0dd723aa7ae6f18d4f9df750d1d140374cd320800aa3

Note2：

contract MyToken
{
 "name": "Brothers wine",
 "website": "https://anhem.top",
 "description": "A leading multi-chain wallet that supports BTC, ETH, BSC, HECO, TRON, EOS, OKExChain, HSC and so on.",
 "explorer": "https://bscscan.com/token/0x4D18f01C2E92CAf08E1bdBfDaA3437d6C715c68b",
 "type": "BEP20",
 "symbol": "ANHEM",
 "decimals": 4,
 "status": "active",
 "id": "0x4D18f01C2E92CAf08E1bdBfDaA3437d6C715c68b"
}

Note3：LOGO
  ANHEM

### CODE REVIEW

**Comment by tubiaoyingji** [comment]
专业加快提交LOGO，20分钟内审核包过，QQ：1450001284

**Comment by sammvio** [comment]
Please donate 3000 TPT as required and submit the transfer link on [Commit changes].

**Comment by visa2021** [comment]
Dear, because some websites introduce different price guidance, I have lost
2000TPT. I can add another 2000TPT. Can I add it? Still have to transfer
3000TPT again. Thank you

SS ***@***.***> 于 2021年12月4日周六 16:20写道：

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by visa2021** [comment]
Ok.你们包过多少钱啊

我第一次提交1000TPT失败，第二次又缴纳过3000TPT了

jiasutijiao ***@***.***> 于 2022年1月3日周一 13:12写道：

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
