### PR TITLE
upload bbc logo and info

### PR DESCRIPTION
**Pull request by amu2025**

### CODE REVIEW

**Comment by amu2025** [comment]
https://bscscan.com/tx/0x999205f57619841cb80d5843ad13aa2f66b7917bc91348b8c6a9b14f72d7104a

**Comment by opera0001** [comment]
1. The two submitted token names and logos are identical, which is not reasonable. 
2. It has been found that both contract addresses contain hidden owner control permissions, which is very dangerous. Therefore, you must provide a code security certificate from a security company.

**Comment by amu2025** [comment]
I only need a contract, the contract address: 0x76550ad5e84882995a7D6db34FA0A95fEb2E7b4E. In addition, if I give up the owner, can I not provide the smart contract audit certificate

**Comment by amu2025** [comment]
I have deleted the old smart contract

**Comment by opera0001** [comment]
Sorry, discarding the token control permissions does not affect the control permissions of the hidden owner, so my apologies. If the token cannot be listed, you don't need to worry; the TPT hash value you submitted can still be used in future submissions.

**Comment by amu2025** [comment]
What can I do other than provide a code audit? Can I modify my contract to meet the conditions of TP Wallet

**Comment by amu2025** [comment]
Can I publish a contract for an owner whose contract is not included? Can you not need the logo on the code audit

**Comment by opera0001** [comment]
Perhaps you can remind me to check again some time after the token starts trading. I need to ensure the security of the token as much as possible, and I hope you understand.

**Comment by amu2025** [comment]
I have deleted the old contract, released the new contract, contract address:0xa0e80327691e5B1f1E8Bccf223db091f9b69acE7

**Comment by amu2025** [comment]
I have removed the permission of hidden owner, may I ask whether this can pass the review?

**Pull request merged**
