### PR TITLE
Add Okx logo and info

### PR DESCRIPTION
**Pull request by berners666**
3000tpt转账哈希：https://bscscan.com/tx/0x91d732a8ff824c463fdc43cd73c0534230da10a37c18d48229d6a6337cdc8215

### CODE REVIEW

**Comment by opera0001** [comment]
The token name and logo are highly similar to the okex platform, so the logo cannot be included for you, and other similar tokens will not be included. The TPT donation hash value link you submitted can be used for subsequent logo submission.
Thank you for your support of tokenpocket

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
