### PR TITLE
Add FTP logo and info

### PR DESCRIPTION
**Pull request by fptnft**
https://bscscan.com/tx/0xa0435f16f3fc5cccd860b315e42c99e53501c91ff87f8a068ee8e50e8a02528b

### CODE REVIEW

**Comment by opera0001** [comment]
Two tokens with the same name use two similar logos. What is the purpose of this? GitHub account can only submit one logo application at a time. Please adjust the content quickly, and the order will be closed in 24 hours.

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by opera0001** [comment]
One GitHub account can only submit one logo application at a time. 0xc1b27c629877d45570385f66b6d2e0c000ef5a98 has been included, and the other needs to be resubmitted.

**Comment by fptnft** [comment]
0xc1b27c629877d45570385f66b6d2e0c000ef5a98 is wrong. It was closed before uploading. What I want to upload is 0x899cac84f19903b1198b4b301e9f2792fb953. I don't know why the two uploaded together. I'm sorry

**Comment by fptnft** [comment]
I just tried to continue uploading. The result turned into three icons. I don't know what to do. I can't delete the previous upload records. If I upload, it will turn into three. I don't dare to continue uploading. Can you help me? I'm a novice

**Comment by fptnft** [comment]
Should I delete this branch first, pull it again and upload it again

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
