### PR TITLE
Add DogeHonor and info

### PR DESCRIPTION
**Pull request by jiang9872369**
BSC-DogeHonor-
0xAA013100348b7Be017397E3308ed5361071A72c3-https://bscscan.com/tx/0x150d756d999b28c6136008fc9ffda4d103145e15f6aeaca82dd534f38012e19b
以下内容仅作项目说明：DogeHonor作为线下，线上社区高度共识DAO项目，项目总发行量1333枚，需要在销毁至999枚时手动停止销毁，还请审核小哥给予审核通过便利 
                                                                                                                                                                                                                            ——以此致谢！

### CODE REVIEW

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by opera0001** [comment]
0x23788081c244fec6Ef6B82d8ffcAd4e4c1532794--
1. No waiver of contractual ownership
2. There may be switches that control transactions

0xaa013100348b7be017397e3308ed5361071a72c3-- done

**Comment by opera0001** [comment]
Please be informed that 30000 TPT donation fees are required for resubmission.

**Comment by opera0001** [comment]
0xaa013100348b7be017397e3308ed5361071a72c3-- done
0xFeefFd9c8Fe8bDa11567e38B1eBE715BbeCd365B--done

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
