### PR TITLE
Add RecreationToken logo and info

### PR DESCRIPTION
**Pull request by recreationtoken**
RecreationToken is a token issued to integrate blockchain into leisure, entertainment, social and other integrated ecological applications.
https://bscscan.com/tx/0x6cb702e2f8dcae2eb48bf3b0512a2ea13e50a39a36c30457090e073695ef3c27

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Please re-submit your files in the correct format.

**Comment by recreationtoken** [comment]
What kind of format is correct?Thank you

zhujiayu03 ***@***.***> 于2021年7月12日周一 下午3:31写道：

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
