### PR TITLE
Add CNT logo and info

### PR DESCRIPTION
**Pull request by 2966535729**
0x5f1d8c143b2645c46b3e7d8f85d82437f5213e81ac07a2aaf216516efec87edd

### CODE REVIEW

**Comment by sammvio** [comment]
Please re-submit your files to bsc folder

**Comment by 2966535729** [comment]
啥意思？怎么又要重新提交？？？？





发自我的iPhone


------------------ Original ------------------
From: SS ***@***.***&gt;
Date: Wed,Jan 19,2022 9:44 PM
To: TP-Lab/tokens ***@***.***&gt;
Cc: 2966535729 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [TP-Lab/tokens] Add CNT logo and info (PR #4950)





 
Please re-submit your files to bsc folder

**Comment by 2966535729** [comment]
已经第二次了？？？？啥意思i


？发自我的iPhone


------------------ Original ------------------
From: SS ***@***.***&gt;
Date: Wed,Jan 19,2022 9:44 PM
To: TP-Lab/tokens ***@***.***&gt;
Cc: 2966535729 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [TP-Lab/tokens] Add CNT logo and info (PR #4950)





 
Please re-submit your files to bsc folder

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
