### PR TITLE
Add BTCK logo and info

### PR DESCRIPTION
**Pull request by watano**
https://bscscan.com/tx/0x90d1c325d93d54a451ebeb22eabe8aaf73701a913d01e4e446a587dbaefeb0fe

### CODE REVIEW

**Comment by opera0001** [comment]
Agency contract is detected, which may have certain risks. Please explain the situation.

**Comment by watano** [comment]
BTCK have some feature still not implement, so we use the openzeppelin upgrade contract.

**Comment by opera0001** [comment]
When can I finish it?

**Comment by watano** [comment]
These feature was finished, but we need test and keep it stable. then we will transferr the administrative authority to the black hole account, but we plan do this on June. And BTCK token had publish 22 days, the market has returned to stability. Now we need let more people know about BTCK, so pls help us upload the BTCK icon on tokenpocket wallet, tks.

**Pull request merged**
