### PR TITLE
ADD AP LOGO INFO

### PR DESCRIPTION
**Pull request by BIGsharkX**
ADD AP LOGO INFO

### CODE REVIEW

**Comment by BIGsharkX** [comment]
Antarctic penguin
https://bscscan.com/tx/0x38011e2beb6f4b3fcd0b5d18700d3a7457945af25085d377857ce3921f998108

**Review by BIGsharkX — COMMENTED** [review]
https://hecoinfo.com/tx/0xf31f85872ea9e4d67b099c1ae997704f5f030b11faaa8c2b55f12a2936765d1a

**Comment by zhujiayu03** [comment]
Please re-submit your snail files to heco folder

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
