### PR TITLE
Add TIMES logo and info

### PR DESCRIPTION
**Pull request by NB-ctrl-hub**
0xf345753422f7d7670b35168e911277c7fd2237b9a4ba62b2a630e2b88a74d318

### CODE REVIEW

**Comment by opera0001** [comment]
1. The TPT donation hash value of one payment can only be used for the addition or replacement of one token logo
2. The time token has been replaced for you
3. It is not recommended to use the same image as the logo

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
