### PR TITLE
Add Meta Baby info and logo

### PR DESCRIPTION
**Pull request by asasa56565**
3000tpt:https://bscscan.com/tx/0x0461bdc675fa8135d76cf58a9c25ad53ca6c2bce5f74fecb9fbbf576fe273a57
bsc::https://bscscan.com/tx/0xb38a9595895827c0843bca5b0978c217947e9413510739146c2194645165bce1

### CODE REVIEW

**Comment by tiaojiaotubiaobaoguo** [comment]
代提交logo，24小时内包过，加QQ：2980874528

**Comment by sammvio** [comment]
Please re-submit your files to bsc folder

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
