### PR TITLE
Add HDO logo and info

### PR DESCRIPTION
**Pull request by ok668**
https://bscscan.com/tx/0x8322f3b0f007563f31ab3a28d4d7f60669073ad783219599f4ac165e47d87ca2

### CODE REVIEW

**Comment by ok668** [comment]
Thanks!!

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by opera0001** [comment]
1. Not relinquishing ownership
2. There will be risks if the capital pool is not locked
There are many assets in the capital pool, so it is safer to give up ownership. Please re adjust or optimize and submit the logo. Thank you for your support for tokenpocket.

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
