### PR TITLE
Replace FT logo and info

### PR DESCRIPTION
**Pull request by ccc3773**
BSC-FT-0xF145AE0b57B4AE2475c35E7deb2055d5dc24FB61-https://bscscan.com/tx/0x5ad8dfa2c30330d5e142fb8090874bd186304b3f927b827b44e41b43cead6493

Original Contract  0xcc21f75ff719ae44e9acabd59d899c7b364b60c0
Current Contract   0xF145AE0b57B4AE2475c35E7deb2055d5dc24FB61
Please change the logo to the current contract address

### CODE REVIEW

**Comment by opera0001** [comment]
Sorry dear, if the logo included in a short time needs to be changed, we can help you replace it for free, but if you need to change the contract address, it is equivalent to a new submission, so you will need a new donation to proceed with the replacement.

**Comment by ccc3773** [comment]
Because the contract address is wrong, I reissued a contract. Please help me replace it. I don’t need the previous contract address with the logo.

**Comment by ccc3773** [comment]
I want to replace the previous logo with a new contract address. The name of the token is the same as the logo. Please help me replace it.

**Comment by ccc3773** [comment]
I’m sorry that the development engineer changed the contract address. Nothing else has changed. The name and logo of the token are still the same. Please help me change the logo.
________________________________
发件人: opera0001 ***@***.***>
发送时间: 2024年9月28日 22:25
收件人: TP-Lab/tokens ***@***.***>
抄送: ccc3773 ***@***.***>; Author ***@***.***>
主题: Re: [TP-Lab/tokens] Replace FT logo and info (PR #11006)


Sorry dear, if the logo included in a short time needs to be changed, we can help you replace it for free, but if you need to change the contract address, it is equivalent to a new submission, so you will need a new donation to proceed with the replacement.

―

**Comment by opera0001** [comment]
Sorry dear, if it's just changing the logo, whether it's a week or two, we can help, but the contract address is an identity label for a token, so its change must be accompanied by a new order. This is not due to any mistakes in our work, so we apologize.

**Comment by ccc3773** [comment]
This is caused by me, please help me, this is indeed a project, and the token is indeed re-issued with the original code. I hope to replace the logo of the original contract address with the new contract address
________________________________
发件人: opera0001 ***@***.***>
发送时间: 2024年10月2日 9:24
收件人: TP-Lab/tokens ***@***.***>
抄送: ccc3773 ***@***.***>; Author ***@***.***>
主题: Re: [TP-Lab/tokens] Replace FT logo and info (PR #11006)


Closed #11006<https://github.com/TP-Lab/tokens/pull/11006>.

―

**Pull request closed without merging**
