### PR TITLE
Add UNIC logo and info

### PR DESCRIPTION
**Pull request by UNIC66**
https://bscscan.com/tx/0x599ce7f48a3cbc3f103c65f15e3d030980504ce61980a4f1c055eeee3071c5eb

### CODE REVIEW

**Comment by opera0001** [comment]
It is suggested that the main elements of the logo you submitted should not overlap or be similar to those of uni, otherwise it may affect the collection of your token logo. Please adjust, thank you.

**Comment by UNIC66** [comment]
Logo has been replaced.Please review. Thanks!

**Comment by opera0001** [comment]
image
I hope there will be an obvious change with the logo of uniswap.

**Comment by STARGlobal** [comment]
This logo has been used in other places. Replacing the logo will lead to inconsistency in many places, which will make users think it is two coins. Could you please make some accommodation

**Comment by opera0001** [comment]
If the logo needs to be replaced or removed due to other factors, the details will be communicated at that time.

**Comment by STARGlobal** [comment]
thanks!

**Comment by UNIC66** [comment]
ok! Thank you  very much!

**Pull request merged**
