### PR TITLE
Add WKT logo and info

### PR DESCRIPTION
**Pull request by liange666**
Add WKT logo and info

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Please re-submit the TPT transfer link on [Commit changes].

**Comment by liange666** [comment]
https://hecoinfo.com/tx/0x910163fff711b088efd2f931ed56c55fd2f25c7c241c9149e4cde328b3f5e84e

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
