### PR TITLE
Add TEST logo and info

### PR DESCRIPTION
**Pull request by linsrin**
0xcd21624713ddf90065abfe63e27053ed932e2822748600c55877211290cd4f4a
0xd4a3a99cc79c85bb02fd79e5a79268ad052472ff2bb0a2856768c86d24bdb25d

### CODE REVIEW

**Comment by opera0001** [comment]
Now the collection logo needs to submit 30000 TPT donation hash value. Please supplement the difference and submit the hash value link in GitHub.

**Comment by opera0001** [comment]
A GitHub account can only submit one logo application.

**Comment by tubiaotijao** [comment]
123

**Comment by tplogotijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
