### PR TITLE
ADD GBOX LOGO and info

### PR DESCRIPTION
**Pull request by gboxspace**
Gbox is a multichain NFT marketplace built for Game and Metaverse assets.

### CODE REVIEW

**Comment by gboxspace** [comment]
ADD GBOX LOGO and info

**Comment by logobaoguo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by sammvio** [comment]
Please donate 3000 TPT as required and submit the transfer link on [Commit changes].

**Comment by gboxspace** [comment]
https://bscscan.com/tx/0xe5e8aa60f4b2281dde5a240d7b4778aae37de613d4c169aaf5c6c4b87a9b39c0

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
