### PR TITLE
Add MOS Info and Logo

### PR DESCRIPTION
**Pull request by KristenLan666**
https://bscscan.com/tx/0x779cd648919fe0c3abc8c64a1eabc6c8b49d053a7c5e03ec9fef236c69dda2ad

### CODE REVIEW

**Comment by opera0001** [comment]
1. If the ownership of the contract is not abandoned, there may be some risks
2. There is no contact information in the official website address. If you encounter problems, you can't contact the project party
Please re adjust and submit the logo application. Thank you for your support for tokenpocket

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
