### PR TITLE
Add DLC logo and info

### PR DESCRIPTION
**Pull request by cd159822**
https://bscscan.com/tx/0x4793aaa1fa0ba75975778b372565290983bad682c8d7fee48d96cc840d95efe2

### CODE REVIEW

**Comment by opera0001** [comment]
A GitHub account can only submit one logo application at a time.

**Comment by jjjgjk** [comment]
1212在吗1212在吗1212在吗

**Comment by jjjgjk** [comment]
1212在吗

**Comment by jjjgjk** [comment]
你好

**Comment by tplogotijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
