### PR TITLE
add AIOT logo and info

### PR DESCRIPTION
**Pull request by ECS202008**
https://bscscan.com/tx/0xdad402e8dafe6ce59816ca43fc6d7104042192fb2d91b1e3958608a078f9925c

### CODE REVIEW

**Comment by opera0001** [comment]
0xdFDd34eF556422E6568DBb552831C8968a0C81c3

**Comment by opera0001** [comment]
0x1FdcD07a314Cbc2dCcfAC578a79E5d2C116f0F9B--
1. No waiver of contractual ownership
2. There may be switches that control transactions

0xdFDd34eF556422E6568DBb552831C8968a0C81c3--done

**Comment by opera0001** [comment]
We haven't seen any changes in the submitted contract after 6 hours. Now we need to close the order and resubmit TPT donation. The number of donations has been increased to 30000. Please know.

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
