### PR TITLE
ADD PTG info and logo

### PR DESCRIPTION
**Pull request by pmj0812**
30000TPT hash：https://bscscan.com/tx/0x4ba277d10040cd2122806aeb36b6e647ec504635a62c0123efb14da4244471a9
info  hash:  https://bscscan.com/tx/0x0c762cbfe56007a72929c1c22990239b401d1e25c37913004ac8059d99abe00c

### CODE REVIEW

**Comment by opera0001** [comment]
image

Please explain the #6504 used logo. Someone complained about your infringement. If you have the original logo design, please show it.


Why should a TPT hash link submit multiple orders?

**Comment by pmj0812** [comment]
#6468 has  closed  i don't know how to open that commit

**Comment by opera0001** [comment]
How can you verify that this TPT hash link is yours?

**Comment by pmj0812** [comment]
of course i will user this hash sender to send new transaction 0.00324 BNB to your address to check this.

**Comment by opera0001** [comment]
Please send 0.00001bnb to this address for verification. Thank you.

0x8ebD347A1706f7d18C5877B2e670fb212b9e857A

**Comment by opera0001** [comment]
Please send 0.00001bnb to this address for verification. Thank you.

0x8ebD347A1706f7d18C5877B2e670fb212b9e857A

**Comment by pmj0812** [comment]
I have send your ask number to your address



---Original---
From: ***@***.***&gt;
Date: Thu, Apr 7, 2022 00:05 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] ADD PTG info and logo (PR #6530)




 
Please send 0.00001bnb to this address for verification. Thank you.
 
0x8ebD347A1706f7d18C5877B2e670fb212b9e857A

**Comment by opera0001** [comment]
done

**Comment by pmj0812** [comment]
thank you for your help

**Pull request merged**
