### PR TITLE
Add SC logo and info

### PR DESCRIPTION
**Pull request by 963149946**

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Please submit the 100 TPT transaction ID

**Comment by 963149946** [comment]
I transfered 100 TPT to you yesterday, and the transaction hash is 0x6f543c2ebe0743052f8adea90bb2ddc29738a97ef8042923f4c88b089f38ab15

**Comment by 963149946** [comment]
> Please submit the 100 TPT transaction ID

I transfered 100 TPT to you yesterday, and the transaction hash is 0x6f543c2ebe0743052f8adea90bb2ddc29738a97ef8042923f4c88b089f38ab15

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
