### PR TITLE
Add WAR logo and info

### PR DESCRIPTION
**Pull request by WarnerMetaverse**
https://bscscan.com/tx/0x0eabed5419c972c1de80895170b7ce5d1a067c041ce37cab0b1ac9ef07e7c6b5
https://bscscan.com/tx/0xc395156802d8b2e3a766b0dc62f57895b08bedd04d66edd8198f071bbd29515b

### CODE REVIEW

**Comment by opera0001** [comment]
Is the submitted website directly related to the token? I only saw a brief introduction, no application entry, and the pictures inside are very risky if they are used without authorization.

**Comment by WarnerMetaverse** [comment]
Confirm that the website is directly related to the token. At present, the application has not been opened, and the link portal has been reserved. The application will be opened soon.

**Comment by WarnerMetaverse** [comment]
> Is the submitted website directly related to the token? I only saw a brief introduction, no application entry, and the pictures inside are very risky if they are used without authorization.

Confirm that the website is directly related to the token. At present, the application has not been opened, and the link portal has been reserved. The application will be opened soon.

**Comment by opera0001** [comment]
1. Token contract ownership is not discarded
2. Token transaction not started
3. It is detected that there is a setting that can control the token transaction switch
We need to observe whether it is safe after the token starts trading

**Comment by opera0001** [comment]
1. Token contract ownership is not discarded
2. Token transaction not started
3. It is detected that there is a setting that can control the token transaction switch
We need to observe whether it is safe after the token starts trading

**Comment by WarnerMetaverse** [comment]
> 1. Token contract ownership is not discarded
> 2. Token transaction not started
> 3. It is detected that there is a setting that can control the token transaction switch
>    We need to observe whether it is safe after the token starts trading


How do I operate in this situation? Is it to reapply after the token transaction starts?

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
