### PR TITLE
Add BDD logo and info

### PR DESCRIPTION
**Pull request by MrMDC**
https://bscscan.com/tx/0x7c69ee71c0276f2f6dcc0b0a53435d944e1343e7aca27c78063a44dde2cf5a3b

### CODE REVIEW

**Comment by opera0001** [comment]
The main diagram of the logo contains the bingdundun element, which is an infringement
Please re submit the logo application after adjustment. Thank you for your support for tokenpocket.

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
