### PR TITLE
ADD UPDT logo and info

### PR DESCRIPTION
**Pull request by MTMetaverse**

### CODE REVIEW

**Comment by opera0001** [comment]
image
The submitted file is not stored in the BSC directory.
The submitted logo is not 256x256 pixels.
The TPT hash value has not been submitted.

**Comment by MTMetaverse** [comment]
捐赠的那个tpt哈西吗





发自我的iPhone


------------------ Original ------------------
From: opera0001 ***@***.***&gt;
Date: Thu,Nov 23,2023 2:00 PM
To: TP-Lab/tokens ***@***.***&gt;
Cc: MTMetaverse ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [TP-Lab/tokens] ADD UPDT logo and info (PR #10044)





 

 The submitted file is not stored in the BSC directory.
 The submitted logo is not 256x256 pixels.
 The TPT hash value has not been submitted.

**Comment by MTMetaverse** [comment]
一般，按流程提交完tpt，多久可以显示





发自我的iPhone


------------------ Original ------------------
From: opera0001 ***@***.***&gt;
Date: Thu,Nov 23,2023 2:00 PM
To: TP-Lab/tokens ***@***.***&gt;
Cc: MTMetaverse ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [TP-Lab/tokens] ADD UPDT logo and info (PR #10044)





 

 The submitted file is not stored in the BSC directory.
 The submitted logo is not 256x256 pixels.
 The TPT hash value has not been submitted.

**Comment by opera0001** [comment]
CN：https://tphelp.gitbook.io/cn/wallet-operation/submit-token
EN：https://help.tokenpocket.pro/en/developer/how-to-submit-a-token-logo#steps-of-adding-a-token-logo-info

The above is our official submission process and requirements, which you can view through the link. In normal circumstances, if the submitted order complies with the inclusion specifications, we aim to complete the inclusion process within two days. For example, if your current submission is a complete order that meets the inclusion criteria, relevant processing for inclusion would be initiated at this moment.

**Comment by UniallPay** [comment]
有电报联系方式吗？？捐赠tpt没搞好



发自我的iPhone


------------------ Original ------------------
From: opera0001 ***@***.***&gt;
Date: Thu,Nov 23,2023 2:00 PM
To: TP-Lab/tokens ***@***.***&gt;
Cc: MTMetaverse ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [TP-Lab/tokens] ADD UPDT logo and info (PR #10044)





 

 The submitted file is not stored in the BSC directory.
 The submitted logo is not 256x256 pixels.
 The TPT hash value has not been submitted.

**Comment by UniallPay** [comment]
在吗，请帮我审核下，准备捐赠tpt



发自我的iPhone


------------------ Original ------------------
From: opera0001 ***@***.***&gt;
Date: Thu,Nov 23,2023 2:00 PM
To: TP-Lab/tokens ***@***.***&gt;
Cc: MTMetaverse ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [TP-Lab/tokens] ADD UPDT logo and info (PR #10044)





 

 The submitted file is not stored in the BSC directory.
 The submitted logo is not 256x256 pixels.
 The TPT hash value has not been submitted.

**Comment by UniallPay** [comment]
在吗





发自我的iPhone


------------------ Original ------------------
From: opera0001 ***@***.***&gt;
Date: Thu,Nov 23,2023 2:00 PM
To: TP-Lab/tokens ***@***.***&gt;
Cc: MTMetaverse ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [TP-Lab/tokens] ADD UPDT logo and info (PR #10044)





 

 The submitted file is not stored in the BSC directory.
 The submitted logo is not 256x256 pixels.
 The TPT hash value has not been submitted.

**Pull request closed without merging**
