### PR TITLE
Add THB logo and info

### PR DESCRIPTION
**Pull request by b13122837066**
Add THB logo and info

### CODE REVIEW

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

The contract address corresponding to the logo to be deleted is not seen. Please use GitHub to submit your account message.

**Comment by b13122837066** [comment]
> 
[Add THB logo and info](https://github.com/TP-Lab/tokens/pull/6663/commits/7bed2b9187695cc610a2847e5fea24b6120bca4d)

**Comment by b13122837066** [comment]
> 订单申请已收到，请耐心等待审核。不要相信任何非官方的消息，并保护自己免受诈骗。
> 
> 没有看到要删除的logo对应的合约地址。请使用 GitHub 提交您的帐户消息。

[Add THB logo and info](https://github.com/TP-Lab/tokens/pull/6663/commits/7bed2b9187695cc610a2847e5fea24b6120bca4d)

**Comment by b13122837066** [comment]
> > 申请已收到，请等待等待任何的消息，并保护自己的非官方广告宣传。
> > 没有看到要删除的协定地址。请使用 GitHub 提交您的帐户信息。
> 
> [添加 THB 徽标和信息](https://github.com/TP-Lab/tokens/pull/6663/commits/7bed2b9187695cc610a2847e5fea24b6120bca4d)

Add files via upload is wrong

**Pull request closed without merging**
