### PR TITLE
Add UCN logo and info

### PR DESCRIPTION
**Pull request by UNIC66**
https://bscscan.com/tx/0xcabaf8987a0221b06713a44995a00b6fb6421baecfd5ac29150d2ed98438b339

### CODE REVIEW

**Comment by UNIC66** [comment]
记得把简介更新到上面，还有nft有缓存，图片及内容显示的不正确，帮忙解决下，感谢

**Comment by UNIC66** [comment]
这个logo适合unic一起成一个生态的

**Comment by opera0001** [comment]
Check whether there is any problem with the server storage format of nft. Under normal circumstances, nft that has been open source and included by TokenPocket can be displayed normally.

**Comment by UNIC66** [comment]
谢谢， 已经正常显示了，帮忙合并下

**Pull request merged**
