### PR TITLE
Add PolyBabyDoge logo and info

### PR DESCRIPTION
**Pull request by ImUrFuture**
https://bscscan.com/tx/0xf73374297208f9e57c2d3b7206d764ef0a7d8d3ac214244a52973cccfd3e43d4

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Please submit the complete file.

**Comment by ImUrFuture** [comment]
What do u mean complete file? I have uploaded both logo and info.

**Comment by ImUrFuture** [comment]
> Please submit the complete file.

What do u mean complete file? I have uploaded both logo and info.

**Comment by ImUrFuture** [comment]
你好 我已经重新提交了图标文件 #1086，麻烦尽快审核。先前序号pr#958。还请麻烦加急帮我审核一下。可以付加急费。非常感谢



Sent&nbsp;from&nbsp;my&nbsp;iPhone


------------------ Original ------------------
From: zhujiayu03 ***@***.***&gt;
Date: Wed,Jul 7,2021 4:24 PM
To: TP-Lab/tokens ***@***.***&gt;
Cc: ImUrFuture ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [TP-Lab/tokens] Add PolyBabyDoge logo and info (#958)





 
Please submit the complete file.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Pull request closed without merging**
