### PR TITLE
Add DES logo and info

### PR DESCRIPTION
**Pull request by f846823400**
{
 "name": "Deep Skyline Token",
 "website": "https://www.wstecserver.com/",
 "description": "DES combines the advantages of DeFi and NFT well, combining finance and mechanisms with NFT, games, and airdrop mechanisms to create a completely free market.",
 "explorer": "https://bscscan.com/token/0x7f97da02976c10A9c5c10a2E19491C050A184035",
 "type": "BEP20",
 "symbol": "DES",
 "decimals": 18,
 "status": "active",
 "id": "0x7f97da02976c10A9c5c10a2E19491C050A184035"
}

### CODE REVIEW

**Comment by f846823400** [comment]
I'm waiting patiently

**Comment by f846823400** [comment]
TPT hash:
https://bscscan.com/tx/0x4eab94737c8d1cb0aa91f97c409311189d0b1e2db08bfbf0d7a399f884ac1696
BNB hash:
https://bscscan.com/tx/0x06cb64f72cc465bef5418d536a3447df8c15f9c4b24cb5f36d5ca8ef31bcdc3d

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Comment by f846823400** [comment]
> 订单申请已收到，请耐心等待审核。不要相信任何非官方的消息，并保护自己免受诈骗。

Ok, thanks!

**Pull request merged**
