### PR TITLE
Add MAG logo and info

### PR DESCRIPTION
**Pull request by magicCoin666**
https://bscscan.com/tx/0x2d30c185f923c0a6826a8f24616eb569119888385ffe07b9b840dd7cf5e18a97

### CODE REVIEW

**Comment by magicCoin666** [comment]
Administrator retention is mainly to respond to market demand

**Comment by opera0001** [comment]
The presence of a switch that can control transactions is detected, although it is a setting that is not in circulation before, so how will this feature be handled subsequently. Because the administrator privileges are not given up, so there will be some risk

**Comment by magicCoin666** [comment]
The transaction opens after 50000 addresses. Tokens are given away until the transaction is opened. Permissions are discarded at this point

**Comment by magicCoin666** [comment]
> The presence of a switch that can control transactions is detected, although it is a setting that is not in circulation before, so how will this feature be handled subsequently. Because the administrator privileges are not given up, so there will be some risk

The transaction opens after 50000 addresses. Tokens are given away until the transaction is opened. Permissions are discarded at this point

**Comment by magicCoin666** [comment]
> > The presence of a switch that can control transactions is detected, although it is a setting that is not in circulation before, so how will this feature be handled subsequently. Because the administrator privileges are not given up, so there will be some risk
> 
> The transaction opens after 50000 addresses. Tokens are given away until the transaction is opened. Permissions are discarded at this point

交易规则：持币地址达到5万时开启交易买卖。在此之前用户的币全部是赠送的

**Pull request merged**
