### PR TITLE
Add Milk logo and info

### PR DESCRIPTION
**Pull request by aba998988**
https://hecoinfo.com/tx/0x0de21238702c687e51414ba16a262cb8013b0ed51b623dc4b218e9105cae4368

### CODE REVIEW

**Comment by aba998988** [comment]
https://hecoinfo.com/tx/0xc35e1914a79e60255dee28718ffd861ebebbb138a1625e406e904ac4d9d57400

**Comment by aba998988** [comment]
https://hecoinfo.com/tx/0xc35e1914a79e60255dee28718ffd861ebebbb138a1625e406e904ac4d9d57400
https://hecoinfo.com/tx/0x0de21238702c687e51414ba16a262cb8013b0ed51b623dc4b218e9105cae4368

**Comment by tubiaoyingji** [comment]
专业加快提交LOGO，20分钟内审核包过，QQ：1450001284

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Pull request closed without merging**
