### PR TITLE
add BVG log and info

### PR DESCRIPTION
**Pull request by BovineVerseProject**
https://bscscan.com/tx/0x829e504fd518f154f1739b2e1f25e5589fab9629dad263f04f857ae4df03067d

### CODE REVIEW

**Comment by opera0001** [comment]
You need to submit the TPT donation hash value link, please hurry to supplement.

**Comment by jjjgjk** [comment]
1212在吗

**Comment by jjjgjk** [comment]
1212在吗1212在吗

**Comment by tplogotijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
