### PR TITLE
Add BIT Token info and logo

### PR DESCRIPTION
**Pull request by nypzxy**
Sample

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Please re-submit your files attached TPT transfer link on [Commit changes].

**Comment by nypzxy** [comment]
0x57d766a323b154fff603f7d844bf5ed545dc95a64ac5b6e5543021c8be695021

**Comment by nypzxy** [comment]
Hi,
I just attached a transfer link on Commit change, and resubmitted it.
Please have a look at it as we are a little bit urgent to launch our token.

 Best Regards

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
