### PR TITLE
add 涨 logo and info

### PR DESCRIPTION
**Pull request by kulazhang1**
https://bscscan.com/tx/0xa69dc7dbe10a32c6a2d66477bf037d1acfdd77a296a82242744d02529ff78b68

### CODE REVIEW

**Comment by opera0001** [comment]
image

The token contract includes various settings. Please provide explanations for their functions.

**Comment by kulazhang1** [comment]
I'm sorry that the contract doesn't look very friendly, but as you can see, it's not a honeypot to shield others from profit, it's a function of preserving rights for fair and reasonable management of the community to prevent attacks and unfriendly actions from causing serious consequences, because it's a token of Chinese cultural thought, around "rising", we're down

**Comment by kulazhang1** [comment]
After the community has achieved self-management, it will completely relinquish permissions

**Comment by kulazhang1** [comment]
Permission has been abandoned, please check

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Pull request merged**
