### PR TITLE
Add FPT logo and info

### PR DESCRIPTION
**Pull request by xiazhong123**
https://www.bscscan.com/tx/0x2fe71897a78782a10af6398c0d756591b36dc899af3e5221dd813f475a497e7a

### CODE REVIEW

**Comment by opera0001** [comment]
A setting has been detected that can suspend token transactions, please explain what it does.

**Comment by opera0001** [comment]
I haven't seen your message or changed it after 4 days, so the order needs to be closed, you can contact me through issues.

https://github.com/TP-Lab/tokens/issues

**Comment by xiazhong123** [comment]
There is no setting to suspend the token transaction, the AVE detection can be used, and all permissions have been discarded

**Comment by xiazhong123** [comment]
It has been 10 days. I need to display the application logo information as soon as possible

**Pull request merged**
