### PR TITLE
Add NFTB info and Logo

### PR DESCRIPTION
**Pull request by TPinfolog**

### CODE REVIEW

**Comment by TPinfolog** [comment]
Token Data Info Order
https://bscscan.com/token/0xde3dbbe30cfa9f437b293294d1fd64b26045c71a
NFTb is a complete multi-chain NFT and DeFi platform for the community. Our ultimate goal is to build a NFT and DeFi platform with the best user experience for anyone anywhere.
Transfer 3000TPT Order
the previous request was refused (1000TPT)
https://bscscan.com/tx/0x91f242530ac4a4baed5aea566150ffdafa8661e389e61bdbe263992a30b641ed
now the new donation (2000TPT)
https://bscscan.com/tx/0x05b76e283e2248db2f92f07075b999def2182a1c827aee15e07b53f6a742158f
BNB transfer Hash
https://bscscan.com/tx/0xf401481eda52d92fa13e2d96941ac2aab6d19f6cfeb638009acd407c05b79e7d

**Comment by guoxintongsam** [comment]
Please submit the checksum address that includes uppercase and lowercase characters.

**Comment by Ssssssssssw** [comment]
Please tell me what went wrong，ok?

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
