### PR TITLE
add LYCC logo and info

### PR DESCRIPTION
**Pull request by wanplan**
TPT: https://bscscan.com/tx/0x159fe1703a285240938d0fbcc87233b617fd13556bb7731e13f21f0149630576
BNB: https://bscscan.com/tx/0xca3d6e9b3381830693a5921934c56edf19a5fed9d4e2e6b9945cdd95a98faacd

### CODE REVIEW

**Comment by opera0001** [comment]
image

Is there a problem with the NFT release?

**Comment by wanplan** [comment]
As we mentioned, the nft is mint by our investors,  each for 50 usdt. after our logo and info is updated, we will launch our project.

**Comment by wanplan** [comment]
is there anything we can do?

**Comment by wanplan** [comment]
and we are NFT of  erc721

**Pull request merged**
