### PR TITLE
Add TSE logo and info

### PR DESCRIPTION
**Pull request by fightForTornothStrength**
https://bscscan.com/tx/0x2bd3b3e13343b8fc2589d08c14ca5bd4467145125b0b22467fe7abdd82eaf0d7

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:2980874528

**Comment by sammvio** [comment]
The contract don’t verify and published. (No open-source)

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
