### PR TITLE
add CCC  logo and info

### PR DESCRIPTION
**Pull request by liujianwei1988**
50,000 TPT交易：https://bscscan.com/tx/0x4412b3d8ac6e51f8ccbeb33bcc1ef4a6d6b4beb7bd7b7546c9ff986b4db548f7 
验证后的哈希值链接：https://bscscan.com/tx/0x6df39349ebff5019b6b06ff96b99e7b1e6c2d97d4e4ac0a73c35c5b30e73ada8 

Credit Check Chain - 'Credit Score of Ethereum' is an ETH L2 public chain based on the credit system, dedicated to creating a new Ethereum World with the principle of 'no trade without credit check'.

### CODE REVIEW

**Comment by opera0001** [comment]
Detection of settings for increasing token issuance in the contract, which may pose risks. Please clarify the purpose of doing so.

**Comment by liujianwei1988** [comment]
sir,already fixed increasing token issuance

**Comment by liujianwei1988** [comment]
https://polygonscan.com/tx/0x416cf934d7d6342b3d0d4143093442459c1f7249a909f224a91c9c233209db66#eventlog

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Pull request merged**
