### PR TITLE
Add BTCB logo and info

### PR DESCRIPTION
**Pull request by dwoura**
https://bscscan.com/tx/0x607b34c094c41ffead3aefe4b3367103b185ed9f7533f0fc469b6f611fc45f2e

### CODE REVIEW

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by opera0001** [comment]
There can be tokens with the same name on the chain, but it's unforgivable if you don't even bother to design the logo. The submitted logo is consistent with the official BTCB of binance, which is very risky, and the pixels are poor. negative comment!

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
