### PR TITLE
add TPT logo and info

### PR DESCRIPTION
**Pull request by he511321511321**
sample

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Added

**Comment by he511321511321** [comment]
Hello: wrong icon uploading, not the contract address, very embarrassing

0x0D7A428342ae2e4F3517bDdcfbb8da5F9cE1fD49

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
