### PR TITLE
Add BTJ logo and info

### PR DESCRIPTION
**Pull request by yubinzhu1992**
https://bscscan.com/tx/0x3313e65726c11926bfd74b5c4a64d43cc0872925ae50dc370f571cdab4f3c057

### CODE REVIEW

**Comment by tiaojiaotubiaobaoguo** [comment]
代提交logo，24小时内包过，加QQ：2980874528

**Comment by sammvio** [comment]
Please re-submit these tokens separately and attach the TPT transfer link on [Commit changes].

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
