### PR TITLE
Add DFT logo and info

### PR DESCRIPTION
**Pull request by wanglei9319**
https://bscscan.com/tx/0x7b1e8241d43ff6e22d299260bbf3ac5c497eb3a45739bb0938bebdb9bb3ac6e3
https://bscscan.com/tx/0x674266f6a08a2454e37d3451a7414fafd641f0faa4d24989199ca2997f0fbb1f

### CODE REVIEW

**Comment by wanglei9319** [comment]
补充2000TPT，交易地址：https://bscscan.com/tx/0x674266f6a08a2454e37d3451a7414fafd641f0faa4d24989199ca2997f0fbb1f

**Comment by opera0001** [comment]
Please carefully operate according to the content required in the tutorial. Please adjust it within 24 hours. Thank you.

https://tphelp.gitbook.io/cn/wallet-operation/submit-token

**Comment by wanglei9319** [comment]
之前少打了2000TPT 现在补上了 接下来该怎么操作呢

**Comment by opera0001** [comment]
Please check the content of the tutorial carefully. Thank you.

**Pull request closed without merging**
