### PR TITLE
Add EGG logo and info

### PR DESCRIPTION
**Pull request by menhigkong**
https://bscscan.com/tx/0x2736ac32329416a656eabdb147b87d8037cfad56220a130d42e0b8be0f8f6aa5

### CODE REVIEW

**Comment by menhigkong** [comment]
Hello,
We have submitted the logo and info of EGG on Github a few days ago, but it hasn't been updated yet.
Could you please check for me?

Token symbol: EGG
Token name: Blade EGG
Chain: OKEXChain (OEC)
Contract address: 0x1aB0F0e761F642FE0180c973448A1A7482f81690
TPT transaction hash address: https://bscscan.com/tx/0x2736ac32329416a656eabdb147b87d8037cfad56220a130d42e0b8be0f8f6aa5
Precision: 18

Thank you!

**Comment by tiaojiaotubiaobaoguo** [comment]
代提交logo，24小时内包过，加QQ：2980874528

**Comment by sammvio** [comment]
The contract didn’t verify and publish. (No open-source)

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
