### PR TITLE
Add PEACE logo and info

### PR DESCRIPTION
**Pull request by thank-tp**
30,000 TPT：
https://bscscan.com/tx/0x28fcf074542dd8207a5a32065981b658883fe934a2ba15cbb7c3d66cc2ca831e
TxHash
https://bscscan.com/tx/0x67a29fd737a5090be3172042fd95627d56356169f37402519c55d61e29e202a0

### CODE REVIEW

**Comment by TokenPocket-JAN** [comment]
Speed ​​up the trial. Please reply to the email if you need.
QQ112831047

**Comment by opera0001** [comment]
1. Token contract control is not discarded
2. There are settings that control the transaction switch

**Comment by opera0001** [comment]
We haven't seen the contract adjusted after 15 hours, so we temporarily close the order and need to resubmit it after your adjustment. Thank you for your support of tokenpocket.

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
