### PR TITLE
Add RC logo and info

### PR DESCRIPTION
**Pull request by romacommunity**
https://www.bscscan.com/tx/0x91ff5feffaa093446a8b05475707c4b5d9fc354a7a8424deb499bda965b845bb

### CODE REVIEW

**Comment by romacommunity** [comment]
https://bscscan.com/tx/0x9e53ec182b8a47eb2afd38bd59e135013571a7d3d40aa357d7a1030bc14eebaa

**Comment by zhujiayu03** [comment]
Tron token logo upload is not allowed for now.

**Comment by romacommunity** [comment]
> Tron token logo upload is not allowed for now.

Has the service of uploading the TOKEN been stopped or the information I submitted is wrong?

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Pull request closed without merging**
