### PR TITLE
Add BRD token

### PR DESCRIPTION
**Pull request by 0oo0oo0**
https://bscscan.com/tx/0x40356b49190c2fa49b582c115a7549704839cb4101d47ee4917da6e547db4f8e
https://bscscan.com/tx/0x51519c008634dfbfaa3920bce17761e22378581631ae88060125ca46c59157c0

### CODE REVIEW

**Comment by opera0001** [comment]
Because of the hash value provided in #9608 and its duplication with yours, it is necessary to send 0.000724 BNB to 0x7837ae9e4fd6e967f1b8c8824d6288ece6e730f9 for verification. Thank you.

**Comment by yl** [comment]
image

**Comment by 0oo0oo0** [comment]
This is proof.
https://bscscan.com/tx/0x51519c008634dfbfaa3920bce17761e22378581631ae88060125ca46c59157c0
image

**Comment by 0oo0oo0** [comment]
> Because of the hash value provided in #9608 and its duplication with yours, it is necessary to send 0.000724 BNB to 0x7837ae9e4fd6e967f1b8c8824d6288ece6e730f9 for verification. Thank you.

https://bscscan.com/tx/0xb6a512165414b3b4918c650840b6badd1a83ccb9dc90c7d145c4a57afe4da29c

**Pull request merged**
