### PR TITLE
ADD DSN LOGO AND INFO

### PR DESCRIPTION
**Pull request by FMCG-P**
https://bscscan.com/tx/0x808aa353d161cdaedb3478ef983f9bacf40258c83bb939d69d3c56c471c04d7c

### CODE REVIEW

**Comment by 15875804435** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by opera0001** [comment]
The administrator authority of the token is not discarded, and there is a switch that can control the circulation.

**Pull request closed without merging**
