### PR TITLE
0x470aae2db7eb523136dd01a55f2dfcfe7c1d4d59

### PR DESCRIPTION
**Pull request by RZT37150**
YS

### CODE REVIEW

**Comment by RZT37150** [comment]
YS

**Comment by opera0001** [comment]
0x470AaE2dB7Eb523136dD01a55f2dfCfE7C1D4D59--
The contractual authority has not been waived

0x47ca75b98b0cf0136f99B4E81778C4F59343923c--
Logo is not 256x256 pixels

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
