### PR TITLE
Add PNT logo and info

### PR DESCRIPTION
**Pull request by seeyounet**
0x0340199eb680fc33f5d82e64b42c555de052f152c89a2d0b5b742e370135c477

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Please re-submit your files attached TPT transfer link on [Commit changes].

**Comment by seeyounet** [comment]
https://bscscan.com/tx/0x0340199eb680fc33f5d82e64b42c555de052f152c89a2d0b5b742e370135c477?utm_source=tokenpocket

**Review by seeyounet — COMMENTED** [review]
https://bscscan.com/tx/0x0340199eb680fc33f5d82e64b42c555de052f152c89a2d0b5b742e370135c477?utm_source=tokenpocket

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Pull request closed without merging**
