### PR TITLE
Add New Logo and Info

### PR DESCRIPTION
**Pull request by TokenLogos**
TPT：https://bscscan.com/tx/0xb418208470a867c3d73d4531f3dde406ab1c2823f4bfb93b5d7e208ca44a24c2 
BNB：https://bscscan.com/tx/0x66088a697700ddf372a8c32d016dd45f592a005251cf083ef236da898a144e41

The paused of pool trading function is used to lock the pool before opening to prevent users from adding pools in advance 

old contract pull request: [#8411](https://github.com/TP-Lab/tokens/pull/8411)

This new contract's data and logo is not changed and same to the old contract: **0x4051cc783Ba4bB787C103400575196C24daF94ED**.
But the number of tokens we locked was wrong, so we changed to use this new contract and logo. 
Please cance old contract and use the new contract.
This new contract extend contract address: **0xF51F3605DFaf09b8C8129442FC069FD0A1cf2d2F**, it is same to the old contarct's extend contract: 0x33251C60d690684cFE296A951691666d58FDCB08.
Thank You.

### CODE REVIEW

**Comment by opera0001** [comment]
There is risk of external contract call, please check this section.

**Comment by TokenLogos** [comment]
External contract is open source and External contract address: 0xF51F3605DFaf09b8C8129442FC069FD0A1cf2d2F

**Comment by TokenLogos** [comment]
I pull request and deleted the old contracts here.  
If there are no problems, you can just merge and to help reduce your work.
Thank You.

**Comment by opera0001** [comment]
image
There is a problem with the submitted information, please resubmit, thank you.

**Comment by TokenLogos** [comment]
I use new branch to pull request

**Pull request closed without merging**
