### PR TITLE
Revert "Add SSZ logo and info"

### PR DESCRIPTION
**Pull request by spaceshipzeroa**
Reverts TP-Lab/tokens#9113

### CODE REVIEW

**Comment by opera0001** [comment]
I don't understand what you mean.Please explain the purpose of submitting the order.

**Comment by spaceshipzeroa** [comment]
logo and info

**Comment by spaceshipzeroa** [comment]
SSZ is an ERC20 token, and we uploaded the ERC20 info. However, you mistook the information for BSC, and this path is incorrect. Please change to ERC20

SSZ是ERC20的代币，我们上传的也是ERC20的info，但是你把Y料弄成了BSC的，@路藉e了。修改ERC20
________________________________
发件人: opera0001 ***@***.***>
发送时间: 2023年3月15日 23:49
收件人: TP-Lab/tokens ***@***.***>
抄送: spaceshipzeroa ***@***.***>; Author ***@***.***>
主题: Re: [TP-Lab/tokens] Revert "Add SSZ logo and info" (PR #9137)


I don't understand what you mean.Please explain the purpose of submitting the order.

―

**Comment by spaceshipzeroa** [comment]
This is the information we submitted
这是我们提交的信息


[cid:3c0e3874-94d1-441d-be2a-c17645722eb4]

This is the information you mistakenly searched and recorded that appears on BEP20. What we need is ERC20.
@是你e`搜的信息出F在BEP20，我需要的是ERC20.
[cid:cdfb28f8-31f4-403f-a682-88a2a8ca5257]


________________________________
发件人: Admin James ***@***.***>
发送时间: 2023年3月17日 8:24
收件人: TP-Lab/tokens ***@***.***>
主题: 回复: [TP-Lab/tokens] Revert "Add SSZ logo and info" (PR #9137)

SSZ is an ERC20 token, and we uploaded the ERC20 info. However, you mistook the information for BSC, and this path is incorrect. Please change to ERC20

SSZ是ERC20的代币，我们上传的也是ERC20的info，但是你把Y料弄成了BSC的，@路藉e了。修改ERC20
________________________________
发件人: opera0001 ***@***.***>
发送时间: 2023年3月15日 23:49
收件人: TP-Lab/tokens ***@***.***>
抄送: spaceshipzeroa ***@***.***>; Author ***@***.***>
主题: Re: [TP-Lab/tokens] Revert "Add SSZ logo and info" (PR #9137)


I don't understand what you mean.Please explain the purpose of submitting the order.

―

**Pull request merged**
