### PR TITLE
Add UPUP logo and info

### PR DESCRIPTION
**Pull request by UPUPBSC**
https://bscscan.com/tx/0x5f1de709188b623fb66b645eeaceefb29f1259314ced5f28635297b82536ed94

### CODE REVIEW

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Comment by UPUPBSC** [comment]
Hello, because there is a problem with our contract, we need to change the new contract address, can you cancel the one I submitted? And then I resubmit.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: opera0001 ***@***.***>
发送时间: Monday, April 1, 2024 3:33:03 PM
收件人: TP-Lab/tokens ***@***.***>
抄送: UPUPBSC ***@***.***>; Author ***@***.***>
主题: Re: [TP-Lab/tokens] Add UPUP logo and info (PR #10480)


The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

―

**Comment by opera0001** [comment]
You can send the new contract address here, or you can delete the submitted file and upload it again.

**Comment by UPUPBSC** [comment]
0x37833feA0F78C2f29F66b6F80976C9d681dEE2dC

Please help me to change the contract address, thank you.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: opera0001 ***@***.***>
发送时间: Wednesday, April 3, 2024 10:44:12 AM
收件人: TP-Lab/tokens ***@***.***>
抄送: UPUPBSC ***@***.***>; Author ***@***.***>
主题: Re: [TP-Lab/tokens] Add UPUP logo and info (PR #10480)


You can send the new contract address here, or you can delete the submitted file and upload it again.

―

**Comment by UPUPBSC** [comment]
Hello, dear, please help me update the latest contract address, and then add the Logo, thank you very much.
Contract Address:0x37833fea0f78c2f29f66b6f80976c9d681dee2dc

Good luck with your work.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: UPUP BSC ***@***.***>
发送时间: Wednesday, April 3, 2024 5:18:55 PM
收件人: TP-Lab/tokens ***@***.***>; TP-Lab/tokens ***@***.***>
抄送: Author ***@***.***>
主题: Re: [TP-Lab/tokens] Add UPUP logo and info (PR #10480)


0x37833feA0F78C2f29F66b6F80976C9d681dEE2dC

Please help me to change the contract address, thank you.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: opera0001 ***@***.***>
发送时间: Wednesday, April 3, 2024 10:44:12 AM
收件人: TP-Lab/tokens ***@***.***>
抄送: UPUPBSC ***@***.***>; Author ***@***.***>
主题: Re: [TP-Lab/tokens] Add UPUP logo and info (PR #10480)


You can send the new contract address here, or you can delete the submitted file and upload it again.

―

**Comment by UPUPBSC** [comment]
Hello, dear, can you help us update the new contract address? Thank you very much

New contract addr：0x37833fea0f78c2f29f66b6f80976c9d681dee2dc

The previous submission number was 10480, since there is a problem with the contract address submitted before, we have updated the new contract address, and the audit will be completed soon, so please help me update the new contract address.

Thank you

Good luck with your work.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: UPUP BSC ***@***.***>
发送时间: Wednesday, April 3, 2024 8:04:22 PM
收件人: TP-Lab/tokens ***@***.***>; TP-Lab/tokens ***@***.***>
抄送: Author ***@***.***>
主题: Re: [TP-Lab/tokens] Add UPUP logo and info (PR #10480)

Hello, dear, please help me update the latest contract address, and then add the Logo, thank you very much.
Contract Address:0x37833fea0f78c2f29f66b6f80976c9d681dee2dc

Good luck with your work.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: UPUP BSC ***@***.***>
发送时间: Wednesday, April 3, 2024 5:18:55 PM
收件人: TP-Lab/tokens ***@***.***>; TP-Lab/tokens ***@***.***>
抄送: Author ***@***.***>
主题: Re: [TP-Lab/tokens] Add UPUP logo and info (PR #10480)


0x37833feA0F78C2f29F66b6F80976C9d681dEE2dC

Please help me to change the contract address, thank you.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: opera0001 ***@***.***>
发送时间: Wednesday, April 3, 2024 10:44:12 AM
收件人: TP-Lab/tokens ***@***.***>
抄送: UPUPBSC ***@***.***>; Author ***@***.***>
主题: Re: [TP-Lab/tokens] Add UPUP logo and info (PR #10480)


You can send the new contract address here, or you can delete the submitted file and upload it again.

―

**Comment by UPUPBSC** [comment]
Hello, dear. Thank you very much.

There is one more thing I need your help with. The slippage for selling our tokens is 3%, but your wallet shows 14.6%. The one shown on AVE is correct. Could you please verify it and help us modify it? Thank you very much!

Good luck with your work.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: opera0001 ***@***.***>
发送时间: Friday, April 5, 2024 2:42:40 PM
收件人: TP-Lab/tokens ***@***.***>
抄送: UPUPBSC ***@***.***>; Author ***@***.***>
主题: Re: [TP-Lab/tokens] Add UPUP logo and info (PR #10480)


Merged #10480<https://github.com/TP-Lab/tokens/pull/10480> into master.

―

**Pull request merged**
