### PR TITLE
Add FLOKI logo and info

### PR DESCRIPTION
**Pull request by 15228328910**
https://bscscan.com/tx/0xb0586d449744a3f7ea57287503ed19897a0000ada2cc19f7fea6e4483bd4fe46

### CODE REVIEW

**Comment by nenrgy** [comment]
专业提交logo,代币，白皮书，诚住经营，值得信赖，价格全网最优！QQ:2099728898
Professional submit logo, scrip, white paper, honestly live operation, reliable, the optimal price cut! QQ: 2099728898

**Comment by giki0318** [comment]
fake

**Comment by 15228328910** [comment]
It’s not fake . Floki upgrade contract. You can check it on Twitter and it’s official website

**Comment by 15228328910** [comment]
Please have a quick check. Since Floki is upgrading to dao. contract change and logo should upgrade too

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
