### PR TITLE
Add MOBOX logo and info

### PR DESCRIPTION
**Pull request by moboxcoin**
https://bscscan.com/tx/0x28049bf1c6f5ec7e18668f55fd8264716aad908d0eeeeca7dfe2d592e9bad20b?utm_source=tokenpocket

### CODE REVIEW

**Comment by giki0318** [comment]
fake

**Comment by moboxcoin** [comment]
What is fake？

**Comment by moboxcoin** [comment]
This is token

**Comment by moboxcoin** [comment]
This is an experimental token

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Pull request closed without merging**
