### PR TITLE
Add HT Club logo and info

### PR DESCRIPTION
**Pull request by MSLD109958**
转3000TPT记录
https://hecoinfo.com/tx/0x51136e14a185dc1be2b816b3b5171c3cedac9352b83413da2630206b414ae181

### CODE REVIEW

**Comment by MSLD109958** [comment]
最新12月16日才是

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:2980874528

**Comment by sammvio** [comment]
The official website cannot be opened, please resubmit.

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
