### PR TITLE
Add CYC logo and info

### PR DESCRIPTION
**Pull request by luke188**
币种：CYC
合约地址：0x73b7EcFaD3BD90834A79340328CC4d087db1F612
50000TPT的交易链接：https://bscscan.com/tx/0x6acc172216d5834df5b2ca397f5a380ec23330d2ceae2fdb963e0dc017e7d9ac
验证后的哈希值链接：https://bscscan.com/tx/0x6bb13e5f12bb8ea69810574c454faff238ccc462eb79fa76ce44d71830bb0958

### CODE REVIEW

**Comment by opera0001** [comment]
The token transaction rate is detected as modifiable, please explain its use.

**Comment by luke188** [comment]
Our transaction fee has a dividend mechanism, and the transaction rate can be modified, in order to make appropriate adjustments according to market changes, so that it can grow healthily and steadily

**Comment by luke188** [comment]
Please check it as soon as possible, thank you

**Comment by luke188** [comment]
> 代币交易率被检测为可修改，请说明其用途。
我们的交易手续费有分红机制，可以修改交易费率，以便根据市场变化进行适当的调整，使其健康稳定增长

**Comment by luke188** [comment]
> Our transaction fee has a dividend mechanism, and the transaction rate can be modified, in order to make appropriate adjustments according to market changes, so that it can grow healthily and steadily

Our transaction fee has a dividend mechanism, and the transaction rate can be modified, in order to make appropriate adjustments according to market changes, so that it can grow healthily and steadily

**Pull request merged**
