### PR TITLE
Add SML logo and info

### PR DESCRIPTION
**Pull request by SMLNFT**
https://bscscan.com/tx/0xba34e5c52fec1146567892474a7180f036dfde3f15d0dab9755582601d171317

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token

**Comment by dudebing99** [comment]
> Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token

Submited already, re-check please.

**Comment by dudebing99** [comment]
@zhujiayu03 Should I re-open the PR or submit a new PR?

**Comment by SMLNFT** [comment]
> Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token

Submitted already, re-check please. @zhujiayu03

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
