### PR TITLE
Add JXRY logo and info

### PR DESCRIPTION
**Pull request by laopowan**
https://bscscan.com/tx/0xf0a0d5e84d492c9379238f1c550234e49dc4e7f7be583d1863437569a06768cd?utm_source=tokenpocket

### CODE REVIEW

**Comment by opera0001** [comment]
If the working capital pool is not viewed, there may be risks in token offline transactions. Please re submit the logo application after adjustment or optimization. Thank you for your support for tokenpocket.

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by laopowan** [comment]
https://bscscan.com/tx/0xe11cb2b719f596ba5effa078db405aedd25bf7b21a2819a0885930f133dca9cf

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
