### PR TITLE
Add GNFT logo and info

### PR DESCRIPTION
**Pull request by GR-coin**
Add GNFT logo and info

### CODE REVIEW

**Comment by GR-coin** [comment]
https://bscscan.com/tx/0x23a35bf9d4612330af3bf3196d0dc919a6d1513a23819e4fad8e0ef949755790

**Comment by zhujiayu03** [comment]
Please refer to the tutorial, and use the contract address in the checksum format.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
