### PR TITLE
upload token info

### PR DESCRIPTION
**Pull request by WhaleFall-Official**
upload token info

### CODE REVIEW

**Comment by wuzhxyl** [comment]
upload token info for whalefall, pls

**Comment by Kendrickyu** [comment]
upload token info for whalefall, pls

**Comment by kimi-V587** [comment]
Why hasn't it been updated yet? ?

**Comment by Aicxz** [comment]
upload token info for whalefall, pls

**Comment by kevinleedev** [comment]
why the whale fall icon did not update?why?

**Comment by WhaleFall-Official** [comment]
Sir, 2 file in the commit, one of them is icon.

**Comment by WhaleFall-Official** [comment]
> upload token info for whalefall, pls

Sir, .json file in commit is token info of whalefall.

**Comment by xiazongfei** [comment]
we need update

**Comment by WhaleFall-Official** [comment]
> we need update

What kind of update do you need, any information missing ?

**Comment by WhaleFall-Official** [comment]
> we need update

Hi body, any response? Cause I really have no idea what the 'update' is all about, I have submit all the neccesary information according to zhe direction of 'https://tphelp.gitbook.io/cn/wallet-operation/submit-token'

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request merged**
