### PR TITLE
Add ZSKRAT and info

### PR DESCRIPTION
**Pull request by C-A-Y-D-E**
https://bscscan.com/tx/0xd1bf815c8bcbca6ef9195cdeed7845d8c80df0a4aac1b3b50679ab91b64bdfb6?utm_source=tokenpocket

### CODE REVIEW

**Comment by opera0001** [comment]
The contract would call functions of other contracts when primary methods are executed.It would cause this contract to be highly dependent on other contracts, which may be a potential risk.

Please explain the code for the calling section.

**Comment by opera0001** [comment]
I have not seen a reply or change after 2 days, so the order needs to be closed and I can be contacted via issues.
https://github.com/TP-Lab/tokens/issues

**Comment by inmefinance** [comment]
That is the antinsipe method

It no longer changes anything, just blocks the snipers it caught

**Comment by inmefinance** [comment]
That is the anti snipe method
It no longer changes anything, just blocks the snipers it caught

**Comment by inmefinance** [comment]
Hello can answer us please ?

**Comment by inmefinance** [comment]
you just upload it and didnt add our offical  data

**Pull request merged**
