### PR TITLE
Add Ancient Doges info

### PR DESCRIPTION
**Pull request by yihui487604**
Ancient Doges and Musk.

We first submit the information file only, and then submit the avatar after the later period is stable. Please TP official staff to review, thank you, it’s troublesome.

### CODE REVIEW

**Comment by yihui487604** [comment]
We first submit the information file only, and then submit the avatar after the later period is stable. Please TP official staff to review, thank you, it’s troublesome.

**Comment by guoxintongsam** [comment]
Please re-submit the TPT transfer link on [Commit changes].

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
