### PR TITLE
Add JGB logo and info

### PR DESCRIPTION
**Pull request by happytreasure-jump**

### CODE REVIEW

**Comment by happytreasure-jump** [comment]
https://bscscan.com/tx/0x85badfca5f5639cfd5f1eceea561fa57d31e1eecdf8e75ccc376997a54c6efb9

**Comment by opera0001** [comment]
It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

**Comment by happytreasure-jump** [comment]
> It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

In fact, our contracts were audited by Certik, see https://www.certik.com/projects/jump

**Comment by happytreasure-jump** [comment]
The token contract is disclosed already, check again, please. @opera0001

**Pull request merged**
