### PR TITLE
Add ETN logo and info

### PR DESCRIPTION
**Pull request by Election242**
TPT：https://bscscan.com/tx/0xaddf908960a8acbe347551770be8251e806182b2ea5af2892d32eee37e23f2f7

BNB：https://bscscan.com/tx/0x02aeb1ad43d6f7385b106cbcdb18ff380a4d2a794c7bc147f11a77e8b88e3793

### CODE REVIEW

**Comment by opera0001** [comment]
image

This seems to have a lot of features, but there may be risks involved without relinquishing control.

**Comment by Election242** [comment]
The built-in contract has these functional limitations. We will give up the permissions after the opening on August 16. You can monitor our behavior. We will not maliciously harm others.
We want to upload the logo in advance

**Comment by Election242** [comment]
> image
> 
> This seems to have a lot of features, but there may be risks involved without relinquishing control.

The built-in contract has these functional limitations. We will give up the permissions after the opening on August 16. You can monitor our behavior. We will not maliciously harm others.
We want to upload the logo in advance

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Pull request merged**
