### PR TITLE
Add MRD Logo and Info

### PR DESCRIPTION
**Pull request by MMNFT**

### CODE REVIEW

**Review by MMNFT — COMMENTED** [review]
Sorry, I forgot to change the URL, request to modify the URL, and change it to: https://metarealmdao.com/.
and also:
TPT:
https://bscscan.com/tx/0x4b364cc33436fde9e41cd5a88f833d13c34021b416bb27d1b7f39f77a1ec6920
BNB:
https://bscscan.com/tx/0xd784f3bdef3ac3e62efeeac85eddd5da02ff1e38755875eac38b8305008189bb

**Comment by MMNFT** [comment]
TPT：
https://bscscan.com/tx/0x4b364cc33436fde9e41cd5a88f833d13c34021b416bb27d1b7f39f77a1ec6920
BNB:
https://bscscan.com/tx/0xd784f3bdef3ac3e62efeeac85eddd5da02ff1e38755875eac38b8305008189bb

**Comment by MMNFT** [comment]
TPT：
https://bscscan.com/tx/0x4b364cc33436fde9e41cd5a88f833d13c34021b416bb27d1b7f39f77a1ec6920
BNB:
https://bscscan.com/tx/0xd784f3bdef3ac3e62efeeac85eddd5da02ff1e38755875eac38b8305008189bb

**Comment by MMNFT** [comment]
Here is our correct URL:
https://metarealmdao.com

**Comment by MMNFT** [comment]
No liquidity has been added yet. We are ready to add liquidity on July 15th

**Comment by opera0001** [comment]
I don't see the json file uploaded, please add it.

**Comment by MMNFT** [comment]
> 

ok ,i will

**Pull request closed without merging**
