### PR TITLE
upload bbc logo and info

### PR DESCRIPTION
**Pull request by amu2025**
https://bscscan.com/tx/0x999205f57619841cb80d5843ad13aa2f66b7917bc91348b8c6a9b14f72d7104a

### CODE REVIEW

**Comment by opera0001** [comment]
The token contract control permission, without being discarded, includes the function of increasing token issuance, which may pose significant risks.

**Comment by amu2025** [comment]
Then I'll create a new contract, and you'll merge

**Comment by amu2025** [comment]
There is something wrong with my contract, I have generated a new contract, you can merge

**Comment by amu2025** [comment]
In contrast, I still need to make some adjustments here. You don't need to help me publish for the time being. I will re-publish a new contract after the modification

**Comment by amu2025** [comment]
I have generated a new contract, you can merge

**Comment by amu2025** [comment]
My new address is: 0xD11379CD368f96b985B7cbe34C4b2Fd1102cFA33

**Comment by opera0001** [comment]
Detected hidden owner permissions in the token contract. Please verify.

**Comment by amu2025** [comment]
I generated a new contract,My new address is: 0x2Db87bB3D6D0d75Fb3FCec85e53BD00A533242F9.
I will retain the owner for the time being and give it up later.
you can merge

**Comment by amu2025** [comment]
I generated a new contract,My new address is: 0x57777D0BB827FD8408121842d550e52bC1a7c6bA.
I will retain the owner for the time being and give it up later.
you can merge

**Comment by opera0001** [comment]
The new address contract has hidden owner permissions in its permissions, which poses a significant risk and cannot be included.

**Comment by amu2025** [comment]
It's all right, manager, I still need to keep my side, you can help me merge

**Comment by amu2025** [comment]
It's all right, owner , I still need to keep my side, you can help me merge

**Comment by amu2025** [comment]
I'm done here. You can help me merge

**Comment by amu2025** [comment]
code security audit report ?Where do I need to get it

**Comment by amu2025** [comment]
Can code security audit report provide it later?

**Comment by amu2025** [comment]
Whether to give up the owner can be approved？

**Comment by opera0001** [comment]
The hidden owner permission does not become invalid even if the token management rights are abandoned. A security audit involves conducting a security review of the code, and it can only be included if the result is deemed secure. Due to the long duration of the order, it needs to be closed. You can continue to contact me through issues. The TPT hash value you submitted will not expire, and you can continue to use it in the next submission.

https://github.com/TP-Lab/tokens/issues

**Pull request closed without merging**
