### PR TITLE
add  logo and info

### PR DESCRIPTION
**Pull request by crypto000001**
https://bscscan.com/tx/0xa083b556cd64c8c6eaf7efa966edc27d27a238960983c2adb80479c07fa8193e

### CODE REVIEW

**Comment by opera0001** [comment]
image
Your submitted order cannot be merged. What is your request? Do you want to delete one logo and add a new one?

**Review by crypto000001 — COMMENTED** [review]
好的，非常好

**Comment by crypto000001** [comment]
该项目非常不错

**Comment by opera0001** [comment]
The logo for the contract address 0x427E5adcfe2f588CE60931BBE7D53a3773835a5A has been included. Please check.

**Pull request closed without merging**
