### PR TITLE
Add CAI logo and Info

### PR DESCRIPTION
**Pull request by crypto-ai-git**
50000TPT:
https://bscscan.com/tx/0xa5a0b1fb2c6905ce9b85a5a5e5a7cd27cceae961ca2aa7385101a958ab10cf70

BNB Data:
https://bscscan.com/tx/0xbd243612df6a6bd6b1ca08ff9f8d0442ea89126c048b9d6dde6d052674acd37c

### CODE REVIEW

**Comment by crypto-ai-git** [comment]
Solid Proof Audit for Token:
https://raw.githubusercontent.com/solidproof/projects/main/Crypto%20AI/SmartContract_Audit_Solidproof_CryptoAi.pdf

Contract Ownership Renounced:
https://bscscan.com/tx/0x1866e83c06622a276a5507b019a2d08e9d69c504c3a27cbc9a3ea60353659536

Unicrypt Locked:
https://app.uncx.network/amm/pancake-v2/pair/0xbbedd0f976c231e64d7d79abe8f6f0f0610d26b2



We got a 15s lock after buy to sell; its in the contract that purpose is to prevent bots to front run. Above links are all our safety done.

**Comment by opera0001** [comment]
image
The submitted file is not saved in the BSC directory, please adjust it again.

**Review by crypto-ai-git — COMMENTED** [review]
Repull into BSC folder

**Comment by crypto-ai-git** [comment]
I had just pull request again to the BSC folder, I drag the folder into BSC folder. 

May I check if there any more issues, thanks

**Pull request merged**
