### PR TITLE
Add VIKINGS logo and info

### PR DESCRIPTION
**Pull request by vikingsinu**
https://bscscan.com/tx/0x96974b2aa833bade36543f4d134a9f86a5e1a16a89654a97d00f4958cbd16915

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Please donate 3000 TPT as required and submit the transfer link on [Commit changes].

**Comment by vikingsinu** [comment]
0xf3857b7164432ac83090e6870604345d23f4ee89b08c9a7845648b194b17e6b6

**Comment by vikingsinu** [comment]
> Please donate 3000 TPT as required and submit the transfer link on [Commit changes].

https://bscscan.com/tx/0xf3857b7164432ac83090e6870604345d23f4ee89b08c9a7845648b194b17e6b6

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
