### PR TITLE
Add KK logo and info

### PR DESCRIPTION
**Pull request by 15896209474**
https://bscscan.com/tx/0x8e8424c16c860adb04aaa9bfc2fabc75b038bb7b2f26b6366a645bcd743b3164

### CODE REVIEW

**Comment by 15896209474** [comment]
Add YC logo and info

**Review by 15896209474 — COMMENTED** [review]
https://hecoinfo.com/tx/0x424c52c9e0fb55f7bb86e18a7ee00d962aad9eb80a91bfa5b8d19f9ad562620d

**Comment by 15896209474** [comment]
https://hecoinfo.com/tx/0x424c52c9e0fb55f7bb86e18a7ee00d962aad9eb80a91bfa5b8d19f9ad562620d

**Comment by zhujiayu03** [comment]
请参考教程，提交正确格式的文件。

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
