### PR TITLE
Add DBTC logo and info

### PR DESCRIPTION
**Pull request by wzp-life-github**
https://bscscan.com/tx/0xfb8013f8f0fc2c82d62e9af4e73b98a1dc1ee2b9091cf7f6c440bac3904957b8

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:2980874528

**Comment by sammvio** [comment]
Please submit the checksum address that includes uppercase and lowercase characters.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
