### PR TITLE
Add CNT logo and info

### PR DESCRIPTION
**Pull request by 2966535729**
0x5f1d8c143b2645c46b3e7d8f85d82437f5213e81ac07a2aaf216516efec87edd

### CODE REVIEW

**Comment by 2966535729** [comment]
Add CNT logo and info
0xF6f7C8683C60FBf108086ef363c85A415dc2C385 (TPT Trade links : 0x5f1d8c143b2645c46b3e7d8f85d82437f5213e81ac07a2aaf216516efec87edd)

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:2980874528

**Comment by sammvio** [comment]
Please re-submit these tokens separately and attach the TPT transfer links on [Commit changes].

**Comment by 2966535729** [comment]
要重新提交？已经付费了呀，也有付费链接



发自我的iPhone


------------------ Original ------------------
From: SS ***@***.***&gt;
Date: Mon,Jan 3,2022 10:37 PM
To: TP-Lab/tokens ***@***.***&gt;
Cc: 2966535729 ***@***.***&gt;, State change ***@***.***&gt;
Subject: Re: [TP-Lab/tokens] Add CNT logo and info (PR #4496)





 
Please re-submit these tokens separately and attach the TPT transfer links on [Commit changes].

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
