### PR TITLE
Create 0x6D6905D98088aDeca6D741B52Ce3730F591Be8cC

### PR DESCRIPTION
**Pull request by baohuitou**
Add TAOISM inf and logo

### CODE REVIEW

**Comment by opera0001** [comment]
Please submit the data and hash links carefully according to the contents of the tutorial.

CN：https://tphelp.gitbook.io/cn/wallet-operation/submit-token
EN：https://help.tokenpocket.pro/en/developer/how-to-submit-a-token-logo#steps-of-adding-a-token-logo-info

**Comment by Yasim76** [comment]
God bless all

**Comment by Yasim76** [comment]
The best all of you

**Comment by opera0001** [comment]
image

**Pull request closed without merging**
