### PR TITLE
Add TPT logo and info

### PR DESCRIPTION
**Pull request by cbitworlds**
This was updated before but maybe there was an issue.
I'm adding it again as instructed.
Thanks
https://bscscan.com/tx/0xe2231f99f3b1afe394957fbd5ae15d9404db007acb8996b663e72545d808ffd3

### CODE REVIEW

**Comment by opera0001** [comment]
1. The contract ownership is not abandoned, and there are certain potential safety hazards
2. There may be a control transaction switch

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
