### PR TITLE
Add BBDOGE Info and logo

### PR DESCRIPTION
**Pull request by annyphong99**
https://bscscan.com/tx/0x4868dc4f20de812b8f36d7ed7cb86f92ea9d0dd8cc5240399eedc70f6acef538

### CODE REVIEW

**Comment by annyphong99** [comment]
output-onlinepngtools (2)
Update logo

**Comment by zhujiayu03** [comment]
Please check your file name again.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
