### PR TITLE
Add bcc logo and info

### PR DESCRIPTION
**Pull request by bb1ssss**
BSC-BCC-0xb3260119514F2D9645dE050fb33874fB4D4d0Ae1-https://bscscan.com/tx/0x7a59f8247bc839ac8f10466976b639a350aa310a230cb0dfb3d0587499c9ebe5

### CODE REVIEW

**Comment by opera0001** [comment]
image

What does the submitted hash value have to do with the two previous orders?

**Comment by bb1ssss** [comment]
BSC-BCC-0xb3260119514F2D9645dE050fb33874fB4D4d0Ae1-https://bscscan.com/tx/0x7a59f8247bc839ac8f10466976b639a350aa310a230cb0dfb3d0587499c9ebe5

**Comment by opera0001** [comment]
image
The submitted file is not saved in the BSC directory, please adjust it again.

The submitted token logo is not 256x256 pixels, please modify it.

**Comment by opera0001** [comment]
I still haven't seen your reply after 2 days, so the order needs to be closed, you can contact me in issues.

https://github.com/TP-Lab/tokens/issues

**Pull request closed without merging**
