### PR TITLE
Add ATS logo and info

### PR DESCRIPTION
**Pull request by Apollo0717**
Atlantis origin is a meta universe game, which virtualizes the survival and development in the real world, and derives a lot of NFT content, in which users interact in the game and generate benefits.

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Please re-submit your files attached TPT transfer link on [Commit changes].

**Comment by Apollo0717** [comment]
你好：
我想知道什么原因需要重新提交呢？



***@***.***
 
From: zhujiayu03
Date: 2021-08-10 18:01
To: TP-Lab/tokens
CC: Apollo0717; Author
Subject: Re: [TP-Lab/tokens] Add ATS logo and info (#2204)
Please re-submit your files attached TPT transfer link on [Commit changes].
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Review by Apollo0717 — COMMENTED** [review]
https://bscscan.com/tx/0x0a99d15ef484cdba4182e39602fc6023e4d4ff52462054bb389d35c5ea262862
这是TPT转账信息

**Comment by Apollo0717** [comment]
你好：
TPT转账信息已经提交，麻烦合并一下，谢谢~

https://bscscan.com/tx/0x0a99d15ef484cdba4182e39602fc6023e4d4ff52462054bb389d35c5ea262862


***@***.***
 
From: zhujiayu03
Date: 2021-08-10 18:01
To: TP-Lab/tokens
CC: Apollo0717; Author
Subject: Re: [TP-Lab/tokens] Add ATS logo and info (#2204)
Please re-submit your files attached TPT transfer link on [Commit changes].
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Review by Apollo0717 — COMMENTED** [review]
https://bscscan.com/tx/0x0a99d15ef484cdba4182e39602fc6023e4d4ff52462054bb389d35c5ea262862
这是TPT转账信息

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Pull request closed without merging**
