### PR TITLE
Add GIM logo and info

### PR DESCRIPTION
**Pull request by genesisIslandMeat**
https://bscscan.com/tx/0x77b4949191db0cc2c898f5d16b52a3b733b367a72c4b8d04b82c6adec3f7234c

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3579750034

**Comment by sammvio** [comment]
The contract didn’t verify and publish. (No open-source)

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
