### PR TITLE
Add BTAI logo and info

### PR DESCRIPTION
**Pull request by akitvyi**
https://bscscan.com/tx/0x825464fa5f29e6e300970a06a4945884b3c3ba3672658b74c5b68c053360c150

### CODE REVIEW

**Review by akitvyi — COMMENTED** [review]
logo

**Comment by akitvyi** [comment]
这个可以不，还需要我再次提交吗

**Comment by 03164460654** [comment]
Yas

**Comment by opera0001** [comment]
No need, dear. I have already completed the task.

**Comment by akitvyi** [comment]
我现在还需要做什么

**Pull request merged**
