### PR TITLE
Add TiMi info and logo   (new)

### PR DESCRIPTION
**Pull request by KKKK1898**
https://bscscan.com/tx/0x8a70a50d4e55148abc61c169cac3419f61c4c24e411abcc990c815cc62b01640?utm_source=tokenpocket

### CODE REVIEW

**Comment by opera0001** [comment]
It is suggested to remove the display of domain names in tokens and to remove Chinese-language prompts.

**Comment by KKKK1898** [comment]
[info.json](https://github.com/TP-Lab/tokens/files/14909777/info.json)
logo
THANK YOU.

**Comment by KKKK1898** [comment]
I have sent a new LOGO, please check, add updates, or I need to initiate a new pull request, please let me know. Thank you so much!

**Comment by KKKK1898** [comment]
> 建议去掉token中域名的显示，并去掉中文提示。


I have sent a new LOGO, please check, add updates, or I need to initiate a new pull request, please let me know. Thank you so much!

**Pull request merged**
