### PR TITLE
add buy token

### PR DESCRIPTION
**Pull request by bunnywebdev**
https://bscscan.com/tx/0x5d69560d4accf16c6d352b88b7e0e16d5c98e43a44b3e296b89d7686f3c3ee27

### CODE REVIEW

**Comment by opera0001** [comment]
1. The logo is not 256x256 pixels, please change it
2、Detected that the transaction rate can be modified, please explain what it does
3、The existence of external contract call function is detected, please check and explain the situation.

**Comment by opera0001** [comment]
1、Detected that the transaction rate can be modified, please explain what it does
2、The existence of external contract call function is detected, please check and explain the situation.

**Comment by bunnywebdev** [comment]
The transaction rate is not finalized yet, the token owner will discard ownership once the rate is finalized and the external contract is finalized.

**Comment by bunnywebdev** [comment]
The external call contract process tax charged to transfer users only. I don't think there are any risks exposes to token holders.

**Pull request merged**
