### PR TITLE
Add UVT logo and info

### PR DESCRIPTION
**Pull request by cmwq**
https://bscscan.com/tx/0x0fcff1f31441250b51f4d23954577c98bb65b6bb1a634ffee4afb27a393158dc

### CODE REVIEW

**Comment by opera0001** [comment]
1、Discover the settings that can suspend trading
2、Detected settings that can modify the transaction rate.

Please explain what they do.

**Comment by cmwq** [comment]
> 1、Discover the settings that can suspend trading 2、Detected settings that can modify the transaction rate.
> 
> Please explain what they do.

1, (10% will be deducted for each transfer transaction, of which 5% will be used to return to the pool, 3% will be used for LP dividends, 1% will be used to distribute 75 users who hold the NFT address of the genesis node, and 1% will be used to distribute 225 holders. Alliance node NFT address user)
2,In the later stage, we will launch UvSwap, which will be routed from the pancakeswap routing contract to our UvSwap routing contract.

**Comment by cmwq** [comment]
Hi sir when is our token expected to passhello when is our token expected to pass

**Comment by cmwq** [comment]
Hi sir when is our token expected to pass

**Pull request merged**
