### PR TITLE
Add VENO logo and info

### PR DESCRIPTION
**Pull request by VENOOfficial**
https://bscscan.com/tx/0xf92ffe45e34df0b3f451a2eab125625b24f81e73fd7b28837524c2f9c365c238 https://bscscan.com/tx/0x898db687a9d694c8715e9f9e2ae08a8fa5e3f4a4fc939944280c694e07f27d7f

### CODE REVIEW

**Comment by VENOOfficial** [comment]
There is a tax adjustment switch, but only up to 25%.
Blacklist is used to counter snipers.

**Comment by VENOOfficial** [comment]
Contract under audit.

**Comment by VENOOfficial** [comment]
After launch, DEV will renounce ownership.

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Pull request merged**
