### PR TITLE
Add NBC logo and info

### PR DESCRIPTION
**Pull request by Hansenkatrine**
Hello dear reviewer, NBC's first submission for review was rejected for the reason: Nobel is a person's name and is not suitable for community distribution. Now that we have made changes, please review again, thank you for your hard work！

### CODE REVIEW

**Comment by opera0001** [comment]
Nobel is a famous person, and we don't think that a Noblecoin is suitable to be issued by meme community.

The hash value you submitted can be used for the next logo audit. Thank you very much for your understanding.

**Comment by Hansenkatrine** [comment]
Dear TokenPocket Good morning!
We had some issues, our token Nobelcoin (NBC) wanted to update the token logo, but after submitting it was rejected and the response we got was: "Nobel is a famous person, and we don't think that a Noblecoin is suitable to be issued by meme community." We have now made rectifications and affirmed that the NBC token is not issued by a certain community, I hope the TokenPocket reviewers will review it again, and I wish you a wonderful day!

The hash value you submitted can be used for the next logo audit. Thank you very much for your understanding

**Comment by Hansenkatrine** [comment]
> 诺贝尔是名人，我们认为诺贝尔币不适合由meme社区发行。
> 
> 您提交的哈希值可用于下次徽标审核。非常感谢您的理解。

Dear TokenPocket Good morning!
We had some issues, our token Nobelcoin (NBC) wanted to update the token logo, but after submitting it was rejected and the response we got was: "Nobel is a famous person, and we don't think that a Noblecoin is suitable to be issued by meme community." We have now made rectifications and affirmed that the NBC token is not issued by a certain community, I hope the TokenPocket reviewers will review it again, and I wish you a wonderful day!

The hash value you submitted can be used for the next logo audit. Thank you very much for your understanding

**Comment by Hansenkatrine** [comment]
> 诺贝尔是名人，我们认为诺贝尔币不适合由meme社区发行。
> 
> 您提交的哈希值可用于下次徽标审核。非常感谢您的理解。

Dear TokenPocket Good morning!
We had some issues, our token Nobelcoin (NBC) wanted to update the token logo, but after submitting it was rejected and the response we got was: "Nobel is a famous person, and we don't think that a Noblecoin is suitable to be issued by meme community." We have now made rectifications and affirmed that the NBC token is not issued by a certain community, I hope the TokenPocket reviewers will review it again, and I wish you a wonderful day!

**Comment by Hansenkatrine** [comment]
Logo

**Comment by Hansenkatrine** [comment]
We have rectified the NBC logo, please review it, and wish you a good day

**Pull request merged**
