### PR TITLE
Add FRET logo and info

### PR DESCRIPTION
**Pull request by freestarter**
https://hecoinfo.com/tx/0x3dc998f86459c379fa689217560de264a9d4ba0b759dc4be474f0322141d6838
Hi admin, the previous ticket #655 didn't update successfully, thank you!

### CODE REVIEW

**Comment by freestarter** [comment]
https://hecoinfo.com/tx/0xc10aa30a8a0b31039ec0a928f7ced2ab83e00f7589f12af63ac8ea5ddbaefef9
Hello, we see that we need to pay 1000TPT to update the logo, we have already added the payment, please merge the branch，thank you!

**Comment by zhujiayu03** [comment]
Since you've submitted 2 tokens with the same name, please confirm which token is correct and be noted that 1000 TPT is for one logo.

**Comment by freestarter** [comment]
Hi, 0x65D0c17fbd419cBa0eBeB80bf25f338C8456eF4F is correct, I made 2
payments, 100TPT before and 1000TPT afterwards, please confirm my pull
request.

zhujiayu03 ***@***.***> 于2021年7月19日周一 下午2:39写道：

**Comment by freestarter** [comment]
#1382


Simon Jinnck ***@***.***> 于2021年7月19日周一 下午7:27写道：

**Comment by freestarter** [comment]
Hello, we are cross-chain DeFi project, the contract address of Etherchain:
0xB18F12fA136B4CC52484cdf83c1128d056Ca97cF, has been successfully added,
the contract address of BSChain:
0x65D0c17fbd419cBa0eBeB80bf25f338C8456eF4F, please confirm my BSChain
request, I have made two payments in total, 1 for 100TPT and 1 for 1000TPT.
Payment link for 1000TPT:
https://hecoinfo.com/tx/0xc10aa30a8a0b31039ec0a928f7ced2ab83e00f7589f12af63ac8ea5ddbaefef9

Simon Jinnck ***@***.***> 于2021年7月19日周一 下午7:27写道：

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Pull request closed without merging**
