### PR TITLE
Add Acid logo and info

### PR DESCRIPTION
**Pull request by 0xnuu**
Dear tokenpocket team, request to add Acid's info and logo

### CODE REVIEW

**Comment by 0xnuu** [comment]
tpt send hash:https://bscscan.com/tx/0x7f23943411db4a729f85c4aa593d5af58aebdea688634cedc57bf6bd66535371

bnb send hash:https://bscscan.com/tx/0x9978ec0783e2f7ee7e46e4b6f5800f59551f76dc0862f0914a8e5b5bed18f5c7

**Comment by opera0001** [comment]
Detected the existence of a function to increase token issuance, please explain its purpose.

**Comment by opera0001** [comment]
After 3 days without seeing your reply or any changes, the order will need to be closed. Any adjustments or explanations can be sent to me through issues.

https://github.com/TP-Lab/tokens/issues

**Comment by 0xnuu** [comment]
> 检测到存在于增加代币发行量的能力，请说明其用途。

Hi, Acid tokens can be produced through the Vest mechanism and Bond mechanism
Here is the audit report
https://docs.0xacid.com/others/contracts/audit

**Pull request closed without merging**
