### PR TITLE
Add UFO logo and info

### PR DESCRIPTION
**Pull request by kkoo000**
https://bscscan.com/tx/0x5698897a65ca1b16f67d69aab86fb97b01bdd2cff595ca828bdfc31e7b62c2ff

### CODE REVIEW

**Comment by opera0001** [comment]
1、Please check the number of TPT donations.
2、The submitted logo is not 256x256 pixels, please modify it.

**Comment by kkoo000** [comment]
https://bscscan.com/tx/0xffe478266b9ff827abf7904958ca6f7f8c9a3c1917ff729f06553cb37d9dc48d

**Comment by kkoo000** [comment]
Add UFO logo and info

**Comment by kkoo000** [comment]
> 1、请查看TPT捐赠数量。 2、提交的logo不是256x256像素，请修改。

https://bscscan.com/tx/0xffe478266b9ff827abf7904958ca6f7f8c9a3c1917ff729f06553cb37d9dc48d

**Pull request merged**
