### PR TITLE
Add logo

### PR DESCRIPTION
**Pull request by OAM-TGR**
TPT https://bscscan.com/tx/0xceb84580c40d5bf6026a4b8f6a40f3619daa2f0ab60bad6a567ad0586f4c2612
BCS https://bscscan.com/tx/0x596a46d59a8a9230ff1179bcaf4504e50eeb70b8a9dcf72736c41c91d2f2ee3f

### CODE REVIEW

**Comment by opera0001** [comment]
1. There are no other operations after the token is issued, so it is impossible to detect whether the contract is safe
2. No fund flow pool found
Please re submit the logo after adjustment or optimization. Thank you for your support for tokenpocket.

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
