### PR TITLE
Add CA Token Logo And Info（ERC20）

### PR DESCRIPTION
**Pull request by MrLiu163**
50000 TPT: https://bscscan.com/tx/0x4b3106b102d68bc4e5e31fdb2560a828fad0dda68b7e67a11c24e698851bd132

### CODE REVIEW

**Comment by opera0001** [comment]
The control permissions of the token contract have not been abandoned, and there is a mechanism for adding and issuing tokens. This could pose a significant risk, so please provide clarification specifically regarding this functionality.

**Comment by MrLiu163** [comment]
Hi opera0001, we will abandon control permissions and stop token issuance within the next few weeks, which is already in progress.

**Comment by MrLiu163** [comment]
Chain Data：[https://etherscan.io/address/0xCc857F9A89C55DE54F3D56961DCd48231c1BDD67](url)

**Comment by MrLiu163** [comment]
Hi admin, we have stopped token issuing yesterday , please see this  [https://etherscan.io/tx/0x301d64966c0d8afa1b6dd009d16963131d5a460fb47a95c424360780ee261037](url)

**Comment by MrLiu163** [comment]
@opera0001  Hi admin, please take a look at this question. Why has the CA token information (such as the token name) displayed in the TP wallet not been updated to the content in the PR? The displayed information now looks the same as when it was not included.

**Pull request merged**
