### PR TITLE
Add SAT info and logo

### PR DESCRIPTION
**Pull request by SAEXIO**
https://bscscan.com/tx/0xe6478cf37f5b811ce826b019c66425677d06a27d920cffe2a3366a6f3c328597

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token

**Comment by SAEXIO** [comment]
sat-submit
submit repeated,please update logo and info

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
