### PR TITLE
Add SKY logo and info

### PR DESCRIPTION
**Pull request by coinbest91839012**
50,000 TPT transaction ID link: https://bscscan.com/tx/0xe9c5e45527eaacb25ec0706ce26fd21ce858dbb183e2bbbd7cf86a0ae84b6dff
verified TxHash: 0xe71cedd3afd69a5a141d953531b54281634ee94f46fd711451bbebee9f63c513

### CODE REVIEW

**Comment by coinbest91839012** [comment]
Hi, the contract permission is for adjusting the tax, the tax modification is hardcoded not to exceed 25% also,
need to reduce to 0% after the linear lock contract finished distributed the tokens to the user

**Comment by opera0001** [comment]
image

This logo is already in use by someone else. Please make adjustments or provide proof that this logo belongs to you.

**Comment by coinbest91839012** [comment]
Hi, How to prove the logo belong to me

**Comment by coinbest91839012** [comment]
i will try to make a minor adjustment on the token

**Comment by opera0001** [comment]
> i will try to make a minor adjustment on the logo

Okay, please adjust it and send it to me afterward.

**Comment by opera0001** [comment]
Dear,

This order has been pending for too long, so I need to close it. Once you have adjusted the logo, you can send it to me through the issues on https://github.com/TP-Lab/tokens/issues. I will help you update the logo once I see it.

Best regards.

**Pull request closed without merging**
