### PR TITLE
ADD HODL logo and info

### PR DESCRIPTION
**Pull request by lcpliu**
https://bscscan.com/tx/0x584db8af15f19024fce285fd2557a24108ef4668424503302bf055d6ec1e6f42 https://bscscan.com/tx/0xfb7c1a756060de8026e44f5f8e8033a879712e99b0c55ffb9f733ecd31629078

### CODE REVIEW

**Comment by opera0001** [comment]
The presence of proxy contracts has been detected, posing significant risks. Token logos cannot be included unless you can provide a code audit report from a reputable security company.

**Comment by lcpliu** [comment]
> The presence of proxy contracts has been detected, posing significant risks. Token logos cannot be included unless you can provide a code audit report from a reputable security company.

Permission has been discarded

**Comment by lcpliu** [comment]
Permission has been discarded

**Comment by opera0001** [comment]
Sorry dear, even after discarding control permissions, hidden permissions still exist and pose significant risks.

**Comment by lcpliu** [comment]
I changed the contract and logo

**Comment by opera0001** [comment]
The newly provided contract still faces issues with proxy authorization. Therefore, there is still no solution to address it.

**Comment by lcpliu** [comment]
We have passed the AVE contract security audit and the contract permissions have been given up.
40508661e22fd35cf9377c428c4c82e
99c4f2c0edea7257a2a21f3d64d7a9b

**Comment by lcpliu** [comment]
> The newly provided contract still faces issues with proxy authorization. Therefore, there is still no solution to address it.

We have passed the AVE contract security audit and the contract permissions have been given up.

**Comment by DEXXX001** [comment]
After giving up the contract permissions, you will not have any operation permissions. The contract has been verified and open source. Please help us review and update it as soon as possible.
https://bscscan.com/token/0x1671a2ab49928523c138dd85c1b9d242f28a35a4#code

**Comment by opera0001** [comment]
AVE also uses detection services based on GO PLUS, but AVE selectively hides some detection results. However, since AVE has already been included and the token is currently circulating normally, it can be listed. I will closely monitor your token, and if any issues arise, I will promptly revoke the logo and categorize it as a risky token.

**Pull request merged**
