### PR TITLE
Upload TPL token

### PR DESCRIPTION
**Pull request by mxkfz**
Upload TPL token

### CODE REVIEW

**Comment by mxkfz** [comment]
https://bscscan.com/tx/0xc4b6ccbd21f53ab459dd2539dafa4d935711440365a749482cbae5d6b794a340

**Comment by guoxintongsam** [comment]
Please re-submit your files attached TPT transfer link on [Commit changes].

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
