### PR TITLE
add LOVE logo and info

### PR DESCRIPTION
**Pull request by WangWeiwei2013**
https://bscscan.com/tx/0x71eb36ea360eade28b90fb1879b733a617ef6adeaa75aa4dd813dfeaacd030ff

### CODE REVIEW

**Comment by opera0001** [comment]
1. It is found that there may be a function that can retrieve administrator permissions
2. The sliding point rate can be modified, which has potential safety hazards
Please re submit the logo application after adjustment or optimization. Thank you for your support for tokenpocket

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
