### PR TITLE
Add  Tcoin logo  and  info

### PR DESCRIPTION
**Pull request by Aptx44511214**
https://bscscan.com/tx/0x6bd47a728b886cc84c7afaa6b150c506358a381f8b15507d8636904081415f4a

### CODE REVIEW

**Comment by opera0001** [comment]
A proxy contract is detected, which can be risky.

**Comment by Aptx44511214** [comment]
> 检测到代理合同，这可能是有风险的。

What should I do.

**Comment by Aptx44511214** [comment]
> 检测到代理合同，这可能是有风险的。
I have communicated with my tech. Because the pool has not been added yet. So there is no lock. It will be locked when we finish adding the pool.

**Comment by Aptx44511214** [comment]
> 检测到代理合同，这可能是有风险的。

We have locked the pool, please pass the review as soon as possible. thanks

**Comment by opera0001** [comment]
I'm very sorry, the proxy contract is not possible to see the actual settings through the detection software, so it is not possible to define the risk.

**Comment by Aptx44511214** [comment]
> I'm very sorry, the proxy contract is not possible to see the actual settings through the detection software, so it is not possible to define the risk.

Please tell me what should I do. Because what I see here is normal and safe.

**Comment by Aptx44511214** [comment]
> I'm very sorry, the proxy contract is not possible to see the actual settings through the detection software, so it is not possible to define the risk.

Hope you can tell me. How can I communicate with my technician. let him know what to do

**Comment by opera0001** [comment]
Sorry, I don't know how to deal with this, such tokens issued using a proxy contract may not be able to be fundamentally changed, maybe only a reissue will do.

**Comment by Aptx44511214** [comment]
> 对不起，我不知道怎么处理，这种使用代理合约发行的代币可能无法从根本上改变，也许只能重新发行。

To confirm with you again, is there something wrong with the tokens under the contract address of my "0xc8dfa3379a00C00CF033CE566AD13b93f9ACB636"?

**Pull request closed without merging**
