### PR TITLE
update website info

### PR DESCRIPTION
**Pull request by kassidyliberty**

### CODE REVIEW

**Comment by kassidyliberty** [comment]
0x42bf81354e30a2120f8fff632e85bfeee8dfd18c5df4f4902f7fb5547208e456
https://bscscan.com/tx/0x42bf81354e30a2120f8fff632e85bfeee8dfd18c5df4f4902f7fb5547208e456

**Comment by zhujiayu03** [comment]
Please submit your logo in the correct size.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
