### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by 94xv**
Add logo and info
https://bscscan.com/tx/0xe13244002735cb333290a8dc3c8aed52085df87726f2080bda313ba9eab48cee

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Please refer to the tutorial, and re-submit your files in the correct format.

**Comment by 94xv** [comment]
你好 哪里的格式不正确了 我重新提交下谢谢

**Comment by 94xv** [comment]
Hello, where is the format incorrect? I will submit it again. Thank you

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Pull request closed without merging**
