### PR TITLE
0x0d3A0F635734d3b9e74418568bE85d7d01388E72

### PR DESCRIPTION
**Pull request by hbk886**
https://hecoinfo.com/tx/0x9d3693f99353fe48d4d7b58a0899f51ee2ec485b2c4f5dfde90e6ddd719e2677

### CODE REVIEW

**Comment by tubiaoyingji** [comment]
专业加快提交LOGO，20分钟内审核包过，QQ：1450001284

**Comment by sammvio** [comment]
Please re-submit these tokens separately and attach the TPT transfer link on [Commit changes].

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
