### PR TITLE
Add TP logo and info

### PR DESCRIPTION
**Pull request by tpswap1**
https://bscscan.com/tx/0xe8ed60d0dc0336fdc67878b7f035ea1587b8b6a231adcf0eee087db8be587966

### CODE REVIEW

**Comment by opera0001** [comment]
1. A setting that suspends token trading is detected, please explain what it does
2、The submitted logo is highly similar to TokenPocket's official logo, please change it.
3、Tokens are temporarily untradeable, what is the plan for follow-up?

**Comment by tpswap1** [comment]
1、暂停交易只是关闭买入功能可以正常卖出，用户只通过挖矿产出的方式获得代币。
2、徽标可以更改，徽标中间换成只有一个T你看符合标准吗？
3、用户通过挖矿产出的方式获取代币，用户数量达到再开通自由买入功能。



---Original---
From: ***@***.***&gt;
Date: Sun, Oct 16, 2022 14:43 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] Add TP logo and info (PR #8406)




  
A setting that suspends token trading is detected, please explain what it does
 2、The submitted logo is highly similar to TokenPocket's official logo, please change it.
 3、Tokens are temporarily untradeable, what is the plan for follow-up?

**Comment by tpswap1** [comment]
I have replaced the logo, please check

**Comment by tpswap1** [comment]
我们已经修改了代币图标，并且回答了官方的问答。想知道代币图标什么时候可以审核？

---Original---
From: ***@***.***&gt;
Date: Sun, Oct 16, 2022 14:43 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] Add TP logo and info (PR #8406)




  
A setting that suspends token trading is detected, please explain what it does
 2、The submitted logo is highly similar to TokenPocket's official logo, please change it.
 3、Tokens are temporarily untradeable, what is the plan for follow-up?

**Pull request merged**
