### PR TITLE
0xE4f1AE07760b985D1A94c6e5FB1589afAf44918c

### PR DESCRIPTION
**Pull request by yue666666**
https://bscscan.com/tx/0x441a393caa805e335b736cf26a52c7149953bc9da4d5918b782cdc886b6ab100

### CODE REVIEW

**Comment by opera0001** [comment]
It is detected that the token has a cooling transaction function. Please explain what this function is?

**Comment by yue666666** [comment]
> 检测到令牌具有冷却事务功能。请解释一下这个函数是什么？
现在区块时间已经大于冷却事务时间，合约代码中的时间已经无法更改，权限已经丢弃了.(function setStart(uint _TIME)public{
        require(msg.sender == setEXAddress);
        if(block.timestamp < startTransaction){
        startTransaction=_TIME;
        }
    }

require(block.timestamp > startTransaction || amount <= code || _isExcludedFromFee[sender],"swap It hasn't started yet");+

**Comment by yue666666** [comment]
> It is detected that the token has a cooling transaction function. Please explain what this function is?

The time in the contract code cannot be changed anymore, and the permissions have been discarded.

require(block.timestamp > startTransaction || amount <= code || _isExcludedFromFee[sender],"swap It hasn't started yet");+

function setStart(uint _TIME)public{
        require(msg.sender == setEXAddress);
        if(block.timestamp < startTransaction){
        startTransaction=_TIME;
        }
    }

**Comment by yue666666** [comment]
Excuse me, I can update the logo after you handle it, right?

opera0001 ***@***.***> 于2022年6月13日周一 23:48写道：

**Comment by yue666666** [comment]
The time in the contract code cannot be changed anymore, and the
permissions have been discarded.

require(block.timestamp > startTransaction || amount <= code ||
_isExcludedFromFee[sender],"swap It hasn't started yet");+

function setStart(uint _TIME)public{
require(msg.sender == setEXAddress);
if(block.timestamp < startTransaction){
startTransaction=_TIME;
}
}

opera0001 ***@***.***> 于2022年6月12日周日 23:43写道：

**Pull request merged**
