### PR TITLE
ADD StarlinkDAO LOGO and info

### PR DESCRIPTION
**Pull request by czmhxt**
https://bscscan.com/tx/0x35aba6e180f6aa9a2154be1aee984aa444f46c80c896c7e86043296ef430ed39

### CODE REVIEW

**Comment by opera0001** [comment]
1. Liquidity pool not created
2. There is no other operation after the issuance of tokens, so it is impossible to determine whether there is a risk in the flow mode
Please re submit the logo application after adjustment or optimization. Thank you for your support for tokenpocket

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
