### PR TITLE
Add CDT logo And info

### PR DESCRIPTION
**Pull request by jguyet**
BSC - TPT - 0x0cbd6fadcf8096cc9a43d90b45f65826102e3ece - https://bscscan.com/tx/0xa6226515bcaf02307c1868c2bc8cc159f5b687d8be7081941234d089100c08dd

### CODE REVIEW

**Comment by tubiaoyingji** [comment]
专业加快提交LOGO，20分钟内审核包过，QQ：1450001284

**Comment by sammvio** [comment]
Please submit the checksum address that includes uppercase and lowercase characters.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
