### PR TITLE
ADD SEADOG logo and info

### PR DESCRIPTION
**Pull request by QQyuri**
ADD SEADOG logo and info

Address: 0x4647a7a0bc932c666e51b3ce03ad5b792fbd4f5a

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Please donate 3000 TPT as required and submit the transfer link on [Commit changes].

**Comment by QQyuri** [comment]
> Please donate 3000 TPT as required and submit the transfer link on [Commit chan
IMAGE 2021-11-12 12:33:00
ges].

https://bscscan.com/tx/0x52995bf18fe3b09e223cba1178050fba3faa9421c419d77c872388a30389c162?utm_source=tokenpocket

**Comment by QQyuri** [comment]
last time submit the request, already transfer the 3000 TPT

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by QQyuri** [comment]
nice spam


jiasutijiao ***@***.***> 於 2022年1月3日 週一 下午2:48寫道：

**Pull request closed without merging**
