### PR TITLE
Add OKSHIB Logo & Info

### PR DESCRIPTION
**Pull request by okshiboec**
TPT - https://bscscan.com/tx/0xfe4b7a89df1f1a1976f1769df64d44cff3dff00b7fdce87badb85066cb9066c6
Verify - https://bscscan.com/tx/0x4a52677b3ef5b75763d1807f5d03dc105d8c8f33787fc113f4e4122633921428

### CODE REVIEW

**Comment by opera0001** [comment]
The logo is suspected of infringement, please modify it.

**Comment by opera0001** [comment]
The logo is suspected of infringement, please modify it.

**Comment by okshiboec** [comment]
logo png

Here is a new resubmission of our LOGO. Please have a look and we didn't have the intention in infringement. Thanks!

**Comment by okshiboec** [comment]
@opera0001

**Pull request merged**
