### PR TITLE
Add USDM logo and info

### PR DESCRIPTION
**Pull request by m9n0106**
Add USDM logo and info

### CODE REVIEW

**Comment by opera0001** [comment]
1.The submitted logo is not 256x256 pixels, please resubmit
2.Detected that the contract includes settings for increased token issuance 
3. Please provide the TPT donation hash value.

**Comment by m9n0106** [comment]
> 1.The submitted logo is not 256x256 pixels, please resubmit 2.Detected that the contract includes settings for increased token issuance 3. Please provide the TPT donation hash value.

I have resubmitted the logo in the correct 256x256 pixel size and provided the TPT donation hash value. Regarding the second point, the increased token issuance function is included because the token is designed to serve as a stable token. This function allows for controlled and necessary issuance to maintain the stability and purpose of the token within its ecosystem.

**Comment by opera0001** [comment]
Please provide the TPT donation hash value.

**Comment by m9n0106** [comment]
> Please provide the TPT donation hash value.

1. 100,000 TPT transaction ID link
https://bscscan.com/tx/0x03d75b4527351859d3111a16d89792f65f3fb2bed9a6dbc87b36caf8b5b78729

2. TxHash in step4
0xfd2b462cdb39784a1dd1cbeb0fc75c082a070eb7f886d42c183a51d451057b90

**Pull request merged**
