### PR TITLE
Add FATHER logo and info

### PR DESCRIPTION
**Pull request by dogefa**
https://bscscan.com/tx/0x4acd64242f7e253d46a171b0c837e0c67c171ef087c6eb4fb50952295e96db7e

### CODE REVIEW

**Comment by opera0001** [comment]
Abnormal token transaction status

**Comment by dogefa** [comment]
Hi TP-Lab,

What is

Abnormal token transaction status?

Thanks

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
