### PR TITLE
ADD Moore logo and  info

### PR DESCRIPTION
**Pull request by MOORESWAP**
https://hecoinfo.com/tx/0x3d404ba4478457d81cdee1bedb21cc6a8afa8c21dcd420f967039ec8eefd723d?utm_source=tokenpocket

### CODE REVIEW

**Comment by MOORESWAP** [comment]
add Moore logo and  info
https://bscscan.com/tx/0x1cdba84ee6b64e251eb83271d8e05d4830c61cfe1401872bd0e656f1354dbec8

**Comment by MOORESWAP** [comment]
add Moore logo and info
https://bscscan.com/tx/0x1cdba84ee6b64e251eb83271d8e05d4830c61cfe1401872bd0e656f1354dbec8

**Comment by zhujiayu03** [comment]
Added

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Pull request closed without merging**
