### PR TITLE
Add SFIS logo add info

### PR DESCRIPTION
**Pull request by stars1618**
https://bscscan.com/tx/0x4094d37cfdcec056f0a72d1422752955c370e911f2af57ecb63e65f9afe84324?utm_source=tokenpocket

### CODE REVIEW

**Comment by nenrgy** [comment]
专业提交logo,代币，白皮书，诚住经营，值得信赖，价格全网最优！QQ:2099728898
Professional submit logo, scrip, white paper, honestly live operation, reliable, the optimal price cut! QQ: 2099728898

**Comment by stars1618** [comment]
这是审核失败吗？





发自我的iPhone


------------------ Original ------------------
From: SS ***@***.***&gt;
Date: Sun,Feb 6,2022 1:52 PM
To: TP-Lab/tokens ***@***.***&gt;
Cc: stars1618 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [TP-Lab/tokens] Add SFIS logo add info (PR #5206)





 
Closed #5206.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
