### PR TITLE
add DT logo

### PR DESCRIPTION
**Pull request by Hanggi**
BSC - DT - 0x07652BC724A8aE4331c94F0871648202e5E68AD3 - https://bscscan.com/tx/0xb858de323c90a60dfa58f66153ad653b3a5ce9355f2c5c7c5b05291ef90adfad

### CODE REVIEW

**Comment by Hanggi** [comment]
> why using proxy? and also the ownership of the token

Thank you for your reply.

Proxy is quite popular these days, for example GALA: https://bscscan.com/token/0x7ddee176f665cd201f93eede625770e2fd911990#readContract

The reason why we are using proxy is that we are not only a token project.
We are making a Dapp system which will add many features work around token.

We will deploy several contracts interact with the token, so we have to keep the ownership to tuning the params.
Of course after deploy all the system contracts we will drop the ownership to make it decentralizable.

Please check again.
Thank you.
@giki0318

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
