### PR TITLE
Add CBA info and logo

### PR DESCRIPTION
**Pull request by lcwypn**
https://bscscan.com/tx/0x781ea5b0746c49c0ee24fe530dfb035bc351f6e7dc5b63b3a80949b8fdcf83eb https://bscscan.com/tx/0xf2975c7d72a2661da7a9e8c9d7dc139d3cecfc65a0936b86716109f2af7b0ffa

### CODE REVIEW

**Comment by opera0001** [comment]
It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

**Comment by lcwypn** [comment]
the token contract code have  disclosed

**Comment by lcwypn** [comment]
Open sourced

**Comment by opera0001** [comment]
1、Detect the existence of the token increase issue function, please explain its role
2、Detected an abnormal token transaction (unable to sell)

**Comment by lcwypn** [comment]
1. Someone cross-chain is not an additional issue, so it leads to the growth of tokens.
2. Those who reach the preset ecological contribution can be traded, and the normal market tokens can be traded normally

**Pull request merged**
