### PR TITLE
Add VFT logo

### PR DESCRIPTION
**Pull request by civa**

### CODE REVIEW

**Comment by civa** [comment]
https://bscscan.com/tx/0x23018ff523d40f7cf5bc51ed4cc85eafd6ce4f08d6be0f594aa284001c06a455

**Comment by sammvio** [comment]
Please re-submit your files to bsc folder

**Comment by exchains** [comment]
to civa
Please go online and arrange a refund

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
