### PR TITLE
Update TRIAS Price

### PR DESCRIPTION
**Pull request by crypto-xiaobai**
Reverts TP-Lab/tokens#10840

Dear TP Wallet, hello!
I have seen that our new TRIAS has updated the token logo, thank you, but there is still a problem. Our new TRIAS does not display the token price.

We have updated the TRIAS token contract address on CMC and Coingecko
https://coinmarketcap.com/currencies/trias-token/
https://www.coingecko.com/en/coins/trias-token

The following exchanges have also completed the TRIAS token contract replacement
Gate.io Supports Trias (TRIAS) Token Migration
https://www.gate.io/announcements/article/37766
MEXC Will Support the Trias (TRIAS) Contract Swap
https://www.mexc.com/support/articles/17827791517201
Bitget Will Support the Trias (TRIAS) Contract Swap
(https://github.com/user-attachments/assets/04cd9615-6519-44f9-b5c9-25204625eb54)

https://www.bitget.com/support/articles/12560603812558
Please help, the new TRIAS price is displayed in the TP wallet
New TRIAS contract address: [0x184cff0e719826b966025f93e05d8c8b0a79b3f9](https://bscscan.com/token/0x184cff0e719826b966025f93e05d8c8b0a79b3f9)

iwEcAqNqcGcDAQTRBNoF0QqABrC0kpcYl616SQaWDb06Y4YAB9ILKq70CAAJomltCgAL0gACkzg jpg_720x720q90

### CODE REVIEW

**Comment by opera0001** [comment]
image

I think the low liquidity of the token is causing the price not to display. Perhaps you can try increasing its liquidity to around $40,000.

**Comment by crypto-xiaobai** [comment]
How can tokens display prices in TP wallets? What conditions need to be met? Can you provide a description document so that we can operate according to the requirements to ensure that the price can be displayed?

**Comment by crypto-xiaobai** [comment]
iwEcAqNqcGcDAQTRAlAF0QUABrDJRJIkx-NcBAaY4OA_e-8AB9ILKq70CAAJomltCgAL0gABkho jpg_720x720q90
iwEcAqNqcGcDAQTRAlAF0QUABrBBhbVQo9ZP_QaY4N-uQ5kAB9ILKq70CAAJomltCgAL0gABcfQ jpg_720x720q90

This is our ecological project token GROW, the liquidity is only 8000 US dollars, but the price is displayed, so is there a way to confirm it? We modified it according to the requirements to ensure that the TRIAS price can be displayed. In addition, CMC and Coingecko have already displayed the TRIAS price. Can we get the latest TRIAS price on these information websites or CEX?

**Comment by opera0001** [comment]
Please send me the contract address for GROW to check. Thank you.

**Comment by crypto-xiaobai** [comment]
New TRIAS Donation Record
https://bscscan.com/tx/0x234e882a7e332f23c55ab907eb32ec8964806e645dfe3c9dd80c0c8082299b83
GROW Donation Record
https://bscscan.com/tx/0xbfb06f9a67da50dc55a01be3a71050dd5078159a86fc7f19a5d0b0f1128b16cc

New TRIAS contract address
[0x184cff0e719826b966025f93e05d8c8b0a79b3f9](https://bscscan.com/token/0x184cff0e719826b966025f93e05d8c8b0a79b3f9)
GROW contract address
[0x0C9aD20802E89BeA858ae2E8594843fAfA887CB3](https://bscscan.com/token/0x0C9aD20802E89BeA858ae2E8594843fAfA887CB3)

Please help to find out why the new TRIAS cannot display the price. It would be better to have a clear document so that our project party can know what to do or what information to submit to display the new TRIAS price.

**Comment by opera0001** [comment]
> New TRIAS Donation Record https://bscscan.com/tx/0x234e882a7e332f23c55ab907eb32ec8964806e645dfe3c9dd80c0c8082299b83 GROW Donation Record https://bscscan.com/tx/0xbfb06f9a67da50dc55a01be3a71050dd5078159a86fc7f19a5d0b0f1128b16cc
> 
> New TRIAS contract address [0x184cff0e719826b966025f93e05d8c8b0a79b3f9](https://bscscan.com/token/0x184cff0e719826b966025f93e05d8c8b0a79b3f9) GROW contract address [0x0C9aD20802E89BeA858ae2E8594843fAfA887CB3](https://bscscan.com/token/0x0C9aD20802E89BeA858ae2E8594843fAfA887CB3)
> 
> Please help to find out why the new TRIAS cannot display the price. It would be better to have a clear document so that our project party can know what to do or what information to submit to display the new TRIAS price.

This situation does indeed exist, and I have already reported it to the technical team for review. The normal standards are the ones I mentioned earlier; you can refer to the historical tokens listed on GitHub, as they all comply with these regulations. However, that particular case might have encountered some bugs.

**Comment by opera0001** [comment]
GROW contract address
[0x0C9aD20802E89BeA858ae2E8594843fAfA887CB3

This token is ranked within the top 3500 on the CMC platform, so its price and other related data will be automatically synced.

**Comment by opera0001** [comment]
Hey, dear, this order has been pending for too long, so I need to merge it. If there are any further issues, feel free to contact me through issues at any time.

https://github.com/TP-Lab/tokens/issues

**Comment by crypto-xiaobai** [comment]
7CB568B3-0B62-44E3-97DD-46CDB0E04534

59E313E4-D48F-415F-9AB4-C034C5C1E810


TRIAS on CMC：https://coinmarketcap.com/currencies/trias-token/

Hello, dear TP Wallet, our TRIAS ranks higher on CMC. Many of our users use TP Wallet, so it is very important to display our TRIAS price in TP Wallet. Please ask the TP technical team to check the specific reason. Thank you

**Pull request merged**
