### PR TITLE
Add Logan logo and info

### PR DESCRIPTION
**Pull request by LoganNetwork**
https://bscscan.com/tx/0x472371155bfb4203a60ddb72ca7072b053b823c4faa6e44a75d3b78baf135d87

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:2980874528

**Comment by sammvio** [comment]
Please donate 3000 TPT as required and submit the transfer link on [Commit changes].

**Comment by sammvio** [comment]
Please submit the checksum address that includes uppercase and lowercase characters.

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
