### PR TITLE
Add CGC logo and info

### PR DESCRIPTION
**Pull request by netlocks**
tpt:https://bscscan.com/tx/0x63a7524a275c22c53aa7bc4c5e8e9cec6cdce2f0c93251fa0f44b66846a3f36a

bnb:https://bscscan.com/tx/0xbc4d16e110f9b0d4e204aa48798e89f53275fa7a9bb1f33d2be3012ee5def05a

### CODE REVIEW

**Comment by opera0001** [comment]
Token transaction is abnormal, and the selling rate is 100%

**Comment by jjjgjk** [comment]
1212在吗

**Comment by netlocks** [comment]
no exception

**Comment by jjjgjk** [comment]
1212在吗

**Comment by jjjgjk** [comment]
1212在吗

**Comment by jjjgjk** [comment]
你好

**Comment by tplogotijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
