### PR TITLE
Add REEL logo and info

### PR DESCRIPTION
**Pull request by REEL927**
https://bscscan.com/tx/0xe7a1e2a5adc515183c094d13dea141fe1c34c3ecc5fbad0d68d4e54cf0447026

### CODE REVIEW

**Comment by opera0001** [comment]
image
1.The submitted file is not saved in the BSC directory, please adjust it again.
2.Please check if the content is correct; this appears to be a request to replace the token logo.

**Comment by REEL927** [comment]
Hello, this is not the replacement token Logo, but the Logo of our new
token contract address. Can I send it to you directly? Because I am not
near the computer now, I am in other cities, but the boss is asking me, I
want to finish my work well, I hope you can understand me, thank you very
much.


{
 "name": "Matrix",
 "website": "https://matrixpro.org",
 "description": "$Reel is the GoLive ecosystem token, and GoLive has
created an innovative short video platform. The $Reel token not only
incentivizes content creators but also ensures transparent and instant
distribution of earnings. Blockchain protects content copyright and user
data privacy, promoting fairness and transparency on the platform.",
"explorer":"
https://bscscan.com/token/0x9F21C84F0fD93462955f2Bb07C308647DD09e35E",
 "type": "BEP20",
 "symbol": "Reel",
 "decimals": 18,
 "status": "active",
 "id":
"0x9F21C84F0fD93462955f2Bb07C308647DD09e35E"
}

https://bscscan.com/tx/0xe7a1e2a5adc515183c094d13dea141fe1c34c3ecc5fbad0d68d4e54cf0447026

This is the payment hash.





opera0001 ***@***.***>于2024年10月1日 周二10:08写道：

**Comment by REEL927** [comment]
Hello, I resubmitted again, please help me to include it as soon as
possible, thank you very much, Good luck with your work.
opera0001 ***@***.***>于2024年10月1日 周二10:08写道：

**Comment by opera0001** [comment]
Sorry, you need to readjust and submit again. I can wait for you for one to two days. Please submit according to the required content.

**Pull request merged**
