### PR TITLE
add PKT info and logo

### PR DESCRIPTION
**Pull request by pokemonnft**
https://bscscan.com/tx/0x3d78786254e69cc2eb2f78d6627462ae464c79ec4faddc431b9ee3706d0af475

### CODE REVIEW

**Comment by pokemonnft** [comment]
tron info : https://bscscan.com/tx/0xc0227e112fd9474cb6063b109e5c778fa82a7f7f0a592d1db63740494932d033

**Comment by pokemonnft** [comment]
eth : https://bscscan.com/tx/0x070f4b91e5a5ce9cc343866ad84b989462a241b0c7e57363d43ad59dbd8a26a6

**Comment by zhujiayu03** [comment]
1. Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token
2. logo infringement

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
