### PR TITLE
ADD kingdoge logo and info

### PR DESCRIPTION
**Pull request by linglingluoluo925**
https://bscscan.com/tx/0xe391f921a1a98a45ddc8eac89e184560d743942e0e57eaf11a0c2af7b9097a31

### CODE REVIEW

**Comment by sammvio** [comment]
Please re-submit your files to bsc folder

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
