### PR TITLE
Add Gourdman logo and info

### PR DESCRIPTION
**Pull request by 15896209474**
Add Gourdman logo and info

### CODE REVIEW

**Comment by 15896209474** [comment]
Add PET logo and info

**Review by 15896209474 — COMMENTED** [review]
Add FET logo and info

**Comment by 15896209474** [comment]
Add FET logo and info

**Comment by zhujiayu03** [comment]
Please attach TPT transfer links

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Pull request closed without merging**
