### PR TITLE
Add FoolsShib logo and info

### PR DESCRIPTION
**Pull request by FoolsShib**
https://bscscan.com/tx/0x887f1cccecd7567068e4f0c9e2005c211bdddb5f559056b6efc16a18763b3a60

### CODE REVIEW

**Comment by lichenguang123** [comment]
111

**Comment by lichenguang123** [comment]
{ 
"name": "FoolsShib",
"website": "http://www.shiblnucash.com/",
"description": "FoolsShib is a community-driven and reflection token on Binance Smart Chain.",
"explorer": "https://bscscan.com/token/0x4b2B558bB6B02cfF564d904bD25749b9Dd999633",
"type": "BEP20",
"symbol": "FoolsShib",
"decimals": 9,
"status": "active",
"id": "0x4b2B558bB6B02cfF564d904bD25749b9Dd999633"
}

**Comment by tplogotijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
