### PR TITLE
Add WHALE logo and info

### PR DESCRIPTION
**Pull request by 15896209474**
Add WHALE logo and info

### CODE REVIEW

**Comment by 15896209474** [comment]
Add BCOP logo and info

**Comment by 15896209474** [comment]
Add babygoose logo and info

**Comment by 15896209474** [comment]
Add OPCH logo and info

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request merged**
