### PR TITLE
Add ART logo and info

### PR DESCRIPTION
**Pull request by bbjs123**
name: ART Chain,
Total amount: 3000
website: https://www.artchainnft.com/,
description: ART is a Chain based on BEP (BSC) network hair completely decentralized community autonomy tokens, pre-sales tokens chips by dispersed in each user's hands, scrip model intelligent written into the contract without zhuang and large manipulation can't tamper with the decision, is a 100% circulation in the market to build the value of tokens by community consensus.
explorer: https://bscscan.com/token/0xe97364f13Fc8f40B0ab372a51b645a648f091483,
type: BEP20,
symbol: ART,
decimals: 18,
status: active,
id: 0xe97364f13Fc8f40B0ab372a51b645a648f091483,
1000 TPT trading ID link:https://bscscan.com/tx/0x35366b8aa8de619cdefe5ee32a0852f320fa75c64401feb8059c72423aaf09e1

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Please refer to the tutorial and use the checksum contract address as the file name.

**Comment by bbjs123** [comment]
OK



在 2021-07-31 14:11:10，"zhujiayu03" ***@***.***> 写道：

Closed #1795.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by daibilogo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
