### PR TITLE
Add IDOGE LOGO And Info

### PR DESCRIPTION
**Pull request by LEN-5**

### CODE REVIEW

**Comment by LEN-5** [comment]
Sample

**Comment by zhujiayu03** [comment]
Please re-submit your files attached TPT transfer link on [Commit changes].

**Review by LEN-5 — COMMENTED** [review]
LOGO

**Comment by LEN-5** [comment]
TPT transfer link : 0xaa5e0b4d92881da1211fee473b3593567b3f8205de478bb6bf5ef65954d77ba7

**Review by LEN-5 — COMMENTED** [review]
TPT transfer link ：0xaa5e0b4d92881da1211fee473b3593567b3f8205de478bb6bf5ef65954d77ba7

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
