### PR TITLE
Add BULLA logo and info

### PR DESCRIPTION
**Pull request by helloMrlin**
https://bscscan.com/tx/0x0f6b1a68c741b9275b300058cbb0372cddc56c85a95b9f21a5d20954772f3aa7
https://bscscan.com/tx/0x0a6625267018af7e46af810b214f80dbf19ab64528ea78824d87c9103603ac75

### CODE REVIEW

**Comment by opera0001** [comment]
1. No capital flow pool is found, the circulation mode of token transaction is unclear, and it is impossible to define whether it is safe or not.
2. Official website address submission error.
Please re submit the logo after adjustment or optimization. Thank you for your support for tokenpocket.

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
