### PR TITLE
Add WDEO logo and info

### PR DESCRIPTION
**Pull request by QuickRol**
https://bscscan.com/tx/0x0e043b352ec26bc377ed91ee603e3fe83ff2b5b9e4ff0149a96efce6cbb469ef

### CODE REVIEW

**Comment by opera0001** [comment]
The submitted logo is not suitable, please replace it with a new one

**Comment by QuickRol** [comment]
A new logo has been submitted, if the new logo is not suitable, please update the old logo

**Comment by QuickRol** [comment]
> 提交的logo不合适，请更换新的


A new logo has been submitted, if the new logo is not suitable, please update the old logo

**Comment by opera0001** [comment]
Where did you submit it to, please?

**Comment by QuickRol** [comment]
> Where did you submit it to, please?

Submitted according to the steps, submitted twice in total, before you leave a message, so I don't know which illegal logo you are talking about

**Comment by QuickRol** [comment]
https://github.com/TP-Lab/tokens/pull/7913/commits/4f1a2e9a5336e12609284bdb4b50aa685c89dc4e

**Comment by QuickRol** [comment]
https://github.com/TP-Lab/tokens/pull/7913/commits/4f1a2e9a5336e12609284bdb4b50aa685c89dc4e
https://github.com/TP-Lab/tokens/pull/7913/commits/4f18915517081d6cfb1c4e8286c8a2b082e26ffa
https://github.com/TP-Lab/tokens/pull/7913/commits/c6865fa93798d97591d70afd8b4f7d5379d38eb8

**Comment by QuickRol** [comment]
> [4f1a2e9 ](https://github.com/TP-Lab/tokens/commit/4f1a2e9a5336e12609284bdb4b50aa685c89dc4e) [4f18915 ](https://github.com/TP-Lab/tokens/commit/4f18915517081d6cfb1c4e8286c8a2b082e26ffa) [c6865fa](https://github.com/TP-Lab/tokens/commit/c6865fa93798d97591d70afd8b4f7d5379d38eb8)

There are a total of 2 logos in it, which one is not illegal, please update which one, thank you

**Pull request merged**
