### PR TITLE
Add MTA logo and info

### PR DESCRIPTION
**Pull request by NinoShima**
Add MTA logo and info

### CODE REVIEW

**Comment by tiaojiaotubiaobaoguo** [comment]
代提交logo，24小时内包过，加QQ：2980874528

**Comment by NinoShima** [comment]
Add JUB logo and info

**Comment by NinoShima** [comment]
Add JUB logo and info

**Comment by sammvio** [comment]
Please donate 3000 TPT as required and submit the transfer link on [Commit changes].

**Comment by NinoShima** [comment]
> Please donate 3000 TPT as required and submit the transfer link on [Commit changes].

I already donate 3000 TPT, pls check: 
https://bscscan.com/tx/0xdff9ceb4c3974913d176549b7e532d2c5fa259ba71ce089168b477176862a7e6

https://bscscan.com/tx/0x0dd6aaf86cb7e906c3d82115a01c5178990bed9ad528824795ae08b2f0e75ad0

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
