### PR TITLE
Add GMK logo and info

### PR DESCRIPTION
**Pull request by YJ88888888**
https://bscscan.com/tx/0xb87ca99b72bb55d63d608133e00fe2e131e1aea3bce82b15f9628a312311e8c8

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Please re-submit your files to bsc folder

**Comment by YJ88888888** [comment]
3902# The information has been re-uploaded, please review, thank you!

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
