### PR TITLE
Add DogeBTC logo and info

### PR DESCRIPTION
**Pull request by Ruthtt**

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Please re-submit your files attached TPT transfer link on [Commit changes].

**Comment by Ruthtt** [comment]
Dear Zhujiayu,

Please I did the transfer and submission the third time!
Help to check it, it takes too long!

Best
DogeBTC
________________________________
发件人: zhujiayu03 ***@***.***>
发送时间: 2021年7月27日 9:14
收件人: TP-Lab/tokens ***@***.***>
抄送: Ruthtt ***@***.***>; Author ***@***.***>
主题: Re: [TP-Lab/tokens] Add DogeBTC logo and info (#1678)


Closed #1678<https://github.com/TP-Lab/tokens/pull/1678>.

―

**Comment by Ruthtt** [comment]
Dear Zhujiayu,

And the new case No is 1842

Thanks!

DogeBTC
________________________________
发件人: zhong jiasheng ***@***.***>
发送时间: 2021年7月27日 9:33
收件人: TP-Lab/tokens ***@***.***>
主题: 回复: [TP-Lab/tokens] Add DogeBTC logo and info (#1678)

Dear Zhujiayu,

Please I did the transfer and submission the third time!
Help to check it, it takes too long!

Best
DogeBTC
________________________________
发件人: zhujiayu03 ***@***.***>
发送时间: 2021年7月27日 9:14
收件人: TP-Lab/tokens ***@***.***>
抄送: Ruthtt ***@***.***>; Author ***@***.***>
主题: Re: [TP-Lab/tokens] Add DogeBTC logo and info (#1678)


Closed #1678<https://github.com/TP-Lab/tokens/pull/1678>.

―

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
