### PR TITLE
Add CPB logo and info

### PR DESCRIPTION
**Pull request by netlocks**
https://bscscan.com/tx/0x0f6f914c0ed1c7a7cbd8c9a8dfd4195c151403937de17de104ac5966fa8377a3

### CODE REVIEW

**Comment by opera0001** [comment]
1. There are switch functions that may not be sold
2. It has the function of obtaining all permissions
3. The submitted web address cannot be opened

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
