### PR TITLE
Add YFSX logo and info

### PR DESCRIPTION
**Pull request by yfsx1998**
https://bscscan.com/tx/0xc2be0d153b3f2d1d0eaf917f69218ff95d2be99b886649af499cd5d2ef63e116

### CODE REVIEW

**Comment by opera0001** [comment]
image

**Comment by yfsx1998** [comment]
现在是审核好了吗，可以按照图上面的修正一下，也可以直接审核这个

**Comment by opera0001** [comment]
Don't worry, I finished the preliminary examination yesterday and will finish the collection today.

**Comment by yfsx1998** [comment]
下午可以看到头像展示吗？

**Pull request merged**
