### PR TITLE
Add SpaceDoge logo and info

### PR DESCRIPTION
**Pull request by 264026152**
30000TPT hash：https://bscscan.com/tx/0x4ba277d10040cd2122806aeb36b6e647ec504635a62c0123efb14da4244471a9
info hash: https://bscscan.com/tx/0x0c762cbfe56007a72929c1c22990239b401d1e25c37913004ac8059d99abe00c

### CODE REVIEW

**Comment by 264026152** [comment]
D66C5EF5D45E4C3824D8EA3016FC1417

**Comment by 264026152** [comment]
This is the copyright certificate

**Comment by spacedoge9999** [comment]
30000TPT hash：https://bscscan.com/tx/0x196afe1718f2c0b2987b37164ce1d82558b6b844034a127fa1e71fca04217ce5

**Comment by spacedoge9999** [comment]
info hash: https://bscscan.com/tx/0x070e0e7b2ee7a5d7fb4f50bc97a98d495de9ca042d7fafa988393c0200980688

**Pull request closed without merging**
