### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by andyi762**

### CODE REVIEW

**Comment by opera0001** [comment]
Submitting the token logo application now requires 30000 TPT donation fees. After submitting the corresponding hash value link, the logo can be included after review. Please supplement the hash value link of the donated TPT in time.

**Comment by tplogotijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by tplogotijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by andyi762** [comment]
https://bscscan.com/tx/0x2ddd14c93b2a7f9d9fc7066da502bbe66a7ec8974098602e055a3dbb14099983
opera0001 ***@***.***>于2022年3月5日 周六17:18写道：

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
