### PR TITLE
Add MF logo and info

### PR DESCRIPTION
**Pull request by okcoin1**
smaple

### CODE REVIEW

**Comment by okcoin1** [comment]
https://bscscan.com/tx/0x6b2c68edc5affedf9aeaaeadec33f2a6e3ebaf10bf574c959c721c093a047857

**Comment by okcoin1** [comment]
这个是BNB的转账记录：https://bscscan.com/tx/0xf46130c0be4746539958f5e15d9acfbbe2709d32ef1ef8487b6c6c5eab76e552

**Comment by okcoin1** [comment]
logo

**Comment by okcoin1** [comment]
我需要更换成这个新的LOGO 之前提交错了文件。

**Comment by okcoin1** [comment]
How long will it take to pass the audit?

**Comment by opera0001** [comment]
image
The submitted file is not saved in the BSC directory, please adjust it again.

**Comment by okcoin1** [comment]
I have uploaded the file again, please check it, thank you!

**Comment by okcoin1** [comment]
I have uploaded the file again, please check it, thank you!

**Comment by okcoin1** [comment]
I'm very sorry that I'm not very proficient in the operation. I hope I can pass the audit quickly. Very support TP

**Comment by okcoin1** [comment]
image

**Comment by okcoin1** [comment]
image
I checked it carefully. It's the correct directory

**Comment by okcoin1** [comment]
Is the administrator there?

**Comment by okcoin1** [comment]
> 图片 提交的文件没有保存在BSC目录下，请重新调整。

are you there?

**Pull request merged**
