### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by good0777**
0x70311119aa2d29610c2c4421aac3d71425ecad15ad66bb6d8155287e2fbe04a7

### CODE REVIEW

**Comment by opera0001** [comment]
image
1、File storage location is not correct, please check the tutorial and submit to the correct BSC file directory.
2、Detected the existence of tokens to increase the settings of the issue 
3、Detected that the token transaction rate can be modified, please explain the reason.

**Comment by good0777** [comment]
1.Do I need to reorder the two files? In the directory of the bsc chain, you only need to pay attention to the folder name and the naming of the two files, and the others are not explained. What adjustments do we need
2.Our tokens are minted by users in the game for free, with a maximum minting amount of 10 million and an initial issuance of 20,000, which will enter the pancake flow pool.
3.In the early stage, the volume is small. In order to avoid the instability of the currency price caused by a large number of purchases by pranksters, we have increased a relatively high fee rate, which will be reduced later with the stability of the casting volume and real players.

**Comment by good0777** [comment]
Do I need to resubmit if necessary? or send you the information.

**Comment by good0777** [comment]
logo头像偏小了，能否修改

**Comment by good0777** [comment]
0x023F2af9807057f5E6Ef03742fF40418E54f907f:logo

**Pull request merged**
