### PR TITLE
Add VINU logo and info

### PR DESCRIPTION
**Pull request by ElemontCapital**
Add VINU logo and info

### CODE REVIEW

**Comment by opera0001** [comment]
The TPT hash value link is not seen, please check and submit. thank you.

**Comment by ElemontCapital** [comment]
> The TPT hash value link is not seen, please check and submit. thank you.

Please explain details & I will send

**Comment by ElemontCapital** [comment]
> The TPT hash value link is not seen, please check and submit. thank you.

VINU
TPT: https://bscscan.com/tx/0x1ca1f939945d0b7d3195ef42968ef8d339c8d093a581a06e872cfa27c1117890
BNB: https://bscscan.com/tx/0x9a74669d745a161a97133008c4efd7854a608375569951bc363c93cf2b57e0c7

**Comment by opera0001** [comment]
Logo is not 256x256 pixels, please adjust.

**Comment by ElemontCapital** [comment]
> Logo is not 256x256 pixels, please adjust.

Adjusted. Please try again.

**Pull request merged**
