### PR TITLE
Add DOTMoon logo and info

### PR DESCRIPTION
**Pull request by op896898466**
https://hecoinfo.com/tx/0xf948ef701a0171773d4b80f558ff8c1ada5b34b7af8553cd3db0a15300b09837

### CODE REVIEW

**Comment by op896898466** [comment]
https://hecoinfo.com/tx/0xf948ef701a0171773d4b80f558ff8c1ada5b34b7af8553cd3db0a15300b09837

**Comment by zhujiayu03** [comment]
logo infringement, please resend your image

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
