### PR TITLE
add SEVEN TOKEN 0xb0Ee373c22bAcA1a343e6Ac8eF075215D792ba6C

### PR DESCRIPTION
**Pull request by 7metadao**
{
 "name": "SEVEN TOKEN",
 "website": "https://sevenmeta.co/#/",
 "description": "SEVEN TOKEN is the only one token that used in SEVEN META platform.And it is inspired by Digital Finance Chain - DFC token listed in Lbank, Defi game,Multi chain wallet - 7 Meta.",
 "explorer": "https://bscscan.com/token/0xb0Ee373c22bAcA1a343e6Ac8eF075215D792ba6C",
 "type": "BEP20",
 "symbol": "SEVEN",
 "decimals": 18,
 "status": "active",
 "id": "0xb0Ee373c22bAcA1a343e6Ac8eF075215D792ba6C"
}

### CODE REVIEW

**Comment by opera0001** [comment]
1、TPT hash value link not submitted

2、It is detected that the function of token issuance can be added. Please explain the situation.

**Comment by 7metadao** [comment]
The token cannot be Added ,for the total supply of token is limited to 1
billion ,
As for TPT, I will submit it as soon as possible

**Comment by 7metadao** [comment]
1000TPT, please check it 

https://bscscan.com/tx/0xdc0fa46d05454ed06c470061f47c3649758fa4e41d066487f54ce56588fb1282

**Comment by opera0001** [comment]
Please check the number of TPTS and review the tutorial carefully.

CN：https://tphelp.gitbook.io/cn/wallet-operation/submit-token
EN：https://help.tokenpocket.pro/en/developer/how-to-submit-a-token-logo#steps-of-adding-a-token-logo-info

**Comment by 7metadao** [comment]
Ok, I will check.

**Pull request closed without merging**
