### PR TITLE
Add BRCP logo and info

### PR DESCRIPTION
**Pull request by timiboxprotonmail**
https://bscscan.com/tx/0xe49eb56595504d40c049c43845ad06fbe011aa52931c50f2bb3c5f15b3ec1da7
https://bscscan.com/tx/0xd55d36de2d40b13cfb00da45403c690dc673b17e9cf85dc8441397067b222355

### CODE REVIEW

**Comment by opera0001** [comment]
1.The submitted file is not saved in the ETH directory, please adjust it again.

2.The provided logo is not 256x256 pixels. Please make the necessary adjustments.

3.Detected that the token contract includes the functionality of increasing token supply, which may pose risks.

**Comment by timiboxprotonmail** [comment]
I have resubmitted the file to the eth directory

**Comment by opera0001** [comment]
Dear, the token contract contains a function to increase token issuance, which may pose security risks, so I need you to explain its purpose.

**Comment by timiboxprotonmail** [comment]
We have an exchange’s repurchase and destruction mechanism based on profits.

In order to ensure market liquidity, a certain amount of additional issuance is carried out every year with the consent of the holders and through DAO voting to ensure that the overall total amount remains deflationary.
We will be very cautious and issue less than 1% of the total amount every year to increase the rewards for important community contributors.

通过 [Proton Mail](https://proton.me/) 安全邮箱发送。

2024年4月13日 星期六 下午 9:22，opera0001 ***@***.***> 来信：

**Pull request merged**
