### PR TITLE
Add F1 logo and info

### PR DESCRIPTION
**Pull request by zzy9**
https://bscscan.com/tx/0xaab2c98ddf47a0d00911b51aa75cf25af890b6eea48a7ecf9c805118ce8433e8

### CODE REVIEW

**Comment by opera0001** [comment]
1. Without online swap, there will be some risks if offline trading is used
2. Low currency address and transaction volume
3. The management of the telegraph community on the official website was chaotic and did not operate normally
Please re submit the logo application after adjustment. Thank you for your support for tokenpocket.

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
