### PR TITLE
Add PRE logo and info

### PR DESCRIPTION
**Pull request by q573927428**
转账：https://bscscan.com/tx/0xb5ac387d6315405156032e1a483cc4925c1e650926edea1ddec5c76821f6ccf5
验证：https://bscscan.com/tx/0x08e997d5c92e4647ba695892265d677f490fc0ad0386cfcdb9b840ea55c76b6c

### CODE REVIEW

**Comment by opera0001** [comment]
1, detected the existence of hidden owner permissions, this risk is very high
2、Detected the existence of tokens to increase the setting of the issue
3、Detected the setting that can suspend token trading

**Comment by q573927428** [comment]
> 1, detected the existence of hidden owner permissions, this risk is very high 2、Detected the existence of tokens to increase the setting of the issue 3、Detected the setting that can suspend token trading

Can I give up the owner's permission?

**Comment by opera0001** [comment]
This you can decide according to the actual situation of your project.

What is the problem with the existence of a hidden owner?

**Comment by opera0001** [comment]
I don't see a reply or change after 2 days, so the order needs to be closed, you can contact me through issues, thanks.

Link: https://github.com/TP-Lab/tokens/issues

**Pull request closed without merging**
