### PR TITLE
Add BuffedShiba logo and info

### PR DESCRIPTION
**Pull request by goldenyee**

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Please donate 3000 TPT as required and submit the transfer link on [Commit changes].

**Comment by goldenyee** [comment]
https://bscscan.com/tx/0x2c2de3a77b19ceb92c6552152dae5f4e53a93f6d6f485cfd46ad0cb4783db16d

**Comment by goldenyee** [comment]
> Please donate 3000 TPT as required and submit the transfer link on [Commit changes].

https://bscscan.com/tx/0x2c2de3a77b19ceb92c6552152dae5f4e53a93f6d6f485cfd46ad0cb4783db16d

**Comment by goldenyee** [comment]
https://bscscan.com/tx/0xabce968f5eff4a8076cae93fd6f9b0422b7a71ddc495a0ee3f5932a4124db5c2

**Comment by goldenyee** [comment]
> Please donate 3000 TPT as required and submit the transfer link on [Commit changes].

https://bscscan.com/tx/0xabce968f5eff4a8076cae93fd6f9b0422b7a71ddc495a0ee3f5932a4124db5c2

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
