### PR TITLE
MVC logo submitted

### PR DESCRIPTION
**Pull request by mvcfinance**
https://bscscan.com/tx/0x3603bf9bd67b2e6b2ecc21a7da6828f6faaecbad717e56894a5bccd6398a2b39
https://bscscan.com/tx/0x4e46e6d998107653b21bdd4f1e99f21a2b18594716aa228e94ecaf3df6d35585

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:2980874528

**Comment by mvcfinance** [comment]
Yes, we want to apply 加速审核2小时内包过, please advise

**Comment by sammvio** [comment]
Please refer to the tutorial, and re-submit your files in the correct format.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
