### PR TITLE
Add SEADOG logo and info

### PR DESCRIPTION
**Pull request by QQyuri**
My Address
0x4647a7a0bc932c666e51b3ce03ad5b792fbd4f5a

Hash ID
0x52995bf18fe3b09e223cba1178050fba3faa9421c419d77c872388a30389c162

View the link
https://bscscan.com/tx/0x52995bf18fe3b09e223cba1178050fba3faa9421c419d77c872388a30389c162

### CODE REVIEW

**Comment by tiaojiaotubiaobaoguo** [comment]
代提交logo，24小时内包过，加QQ：2980874528

**Comment by sammvio** [comment]
Please refer to the tutorial, and re-submit your files in the correct format.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
