### PR TITLE
Add TPT logo and info

### PR DESCRIPTION
**Pull request by ZhengyuanChain**
sample

### CODE REVIEW

**Comment by opera0001** [comment]
Please check the content of the submitted json, you cannot directly copy the data from the tutorial and use it, you need to replace it according to the parameters of your own tokens, please readjust it.

**Comment by ZhengyuanChain** [comment]
是在下面截图的未知，填写info.json内容还是重新提交info.json文件啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TP-Lab/tokens"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月26日(星期五) 下午4:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TP-Lab/tokens] Add TPT logo and info (PR #8092)





 
Please check the content of the submitted json, you cannot directly copy the data from the tutorial and use it, you need to replace it according to the parameters of your own tokens, please readjust it.

**Comment by ZhengyuanChain** [comment]
{
 "name": "TokenPocket Token",
 "website": "https://tokenpocket.pro",
 "description": "A leading multi-chain wallet that supports BTC, ETH, BSC, HECO, TRON, EOS, OKExChain, HSC and so on.",
 "explorer": "https://bscscan.com/token/0x8b4D4e4fB663725E19087d384B1C8C1a10cDe9f7",
 "type": "BEP20",
 "symbol": "TPT",
 "decimals": 4,
 "status": "active",
 "id": "0x8b4D4e4fB663725E19087d384B1C8C1a10cDe9f7"
}

**Comment by ZhengyuanChain** [comment]
尊敬的客服：您好！
按照要求重新提交了，请加快审核以下！
谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TP-Lab/tokens"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月26日(星期五) 下午4:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TP-Lab/tokens] Add TPT logo and info (PR #8092)





 
Please check the content of the submitted json, you cannot directly copy the data from the tutorial and use it, you need to replace it according to the parameters of your own tokens, please readjust it.

**Pull request closed without merging**
