### PR TITLE
add atna logo and info

### PR DESCRIPTION
**Pull request by mangoDefi**
The Athena Token as the gamefi play-to-earn token

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3579750034

**Comment by sammvio** [comment]
Please donate 3000 TPT as required and submit the transfer link on [Commit changes].

**Comment by mangoDefi** [comment]
transfer link
https://bscscan.com/tx/0xbeb96bcd59251fabde960406881f9d8b3c8888e3c75499d29afc9cfa48c29448

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
