### PR TITLE
Add TIME logo and info

### PR DESCRIPTION
**Pull request by dange888**
https://hecoinfo.com/tx/0x2a48d82157438dda3b34acba0cc44801e9d56031f0adb29e9f12237a6c44f36a

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3579750034

**Comment by sammvio** [comment]
The official website cannot be opened, please resubmit.

**Comment by dange888** [comment]
It has been modified and re-uploaded, please review as soon as possible.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
