### PR TITLE
add card info and logo

### PR DESCRIPTION
**Pull request by logozhuanyong**
https://bscscan.com/tx/0xa99a11cc0e585e94ce19329f060e36db430e3e11d4680ddfcb8a869a97141d86

> Please submit your logo in the correct size. (png.)

好的，我删了，再重复提交下，谢谢！

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token

**Comment by logozhuanyong** [comment]
> Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token
我已经提交过了，并且这个网站还提示成功，之后我才在github提交的， 结果现在你这里又说我没有提交

**Comment by guoxintongsam** [comment]
Please submit your logo in the correct size. (png.)

**Comment by oko-token** [comment]
> Please submit your logo in the correct size. (png.)

Please pay attention to the merge. The display has been merged, but the logo has not been updated after the merge.. Please help me see what‘s the problem
https://github.com/TP-Lab/tokens/pull/2844

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
