### PR TITLE
ADD bhic logo and info

### PR DESCRIPTION
**Pull request by xwd1314191**
100000tpt电网线路负载：
https://bscscan.com/tx/0x0ba5c2edce0d9807534f2db7338adf6195fe904cc9f433dc6535ce7d0ca69dbb
确认带宽：https://bscscan.com/tx/0x9ffed7e81fb5590b143d84c896476c75caa600e6b5cdfd9e3676a3cf3ee12eb6

### CODE REVIEW

**Comment by opera0001** [comment]
image
There seems to be some issues with the data submission, please check again.

**Comment by xwd1314191** [comment]
不是已经重复提交新的啦

**Comment by xwd1314191** [comment]
已经重新上传了请审核

**Comment by opera0001** [comment]
Dear, it seems that there is no change in the results, please check.

**Comment by opera0001** [comment]
The submitted data still has some issues; you can send the token contract address and token logo here.

**Comment by xwd1314191** [comment]
logo

**Comment by xwd1314191** [comment]
BHIC代币合约地址：0xda9e5030d90Cf1b94a38Ea7399CeddEF0F5f2f57

**Comment by xwd1314191** [comment]
是这样发吗？

**Comment by xwd1314191** [comment]
> 提交的数据还存在一些问题；您可以在此处发送代币合约地址和代币徽标。

BHIC代币合约地址：0xda9e5030d90Cf1b94a38Ea7399CeddEF0F5f2f57
logo

**Comment by xwd1314191** [comment]
[info.json](https://github.com/user-attachments/files/17348533/info.json)
logo

**Comment by xwd1314191** [comment]
[info.json](https://github.com/user-attachments/files/17348537/info.json)
logo

**Comment by xwd1314191** [comment]
[info.json](https://github.com/user-attachments/files/17348546/info.json)

**Pull request closed without merging**
