### PR TITLE
Add BOSS001 logo and info

### PR DESCRIPTION
**Pull request by hashboss001**
https://bscscan.com/tx/0x438d71c1f356b64f84deea7add7fe5edbd6ecb90751b079d5dca421b880efc2c

### CODE REVIEW

**Comment by hashboss001** [comment]
boss001 is only used for statistical invitation function, not for sale or circulation, used to bind the relationship between superiors and subordinates.

**Comment by hashboss001** [comment]
https://www.bscscan.com/token/0x5fc8a70594dd020af0009a6295e37ee51c1cfe68#code 
It is used for the binding of supervisor-subordinate relationship on the platform, and does not have financial attributes. Donating 50000TPT to apply for adding ICONS is entirely for the purpose of better looking ICONS when users bind supervisor-subordinate relationship

**Comment by hashboss001** [comment]
It is used for the binding of supervisor-subordinate relationship on the platform, and does not have financial attributes. Donating 50000TPT to apply for adding ICONS is entirely for the purpose of better looking ICONS when users bind supervisor-subordinate relationship.

**Comment by opera0001** [comment]
It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

**Comment by opera0001** [comment]
I don't see your message or change after 2 days, so the order needs to be closed, you can contact me via issues.

https://github.com/TP-Lab/tokens/issues

**Pull request closed without merging**
