### PR TITLE
Add SFIS logo and info

### PR DESCRIPTION
**Pull request by stars1618**
https://bscscan.com/tx/0x4094d37cfdcec056f0a72d1422752955c370e911f2af57ecb63e65f9afe84324

### CODE REVIEW

**Comment by giki0318** [comment]
#1. your website cannot be accessed.
#2. you have logo infringement

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
