### PR TITLE
Add NTG logo and info

### PR DESCRIPTION
**Pull request by str45468**
BSC-NTG-0xB6B5Ce3c3bfaD1bE1043Ad5167a6697ecc28c4cC-https://bscscan.com/tx/0xa2757c8876320fa4d50ea6423dfedf9c612b91b4737098d428a15361ca53749c

### CODE REVIEW

**Comment by opera0001** [comment]
1. tpt donate hash value link invalid
2.It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

**Comment by str45468** [comment]
tpt donate:
https://cn.etherscan.com/tx/0xa2757c8876320fa4d50ea6423dfedf9c612b91b4737098d428a15361ca53749c

**Comment by str45468** [comment]
Contract code has been opened

**Comment by str45468** [comment]
BNB Verify address:
https://bscscan.com/tx/0x2f86ca98b89efde98500cd2dec55d950ae9c167e0b9302d46241506a5024d789

**Pull request merged**
