### PR TITLE
Add OPPA Token and info

### PR DESCRIPTION
**Pull request by oppaghost**
Please add the logo for OPPA token. 

The donation has been made, as you can see from the link below. 

https://bscscan.com/tx/0x71859b57ae3b11801b5f46041c57778d2acd23936f1a0887133dc4516943e1be

### CODE REVIEW

**Comment by logobaoguo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by oppaghost** [comment]
@logobaoguo 

I am sorry but I think I will need a little more details that that. I tried to translate your message in English and my take was that there is a price display problem. Am I correct? if so, how do we fix that? 

I believe that the JSON file we submitted are accurate and correct, and there isn't a property there that says something about price. 

Please advise on what we can do from our end to get this going, and we will comply. 

Looking forward to your response.

**Comment by sammvio** [comment]
Please submit the checksum address that includes uppercase and lowercase characters.

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
