### PR TITLE
Add DKEY info and logo

### PR DESCRIPTION
**Pull request by e8ward**
https://bscscan.com/tx/0x0bd34f1bdc05a5205b9b2384567e53bfea286a61181574f14c34cd080ffa1264

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3579750034

**Comment by sammvio** [comment]
Please submit the checksum address that includes uppercase and lowercase characters.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
