### PR TITLE
Add TPT logo and info

### PR DESCRIPTION
**Pull request by sun518**
Cloud chain game combines the application of metauniverse + Chain Game + Dao + DEX + defi + NFT + gamefi in the ecosystem to create decentralized autonomous management (DAO)

### CODE REVIEW

**Comment by opera0001** [comment]
TPT donation hash value not submitted

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
