### PR TITLE
Add TTS logo and info

### PR DESCRIPTION
**Pull request by ghsdfvs**
https://bscscan.com/tx/0xeac296ef963646e314d4f3453ad976ef005dfa4942880a78806531b4e4ed171c

### CODE REVIEW

**Comment by opera0001** [comment]
There may be some risks if you do not give up your administrator rights. Please re submit the logo after adjustment or optimization. Thank you for your support for tokenpocket.

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
