### PR TITLE
Add FYM logo and info

### PR DESCRIPTION
**Pull request by xuzhi5858**
Sample

### CODE REVIEW

**Comment by opera0001** [comment]
1、Please provide the tpt hash and confirm hash values
2、The logo you submitted is not 256x256 pixels and needs to be modified.

**Comment by xuzhi5858** [comment]
https://bscscan.com/tx/0xf7efea8b96ffa7bc2cb48731ddccd0bc2b3b405f847cb469150ba45b648a0273

**Comment by xuzhi5858** [comment]
How to replace images? Can you tell me the method?

**Comment by xuzhi5858** [comment]
logo png

**Pull request closed without merging**
