### PR TITLE
Add Partyboard info and logo

### PR DESCRIPTION
**Pull request by Pabsysop**
https://bscscan.com/tx/0x4c33de1c612a924f03ea151c91b8cf295f8b726cd2348af70f82db37861c5a47
https://bscscan.com/tx/0x40e7fb1e15fcf159feee28db2849a00ed8e256168b0e41e276aae51682efba86

### CODE REVIEW

**Comment by opera0001** [comment]
1. Low liquidity of capital pool
2. Token transactions are inactive
3. There is a large gap in the price of tokens
Please re submit the logo application after adjustment. Thank you for your support for tokenpocket.

**Comment by Pabsysop** [comment]
1. How much liquidity is ok?
2. How often transactions is ok?
3. Because this is cheap now.

opera0001 ***@***.***> 於 2022年2月18日 週五 下午12:23寫道：

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
