### PR TITLE
Add FS logo and info

### PR DESCRIPTION
**Pull request by fscoin**
https://bscscan.com/tx/0x323d2223327b6d577d8288345acc984748a85443fe501c40939dad7c403a387a

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Please refer to the tutorial and use the checksum contract address.

**Comment by fscoin** [comment]
https://bscscan.com/tx/0xa466c97756cea757e2381a1e7f8799a7614485eff5e899bf3f8597287b71fed0

**Comment by fscoin** [comment]
The hash link is incorrect, please review it again, thank you, hash link:https://bscscan.com/tx/0xa466c97756cea757e2381a1e7f8799a7614485eff5e899bf3f8597287b71fed0

**Comment by fscoin** [comment]
@zhujiayu03 
The hash link is incorrect, please review it again, thank you, hash link:https://bscscan.com/tx/0xa466c97756cea757e2381a1e7f8799a7614485eff5e899bf3f8597287b71fed0

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Pull request closed without merging**
