### PR TITLE
Add CDH logo and info

### PR DESCRIPTION
**Pull request by mary362153939**

### CODE REVIEW

**Comment by opera0001** [comment]
Your token contract is not open source, so you can't check the security of token contract. Please adjust it quickly. The order will be closed in 24 hours.

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联快速提交tp头像2小时内包过，需要联系QQ：2651964563系QQ：2651964563

**Comment by 15875804435** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
