### PR TITLE
0x247b7aa3c383a97643f5d35f0ba80f4290250672

### PR DESCRIPTION
**Pull request by ToNFT**
0xc95c301641ca7cf8ed11568712a0f3dc3d23fe19450fb30133e81ba7c6f06b03

### CODE REVIEW

**Review by ToNFT — COMMENTED** [review]
logo

**Comment by opera0001** [comment]
The submission is not in the correct format, please adapt it to the content of the tutorial.

CN: https://tphelp.gitbook.io/cn/wallet-operation/submit-token
EN: https://help.tokenpocket.pro/en/developer/how-to-submit-a-token-logo#steps-of-adding-a-token-logo-info

**Comment by ToNFT** [comment]
I have changed. Please review as soon as possible

**Comment by opera0001** [comment]
What has changed, please? This one still doesn't pass.

**Pull request closed without merging**
