### PR TITLE
Add ONEX logo and info

### PR DESCRIPTION
**Pull request by onexwallet**
https://bscscan.com/tx/0x52eaa45e8d73664703c61722505ffb18247b95090de9a8da70b92eca103756ac

### CODE REVIEW

**Comment by opera0001** [comment]
Token ownership permission has been detected as hidden, which is very dangerous.

**Comment by onexwallet** [comment]
How should we rectify the case?

**Comment by onexwallet** [comment]
https://bscscan.com/address/0x33dc5a6e2e01702c39f038f3a1c1cfefb81f2857#code

**Comment by opera0001** [comment]
I have conducted an initial inspection using Go Plus's detection and identified hidden owner permissions. Therefore, you need to verify and confirm the existence of this issue. If you have any doubts about the detection results, you can communicate with Go Plus. Please visit their website at https://gopluslabs.io/.

**Comment by opera0001** [comment]
I haven't received your response yet, so the order needs to be closed. You can continue to contact me through issues.

https://github.com/TP-Lab/tokens/pull/9939/commits

**Comment by onexwallet** [comment]
We are planning to rewrite the smart contract and will perform verification on gopluslabs to ensure no security conflict.
May I know is there any other verification you will perform? So that we can ensure we fulfill the requirement before resubmitting.

**Comment by seanlen31** [comment]
> I haven't received your response yet, so the order needs to be closed. You can continue to contact me through issues.
> 
> https://github.com/TP-Lab/tokens/pull/9939/commits

Hi, We are planning to rewrite the smart contract and will perform verification on gopluslabs to ensure no security conflict.
May I know is there any other verification you will perform? So that we can ensure we fulfill the requirement before resubmitting.

**Comment by onexwallet** [comment]
> I haven't received your response yet, so the order needs to be closed. You can continue to contact me through issues.
> 
> https://github.com/TP-Lab/tokens/pull/9939/commits

Hi, we are planning to rewrite the smart contract and will perform verification on gopluslabs to ensure no security conflict.
May I know is there any other verification you will perform? So that we can ensure we fulfill the requirement before resubmitting.

**Pull request closed without merging**
