### PR TITLE
Add NSM logo and info

### PR DESCRIPTION
**Pull request by kobe1234567890**
https://bscscan.com/tx/0xbf6cae62730b31a16558f9f2b2f81987d0b63e92e4058e1a31aff2bd29b6e0bf

### CODE REVIEW

**Comment by opera0001** [comment]
1. No liquidity pool has been added, and there are certain risks in offline offering.
2. The URL link cannot be opened.
Please re adjust and continue to apply for the token logo. Thank you very much for your recognition of tokenpocket.

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
