### PR TITLE
Add MTNB logo and info

### PR DESCRIPTION
**Pull request by Rain4086**
TPT  https://bscscan.com/tx/0xbbd80facff458a0603412acafd1492ada8dd63ee684c6624e0b3333db9a6b9b0 
验证 https://bscscan.com/tx/0x057de9dae497b46ba1a505d486ed324c3d00c714b70c6ea5622a72ca775953ad

### CODE REVIEW

**Comment by opera0001** [comment]
It is detected that the token contract has the function of increasing the issuance of tokens, taking back ownership, blacklist and other functions, so there is a certain risk, so it cannot be included for you.Sorry.

**Comment by Rain4086** [comment]
> It is detected that the token contract has the function of increasing the issuance of tokens, taking back ownership, blacklist and other functions, so there is a certain risk, so it cannot be included for you.Sorry.

Ok, understand, please put the original road 50000 TPT back into the purse at address 0 x54703e0ffb4ed975a39da2e6d0e53f84f8213d55, Thank you.

**Comment by opera0001** [comment]
Dear, I am very sorry, the donation is a voluntary act of the individual, and the record of your donation can also be used for future token applications.

**Comment by opera0001** [comment]
If you have any questions, please contact me at https://github.com/TP-Lab/tokens/issues.

**Pull request closed without merging**
