### PR TITLE
Add LICENSE logo and info

### PR DESCRIPTION
**Pull request by DAOFarmerTools**
LICENSE
TPT: https://bscscan.com/tx/0xc81756200574b26bef265da5e282f4929cbfaef438dc494950f360e67dae263a
BNB: https://bscscan.com/tx/0x436ca255fdcddee7c96c374c7f225ee4b8b550e2b4d8eb3966aeab9968082055

### CODE REVIEW

**Comment by DAOFarmerTools** [comment]
https://www.certik.com/projects/dao-farmer

**Comment by opera0001** [comment]
image
What is the relationship between the project in the audit link and you?

**Comment by DAOFarmerTools** [comment]
https://twitter.com/daofarmer/status/1514843241010532356?s=21&t=6W-fuQeZoG_qSvdL3XfxSQ

**Comment by DAOFarmerTools** [comment]
https://twitter.com/daofarmer/status/1509196388399460354?s=21&t=zOGaVjVDc2KiBcgSXVwYKQ

**Pull request merged**
