### PR TITLE
Update RMC logo and info

### PR DESCRIPTION
**Pull request by RMCMO999**
https://bscscan.com/tx/0xe974220dc7c7b35cb76a62fe34260e235e27a4375a483109dbad9223eb4c909e   https://bscscan.com/tx/0xeb7aae2803a93867c80422313ead68fef17700a5b5e36e766116d872c1e9c459

### CODE REVIEW

**Comment by opera0001** [comment]
Changing the contract address or logo requires submitting a new TPT hash value.

**Comment by RMCMO999** [comment]
New TPT tx :
https://bscscan.com/tx/0xf1691bbada0bba6d346391a870123fdc8b79a03f7e65f32b4b4da8146f1988ce 

https://bscscan.com/tx/0xf9b8bab9004ae8af9619a50742438b63b299ede68be5ccef48ce573d729e2783

**Comment by opera0001** [comment]
I've replaced it for you, but the logo you submitted doesn't seem very clear. If you need to replace the high-definition logo, please go to https://github.com/TP-Lab/tokens/issues Thank you for submitting your application.

**Comment by RMCMO999** [comment]
could current token logo be shown in token pocket? if yes it okay without changing it

**Pull request merged**
