### PR TITLE
Add BIN logo and info

### PR DESCRIPTION
**Pull request by BIN66666**
Hash:
50000TPT:
https://bscscan.com/tx/0x2f3c497e9c2217d070a047dbee91b50a9ccb5cd6795b35c7109ff40f817d7200
BNB:
https://bscscan.com/tx/0xddd01b8011c28545a50f8fa0f33d41e1f6fc078ff4111abe341963765f579f44

### CODE REVIEW

**Comment by BIN66666** [comment]
@opera0001 Please help me to verify, thank you

**Comment by BIN66666** [comment]
Bin is associated with Dor(#7731) and Amo(#7747). Bin is obtained by adding amo liquidity.I hope you can understand

**Comment by opera0001** [comment]
It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

**Comment by opera0001** [comment]
After 3 days still do not see your reply or change, so need to close the order, subsequent problems encountered in the following link can notify me: https://github.com/TP-Lab/tokens/issues

**Pull request closed without merging**
