### PR TITLE
admin

### PR DESCRIPTION
**Pull request by zntutu007**
admin  测试

### CODE REVIEW

**Comment by zntutu007** [comment]
BSC-WorldCup-0xF705099Fa3a377Bcd798d19c7235737E163F82fF-https://bscscan.com/tx/0x8686f31f5b07a671e433bd9016ad6bbf6c0581b657025ccc02e8ee60497c642f

**Comment by zntutu007** [comment]
WorldCup LOGO and info

**Comment by opera0001** [comment]
There is a risk of infringement when submitting the logo.

**Comment by zntutu007** [comment]
重新提交logo.还需要再交3000tpt吗












Mr.hero
***@***.***


---Original---
From: ***@***.***&gt;
Date: Sat, Feb 12, 2022 21:55 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] admin (PR #5305)




 
Closed #5305.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by zntutu007** [comment]
诈骗












Mr.hero
***@***.***


---Original---
From: ***@***.***&gt;
Date: Sun, Mar 13, 2022 09:38 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] admin (PR #5305)




 
快速提交tp头像2小时内包过，需要联系QQ：2651964563
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request closed without merging**
