### PR TITLE
Add CHT logo and info

### PR DESCRIPTION
**Pull request by gaildavie**
0x887f1cccecd7567c68e4f0c9e2005c211bdddb5f559056b6efc16a18763b3a6c  30,0000tpt

### CODE REVIEW

**Comment by giki0318** [comment]
Please attach your donation link. we cannot review your donation according to your hash.
We will close this PR within 24 hrs if there is no more reply.

**Comment by gaildavie** [comment]
Sorry, an error occurred while submitting. The correct hash value link is: https://bscscan.com/tx/0xb55340b34e0ca156d1d942b5a3071c64ef7c0bdf83f5ba81003e25403efd6a94

**Comment by jjjgjk** [comment]
1212在吗

**Comment by jjjgjk** [comment]
你好

**Comment by tplogotijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request merged**
