### PR TITLE
0x47dd08ac01fE7924d834B53757420bACa97B16dB

### PR DESCRIPTION
**Pull request by tl2215689**
https://hecoinfo.com/tx/0x648116310f95512abbe6cda4f2f8dd99d554b0e11ea5362d1ed58584b4eff089

Application display“Holders，Transfers，info”And other detailed data。

### CODE REVIEW

**Comment by tl2215689** [comment]
https://hecoinfo.com/tx/0xf10a379a169865a2885dd5be7637909b07376d381db2c28b358a9a443d6e4223
Application display“Holders、Transfers、info”And other detailed data。

**Comment by zhujiayu03** [comment]
Please do not submit TPT token information and re-submit your token logo and info to us.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
