### PR TITLE
Add PTM logo and info

### PR DESCRIPTION
**Pull request by PoorTravelMeta**
BSC-0xe33F6009921842b99884Eadd82900E34367b5eA0- https://www.bscscan.com/tx/0xfd3b2b0c2209485b0eede05c55c91639b5097f2039b5097f2039b509205eA03

### CODE REVIEW

**Comment by PoorTravelMeta** [comment]
BSC-0xe33F6009921842b99884Eadd82900E34367b5eA0- https://www.bscscan.com/tx/0xfd3b2b0c2209485b0eede05c55c91639b5097f2039b5097f2039b509205eA03

**Comment by tiaojiaotubiaobaoguo** [comment]
24小时提交logo包过，加QQ：2980874528

**Comment by sammvio** [comment]
Please re-submit your files to bsc folder

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
