### PR TITLE
木瓜社区欢迎你

### PR DESCRIPTION
**Pull request by eosubq**
一个纯粹的社区治理代币。这是一次伟大的社会实践，也许会失败，但一旦成功那将是惊人的！
https://bscscan.com/tx/0x68d3881091db46e7aaad07222b77d9e5a53a66cc0ae0d6377b12ef2eda837b3a?utm_source=tokenpocket

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Please refer to the tutorial, and re-submit your files in the correct format.

**Comment by eosubq** [comment]
我想了解一下，是那个地方出现了错误？导致图标不能合并？ ub eq ***@***.*** 签名由 网易邮箱大师 定制 在2021年08月16日 22:24，zhujiayu03 写道： Please refer to the tutorial, and re-submit your files in the correct format. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
