### PR TITLE
Add LC logo and info

### PR DESCRIPTION
**Pull request by 123456llcc**
HECO - LC - 0xC0511D20A75fcA0716D073bdC391c8952C45a138 - https://hecoinfo.com/tx/0x1917e486c7ce1867d9be188ab56c7df9372b5a788dbdc2c38c069cbc56eb2e31

### CODE REVIEW

**Comment by 123456llcc** [comment]
HECO - LC - 0xC0511D20A75fcA0716D073bdC391c8952C45a138 - https://hecoinfo.com/tx/0x1917e486c7ce1867d9be188ab56c7df9372b5a788dbdc2c38c069cbc56eb2e31

**Comment by 123456llcc** [comment]
HECO - LC - 0xC0511D20A75fcA0716D073bdC391c8952C45a138 - https://hecoinfo.com/tx/0x1917e486c7ce1867d9be188ab56c7df9372b5a788dbdc2c38c069cbc56eb2e31

**Comment by 123456llcc** [comment]
HECO - WC - 0xDD4D570456780FbFD463544A6AA3466A48b64AB1
https://hecoinfo.com/tx/0x5a7905470f71abd26b22909b6db43b02d6609a98b374d05dbb25ec1631388dee

**Comment by zhujiayu03** [comment]
Please re-submit your files to heco folder

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
