### PR TITLE
Add LONG logo and info

### PR DESCRIPTION
**Pull request by Longtotem1**
https://bscscan.com/tx/0xcbf7128ace879d8eab2348efd99daf1764a5842b657ca20821abf416d20293af

### CODE REVIEW

**Comment by opera0001** [comment]
1.  It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.
2. The submitted file is not saved in the eth directory, please adjust it again.

**Comment by Longtotem1** [comment]
Hello, our tokens will be listed on February 3, we will submit the audit, I
will send you the audit link, the second question I did not put the file
into the ETH folder, because I can not put it in the submission process, so
can you ask your technicians to help me put the ETH chain? Thank you very
much.

CMC and CGC will also be included after our project is launched, and we
have submitted it. We also have publicity cooperation with many wallets,
and we have also found many local KOL publicity in Taiwan.
opera0001 ***@***.***>于2024年2月1日 周四09:27写道：

**Comment by Longtotem1** [comment]
I'll resubmit.

LONG TOTEM ***@***.***>于2024年2月2日 周五17:06写道：

**Comment by opera0001** [comment]
Please inform me after completing the token security review.

**Comment by Longtotem1** [comment]
Hello, I have re-submitted once, this time I put it in the ETH folder,
because we have changed the new contract address, so we will re-audit, I
will send it to you after the audit is completed, thank you, if you have
any questions about the information submitted this time, please tell me,
thank you

opera0001 ***@***.***>于2024年2月3日 周六23:34写道：

**Comment by opera0001** [comment]
It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

**Comment by opera0001** [comment]
It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

**Comment by opera0001** [comment]
The token you submitted has undergone multiple revisions and extensive communication, but still cannot be resolved. Therefore, the order needs to be closed, and you can resubmit the order.

**Pull request closed without merging**
