### PR TITLE
Add RMB logo and info

### PR DESCRIPTION
**Pull request by jerrysongshu**
https://bscscan.com/tx/0x4e82526e5b4176c6f416c5f3efc94db722bf9ba1fa359876d2aaf1ad8c2ca39f

### CODE REVIEW

**Comment by netlocks** [comment]
CPB hash : https://bscscan.com/tx/0x0f6f914c0ed1c7a7cbd8c9a8dfd4195c151403937de17de104ac5966fa8377a3

**Comment by giki0318** [comment]
rejected

**Comment by netlocks** [comment]
why?

> 拒绝

why?

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
