### PR TITLE
Add CTC logo and info

### PR DESCRIPTION
**Pull request by CTCLOGO**
https://bscscan.com/tx/0xaab580c84a558af29ae10f9077f252c113646d20ee18c37998f4771845da0bc1;
https://bscscan.com/tx/0x7d96184da784d9a935a2d226c82e3ec4f6af411d2c59770f9a0b0e71d9d484bf;

### CODE REVIEW

**Comment by opera0001** [comment]
Tokens have a high circulation rate, why is that?

**Comment by CTCLOGO** [comment]
> Tokens have a high circulation rate, why is that?

Because tokens is all in circulation

**Comment by opera0001** [comment]
Sorry, the point I was trying to make was that the token buy-in rates are high, why is that?
image

**Comment by opera0001** [comment]
1 day later did not see your message or change, so close the order, follow-up questions can contact me: https://github.com/TP-Lab/tokens/issues

**Pull request merged**
