### PR TITLE
Add SOACS logo and info

### PR DESCRIPTION
**Pull request by BIGsharkX**
3000TPT:https://bscscan.com/tx/0xc6e40eb98f94d337cc7b1b407f87700da4f7be84afdbed8a766a294968ce3f7f
27000tpt:https://bscscan.com/tx/0xb1546c0af578fe5144d8f1ae8bdeef12c6d430d1cdb7971fd79adf70f0601526
BSC;https://bscscan.com/tx/0xde163063be2f805a8cc3720c0d08422ce384138e498f379995dfb80f62cf9a47

### CODE REVIEW

**Comment by BIGsharkX** [comment]
27000tpt:https://bscscan.com/tx/0xb1546c0af578fe5144d8f1ae8bdeef12c6d430d1cdb7971fd79adf70f0601526

**Comment by tubiaotijao** [comment]
1

**Comment by tplogotijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request merged**
