### PR TITLE
Add BMW logo and info

### PR DESCRIPTION
**Pull request by XiangBin520**
0x6e98e733c7d441b2e078e59146fcd5bb88d1731de1ee4b616a28a52ee6a28caf

### CODE REVIEW

**Comment by opera0001** [comment]
1. There is no official contact information on the official website

2. There is no safety audit content in the project

3. It is found on the official website that meelons related materials are used. It is necessary to explain the situation

4. It is found that there may be a switch to prohibit transactions

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
