### PR TITLE
Add MP logo and info

### PR DESCRIPTION
**Pull request by xioscd**
Sample

### CODE REVIEW

**Comment by xioscd** [comment]
> 
> 
> https://bscscan.com/tx/0xd1a726138a0620f8114e86df8f7a9cde2700aba4b394f065f6d08afdd321fdce

**Comment by xioscd** [comment]
Can someone approve this please? We paid the fees and everything. If this is no longer active please announce it

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
