### PR TITLE
Add Afro logo and info

### PR DESCRIPTION
**Pull request by ChrisTriesToDoBest**
BSC - AFRO - 0x2f4e9c97aaffd67d98a640062d90e355b4a1c5392 - https://bscscan.com/tx/0x1f0a9b7ba08e46faa6d6f33eb78b24700cd639f16f44bdab105adbc030fb0ad4

### CODE REVIEW

**Comment by tiaojiaotubiaobaoguo** [comment]
24小时提交logo包过，加QQ：2980874528

**Comment by ChrisTriesToDoBest** [comment]
Updated logo.png

**Comment by sammvio** [comment]
Please submit the checksum address that includes uppercase and lowercase characters.

**Comment by ChrisTriesToDoBest** [comment]
0x2F4e9c97aAFFD67D98A640062d90e355B4a1C539

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
