### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by PUBG-tp**
https://bscscan.com/tx/0xb06296fd279ca4df23876770bca64975ce0460b2df0249bbcfb2c5735a354d67 https://bscscan.com/tx/0x7e32bca8cc2031c1e1dba599bbb73f824fdd7dead52b1cca17bd9ef8d4f2c668

### CODE REVIEW

**Comment by opera0001** [comment]
The submitted logo is infringing, so the use of this logo is not recommended.

**Comment by PUBG-tp** [comment]
It's ok, please upload directly

**Comment by opera0001** [comment]
Sorry, didn't see the new logo submission.

**Comment by PUBG-tp** [comment]
logo

**Comment by PUBG-tp** [comment]
logo

**Comment by PUBG-tp** [comment]
Please use this to submit

**Comment by PUBG-tp** [comment]
老板，我今天找了一天没找到重新提交图片的地方，我的合约也没问题，你就给我上了吧，人家英国女皇去世了上头像也没说侵犯肖像权阿，求求大佬了

**Comment by PUBG-tp** [comment]
谢谢老板

**Comment by PUBG-tp** [comment]
我看了，图片的话，无法编辑，无法删除，我找不到上传图片的地方了

**Comment by PUBG-tp** [comment]
image
真的没有重新上传的地方

**Comment by PUBG-tp** [comment]
老板，你给我上了吧，求求

**Pull request merged**
