### PR TITLE
Add SDOGE logo and info

### PR DESCRIPTION
**Pull request by AQscoutdoge**
3000TPT-https://bscscan.com/tx/0x885639d83ef151b67e9e2e656d6b43fb668c8cebe667e2682e2546b2f140add5
token info
{
"name": "Scout Doge Token",
"website": "https://bscscan.com/token/0x9e551b430b7ab145c96c6ede72a34ec2a90d4eca",
"description": "Scout Doge TOKEN.",
"explorer": "https://bscscan.com/token/0x9e551b430b7ab145c96c6ede72a34ec2a90d4eca",
"type": "BEP20",
"symbol": "SDOGE",
"decimals": 9,
"status": "active",
"id": "0x9e551b430b7ab145c96c6ede72a34ec2a90d4eca"
}

### CODE REVIEW

**Comment by Metaverseswap** [comment]
专业提交logo！加速审核2小时内包过！QQ:3579750034

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3076439606

**Comment by sammvio** [comment]
Please submit the checksum address that includes uppercase and lowercase characters.

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
