### PR TITLE
Replace GV logo and info

### PR DESCRIPTION
**Pull request by a31235**
Original contract address
BSC-GV-0xd4673C38f24a183f1bF5397425dF075be0BbCA6d-https://bscscan.com/tx/0x11c56cd3556ec62c66de63417120c1feff7b7e1c54d4db7d964fad30fb8d83f4 

Current contract address
BSC-GV-0xC574c5a34d57e9246B9C82954a4C31482d950D23-https://bscscan.com/tx/0x11c56cd3556ec62c66de63417120c1feff7b7e1c54d4db7d964fad30fb8d83f4

If the contract address changes, please change the logo

### CODE REVIEW

**Comment by opera0001** [comment]
Sorry dear, if the logo included in a short time needs to be changed, we can help you replace it for free, but if you need to change the contract address, it is equivalent to a new submission, so you will need a new donation to proceed with the replacement.

**Comment by a31235** [comment]
My contract address is wrong. I reissued the contract and hope to replace the previous logo with the new contract address. The name of the token is the same as the logo. Please help me replace it.

**Comment by opera0001** [comment]
Sorry dear, if the logo included in a short time needs to be changed, we can help you replace it for free, but if you need to change the contract address, it is equivalent to a new submission, so you will need a new donation to proceed with the replacement.

**Comment by a31235** [comment]
I am very sorry for the trouble this has caused you. Although the contract address of this token has been changed, its name and logo have not changed. Please help me change its logo.
________________________________
寄件者: opera0001 ***@***.***>
寄件日期: 2024年9月29日 下午 10:58
收件者: TP-Lab/tokens ***@***.***>
副本: a31235 ***@***.***>; Author ***@***.***>
主旨: Re: [TP-Lab/tokens] Replace GV logo and info (PR #11001)


Sorry dear, if the logo included in a short time needs to be changed, we can help you replace it for free, but if you need to change the contract address, it is equivalent to a new submission, so you will need a new donation to proceed with the replacement.

**Comment by a31235** [comment]
We just changed the contract address, nothing else has changed. Please believe me, it is definitely the same project. This error is temporary. It was submitted successfully last week. This week, the error was found and the contract address was resubmitted. I hope the original logo can be migrated over.

**Comment by opera0001** [comment]
This is a one-time occurrence; there will be no next time.

**Comment by a31235** [comment]
Thank you very much for your understanding and support

**Pull request merged**
