### PR TITLE
Add WF logo and info

### PR DESCRIPTION
**Pull request by 18823829278**
https://bscscan.com/tx/0x6de88747e833e80a79d54b6e9c34ba91f6e52f4b46ee40abfe838493629439f8

### CODE REVIEW

**Comment by opera0001** [comment]
1. Detect the existence of tokens to increase the setting of the issue
2、Detected the setting that tokens cannot be sold 100%

Please explain what they do separately.

**Comment by opera0001** [comment]
A setting that can increase token issuance is detected, please explain what it does.

**Comment by opera0001** [comment]
Check it out here: https://gopluslabs.io/token-security/56/0x6B45229113E7C02EdFC5545F52B664Fc8b805859

**Comment by 18823829278** [comment]
> 在这里查看：[https ://gopluslabs.io/token-security/56/0x6B45229113E7C02EdFC5545F52B664Fc8b805859](https://gopluslabs.io/token-security/56/0x6B45229113E7C02EdFC5545F52B664Fc8b805859)
确认真的没有增发，可以让你们技术看看源码，只有减少

**Comment by 18823829278** [comment]
> 
合约功能上 存在_balances[地址].add方法有3种情况：1、给黑洞地址增加，这个是代币销毁功能  2、给合约本身增加，这个是回流底池功能， 3、正转账和swap交易中功能 ，再无其他地方存在增加余额功能

**Pull request merged**
