### PR TITLE
ADD MCU INFO and LOGO

### PR DESCRIPTION
**Pull request by jackbob123**
ADD MCU INFO and LOGO
Add Bzzt Info and Logo
Add Bzzb Info and Logo
Add Bzzone Info and Logo
Add Pangolin Info and Logo

支付链接：
mcu:
https://bscscan.com/tx/0xbf4602cbf4c29244dfedba08a36cb4ddb6287bf19a8eac71a78ddd6181aec2ab
bzzb:
https://bscscan.com/tx/0xfa20c764f46063802fc288e6737247864e8d88b9c53d923634a3c5232e5f6594
Bzzone:
https://bscscan.com/tx/0x935e19396fa9533de6e44a7fe0f434808922ac701cf3d378482e3d5cd9493457
bzzt:
https://bscscan.com/tx/0x9aeeb60efc3b9353e1b6aa3b5f695797343d1c0af5499aa4767b40023d7f3b20
Pangolin:
https://bscscan.com/tx/0x831b62d1e849013c7b7d233d52fac0b668e24a8efca2a2d29b95ab27cd2f2d17

TPT：
https://bscscan.com/tx/0xc6705713b6523b0417165da92a36d63e5285d4d9c60f30f7739e4175f0a67994
https://bscscan.com/tx/0xd34f6e570e392809d403a96441b618a329796f0fe0862fada60dce4de234a270
https://bscscan.com/tx/0x94c42ade4ddc73449e4e88ec14d675fc3a8c03d084b5c0c86fa72349bf6c164d
https://bscscan.com/tx/0xda827032c5bc0b2a7a0d4584b7ef1c21a3499bdf06b79ec20a3e9019a36ad6bd
https://bscscan.com/tx/0xb60286754d66d494ef7745437b1d411a7af63ea0df355da5b5b0dac366b6b64f

### CODE REVIEW

**Comment by jackbob123** [comment]
支付记录链接更正：
mcu:
https://bscscan.com/tx/0xe2b97372299d1d526aeda969d72f46359440ac67cc2e678c8016ef0a817d4e59

bzzb:
https://bscscan.com/tx/0xfa20c764f46063802fc288e6737247864e8d88b9c53d923634a3c5232e5f6594

Bzzone:
https://bscscan.com/tx/0x935e19396fa9533de6e44a7fe0f434808922ac701cf3d378482e3d5cd9493457

bzzt:
https://bscscan.com/tx/0x9aeeb60efc3b9353e1b6aa3b5f695797343d1c0af5499aa4767b40023d7f3b20

Pangolin:
https://bscscan.com/tx/0x831b62d1e849013c7b7d233d52fac0b668e24a8efca2a2d29b95ab27cd2f2d17

**Comment by jackbob123** [comment]
支付记录链接更正：
mcu:
https://bscscan.com/tx/0xbf4602cbf4c29244dfedba08a36cb4ddb6287bf19a8eac71a78ddd6181aec2ab

bzzb:
https://bscscan.com/tx/0xfa20c764f46063802fc288e6737247864e8d88b9c53d923634a3c5232e5f6594

Bzzone:
https://bscscan.com/tx/0x935e19396fa9533de6e44a7fe0f434808922ac701cf3d378482e3d5cd9493457

bzzt:
https://bscscan.com/tx/0x9aeeb60efc3b9353e1b6aa3b5f695797343d1c0af5499aa4767b40023d7f3b20

Pangolin:
https://bscscan.com/tx/0x831b62d1e849013c7b7d233d52fac0b668e24a8efca2a2d29b95ab27cd2f2d17

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
