### PR TITLE
Add PNT logo and info

### PR DESCRIPTION
**Pull request by seeyounet**
https://bscscan.com/tx/0x0340199eb680fc33f5d82e64b42c555de052f152c89a2d0b5b742e370135c477?utm_source=tokenpocket

### CODE REVIEW

**Comment by guoxintongsam** [comment]
The contract didn’t verify and publish.

**Comment by seeyounet** [comment]
How to solve this problem？

**Comment by seeyounet** [comment]
> 合同没有公布和发布。

How to solve this problem

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
