### PR TITLE
Add AI logo and info

### PR DESCRIPTION
**Pull request by milesdjs**

### CODE REVIEW

**Comment by opera0001** [comment]
Please provide the donation TPT hash value link.

**Comment by irameehan** [comment]
https://bscscan.com/tx/0x6498c6bf1d2e9261026ec91493ac609ba9124e843699c14171191293497edd1f  TPT

**Comment by irameehan** [comment]
I apologize for changing my account and resubmitting the TPT hash value due to some issues with my previous account. Thank you.

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Pull request merged**
