### PR TITLE
Create Add FSD logo And Info

### PR DESCRIPTION
**Pull request by sansu8866**
Transaction Hash:
0x87fd8fa748e53d0f6761fdcec35709743a0682118e615aea139a62856213704b

https://bscscan.com/tx/0x87fd8fa748e53d0f6761fdcec35709743a0682118e615aea139a62856213704b

### CODE REVIEW

**Comment by opera0001** [comment]
The provided TPT hash value is duplicated with #10622, please check. Additionally, the submitted JSON and logo files are incorrect, please adjust.

**Review by sansu8866 — COMMENTED** [review]
能否重新提交50000TPT截图，重新申请并通过

**Comment by opera0001** [comment]
> 能否重新提交50000TPT截图，重新申请并通过

Okay, please resubmit and let me know afterward.

**Comment by sansu8866** [comment]
您好，已经重新提交，请您审核，谢谢

**Comment by sansu8866** [comment]
logo
你好，用这个logo可以吗，我裁剪了一下

**Comment by sansu8866** [comment]
logo
这个才是256*256规格的，请使用这个

**Comment by opera0001** [comment]
image

1. No new TPT donation hash value has been seen.
2. Check the submitted JSON file because the current submission content cannot be merged.
3. The submitted logo is not 256x256 pixels.

**Comment by sansu8866** [comment]
你好，这个是新的交易哈希值：上午刚转的，0xf604f120ae81725a8e9e51aa0128a3afff35698ba4115ea9be5faa51ead127b9

**Comment by sansu8866** [comment]
我全部重新提交吧

**Comment by sansu8866** [comment]
{
 "name": "Full-Self Driving",
 "website": "https://usfsd.org",
 "description": "A leading multi-chain wallet that supports BTC, ETH, BSC, HECO, TRON, EOS, OKExChain, HSC and so on.",
 "explorer": "https://bscscan.com/token/0xB1B48f5F5b025F693E81797f17b2C5dF43f4E7E5",
 "type": "BEP20",
 "symbol": "FSD",
 "decimals": 12,
 "status": "active",
 "id": "0xB1B48f5F5b025F693E81797f17b2C5dF43f4E7E5"
}

**Comment by sansu8866** [comment]
你好，我现在文件都没有问题了是吗？是不是等logo审核通过？

**Pull request closed without merging**
