### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by nankaicheng**
Add BNV logo and info

BSC - TPT - 0x42687d69c41fee9dd804e36d1b4df3d57e848291af0e2f9a3bf6436b5a5d5dde

https://bscscan.com/tx/0x42687d69c41fee9dd804e36d1b4df3d57e848291af0e2f9a3bf6436b5a5d5dde

### CODE REVIEW

**Comment by nankaicheng** [comment]
Please，Add BNV logo and info，Thanks

**Comment by hujun918** [comment]
TPT转账链接：https://bscscan.com/tx/0x42687d69c41fee9dd804e36d1b4df3d57e848291af0e2f9a3bf6436b5a5d5dde

文件里面也有附送的，谢谢！

**Comment by nankaicheng** [comment]
https://bscscan.com/tx/0x42687d69c41fee9dd804e36d1b4df3d57e848291af0e2f9a3bf6436b5a5d5dde

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request merged**
