### PR TITLE
Add Logan logo and info

### PR DESCRIPTION
**Pull request by logannew**
https://bscscan.com/tx/0x111d8fd24a45e9793055ec6fe18804ccb95e479bf0902132b067d122da918ad6

### CODE REVIEW

**Comment by opera0001** [comment]
Please submit a link to the hash value of the TPT donation.

**Comment by logannew** [comment]
> Please submit a link to the hash value of the TPT donation.

@opera0001  https://bscscan.com/tx/0x19de4a9f7fcdccafa9ce22f55de5514824c19c93c6c27a86bf55918eed9e522f

**Comment by opera0001** [comment]
Please check the quantity

**Comment by opera0001** [comment]
After 2 days of not seeing your reply, the order needs to be closed, you can go to issues and leave a message for me.

https://github.com/TP-Lab/tokens/issues

**Comment by logannew** [comment]
> After 2 days of not seeing your reply, the order needs to be closed, you can go to issues and leave a message for me.
> 
> https://github.com/TP-Lab/tokens/issues

@opera0001 https://bscscan.com/tx/0x18e1eabed79b9c9f7f587a309d29cac69436b4774b1a8ba6c46247864db46a6d

**Comment by logannew** [comment]
> Please check the quantity

@opera0001 https://bscscan.com/tx/0x18e1eabed79b9c9f7f587a309d29cac69436b4774b1a8ba6c46247864db46a6d

**Pull request closed without merging**
