### PR TITLE
Add Catcoin

### PR DESCRIPTION
**Pull request by catcoincom**

### CODE REVIEW

**Comment by catcoincom** [comment]
https://bscscan.com/tx/0xcae4c678a3fe22e3d212544a214a199c4e43195f0313a1f730da7be55d90b1ef

**Comment by opera0001** [comment]
Please check if the submitted content is correct.

**Comment by catcoincom** [comment]
yes its correct

**Comment by catcoincom** [comment]
If anything is wrong then kindly let us know

**Comment by opera0001** [comment]
image

Please change the PNG resolution to 256x256 pixels.

**Comment by catcoincom** [comment]
cat256

shared here is that ok

**Comment by catcoincom** [comment]
logo

**Comment by catcoincom** [comment]
uplaod is disabled so we uploaded here

**Pull request merged**
