### PR TITLE
Add ELE logo and info

### PR DESCRIPTION
**Pull request by elelogo**
TPT: https://bscscan.com/tx/0x569ffe948a1adba18335b1ea5fa5127c92666c42e5686afded5595f5bbb99531
BNB: https://bscscan.com/tx/0x4730bec653fb5054b61ecec6319270e5edf35b74da21696e869b4d444d83d680

### CODE REVIEW

**Comment by opera0001** [comment]
1、It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

2、The submitted logo is not 256x256 pixels, please adjust it.

**Comment by elelogo** [comment]
I have adjusted the resolution of the LOGO. What should I do to replace the submitted LOGO?

**Comment by opera0001** [comment]
1. The logo can be sent to me in a message.

2. A hidden owner permission is detected, please check the code.
image

**Comment by opera0001** [comment]
We have not seen your reply after 2 days, so the order needs to be closed, please contact us in issues.

https://github.com/TP-Lab/tokens/issues

**Pull request merged**
