### PR TITLE
add Fiking logo and info

### PR DESCRIPTION
**Pull request by taozi668899**
BSC-TPT-0x7e5bD2c2FBAaccA61257061661CFed2A565fC1Be-
https://bscscan.com/tx/0x3bb6be2f9c2b11def68d9d3ba999b04fb4a13df8bb2249a8a983fff4c1f81469

### CODE REVIEW

**Comment by opera0001** [comment]
1. Not open source, unable to view contract security
2. There may be some risks if you do not give up your administrator rights.

**Comment by opera0001** [comment]
I left a message with you 18 hours ago to remind you of the token contract. So far, there has been no adjustment, so you need to close the order. After closing, you need to resubmit the order, and the donation fee will be adjusted to 30000 TPT. Please know.

**Comment by opera0001** [comment]
Thank you for your support of tokenpocket.

**Comment by taozi668899** [comment]
Hello, I am sorry that I did not read the email on business yesterday. Is 3000TPT not returned if it is not approved&nbsp;&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TP-Lab/tokens"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月1日(星期二) 下午3:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TP-Lab/tokens] add Fiking logo and info (PR #5849)





 
Closed #5849.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
