### PR TITLE
add DBG logo and info

### PR DESCRIPTION
**Pull request by qq3086336593**
https://hecoinfo.com/tx/0x038560ae2fbfac09b4c26f7dc01680451cf2c99dd589df1bf573002af7f6ceef

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Please refer to the tutorial, and re-submit your files in the correct format.

**Comment by qq3086336593** [comment]
I have strictly in accordance with your requirements for the application, how can not pass&nbsp;



---Original---
From: ***@***.***&gt;
Date: Mon, Aug 30, 2021 12:28 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] add DBG logo and info (#2869)




 
Closed #2869.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by qq3086336593** [comment]
#2869  Hello, I didn't see that line. Please have a look. Thank you. I applied strictly according to your requirements.

**Comment by guoxintongsam** [comment]
Please re-submit your files to heco folder

**Comment by qq3086336593** [comment]
Then just pull up the request. yeah, do I still have to pay tpt?&nbsp; There is no extra line, you should be able to pass directly through this side, brother&nbsp;

---Original---
From: ***@***.***&gt;
Date: Tue, Aug 31, 2021 11:13 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] add DBG logo and info (#2869)




 
Please re-submit your files to heco folder
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by qq3086336593** [comment]
Or do you want to delete the source folder and resubmit it&nbsp;



---Original---
From: ***@***.***&gt;
Date: Tue, Aug 31, 2021 11:13 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] add DBG logo and info (#2869)




 
Please re-submit your files to heco folder
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
