### PR TITLE
Upload Fma logo and info

### PR DESCRIPTION
**Pull request by Fma999**
https://bscscan.com/tx/0x8748bd44ddb094c4df4d3b13092f582c5699a0e87b1fc5c66ce023de2ecb017e 
We have implemented a mechanism where tokens are sourced from gifts and are not encouraged to buy or sell, so tokens are only allowed to buy in small quantities. Please review!
Thanks.

### CODE REVIEW

**Comment by opera0001** [comment]
Haven't started trading yet?

**Comment by Fma999** [comment]
The transaction has already started.

**Comment by opera0001** [comment]
The buying cost requires a 90% slippage, why is that?

**Comment by Fma999** [comment]
The buying cost requires a 90% slippage, We have implemented a mechanism where tokens come from gifts and are not encouraged to be purchased, so tokens are only allowed to be purchased in small quantities.
Thanks.

**Pull request closed without merging**
