### PR TITLE
add TRGC logo and info

### PR DESCRIPTION
**Pull request by Leo900805**
https://bscscan.com/tx/0xec728f1f32935115007e06bc46d15cadcb8da0eb985df73a4578a4cf6a6cb39a ; https://bscscan.com/tx/0xaeda07675b233ad646b13b367933deac91af7106027268294825c311ee5c8a68

### CODE REVIEW

**Comment by opera0001** [comment]
The token control permissions have not been discarded and still retain the ability to modify transaction fees, suspend token trading, and other permissions. Please provide an explanation of the functionality of these features.

The submitted logo is not 256x256 pixels, please make the necessary adjustments.

**Comment by opera0001** [comment]
Two days have passed without seeing your reply or any changes, so the order needs to be closed. If you wish to continue with this order (without needing to resubmit it to the queue), you can contact me through issues at the following link:

https://github.com/TP-Lab/tokens/issues

**Comment by Leo900805** [comment]
Sorry I just saw it

**Comment by Leo900805** [comment]
How do I resubmit

**Pull request closed without merging**
