### PR TITLE
demarket.io，一个基于Web3.0的电商平台，DMA是我们的平台代币。

### PR DESCRIPTION
**Pull request by distoken001**
TPT转账链接：https://bscscan.com/tx/0x73b1ef2c92696990161e890bcac686edd21fd37ef4187b7007255bde42b5b17e BNB转账链接：https://bscscan.com/tx/0x95e46ec980f2afe88c7b4d6ecd30884a8d4531cc1a54fc4345f2cf2864169696

### CODE REVIEW

**Comment by opera0001** [comment]
Detected that the token can have an increase issuance setting. Please explain its purpose.

**Comment by distoken001** [comment]
> 

管理员权限已经回收，目前不能增发 。
Administrative privileges have been revoked, and currently, there is no ability to issue additional tokens.

**Comment by distoken001** [comment]
管理员权限已经回收，不能增发 。
Administrative privileges have been revoked, and currently, there is no ability to issue additional tokens.

**Comment by distoken001** [comment]
> Detected that the token can have an increase issuance setting. Please explain its purpose.



> 
管理员权限已经回收，不能增发 。
Administrative privileges have been revoked, and currently, there is no ability to issue additional tokens.

**Pull request merged**
