### PR TITLE
Add DBG logo and info

### PR DESCRIPTION
**Pull request by qq3086336593**
BSC-DBG-0xE1144C736E9419A3524D1e8394F357b494D6B4C2-https://bscscan.com/tx/0x550230275c8925fa8408549b0e756640eabb99df6cb20bca6d213b01e5aa2ce2

### CODE REVIEW

**Comment by opera0001** [comment]
Please follow the tutorial.
https://tphelp.gitbook.io/cn/wallet-operation/submit-token

**Comment by qq3086336593** [comment]
Has been resubmitted. Please merge. Thank you.

**Comment by opera0001** [comment]
Have you checked carefully according to the tutorial? Please reconfirm and resubmit. A GitHub account can only submit one logo application at a time, and the logo cannot be used for one purpose. And the number of TPTS....

**Comment by qq3086336593** [comment]
Receive&nbsp;



---Original---
From: ***@***.***&gt;
Date: Tue, Mar 22, 2022 13:13 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] Add DBG logo and info (PR #6306)




 
Closed #6306.

**Pull request closed without merging**
