### PR TITLE
add YNF logo and info

### PR DESCRIPTION
**Pull request by xuezhangkaren**
https://bscscan.com/tx/0x94ef7a65da3cb5fea05f8b6cb9b4f87af0fd0ecd3c34afa7be9476ecfb53c625

### CODE REVIEW

**Comment by opera0001** [comment]
1. Contract not open source
2. Insufficient working capital pool
Please submit again after adjustment. Thank you for your support for tokenpocket

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
