### PR TITLE
Add CPD info and logo

### PR DESCRIPTION
**Pull request by mboothj56**
https://bscscan.com/tx/0x53deb8c299e03df2de59f3795f1e834b6d62551e80e30b31f79e95221c9f0403

### CODE REVIEW

**Comment by heipacker** [comment]
According to the DAO, the donation amount for a logo update has been updated to 30,000 TPT. [Click here for Details](https://snapshot.org/#/tptdao.eth/proposal/0x781abc1ade2ebd082aec4f57b7199d472a2b2850b3df46c8ec37e3b6a1a243c2)

**Comment by giki0318** [comment]
Please update your donation to 30,000 TPT.

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
