### PR TITLE
Add STE logo and info

### PR DESCRIPTION
**Pull request by nenrgy**
https://hecoinfo.com/tx/0xf4f94c6195335736c181e3fefcabef2f7f53b6c0d5e418acc47484008d7f3ec2

### CODE REVIEW

**Comment by tubiaoyingji** [comment]
专业加快提交LOGO，20分钟内审核包过，QQ：1450001284

**Comment by sammvio** [comment]
Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token

**Comment by nenrgy** [comment]
How do you do
Token information has been submitted, with TP staff identified several times, help me to review, thank you!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TP-Lab/tokens"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月8日(星期三) 上午10:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TP-Lab/tokens] Add STE logo and info (PR #4261)





 
Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
