### PR TITLE
Add BM info and logo

### PR DESCRIPTION
**Pull request by btmiracle**
https://bscscan.com/tx/0x92ed0890a4334311e228da9204ae025f21b139dfa53167d84f50acdfdea98dd0

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:2980874528

**Comment by sammvio** [comment]
Please delete the wrong files.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
