### PR TITLE
Add IFW logo and info

### PR DESCRIPTION
**Pull request by zwilly**
3000TPT has been donated, transaction address: 0x82607e8265006cdcd2fd36f555528090bbb38608ca25f3781914c0032a2e40c5

### CODE REVIEW

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by opera0001** [comment]
1. Not open source, unable to view contract security
2. Not relinquishing ownership
3. The working capital pool is not high
It is a safer way to open source contracts and give up ownership. Please re adjust or optimize the logo and submit it later. Thank you for your support for tokenpocket.

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
