### PR TITLE
add hood nft logo

### PR DESCRIPTION
**Pull request by lcwypn**
https://bscscan.com/tx/0x01c3dde4ac84ca30e90643a58121ed0d78c4d56f0ef48e77ac57a2cce46897ce
https://bscscan.com/tx/0x5d260aa15baba44d72f30a87dcaa09f3280487e7393255bdd3fe3478a6a81f0b

### CODE REVIEW

**Review by lcwypn — COMMENTED** [review]
logo

**Comment by opera0001** [comment]
Detected that the NFT contract is not open-source, which could affect the display of future content. Please notify me after it is open-sourced.

**Comment by lcwypn** [comment]
NFT is already open source

**Comment by lcwypn** [comment]
> Detected that the NFT contract is not open-source, which could affect the display of future content. Please notify me after it is open-sourced.

NFT is already open source

**Pull request merged**
