### PR TITLE
Add gocp token info

### PR DESCRIPTION
**Pull request by tl2215689**
Request to update gocp token information data

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Please re-submit the TPT transfer link on [Commit changes].

**Comment by tl2215689** [comment]
已重新提交资料，请查验


 
---Original---
From: ***@***.***&gt;
Date: Fri, Sep 10, 2021 11:43 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] Add gocp token info (#3199)




 
Closed #3199.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tl2215689** [comment]
已重新提交资料，请查验


 
---Original---
From: ***@***.***&gt;
Date: Fri, Sep 10, 2021 11:43 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] Add gocp token info (#3199)




 
Please re-submit the TPT transfer link on [Commit changes].
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tl2215689** [comment]
我前几天提交了资料，请审核一下


 
---Original---
From: ***@***.***&gt;
Date: Fri, Sep 10, 2021 11:43 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] Add gocp token info (#3199)




 
Closed #3199.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
