### PR TITLE
Add SOD logo and info

### PR DESCRIPTION
**Pull request by medaliHm**
https://bscscan.com/tx/0x39cbafc2b1d105e19c3870ba6163f5156b41c239e6de417f8dcdd79c629d6ed9
https://bscscan.com/tx/0x3b6dc68356ac97c3060f52a4d88aa9639196843d07443fe3ebfa5d9c845e1965

### CODE REVIEW

**Comment by medaliHm** [comment]
This is to add SOD  logo and info in TokenPocket , donation done 
https://bscscan.com/tx/0x39cbafc2b1d105e19c3870ba6163f5156b41c239e6de417f8dcdd79c629d6ed9
https://bscscan.com/tx/0x3b6dc68356ac97c3060f52a4d88aa9639196843d07443fe3ebfa5d9c845e1965

**Comment by opera0001** [comment]
It is detected that there may be a switch to control token circulation, and the rate can be adjusted. Please explain.

**Comment by medaliHm** [comment]
we control token circulation so we can do burns which lower the supply and the rate is we can turn off taxes when ready to apply to tier 1 exchanges

**Comment by opera0001** [comment]
Sorry, this does not conform to our audit specification. If you can give up the control right of token contract, it can be included normally.

**Comment by opera0001** [comment]
After waiting for 2 days, you still haven't replied, so please help you close the order first. If you need to continue communication, please go to https://github.com/TP-Lab/tokens/issues Initiate the topic, thank you.

**Pull request closed without merging**
