### PR TITLE
Add GCCB logo and info

### PR DESCRIPTION
**Pull request by kylincoin**
0x6390ed7f8105a32c42d66cb1981e73b4aff13de34504c7f73ce5a84d7a5b634c

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Please re-submit your files attached TPT transfer link on [Commit changes].

**Comment by kylincoin** [comment]
为什么还要重提？



---Original---
From: ***@***.***&gt;
Date: Mon, Aug 30, 2021 16:17 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] Add GCCB logo and info (#2916)




 
Please re-submit your files attached TPT transfer link on [Commit changes].
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
