### PR TITLE
Add SWAN22 logo and info

### PR DESCRIPTION
**Pull request by swan2211**
https://hecoinfo.com/tx/0xf571193b51fdb709f4572d77d1aa1ae2dc425c7be8d1b7f48d69c4f0693b2302

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3579750034

**Comment by sammvio** [comment]
Please refer to the tutorial, and re-submit your files in the correct format.

**Comment by swan2211** [comment]
hi,
good day  sir,
regarding about my submitted logo and info for my token  rejected, how to
contact your team for service and next step to do ,i haven't QQ to contact.

best regards

jiasutijiao ***@***.***> 于 2021年12月26日周日 15:12写道：

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
