### PR TITLE
Add VBN logo and info

### PR DESCRIPTION
**Pull request by gumu1572**
https://bscscan.com/tx/0x8af15987e6474a8481b6f2e51edef998a22d68b76b171a21658a7307f585b854

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3579750034

**Comment by sammvio** [comment]
Please submit the checksum address that includes uppercase and lowercase characters.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
