### PR TITLE
Add Beer Doge logo and info

### PR DESCRIPTION
**Pull request by beerdoge**
https://bscscan.com/tx/0xaeaf8e3c22c4ebdd45265b87e7164644396a3ec73db1ae5e784c82207734129c

### CODE REVIEW

**Comment by beerdoge** [comment]
please check again

**Comment by zhujiayu03** [comment]
Sensitive words in logo.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
