### PR TITLE
add PCH logo and info

### PR DESCRIPTION
**Pull request by jianme**
捐赠hash链接：https://bscscan.com/tx/0x17376a08b05f03251a71445e26febc042abaab60eaa614379dfb091724d4f1de

验证hash链接: https://bscscan.com/tx/0x4f30ae3fe79dd505b5b1e48c394e8a585a2b46a4b427843c751014d84adab2a9

### CODE REVIEW

**Comment by jianme** [comment]
就一个标准ERC20代币，不会有任何问题的

**Comment by opera0001** [comment]
It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

**Comment by jianme** [comment]
您好，这是我老板发的，我这没代码我也开源不了。我们是通过比特派钱包一键发币发的，如何验证？，所以安全性肯定是没问题的。我这都买了无数的TPT提交了无数个logo 了。

**Comment by opera0001** [comment]
You can contact the token issuer to request some data that can prove its security. Thank you. Since you have submitted the logo many times before, you should have followed our review guidelines, only in this way can it be included. Thank you.

**Comment by opera0001** [comment]
After not receiving your response for one day, the order needs to be temporarily closed. You can contact me through issues to continue this order.

https://github.com/TP-Lab/tokens/issues

**Comment by jianme** [comment]
我联系不上，我们就是通过比特派钱包发的。你要么通过要么给我退钱好吗？我们都交钱了不给通过，这么坑人么？将近500U的TPT，不是为了上传LOGO谁会捐钱给你？莫名其妙关了。

**Pull request closed without merging**
