### PR TITLE
Add TPT logo and info 

### PR DESCRIPTION
**Pull request by a87599633**
Sample

### CODE REVIEW

**Comment by opera0001** [comment]
One token logo submission per GitHub order, so please select one.

**Comment by a87599633** [comment]
0xbc470e3d506df49e3498dac3df57d9dbb746caa6   这个合约地址么



---- Replied Message ----
| From | ***@***.***> |
| Date | 03/27/2024 09:37 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [TP-Lab/tokens] Add TPT logo and info (PR #10464) |

One token logo submission per GitHub order, so please select one.

**Comment by a87599633** [comment]
Choose the red line



---- Replied Message ----
| From | ***@***.***> |
| Date | 03/27/2024 09:37 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [TP-Lab/tokens] Add TPT logo and info (PR #10464) |

One token logo submission per GitHub order, so please select one.

**Comment by a87599633** [comment]
> 每个 GitHub 订单提交一个令牌徽标，因此请选择一个。

I choose to add tpt logo and info

**Comment by opera0001** [comment]
Token contracts have the following functions without discarding control permissions:

1. Token transaction fees can be modified.
2. Transactions can be paused.
3. Blacklist and whitelist exist, which may be used in conjunction with anti-bot measures.

Therefore, you need to explain these functions to convince me that they are secure. Thank you.

**Comment by a87599633** [comment]
We're still deploying tests, and permissions will be cleared later

**Pull request merged**
