### PR TITLE
Add SONOFODGE logo and info

### PR DESCRIPTION
**Pull request by SonofDoge**
https://bscscan.com/tx/0xc87d5a464a19f68440af75bf6471bc92781914e13da082333c1d004f7fc65347

### CODE REVIEW

**Comment by zhujiayu03** [comment]
logo infringement, please resend your image

**Comment by SonofDoge** [comment]
My logo here: 

https://sonofdogecoin.com/wp-content/uploads/2021/08/sonofdogelogo-200-200.png or 
image

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
