### PR TITLE
Add AID logo and info

### PR DESCRIPTION
**Pull request by ysdang**
https://bscscan.com/tx/0x5ea06b3dc60a2052da9550cc42d1b210fc68df8de4bac8d28c78e7dbc0c58900
https://bscscan.com/tx/0x086ed2383425ff256a10471b61cbc78cb99cf48c666645c52d4a6061f8ac3524

### CODE REVIEW

**Comment by opera0001** [comment]
It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

**Comment by ysdang** [comment]
The contract code is already disclosed, please check again.

**Comment by opera0001** [comment]
It is detected that there is a function of tentative transaction. Please explain.

**Comment by ysdang** [comment]
The buytoken () method is used to count the sales of private placement before the token goes online and give rewards to the invitees.

**Comment by opera0001** [comment]
A function that can suspend transactions is detected, which will be risky.

**Comment by ysdang** [comment]
Our TOKEN has been airdropped. In order to prevent some people from adding liquidity in advance, we need such a function to control the start of the transaction.

**Comment by opera0001** [comment]
When will administrator privileges be discarded?

**Comment by ysdang** [comment]
After adding liquidity, the administrator permission will be waived!!!

**Pull request merged**
