### PR TITLE
Add GNT info and logo

### PR DESCRIPTION
**Pull request by GoldNeta**
https://bscscan.com/tx/0x42d5a10a3405b546a1286524774663198b1467ee32c060374c69d40ca8d424f1

https://bscscan.com/tx/0xc73abacc1a389587f85eaa9b165924bf1fc5c33fd784b625e90f155ef15d8d78

### CODE REVIEW

**Comment by opera0001** [comment]
It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

**Comment by GoldNeta** [comment]
token contract code is here: 
https://github.com/GoldNeta/gnttoken
Let us know if we still need to provide audit report

**Comment by opera0001** [comment]
Please verify it through bscscan, thank you.

**Comment by opera0001** [comment]
Sorry, you can verify it on Polygon. Thank you.

**Comment by opera0001** [comment]
After verification is completed, you can notify me through issues. The order needs to be temporarily closed.

https://github.com/TP-Lab/tokens/issues

**Pull request closed without merging**
