### PR TITLE
add MRP logo and info

### PR DESCRIPTION
**Pull request by mmm314coder**
https://bscscan.com/tx/0xf2cbe2e593fd97b97427288098f3e1ade804744ea9038d433085c814f6d2580f
https://bscscan.com/tx/0xf32d3b3da6d2f35c4d8677b1a38fc403e42168ea12be6d57381b3ddc637b62ed

### CODE REVIEW

**Comment by opera0001** [comment]
image
Hidden owner privileges are very dangerous.

**Comment by mmm314coder** [comment]
The first question is that the mint in the contract is a feature of our project. Mint is determined according to user needs or market needs. You can check the specific contract logic.
The second question is that we only have some subsidiary contracts that can be modified for the contract, which does not affect the specific rights and interests of the current contract to the user. It is to facilitate the community to do some expansion.
The third question is that the contract calls the external contract to inform the subsidiary contract that an event is triggered and do some data recording and some subsidiary logic processing, which does not affect the fairness of the contract and the rights and interests of users.
The above questions and all subsidiary contracts are now open source, and you can read the source code.

**Comment by opera0001** [comment]
The risk of hidden owner functions is very high, so it is necessary to provide a code security audit report from a reputable and reliable security company.

**Comment by mmm314coder** [comment]
Which auditing companies do you approve of? I can contact them.

**Comment by mmm314coder** [comment]
Do you recognize interfi audits?

**Pull request merged**
