### PR TITLE
Add YFS logo and info

### PR DESCRIPTION
**Pull request by SHJL252**
3000TPT: https://bscscan.com/tx/0x2c0a96ef242fe6613f44e1874b3c2d99154c1dffd1cf5c7ac6b291922691c7c1

{
 "name": "YFS",
 "website": "https://yfs.world",
 "description": "Highly decentralized and charity DeFi platform.",
 "explorer": "https://bscscan.com/address/0x9320e12a4B8c397E53D313122bCfbacc94Cc031b",
 "type": "BEP20",
 "symbol": "YFS",
 "decimals": 18,
 "status": "active",
 "id": "0x9320e12a4B8c397E53D313122bCfbacc94Cc031b"
}

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3579750034

**Comment by sammvio** [comment]
Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
