### PR TITLE
update bgar info

### PR DESCRIPTION
**Pull request by fsdajlkl**
如题

### CODE REVIEW

**Comment by fsdajlkl** [comment]
https://bscscan.com/tx/0x227bad71bc7fc36854cf7b0769910f38b69fbf8844cc65d91863792dfc1777f4

**Comment by guoxintongsam** [comment]
Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
