### PR TITLE
Token:newinu

### PR DESCRIPTION
**Pull request by werx111fds**
Token:newinu 

contract address: 0x2550b63d28fae53827ddabee1b1f4b6d67bd33 

precision:9

Newinu is a completely decentralized, point-to-point digital currency named after an endangered wild dog found in Papua New Guinea. New Guinea Singing INU ($newinu) is a deflationary meme coin with built-in ARF technology.

### CODE REVIEW

**Comment by werx111fds** [comment]
Token:newinu 

contract address: 0x2550b63d28fae53827ddabee1b1f4b6d67bd33 

precision:9

Newinu is a completely decentralized, point-to-point digital currency named after an endangered wild dog found in Papua New Guinea. New Guinea Singing INU ($newinu) is a deflationary meme coin with built-in ARF technology.

**Comment by werx111fds** [comment]
Token:newinu 

contract address: 0x2550b63d28fae53827ddabee1b1f4b6d67bd33 

precision:9

Newinu is a completely decentralized, point-to-point digital currency named after an endangered wild dog found in Papua New Guinea. New Guinea Singing INU ($newinu) is a deflationary meme coin with built-in ARF technology.

**Comment by zhujiayu03** [comment]
Please submit detailed token info.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
