### PR TITLE
Add THB logo and info

### PR DESCRIPTION
**Pull request by Shengqian-Zou**
https://bscscan.com/tx/0xd1ace84cddd00befabda1725ff5dc7d5c2b2826914a59ff223da1b06f1ffcc83

### CODE REVIEW

**Comment by opera0001** [comment]
There may be some risks if you do not give up your administrator rights.

**Comment by Shengqian-Zou** [comment]
> There may be some risks if you do not give up your administrator rights.

Can I just upload an logo please?

**Comment by Shengqian-Zou** [comment]
> There may be some risks if you do not give up your administrator rights.
 Do you means if do not give up the administrator rights, it can not upload the logo?

**Comment by Shengqian-Zou** [comment]
> There may be some risks if you do not give up your administrator rights.

I just want to upload the logo, pls help me, I have already transferred 3000TPT， Thank you very much!

**Comment by Shengqian-Zou** [comment]
> There may be some risks if you do not give up your administrator rights.

What is administrator rights means，do you mean contract open source?

**Comment by opera0001** [comment]
After 17 hours, we still haven't seen your change, so we need to close the order and resubmit the TPT donation. Now we need 30000 TPT donations. Please know.

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
