### PR TITLE
Add INF logo and info

### PR DESCRIPTION
**Pull request by WZ888FACAI**
INF is based on the HECO Ecological Chain.
trade id:0x21fdb23f39823a212697f1ea93764e6a01cc350ce0ed4b273323d79dcb0e14d4

### CODE REVIEW

**Comment by WZ888FACAI** [comment]
OK

**Comment by WZ888FACAI** [comment]
INF Submit logo

**Comment by guoxintongsam** [comment]
Please re-submit your files attached TPT transfer link on [Commit changes].

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Pull request closed without merging**
