### PR TITLE
add SingleDoge into and logo

### PR DESCRIPTION
**Pull request by DOUSENCAI**

### CODE REVIEW

**Comment by DOUSENCAI** [comment]
Sdoge

**Comment by DOUSENCAI** [comment]
Sdoge

**Review by DOUSENCAI — COMMENTED** [review]
is ok

**Comment by DOUSENCAI** [comment]
TPT Paid
https://bscscan.com/tx/0x47ed7e470fa41972eeee42a8cc0f114e1e9a5cdb9c91cdec7d482d5c61260bf9

**Comment by DOUSENCAI** [comment]
MARST:https://bscscan.com/tx/0x6b0abd31db821251a81b6e8edbfa524e0996f622716a82568d92230696d769a4
BSC

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Pull request closed without merging**
