### PR TITLE
update zkd contract address

### PR DESCRIPTION
**Pull request by jianme**
Due to the need of technology upgrade, we changed the zkd contract address, please help us merge it, thank you。

### CODE REVIEW

**Comment by opera0001** [comment]
image

The submitted content does not meet the standard requirements. Please make revisions.

**Comment by jianme** [comment]
Where does not meet the requirements, please point out. I remember the last time I submitted it like this.

**Comment by opera0001** [comment]
If you need to resubmit the logo for inclusion, please submit it according to the content in the JSON and logo. If you need to update the logo, you can send relevant information to the order.

**Comment by jianme** [comment]
I'm going to update the contract address because we did an upgrade. Both my json and logo are consistent, and my token has already donated TPT. I was in bsc before, and then migrated to the zk chain. I submitted it once and it was ok. Now I just change the contract address. Please help us to change it Down. I don't know which branch your zksync chain submission is in, so I submitted it to the master branch


Our token pool is two million, and the number of users is very large. We have always used the TP wallet, because the logo has donated TPT several times. We just changed the contract address now, and the project information website has not changed. Do you mean that I have to donate TPT again? I think it is very unreasonable, TP wallet is so short of money?


Old contract address: 0xAdB9eF74F7FeCC75d1c4a45b424819388310d405
New contract address: 0x80615f96EC3AB04E54FeB7465d646B3967319eBA


They are all zk chains, and the old one is no longer clear which branch to sync to. The way I submit it now is exactly the same as the way I migrated from bsc last time, but the address is changed. Thanks.





1131168468
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TP-Lab/tokens"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月14日(星期一) 中午11:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TP-Lab/tokens] update zkd contract address (PR #9667)





 
If you need to resubmit the logo for inclusion, please submit it according to the content in the JSON and logo. If you need to update the logo, you can send relevant information to the order.

**Comment by opera0001** [comment]
This has nothing to do with money; it's only a matter of rules.

**Pull request merged**
