### PR TITLE
Add MIC logo and info

### PR DESCRIPTION
**Pull request by manggigog**
https://bscscan.com/tx/0xd5f521acd5e84f5a63fcd954b8cee94426846870421a23decfc0db8f49cf2a94

### CODE REVIEW

**Comment by opera0001** [comment]
Abnormal token circulation, high risk!!!

**Comment by manggigog** [comment]
> 代币流通异常，高风险!!!

Please tell me what to do next?

**Comment by manggigog** [comment]
> Abnormal token circulation, high risk!!!

Please tell me what to do next?

**Comment by manggigog** [comment]
> Abnormal token circulation, high risk!!!

Now the token is in the pre-sale stage, and the trading function will be opened tomorrow. Please pass the application for the trouble icon
@opera0001

**Pull request merged**
