### PR TITLE
add metacap logo and info &  Ptiger logo and info

### PR DESCRIPTION
**Pull request by Betonone**
metacap link ： https://bscscan.com/tx/0xa3dfa1209b947fb153d60a6cf51a947bf2d0fa4445b5371026b1abed1c0cd147

### CODE REVIEW

**Comment by logobaoguo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by Betonone** [comment]
https://bscscan.com/tx/0xabe0bcdaf91dabf1111bb93e5758ced6a003d1b754c137494b501c3f19a78dd8

**Comment by sammvio** [comment]
Please refer to the tutorial, and re-submit your files in the correct format.

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
