### PR TITLE
Add NFLA info and logo

### PR DESCRIPTION
**Pull request by aasasas123**
3000TPT: https://bscscan.com/tx/0x4c80ef60c7f889e54616bfbc6252a6ed9fad5049ba7691d4ca57c4e5bc01ff9e
bsc: https://bscscan.com/tx/0xe9a1e4745f97d42e861318011ad8b749cee8b1221cb5a261c06fbac0d1f02f62

### CODE REVIEW

**Comment by tiaojiaotubiaobaoguo** [comment]
代提交logo，24小时内包过，加QQ：2980874528

**Comment by sammvio** [comment]
Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
