### PR TITLE
Add CatMoon logo and info

### PR DESCRIPTION
**Pull request by catgitmoon**
https://bscscan.com/tx/0x2160331b76b1236c78856ca2279271ac40ce4a23dc16b14c2ccc2ae243910211

### CODE REVIEW

**Comment by tiaojiaotubiaobaoguo** [comment]
代提交logo，24小时内包过，加QQ：2980874528

**Comment by sammvio** [comment]
Please submit the checksum address that includes uppercase and lowercase characters.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
