### PR TITLE
Add UFC logo and info

### PR DESCRIPTION
**Pull request by king0012-star**

### CODE REVIEW

**Comment by king0012-star** [comment]
100TPT 已经支付，麻烦审核下。https://bscscan.com/tx/0xd3acebda262c2a90b05e7b01777a906b4376b6eba445e44012ba7ae2f39c2dac

**Comment by king0012-star** [comment]
100TPT has been paid, please review it, thank you.
https://bscscan.com/tx/0xd3acebda262c2a90b05e7b01777a906b4376b6eba445e44012ba7ae2f39c2dac

**Comment by zhujiayu03** [comment]
Please add token info

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Pull request closed without merging**
