### PR TITLE
Add Linea logo and info

### PR DESCRIPTION
**Pull request by stuniii**
https://bscscan.com/tx/0x24a983c1cbdbba27869bd3c13548dab69e97854e68c01be67a759333cb42ae4d

### CODE REVIEW

**Comment by opera0001** [comment]
In the absence of relinquishing token control authority, various control permissions exist. Please explain their respective functions.

**Comment by stuniii** [comment]
> 在不放弃代币控制权的情况下，存在各种控制权限。请解释一下它们各自的作用。


The team is discussing the final tax rate, and owner rights will be given up once the project is launched.

**Comment by stuniii** [comment]
> In the absence of relinquishing token control authority, various control permissions exist. Please explain their respective functions.


The team is discussing the final tax rate and owner rights will be waived once the project starts.

**Comment by stuniii** [comment]
> > In the absence of relinquishing token control authority, various control permissions exist. Please explain their respective functions.
> 
> The team is discussing the final tax rate and owner rights will be waived once the project starts.


Or tell me what permissions I need to give up to upload via logo.

**Comment by stuniii** [comment]
> In the absence of relinquishing token control authority, various control permissions exist. Please explain their respective functions.

Single purchase limit Purchase limit: 99999.99999999999 Linea
Sale limit: 99999.99999999999 Linea
The maximum currency holding limit for a single wallet is 99999.99999999999 Linea
Kill block 2 block
Transfer tax rate
0%
Marketing Wallet 0x00...0dEaD
Pot USDT
Exchange Pancakeswap
Liquidity pool address 0xaF...a3C31

**Pull request merged**
