### PR TITLE
Add TP logo and info

### PR DESCRIPTION
**Pull request by peopleswap**
TPT Txn Hash - https://bscscan.com/tx/0xe8e0c9c6d3a69d7ecdaa9d3751d76a5ce891b95dd787ddf77db00c20bac7fc7f
BNB Txn Hash - https://bscscan.com/tx/0xc161cb1b267aaf524c9caede059d834dbd366ebf4b6b9d057b96c9ba9441556f

### CODE REVIEW

**Comment by opera0001** [comment]
1. Not relinquishing ownership
2. Blacklist function may exist

**Comment by peopleswap** [comment]
@opera0001 Please let us know how we can do for this? Can we resubmit？

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
