### PR TITLE
ADD NATD Token

### PR DESCRIPTION
**Pull request by Daxiongzhang**
transfer : https://bscscan.com/tx/0xa70d65d53d3f2a1c944fd568c4f2a0e08ae93bae934aaa261ca6efcd73eb9f85
verify : https://bscscan.com/tx/0x8fe1acebac320678f919bc729c272f0aeab0363624922ea9e574954f64b1b54e

### CODE REVIEW

**Comment by Daxiongzhang** [comment]
Reach an agreement with the community and abstain after the official launch

**Comment by Daxiongzhang** [comment]
Reach an agreement with the community and abstain after the official launch

**Comment by opera0001** [comment]
What is the purpose of increasing token issuance?

**Comment by opera0001** [comment]
Two days have passed without receiving your response, so the order needs to be closed. You can contact me through the issues section at the following link:

https://github.com/TP-Lab/tokens/issues

**Pull request closed without merging**
