### PR TITLE
Add logo for APO

### PR DESCRIPTION
**Pull request by Apolloplan2022**
TPT:https://bscscan.com/tx/0x890ba2d553e1b60879130b239430f1b274e72350b4811d57c6d8fb7aa51a9e99
BNB:https://bscscan.com/tx/0xbd5908054167b3f36b17f4d7d43b7c7e234ab651055017d2ed65fd2c54e4fc02
PS: There are two internal permissions in the contract, one is _eb and the other is _wha. _eb is a special permission that is stripped from the Owner permission to prevent arbitrage robots at opening, and _wha is the whitelist setting permission (whitelist free of fee charge), we will abandon these permissions as soon as possible after the deployment is completed

### CODE REVIEW

**Comment by Apolloplan2022** [comment]
Dropped the ownership of the contract at https://bscscan.com/tx/0x7ae7b6bd49e824fe6a96053d84f2990cb6275440e345c783f2f2c8e3b19ce48e

**Comment by opera0001** [comment]
There are hidden owner permissions that may set up functions such as token increment. Please check

**Comment by Farecosystem** [comment]
dropped at https://bscscan.com/tx/0x599eaa52157517d276449841cfb5952a1c5924ee0e30a1e621ab40b8787e0297
pls kindly check

**Comment by Apolloplan2022** [comment]
> There are hidden owner permissions that may set up functions such as token increment. Please check

already dropped at https://bscscan.com/tx/0x599eaa52157517d276449841cfb5952a1c5924ee0e30a1e621ab40b8787e0297
please kindly check
eb

**Comment by Apolloplan2022** [comment]
_wha permission dropped at https://bscscan.com/tx/0xa906dd4dda1108e6e56a2154b7017654910008bbde113ca340e0d7c087f73251
So now there are no hidden permissions, please check~

**Pull request merged**
