### PR TITLE
Add TOD token

### PR DESCRIPTION
**Pull request by nanshun2020**
add TonDao(TOD) token
BSC - TOD - 0x5e64D48b2E33B181Aa5D8aeAdB4939b74085342f -
https://bscscan.com/tx/0xc68e5b63242a6dfe40555077a11d1e9f12fd9b2e94cdd2e5214f8591a068f576

Uplink Data ：       https://bscscan.com/tx/0x89dcfcadcfa146e71ffaef5db6620ab23ba840b49eb8b140b851d38d0da03a7b

### CODE REVIEW

**Comment by opera0001** [comment]
Without relinquishing control authority over the token contract, the setting for increasing token issuance exists, which poses a higher risk. Therefore, it is necessary to provide an explanation for this.

**Comment by nanshun2020** [comment]
This token (TOD ) contract will be resent, administrator permissions will
be removed, and the contract address will change. Can I continue to apply
add token to TP wallet? Thank you

opera0001 ***@***.***> 於 2023年10月27日週五 上午9:42寫道：

**Comment by nanshun2020** [comment]
new TOD token address :

0x5e64D48b2E33B181Aa5D8aeAdB4939b74085342f

nan shun ***@***.***> 於 2023年10月27日週五 下午12:41寫道：

**Comment by nanshun2020** [comment]
BSC - TOD - 0x5e64D48b2E33B181Aa5D8aeAdB4939b74085342f -
https://bscscan.com/tx/0xc68e5b63242a6dfe40555077a11d1e9f12fd9b2e94cdd2e5214f8591a068f576

Uplink Data ：       https://bscscan.com/tx/0x89dcfcadcfa146e71ffaef5db6620ab23ba840b49eb8b140b851d38d0da03a7b

**Review by nanshun2020 — COMMENTED** [review]
Change the token address to:0x5e64D48b2E33B181Aa5D8aeAdB4939b74085342f

**Pull request merged**
