### PR TITLE
Add EVB logo and info

### PR DESCRIPTION
**Pull request by Swain-Xie**
TRON - EVB - TQnpQtnkcyiUS6hMjJgzR9XHfFEgNtk7mM -
https://bscscan.com/tx/0x039860e7441e2d43da320ddc741929ddc12398f9dea52b2833139ff7a67d19ec

### CODE REVIEW

**Comment by Swain-Xie** [comment]
请尽快审核，谢谢

**Comment by guoxintongsam** [comment]
Tron token logo upload is not allowed for now.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
