### PR TITLE
ADD PADX logo and info

### PR DESCRIPTION
**Pull request by meiguodada**
https://bscscan.com/tx/0xc4f0ee12f871d4d699e06fb91754add82ef2a77b78bc0e7043ebe0a227768aba

### CODE REVIEW

**Comment by Darkwar2021** [comment]
链游开发，过审logo、白皮书中英文制作、专业解决代币问题，详细咨询飞机：dappsoft

**Review by bscpadx — CHANGES_REQUESTED** [review]
{ 
"name": "Puzzle And DragonsX",
"website": "https://www.PuzzleAndDragonsX.com",
"description": "PADX is a yield-generating deflationary charitable cryptocurrency that runs on Binance Smart Chain. It rewards holders through reflections by taxing transactions. ",
"explorer": "https://bscscan.com/token/0x2DfB898059bd7E3d1030da4ce22Eb90a6f1E0C2A",
"type": "BEP20",
"symbol": "PADX",
"decimals": 9,
"status": "active",
"id": "0x2DfB898059bd7E3d1030da4ce22Eb90a6f1E0C2A"
}

**Comment by meiguodada** [comment]
{
"name": "Puzzle And DragonsX",
"website": "https://www.PuzzleAndDragonsX.com",
"description": "PADX is a yield-generating deflationary charitable cryptocurrency that runs on Binance Smart Chain. It rewards holders through reflections by taxing transactions. ",
"explorer": "https://bscscan.com/token/0x2DfB898059bd7E3d1030da4ce22Eb90a6f1E0C2A",
"type": "BEP20",
"symbol": "PADX",
"decimals": 9,
"status": "active",
"id": "0x2DfB898059bd7E3d1030da4ce22Eb90a6f1E0C2A"
}

**Review by bscpadx — COMMENTED** [review]
{
"name": "Puzzle And DragonsX",
"website": "https://www.PuzzleAndDragonsX.com",
"description": "PADX is a yield-generating deflationary charitable cryptocurrency that runs on Binance Smart Chain. It rewards holders through reflections by taxing transactions. ",
"explorer": "https://bscscan.com/token/0x2DfB898059bd7E3d1030da4ce22Eb90a6f1E0C2A",
"type": "BEP20",
"symbol": "PADX",
"decimals": 9,
"status": "active",
"id": "0x2DfB898059bd7E3d1030da4ce22Eb90a6f1E0C2A"
}

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:2980874528

**Comment by sammvio** [comment]
Please refer to the tutorial, and re-submit your files in the correct format.

**Pull request closed without merging**
