### PR TITLE
Add DWT info

### PR DESCRIPTION
**Pull request by Johnson198593**

### CODE REVIEW

**Comment by giki0318** [comment]
According to the DAO, the donation amount for a logo update has been updated to 30,000 TPT. [Click here for Details](https://snapshot.org/#/tptdao.eth/proposal/0x781abc1ade2ebd082aec4f57b7199d472a2b2850b3df46c8ec37e3b6a1a243c2)[](https://github.com/TP-Lab/tokens#how-to-submit)

**Comment by TokenPocket-JAN** [comment]
Speed ​​up the trial. Please reply to the email if you need.
QQ112831047

**Comment by opera0001** [comment]
No logo file of 256x256 pixels was submitted

**Comment by opera0001** [comment]
We haven't seen the supplementary TPT donation hash value and logo file after 22 hours, so we temporarily close the order and need to resubmit it after you supplement the TPT quota. Thank you for your support of tokenpocket.

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
