### PR TITLE
Add GAC logo and info

### PR DESCRIPTION
**Pull request by zhangshoushu**
https://hecoinfo.com/tx/0x611dc20e90d7bb19d4f98a85709759913ca767b4ba5294e50df14aa3c7dbc36a

### CODE REVIEW

**Comment by zhangshoushu** [comment]
Add OKC logo and info：
https://hecoinfo.com/tx/0xb9927b61d86f7ee0df6fded5086431df285a0e91f23dd4537a191e70c1c91560

**Comment by zhujiayu03** [comment]
Please submit your files to heco folder

**Comment by zhangshoushu** [comment]
> 将您的文件提交到 heco 文件夹

It's submitted in heco

**Comment by zhangshoushu** [comment]
> Please submit your files to heco folder

已经重新提交了，非常感谢您的提醒，可以帮忙审核吗？新的提交：dd OKC logo and info #1083

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Pull request closed without merging**
