### PR TITLE
ADD-BDD logo and info

### PR DESCRIPTION
**Pull request by gsqtoken**
原来是PR#5408重新上传新的logo请求审核，sample

### CODE REVIEW

**Comment by opera0001** [comment]
1. The new logo uses the icon of Kung Fu Panda, which will cause infringement
2. There are no other operations after the token is issued, so the security cannot be verified
3. No token capital flow pool found
Thank you very much for being able to re submit GitHub after adjustment so soon. Please re submit the logo application after modification or optimization again. Thank you for your support for tokenpocket

**Comment by gsqtoken** [comment]
我朋友让我帮忙问下，为什么你们tp钱包的资产价值不显示，在bitkeep钱包都显示，还说好几个钱包都显示，每天都有交易，而且持币地址也达到了，他们说都有按你的要求操作还是无法显示资产价格和价值。他的项目合约地址：0xD71fFc69902264E6240f84EEd8532457fdD9381F
 名字叫gsq，麻烦您帮忙寻找一下什么问题？

opera0001 ***@***.***> 于2022年2月19日周六 00:29写道：

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
