### PR TITLE
Add WETN logo and info

### PR DESCRIPTION
**Pull request by cc0812**
https://bscscan.com/tx/0x1529a19e638b7e76507a25a85649392262f670349a963bd245bf77ccfcce3031

### CODE REVIEW

**Comment by cc0812** [comment]
https://bscscan.com/tx/0xd19a0a0e4ffbb0cc1257620bb46f71ee55e9264bba94afb6d533260db59d23d0

**Comment by opera0001** [comment]
image
The submitted file is not saved in the BSC directory, please adjust it again.

There are not enough tpt donations

**Comment by cc0812** [comment]
If I don’t do it, can I return the TPT?


湖南达凯网络科技有限公司
测试：陈多胜
手机：17336619957
***@***.***
 
From: opera0001
Date: 2023-03-03 09:17
To: TP-Lab/tokens
CC: cc0812; Author
Subject: Re: [TP-Lab/tokens] Add WETN logo and info (PR #9076)

The submitted file is not saved in the BSC directory, please adjust it again.
There are not enough tpt donations

**Comment by cc0812** [comment]
https://bscscan.com/tx/0x1529a19e638b7e76507a25a85649392262f670349a963bd245bf77ccfcce3031
https://bscscan.com/tx/0xd19a0a0e4ffbb0cc1257620bb46f71ee55e9264bba94afb6d533260db59d23d0
https://bscscan.com/tx/0xdf9e93a49f9a0c5c839878afa65884db47891b51fc7a4cc74e47f1dbf97a45bd
https://bscscan.com/tx/0x9d2b07c78e3a2fc36deb0ffcb44f1fb60d7181b7cd15f86723c62300a4f1e698

**Pull request merged**
