### PR TITLE
ADD FEB logo and info

### PR DESCRIPTION
**Pull request by qww530**
https://bscscan.com/tx/0xa0502d0ae23a224b621f0126fdcf846786197e025cca367089b9cfea0169ce69

### CODE REVIEW

**Comment by tiaojiaotubiaobaoguo** [comment]
代提交logo，24小时内包过，加QQ：2980874528

**Comment by sammvio** [comment]
Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token

**Comment by qww530** [comment]
Respect of the official staff hello:
Already submitted tokens, bother to review, hard ~ thank you ~







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TP-Lab/tokens"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月26日(星期五) 晚上9:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TP-Lab/tokens] ADD FEB logo and info (PR #4122)





 
Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
