### PR TITLE
Add TeslaBot logo and info

### PR DESCRIPTION
**Pull request by qianlai521**
https://bscscan.com/tx/0x8197ba223b5a8f0e340d304dbdf9f017558db3ea81c0c252e3fff69c33c43e37
https://bscscan.com/tx/0x1e87ff110da63f410be7c9fb22ecfebc3e1fe19a952951d7773
replace https://github.com/TP-Lab/tokens/pull/7320

### CODE REVIEW

**Comment by qianlai521** [comment]
之前的图标侵权，已重新更换代币及图标
The previous icon infringed, and the token and icon have been replaced again

**Comment by qianlai521** [comment]
It hasn't been launched yet. There's no holder. Wait for the icon to be

**Comment by qianlai521** [comment]
> 代币流通率太高，达到51%。请解释一下情况。

It hasn't been launched yet. There's no holder. Wait for the icon to be

**Comment by qianlai521** [comment]
Administrative rights have been lost

**Comment by opera0001** [comment]
Is there any direct relationship between logo display and rate?

**Comment by qianlai521** [comment]
> Is there any direct relationship between logo display and rate?

Bonus contract, if not sold, dividends will be accumulated, so the tax becomes extremely high, the contract will be automatically restored after a sale, currently no management authority, please review

**Comment by qianlai521** [comment]
Many attempts have been made and the buying and selling tax rate is normal.

**Pull request merged**
