### PR TITLE
Add ZBTC logo and info

### PR DESCRIPTION
**Pull request by huazai1699**
TPT交易哈希：https://bscscan.com/tx/0xb46153605d665c7f38e39989a7a0714ff85e957661f980a07dded31f91d41c37
步骤5验证哈希：https://bscscan.com/tx/0x6c4804a77928bd5d0273f7dc19100a68200f41e5f112a6f763286fef0274c106

### CODE REVIEW

**Comment by opera0001** [comment]
The hash value and #6834 link submitted are the same, please check. If we find that someone else's link is stolen, we will pull the GitHub account into the blacklist, and the submitted token will not be included.

**Comment by sduakh** [comment]
https://bscscan.com/tx/0xa99299ca80e418a48a83d23a00fbf05d66d1d8f0ccb52b974505d3aacbac4d6

**Comment by huazai1699** [comment]
TPT交易哈希：https://bscscan.com/tx/0xb46153605d665c7f38e39989a7a0714ff85e957661f980a07dded31f91d41c37
步骤5验证哈希：https://bscscan.com/tx/0x6c4804a77928bd5d0273f7dc19100a68200f41e5f112a6f763286fef0274c106

**Comment by huazai1699** [comment]
This is my submission

**Comment by huazai1699** [comment]
I can provide any evidence

**Pull request merged**
