### PR TITLE
add logo and info

### PR DESCRIPTION
**Pull request by dagegehash**
https://bscscan.com/tx/0x7b0945f539a0a061580f8dd94398318b4945f200214cd5c288401459eb42c2ea
https://bscscan.com/address/0x8639c37d43b1FDf61F8B56B133c01f563D7F1f8e#code

### CODE REVIEW

**Comment by dagegehash** [comment]
https://bscscan.com/tx/0xa5164594bd71033fc9bf7c493cb75ed4fa1b226ac596f1eb595e89ad3cc3a304

**Comment by dagegehash** [comment]
This is the transaction Tx that was unsuccessful in submitting the token DOE last year. You told me that I can use this transaction Tx in the future
https://bscscan.com/tx/0xa5164594bd71033fc9bf7c493cb75ed4fa1b226ac596f1eb595e89ad3cc3a304

**Comment by dagegehash** [comment]
Add MGC logo and info
transaction Tx
https://bscscan.com/tx/0x0552c378be0524208fca4ed2dd99abb898b3ca7dba4a9f95d2f1f92a4bc73cdc
The contract code has been open sourced
https://bscscan.com/address/0x33f3470bD66653598b09060F3d4780B9054fa9dF#code

**Comment by dagegehash** [comment]
Add DFH logo and info
transaction Tx
https://bscscan.com/tx/0x16774c9ef203bbebce4fe5b7a57cebefd5cb5388d538082bffaa636daa60c582
The contract code has been open sourced
https://bscscan.com/address/0x0CAd9EFb503144fC4e7F507CC612E71313877fCF#code

**Comment by opera0001** [comment]
A github account can only submit one order at a time, so you need to submit a total of 3 orders.

https://bscscan.com/tx/0xa5164594bd71033fc9bf7c493cb75ed4fa1b226ac596f1eb595e89ad3cc3a304
https://bscscan.com/tx/0x7b0945f539a0a061580f8dd94398318b4945f200214cd5c288401459eb42c2ea
The number of these two hashes does not meet the requirements, and this hash has been used historically.

**Comment by dagegehash** [comment]
I will resubmit the latter two, please help me to review the first token, thank you

**Comment by opera0001** [comment]
After the audit is completed, you can notify me through issues and I will handle it for you then. Thank you.

https://github.com/TP-Lab/tokens/issues

**Pull request closed without merging**
