### PR TITLE
add kic logo and info

### PR DESCRIPTION
**Pull request by xwd1314191**
KIC：
BSC—KIC—0x74b3ff7051d25a263beb01faed8b2694549aa285 https://bscscan.com/tx/0xa01139f6a1401f6e2a8fc0adfde27f0a229e0ae19ad0066992a14e648a28efc2

记录https://bscscan.com/tx/0xf92b6e3674a6d2042dd757f3efcbdb1eda111e06bcf7ee311982070d676858f1

### CODE REVIEW

**Comment by xwd1314191** [comment]
0xf92b6e3674a6d2042dd757f3efcbdb1eda111e06bcf7ee311982070d676858f1

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

The token cannot be sold all at once. This setting must be clearly explained; otherwise, users might report it as an unsellable token.

**Comment by xwd1314191** [comment]
每次可以出售90%

**Comment by xwd1314191** [comment]
每次可以出售总量的90%

**Pull request merged**
