### PR TITLE
Add BOC logo and info

### PR DESCRIPTION
**Pull request by TATA12github**
https://bscscan.com/tx/0xa8a91eb803caa2fe18b076c2adebdba62a07467f9539dec62846239ab6021685?utm_source=tokenpocket

### CODE REVIEW

**Comment by TATA12github** [comment]
已经提交，请审核。
https://bscscan.com/tx/0xa8a91eb803caa2fe18b076c2adebdba62a07467f9539dec62846239ab6021685?utm_source=tokenpocket

**Comment by TATA12github** [comment]
Already submitted, please review.

https://bscscan.com/tx/0xa8a91eb803caa2fe18b076c2adebdba62a07467f9539dec62846239ab6021685?utm_source=tokenpocket

**Comment by opera0001** [comment]
https://bscscan.com/token/0x219eb2e9f45e662e3AC76FA9153302A70823115f
image

Token contract exception, please check.

image

The submitted file is not saved in the BSC directory, please adjust it again.

**Comment by TATA12github** [comment]
@opera0001 Table of contents has been adjusted. Please check, thank you so much.

**Comment by TATA12github** [comment]
@opera0001 The token contract is abnormal. What is the abnormality? Please help point it out so that we can correct it. Thank you very much.

**Comment by TATA12github** [comment]
@opera0001  The contract anomaly has been adjusted. Please review it. Thank you very much.

**Comment by TATA12github** [comment]
@opera0001 If you still have any questions, please point them out, thank you very much!

**Comment by opera0001** [comment]
The submitted contract address seems to be using a very outdated code approach, and it is not a standard token. Please double-check.

**Comment by TATA12github** [comment]
@opera0001 The new contract has been updated and a relatively new version is used. Please review it. Thank you very much! https://bscscan.com/token/0xA5C8C9C3c44Fe52D12c8360a643d7A1466cB5564

**Pull request merged**
