### PR TITLE
Add Logo  ALVN and info 

### PR DESCRIPTION
**Pull request by L2b2n**
https://github.com/AlvareNet/tokens/commit/a1b30748d452b9cc66d6c845098f68d28d593f65

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Please donate 3000 TPT as required and submit the transfer link on [Commit changes].

**Comment by L2b2n** [comment]
https://bscscan.com/tx/0x2b7ff2a0d157dbd4ce220bfd83129bd5e38980148d82d8361a576e3efe162933

It payd

**Comment by L2b2n** [comment]
Why Closed ???

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
