### PR TITLE
Add Hero Dog logo and info

### PR DESCRIPTION
**Pull request by BIGsharkX**
1000tpt:https://hecoinfo.com/tx/0x233a89d3468285fb19d36450f2a21a415f130fcc6375ff46884274d4992dd5d7

### CODE REVIEW

**Review by BIGsharkX — COMMENTED** [review]
1

**Comment by guoxintongsam** [comment]
Please re-submit these tokens separately and attached the TPT transfer link on [Commit changes].

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
