### PR TITLE
Add TCM logo and info

### PR DESCRIPTION
**Pull request by LittleTigerbsc**
TCM is a hyper-deflationary DeFi token that runs on the Binance Smart Chain. TCM has a benign ecological pillar, where high-quality digital currency assets can be obtained and a new diversified decentralized transaction network has been established.
https://bscscan.com/tx/0x0a8ddb7ff5a2640d3548824ada85491b819b7a7fba07cb5f0701cf0c34aa9532

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Please re-submit your files attached to two TPT transfer links on [Commit changes].

**Comment by LittleTigerbsc** [comment]
请帮忙审核通过头像申请，谢谢



---Original---
From: ***@***.***&gt;
Date: Mon, Aug 30, 2021 11:59 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] Add TCM logo and info (#2878)




 
Closed #2878.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LittleTigerbsc** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TP-Lab/tokens"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月30日(星期一) 中午11:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TP-Lab/tokens] Add TCM logo and info (#2878)





 
Please re-submit your files attached to two TPT transfer links on [Commit changes].
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LittleTigerbsc** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TP-Lab/tokens"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月30日(星期一) 中午11:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TP-Lab/tokens] Add TCM logo and info (#2878)





 
Closed #2878.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Pull request closed without merging**
