### PR TITLE
Add CANTO logo and info

### PR DESCRIPTION
**Pull request by 666bernerslee**
5w tpt 转账哈希：https://bscscan.com/tx/0x880ba4cc45fc3f34379c343b3f7c927949738ee53c5420737d8ba6153f0bf478 
验证哈希：https://bscscan.com/tx/0x39dc402ca26d778f94991b3fcf76d5bb4d481ad1c284753312a3cd5ea5dd2ffe

### CODE REVIEW

**Comment by opera0001** [comment]
Detected the presence of a hidden owner function in the contract, which is a highly dangerous configuration.

**Comment by opera0001** [comment]
Since we haven't received a response or any changes from you in the past 2 days, we will need to close the order. The donated hash value can still be utilized in future orders. Feel free to contact me through the issues section:

https://github.com/TP-Lab/tokens/issues

**Comment by 666bernerslee** [comment]
"lockTheSwap" is set up to prevent excessive slippage when exchanging tokens in the pool during a sell, and this method has been widely used in the past two years with no centralized control. Regarding external method calls, it is evident in the contract that the control of external contracts is entirely governed by the current contract. The TokenDistributor contract is only used for token transfer and has no other methods. In mainstream dividend token contracts, if direct transfers are not used via an external contract, decentralized exchanges cannot support continuous exchanges, leading to transaction failures. Therefore, the method of transferring dividend tokens via an external contract has been adopted to meet the related requirements. This method has been in use for over a year, representing a mature and common practice in the industry. It is hoped that this method will be given special attention during contract security testing and that the associated risk warnings related to this method will be removed.

**Comment by 666bernerslee** [comment]
> Since we haven't received a response or any changes from you in the past 2 days, we will need to close the order. The donated hash value can still be utilized in future orders. Feel free to contact me through the issues section:
> 
> https://github.com/TP-Lab/tokens/issues

"lockTheSwap" is set up to prevent excessive slippage when exchanging tokens in the pool during a sell, and this method has been widely used in the past two years with no centralized control. Regarding external method calls, it is evident in the contract that the control of external contracts is entirely governed by the current contract. The TokenDistributor contract is only used for token transfer and has no other methods. In mainstream dividend token contracts, if direct transfers are not used via an external contract, decentralized exchanges cannot support continuous exchanges, leading to transaction failures. Therefore, the method of transferring dividend tokens via an external contract has been adopted to meet the related requirements. This method has been in use for over a year, representing a mature and common practice in the industry. It is hoped that this method will be given special attention during contract security testing and that the associated risk warnings related to this method will be removed.

**Pull request closed without merging**
