### PR TITLE
Add ORC logo and info

### PR DESCRIPTION
**Pull request by oracledaox**
https://bscscan.com/tx/0xaa518dab6fca3c42959c541bbc387d13bd71f6fb8b222cefc24dd2549ac515b9 https://bscscan.com/tx/0xfd167ebe94a73b96d3f64ed8e960b78e4f92ce033173a78ff6db6cb27a549980

### CODE REVIEW

**Comment by opera0001** [comment]
A setting that suspends the circulation of tokens is detected, please explain what it does, thank you.

**Comment by oracledaox** [comment]
we are launched IDO now for one month period , so we not allow transfer at the moment .After IDO period (by october 26), our token transfer will be enabled .

**Comment by oracledaox** [comment]
Hi opera001 , 

May I know the status of this request?is this approved?

**Comment by oracledaox** [comment]
hi regarding the token on-chain info , is that TP will actively to grab the update from contract , am i right?

**Comment by oracledaox** [comment]
I 've provide website detail  in json file .

{ 
"name": "ORACLE DAO TOKEN",
"website": "https://oracle-dao.com",

}

**Comment by oracledaox** [comment]
hi opera001 ,
1）regarding the token on-chain info , is that TP will actively to grab the update from contract , am i right?
2）how to update token social profile?

**Pull request merged**
