### PR TITLE
Add BabyDogeCoin logo and info

### PR DESCRIPTION
**Pull request by KKBabyDoge**
HECO-BabyDoge-0xe6801928061cdbe32ac5ad0634427e140efd05f9-https://bscscan.com/tx/0xb6c0cc28c10aba076c2eb2134f6d9d66ddf3f9d225bc780dd79e22e917893049

### CODE REVIEW

**Comment by KKBabyDoge** [comment]
BSC-Galaxy Heroes Coin-0x683fae4411249Ca05243dfb919c20920f3f5bfE0-https://bscscan.com/tx/0x5f0f7d621c30d962749d6faae3b1839e1acdb9731df421d1f5e3656fa8f39c0d

**Comment by guoxintongsam** [comment]
Please re-submit these tokens separately and attached the TPT transfer link on [Commit changes].

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
