### PR TITLE
Add AILP logo and info

### PR DESCRIPTION
**Pull request by OJBK77**
https://bscscan.com/tx/0x12cad1ec75a4a84c576f56215216dde9b90509184d4e29467ae86bce33589664

### CODE REVIEW

**Comment by OJBK77** [comment]
Dear, please create the logo for AILP token and add the info, thanks

**Comment by opera0001** [comment]
It has been observed that the purchase fees for the token are exceptionally high. Please provide details regarding this situation.

**Comment by OJBK77** [comment]
> It has been observed that the purchase fees for the token are exceptionally high. Please provide details regarding this situation.

Before the AILP is destroyed to 524W, members outside the community are prohibited from purchasing AILP tokens. AILP community members can only receive AILP token rewards by participating in the "Twelve Constellations" through www.ailp.link. This is a joint decision of the community!

**Comment by OJBK77** [comment]
> 据观察，代币的购买费用非常高。请提供有关这种情况的详细信息。

When the destruction reaches 5.24 million, the transaction fee required for purchase will be adjusted to 0

**Pull request merged**
