### PR TITLE
Add CP logo and info

### PR DESCRIPTION
**Pull request by ddqxx**
name	"communist party"
website	"https://0.plus/joinchat/LyhlJzB05XowYWRl"
description	"There is no value, only commemorative significance."
explorer	"https://hecoinfo.com/token/0x0015Ac41EeE3Fc017Fc04b7C20dFfF2F135E9466"
type	"HECO"
symbol	"CP"
decimals	18
status	"active"
id	"0x0015Ac41EeE3Fc017Fc04b7C20dFfF2F135E9466"
100TPT 的交易ID链接：https://hecoinfo.com/tx/0x3073ce4f705e6e1223ccca315f4e1155ac0aa3865431f7f6d9da4d86dbc41c7d

### CODE REVIEW

**Comment by zhuroujuan** [comment]
违法相关法律法规

**Comment by zhujiayu03** [comment]
Rejected

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
