### PR TITLE
add logo and info

### PR DESCRIPTION
**Pull request by logoWen**
0x5b60322628326e07514515d85b01c99e00c9f7256b2af930a3a4137867dd79e6
0x90d15970881598fb5f4b7b8aacf328809d2af33a8aa42496d1c931bc7aa75ec3

### CODE REVIEW

**Comment by logoWen** [comment]
https://bscscan.com/tx/0x5b60322628326e07514515d85b01c99e00c9f7256b2af930a3a4137867dd79e6

https://bscscan.com/tx/0x90d15970881598fb5f4b7b8aacf328809d2af33a8aa42496d1c931bc7aa75ec3

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Comment by logoWen** [comment]
为什么TP钱包LOGO还是不显示

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by logoWen** [comment]
是要删除后，重新提交吗？

**Pull request merged**
