### PR TITLE
Add logo and info

### PR DESCRIPTION
**Pull request by wuwenjia666**
BSC-XMT-0x67E20170749c501786b9cBa6A56800A512Ea355d- 
   deal: https://bscscan.com/tx/0xb33ff330ec3686bd66cac03ed37598bba1d0d1d1ed2db3b9742b098f602815fa
  test: https://bscscan.com/tx/0xa3fbd4212c9ed60de6c8b5aae708154355db55cececceb023804c49c70382186

### CODE REVIEW

**Comment by opera0001** [comment]
The submitted token logo is not 256x256 pixels. Please modify it.

**Comment by wuwenjia666** [comment]
logo

**Comment by wuwenjia666** [comment]
> 提交的令牌徽标不是 256x256 像素。请修改它。

read

**Comment by wuwenjia666** [comment]
Please check the message I gave you

在 2023-07-15 16:54:07，opera0001 ***@***.***> 写道：


The submitted token logo is not 256x256 pixels. Please modify it.

**Comment by opera0001** [comment]
The submitted token logo is not 256x256 pixels. Please modify it.

**Comment by wuwenjia666** [comment]
> 提交的令牌徽标不是 256x256 像素。请修改它。

logo

**Comment by wuwenjia666** [comment]
> 提交的令牌徽标不是 256x256 像素。请修改它。

Brother is like this?

**Pull request merged**
