### PR TITLE
update NAGA logo

### PR DESCRIPTION
**Pull request by Naga-Service**
update NAGA logo

### CODE REVIEW

**Comment by Naga-Service** [comment]
change the naga logo
TPT transfer hash: https://hecoinfo.com/tx/0xa9ac147179a3ceaf346a1c6af88d5b3cf1e6dbb764a104ec99373e6c65096729
BNB transfer hash: https://hecoinfo.com/tx/0x3347ce61b4a03984f305c5b8eef8d1541bcf7bbd8696d74aef5049c7cdc89a9a

**Comment by New-NAGA** [comment]
help me remove the token,thank you very much!

**Comment by Naga-Service** [comment]
help me remove the token info and logon ,thank you very much!

**Comment by Naga-Service** [comment]
I will send tpt transfer hash to you ,please approve it and [#7074](https://github.com/TP-Lab/tokens/pull/7074),thank you very much

**Pull request closed without merging**
