### PR TITLE
add DOGZ logo and info

### PR DESCRIPTION
**Pull request by xqjqqq**
0x5603fe5da90b48b74cF189736BC38a2C79C4c895
Project introduction
太空狗名字由来是想将其影响力传播至宇宙，所以起名太空狗。太空狗是狗狗币的一个新侧链，从技术特点上讲，其拥有狗狗币的全部优点，例如去中心化、无国界、安全性、匿名性、便捷性等。除了这些优点，太空狗还增强并增加了新的优点，例如算法升级、专属所有权、无隐藏成本、应用快速落地。这些曾经都是狗狗币上的短板，但如今在太空狗上得到了解决并完善。
The origin of the space dog's name is to spread its influence to the universe, so it is named space dog. Space dog is a new side chain of dog coin. In terms of technical characteristics, it has all the advantages of dog coin, such as decentralization, borderless, security, anonymity, convenience and so on. In addition to these advantages, the space dog also enhances and adds new advantages, such as algorithm upgrade, exclusive ownership, no hidden cost, and rapid application landing. These were once short boards on dog coins, but now they have been solved and improved on space dogs.

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3076439606

**Comment by sammvio** [comment]
Please refer to the tutorial, and re-submit your files in the correct format.

**Comment by xqjqqq** [comment]
--
致以问候。
xia qijun
***@***.***
---
***@***.***吧！ 星期五, 14 一月 2022, 11:23下午 +08:00 发件人 SS  ***@***.*** :

**Comment by xqjqqq** [comment]
费用
--
致以问候。
xia qijun
***@***.***
---
***@***.***吧！ 星期六, 08 一月 2022, 06:32下午 +08:00 发件人 jiasutijiao  ***@***.*** :

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
