### PR TITLE
add open token info

### PR DESCRIPTION
**Pull request by jasonz1987**
add open token info

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Please re-submit your files attached TPT transfer link on [Commit changes].

**Comment by jasonz1987** [comment]
TRON - CRS -TRegosVaS1o3DHG85nnW8xYzczPm3xL76K - 0xaa82d7c492d95750da9d22ec983b8dcdadd0007b6e734aaae5657cbc025bfea4

TRON - OPEN - TTNFpr4cxwMWnYYsrSTvGT9d4VCJnxVMnj - 0x762ae3031f0fffd37656db09c7f2b92fa7e7f248fe6236bf2a5b019e63ab75ed


please recheck, tks~

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
