### PR TITLE
Add MBC logo and info

### PR DESCRIPTION
**Pull request by MetaBabyCake1**
Decentralized Meme Token on BSC which provides a ecosystem for passive income for everyone.
Holders get paid hourly 9% rewards in $cake for holding $MBC.

Tx-hash: https://bscscan.com/tx/0x1a5196b6fb0bc1b1d2f3eea2468007d0a3e619e76fb7c9777eb737ec5259e9c3

### CODE REVIEW

**Comment by MetaBabyCake1** [comment]
No Logo shown in Token Pocket but already merged and closed, why?

**Comment by sammvio** [comment]
logo infringement, please resend your image

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request merged**
