### PR TITLE
add SPOOKYSHIBA

### PR DESCRIPTION
**Pull request by ChessPeace**
The #1 Horror genre token on the Binance Smart Chain. Not your typical Meme token! 
Stealth Launched 10/28/2021.  SpookySwap, P2E Game, NFT Marketplace and much more to come.
SpookySeasonNeverEnds.  

http://www.spookyshibabsc.com 
tw: @Shibaspooky
TG: t.me/spookyshibaOfficial 
BSC CA: 0xed74bc5dc139356e08de28143996f5ef6e4334a4
logo: bsc/0xed74bc5dc139356e08de28143996f5ef6e4334a4/logo.png.png
Spooky transp

https://bscscan.com/tx/0x06f7c9cce6e887f33bf416cb5b13d1a26041aa7a157df4b79d7d1ae044d986be
#5004 (closed and unresolved)

### CODE REVIEW

**Comment by nenrgy** [comment]
专业提交logo,代币，白皮书，诚住经营，值得信赖，价格全网最优！QQ:2099728898
Professional submit logo, scrip, white paper, honestly live operation, reliable, the optimal price cut! QQ: 2099728898

**Comment by ChessPeace** [comment]
What is wrong with what I already submitted to you? What "scrip" are you
asking ?

  I followed these instructions perfectly.
https://tphelp.gitbook.io/en/wallet-operation/how-to-submit-a-token-logo

and sent $60 TPT to provided address as instructed.  Please add the logo!
our project has been live and operational since October 28th.

t.me/spookyshibaofficial


RE:
https://github.com/TP-Lab/tokens/pull/5004 - THIS IS EVERYTHING REQUIRED

**Comment by ChessPeace** [comment]
.png file logo black background
acceptable

**Comment by sammvio** [comment]
Please submit the checksum address that includes uppercase and lowercase characters.

**Pull request closed without merging**
