### PR TITLE
add milit logo and info

### PR DESCRIPTION
**Pull request by WangWeiwei2013**
https://bscscan.com/tx/0x89e4ca182caacfe8c63e74e49a2059c15b7e41543a5705c9753701787d776255

### CODE REVIEW

**Comment by WangWeiwei2013** [comment]
https://bscscan.com/tx/0x89e4ca182caacfe8c63e74e49a2059c15b7e41543a5705c9753701787d776255

**Comment by guoxintongsam** [comment]
Please donate 3000 TPT as required and submit the transfer link on [Commit changes].

**Comment by WangWeiwei2013** [comment]
https://bscscan.com/tx/0x8b65ec100f4128f8b8f8a939e5c707291f3cd989ed6cdf8930acaea040728e1a

**Comment by WangWeiwei2013** [comment]
补上2000了

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3579750034

**Pull request closed without merging**
