### PR TITLE
Add XOX logo and info

### PR DESCRIPTION
**Pull request by XGame-XRush**
https://bscscan.com/tx/0xf824711da16d1858146f8bb1096a18cf07ecde26709894520ab56598dcccf9de && https://bscscan.com/tx/0x724afac937b9453d3b78bc86befdcdd137f3d69f19e61644ea07ef5b12a6b372

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token

**Comment by XGame-XRush** [comment]
@guoxintongsam already submit, please check.Thanks.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
