### PR TITLE
ADD ANTY logo and info

### PR DESCRIPTION
**Pull request by csskd**
交易1000TPT哈希
0x8b605847a68c5b1860456e4f2f6e957fdd057176d4fb2fd0866bd9bdfc8457a5

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Please re-submit the TPT transfer link on [Commit changes].

**Comment by oko-token** [comment]
> Please re-submit the TPT transfer link on [Commit changes].

Sorry 、Dear auditor、I can't reach you ， Please pay attention to the merge. The display has been merged, but the logo has not been updated after the merge.. Please help me see what‘s the problem
https://github.com/TP-Lab/tokens/pull/2844

**Comment by csskd** [comment]
https://bscscan.com/tx/0x8b605847a68c5b1860456e4f2f6e957fdd057176d4fb2fd0866bd9bdfc8457a5

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request merged**
