### PR TITLE
add SCC logo and info

### PR DESCRIPTION
**Pull request by duoladaimeng**
https://bscscan.com/tx/0x9b68b7390e566b04e1c5ffb3148297ee66c03f3046f8a5d096e6f0e7c3ee2b83

### CODE REVIEW

**Comment by tubiaoyingji** [comment]
专业加快提交LOGO，20分钟内审核包过，QQ：1450001284

**Comment by sammvio** [comment]
Please submit the checksum address that includes uppercase and lowercase characters.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by logobaoguo** [comment]
专业提交logo！加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
