### PR TITLE
ADD nuwa LOGO AND INFO

### PR DESCRIPTION
**Pull request by a54330173**
https://bscscan.com/tx/0x8f6c8ffa3d58a023a8e57b3428c386e99bc88a22b6611610a3125dc1d4c4a65d?utm_source=tokenpocket

### CODE REVIEW

**Comment by a54330173** [comment]
打了两次tpt  提交了两次 避免下次不合格

**Comment by a54330173** [comment]
请尽快审核

**Comment by sammvio** [comment]
Please submit the checksum address that includes uppercase and lowercase characters.

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
