### PR TITLE
ZEOS privacy protocol on EOS Blockchain added

### PR DESCRIPTION
**Pull request by bngone**

### CODE REVIEW

**Comment by opera0001** [comment]
Please provide the donation hash value link for TPT.

**Comment by bngone** [comment]
I'm Sorry,  no donation was made, I'm a contributor to the project. which has the potential to solve the issue of Assets Privacy of the general public, work on the project is ongoing, and we hope when its protocol part is fully live, you may add the features to your Wallet, Thank You.

**Comment by opera0001** [comment]
> I'm Sorry, no donation was made, I'm a contributor to the project. which has the potential to solve the issue of Assets Privacy of the general public, working on the project is ongoing, and we hope when its protocol part is fully live, you may add the features to your Wallet, Thank You.

According to the current token listing rules, you need to submit a donation in order to complete the inclusion of the token logo. This rule has been in effect for a long time, and everyone has been increasing logo inclusions through this method.

**Comment by opera0001** [comment]
Since we haven't received a response from you in 2 days, we will need to close the order. If you have any further questions, please contact us through the issues section at:

https://github.com/TP-Lab/tokens/issues

**Pull request closed without merging**
