### PR TITLE
Add BAB logo and info

### PR DESCRIPTION
**Pull request by BABOwner**
https://bscscan.com/tx/0x95199715b567b5fca6f75aabe1d0363604e677c0d63d863cc6170ccdda2b92b9 
https://bscscan.com/tx/0xcd50a6eeb516cde249214ef95ed80fb7dddfd26bc927e0eee36bc927e0eee1336

### CODE REVIEW

**Comment by BABOwner** [comment]
Hello, the manager has modified the submission location. Please review it again. Thank you

**Comment by BABOwner** [comment]
Hello, the manager has modified the submission location. Please review it again. Thank you

**Comment by BABOwner** [comment]
Hello administrator, you have modified the submission location, please re-approve, thank you!

**Comment by BABOwner** [comment]
Hello, administrator, the submission location has been modified. Please re-approve. Thank you!

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Pull request merged**
