### PR TITLE
Please add WHEE token & logo

### PR DESCRIPTION
**Pull request by sunsunsz**
Transfer 50000TPT : https://bscscan.com/tx/0x8e91762a7934fb0accb8435632b76c762a90827c1ddde998b49071f1b0493514 

Verify TX：https://bscscan.com/tx/0x2d933062d76222f4429fc61c0cbe9eab3e056e22d7b7ff53612ef55705ba5a02

### CODE REVIEW

**Comment by sunsunsz** [comment]
logo and info

**Comment by opera0001** [comment]
Please submit the content according to the basic guidelines.

CN：https://tphelp.gitbook.io/cn/wallet-operation/submit-token
EN：https://help.tokenpocket.pro/en/developer/how-to-submit-a-token-logo#steps-of-adding-a-token-logo-info

**Comment by sunsunsz** [comment]
BSC-TPT- 0x62238038AbeAe5A667cDe8769E708c5a07d7ADdB- https://bscscan.com/tx/0x8e91762a7934fb0accb8435632b76c762a90827c1ddde998b49071f1b0493514

**Comment by sunsunsz** [comment]
BSC-TPT- 0x62238038AbeAe5A667cDe8769E708c5a07d7ADdB- https://bscscan.com/tx/0x8e91762a7934fb0accb8435632b76c762a90827c1ddde998b49071f1b0493514

**Comment by sunsunsz** [comment]
BSC-TPT- 0x62238038AbeAe5A667cDe8769E708c5a07d7ADdB- https://bscscan.com/tx/0x8e91762a7934fb0accb8435632b76c762a90827c1ddde998b49071f1b0493514|

**Comment by sunsunsz** [comment]
https://bscscan.com/tx/0xff7d457f8fa5bd31326e7898a8973082fcdaeec2c1bf635decd855e00d9e729c

**Comment by sunsunsz** [comment]
Submit tx according to basic guidelines

**Review by sunsunsz — COMMENTED** [review]
update logo to png

**Comment by sunsunsz** [comment]
submit to new pr

**Pull request closed without merging**
