### PR TITLE
Add SDOGE logo and info

### PR DESCRIPTION
**Pull request by AQscoutdoge**
3000TPT transfer hash：https://bscscan.com/tx/0x885639d83ef151b67e9e2e656d6b43fb668c8cebe667e2682e2546b2f140add5
{
 "name": "Scout Doge Token",
 "website": "https://scoutdoge.com",
 "description": "Scout Doge TOKEN.",
 "explorer": "https://bscscan.com/token/0x9e551b430b7ab145c96c6ede72a34ec2a90d4eca",
 "type": "BEP20",
 "symbol": "SDOGE",
 "decimals": 9,
 "status": "active",
 "id": "0x9e551b430b7ab145c96c6ede72a34ec2a90d4eca"
}

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3579750034

**Comment by AQscoutdoge** [comment]
Sir, please pass me through

**Comment by sammvio** [comment]
Please re-submit your files to bsc folder

**Comment by AQscoutdoge** [comment]
> Please re-submit your files to bsc folder
Sir, I've already resubmitted it     
link: https://github.com/TP-Lab/tokens/pull/4753

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
