### PR TITLE
HDT no logo and info in TP, need update,please help

### PR DESCRIPTION
**Pull request by cokeswap**
HDT logo and info not updated  in TokenPocket.,please help !

https://bscscan.com/tx/0xc171b54bd33a54d7e30b1481b333b9bf1c006aad58c6a464069235a61d980325

### CODE REVIEW

**Comment by qq2871019009** [comment]
快速提交logo，一天内包过，不过全额退款。加QQ：2871019009

**Comment by SAEXIO** [comment]
> HDT logo and info not updated in TokenPocket.,please help !
> 
> https://bscscan.com/tx/0xc171b54bd33a54d7e30b1481b333b9bf1c006aad58c6a464069235a61d980325

it not update in TP . please look

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
