### PR TITLE
Create Add-and-logo-info INFINITY GLOBAL

### PR DESCRIPTION
**Pull request by infinity-global**
https://bscscan.com/tx/0x700cdb5637eb744e78c700a274f9033729d8fe8608554d4c6f7b3a6ac87a8fa8
https://bscscan.com/token/0x916fd59e5f4f26dd2a3a6a6b47f80194b3d1d7dd
https://drive.google.com/file/d/1ED6LaAtz9b-spVVu4TrSR24is-vVgHuW/view?usp=drivesdk
{
 "name": "INFINITY GLOBAL",
 "website": https://www.infinity-global.app/1"",
 "description": ".THE INFINITY GLOBAL IGL TOKEN IS A UTILITY TOKEM USED ON THE INFINITY GLOBAL PLATFORM TO BUY SMART CONTRACTS IT IS PART OF A SYSTEM TO PAY FOR GAMES LOTTERIES AND WILL HAVE ITS OWN META VERSE HAS A BONUS SYSTEM THAT PAYS DIRECTLY INTO THE DIGITAL WALLETS OF THE COMMUNITY PARTICIPATING IN THE PROJECT",
 "explorer": "https://bscscan.com/token/0x916fd59e5f4f26dd2a3a6a6b47f80194b3d1d7dd",
 "type": "BEP20",
 "symbol": "IGL",
 "decimals": 18,
 "status": "active",
 "id": "0x916fd59E5F4f26dd2a3A6A6B47F80194b3d1d7dD"

### CODE REVIEW

**Comment by opera0001** [comment]
The submission format is incorrect. Please review the tutorial again and adjust the submission format.
Tutorial link: https://tphelp.gitbook.io/cn/wallet-operation/submit-token

**Comment by infinity-global** [comment]
please check again i made an update


Em sáb, 5 de mar de 2022 06:19, opera0001 ***@***.***>
escreveu:

**Comment by opera0001** [comment]
Logo requires 256x256 pixel files

**Comment by infinity-global** [comment]
nvo igl

**Comment by infinity-global** [comment]
I updated the logo please check


Em sáb, 5 de mar de 2022 22:14, opera0001 ***@***.***>
escreveu:

**Comment by giki0318** [comment]
According to the DAO, the donation amount for a logo update has been updated to 30,000 TPT. [Click here for Details](https://snapshot.org/#/tptdao.eth/proposal/0x781abc1ade2ebd082aec4f57b7199d472a2b2850b3df46c8ec37e3b6a1a243c2)

**Comment by infinity-global** [comment]
yes, this agreement is being read after 02.28.2022 I made the DONATION a long time ago for the logo update, see the date
https://bscscan.com/tx/0x700cdb5637eb744e78c700a274f9033729d8fe8608554d4c6f7b3a6ac87a8fa8

**Comment by infinity-global** [comment]
https://bscscan.com/tx/0x700cdb5637eb744e78c700a274f9033729d8fe8608554d4c6f7b3a6ac87a8fa8

yes, this agreement is being read after 02.28.2022 I made the DONATION
a long time ago for the logo update, see the date


Em dom, 6 de mar de 2022 23:30, opera0001 ***@***.***>
escreveu:

**Pull request merged**
