### PR TITLE
Add CatBoy Logo and Info

### PR DESCRIPTION
**Pull request by msecretmsecretmsecret**
https://bscscan.com/tx/0x64ab78eff22065abed3935263b5e8b2af6d195faf8dc6a6f84624b00a13ba93c

### CODE REVIEW

**Comment by opera0001** [comment]
Now the token logo application needs 30,000 TPT donations. Please add the difference and leave a message to us on GitHub. Thank you.

**Comment by TokenPocket-JAN** [comment]
Speed ​​up the trial. Please reply to the email if you need.
QQ112831047

**Comment by opera0001** [comment]
We haven't seen the supplementary TPT donation hash value after 22 hours, so we temporarily close the order and need to resubmit it after you supplement the TPT quota. Thank you for your support for tokenpocket.

**Comment by msecretmsecretmsecret** [comment]
https://bscscan.com/tx/0x64ab78eff22065abed3935263b5e8b2af6d195faf8dc6a6f84624b00a13ba93c

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
