### PR TITLE
add PPDAO logo and info 

### PR DESCRIPTION
**Pull request by ppdao**
https://bscscan.com/tx/0xc49eedbece92052820ed7a3f2b447840afe43b651743c632c292db5a994d74cd

### CODE REVIEW

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by opera0001** [comment]
1. Abnormal token transaction status
2. The contract does not give up ownership
3. Please do not submit the same content repeatedly

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
