### PR TITLE
Add SHIB logo and info

### PR DESCRIPTION
**Pull request by TP404544957Q**
30000TPT:
https://bscscan.com/tx/0x2410f57161b143715255ba800b17b076e77650f7669866f51aa77dfe284e8667
BnbTX:
https://bscscan.com/tx/0xf718ab5dc60da733dabe1e6b6b85318d9d40b917f06a2b6fa4024ed160812b20

### CODE REVIEW

**Comment by opera0001** [comment]
It is recommended that you adjust the submitted logo because it may infringe.

**Comment by TP404544957Q** [comment]
@opera0001  I have modified the logo. Please add it for me as soon as possible

**Comment by TP404544957Q** [comment]
logo

**Comment by opera0001** [comment]
A brand new logo is recommended.

**Comment by TP404544957Q** [comment]
@opera0001   I have cancelled this request and reissued another request. Please help me finish #6707

**Pull request closed without merging**
