### PR TITLE
add Rise Fist LOGO and info

### PR DESCRIPTION
**Pull request by DD88BAO**
https://bscscan.com/tx/0x6661c87d3429e4c7d8d1162c60c4a0cc37a9b56e09c7a79df8476a3f8590cb9a

### CODE REVIEW

**Comment by opera0001** [comment]
1、The submitted TPT hash value is the same as the #6543 order, please check.
2、The content of JSON file is submitted incorrectly.
image

**Comment by opera0001** [comment]
Please adjust within 24 hours

**Comment by DD88BAO** [comment]
已经调整

**Comment by DD88BAO** [comment]
> 请在24小时内调整

已经调整，请查看

**Comment by opera0001** [comment]
The adjusted content is OK. What's the matter with #6544 using the same hash value?

**Comment by DD88BAO** [comment]
那个提交的不完整，我就从新提交的，请列出，没有任何问题

**Comment by opera0001** [comment]
done

**Pull request merged**
