### PR TITLE
Add BFFA logo and info

### PR DESCRIPTION
**Pull request by IceCattle001**
https://bscscan.com/tx/0xb39c15fec071529373ca7eb54f8ade8430dd489aa8c57ceba562298efc8a6ce4

### CODE REVIEW

**Comment by IceCattle001** [comment]
https://bscscan.com/tx/0xb39c15fec071529373ca7eb54f8ade8430dd489aa8c57ceba562298efc8a6ce4

**Comment by opera0001** [comment]
The submitted logo is not 256x256 pixels. Please adjust and replace it. Thank you.

**Comment by IceCattle001** [comment]
Please resubmit it after I corrected images?Has the need to donate?

**Comment by IceCattle001** [comment]
I have to resubmit 256 * 256 icon

**Pull request merged**
