### PR TITLE
Added Timerr logo and info

### PR DESCRIPTION
**Pull request by Timerr1**
https://bscscan.com/tx/0xca7bd108d8e0ee2750d6553f1a4c534fa6db4b51b08f5fd898e58787871d6987

### CODE REVIEW

**Comment by opera0001** [comment]
If the ownership of the contract is not abandoned, there may be some risks.

**Comment by Timerr1** [comment]
So what does mean is it going to merge to main branch or  request is rejected ?

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
