### PR TITLE
Add PNC logo and info

### PR DESCRIPTION
**Pull request by AuraSuper**
https://bscscan.com/tx/0xd6dc261bd3a903f0043d82cafa1d34a8fa247189d79d659675ba25ae01262585

### CODE REVIEW

**Comment by opera0001** [comment]
1. The token logo is fuzzy. It is recommended to use high-definition pictures
2. The token does not create a flow pool, and the risk is unknown
3. The URL provided cannot be opened, and there is a safe prompt.
After adjustment, you can resubmit using the TPT donation hash value.

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
