### PR TITLE
Add RBL logo and info

### PR DESCRIPTION
**Pull request by inhcwziwt5pe6xpu**
https://bscscan.com/tx/0xb76f92b065f16ffecbe80ae97aef73c7588bfe1b602612741816d7f328d2d14c
https://bscscan.com/tx/0xd0f001528bea60bf24436cc1f9db450643e837921d16c90427316c19babb3bb0

### CODE REVIEW

**Comment by opera0001** [comment]
image

The correct link to submit should be.
NFT/bsc/erc721/0x541B37c5B707eC8AE79Acf5faC8d15CE22362B23/info.json and logo.png

**Comment by opera0001** [comment]
I don't see a reply or change after 4 days, so the order needs to be closed, you can contact me through issues, thanks.

Link: https://github.com/TP-Lab/tokens/issues

**Comment by inhcwziwt5pe6xpu** [comment]
Is the submission closed now, can I resubmit it again?

opera0001 ***@***.***> 于2022年8月22日周一 20:55写道：

**Comment by inhcwziwt5pe6xpu** [comment]
The correct nft721 contract address should be this
0xd464e7D5809CE4d501d2aBeD1A533c65741e3c32


opera0001 ***@***.***> 于2022年8月22日周一 20:55写道：

**Comment by inhcwziwt5pe6xpu** [comment]
Can you change it for me directly, or do I need to resubmit it myself

opera0001 ***@***.***> 于2022年8月18日周四 16:10写道：

**Pull request closed without merging**
