### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by GEX666520**
https://bscscan.com/tx/0x745933e8f03cb3f28f89084d390942b5e1252b286ec8be0594ee5ad89ed9f8e2?utm_source=tokenpocket

### CODE REVIEW

**Comment by opera0001** [comment]
The token contract features a function that allows trading to be paused. Please explain this.

**Comment by RotMCC520** [comment]
您好！项目目前还在Mint 阶段，等mint完成后会 正常启动，也会丢掉权限，麻烦给与通过谢谢！

**Comment by GEX666520** [comment]
您好！项目目前仍在Mint阶段，等mint完成后会正常启动，同时丢掉权限，麻烦给与通过谢谢！

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Pull request merged**
