### PR TITLE
Add ANM logo and ingo

### PR DESCRIPTION
**Pull request by anmfinance**
https://bscscan.com/tx/0x10f289fca0d60b3c775d4a081f71750cd11ac21b4a46d3e102438dd73ace1437

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Please refer to the tutorial, and re-submit your files in the correct format.

**Comment by anmfinance** [comment]
> Please refer to the tutorial, and re-submit your files in the correct format.

could you pls tell me where the mistakes at? I'm pretty sure I followed the tutorial correctly.

**Comment by anmfinance** [comment]
> Please refer to the tutorial, and re-submit your files in the correct format.

I see, the folder name was a wrong address, just updated in #2846 ,pls check, thanks

**Comment by anmfinance** [comment]
> Please refer to the tutorial, and re-submit your files in the correct format.

您好，可以看到我的留言吗，看到请加急处理一下，麻烦您了

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Pull request closed without merging**
