### PR TITLE
Add DBTC logo and info

### PR DESCRIPTION
**Pull request by dodopa**
https://bscscan.com/tx/0xf5cd8c498a1a2643f8d5209d1023db29d2102953c81cdcba70da2eb63806b9dd
0x0644fd001df8aaf11861c8362eb56fe85812dc02

### CODE REVIEW

**Comment by opera0001** [comment]
Now the token logo application needs 30000 TPT donations. Please add the difference and leave a message to us on GitHub. Thank you.

**Comment by dodopa** [comment]
捐赠3000TPT哈西链接；https://bscscan.com/tx/0xf5cd8c498a1a2643f8d5209d1023db29d2102953c81cdcba70da2eb63806b9dd
补捐27000TPT哈西链接；
https://bscscan.com/tx/0xbdf4a08e0813ea2642fd06847a5207a9fdc90b84bfc8fdc19006b61aa6356257
麻烦核实

**Comment by tplogotijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request merged**
