### PR TITLE
Add Sonic logo and info

### PR DESCRIPTION
**Pull request by tubiaotijao**
https://bscscan.com/tx/0xb14fee7196704c13c7231fdeb20da123dabd0a301a4b93945ef80866ab1f7e2c

### CODE REVIEW

**Comment by opera0001** [comment]
1, catalog successful (0x092b1a318EC1d9933B905703D56267baC0703cC3)
2, including invasion elements in the logo（0x1784FE238E34dDCCb3870f34162F34d41e19e0A6）
3、The tokens were not circulated and the liquidity pool was not increased after 125 days of issuance.（0xFfce84f80e5c0168687e7D6d4800bdaAbdFeAF6B）
4、Insufficient liquidity of capital pool。（0x04394fCfDb939F3c04391aC39A3EA9f1C75BD0F2）
5、Token logo submission pixel size error（0xcb5aa9e9E531759C482096597a69408538704b82）

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
