### PR TITLE
Add BXB logo and info

### PR DESCRIPTION
**Pull request by fucksk**
https://bscscan.com/tx/0x73a7a1b29f3c76c06ab77d6cd5624ed8ca39f873286c924a5e816094fa116884

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3579750034

**Comment by sammvio** [comment]
The contract don’t verify and published. (No open-source)

**Comment by fucksk** [comment]
I'm already open source. Please add the logo




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TP-Lab/tokens"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月6日(星期四) 中午11:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TP-Lab/tokens] Add BXB logo and info (PR #4667)





 
The contract don’t verify and published. (No open-source)
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fucksk** [comment]
I'm already open source. Please add the logo

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
