### PR TITLE
add seedx logo and info

### PR DESCRIPTION
**Pull request by seedx1**
50000TPT ID:https://bscscan.com/tx/0xb3867327cdbfd20605e6a42fdcc9c377bb4f8cb5b00092c831c3f2a4cef2fe5c BNB Hash :https://bscscan.com/tx/0xfb89154614a77f1f2937935095593bd00cb457966454bdd0294a95829a8dd5d9

### CODE REVIEW

**Comment by opera0001** [comment]
image
The submitted file is not saved in the BSC directory, please adjust it again.

The submitted file is not saved in the BSC directory, please adjust it again.

**Comment by seedx1** [comment]
i have added my logo icon and info folder in bsc folder with their contract address named folder please verify Mr. admin

**Comment by opera0001** [comment]
It is found in the token contract that the function of adding tokens to the issue is available. Please explain the reason for this setting.

**Comment by seedx1** [comment]
Yes, I have mentioned total tokenomics here https://docs.seedx.app/seedxapp/seedx-assets. We released only 100M $SEEDx currently for Airdrop and launchpad; the remaining 150M token will be released through DAO Governing process on proposal of issuing and burning , Currently we require only 100M $Seedx for 3-4 years. If Extra token will not required it will burn through voting on proposal

**Comment by seedx1** [comment]
Yes, I have mentioned total tokenomics here
https://docs.seedx.app/seedxapp/seedx-assets. We released only 100M $SEEDx
currently for Airdrop and launchpad; the remaining 150M token will be
released through DAO Governing process on proposal of issuing and burning ,
Currently we require only 100M $Seedx for 3-4 years. If Extra token will
not required it will burn through voting on proposal

**Pull request merged**
