### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by SHPSHP520**
https://bscscan.com/tx/0xa4469ef46b2cb750d4baaf739af9d637a0333744238579ceafcfb1b38cd0e89d?utm_source=tokenpocket

### CODE REVIEW

**Comment by opera0001** [comment]
Hidden owner permissions were detected in the token contract, which poses a very, very high risk. Therefore, the token cannot be listed. However, don't worry, the TPT hash value you submitted can still be used in future submissions.

**Comment by SHPSHP520** [comment]
您好！目前还开发DAPP中，权限还没有丢弃，需要与DAPP做对接，等DAPP开发完成后会丢掉权限。麻烦给予通过，谢谢！

**Comment by opera0001** [comment]
The hiding of owner control permissions is based on the results displayed by the goplus verification platform. If you have doubts about the verification results, you can contact them for manual verification. In case of a misjudgment, you can request them to update their database, and the inclusion can proceed as usual. You can find more information on their website: https://gopluslabs.io/.

**Comment by SHPSHP520** [comment]
您好！目前还开发DAPP中，权限还没有丢弃，需要与DAPP做对接，等DAPP开发完成后会丢掉权限。隐藏权限是DAPP需要调用合约权限，DAPP有质押挖矿，和铸造的功能，麻烦给予通过，谢谢！

**Comment by opera0001** [comment]
I'm sorry, dear, I can't confirm if the hidden owner feature you mentioned is genuine.

**Comment by SHPSHP520** [comment]
老合约地址0x893ec985d6c9cee950a6a899b76bd10c0b1307d7
您好，这是我们老合约地址，新合约的代码和老合约是一样，您可以查看。新合约的DAPP功能在测试中，等测试正常后就会丢掉权限，麻烦给与通过，谢谢。

**Comment by SHPSHP520** [comment]
合约权限，这两天就会放弃，麻烦给与通过谢谢！

**Pull request merged**
