### PR TITLE
add wildwolf logo and info 

### PR DESCRIPTION
**Pull request by wsf629**
sample

### CODE REVIEW

**Comment by wsf629** [comment]
https://bscscan.com/tx/0x31868ec34ef95c91effe60119e7d2108b267d027b0118c6a4ce7958c353f1f85

**Comment by zhujiayu03** [comment]
Please re-submit your files to bsc folder

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
