### PR TITLE
Add LIBRA logo and info

### PR DESCRIPTION
**Pull request by SmallCharm**
Libra token logo and info
BSC-LIBRA-0x85979c90D53E20E4505C83d9408b8A61Beb8db1F-https://bscscan.com/tx/0x850d7598f1a41d059baa8632580f34a4aa30121d4549d06afc4ebd5c0c153303

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token

**Comment by SmallCharm** [comment]
I have add token list by the form you given,do I need to commit again?

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
