### PR TITLE
Add LOVER logo and info

### PR DESCRIPTION
**Pull request by jesaon**
#5501 update https://bscscan.com/tx/0x2e2ff492cdd6cb0d692e15a16c508c346d2ac21dec6a217701ee41216c385369

### CODE REVIEW

**Comment by jesaon** [comment]
Modify the two submitted before, LOVER and ODIN
Changed as requested

**Comment by opera0001** [comment]
0x0ae5Ce708D1CB1ae8EE3A6A8807340BC0e9b94cE--
The submitted logo uses other people's creative products, https://www.sohu.com/a/493502506_121119407

0xe2578b3afcc78F87e2e07fFA5e402DC3629730D6--
Insufficient liquidity of token fund pool

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
