### PR TITLE
ADD TIGER logo and info

### PR DESCRIPTION
**Pull request by babyface001**
TPT transfer https://bscscan.com/tx/0x243e0836775400e313f53e9cc410ea0d1fa9b6c80bc08cfb784ba5150d84277d
BNB confirm https://bscscan.com/tx/0xd2e6edde656dbf1a91be10aa84af254be6094cf504eb6aa844c36e4f25b1cc7a

### CODE REVIEW

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by opera0001** [comment]
1. Contract not open source
2. Not relinquishing ownership
There are many assets in the capital pool, so it is safer to open source and give up ownership. Please re adjust or optimize and submit the logo. Thank you for your support for tokenpocket.

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request merged**
