### PR TITLE
Add Brave logo and info

### PR DESCRIPTION
**Pull request by BraveTokenmoon**
https://bscscan.com/tx/0xa836385f40c2a5e9c37d5cf0fa1ff305fefb078a6e716f550c026742268ae591

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Please submit the checksum address that includes uppercase and lowercase characters.

**Comment by BraveTokenmoon** [comment]
> Please submit the checksum address that includes uppercase and lowercase characters.

checksum address: 0xadb5ab463c060632df20fac209e703799b146f50

**Comment by BraveTokenmoon** [comment]
checksum address: 0xadb5ab463c060632df20fac209e703799b146f50

**Comment by BraveTokenmoon** [comment]
> Please submit the checksum address that includes uppercase and lowercase characters.

checksum address: 0xadb5ab463c060632df20fac209e703799b146f50

**Comment by BraveTokenmoon** [comment]
checksum address: 0xadb5ab463c060632df20fac209e703799b146f50


guoxintongsam ***@***.***> 于2021年11月1日周一 下午3:15写道：

**Comment by BraveTokenmoon** [comment]
0xADB5AB463c060632df20fAc209E703799B146f50

guoxintongsam ***@***.***> 于2021年11月1日周一 下午3:15写道：

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
