### PR TITLE
Add DOD and logo

### PR DESCRIPTION
**Pull request by DOD195450508**
Add DOD and logo

### CODE REVIEW

**Comment by DOD195450508** [comment]
Add DOD and logo #4044 

I have submitted it for 6 days, and I haven’t seen the logo yet, and I paid for TPT. Please see what the reason is.

**Comment by tiaojiaotubiaobaoguo** [comment]
代提交logo，24小时内包过，加QQ：2980874528

**Comment by sammvio** [comment]
Please donate 3000 TPT as required and submit the transfer link on [Commit changes].

**Comment by DOD195450508** [comment]
> Please donate 3000 TPT as required and submit the transfer link on [Commit changes].

https://bscscan.com/tx/0x2908603568df53f6556055aca6cf2e8d79f436c574bc2220987451e5f35b2c27

**Comment by DOD195450508** [comment]
> Please donate 3000 TPT as required and submit the transfer link on [Commit changes].
This is a memo transaction

https://bscscan.com/tx/0x243ed9f89326a9e76e1cdfac9305a56dab65c85b6d5392191a6deda63c84a05c

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
