### PR TITLE
Add OK FLY logo and info

### PR DESCRIPTION
**Pull request by shunpeng**
0x72ffcb3604b37b7569570d40eb0f6d17e7b1213f96b4e370c3d3aa4af21d8e46

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3579750034

**Comment by sammvio** [comment]
Please re-submit your files to bsc folder

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
