### PR TITLE
dogstonks

### PR DESCRIPTION
**Pull request by a1603329984**
1000TPT链接https://bscscan.com/tx/0x5438ecfc841e9bf86bf0d121aa7c1e71684ad3d9ce48dc7174581359dc20fd9c
合约地址0x6a3340dD0144067E298dB6a7339482374E86f851
代币名dogstonks

### CODE REVIEW

**Comment by a1603329984** [comment]
1000TPT链接https://bscscan.com/tx/0x5438ecfc841e9bf86bf0d121aa7c1e71684ad3d9ce48dc7174581359dc20fd9c
合约地址0x6a3340dD0144067E298dB6a7339482374E86f851
代币名dogstonks

**Comment by zhujiayu03** [comment]
Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token

**Comment by a1603329984** [comment]
> Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token

1000TPT链接https://bscscan.com/tx/0x5438ecfc841e9bf86bf0d121aa7c1e71684ad3d9ce48dc7174581359dc20fd9c
合约地址0x6a3340dD0144067E298dB6a7339482374E86f851
代币名dogstonks

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
