### PR TITLE
MIN token logo and info

### PR DESCRIPTION
**Pull request by contractsolidity**
BSC-MIN-0xC812316bE6A3Ee958679bb858b11310aDD3aF759-https://bscscan.com/tx/0x6ec43de3320a5e319e0edca1e008d7bb13fb809f6c1b4fb745bd26311941fab0
https://bscscan.com/tx/0xa21396f6c847002c42d956967de1050b2e8de9201b257d8ca5b3fc679d21b3ed

### CODE REVIEW

**Comment by contractsolidity** [comment]
When to process

**Comment by opera0001** [comment]
Detected hidden owner permissions in the token contract, which poses significant risks. Please do not display exaggerated content on the logo, and you may even remove the Chinese content.

**Comment by contractsolidity** [comment]
{
    "name": "MIN Token",
    "website": "http://www.minmotions.com",
    "description": "",
    "explorer": "https://bscscan.com/token/0xC812316bE6A3Ee958679bb858b11310aDD3aF759",
    "type": "BEP20",
    "symbol": "MIN",
    "decimals": 18,
    "status": "active",
    "id": "0xC812316bE6A3Ee958679bb858b11310aDD3aF759"
   }

**Comment by contractsolidity** [comment]
Please help me remove it.

**Comment by opera0001** [comment]
The logo adjustment is now fine, but the hidden owner permissions in the token contract are a major factor affecting the audit. This is a very dangerous setting.

**Comment by contractsolidity** [comment]
This is added for the need to destroy the MIN in lp

**Comment by contractsolidity** [comment]
We pay you to update your token information

**Comment by contractsolidity** [comment]
Can it be done? Give me a quick answer.

**Comment by opera0001** [comment]
The order has undergone a long period of modifications but still does not meet the standards for inclusion, so the order needs to be temporarily closed. The TPT hash value you donated can be used again in the next logo submission process.

**Pull request closed without merging**
