### PR TITLE
Add NFTT logo and info

### PR DESCRIPTION
**Pull request by 1688989**
BSC-NFTT-0x26A031968065Bfa407c615F615e8cb0C9D80f077-https://bscscan.com/tx/0x95f69a3787065ce75fd76ac66583a38ab6cd5901fa4c64dc824fff3bf8826043

### CODE REVIEW

**Comment by tiaojiaotubiaobaoguo** [comment]
代提交logo，24小时内包过，加QQ：2980874528

**Comment by sammvio** [comment]
The contract didn’t verify and publish. (No open-source)

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
