### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by BRCBRC520520**
https://bscscan.com/tx/0x830a6a2d184cf11209b32b399c27da734209328e0bf10d5f5fde62f4e9aca3e5?utm_source=tokenpocket

### CODE REVIEW

**Comment by opera0001** [comment]
The presence of a proxy contract has been detected, carrying significant risks. Unless you can provide a valid security certificate issued by an authorized security auditing entity, the token logo cannot be added for you.

**Comment by BRCBRC520520** [comment]
你好，这个项目后续还要继续开发，目前正在开发DAPP中，等DAPP开发完成后，所有功能测试完成后项目会正常运行，麻烦给予通过，谢谢。

**Comment by opera0001** [comment]
I'm sorry, dear. The proxy contract must have a security audit certificate from a recognized security testing organization, proving that the code is secure enough for inclusion.

**Comment by BRCBRC520520** [comment]
您好，后面布局dapp，所以预留了代理合约，会在dapp完成后，马上关闭代理合约。目前正在开发DAPP中，等DAPP开发完成后马上会关掉代理合约。麻烦给予通过，谢谢。我一年再咱们平台起码上200个头像的，没有一个合约出现过问题呢，麻烦通过谢谢。可以查看我转账TPT 的记录0xee7020D64bCDDeA5D1629C60F7d5Ea12e7606666。这只是其中一个地址。

**Pull request merged**
