### PR TITLE
Add SBT info and logo

### PR DESCRIPTION
**Pull request by lonely1215225**
https://bscscan.com/tx/0x3a6c4b1b998762bdc9f5ca57c8175b1fb391bf2fe15990cb01ad23e6fcb54fc7

### CODE REVIEW

**Comment by opera0001** [comment]
Please check the TPT donation hash value link.

**Comment by lonely1215225** [comment]
> Please check the TPT donation hash value link.

sorry， i change  that tx！

**Review by lonely1215225 — COMMENTED** [review]
update tx hash:
https://bscscan.com/tx/0xc215b6dece768134bb8810dcf8f2e5d229e7fcc9751c1b0bc0dab99dbaab7ace

**Comment by lonely1215225** [comment]
> Please check the TPT donation hash value link.

hello?

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Pull request merged**
