### PR TITLE
add USDC info and logo

### PR DESCRIPTION
**Pull request by liyiwan1205**
https://bscscan.com/address/0xac1ae43e54be7923782605e2d20709c50504a466

### CODE REVIEW

**Comment by liyiwan1205** [comment]
[](url)

**Comment by liyiwan1205** [comment]
[](url)

**Comment by liyiwan1205** [comment]
{ 
"name": "USDCoin",
"website": "https://li447742508147.wixsite.com/sg-nft",
"description": "USDC is a large scale multiplayer online simulation game (USDGAME), with interstellar space as the background and cyberpunk style as the main theme. The game provides a large number of galaxies home to various planets. ",
"explorer": "https://bscscan.com/address/0xac1ae43e54be7923782605e2d20709c50504a466",
"type": "BEP20",
"symbol": "USDC",
"decimals": 18,
"status": "active",
"id": "0xac1ae43e54be7923782605e2d20709c50504a466"
}

**Comment by opera0001** [comment]
I'm very sorry, the token name you submitted does not meet the inclusion rules, and the tpt hash value you donated can continue to be used in the future.

**Pull request closed without merging**
