### PR TITLE
Add octopus logo and info

### PR DESCRIPTION
**Pull request by asas1232**
Add octopus logo and info
https://hecoinfo.com/tx/0xe5caa89db3da0f8775f977de398f3f423ce8ff696bf4465e150d52ebddcd9f05

### CODE REVIEW

**Comment by asas1232** [comment]
https://hecoinfo.com/tx/0xe5caa89db3da0f8775f977de398f3f423ce8ff696bf4465e150d52ebddcd9f05

**Comment by asas1232** [comment]
https://hecoinfo.com/tx/0xf31f85872ea9e4d67b099c1ae997704f5f030b11faaa8c2b55f12a2936765d1a
Add snailn logo and info

**Comment by asas1232** [comment]
Add BABYCAT logo and info
1000tpt https://hecoinfo.com/tx/0xd9b1e99c2a3e634cdec296fce7a7f8789d9c4176e88fdfb5a6568e7879a7ce54

**Comment by zhujiayu03** [comment]
Please submit the YOLK files to heco folder; 
Unlisted snail token, please submit snail token first, https://www.tokenpocket.pro/zh/submit/token

**Comment by asas1232** [comment]
https://hecoinfo.com/tx/0xf31f85872ea9e4d67b099c1ae997704f5f030b11faaa8c2b55f12a2936765d1a
Add snailn logo and info

**Comment by asas1232** [comment]
Add YOLK logo and info
1000tpt https://hecoinfo.com/tx/0x68df665e831df19084e31258e26a4f2495188b2bfc5c5651cd988f4c7c5f2659

**Pull request merged**
