### PR TITLE
add MNC logo and info

### PR DESCRIPTION
**Pull request by leewenping**
https://bscscan.com/tx/0x0e38871e2ea3d9dfe4e37a7b4c0c0b6eee73d74533a532d293d08e374e331d10

the logo was designed by our designers and we own the copyright. 
by the way MNC has been recorded on HECO of TP.

### CODE REVIEW

**Comment by leewenping** [comment]
the logo was designed by our designers and we own the copyright. 
on the side the MNC has been recorded on HECO of TP.

**Comment by leewenping** [comment]
the logo was designed by our designers and we own the copyright.
by the way MNC has been recorded on HECO of TP.

**Comment by zhujiayu03** [comment]
logo infringement, please resend your image

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
