### PR TITLE
Change RDOG contract and readd logo and info

### PR DESCRIPTION
**Pull request by RobotDogDao**
https://bscscan.com/tx/0x56c5c65350b66d545ebbef7022aaedccafa856d2e87c5996a5eebc35172ebb6c
https://bscscan.com/tx/0xebbc9f5ec7c5f410808d6d51013b0b94ae3af47de5e68366d95e6206f3573bf3

### CODE REVIEW

**Comment by opera0001** [comment]
1、Abnormal token circulation status
2、It is detected that there is a setting that can adjust the rate. Please explain its function.

**Comment by RobotDogDao** [comment]
1.The no.1 holder of the token is the contract address for mapping old RDOG to new RDOG and the dapp link is https://robotdogdao.io/#/RDogmapping . Maybe because of the mapping, the circulation looks abnormal but it has been trading normally on pancake for 5 days and keeps growing.
2.The function to modify the slippage is used to prevent the robot from buying at the opening. It is only used in the first 3 minutes of the opening, and then maintains a 13% slippage, which is known to the community.
Thanks for your review

**Comment by opera0001** [comment]
image
image
Token flow status is abnormal.

**Comment by RobotDogDao** [comment]
This may be caused by a bug in the audit software. Because this token contract has a mechanism that when the currency price rises, the user can sell 5% of the total balance per day, and when the currency price falls, the user can sell 2% of the total balance per dayIn fact, both the Sell tax and the Buy tax are 13%. This can be seen in open source contracts. You can also observe a third-party transaction data monitoring platform. It can be normally sold.
rdog
The open source contract code is at:https://bscscan.com/address/0x3e72A2502E5c3908946EA1807C56f1488e26123F#readContract

**Pull request merged**
