### PR TITLE
Add DNFT logo and info

### PR DESCRIPTION
**Pull request by shya88**
BSC链-代币名称：DNFT- 合约地址：0x8a689d68e237f2c432dcb06966d92e23a1e1e0fd- 支付1000TPT交易哈希值链接：0xffe2ce2ea0fc3fa9a09aac1e0e64d545c99910f3bf3ea39b843d7e42f74c1f68- 简介：Dnft protocol is an NFT for Web 3.0, which allows users to cast and trade across blocks to manage their NFT assets. Encrypted NFT games and meta universe assets are presented through the concept of dnft. Anyone can obtain token rewards through their contribution to the ecosystem.

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Please re-submit these tokens separately and attached the TPT transfer link on [Commit changes].

**Comment by shya88** [comment]
可以加急吗这个文件 ，已经提交了



发自我的iPhone


------------------ Original ------------------
From: guoxintongsam ***@***.***&gt;
Date: Mon,Sep 6,2021 2:56 PM
To: TP-Lab/tokens ***@***.***&gt;
Cc: shya88 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [TP-Lab/tokens] Add DNFT logo and info (#3100)





 
Please re-submit these tokens separately and attached the TPT transfer link on [Commit changes].
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
