### PR TITLE
ADD DCO logo and info

### PR DESCRIPTION
**Pull request by kahshin03**
https://bscscan.com/tx/0x1e51f0037e917bff675d4c6fb82f8559304be29f7010c636a0fc9e34969cc244
https://bscscan.com/tx/0x161d88852b0f72a80ed4d7b264d02804bb3322b5da5d0c90837f55956c094709

### CODE REVIEW

**Comment by opera0001** [comment]
It is detected that the proxy contract is included, which will be very risky. If there are relevant security audit results, you can send it to me for review.

**Comment by opera0001** [comment]
Yes, it would obviously be good to have relevant audit information available.

**Comment by opera0001** [comment]
I still haven't gotten your reply after 2 days, so the order needs to be closed. If you have any problems, you can contact me in issues.

https://github.com/TP-Lab/tokens/issues

**Comment by kahshin03** [comment]
Please allow us to have some time, audit smart contract need time to proceed.

> Yes, it would obviously be good to have relevant audit information available.

**Pull request closed without merging**
