### PR TITLE
Add JBX logo and info

### PR DESCRIPTION
**Pull request by MetaGameaaqq**
https://bscscan.com/tx/0x15b61819815a9e1a29194498c45a1da1057780d9edc4f15bce9252551286ab5e

### CODE REVIEW

**Comment by opera0001** [comment]
May I ask you and https://juicebox.money/ What is your relationship?

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
