### PR TITLE
Add BabyDog logo and info

### PR DESCRIPTION
**Pull request by babydogtoken**
https://bscscan.com/tx/0xfc7906bafc84c7d11f80fdac9dce2746aa13b35a3a0747a58689369d50e3b459?utm_source=tokenpocket

### CODE REVIEW

**Comment by zhujiayu03** [comment]
logo侵权

**Comment by babydogtoken** [comment]
logo未侵权，此logo为我们设计创作还有GIF源文件Baby Dog a new cryptocurrency created by members and fans of Shiba Inu original community,wants to be cared for and loved.Simply Love, pet, and watch your Baby Dog grow.---- On 星期二, 2021-07-20 21:03:02  ***@***.******@***.***> wrote ----  
logo侵权

**Comment by babydogtoken** [comment]
Baby Dog a new cryptocurrency created by members and fans of Shiba Inu original community,wants to be cared for and loved.Simply Love, pet, and watch your Baby Dog grow.



---- 在 星期二, 2021-07-20 21:05:18 babyDogToken ***@***.***> 撰写 ----


为什么我们的logo还没有更新 ，都2周了








Baby Dog a new cryptocurrency created by members and fans of Shiba Inu original community,wants to be cared for and loved.Simply Love, pet, and watch your Baby Dog grow.






---- On 星期二, 2021-07-20 21:03:02 ***@***.******@***.***> wrote ----





logo侵权

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
