### PR TITLE
Adding ZEOS Token 

### PR DESCRIPTION
**Pull request by bngone**
Adding ZEOS Token  Logo and Meta Data.  Thank You.

### CODE REVIEW

**Comment by opera0001** [comment]
Please add the TPT donation hash value.

**Comment by bngone** [comment]
> Please add the TPT donation hash value.

Please How do I donate, and what is the amount?

**Comment by bngone** [comment]
> 

Ok Sir ,understood

**Comment by opera0001** [comment]
Orders need to be closed, you can contact me in issues, link: https://github.com/TP-Lab/tokens/issues

**Pull request closed without merging**
