### PR TITLE
Add AONC Logo and info

### PR DESCRIPTION
**Pull request by bitong1**
https://bscscan.com/tx/0x9e3120b91d0d2a2fafc1ecf38811f288c8488164f2a705a162a18f640aa1d08c

### CODE REVIEW

**Comment by opera0001** [comment]
image
Dear, how did you transfer TPT to the TPT contract address??? This operation does not meet the standard requirements. I am sorry and regret to inform you that you may need to make the donation again.

**Comment by bitong1** [comment]
。。。。。转差了这个必须要重新捐款了嘛

**Comment by opera0001** [comment]
> 。。。。。转差了这个必须要重新捐款了嘛

Yes, dear, because this is not caused by our problem. The tutorial provides very detailed instructions for transferring funds. If you use the TPT token contract address as the receiving address in TokenPocket, you will also receive a prompt message. So, unfortunately.

**Comment by opera0001** [comment]
After you have finished processing, you can contact me through issues. Alternatively, you can resubmit the order, and the review process will be faster this time. It should take about 2 days to complete the token review and inclusion.

**Pull request closed without merging**
