### PR TITLE
Add TAD logo and info

### PR DESCRIPTION
**Pull request by Redf3s**
https://www.bscscan.com/tx/0x510440f6ab076472f72e1555ffa0532c3662148ebefd15652906ddab12ffadcd

### CODE REVIEW

**Comment by Redf3s** [comment]
https://www.bscscan.com/tx/0xbe68e8dfe63aac5a5c24bc42ed37873543ba52d5d03959aa5c3fbf6aa65efc9e

**Comment by opera0001** [comment]
image
The submitted file is not saved in the BSC directory, please adjust it again.

**Comment by Redf3s** [comment]
Just now, it has been uploaded to BSC again. Please check whether it is normal

**Review by Redf3s — COMMENTED** [review]
Add TAD logo and info

**Pull request merged**
