### PR TITLE
Add DND logo and info

### PR DESCRIPTION
**Pull request by sweewu**
BSC - DND - 0x14c358b573a4ce45364a3dbd84bbb4dae87af034 - https://bscscan.com/tx/0x4903801580c62eca8593096194b742e79e8672b7aa688a9e9b41429268f6404c

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Please submit the checksum address that includes uppercase and lowercase characters.

**Comment by sweewu** [comment]
excuse me, our token DND ( 0x14c358b573a4ce45364a3dbd84bbb4dae87af034 )
still don't update its logo, can you help me to chek out?
thanks


guoxintongsam ***@***.***> 于2021年9月7日周二 下午2:42写道：

**Comment by sweewu** [comment]
excuse me, our token DND ( 0x14c358b573a4ce45364a3dbd84bbb4dae87af034 )
still don't update its logo, can you help me to chek out?
thanks

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
