### PR TITLE
add DT logo and info

### PR DESCRIPTION
**Pull request by Hanggi**
BSC - DT - 0x07652BC724A8aE4331c94F0871648202e5E68AD3 - https://bscscan.com/tx/0xb858de323c90a60dfa58f66153ad653b3a5ce9355f2c5c7c5b05291ef90adfad

> why using proxy? and also the ownership of the token

Thank you for your reply.

Proxy is quite popular these days, for example GALA: https://bscscan.com/token/0x7ddee176f665cd201f93eede625770e2fd911990#readContract

The reason why we are using proxy is that we are not only a token project.
We are making a Dapp system which will add many features work around the token.
And also to avoid some vulnerability risk from atacks or bugs.

We will deploy several contracts interact with the token, so we have to keep the ownership to tuning the params.
Of course after deploy all the system contracts we will drop the ownership to make it truely decentralizable.

Please check again.
Thank you.
@giki0318

### CODE REVIEW

**Comment by Hanggi** [comment]
https://github.com/TP-Lab/tokens/pull/5460

**Comment by opera0001** [comment]
There is no problem with your explanation, but we can't predict the result before the problem occurs, so it's best to give it to the facts. It's best to improve the operations you said as soon as possible and realize decentralization faster. Then you submit it again. After the problem is solved, you will pass your logo application. Thank you for your support for tokenpocket.

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
