### PR TITLE
ADD NWD LOGO AND INFO

### PR DESCRIPTION
**Pull request by Zhangsanfeng123789**
BSC-NWD-https://bscscan.com/tx/0x4263345f71580f61a043972144747b4d4f387c420acead6523564d8f1d8ee017

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3579750034

**Comment by sammvio** [comment]
Please submit the checksum address that includes uppercase and lowercase characters.

**Comment by Zhangsanfeng123789** [comment]
BSC-NWD-0xc553578fb98b3857104247538e185a3f773e1f99-https://bscscan.com/tx/0x4263345f71580f61a043972144747b4d4f387c420acead6523564d8f1d8ee017

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
