### PR TITLE
Add BRK logo and info

### PR DESCRIPTION
**Pull request by Linge19494492**
https://hecoinfo.com/tx/0x44a8b0b2b199b41cfd90faa662355cf56f48fad6064a7a0ffd56842b3633899a

### CODE REVIEW

**Comment by sammvio** [comment]
Please donate 3000 TPT as required and submit the transfer link on [Commit changes].

**Comment by Linge19494492** [comment]
@sammvio https://hecoinfo.com/tx/0x14e50790ab798a177c7dcd9ac94d145613af2cefa82e13cdf67360e6e635a14d

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
