### PR TITLE
add ANHEM info and logo

### PR DESCRIPTION
**Pull request by flamees**
https://bscscan.com/tx/0x2483d6388f1582da2ce8b1f1329b9270068f25e05df583b3e4a8305f2c46a8e8

### CODE REVIEW

**Comment by nenrgy** [comment]
专业提交logo,代币，白皮书，诚住经营，值得信赖，价格全网最优！QQ:2099728898
Professional submit logo, scrip, white paper, honestly live operation, reliable, the optimal price cut! QQ: 2099728898

**Comment by sammvio** [comment]
The contract doesn’t verify and published. (No open-source)

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
