### PR TITLE
ADD ClownGirl Coin logo and info

### PR DESCRIPTION
**Pull request by scottccy**
ADD ClownGirl Coin logo and info

### CODE REVIEW

**Comment by zhujiayu03** [comment]
未找到该代币信息收录

**Comment by PiKaChu0121** [comment]
I have the same situation as you. Why does it say that the included information has not been found？

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
