### PR TITLE
Add HTU66 logo and info

### PR DESCRIPTION
**Pull request by Oyyh978**
https://bscscan.com/tx/0x7250236eebea21d0e99f8f90e6fb1d7620d5e16b3d652cd08dc99459a9fa3f60

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:2980874528

**Comment by Oyyh978** [comment]
没通过，有微信吗？



---Original---
From: ***@***.***&gt;
Date: Sun, Dec 19, 2021 14:16 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] Add HTU66 logo and info (PR #4493)




 
专业提交logo！加速审核2小时内包过！QQ:2980874528
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
