### PR TITLE
add HXB logo info

### PR DESCRIPTION
**Pull request by XieLong1**
https://bscscan.com/tx/0x77cf13a4bf07a574afad5d2cf7d2c1a2315a3d66930922a7e1dbee708cc49c96

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token

**Comment by XieLong1** [comment]
Sorry, it's submitted now

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
