### PR TITLE
Add FTD logo and info

### PR DESCRIPTION
**Pull request by 216793036**
https://bscscan.com/tx/0x2af611f75cd2126a2a618ef1e3c5b24ea80ee2880f1c47665802d0c51b8dd982

### CODE REVIEW

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by opera0001** [comment]
Sorry, we don't accept Tron's logo application for the time being. The TPT donation hash value you paid can be submitted to the logo application of other chains. I'm sorry for the inconvenience.

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
