### PR TITLE
Add ASSACC logo and info

### PR DESCRIPTION
**Pull request by ASSACC**
https://bscscan.com/tx/0x26d7555431f337ad4cac29a3ccaf2c1bc788d94475acb577065899fd64d084fa

### CODE REVIEW

**Review by Shahryarmohammadie643 — APPROVED** [review]

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3579750034

**Comment by sammvio** [comment]
EOS token logo upload is not allowed for now.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
