### PR TITLE
LOGO

### PR DESCRIPTION
**Pull request by gsqtoken**
BSC - SDD - 0xC970886CB41Db33a89eF17BD474EE1bacA0bc391 - 

https://bscscan.com/tx/0xa5164594bd71033fc9bf7c493cb75ed4fa1b226ac596f1eb595e89ad3cc3a304

### CODE REVIEW

**Comment by opera0001** [comment]
The TPT hash value you submitted is duplicate with the order #7329. You need to send 0.000007329bnb to 0x7837ae9e4fd6e967f1b8c8824d6288ece6e730f9 address for verification.

**Comment by gsqtoken** [comment]
BSC - SDD - 0xC970886CB41Db33a89eF17BD474EE1bacA0bc391 -

https://bscscan.com/tx/0xa5164594bd71033fc9bf7c493cb75ed4fa1b226ac596f1eb595e89ad3cc3a304

**Comment by gsqtoken** [comment]
BSC - SDD - 0xC970886CB41Db33a89eF17BD474EE1bacA0bc391 - https://bscscan.com/tx/0x97ea714f53771f20d9c3bbbeda4701767c5cb08acdb6db11c2a9311435855a00

**Comment by gsqtoken** [comment]
https://bscscan.com/tx/0xeee3a087ef542b30f2aedadb5af80e258306580257b2b03ad76b97d3385b9427

**Comment by gsqtoken** [comment]
https://bscscan.com/tx/0xeee3a087ef542b30f2aedadb5af80e258306580257b2b03ad76b97d3385b9427

**Comment by opera0001** [comment]
The hash value submitted subsequently and the \7306 order have been repeated twice. This behavior is so bad that you need to remove your token logo. There is a problem https://github.com/TP-Lab/tokens/issues Feedback.

**Pull request merged**
