### PR TITLE
ADD LNG logo and info XCH

### PR DESCRIPTION
**Pull request by mayeio**
logo5
 "name": "XCH",
 "website": "http://xch.xch.cn.com",
 "description": "XCH network is a San Francisco based company dedicated to improving cryptocurrency infrastructure. Our CEO, oppcom, famously invented XCH netwok: one of the first modern distributed network protocols and incentives for bitcoin. Our founding team has experience in cryptocurrency and finance from King, crypto company and lightning lab. By March 1, 2016.",
 "explorer": "https://bsscan.com/token/0xf26dec72e97f3cc0ba656d9d521a3672729bf5a1",
 "type": "BEP20",
 "symbol": "XCH",
 "decimals": 18,
 "status": "active",
 "id": "0xf26dec72e97f3cc0ba656d9d521a3672729bf5a1"
} 

bsc/0xF26dEC72E97f3CC0BA656D9D521a3672729bF5A1/logo.png

### CODE REVIEW

**Comment by tiaojiaotubiaobaoguo** [comment]
代提交logo，24小时内包过，加QQ：2980874528

**Comment by sammvio** [comment]
Please refer to the tutorial, and re-submit your files in the correct format.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
