### PR TITLE
Add SAT info and logo

### PR DESCRIPTION
**Pull request by SAEXIO**
https://bscscan.com/tx/0x2a35706ba7c85cc16d150eec8cfd8fb275ce24eaa194de19afb2ce5bc28c8990
image

submit token repeated ,please update sat logo and info !!!

### CODE REVIEW

**Comment by tiaojiaotubiaobaoguo** [comment]
代提交logo，24小时内包过，加QQ：2980874528

**Comment by sammvio** [comment]
Please donate 3000 TPT as required and submit the transfer link on [Commit changes].

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
