### PR TITLE
Add UCON logn and info

### PR DESCRIPTION
**Pull request by brouniknlyn**
TPT
https://bscscan.com/tx/0x7471b19bef5deb3cfda653dbff3b9d14302749690b033d7e199e43ed10141855 验证
https://bscscan.com/tx/0x575073ef3ec4cff3d99a34fe9268c1f34806070e736ad4c7dc23b884cc97c676

### CODE REVIEW

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Comment by tiancong-netizen** [comment]
Admin and Ownership permissions dropped

**Comment by tiancong-netizen** [comment]
bsc所有跨链的项目检测都会显示可增发，但是管理员地址和权限已经被删除

**Comment by tiancong-netizen** [comment]
All cross-chain project detection of bsc will show that additional issuance is possible, but the administrator address and permissions have been deleted, please pass as soon as possible. Thank you

**Pull request merged**
