### PR TITLE
Update logo & description

### PR DESCRIPTION
**Pull request by JoeDon16**
Update logo & description for $MOONRISE

FEE PAID: https://bscscan.com/tx/0x5fe276e35f5463e3576a56ffc56cffc52dfc4493d85fdb4cf4b7425e08e5aec2

### CODE REVIEW

**Comment by JoeDon16** [comment]
Fee paid: https://bscscan.com/tx/0x5fe276e35f5463e3576a56ffc56cffc52dfc4493d85fdb4cf4b7425e08e5aec2

**Comment by zhujiayu03** [comment]
Please re-submit your files in the correct format.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
