### PR TITLE
Add WIN logo and info

### PR DESCRIPTION
**Pull request by phoenix33139**
转账50000TPT的哈希: https://bscscan.com/tx/0xa0f05486a96a38fad6163dc9d4776a50091f7d34348bde10e9e5cfcc3f863145
验证哈希: https://bscscan.com/tx/0x2b182e63bfee0bdc3915827cdbdcd3d04764e73be70a05cf36571d418d6a9684

### CODE REVIEW

**Comment by opera0001** [comment]
It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

**Comment by phoenix33139** [comment]
合约已经开源

**Comment by opera0001** [comment]
Hidden owner permissions have been detected, which is a very dangerous configuration.

**Comment by opera0001** [comment]
You can continue to communicate with me through issues, but hidden permissions are a very risky feature. Unless you can provide a security report issued by a reputable security company that proves this token is safe, I cannot proceed.

https://github.com/TP-Lab/tokens/issues

**Pull request closed without merging**
