### PR TITLE
Revert "add PGNFT bsc token"

### PR DESCRIPTION
**Pull request by PanguChain**
Reverts TP-Lab/tokens#6135    0xCf55427E6da0e894746b8C06CCB92991550c475E

### CODE REVIEW

**Comment by PanguChain** [comment]
[](url)
pgnft

**Comment by PanguChain** [comment]
logo

**Comment by opera0001** [comment]
#The hash value link of 6135 has been used to add a logo, so if you want to replace a new contract or logo, you can only resubmit a TPT hash value and a new order.

**Comment by PanguChain** [comment]
Re-transfer, hash, send it to you below, is it okay?

**Comment by PanguChain** [comment]
Is it necessary to transfer 30,000 TPT for every update?

**Pull request closed without merging**
