### PR TITLE
add HKT logo and info

### PR DESCRIPTION
**Pull request by gameangrybirds**
BSC - HKT - 0x8355dAAb8550154068c94Cf1d67910fFDA0097A6 - https://bscscan.com/tx/0xf37bc7822af261634ce6e2c0e89c579a7f8f1adc78d6be68783cc9b9d2c6596a

### CODE REVIEW

**Comment by gameangrybirds** [comment]
BSC - HKT - 0x8355dAAb8550154068c94Cf1d67910fFDA0097A6 - https://bscscan.com/tx/0xf37bc7822af261634ce6e2c0e89c579a7f8f1adc78d6be68783cc9b9d2c6596a8

**Comment by opera0001** [comment]
The provided hash value is incorrect, please check carefully.

**Comment by gameangrybirds** [comment]
BSC - 香港电讯 - 0x8355dAAb8550154068c94Cf1d67910fFDA0097A6 - https://bscscan.com/tx/0xf37bc7822af261634ce6e2c0e89c579a7f8f1adc78d6be68783cc9b9d2c6596a

**Review by gameangrybirds — COMMENTED** [review]
BSC - HKT - 0x8355dAAb8550154068c94Cf1d67910fFDA0097A6 - https://bscscan.com/tx/0xf37bc7822af261634ce6e2c0e89c579a7f8f1adc78d6be68783cc9b9d2c6596a

**Comment by gameangrybirds** [comment]
BNBinfo
https://bscscan.com/tx/0xb29791da673b3aac9374d6cc021ab0d48d4e6c8f7ba033e739ee2f18b9c9f04a

**Comment by gameangrybirds** [comment]
BSC - HKT - 0x8355dAAb8550154068c94Cf1d67910fFDA0097A6 - https://bscscan.com/tx/0xf37bc7822af261634ce6e2c0e89c579a7f8f1adc78d6be68783cc9b9d2c6596a

**Comment by gameangrybirds** [comment]
https://github.com/TP-Lab/tokens/pull/9115#issue-1618408000
该链接提交时出BUG,哈希链接最后自动添加了一个字符'8',请帮忙重新拉取合并一下

**Comment by gameangrybirds** [comment]
https://github.com/TP-Lab/tokens/pull/9115#issue-1618408000
There was a bug when the link was submitted, and a character '8' was automatically added at the end of the hash link. Please help to pull and merge again.

**Pull request merged**
