### PR TITLE
Add PFR logo and info

### PR DESCRIPTION
**Pull request by rabinzhangch**
BSC - PFR - 0xe99e6ecfdd7262580f5C54e9fc1145EA1A8ffe69 - https://bscscan.com/tx/0xcc38e2e02a6cb1b2cbcf72d0e3ee282d5c04592ebeabf67ffc88e8fad67f6dbe
AND
BSC - PFR - 0xe99e6ecfdd7262580f5C54e9fc1145EA1A8ffe69 -https://bscscan.com/tx/0x2971e16bb8725229d1bf114e783a724adc6167475da800e57e25e68ceb3007e7

BNB - https://bscscan.com/tx/0x549611b1bf6dac5dc8a766d3d5ef38013e0330d300fee0f72375764eb5e5a08c

### CODE REVIEW

**Comment by rabinzhangch** [comment]
BNB - https://bscscan.com/tx/0x549611b1bf6dac5dc8a766d3d5ef38013e0330d300fee0f72375764eb5e5a08c

**Comment by opera0001** [comment]
Please check the number of TPT submissions, thank you.

**Comment by rabinzhangch** [comment]
> Please check the number of TPT submissions, thank you.

Can I transfer another 50000 TPT

**Comment by rabinzhangch** [comment]
> Please check the number of TPT submissions, thank you.

BSC - PFR - 0xe99e6ecfdd7262580f5C54e9fc1145EA1A8ffe69 -https://bscscan.com/tx/0x2971e16bb8725229d1bf114e783a724adc6167475da800e57e25e68ceb3007e7

50000 TPT has been replenished, totaling 100000 TPT, thank you.

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Pull request merged**
