### PR TITLE
Add Dogc logo and info

### PR DESCRIPTION
**Pull request by Brunnhild**
https://bscscan.com/tx/0xc891b641aaf2b9a7851a05539a8b0cc9726df965ad8a901fe43228acf65e1152

### CODE REVIEW

**Comment by tiaojiaotubiaobaoguo** [comment]
代提交logo，24小时内包过，加QQ：2980874528

**Comment by sammvio** [comment]
Please re-submit your files to bsc folder

**Comment by Brunnhild** [comment]
I re-submitted a new PR, please find it in the end of the queue, thanks a lot.

**Comment by Brunnhild** [comment]
@sammvio

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
