### PR TITLE
Add CTBA logo and info

### PR DESCRIPTION
**Pull request by 3634300264**
BSC－CTBA－0x99343aC3Dc908b45495454A450aBeA3230FCbb52－https://bscscan.com/tx/0xc8dacb234fdc84b453ce56b8bfbdfa10b3251bd458651642139343349a0d6e99

### CODE REVIEW

**Comment by opera0001** [comment]
image
The submitted file is not saved in the BSC directory, please adjust it again.

**Comment by 3634300264** [comment]
浏览器里地址复制就这样怎么更换

**Comment by 3634300264** [comment]
可否说一下那方面的问题吗？我进行修改


---Original---
From: ***@***.***&gt;
Date: Tue, Jun 28, 2022 00:59 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] Add CTBA logo and info (PR #7583)




 

 The submitted file is not saved in the BSC directory, please adjust it again.
 
&mdash;

**Comment by 3634300264** [comment]
是哪里什么问题吗？



---Original---
From: ***@***.***&gt;
Date: Tue, Jun 28, 2022 00:59 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] Add CTBA logo and info (PR #7583)




 

 The submitted file is not saved in the BSC directory, please adjust it again.

**Pull request closed without merging**
