### PR TITLE
Add CS logo and info

### PR DESCRIPTION
**Pull request by sdlyxcc**
TPT hx: https://bscscan.com/tx/0x319587ddad820f39680025a081997860b2207417dd1b49d40ecaf0ac5e328b11  
BNB hx:https://bscscan.com/tx/0xae03adaff5972a5d2fa70900f7f4dbe914ce9c038342166a5c392906a8117c5d

### CODE REVIEW

**Comment by opera0001** [comment]
Proxy contracts are detected, which can be dangerous.

**Comment by sdlyxcc** [comment]
The contract has been open sourced, and the corresponding administrator rights have been discarded. Please agree to it. The TPT to be paid has also been paid successfully. Please review it. If there are other services, please explain. We will cooperate to provide them here. Thanks

**Comment by opera0001** [comment]
We are very sorry, but tokens with proxy contracts cannot be included unless there is a security audit report for the proxy contract.

**Comment by sdlyxcc** [comment]
Which security auditing platform can we use。

**Comment by opera0001** [comment]
Any formal platform is fine.

**Comment by opera0001** [comment]
Orders need to be closed for now, contact me in issues, thanks.

https://github.com/TP-Lab/tokens/issues

**Pull request closed without merging**
