### PR TITLE
ADD META LOGO

### PR DESCRIPTION
**Pull request by btcdao-vip**
BSC - META - 0x2D996A77A979337bf2b28027252d29cDcB742e1b - https://bscscan.com/tx/0x4b5c2cf2a3e1c10413f9c8bc6a5bca873a298819226e75c5116c9539cb9d20eb
BNB desc  tx:
https://bscscan.com/tx/0x50da886d7c87e7fa2a63105894d7c59d6a6bd7f3ae82586c9526146a3ead3224

### CODE REVIEW

**Comment by btcdao-vip** [comment]
BNB desc  tx:
https://bscscan.com/tx/0x50da886d7c87e7fa2a63105894d7c59d6a6bd7f3ae82586c9526146a3ead3224

**Comment by opera0001** [comment]
The contract is not disclosed, and there may be some risks.
Please re submit the logo after adjustment or optimization. Thank you for your support for tokenpocket.

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
