### PR TITLE
Add LaborDoge logo and info

### PR DESCRIPTION
**Pull request by lichenguangtp123**
Transaction ID link:https://bscscan.com/tx/0x887f1cccecd7567068e4f0c9e2005c211bdddb5f559056b6efc16a18763b3a60
Verify the address link:https://bscscan.com/tx/0xb7f9fb9d9a00b61ce96730d8203380e311528f9cf70e9f4352e50d66ac17d0d2

### CODE REVIEW

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by opera0001** [comment]
TPT donation hash value has been used by #6071 order, please check, order will be closed in 24 hours.

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request merged**
