### PR TITLE
Add LOWB logo and info

### PR DESCRIPTION
**Pull request by lvniu001**
Add LOWB logo and info

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Please re-submit your files attached TPT transfer link on [Commit changes].

**Comment by lvniu001** [comment]
https://bscscan.com/tx/0x98a79d2bc34c5838c43d95a455286e938d5be438ee8fe6c7ba8096cd494d4e50

**Comment by lvniu001** [comment]
The above is my TPT transfer link.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
