### PR TITLE
Add OK Logo and Ifo

### PR DESCRIPTION
**Pull request by oknetwork999**
https://bscscan.com/tx/0xbdb6a02be9271398c87fd222affd74713b473b16882803925c33de592773deec
https://bscscan.com/tx/0x57d3bfd5f632d7d49438e79927e3b2dbf5c3c6ea527f614c06990dc03bea0d26

### CODE REVIEW

**Comment by opera0001** [comment]
It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

**Comment by oknetwork999** [comment]
Already open source, please check
https://bscscan.com/address/0x3c54bE79B841fB5E886940D7a861AC11ff389C3e#code

**Comment by opera0001** [comment]
Explain the hidden owner permissions found in the token contract.

**Comment by oknetwork999** [comment]
The rights and interests of the owner address are currently reserved to adjust the handling fee, which is determined based on the DAO community vote. After the subsequent handling fee is adjusted to normal, the owner's rights and interests will be discarded.

**Pull request merged**
