### PR TITLE
Add MOTI logo and info

### PR DESCRIPTION
**Pull request by scsp1064**
https://bscscan.com/tx/0xee3085f9f99fbb5831c1252969c48d0708fbc4f16f2832a12cb3b117f0e61d9d

### CODE REVIEW

**Comment by scsp1064** [comment]
DATA
https://bscscan.com/tx/0xba73d1558b2fe0cca5b8fe4f354289388935bbfb83d30b6486f492e86465edb4

**Comment by nenrgy** [comment]
专业提交logo,代币，白皮书，诚住经营，值得信赖，价格全网最优！QQ:2099728898
Professional submit logo, scrip, white paper, honestly live operation, reliable, the optimal price cut! QQ: 2099728898

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request merged**
