### PR TITLE
SLAM DUNK

### PR DESCRIPTION
**Pull request by SLAMDUNKGAMEFI**
https://bscscan.com/tx/0xf5b292f9cd0b92a012ad0228a2f6713d09fd727ef41f53e07e2c3a433c36cfc0
https://bscscan.com/tx/0xca412c8de1531f4dc390486d2598c305d372eaf92e25a545d590e80db6e38416

### CODE REVIEW

**Comment by SLAMDUNKGAMEFI** [comment]
NICE

**Comment by SLAMDUNKGAMEFI** [comment]
sorry, i want to change the logo file, but i do not know how to do this..
logo
.

**Comment by opera0001** [comment]
image
Please check the path of the submission and the content of the json. You can refer to the tutorial to rearrange it.

CN: https://tphelp.gitbook.io/cn/wallet-operation/submit-token
EN: https://help.tokenpocket.pro/en/developer/how-to-submit-a-token-logo#steps-of-adding-a-token-logo-info

**Comment by opera0001** [comment]
image
The submitted file is not saved in the BSC directory, please adjust it again.

**Pull request closed without merging**
