### PR TITLE
Add FT logo and info

### PR DESCRIPTION
**Pull request by ccc3773**
BSC-FT-0xcc21f75ff719ae44e9acabd59d899c7b364b60c0-https://bscscan.com/tx/0x5ad8dfa2c30330d5e142fb8090874bd186304b3f927b827b44e41b43cead6493

### CODE REVIEW

**Comment by opera0001** [comment]
image
1. The submitted file is not saved in the BSC directory, please adjust it again.

2. The fee rate for selling the token is very high, why is that?

**Comment by ccc3773** [comment]
I found the commit step 4 to be rather unclear. It prevented me from committing to the specified folder.

**Comment by opera0001** [comment]
When you click Fork, you can select the BSC directory and then upload the prepared folder. It’s very easy, dear.

**Pull request closed without merging**
