### PR TITLE
Add SIRE logo and info

### PR DESCRIPTION
**Pull request by coinsire**
https://bscscan.com/tx/0xa2b8e03c788727ae439a47c553488bda4f92a116cd85141ba050994c35ba89b9
https://bscscan.com/tx/0xb91c8e6bd9de096164ac0feef5e902db8a087c5bd44fad998dc9ccbe236810f6

### CODE REVIEW

**Comment by opera0001** [comment]
The detected token purchase fee rate is one hundred percent, what is the purpose of doing this?

**Comment by coinsire** [comment]
Purchases not through pancakeswap, purchases through other smart contracts will be prohibited to prevent arbitrage by clip robots

**Comment by coinsire** [comment]
You can only buy it through pancakeswap's router, but it's not 100% fee

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Pull request merged**
