### PR TITLE
Add LAF logo and info

### PR DESCRIPTION
**Pull request by kejin1208**
https://bscscan.com/tx/0xae88159716d2bd00f38dd8cb4535b3467ae57853e0f5e44d0f1b664406aa596b?utm_source=tokenpocket

### CODE REVIEW

**Comment by zhujiayu03** [comment]
请重新提交checksum合约地址的文件，并知悉1000TPT为一个logo的上传。

**Comment by kejin1208** [comment]
https://bscscan.com/tx/0xd47b466055138078247b8d8eef8157364d5e68eff17e92bbdb01c428452e6f7b?utm_source=tokenpocket

**Comment by kejin1208** [comment]
你好&nbsp; 我应该怎么操作？我是新手




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TP-Lab/tokens"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月5日(星期四) 中午12:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TP-Lab/tokens] Add LAF logo and info (#1995)





 
Closed #1995.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Pull request closed without merging**
