### PR TITLE
ADD MCU INFO and LOGO

### PR DESCRIPTION
**Pull request by jackbob123**

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Please submit TPT transfer link

**Comment by jackbob123** [comment]
https://bscscan.com/tx/0xc6705713b6523b0417165da92a36d63e5285d4d9c60f30f7739e4175f0a67994
https://bscscan.com/tx/0xd34f6e570e392809d403a96441b618a329796f0fe0862fada60dce4de234a270
https://bscscan.com/tx/0x94c42ade4ddc73449e4e88ec14d675fc3a8c03d084b5c0c86fa72349bf6c164d
https://bscscan.com/tx/0xda827032c5bc0b2a7a0d4584b7ef1c21a3499bdf06b79ec20a3e9019a36ad6bd
https://bscscan.com/tx/0xb60286754d66d494ef7745437b1d411a7af63ea0df355da5b5b0dac366b6b64f

**Comment by jackbob123** [comment]
> 请提交TPT转移链接



> 请提交TPT转移链接

https://bscscan.com/tx/0xc6705713b6523b0417165da92a36d63e5285d4d9c60f30f7739e4175f0a67994
https://bscscan.com/tx/0xd34f6e570e392809d403a96441b618a329796f0fe0862fada60dce4de234a270
https://bscscan.com/tx/0x94c42ade4ddc73449e4e88ec14d675fc3a8c03d084b5c0c86fa72349bf6c164d
https://bscscan.com/tx/0xda827032c5bc0b2a7a0d4584b7ef1c21a3499bdf06b79ec20a3e9019a36ad6bd
https://bscscan.com/tx/0xb60286754d66d494ef7745437b1d411a7af63ea0df355da5b5b0dac366b6b64f

**Comment by jackbob123** [comment]
总共是五笔，五个代币都是1000个tpt
https://bscscan.com/tx/0xc6705713b6523b0417165da92a36d63e5285d4d9c60f30f7739e4175f0a67994

https://bscscan.com/tx/0xd34f6e570e392809d403a96441b618a329796f0fe0862fada60dce4de234a270

https://bscscan.com/tx/0xb60286754d66d494ef7745437b1d411a7af63ea0df355da5b5b0dac366b6b64f

https://bscscan.com/tx/0x94c42ade4ddc73449e4e88ec14d675fc3a8c03d084b5c0c86fa72349bf6c164d

https://bscscan.com/tx/0xda827032c5bc0b2a7a0d4584b7ef1c21a3499bdf06b79ec20a3e9019a36ad6bd

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Pull request closed without merging**
