### PR TITLE
Add PP token logo and info

### PR DESCRIPTION
**Pull request by jinghaiying**
https://bscscan.com/tx/0x5b84aa2833ebf641023131926e6a07191d692204db10f35c5f59063f56b765be

### CODE REVIEW

**Comment by opera0001** [comment]
It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

**Comment by jinghaiying** [comment]
> 
Contract code submitted by bscscan has been validated however, and I forgot the compiler version deployed by the contract at the time...

**Comment by jinghaiying** [comment]
> It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

Contract code submitted by bscscan has been validated however, and I forgot the compiler version deployed by the contract at the time...

**Comment by jinghaiying** [comment]
> It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

Since the project has been online, we are in a hurry to finish the ICONS. Can we not update without these ICONS

**Comment by opera0001** [comment]
It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

**Comment by opera0001** [comment]
No change was seen after 2 days, so the order needs to be closed. You can contact me through issues.

https://github.com/TP-Lab/tokens/issues

**Pull request closed without merging**
