### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by aabcdsss1254211465**
0xb15cf9da7d86f73e63b074e6c0e93c9564ec22b11e2b893d33071fb7a2e49585

### CODE REVIEW

**Comment by aabcdsss1254211465** [comment]
BSC-TGE-0xaa76b28f1ba2a61a9e00c51a74869881f4776394-https://bscscan.com/tx/0xb15cf9da7d86f73e63b074e6c0e93c9564ec22b11e2b893d33071fb7a2e49585

**Comment by aabcdsss1254211465** [comment]
BSC-TGE-0xaa76b28f1ba2a61a9e00c51a74869881f4776394-https://bscscan.com/tx/0xb15cf9da7d86f73e63b074e6c0e93c9564ec22b11e2b893d33071fb7a2e49585

**Comment by aabcdsss1254211465** [comment]
BSC-LionCoin-0x4dee35f1f0a2504117ab65d238823f6fa4f9b6b3-https://bscscan.com/tx/0x6a663e5cf1e15977c3da5378088339d88d5c93947d7de7ca98c7e6700030eb77

**Comment by zhujiayu03** [comment]
Added TIGER COIN

**Pull request closed without merging**
