### PR TITLE
Add SpaceDoge logo and info

### PR DESCRIPTION
**Pull request by 264026152**
https://bscscan.com/tx/0xa189712d4617ef3e72aa053d350c242e0cc56bc7e4769bde67dea5f33eca6b53

### CODE REVIEW

**Comment by opera0001** [comment]
#This TPT hash value has been used in 6467 orders. Please check or explain the situation.

**Comment by 264026152** [comment]
> #This TPT hash value has been used in 6467 orders. Please check or explain the situation.



> #This TPT hash value has been used in 6467 orders. Please check or explain the situation.

https://bscscan.com/tx/0xa189712d4617ef3e72aa053d350c242e0cc56bc7e4769bde67dea5f33eca6b53

**Comment by 264026152** [comment]
> #This TPT hash value has been used in 6467 orders. Please check or explain the situation.

https://bscscan.com/tx/0xa189712d4617ef3e72aa053d350c242e0cc56bc7e4769bde67dea5f33eca6b53

**Comment by 264026152** [comment]
> 

https://bscscan.com/tx/0xa189712d4617ef3e72aa053d350c242e0cc56bc7e4769bde67dea5f33eca6b53

**Comment by 264026152** [comment]
> #This TPT hash value has been used in 6467 orders. Please check or explain the situation.

https://bscscan.com/tx/0xa189712d4617ef3e72aa053d350c242e0cc56bc7e4769bde67dea5f33eca6b53

**Comment by 264026152** [comment]
https://bscscan.com/tx/0xa189712d4617ef3e72aa053d350c242e0cc56bc7e4769bde67dea5f33eca6b53



---Original---
From: ***@***.***&gt;
Date: Thu, Mar 31, 2022 00:58 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] Add SpaceDoge logo and info (PR #6479)




 
#This TPT hash value has been used in 6467 orders. Please check or explain the situation.

**Pull request closed without merging**
