### PR TITLE
add Mini Rise info logo

### PR DESCRIPTION
**Pull request by qaaz14566**

### CODE REVIEW

**Comment by qaaz14566** [comment]
HECO-Mini Rise -0x873b2b24843fa719bd94ce21ba050c8016ff8cce - https://hecoinfo.com/tx/0xd131dfd6060f12e7c0229c39d5cf41efe8c0ee0d7afd2c89457d10e3891ace8b

**Comment by qaaz14566** [comment]
HECO-Mini Rise -0xbbc66f6f20773470dfff2e4eb85b45a88848c1d0 - https://hecoinfo.com/tx/0x2a4e3edd37a9e4a94109f0664eb6e443662f7657d2f14d97ee0674e64e9ef7e0

**Comment by qaaz14566** [comment]
HECO-Mini Rise -0xbbc66f6f20773470dfff2e4eb85b45a88848c1d0 - https://hecoinfo.com/tx/0x2a4e3edd37a9e4a94109f0664eb6e443662f71647e7e6e

**Comment by zhujiayu03** [comment]
Please refer to the tutorial and use the checksum contract address as the file name.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
