### PR TITLE
Add DPI logo and info

### PR DESCRIPTION
**Pull request by dpiswap**
https://bscscan.com/tx/0xb67caf60ce746769b4903e34f3a3b1c3a1f64f2a69bd6ebca2ece828592d8791 https://bscscan.com/tx/0xee65d3b9598c36ed1315ef6866ce6f2086305d17ca5dcc256d6781978b71f91e

### CODE REVIEW

**Comment by opera0001** [comment]
Detected the presence of a token issuance setting in the token contract. Please provide an explanation for this.

**Comment by opera0001** [comment]
Three days have passed without seeing your reply, so the order needs to be closed. You can continue to stay in touch with me through issues.

https://github.com/TP-Lab/tokens/issues

**Comment by dpiswap** [comment]
Because DPI does not have an initial issuance quantity, similar to inscriptions, only when users participate, new DPI coins will be generated based on the amount of USDT that users participate in, making DPI completely and uniquely determine the issuance quantity based on the amount of USDT that users participate in. In essence, There is a linear mapping relationship with USDT.
This behavior is executed by a smart contract on the BSC chain. The contract adopts a fixed and public algorithm. The contract will not issue additional DPI outside of these rules to protect the interests of participants.

**Comment by opera0001** [comment]
Done

**Pull request closed without merging**
