### PR TITLE
add mast

### PR DESCRIPTION
**Pull request by MagicDeveloperDocs**

### CODE REVIEW

**Comment by MagicDeveloperDocs** [comment]
https://bscscan.com/tx/0xf7b4740d083c0016a00cf0f2651f7a8a324dfe45ca722432cb1c216bda2983ab

**Comment by MagicDeveloperDocs** [comment]
@[giki0318](https://github.com/giki0318)

**Comment by MagicDeveloperDocs** [comment]
Please deal with it as soon as possible

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request merged**
