### PR TITLE
Add DNFT logo and info

### PR DESCRIPTION
**Pull request by shya88**
BSC链 - 代币名称：DNFT-合约地址：0x8a689d68e237f2c432dcb06966d92e23a1e1e0fd  - 支付1000TPT哈希值链接：0xffe2ce2ea0fc3fa9a09aac1e0e64d545c99910f3bf3ea39b843d7e42f74c1f68  - 简介：Dnft协议是Web 3.0，它允许用户演贸易跨块来管理他们的NFT资产NFT。加密的 NFT 游戏和元宇宙资产通过 dnft 的概念呈现。任何人都可以通过对生态系统的贡献获得代币奖励。【提交更改】修改前的传输链接：https://github.com/TP-Lab/tokens/pull/3100/commits/ad4e800425c0f31f0a9766c9fcc0eb138e0ed3e0?file-filters%5B%5D=#diff-fbfd18b2b42953c0ddbfd4c0dd3d9ddff590f19e73c257577d0b68f57e91f413

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Please re-submit your files attached TPT transfer link on [Commit changes].

**Comment by shya88** [comment]
不是已经重新提交过一次了吗？哪里出错了吗？



发自我的iPhone


------------------ Original ------------------
From: guoxintongsam ***@***.***&gt;
Date: Fri,Sep 10,2021 11:24 AM
To: TP-Lab/tokens ***@***.***&gt;
Cc: shya88 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [TP-Lab/tokens] Add DNFT logo and info (#3189)





 
Please re-submit your files attached TPT transfer link on [Commit changes].
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shya88** [comment]
你好。我这个logo申请怎么还没有消息啊



发自我的iPhone


------------------ Original ------------------
From: guoxintongsam ***@***.***&gt;
Date: Fri,Sep 10,2021 11:24 AM
To: TP-Lab/tokens ***@***.***&gt;
Cc: shya88 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [TP-Lab/tokens] Add DNFT logo and info (#3189)





 
Closed #3189.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
