### PR TITLE
Add SNP logo and info

### PR DESCRIPTION
**Pull request by oneusdt**
https://hecoinfo.com/tx/0xe940ae6956eb3dfa4a30ed021d3bdae1864f31920fb6037eaa6315343ab19822

### CODE REVIEW

**Comment by oneusdt** [comment]
https://hecoinfo.com/tx/0xe940ae6956eb3dfa4a30ed021d3bdae1864f31920fb6037eaa6315343ab19822

**Comment by zhujiayu03** [comment]
Tron token logo upload is not allowed for now.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
