### PR TITLE
Add YTCQ logo and info

### PR DESCRIPTION
**Pull request by zhao199479**
https://hecoinfo.com/tx/0x55c4f8a5d539b188b998e3c88fb07804272e62ba17e1c77149c87d646f21e7cc

### CODE REVIEW

**Comment by nenrgy** [comment]
专业提交logo,代币，白皮书，诚住经营，值得信赖，价格全网最优！QQ:2099728898
Professional submit logo, scrip, white paper, honestly live operation, reliable, the optimal price cut! QQ: 2099728898

**Comment by zhao199479** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by sammvio** [comment]
The official website cannot be opened, please resubmit.

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
