### PR TITLE
Add FAX logo and info

### PR DESCRIPTION
**Pull request by ipfsecology**
https://hecoinfo.com/tx/0x37d8790b79e1b0e4956b76a5a73fd58446f998dc324b07c1896e8163f26d1ef2

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3579750034

**Comment by sammvio** [comment]
We don't support adding custom network logo now, you can add the network following the tutorial..https://help.tokenpocket.pro/en/wallet-operation/how-to-add-custom-network

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
