### PR TITLE
Add YBI logo and info

### PR DESCRIPTION
**Pull request by 81956804**
https://cn.etherscan.com/tx/0x74985effe0826a624827735f27820f9dd001402c7d946af4fc4195c5d67fdada?utm_source=tokenpocket

### CODE REVIEW

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 81956804** [comment]
审核需要多久呢？

**Comment by 81956804** [comment]
审核需要多久呢

**Comment by opera0001** [comment]
The token contract code is not open source, so it is impossible to check whether there are risks. Please give feedback on GitHub after adjustment. The order will be closed in 24 hours.

**Comment by 81956804** [comment]
已调整，重新审核一下。谢谢

**Comment by 81956804** [comment]
> 新
Adjusted again, please review again.

**Pull request merged**
