### PR TITLE
Add MB logo and info

### PR DESCRIPTION
**Pull request by tianliangl2021**
BSC-MB-0x46b29ADB5BBACB967284D1510840FcA61d7F5429-https://bscscan.com/tx/0xedf7743cf2b62bfd0fc99e75f3b2c83d1d193cba2bbcde0e9c17fca3397739be

### CODE REVIEW

**Comment by tiaojiaotubiaobaoguo** [comment]
代提交logo，24小时内包过，加QQ：2980874528

**Comment by sammvio** [comment]
Please refer to the tutorial, and re-submit your files in the correct format.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
