### PR TITLE
Add PIPA logo and info

### PR DESCRIPTION
**Pull request by ZWJKFLC**
BSC - PIPA - 0xe6B41F9f8Ff57F81b8fE237381F9dc370d8Bb1EA - https://bscscan.com/tx/0x2db3d3d31c8479f834f369bf71f0d6b757f91ba9390d4e850510d35cccd5f00a

### CODE REVIEW

**Comment by opera0001** [comment]
The contract does not give up ownership, so there are certain risks

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
