### PR TITLE
Add MET logo and info

### PR DESCRIPTION
**Pull request by linsrin**
{
 "name": "Metaverse",
 "website": "http://ytlds.fzrtcz.com/h5/#/",
 "description": "Gamefi - ATLANTIS - Uniquely specified Token.",
 "explorer": "https://bscscan.com/token/0x4e0ce944729afa118dc1798c4c10ec8694b609ed",
 "type": "BEP20",
 "symbol": "MET",
 "decimals": 18,
 "status": "active",
 "id": "0x4E0Ce944729afa118dc1798C4C10EC8694b609ED"
  "tx": "https://bscscan.com/tx/0x78d05fc3e8a4e3fd73f7826525b385129d23e15f8040370887f054c57f430266/"
}

### CODE REVIEW

**Comment by opera0001** [comment]
Submission format error (duplicate), please submit again.

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
