### PR TITLE
ZTK

### PR DESCRIPTION
**Pull request by hell176**
https://bscscan.com/tx/0x636d0442d7cd8230446ffbb963cc7fbbab1587b8ca66d858e6b761adc2490bef

### CODE REVIEW

**Comment by hell176** [comment]
Add ZTK logo and info

**Comment by opera0001** [comment]
It was detected that the token has a risk of increased issuance, so you need to provide an explanation.

**Comment by hell176** [comment]
Do I need to pay 5000TPT again if I change the contract?

**Comment by hell176** [comment]
> It was detected that the token has a risk of increased issuance, so you need to provide an explanation.
Do I need to pay 5000TPT again if I change the contract?

**Comment by opera0001** [comment]
> > It was detected that the token has a risk of increased issuance, so you need to provide an explanation.
> > Do I need to pay 5000TPT again if I change the contract?

There's no need to repay again. Perhaps you can tell me the purpose of the token issuance increase setting. I'm just trying to ensure that the token contract can be as secure as possible.

**Comment by hell176** [comment]
Ok, our community is discussing whether to cancel the additional issue, may change the contract, is still under discussion.

**Comment by opera0001** [comment]
Then I think I can wait for you for two days. I hope there will be a result within this time frame.

> Ok, our community is discussing whether to cancel the additional issue, may change the contract, is still under discussion.

Then I think I can wait for you for two days. I hope there will be a result within this time frame.

**Comment by opera0001** [comment]
The order has been waiting for too long, so it needs to be closed. However, you can still keep in touch with me through issues and continue to complete this order.

https://github.com/TP-Lab/tokens/issues

**Pull request closed without merging**
