### PR TITLE
Add MGC logo and info

### PR DESCRIPTION
**Pull request by magicofuniverse**
https://bscscan.com/tx/0x98db0acbc647cb688cd3d01740b5a6cdd5fdab594ac6a000ee44e6bfec21233f

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:2980874528

**Comment by sammvio** [comment]
Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token

**Comment by magicofuniverse** [comment]
> Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token

I have submit the token info. Can you check again

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
