### PR TITLE
Add TPT logo for Floki Shiba Inu

### PR DESCRIPTION
**Pull request by FlokiShib**
Floki Shiba Inu TPT logo

### CODE REVIEW

**Comment by bisonswap** [comment]
yes

**Comment by FlokiShib** [comment]
hello already paid what do i do next?

**Comment by zhujiayu03** [comment]
Please submit the files to bsc folder

**Comment by FlokiShib** [comment]
hello how to add ? i keep getting problem

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Pull request closed without merging**
