### PR TITLE
Add FOMO logo and info

### PR DESCRIPTION
**Pull request by fomodaotoken**
TPT - https://bscscan.com/tx/0x2ac01ecc9c1a810733f24c696f0b4954423fc455cae8d8febc87ff066b809b23
BNB - https://bscscan.com/tx/0xc3f69aa37c15bcba00d6d06e828f1cbf7f63a1fd58843de88d0c83ca01d02671

This is an update from the previous #7140 where we change accordingly.

### CODE REVIEW

**Comment by opera0001** [comment]
Token circulation status is abnormal.

**Comment by opera0001** [comment]
Token circulation status is abnormal.

**Comment by fomodaotoken** [comment]
The token circulation is correct, please check again @opera0001

**Comment by opera0001** [comment]
0x5dd4eC212bd8e9fa42d278e09b6d6857E4aBaeCa

image
image
image

**Pull request merged**
