### PR TITLE
Add CPB logo and info

### PR DESCRIPTION
**Pull request by netlocks**
https://bscscan.com/tx/0x0f6f914c0ed1c7a7cbd8c9a8dfd4195c151403937de17de104ac5966fa8377a3
https://github.com/TP-Lab/tokens/pull/5336 update
Modify the contract before TPT according to the prompt

### CODE REVIEW

**Comment by netlocks** [comment]
update token  0xd496ca047647abce8b57a03dbd47cdbf090fb03e

**Comment by netlocks** [comment]
Use None if the URL is wrong

**Comment by opera0001** [comment]
1. No capital flow pool found
2. More concentrated tokens
3. Tokens are not other public chain mapped tokens
4. Tokens have not been launched on other centralized trading platforms
Please re submit the logo after adjustment or optimization. Thank you for your support for tokenpocket

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
