### PR TITLE
Upload logo for HY

### PR DESCRIPTION
**Pull request by hyswap**
TPT - https://bscscan.com/tx/0x1579f8ce4c686230015d7341a7544d97764f016b1af337c9c962de744451c8a0 BNB - https://bscscan.com/tx/0xebb71a0042384d92bce0cd05745c09dfeffd3d5d6943b69bba6c6acf7c1f0fd2

### CODE REVIEW

**Comment by opera0001** [comment]
image
1、The submitted file is not saved in the BSC directory, please adjust it again.
2、It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

**Comment by hyswap** [comment]
1. This is a HECO Chain Token. Please confirm.

**Comment by hyswap** [comment]
How should I readjust it? @opera0001

**Comment by opera0001** [comment]
It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

**Comment by hyswap** [comment]
We will upload the audit report to here in short. Please wait for us @opera0001

**Comment by opera0001** [comment]
Okay no problem.

**Pull request closed without merging**
