### PR TITLE
Add MUR logo and info

### PR DESCRIPTION
**Pull request by Mur-Token-BSC**
We Will Make You Rich By Our farms and Pools Coming Soon...........

### CODE REVIEW

**Comment by Mur-Token-BSC** [comment]
BSC - MUR - https://bscscan.com/tx/0x944120c752dcfef25fcb3dd01d1b210106a15a13e6a88c039ed6c1451e0a4ada

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3579750034

**Comment by Mur-Token-BSC** [comment]
On Mon, 3 Jan 2022 at 1:04 PM, jiasutijiao ***@***.***> wrote:

> Hi I don't wanna add this token I have stopped this project and it's no
more






专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
