### PR TITLE
Renew ACE logo from 600*600 to 256*256

### PR DESCRIPTION
**Pull request by Kelvinorin**
Renew the logo.png. Old one is 600x600 pixels. The new one is 256x256

### CODE REVIEW

**Comment by opera0001** [comment]
Have you submitted the token contract address or the number submitted by GitHub?

**Comment by Kelvinorin** [comment]
Yes. I have submitted the token contract address already.

**Comment by opera0001** [comment]
I don't see the content of the JSON file you submitted. Please check again.

**Comment by Kelvinorin** [comment]
I just renew the logo.png. the JSON file is the same as before I have uploaded.

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request merged**
