### PR TITLE
Add DOG logo and info

### PR DESCRIPTION
**Pull request by wowodogdog**
https://bscscan.com/tx/0x80afef92f05bf6eaec7b2e69a57cac745e935a9d58c1cac7e0e6b09150208cb1

### CODE REVIEW

**Comment by opera0001** [comment]
There are no other operations after the token is issued, and the security cannot be determined. Please re submit the logo after adjustment or optimization. Thank you for your support for tokenpocket.

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
