### PR TITLE
Change LOGO

### PR DESCRIPTION
**Pull request by LemonDAO6**
This contract of ours has a loophole and has been deprecated. Now I want to delete the logo and info related to this contract.

### CODE REVIEW

**Comment by opera0001** [comment]
The hash value link has been used in order #7441, if a similar problem is found again, we will control the tokens or account you submit.

**Comment by LemonDAO6** [comment]
This contract has been voided, we just want to delete the previous LOGO,
what should I do?

opera0001 ***@***.***> 于2022年7月4日周一 10:23写道：

**Comment by LemonDAO6** [comment]
> The hash value link has been used in order #7441, if a similar problem is found again, we will control the tokens or account you submit.

0x07033A47CD01e8cf8bC67302554906b63eA03330 is our old contract, which we have deprecated due to loopholes in the contract.
User data is remapped to the new contract. We have filed an application to delete the LOGO information on 0x07033A47CD01e8cf8bC67302554906b63eA03330, but the method may be wrong and it has not been implemented yet.
We have paid 50000TPT and hope to enable this LOGO and INFO on the new contract, so please delete this logo and info of the old contract at 0x07033A47CD01e8cf8bC67302554906b63eA03330.

**Comment by LemonDAO6** [comment]
Really Thank You

opera0001 ***@***.***> 于2022年7月6日周三 16:53写道：

**Pull request merged**
