### PR TITLE
logo

### PR DESCRIPTION
**Pull request by 18112221631**

### CODE REVIEW

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by opera0001** [comment]
0x1784FE238E34dDCCb3870f34162F34d41e19e0A6--

1. The main character of the token logo is suspected of infringement (previously prompted)
2. It is found that the ownership function can be retrieved (prompted before)
3. It is found that there may be a switch to control the transaction (prompted before)
4. Token contract needs to give up ownership (recommended)

0x30699E201b99dbBC920Ca41731779fE470184077--

1. Token contract needs to give up ownership (recommended)
2. It is found that the ownership function can be retrieved (prompted before)
3. It is found that there may be a switch to control the transaction (prompted before)

0x4b1fd2b442d24fb410a45fea93461d3495efb322--Done

0xD43b61dAa9205a8627CfdAE1F71A169104207D26--

1. Token contract needs to give up ownership (recommended)
2. It is found that the ownership function can be retrieved (prompted before)
3. It is found that there may be a switch to control the transaction (prompted before)
4. The submitted logo is not 256x256 pixels

0xe3bf6603babeabc3192bc87558964374705071d7--Done

0x5469d9d359f92F8f40050231d69ECd97b5b5B38C--

1. Token contract needs to give up ownership (recommended)
2. It is found that the ownership function can be retrieved (prompted before)
3. It is found that there may be a switch to control the transaction (prompted before)

0xBA9D8f8659059569B739D4Ba62781311731944b0--

Insufficient token liquidity pool.

TEn7CaopcXcMHPnBMWigczqhG522M7MbgZ

TFB7VqVCNLzHw87EZ7RjqNBmpYPtGYuYqf

The token logo of Tron cannot be operated temporarily.

**Comment by opera0001** [comment]
Please be informed that 30000 TPT donation fee is required to resubmit the logo application.

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
