### PR TITLE
add PIFI logo and info

### PR DESCRIPTION
**Pull request by PiFinance**
https://bscscan.com/tx/0xf332b87a20365dbad1d0f9087984e04074f1135334eb91d54dd289388ebaffea
https://bscscan.com/tx/0xf4c6240b3b4a020521dcbcbcc987bc0b3026e3707d7e929c2ad37eba1386d596

### CODE REVIEW

**Comment by opera0001** [comment]
A setting that can modify the rate is detected, please explain what it does.

**Comment by fitape** [comment]
> A setting that can modify the rate is detected, please explain what it does.
u mean that the tax can be adjusted?

**Comment by fitape** [comment]
> u mean that the tax can be adjusted?
> Now tax is 10%. but we will list on Exchange, so need adjust tax.
> We will renounce ownership after launching.

u mean that the tax can be adjusted?
Now tax is 10%. but we will list on Exchange, so need adjust tax.
We will renounce ownership after launching.

**Comment by fitape** [comment]
> A setting that can modify the rate is detected, please explain what it does.
u mean that the tax can be adjusted?
Now tax is 10%. but we will list on Exchange, so need adjust tax.
We will renounce ownership after launching.

**Pull request merged**
