### PR TITLE
Revert "add PGNFT bsc token"

### PR DESCRIPTION
**Pull request by yuxiansegn**
Reverts TP-Lab/tokens#6135

### CODE REVIEW

**Comment by yuxiansegn** [comment]
Please delete the wrong contract 0xbcb4308F59afd008424EFb23c9407Db3E6Aa0536

correct contract
0x694DF947A7560eB0Fb5005BB2A4290E18d0c5A4e

**Comment by opera0001** [comment]
image

The submitted format is still incorrect. Please fill in and upload the content in strict accordance with the requirements of the tutorial. Please update the content as soon as possible. The order will be closed in 24 hours.

**Comment by opera0001** [comment]
https://tphelp.gitbook.io/cn/wallet-operation/submit-token

**Comment by yuxiansegn** [comment]
Please admin, check the record #6135, it has been responded, you have also checked, but there is an error when updating

**Comment by yuxiansegn** [comment]
But that order has not been closed by you. This is a new request from my association reply.

**Comment by yuxiansegn** [comment]
Admin, can you express it clearly?

**Comment by yuxiansegn** [comment]
Admin, can you see my description

**Comment by opera0001** [comment]
done

**Comment by PanguChain** [comment]
Hello admin, please update the new contract


0xCf55427E6da0e894746b8C06CCB92991550c475E




---Original---
From: ***@***.***&gt;
Date: Tue, Mar 15, 2022 11:03 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] Revert "add PGNFT bsc token" (PR #6175)




 
Closed #6175.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by PanguChain** [comment]
There are some problems with the original contract, please remove it



New contract address: 0xCf55427E6da0e894746b8C06CCB92991550c475E and new logo




---Original---
From: ***@***.***&gt;
Date: Tue, Mar 15, 2022 11:03 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] Revert "add PGNFT bsc token" (PR #6175)




 
Closed #6175.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request closed without merging**
