### PR TITLE
Add XR logo and info

### PR DESCRIPTION
**Pull request by tptouxiang**
3000TPT转账链:：https://bscscan.com/tx/0xa7c4213d95ca79220162111be158e6679aacf028ac1b58ccc7ff4925712c75ec

### CODE REVIEW

**Comment by opera0001** [comment]
No liquidity pool has been added。

Please re adjust and continue to apply for the token logo. Thank you very much for your recognition of tokenpocket

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
