### PR TITLE
Add CsDoge logo and  info

### PR DESCRIPTION
**Pull request by constellation-doge**
Add CsDoge logo and  info

### CODE REVIEW

**Comment by opera0001** [comment]
The TPT hash value link is not seen.

**Comment by constellation-doge** [comment]
I have sent the transaction to your address with signed message

**Comment by constellation-doge** [comment]
BSC - CsDoge - 0x1642C5E36822Ad371bDba3aF81F9840a456A0969 - https://bscscan.com/tx/0x609cb6451cd29102e191e7f7f6c26ab713099ef03b1fd25ee6747b7224a9a6a7

TPT Tx:
https://bscscan.com/tx/0x609cb6451cd29102e191e7f7f6c26ab713099ef03b1fd25ee6747b7224a9a6a7

**Comment by constellation-doge** [comment]
Signed Hash: 
https://bscscan.com/tx/0x3861f397e54969920391e2bbacce2e8a92ede45ad13891407afc4e563f859c9a

**Comment by constellation-doge** [comment]
hello?

**Comment by constellation-doge** [comment]
Hello?

**Comment by constellation-doge** [comment]
Execuse me?

**Comment by opera0001** [comment]
The switch that can suspend the transaction and modify the rate is detected, which will be at risk.

**Comment by opera0001** [comment]
Token circulation status is abnormal.

**Pull request closed without merging**
