### PR TITLE
add KBX logo and info

### PR DESCRIPTION
**Pull request by KBX007**
TPT transfer hash:https://hecoinfo.com/tx/0x375c4988dcc25fca7bd70f7bcdbd0af2258751b3f37c92e791edeafb93031a7c
HT transfer hash:https://hecoinfo.com/tx/0x379bcce9468a09f64ab6a864295ab1999f9379ae3c7daf74465e7dddacf513a1

### CODE REVIEW

**Comment by opera0001** [comment]
It is detected that the transaction can be suspended. Please explain the situation.

**Comment by KBX007** [comment]
> It is detected that the transaction can be suspended. Please explain the situation.


This is a robot killer，The owner permission will be released later

**Comment by KBX007** [comment]
> It is detected that the transaction can be suspended. Please explain the situation.
This is a security control method we set up when issuing tokens. It is a protection measure to prevent tokens from being stolen or attacked. It can largely protect the users' assets security

**Comment by KBX007** [comment]
> It is detected that the transaction can be suspended. Please explain the situation.

This is a security control method we set up when issuing tokens. It is a protection measure to prevent tokens from being stolen or attacked. It can largely protect the users' assets security

**Pull request merged**
