### PR TITLE
Add NB logo and info

### PR DESCRIPTION
**Pull request by nuoyan2022**
https://bscscan.com/tx/0x0fef4f0d58cfe1689cdf0e185cbc5599f04d48bc5863d8163b65d25a5e1354b5
https://bscscan.com/tx/0x00f5bf3411a4b0001c731a3eb4e5ea8b63e649280b0b6e412c0670339f4a780d

### CODE REVIEW

**Comment by opera0001** [comment]
The logo submitted in the order is the same as the #6747 order logo, please explain.

**Comment by nuoyan2022** [comment]
> The logo submitted in the order is the same as the #6747 order logo, please explain.

They are the same token, the old contract has given up ownership, there is no way to fix the code error, so the contract needs to be updated, the official website has updated the new contract https://www.nuclearbomb.vip/

**Comment by nuoyan2022** [comment]
> The logo submitted in the order is the same as the #6747 order logo, please explain.

**Comment by hanssllson** [comment]
> The logo submitted in the order is the same as the #6747 order logo, please explain.

This is the ID of the original application, please review and approve, thank you

**Comment by nuoyan2022** [comment]
> The logo submitted in the order is the same as the #6747 order logo, please explain.

https://coinmarketcap.com/currencies/nuclear-bomb/
CMC

**Comment by opera0001** [comment]
Does the logo of the old contract need to be deleted?

**Pull request merged**
