### PR TITLE
Add FPT logo and info

### PR DESCRIPTION
**Pull request by ftprediction**
https://bscscan.com/tx/0x4fcf456c52b19cc749353fa92a9f698d9e0c24dbc4a38bab0a8488541f8af0a5

### CODE REVIEW

**Comment by fptnft** [comment]
This is a mistake. Please let me upload it again

**Comment by fptnft** [comment]
This is a mistake. Please let me upload it again

**Comment by opera0001** [comment]
Then I'll restore both to the default, and then close the GitHub order. You can submit it again.

**Comment by fptnft** [comment]
Thank you very much

**Comment by tplogotijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by ftprediction** [comment]
https://github.com/TP-Lab/tokens/pull/6241   This is my resubmission. Please let me pass

**Pull request merged**
