### PR TITLE
Add CCC logo and info

### PR DESCRIPTION
**Pull request by panxianhai**
https://bscscan.com/tx/0xb2937433254f7464bf4d3ffaa191ed3a9398314972adaab7c9f99a2a37dcb3a7

### CODE REVIEW

**Comment by tubiaoyingji** [comment]
专业加快提交LOGO，20分钟内审核包过，QQ：1450001284

**Comment by sammvio** [comment]
Please donate 3000 TPT as required and submit the transfer link on [Commit changes].

**Comment by panxianhai** [comment]
@sammvio I have resubmit here.https://github.com/TP-Lab/tokens/pull/4294

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
