### PR TITLE
Add LYC logo and info

### PR DESCRIPTION
**Pull request by a123465**
TPT交易链接：https://bscscan.com/tx/0xc0b7678f16ba3ab6c76f841a92d62f13a8b2a503fe72eae144b2ba908fb63baa
验证链接：[https://bscscan.com/tx/0xcfdb15f439a960badf31675fe1c2cf355ecd59a06bdae2a](https://bscscan.com/tx/0xcfdb15f439a960badf31655fe1c2cf07da15a068a2e553d967a6b6da935ec558)

### CODE REVIEW

**Comment by opera0001** [comment]
This token contract has a code that states that it cannot be sold. Maybe this is a honeypot.

**Comment by a123465** [comment]
> This token contract has a code that states that it cannot be sold. Maybe this is a honeypot.

Can be traded through PancakeSwap

**Comment by opera0001** [comment]
The fact that you can trade at pancakeswap does not mean that it is absolutely safe, please check the code carefully.

**Comment by opera0001** [comment]
Orders need to be closed, contact me in issues with questions, thanks.

https://github.com/TP-Lab/tokens/issues

**Pull request closed without merging**
