### PR TITLE
add META logo and info

### PR DESCRIPTION
**Pull request by elonmusk888**
哈希值：0x60e6bd7571ecfae5b6d88ac2016d99a8c149679251acd312fb0a3392e0efc641
BSC-META-0x566f47bf6e0Fd69cD97Da548573A6127C18cE1c0-https://bscscan.com/tx/0xd1489a0175d81160d737a4e6f0cc3c3083f37faba0bfa4e8d8d45bce9d85da46

### CODE REVIEW

**Comment by giki0318** [comment]
logo infringement with Meta(previously facebook)

**Comment by jjjgjk** [comment]
1212在吗

**Comment by jjjgjk** [comment]
你好

**Comment by tplogotijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
