### PR TITLE
ADD fmc LOGO AND INFO

### PR DESCRIPTION
**Pull request by koolew1110**
ADD fmc LOGO AND INFO

### CODE REVIEW

**Comment by koolew1110** [comment]
https://etherscan.io/tx/0x240ddef744fb92587e97f76921e759ae02538ded687c9ca12feb658a33a685d0

**Comment by koolew1110** [comment]
https://www.bscscan.com/tx/0xed27be0cb166a1c9baafc2c0cb290fafbae1b089625161d3c328676cc8c3a39c

**Comment by koolew1110** [comment]
ADD fmc LOGO INFO
100000tpt https://etherscan.io/tx/0x240ddef744fb92587e97f76921e759ae02538ded687c9ca12feb658a33a685d0
verify  https://www.bscscan.com/tx/0xed27be0cb166a1c9baafc2c0cb290fafbae1b089625161d3c328676cc8c3a39c

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Pull request merged**
