### PR TITLE
Add F3dog logo and info

### PR DESCRIPTION
**Pull request by weidor**
https://bscscan.com/tx/0x411fc1e1e955d8d641ada6d2270d72098eb5c40b2c5c60e75fe4cdef7ca8d687;https://bscscan.com/tx/0x5d2018ea28c9e2ac49f7f24165f00adbc3baae677a0e86bb42af51bc15dc4da9

### CODE REVIEW

**Comment by opera0001** [comment]
1. Contract ownership not abandoned
2. Logo is not 256x256 pixels

**Comment by lichenguang123** [comment]
1	+{	
2 +“名称”:“Fomo3dDog”，
3+“网站”:“http://www.f3dog.info ”,
4+“描述”:""Fomo3dDog是Fomo3dDo的新游戏，由大领衔，100个社区推广，放弃合约所有权，无鼠标房，公平上线，玩家共有，让Fomo3dDoe翻千倍惊人的”，
5+“探索者”:“https://bscscan.com/token/0x58db7380288bd21697b948083e089f987bde530e”,
6
+“类型”:“BEP20”，7+ “符号”:“ F3dog”,8 +“小数”:18，9 +“状态”:“活动”，
10+“id”:“0x58db7380288bd21697b948083e089f987bde530e”
mmexport1645792988268

**Comment by opera0001** [comment]
You need to replace info.json  file and logo. This is a very simple thing for developers. We must remember that the logo is 256x256 pixels.

**Comment by lichenguang123** [comment]
5f312919e4874451334daf8c70b1ba7b
（备注）合约地址已经锁池：0x58db7380288bd21697b948083e089f987bde530e

**Comment by lichenguang123** [comment]
The address of the risk contract has been modified, and the modified contract address is 0x58db7380288bd21697b948083e089f987bde530e

**Pull request merged**
