### PR TITLE
add star

### PR DESCRIPTION
**Pull request by lcwypn**
https://bscscan.com/tx/0xe9b4d8ea21c57709e201231955703ea6dc276ab9e1e396dadc9eb21a32bfd862
https://bscscan.com/tx/0x32ac6db8ab7faeca5b92634e9c272686f73168a863f55ccfdf526c78414c0dc2

### CODE REVIEW

**Comment by opera0001** [comment]
The token contract contains multiple configuration switches, among which, incorrect usage of the token issuance increase could pose significant risks. 

(Note: The provided text appears to be related to cryptocurrency or blockchain technology.)

**Comment by lcwypn** [comment]
> The token contract contains multiple configuration switches, among which, incorrect usage of the token issuance increase could pose significant risks.
> 
> (Note: The provided text appears to be related to cryptocurrency or blockchain technology.)

The reason for the additional issuance is that our tokens need to be minted by users themselves, which is an important element of the project ecosystem. When the mint reaches 1 million, this function will stop.

**Comment by lcwypn** [comment]
The reason for the additional issuance is that our tokens need to be minted by users themselves, which is an important element of the project ecosystem. When the mint reaches 1 million, this function will stop.

**Comment by opera0001** [comment]
The token has not yet begun trading, so no risks have been identified. We hope to proceed according to the regular process, and if any issues are discovered, we will promptly address them concerning the token.

**Pull request merged**
