### PR TITLE
ADD WMP logo and info 

### PR DESCRIPTION
**Pull request by FLL392670505a**
https://bscscan.com/tx/0x8decac7eb42a36abe0d359e93bb5f8aae91516e1e46932f1aa28dce1c8282666

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Please re-submit your files attached two TPT transfer links on [Commit changes].

**Comment by guoxintongsam** [comment]
Please re-submit your files attached to two TPT transfer links on [Commit changes]. Please submit your first token https://www.tokenpocket.pro/zh/submit/token

**Review by FLL392670505a — COMMENTED** [review]
https://bscscan.com/tx/0x68413da32eb9a89422899313a4d3cb955a8a317dfa575e954e1474a2deb45f91

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
