### PR TITLE
Add IXBTC logo and info

### PR DESCRIPTION
**Pull request by longbac18**
https://www.bscscan.com/tx/0xf69ebd3b99f83638d2a27cec618a134516be8fd1d1ca76e0e1abd8af8abc3883

### CODE REVIEW

**Comment by jjjgjk** [comment]
1212在吗

**Comment by jjjgjk** [comment]
你好

**Comment by longbac18** [comment]
你好



---Original---
From: ***@***.***&gt;
Date: Sat, Mar 12, 2022 18:48 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] Add IXBTC logo and info (PR #6103)




 
Merged #6103 into master.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tplogotijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request merged**
