### PR TITLE
Add OPPA token logo and info

### PR DESCRIPTION
**Pull request by oppaghost**
Add the the token log and info for the following asset. 

Here is the payment / donation transaction id on bscscan: 0x71859b57ae3b11801b5f46041c57778d2acd23936f1a0887133dc4516943e1be

### CODE REVIEW

**Comment by nenrgy** [comment]
专业提交logo,代币，白皮书，诚住经营，值得信赖，价格全网最优！QQ:2099728898
Professional submit logo, scrip, white paper, honestly live operation, reliable, the optimal price cut! QQ: 2099728898

**Comment by sammvio** [comment]
Please submit the checksum address that includes uppercase and lowercase characters.

**Comment by oppaghost** [comment]
hi @sammvio  . 

May I get some clarifications on what address are you referring to here. I believe I sent you the one that shows the transaction. 

This has been the 3rd time we are applying for this, and we really want to get a proper listing and icon. Please advise on what else is missing from the information that we shared.

**Comment by oppaghost** [comment]
HI @nenrgy , 

I would like to follow up on this request. I requested for some clarification on what address it is that you are looking for. We have already sent you the transaction address for this application.

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
