### PR TITLE
ADD VIA info and logo

### PR DESCRIPTION
**Pull request by lcwypn**
https://bscscan.com/tx/0x3dcab738fecfaca4b2b0fc4d748f0cc41a7d9ecad8cdbc7f09cf1a0d5aa26b6a
https://bscscan.com/tx/0x7c1a85590b2859fad595a1548161e9d90c388bca21c8cfdcee42257643ed187b

### CODE REVIEW

**Comment by opera0001** [comment]
Only one logo order can be submitted at a time, so you will need to determine which contract address to include this time. The other one needs to be resubmitted.

**Comment by lcwypn** [comment]
> 一次只能提交一个徽标订单，因此您需要确定这次要包含的合约地址。另一份需要重新提交。

The token VIS submitted this time, the contract address: 0x88888b6Bad5B7B3b1B924A19cB452E658DdF8207

**Comment by lcwypn** [comment]
The token VIS submitted this time, the contract address: 0x88888b6Bad5B7B3b1B924A19cB452E658DdF8207

**Comment by opera0001** [comment]
The presence of a token increase issuance setting is detected, please explain what it does.

**Comment by lcwypn** [comment]
> The presence of a token increase issuance setting is detected, please explain what it does.

While destroying, casting, nft pledge reward casting, the mechanism is like this, the same model as gmt

**Comment by lcwypn** [comment]
While destroying, casting, nft pledge reward casting, the mechanism is like this, the same model as gmt

**Pull request merged**
