### PR TITLE
Add BSC token - Xpense / XPE

### PR DESCRIPTION
**Pull request by mrmikeo**
Token information and logo for Xpense / XPE

### CODE REVIEW

**Comment by opera0001** [comment]
Please provide the required hash link.

**Comment by mrmikeo** [comment]
Hello.  Im a little confused about that.   Do i have to send the TPT donation from the TokenPocket app, or can i sent it to the donation address from gateio?

**Comment by opera0001** [comment]
Both of these processing methods are acceptable.

**Comment by mrmikeo** [comment]
Ok sent.  BSC

0x845394fbffbf4e08dec19d27fd48203129ecfbb568c3d181e5c9d3ab0e163c13

**Pull request merged**
