### PR TITLE
desert

### PR DESCRIPTION
**Pull request by Desertprot**

### CODE REVIEW

**Comment by opera0001** [comment]
There are many kinds of control switches in token contracts, which will have certain risks. Have you considered discarding the control right?

**Comment by Desertprot** [comment]
> 

yes，discarding the control

**Comment by Desertprot** [comment]
> There are many kinds of control switches in token contracts, which will have certain risks. Have you considered discarding the control right?

yes，discarding the control

Do I need to provide any more information?

**Comment by opera0001** [comment]
Not for the time being.

**Comment by opera0001** [comment]
Thank you for your feedback.

**Comment by Desertprot** [comment]
> Not for the time being.

hello，When will LOGO be approved?

**Comment by Desertprot** [comment]
hello，Do I need to deal with anything?

**Comment by Desertprot** [comment]
> Not for the time being.

hello，Do I need to deal with anything?

**Pull request closed without merging**
