### PR TITLE
Add MYES logo and info

### PR DESCRIPTION
**Pull request by myestoken**
please refer to fill commits on 28 FEB

434198c8b16ffc0a1cb27b150a3700ac3d396dbb

3000 TPT donation tx https://bscscan.com/tx/0x56ce370324bff6cfd92b5ec531b726ed765d3e3d934024258f02b4b5fc8de303

### CODE REVIEW

**Comment by opera0001** [comment]
0x8568DF583fc4d996E94598ECc9b58B3B62c661a4--
1. No waiver of contractual ownership
2. There are settings that can control transactions
Please hurry to adjust

0x63CBDd44DE1Bc42D00B5dE776e2e2D678a44204F--
1. No waiver of contractual ownership
2. There are settings that can control transactions
3. Find a function that can find ownership
Please hurry to adjust

**Comment by opera0001** [comment]
I sent you the problems in contract review 7 hours ago. So far, I haven't seen any changes in token contract, so I need to close the order. After closing the order, you need to submit it again. Please know that the TPT donation fee has increased to 30000.

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
