### PR TITLE
add GROK-Cat logo and info

### PR DESCRIPTION
**Pull request by kulagrok**
https://bscscan.com/tx/0xa57816a28c1a6f0e053db5c1108686ad888af6db71a0f36e4d370aad3a2c575b

### CODE REVIEW

**Comment by opera0001** [comment]
The submitted logo does not have a pixel size of 256x256. Please make the necessary adjustments.

**Comment by kulagrok** [comment]
sorry，check

**Comment by opera0001** [comment]
The resolution of the logo is still wrong, please check again and modify it.

**Comment by kulacxdao** [comment]
logo

**Comment by kulacxdao** [comment]
now？

**Pull request merged**
