### PR TITLE
Add 98# logo and info

### PR DESCRIPTION
**Pull request by likeblacktea**
https://bscscan.com/tx/0xe99e067d91afe55c2498ad3740e33cc9a4415a41d7a382165cea4c7b107edd91

### CODE REVIEW

**Comment by opera0001** [comment]
image

There is a problem with the submitted data, please correct it.

**Comment by likeblacktea** [comment]
I only uploaded my files but I don't know why it has two pieces code.
How can I modify it?

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by opera0001** [comment]
Simply, you can delete the submitted data and submit a new one without changing the ranking of your submitted order.

**Comment by opera0001** [comment]
I suggest you resubmit it.

**Pull request closed without merging**
