### PR TITLE
Add SGB Token Info and Logo

### PR DESCRIPTION
**Pull request by m21917**
https://bscscan.com/tx/0x8b662141c1dac6d5fab55f9f048bf5d555aedb029fee8c9ec87ea9cc9a6ef13a
https://bscscan.com/tx/0x4cdc927a925df669cd9330d74dc24d2ad35d945c04c3320140dd9bff4450c486

Pleace Update our token info and logo, Thanks

### CODE REVIEW

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by opera0001** [comment]
1. Abnormal token transaction status
2. Token contract does not relinquish ownership
3. Blacklist function may exist
4. The logo uses the same logo as the subgame chain

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
