### PR TITLE
add EEQ logo and info

### PR DESCRIPTION
**Pull request by ZHANGMAZ1**
https://hecoinfo.com/tx/0x36f0b63f2f7f049cfa8d11d1fc8251287f2de44557bf327453be203a96f66a5b

### CODE REVIEW

**Comment by giki0318** [comment]
1. not opensource

**Comment by giki0318** [comment]
1. not open-source
2. too many dangerous methods

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
