### PR TITLE
Add NyQuil logo and info

### PR DESCRIPTION
**Pull request by helloshj**
捐赠3000TPT交易链接：https://bscscan.com/tx/0xa86b1c486dfe74a0471e1a27e579eef3eee322c5bd449a503634a1226b9f4454

### CODE REVIEW

**Comment by helloshj** [comment]
转0 BNB备注交易：https://bscscan.com/tx/0x5f192403443b364fb12fefd6944f4fd23732993c3a719b488ff2fb79b2c4976b

**Comment by nenrgy** [comment]
专业提交logo,代币，白皮书，诚住经营，值得信赖，价格全网最优！QQ:2099728898
Professional submit logo, scrip, white paper, honestly live operation, reliable, the optimal price cut! QQ: 2099728898

**Comment by sammvio** [comment]
Please re-submit your files to bsc folder

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
