### PR TITLE
Add dogeback logo and info

### PR DESCRIPTION
**Pull request by doge1988**
BSC-DOGEBACK-0x08C975868e547BFE5F76Db7d1e075680e9736034-https://bscscan.com/tx/0xfb7e38b0127b56eec7927dfa13549e4259310057d3a2ce1f3afbfc19d9c614ef

### CODE REVIEW

**Review by doge1988 — COMMENTED** [review]
Please check it. Thank you

**Comment by doge1988** [comment]
> BSC-DOGEBACK-0x08C975868e547BFE5F76Db7d1e075680e9736034- [https://bscscan.com/tx/0xfb7e38b0127b56eec7927dfa13549e42573449e425734c36034c36034](https://bscscan.com/tx/0xfb7e38b0127b56eec7927dfa13549e4257d14fc9e425713fc93fc9736034)

**Comment by zhujiayu03** [comment]
Please refer to the tutorial, and use the contract address in the checksum format.

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
