### PR TITLE
Add TPT logo to mvs

### PR DESCRIPTION
**Pull request by YyGg779**
30000 TPT Trade ID : 0x4feca28cb70c9990a75ff40242270bc5a09c565ba59ebd9b18a542606b3b6408 
0 BNB hash : https://bscscan.com/tx/0x68e22025c8834a77281f45117f33a4f17f02608807cee1944f739444e526ceee

### CODE REVIEW

**Comment by opera0001** [comment]
The token circulation status is abnormal, and the contract address has too many permissions.

**Comment by YyGg779** [comment]
The token condition is normal and tradable

**Comment by opera0001** [comment]
image
image

**Comment by YyGg779** [comment]
image
This is not a manual audit. The robot is wrong.This token works normally. see  this
https://poocoin.app/tokens/0x435802d8f34fd36a66e86423592ed2cc763c4c38

**Pull request merged**
