### PR TITLE
Add LIGHT(STAR Ecological coin) logo and info

### PR DESCRIPTION
**Pull request by STARGlobal**
https://bscscan.com/tx/0x97ea714f53771f20d9c3bbbeda4701767c5cb08acdb6db11c2a9311435855a00  
Certic has been audited https://www.certik.com/projects/starlight

### CODE REVIEW

**Comment by STARGlobal** [comment]
In response to the development of the market needs to retain the management authority

**Comment by opera0001** [comment]
#7306 order has used TPT hash value, please explain.

**Comment by STARGlobal** [comment]
image

**Comment by STARGlobal** [comment]
Please check the address for forwarding to TPT and the address for submission

**Comment by STARGlobal** [comment]
image

**Comment by opera0001** [comment]
请向0x7837AE9E4FD6E967F1B8C8824D6288ECE6e730F9转入0.000065个bnb公司验证。

**Comment by STARGlobal** [comment]
image

**Comment by STARGlobal** [comment]
BNB has transfered!

**Pull request merged**
