### PR TITLE
Add Meta Cloth logo and info

### PR DESCRIPTION
**Pull request by RichMooncn**
This is an organization that supplies meta-universe clothing. We hope to create a beautiful meta-universe, so that every meta-universe character can have a good-looking dress, or they can customize their own clothing.

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3579750034

**Comment by RichMooncn** [comment]
Change RichMoon Logo and info  ,to   Meta Cloth Logo and info

**Comment by RichMooncn** [comment]
0xfa41f4ea9b8ba9db0d48995a0b93605e60fea441e70185874813c065809701c0

**Comment by RichMooncn** [comment]
Change RichMoon Logo and info ,to Meta Cloth Logo and info

**Comment by RichMooncn** [comment]
Change RichMoon Logo and info ,to Meta Cloth Logo and info

**Review by RichMooncn — COMMENTED** [review]
ChangeTPT ,to Meta Cloth

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
