### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by HBOBwh23850**
https://bscscan.com/tx/0x7721472496d28e27353926d0b8ae7fd3d12de218441cb07149a39d43a7c6396b?utm_source=tokenpocket

### CODE REVIEW

**Comment by HBOBwh23850** [comment]
您好，项目目前再开发DAPP中，等DAPP开发好后会丢掉权限，麻烦给予通过，谢谢！

**Comment by opera0001** [comment]
Hidden owner permissions detected, please verify and explain their purpose, as it is a very, very, very dangerous configuration.

**Comment by HBOBwh23850** [comment]
您好！项目目前正常运行，项目目前有DAPP挖矿，权限还么有丢弃，等DAPP运行一段时间后，会丢掉权限，麻烦给与通过，谢谢！













At 2023-09-03 20:55:14, "opera0001" ***@***.***> wrote:

Hidden owner permissions detected, please verify and explain their purpose, as it is a very, very, very dangerous configuration.

**Comment by opera0001** [comment]
"Please provide a detailed explanation of the hidden owner portion within the token contract."

**Comment by HBOBwh23850** [comment]
您好！这个项目有DAPP质押挖矿，挖矿的是每天铸造产出代币，DAPP要掉用合约才可以铸造产出，麻烦给与通过谢谢，本月16日会丢掉合约权限，麻烦给与通过。
















At 2023-09-04 08:45:43, "opera0001" ***@***.***> wrote:

"Please provide a detailed explanation of the hidden owner portion within the token contract."

**Pull request merged**
