### PR TITLE
add 2Cc logo add info

### PR DESCRIPTION
**Pull request by zczx520**
{
 "name": "2Cc",
 "website": "无",
 "description": "2Cc是基于币安发行的代币，永不增发，未来价值巨大",
 "explorer": "https://bscscan.com/token/0x927aa9b7cefffbccaeedb48f687f57b1069e411e",
 "type": "HRC20",
 "symbol": "2Cc",
 "decimals": 18,
 "status": "active",
 "id": "0x927aa9b7cefffbccaeedb48f687f57b1069e411e"
}

### CODE REVIEW

**Comment by zczx520** [comment]
{
 "name": "2Cc",
 "website": "无",
 "description": "2Cc是基于币安发行的代币，永不增发，未来价值巨大",
 "explorer": "https://bscscan.com/token/0x927aa9b7cefffbccaeedb48f687f57b1069e411e",
 "type": "HRC20",
 "symbol": "2Cc",
 "decimals": 18,
 "status": "active",
 "id": "0x927aa9b7cefffbccaeedb48f687f57b1069e411e"
}

**Comment by zczx520** [comment]
{
 "name": "2Cc",
 "website": "无",
 "description": "2Cc是基于币安发行的代币，永不增发，未来价值巨大",
 "explorer": "https://bscscan.com/token/0x927aa9b7cefffbccaeedb48f687f57b1069e411e",
 "type": "HRC20",
 "symbol": "2Cc",
 "decimals": 18,
 "status": "active",
 "id": "0x927aa9b7cefffbccaeedb48f687f57b1069e411e"
} 
2Cc

**Comment by zczx520** [comment]
尊敬的工作人员你好，这是币安链上logo 麻烦看到处理下谢谢

**Comment by zhuroujuan** [comment]
未按照要求提交

**Comment by zhujiayu03** [comment]
请重新提交文件至相对应的heco文件夹

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Pull request closed without merging**
