### PR TITLE
Add HQ logo and info

### PR DESCRIPTION
**Pull request by wupengkk**

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Please re-submit your files attached TPT transfer link on [Commit changes].

**Comment by wupengkk** [comment]
Where is Commit changes? 提交更改在哪里？tpt传输连接在里面啊

**Comment by wupengkk** [comment]
我是按照教程提交的

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Pull request closed without merging**
