### PR TITLE
Add PETO logo and info

### PR DESCRIPTION
**Pull request by petogame**
PETO is a combination of gaming and cryptocurrency, a platform for all gaming lovers.
TPT
https://bscscan.com/tx/0x86ddc9f1ca9eda32d9c71d93b3c9a9c9430c07e939314a201b9c080db91a67a9
BSC
https://bscscan.com/tx/0xc366cb7a8549d1599edd817c56e83ba6ffcefc059b82c579b5a6f5b82430b7c3

### CODE REVIEW

**Comment by petogame** [comment]
The PETO project is a web3 based application platform using gamified finance and social finance.
Combine game content with sports and learning. With the help of game financialization, the project aims to promote users to live a healthier and more environmentally friendly lifestyle through the mutual growth of users and pets.
Token name: PETO;
Token symbol: PTC;
Total circulation: 3,000,000,000;
20% transaction fee:
1. Each transaction will trigger 10% burn;
2. The team will charge 10% of each transaction (8% is the team's income, and 2% is allocated to all currency holding addresses)

**Comment by opera0001** [comment]
The submitted tpt is not 256x256 pixels, please adjust it.

**Comment by petogame** [comment]
OK , re-uploaded

**Comment by petogame** [comment]
Hello, what else do I need to do?

**Pull request merged**
