### PR TITLE
0xc46a1316d6c49b6bd9cf78ac9afeb8135aa32d2e

### PR DESCRIPTION
**Pull request by Jonnyweiv**
https://bscscan.com/tx/0xb31459ecfee3a8e3fa4ffdf53d88c6d7709ac40bd3085e06d9074225e86e8b26
https://t.me/Spo_DAO

### CODE REVIEW

**Comment by opera0001** [comment]
image
The submitted file is not saved in the BSC directory, please adjust it again.

**Comment by Jonnyweiv** [comment]
0xc46a1316d6c49b6bd9cf78ac9afeb8135aa32d2e

**Comment by Jonnyweiv** [comment]
SPODAO is a real community currency, so that all participants will be treated fairly

}

**Comment by Jonnyweiv** [comment]
已经重新提交了

opera0001 ***@***.***> 于2022年8月2日周二 21:48写道：

**Comment by Jonnyweiv** [comment]
谢谢！

opera0001 ***@***.***> 于2022年8月6日周六 13:00写道：

**Pull request merged**
