### PR TITLE
Add Arche logo and info

### PR DESCRIPTION
**Pull request by qweras24**
https://bscscan.com/tx/0x8b7ffb13f79e9bfc0d1e4083c9ab5c3c50295bcf0866ee8490dc5f1374569157

### CODE REVIEW

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Comment by opera0001** [comment]
image
The main element of logo is too small, and the effect may not be very good after collection. Personal opinions are not used as a reference.

**Comment by qweras24** [comment]
@opera0001 The logo is designed and created by the designer. I hope the administrator can pass the certification

**Comment by qweras24** [comment]
> image The main element of logo is too small, and the effect may not be very good after collection. Personal opinions are not used as a reference.

The logo is designed and created by the designer. I hope the administrator can pass the certification

**Pull request merged**
