### PR TITLE
add ROTN logo and info

### PR DESCRIPTION
**Pull request by RotnCoin-Hub**
TPT: https://bscscan.com/tx/0x647567e723cf25a685201743d5b23dfc9aa5fe8ce2166b09943c864bf0d83bf5
BNB: https://bscscan.com/tx/0xeb5f31e36f8e51dbdb4fad7f2f0e35cad21f335efb147a419d64cb348b3208e8

### CODE REVIEW

**Comment by opera0001** [comment]
The function of adding token issuance is detected. Please explain.

**Comment by AitnCoin** [comment]
Mining requires issuance function

**Comment by RotnCoin-Hub** [comment]
Mining requires issuance function

**Comment by RotnCoin-Hub** [comment]
@opera0001 please check and let me know, if anything is missing

**Pull request merged**
