### PR TITLE
Add AK47 logo and info

### PR DESCRIPTION
**Pull request by MSNirvana**
https://bscscan.com/tx/0xe0d125dbf2fdb2eb48f71070520c028db52a9a8ef01b3779d27c549620466b1c

### CODE REVIEW

**Comment by MSNirvana** [comment]
Add AK47 logo and info

**Comment by opera0001** [comment]
1. There is no subsequent operation after the token is issued
2. No fund pool information
3. Submit url link cannot be opened
Please re submit for approval after adjustment.

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
