### PR TITLE
Create json.info

### PR DESCRIPTION
**Pull request by Le025**
{ 

"name": "Bitcoin META",

"website": "https://bitcoinmetachain.com/bitcoin-meta™",

"description": "Bitcoin META aims to become the 1st cryptocurrency within the metaverse.
An exchange on all available networks to facilitate transactions in the Blockchain.
A decimal point has been added to allow better configuration.
EARN UP TO 5% REWARD WALLET HOLDERS.
Ongoing adaptation for the metaverse world is needed to enable better conversion.
Bitcoin META will be the 1st Metaverse Token.",

"explorer": "https://bscscan.com/token/0x472ab0e69493d35b4c0965f01466b04d57d97252",

"type": "BEP20",

"symbol": "BTCM",

"decimals": 9,

"status": "active",

"id": "0x472ab0e69493d35b4c0965f01466b04d57d97252"

}

### CODE REVIEW

**Comment by Le025** [comment]
logo

**Comment by Le025** [comment]
Add Bitcoin META Token LOGO

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
