### PR TITLE
Add WUDI logo and info

### PR DESCRIPTION
**Pull request by imBTC**
Thanks

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Please re-submit your files attached TPT transfer link on [Commit changes].

**Review by imBTC — COMMENTED** [review]
1000 TPT https://bscscan.com/tx/0x17eba32ece77b76923dc5579774dc56a34526585874cf4ff784ed5319ded5321

**Comment by imBTC** [comment]
发自我的iPhone


------------------ Original ------------------
From: zhujiayu03 ***@***.***&gt;
Date: Wed,Jul 28,2021 11:32 AM
To: TP-Lab/tokens ***@***.***&gt;
Cc: imBTC ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [TP-Lab/tokens] Add WUDI logo and info (#1712)





 
Closed #1712.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by imBTC** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
^.^

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
