### PR TITLE
Add BVT logo and info

### PR DESCRIPTION
**Pull request by BovineVerseProject**
https://bscscan.com/tx/0xe53d2d0ff9d2740965b612aaead5a4e885f6fcf531d86bc89afda85b6792bc47
https://bscscan.com/tx/0x63f24a51b5de425adc6a8096d8b64a6759692efc1a772cdf7dc43883c4a6a179

### CODE REVIEW

**Comment by opera0001** [comment]
1、Please check the number of TPT donations
2, the submitted logo is not 256x256 pixels, please adjust
3、Detected that there may be a setting to suspend token trading, please explain what it does.

**Comment by BovineVerseProject** [comment]
1. Please check the transaction hash,0xe53d2d0ff9d2740965b612aaead5a4e885f6fcf531d86bc89afda85b6792bc47
b3211ef9947bcd646ba2a7e146d9600
2.
1bd5831a8c94812304aeba3aaa1aa26

3. Please note that our token contract has a function that restricts the interaction by smart contracts, only whitelisted smart contracts can use the token, this was designed to prevent against arbitrage bots. Ordinary personal addresses, hot and cold wallets are not affected.

**Comment by opera0001** [comment]
CN：https://tphelp.gitbook.io/cn/wallet-operation/submit-token
EN：https://help.tokenpocket.pro/en/developer/how-to-submit-a-token-logo#steps-of-adding-a-token-logo-info

Please check the tutorial here, and send me the link in your screenshot, please.

**Comment by BovineVerseProject** [comment]
1. click here, https://www.tokenpocket.pro/
image
2. Then click submit a token logo,https://help.tokenpocket.pro/developer-en/token/how-to-submit-a-token-logo
image

**Comment by opera0001** [comment]
I am very sorry, I think there is a problem with the update, now the tutorial links are based on the links in the help center of the official website: https://help.tokenpocket.pro/en/developer/how-to-submit-a-token-logo
image

This is also the link used in the https://github.com/TP-Lab/tokens link on github.
image


You can add the remaining number of tpt and resend the hash here, and we will do the logo inclusion today.

The token contract detects that you can suspend token transactions, please explain what it does.

**Comment by BovineVerseProject** [comment]
Hi, I have expained in the 1st comment please check above. 
(Please note that our token contract has a function that restricts the interaction by smart contracts, only whitelisted smart contracts can use the token, this was designed to prevent against arbitrage bots. Ordinary personal addresses, hot and cold wallets are not affected.)

Trasaction hash:0xd58c3501301348c54717fa4780939a8a4e7e9cfc28ff26a2ba829595600ab967

**Pull request merged**
