### PR TITLE
upload  info

### PR DESCRIPTION
**Pull request by hypenname**

### CODE REVIEW

**Comment by hypenname** [comment]
Last time the contract was closed without open source, now the contract is open source.

Contracts have some risk, which is 100% slippage in buying and selling, removing restrictions before launching, and discarding permissions afterwards

**Comment by hypenname** [comment]
付款链接 https://bscscan.com/tx/0x710c7586ea0f7435934ea04ea69e4cbbe8378f9135f46e0134dc72aa4fd44fc3

**Comment by opera0001** [comment]
Detected hidden owner permissions, please check.

**Comment by hypenname** [comment]
Now that transactions are open, there are no security issues, and the proxy contract will also discard permissions

**Comment by opera0001** [comment]
The hidden owenr Settings are not affected by control discarding, which is unfortunately quite risky.

**Comment by hypenname** [comment]
The proxy contract is used to set sliding points and whitelist addresses, without any other security risks

**Pull request closed without merging**
