### PR TITLE
Add ACat logo and info

### PR DESCRIPTION
**Pull request by ACatCommunity**
https://bscscan.com/tx/0x589fd4881e40a23b4f4fa4a255c3896b46c30306eb9a80b0675d7e831dbc62d2

### CODE REVIEW

**Comment by opera0001** [comment]
1. Tokens haven't started trading yet
2. There are many token settings
3. It is recommended to discard control after starting the transaction

**Comment by ACatCommunity** [comment]
Yes. after the transaction begins,our ownership will be abandoned.This is
to prevent mistakes!Thank you

opera0001 ***@***.***> 于2022年3月13日周日 22:40写道：

**Comment by opera0001** [comment]
For the sake of safety, the audit may be conducted after the token contract control is discarded. Please wait patiently or resubmit at that time.

**Comment by ACatCommunity** [comment]
How long will it take ?Just TP logo.


opera0001 ***@***.***> 于2022年3月14日周一 20:32写道：

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request merged**
