### PR TITLE
Add BGK logo and info

### PR DESCRIPTION
**Pull request by BurgerKing8**
https://bscscan.com/tx/0x55b46ed27fbae312ac7a38b6b956279cde9d446a880578021707c929961164c1

### CODE REVIEW

**Comment by BurgerKing8** [comment]
The administrator reserves the parameters to be adjusted according to the market and will discard them after they become stable

**Comment by opera0001** [comment]
Token circulation status is abnormal.

**Comment by BurgerKing8** [comment]
It's not online yet. Is it related to buying and selling?

**Comment by BurgerKing8** [comment]
It's online ,please review!

**Comment by opera0001** [comment]
Done

**Pull request merged**
