### PR TITLE
Add Laeeb logo and info

### PR DESCRIPTION
**Pull request by sfxgdrc**
TPT: https://bscscan.com/tx/0xf7e339a91028f379c9f39dfa9cf5e4138f85eac257f6d9012e647aca5a2270d5 验证：https://bscscan.com/tx/0x307aec2e9e3fded8e4a8c7e445fed1cc18788c17f503aa3bdca0c7807b23df25

### CODE REVIEW

**Comment by opera0001** [comment]
1. If you detect that the transaction rate can be modified, please explain what it does.
2、The logo content is similar to the logo content already included now, please make adjustments.

**Comment by sfxgdrc** [comment]
1，代币所有权已经放弃，因此税率已经不能更改
2，现在已经收录的代币与我这个是同一个项目，是映射重开的，如果不能同时收录，可以下掉原来的那个头像，只加这一个

官推可以证明，这是同一个项目
同时ave上面也可以查到，两个项目所有资料都是一致的。
推特:https://twitter.com/LaEeb_Dao



| |
qiufangguoa
|
|
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 09/28/2022 19:50 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [TP-Lab/tokens] Add Laeeb logo and info (PR #8313) |

If you detect that the transaction rate can be modified, please explain what it does.
2、The logo content is similar to the logo content already included now, please make adjustments.

**Comment by opera0001** [comment]
What is the contract address of the other token, please?

**Comment by sfxgdrc** [comment]
> What is the contract address of the other token, please?

0xa2b8a15a07385ea933088c6bcbb38b84c1051a58

**Pull request merged**
