### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by gggggyysss**
https://bscscan.com/tx/0xc8429cddaac9d866c17b6c7d73b29bb99eb1d7270c1dde77d09a9fa48c0a117e

### CODE REVIEW

**Comment by opera0001** [comment]
Token issuance increase setting has been detected.

It has been detected that token trading can be paused. Please explain the reason for doing so.

The transaction fee rate for detecting tokens can be modified. Please explain the reason for doing so.

If the submitted logo is not 256x256 pixels, please modify it.

The administrative permissions have not been revoked, so the above issues are relatively complex.

**Comment by gggggyysss** [comment]
The reason why transactions can be suspended and exchange rates were set as before is because they were set like this. Please rest assured that we will not make any changes or suspensions to these. The logo has been changed. How can I resubmit it

发自我的iPhone


------------------ Original ------------------
From: opera0001 ***@***.***&gt;
Date: Tue,May 9,2023 7:11 PM
To: TP-Lab/tokens ***@***.***&gt;
Cc: gggggyysss ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [TP-Lab/tokens] Add files via upload (PR #9342)





 
Token issuance increase setting has been detected.
 
It has been detected that token trading can be paused. Please explain the reason for doing so.
 
The transaction fee rate for detecting tokens can be modified. Please explain the reason for doing so.
 
If the submitted logo is not 256x256 pixels, please modify it.
 
The administrative permissions have not been revoked, so the above issues are relatively complex.

**Comment by gggggyysss** [comment]
> 检测到令牌颁发增加设置。
> 
> 已经检测到代币交易可以暂停。请解释这样做的原因。
> 
> 可以修改检测代币的交易费率。请解释这样做的原因。
> 
> 如果提交的徽标不是 256x256 像素，请对其进行修改。
> 
> 管理权限尚未撤销，因此上述问题相对复杂。

已经重新提交 您看看

**Comment by opera0001** [comment]
After resubmission, the format and logo are fine. The only issue is that there is a setting in the token contract for increasing token issuance. I need to know its purpose.

**Comment by gggggyysss** [comment]
The logo has been successful. Thank you. May I ask why it was not recorded on the official website

发自我的iPhone


------------------ Original ------------------
From: opera0001 ***@***.***&gt;
Date: Thu,May 11,2023 1:53 PM
To: TP-Lab/tokens ***@***.***&gt;
Cc: gggggyysss ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [TP-Lab/tokens] Add files via upload (PR #9342)





 
After resubmission, the format and logo are fine. The only issue is that there is a setting in the token contract for increasing token issuance. I need to know its purpose.

**Pull request merged**
