### PR TITLE
Add FREE TOKEN logo and info

### PR DESCRIPTION
**Pull request by moonlight155**
https://bscscan.com/tx/0xa6101925e5ebf0ab3ced93d8a6f3edb3fa2ffe518e12e7ee1a7fd9936811ff72

### CODE REVIEW

**Comment by opera0001** [comment]
image

The path for submitting data is incorrect. Please store it according to the specifications in the tutorial.

The fee for detecting fraudulent coin transactions can be modified. What is the purpose of this?

**Comment by moonlight155** [comment]
> image
> 
> The path for submitting data is incorrect. Please store it according to the specifications in the tutorial.
> 
> The fee for detecting fraudulent coin transactions can be modified. What is the purpose of this?

I would ask technically specific reasons. Is this the reason why we don't have an avatar on the official website? or is there another reason

**Comment by moonlight155** [comment]
Current transaction fees, dividends for community contributions. At the same time, the transaction rate of FREE is set at the upper limit of 10% selling and 4% buying.

**Comment by moonlight155** [comment]
When the community development enters a virtuous circle, the cost will be reduced. Please rest assured that we cherish our users very much, and this result is decided by the community Dao organization.

**Pull request merged**
