### PR TITLE
Add ZEED logo and info

### PR DESCRIPTION
**Pull request by GiraffeZJ**
https://bscscan.com/tx/0x7840ba73e1ff728a05a93fbe25a5e9fc1831da5574e7c5580fc40d741c16f68b

### CODE REVIEW

**Comment by opera0001** [comment]
Token contract is not open source, so the security cannot be checked. Please adjust it.

**Comment by TokenPocket-JAN** [comment]
Speed ​​up the trial. Please reply to the email if you need.
QQ112831047

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request merged**
