### PR TITLE
add BT2 logo

### PR DESCRIPTION
**Pull request by zplanbt2**
https://bscscan.com/tx/0xc41df55a8ef451f8ab1af7e44a9d5b49df26bdfb7fac14925a0b31c97a8ed1af
https://bscscan.com/tx/0xfbe4a52b88bf3318bc5ca786beb98392ed46995516cd6aa2e6d32a82f636581d

1.The development is an agency contract, but the authority has been given up and cannot upgrade
2.Size has been modified

### CODE REVIEW

**Comment by opera0001** [comment]
The proxy contract carries significant risks. Please provide the results of the code security audit.

**Comment by zplanbt2** [comment]
Which audit institutions do you support?

**Comment by opera0001** [comment]
> Which audit institutions do you support?

Any code security audit results provided by a reputable security company will be acceptable.

**Comment by zplanbt2** [comment]
image
ave has audited

**Pull request merged**
