### PR TITLE
Add CGC logo and info 

### PR DESCRIPTION
**Pull request by netlocks**
tpt:https://bscscan.com/tx/0x63a7524a275c22c53aa7bc4c5e8e9cec6cdce2f0c93251fa0f44b66846a3f36a

bnb:https://bscscan.com/tx/0xbc4d16e110f9b0d4e204aa48798e89f53275fa7a9bb1f33d2be3012ee5def05a

#6127  no exception

### CODE REVIEW

**Comment by netlocks** [comment]
Hello, it has been open for a long time, and I have no authority. Now there is no problem in buying and selling.

**Comment by netlocks** [comment]
The pool is also locked

**Comment by netlocks** [comment]
Now that many people are trading, how can they sell 100%?

**Comment by opera0001** [comment]
In the first audit, it was found that the purchase and sale of the token require a rate of% 100. Currently, it has been adjusted normally, but there are still risks. It may be safer if the administrator's permission can be discarded.

**Comment by netlocks** [comment]
你好，该合约没有任何权限，也没有任何方法可以执行

**Comment by netlocks** [comment]
Hello, this contract does not have any permissions nor any method to execute

**Comment by netlocks** [comment]
And there is no owner function

**Comment by opera0001** [comment]
It's normal now, so please wait patiently for the review. It may take tomorrow or later to pass.

**Comment by netlocks** [comment]
OK, thanks

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request merged**
