### PR TITLE
PINE

### PR DESCRIPTION
**Pull request by pineprotocol**
tpt:  https://bscscan.com/tx/0x2996adc176beaf96fb578d6f9567b537e24a6183f69ebea96f3b92318e6fca04
bnb:  https://bscscan.com/tx/0x05c022898463898fb9f43e38df9e5abc026ede685051af07a96ef1bac6224dfd

### CODE REVIEW

**Comment by opera0001** [comment]
A setting to increase the issue of tokens is detected, please explain what it does.

**Comment by pineprotocol** [comment]
The title has been relinquished by us

**Comment by pineprotocol** [comment]
The owner permission has been waived

opera0001 ***@***.***> 于 2022年9月20日周二 00:32写道：

**Comment by pineprotocol** [comment]
The owner permission has been waived

protocol Pine ***@***.***> 于 2022年9月20日周二 13:41写道：

**Comment by pineprotocol** [comment]
How soon can it be merged?

**Comment by pineprotocol** [comment]
？？？？？

**Pull request merged**
