### PR TITLE
Add BHC logo and info

### PR DESCRIPTION
**Pull request by propier**
https://www.bscscan.com/tx/0x101852e79bb28dea0135481f910df66c9a2db654484962a2977ee88c8e3cf53f

### CODE REVIEW

**Comment by 15875804435** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by opera0001** [comment]
The token contract source code is not public, so the security cannot be checked.

**Comment by propier** [comment]
> The token contract source code is not public, so the security cannot be checked.

The token contract source code is public now

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request merged**
