### PR TITLE
add TiMi info and logo 

### PR DESCRIPTION
**Pull request by KKKK1898**
https://bscscan.com/tx/0x72b18532699a8057589e26b334ea7d1a4829caab865bd111556279df209fb2dd?utm_source=tokenpocket

Thank you so much!

### CODE REVIEW

**Comment by opera0001** [comment]
We will not list tokens with domain names as their names (e.g., TiMi.C0M). Such tokens are highly misleading and prone to risk issues. The TPT donation hash value you submitted can be used in future GitHub submissions.

**Comment by KKKK1898** [comment]
hi ， My token has been replaced with a new contract and it does not come with COM. Please check the last and latest ones, thanks

**Comment by KKKK1898** [comment]
add TiMi info and logo     , is  TiMi ， NO TiMi.C0M

**Review by KKKK1898 — COMMENTED** [review]
这是最新的， 感谢！

**Review by KKKK1898 — COMMENTED** [review]
This is the latest and correct. grateful!
Snipaste_2024-04-06_12-40-27

**Pull request closed without merging**
