### PR TITLE
add mbank info and logo

### PR DESCRIPTION
**Pull request by ade23asd**
https://bscscan.com/tx/0x58be63f07909453e813433665d624a5126d799febc0804d57251879c4af322b9 https://bscscan.com/tx/0x2dc038b22cdd3f6e57217c651b02dc0e3b44337baad618ffb7ec92069484f2ae

### CODE REVIEW

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Comment by ade23asd** [comment]
This token has some issues; Can we change the token

**Comment by opera0001** [comment]
> This token has some issues; Can we change the token

Yes, you can send me the new contract address.

**Comment by opera0001** [comment]
> Okay, the new contract is currently being tested. Once it goes live, can we send it directly to the message

The adjustments have been made. You can contact me through issues for any further inquiries.

https://github.com/TP-Lab/tokens/issues

**Comment by ade23asd** [comment]
The new contract has already come out. How do I submit it? I tried to resubmit it, but it seems that I can't submit it. The contract's information and logo have changed compared to before

**Comment by ade23asd** [comment]
Contract address:：0xD5337315fA408afEEA9c660c33c8090Fc4c98f09
logo upload
logo
I'm not sure if you can receive the logo

**Pull request closed without merging**
