### PR TITLE
info logo

### PR DESCRIPTION
**Pull request by sjzhhm1**
info logo

### CODE REVIEW

**Comment by sjzhhm1** [comment]
什么时候审核

**Comment by sjzhhm1** [comment]
BSC-BisonSwap-0xbfF9e1a527467E1bDBd8b2aFC026b5694fE5464C-https://bscscan.com/tx/0x81391bd8336a492ab349f2588b47016fcf37cf772bbf93c3e12d3b0cc9c3c735
BSC-Lucky Rabbit-0x802DaC42657B889E683de3Be7e35dFdd23d42D0C-https://bscscan.com/tx/0x70c9c8694282d4deac365c81542c5e0c642919198cfa6617d034b48d11438d3c
Bsc-SafeMiniBabyDoge Coin-0x362920c7ad830145a4baDAe6A476ac1F5Ebe4021-https://bscscan.com/tx/0xcd9ac1c5620f02d16ca7155493f3035691fa8db42accb46191b6758a8bda1aee
BSC-Lucky Rabbit-0x185f96A46d80d77b757E52BA8cA69919672ABCC8-https://bscscan.com/tx/0x3a5bb161b85f27ab37db49d2c4a1b7dc4b0aba1a49c7c18b7978776393eceb4e

**Comment by zhujiayu03** [comment]
1、请重新检查 BISS 网站；2、勿提交重复的logo

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
