### PR TITLE
Add MJN logo and info

### PR DESCRIPTION
**Pull request by mjnetwork**
BSC-MJN－0x6A144274D3F7a2277f38b2d76e3fb8377799737d-https://bscscan.com/tx/0x3f82df2998951284695104e481e0a4005b910a3b8a29e91ee499f9c548ee177b

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by mjnetwork** [comment]
您好！非常感谢！我们已经收到你的邮件，请关注威宁论坛www.wn5.cc。..........................................................................
..........................................................................

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by mjnetwork** [comment]
您好！非常感谢！我们已经收到你的邮件，请关注威宁论坛www.wn5.cc。..........................................................................
..........................................................................

**Pull request closed without merging**
