### PR TITLE
Add LY logo and info

### PR DESCRIPTION
**Pull request by htwang1134**
50000TPT转账地址链接：https://bscscan.com/tx/0x4d7df6d8d115894912b9736022bd383945675470babe9aac296e96240e4cb6aa 步骤5验证哈希链接：https://bscscan.com/tx/0xc9cf3ed99cb56974d26b1db00cc080716735b6be2edfc65aea0ded3cc91dcf71

### CODE REVIEW

**Comment by htwang1134** [comment]
第一次提交图片尺寸有问题，第二次修改了图标

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Comment by htwang1134** [comment]
非常抱歉给您带来的不便，请帮忙处理一下，非常感谢！

**Comment by htwang1134** [comment]
错误的合约地址：0xc24C0154fee4408451B671317e0598dd8C2997cB
正确的合约地址：0x5D3BDC8AC59318EAc858d5588F164E19E0764268
麻烦管理给修正一下，非常感谢！

**Pull request merged**
