### PR TITLE
Add logo and info

### PR DESCRIPTION
**Pull request by gcuptoken**
https://bscscan.com/tx/0x0769e987756e5604e699535c09f08d2e2f55c69f233027416fd7ccb82128f49a

### CODE REVIEW

**Comment by opera0001** [comment]
1. There is no official contact information on the official website
2. There is no exchange on the official website
3. Please explain that the ownership of the contract has not been abandoned
Please re submit the logo after adjustment or optimization. Thank you for your support for tokenpocket.

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
