### PR TITLE
Add RLT info and logo

### PR DESCRIPTION
**Pull request by greenyrichard476**
https://bscscan.com/tx/0xa39f7e7ef942569348e37483882b92ce665e618f9982b54439c28b1a0f4f271b

### CODE REVIEW

**Comment by opera0001** [comment]
1. The token contract is not open source
2. No fund flow pool was found

Please adjust

**Comment by opera0001** [comment]
1. The token contract is not open source
2. No fund flow pool was found

Please adjust

**Comment by ganggang0369** [comment]
we have add the flow 0x3948a1a2ff39069c34609c093f83994421e1d776
and the contract is open source

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request merged**
