### PR TITLE
Add SH logo and info

### PR DESCRIPTION
**Pull request by SHswapadmin**
https://bscscan.com/tx/0xe43d56ed015f9ee782ac5d07e0f2a6e9febb0d876fc944b0a83a7b25b327dee3

### CODE REVIEW

**Comment by opera0001** [comment]
The submitted logo is not 256x256 pixels. Please readjust and replace it.

**Review by SHswapadmin — COMMENTED** [review]
logo

**Comment by SHswapadmin** [comment]
Thanks for Opera0001's suggestion, I have adjusted the new LOGO and sent it here

**Comment by SHswapadmin** [comment]
Since I don't have permission to delete the LOGO picture, I don't know whether I should try to send pull requests again

**Comment by opera0001** [comment]
Please wait patiently, and we will review it for you later.

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request merged**
