### PR TITLE
add STAR logo and info

### PR DESCRIPTION
**Pull request by Farswap2021**
https://bscscan.com/tx/0x8a806574b33c7c3f65244ae98422617d924366dad379ed611b133206b71887f9
https://bscscan.com/tx/0x6ac28a7ac4df60edd461c93ddec5dd77cd781f3531ea8a19a851e921ed192830

### CODE REVIEW

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by opera0001** [comment]
1. Abnormal token transaction status
2. The contract does not give up ownership
Please re submit the logo after adjustment. Thank you for your support for tokenpocket.

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
