### PR TITLE
Add BOT logo and info

### PR DESCRIPTION
**Pull request by cswwell**
TPT:https://bscscan.com/tx/0x0acec9a589cff85f8258894383bec9fcf7f89ba02b0bc8d57fce3dc8e99c2ec8 BNB:https://bscscan.com/tx/0x4d9ea44a9fba4d9b9ab489148d37cd93674af4fd4eda7e684df8da2ab005d95d

### CODE REVIEW

**Comment by opera0001** [comment]
1、Detecting that tokens can increase issuance,
2、Token transaction rates detected can be modified

Please explain their role.

**Comment by cswwell** [comment]
Hello, the contract permission has been lost, and the slippage should not be changed.

**Comment by opera0001** [comment]
No discard of title was detected.

**Comment by opera0001** [comment]
I did not see your reply after 2 days, so the order needs to be closed. You can contact me through issues.

https://github.com/TP-Lab/tokens/issues

**Pull request closed without merging**
