### PR TITLE
Add GEM logo and info

### PR DESCRIPTION
**Pull request by Duxxjjd**
Transaction ID link:https://bscscan.com/tx/0xdbd3378694dde47d6d881dfee65ddb2c0a03d08b5caa4f93ac4c900e4a4f4402
Verify the address link:https://bscscan.com/tx/0x5c9e2994038d4ed9df427083f41fd3aa044a2027b91f2e67bc1724e830b28655

### CODE REVIEW

**Comment by jjjgjk** [comment]
1212在吗

**Comment by jjjgjk** [comment]
1212在吗

**Comment by jjjgjk** [comment]
1212在吗

**Comment by jjjgjk** [comment]
你好

**Comment by tplogotijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request merged**
