### PR TITLE
Add Thoreum logo adn info

### PR DESCRIPTION
**Pull request by YesmbNot**
https://bscscan.com/tx/0x49f1e0a53e92103013783da7a7886b46f098569d9ba7139cd18fd0a30afd21be - This is 1000 tpt
https://bscscan.com/tx/0xcd39d1e18d7172e90bf784647ff33af8928b8801977096f285f25a837f225073 - This is the comment submitted

What is Thoreum?
Thoreum is TRUE hyper deflationary token, the best coin for HODLING. Built to be Safemoon 2.0, Thoreum has many innovative features that help users earn & win bigger.

Our site : https://thoreum.finance/
Docs: https://docs.thoreum.finance/
CERTIK audit : https://www.certik.org/projects/thoreumfinance
Telegram : https://t.me/Thoreum 
Twitter : https://twitter.com/ThoreumFinance

### CODE REVIEW

**Comment by zhujiayu03** [comment]
logo infringement, please resend your image

**Comment by YesmbNot** [comment]
> logo infringement, please resend your image

logo

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
