### PR TITLE
Add NLT logo and info

### PR DESCRIPTION
**Pull request by nltlogo**
TPT: https://bscscan.com/tx/0xba0be32311fac6fbe2ab40bc20f7ee36380639ebeb7a3e9d3ef2038374a56238
BNB: https://bscscan.com/tx/0xcb0a5acd793243a2cd054525e827bda791d8ca78ba5439301b4849c3e5175441

### CODE REVIEW

**Comment by opera0001** [comment]
1、It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.
2、The submitted logo is not 256x256 pixels, please adjust it.

**Comment by nltlogo** [comment]
logo

**Comment by nltlogo** [comment]
This is new Logo, The contract has been opened, Please confirm

**Comment by opera0001** [comment]
Hidden owner
The token has a hidden owner address.For contract with a hidden owner, developer can still manipulate the contract even if the ownership has been abandoned.

**Comment by opera0001** [comment]
I still haven't seen your reply after 2 days, so the order needs to be closed, you can contact me in issues.

https://github.com/TP-Lab/tokens/issues

**Pull request closed without merging**
