### PR TITLE
Add UFS logo and info

### PR DESCRIPTION
**Pull request by Unifies-coin**
https://bscscan.com/tx/0xe85bb2af4d0cd210402cdcf97b9268affa1fa99c9f363793c124b0ebc11d0ac8

### CODE REVIEW

**Comment by opera0001** [comment]
1. There may be additional issuance function
2. Low liquidity pool

**Comment by Unifies-coin** [comment]
Contract permissions have been abandoned, can it be merged?

**Comment by Unifies-coin** [comment]
https://bscscan.com/address/0x99988bC9D822e43d728770fb97E6141859f1a848#readContract

Permissions have entered a black hole

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
