### PR TITLE
Add PWC logo and info

### PR DESCRIPTION
**Pull request by ywl11010**
Perfect World Coin
Perfect World integrates GameFi, NFT, and pledge to achieve decentralization, no marketing, all for community autonomy, and return the market to the participants! PWC is the governance token of Perfect World.

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3579750034

**Comment by sammvio** [comment]
Please re-submit your files to bsc folder

**Comment by ywl11010** [comment]
Dear administrator, hello! What is the reason, audit did not pass?


---Original---
From: ***@***.***&gt;
Date: Wed, Jan 5, 2022 09:57 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] Add PWC logo and info (PR #4647)




 
Please re-submit your files to bsc folder
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
