### PR TITLE
Add 520 logo and info

### PR DESCRIPTION
**Pull request by T520Love**
https://bscscan.com/tx/0xb17d4ef4740143c391fe9d4230bb9b5818e4a6f5d606936f9b68e133dee18944

Administrators are retained for the development of the market

### CODE REVIEW

**Comment by opera0001** [comment]
You can set the tokens transaction to be suspended. Please explain what it does.

**Comment by T520Love** [comment]
> You can set the tokens transaction to be suspended. Please explain what it does.
Administrators can only add addresses that are free of fees and have no permission to suspend transactions

**Comment by T520Love** [comment]
here is no such action in the source code

**Comment by T520Love** [comment]
The administrator will discard these two days, mainly for the previous batch of whitelisted users

**Comment by T520Love** [comment]
> You can set the tokens transaction to be suspended. Please explain what it does.

The administrator permision has discarded

**Comment by T520Love** [comment]
> You can set the tokens transaction to be suspended. Please explain what it does.
The administrator permission has been discarded, previously for whitelist

**Comment by T520Love** [comment]
The administrator permission has been discarded

**Pull request merged**
