### PR TITLE
Add info and Logo

### PR DESCRIPTION
**Pull request by TokenLogos**
https://bscscan.com/tx/0xccb7b64d2bda5f7c772789d1a059d99f5e16dac40647795dcbcf3932c31e4321

### CODE REVIEW

**Comment by opera0001** [comment]
Transaction risk of agency contract detected

**Comment by TokenLogos** [comment]
The logo cannot be uploaded for  agency contract?

**Comment by TokenLogos** [comment]
> Transaction risk of agency contract detected

The logo cannot be uploaded for  agency contract?

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
