### PR TITLE
add CXB logo and info

### PR DESCRIPTION
**Pull request by CXBgod**
https://bscscan.com/tx/0xdb520273c6670b7e0c321ef9c01474b6c338abc2ad5ccb6c9e89b9dc148bc5f8  

Dear administrator, please review and approve as soon as possible, thank you

### CODE REVIEW

**Comment by CXBgod** [comment]
Hello Administrator, this is the link to remark information on BNB after submitting TPT
0x01e926d7945c5dd0250aae251f3e1093c6000a884924100f186bd1a30bc8f10b

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:2980874528

**Comment by sammvio** [comment]
Please refer to the tutorial, and re-submit your files in the correct format.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
