### PR TITLE
Add AresDoge logo and info

### PR DESCRIPTION
**Pull request by taomuli**
https://hecoinfo.com/tx/0xc653df646bbe5d3abdbebe7ef806129c1fd7ceac262ba5c48c2c42abe397c6df

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Please refer to the tutorial, and re-submit your files in the correct format.

**Comment by taomuli** [comment]
> 
> 
> 请参阅本教程，并重新提交的文件以正确的格式。

Which tutorial to refer to? There is no error

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
