### PR TITLE
Add MNTC logo and info

### PR DESCRIPTION
**Pull request by minaticoin**
Sample

### CODE REVIEW

**Comment by minaticoin** [comment]
Hey

**Comment by minaticoin** [comment]
Check and Confirm Please

Coin Market Cap :- https://coinmarketcap.com/currencies/minati-coin/

Website :- https://minati.io/

Bscscan :- https://bscscan.com/token/0xe4e11e02AA14c7f24DB749421986EAEc1369e8C9

**Comment by minaticoin** [comment]
Please Reply

**Comment by opera0001** [comment]
1、Please provide the TPT donation hash value link.
2、A mechanism has been detected for increasing token issuance.

**Comment by minaticoin** [comment]
TPT Hash :- https://bscscan.com/tx/0xa1a4f71c2b370762a560874c061958dde74a9280c7dd2caa43bb14685015da89

**Comment by minaticoin** [comment]
BNB BSC Hash :- https://bscscan.com/tx/0xb09c737ba78bab163ce01ea450f18309148044c44683c65ae149dd530aa1ca5d

**Comment by minaticoin** [comment]
Please Confirm and  Update logo and info

We have limited supply 12,500,000 MNTC

**Pull request merged**
