### PR TITLE
Add CTN logo and info

### PR DESCRIPTION
**Pull request by zhengjf124**
HECO-TPT-0x23a1ac95448dd08ebdec3acd70c7ae1106bf1de18ded66d5dbe07b8ccb3ff71c-https://hecoinfo.com/tx/

### CODE REVIEW

**Comment by zhengjf124** [comment]
Add CTN logo and info

**Comment by tiaojiaotubiaobaoguo** [comment]
24小时提交logo包过，加QQ：2980874528

**Comment by sammvio** [comment]
Tron token logo upload is not allowed for now

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
