### PR TITLE
Add FRAME logo and info

### PR DESCRIPTION
**Pull request by yutianmr**
https://bscscan.com/tx/0x6aa8d54b8c5a305282a50b8656e1b6d1f4c00275564551045d3acdc37074bad4

### CODE REVIEW

**Comment by tiaojiaotubiaobaoguo** [comment]
代提交logo，24小时内包过，加QQ：2980874528

**Comment by sammvio** [comment]
The contract didn’t verify and publish. (No open-source)

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
