### PR TITLE
ADD SMS logo and info 

### PR DESCRIPTION
**Pull request by lisijiang1999**
ADD SMS logo and info

### CODE REVIEW

**Comment by jjjgjk** [comment]
121212

**Comment by jjjgjk** [comment]
121212

**Comment by jjjgjk** [comment]
121212

**Comment by lisijiang1999** [comment]
https://bscscan.com/tx/0x787c1ec32e4483e162951613ee9fb45b008dbdebe50aeeaad2722e4cf41e8786

**Comment by opera0001** [comment]
For pre-sale items, there may be risks. It is recommended to re apply for token logo inclusion after token trading starts.

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by lisijiang1999** [comment]
Tokens have started trading。

**Pull request closed without merging**
