### PR TITLE
Add HT Club logo and info

### PR DESCRIPTION
**Pull request by GMV210**
转3000TPT记录
https://bscscan.com/tx/0x067502ca6a0a6a4f1e32c04ce637d3f017090998ea31132437b366b21bc057f4
TOKEN信息：HECO - HT Club - 0xb666CCF557d2a61adDB07D3b9df1607Ca9418b8f

### CODE REVIEW

**Comment by tiaojiaotubiaobaoguo** [comment]
代提交logo，24小时内包过，加QQ：2980874528

**Comment by sammvio** [comment]
Please submit the checksum address that includes uppercase and lowercase characters.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
