### PR TITLE
Add Lightcap logo and info

### PR DESCRIPTION
**Pull request by qq404544957**
30000TPT：
https://bscscan.com/tx/0xe9f72bbf2ee9d5329dfae49e4358f42ea6e067d38175d01c473adec9df0b1608
TxHash：
https://bscscan.com/tx/0xbe3338905bcb9cb7dd9259600c8bf73ae1242984419e88bd8451b4adb6694be3

### CODE REVIEW

**Comment by opera0001** [comment]
Is 0x34e7b8f2d42c7d39a54437a30795030d0b9e5485 submitted in GitHub? What is the order number?

**Comment by qq404544957** [comment]
> 
yes，0x34e7b8f2d42c7d39a54437a30795030d0b9e5485,explorer,#6318

**Comment by qq404544957** [comment]
Is there anything wrong with that?  The two orders have nothing to do with each other

**Comment by opera0001** [comment]
0x34e7b8f2d42c7d39a54437a30795030d0b9e5485 should be processed. Please wait patiently for the token logo review.

**Comment by qq404544957** [comment]
> 0x34e7b8f2d42c7d39a54437a30795030d0b9e5485 应该被处理。请耐心等待token logo审核。

Why cancel the logo of 0x34e7b8f2d42c7d39a54437a30795030d0b9e5485? I have made two donations and should keep the logo of both projects at the same time

**Comment by opera0001** [comment]
image
Isn't the red part to delete the logo? If not, why add it?

**Comment by qq404544957** [comment]
Sorry, it's my mistake. I've changed my request

**Comment by opera0001** [comment]
Please fully describe your current needs.

**Comment by qq404544957** [comment]
I only need to add Lightcap logo and info. Please do not delete the logo of "explorer"

**Comment by opera0001** [comment]
I see. Just a moment, please.

**Comment by opera0001** [comment]
done

**Pull request merged**
