### PR TITLE
Add ChatGPT Logo

### PR DESCRIPTION
**Pull request by ChatGPT0x293a**
https://bscscan.com/tx/0x8fe7457d9d79215025de6aaef9941d1935fc579dede573be743c033a23a746e1

### CODE REVIEW

**Comment by opera0001** [comment]
image
What is the relationship between this submission history account and you?

**Comment by ChatGPT0x293a** [comment]
This is also my account. When RPO submitted the logo last time, it said it was an agency contract. It failed, and then it was not transferred. This time ChatGPT is not an agency contract!

**Comment by ChatGPT0x293a** [comment]
> 图像 这个投稿历史账号和你是什么关系？

This is also my account. When RPO submitted the logo last time, it said it was an agency contract. It failed, and then it was not transferred. This time ChatGPT is not an agency contract!

**Comment by opera0001** [comment]
Please use the address 0xbe96a9ad3036cac904aaa9a1017e5b3c52ce4442 to transfer 0.000011bnb to 0x7837ae9e4fd6e967f1b8c8824d6288ece6e730f9 for verification and send me the hash value after the transfer, thanks.

**Comment by opera0001** [comment]
After submitting, you can let me know through issues.

https://github.com/TP-Lab/tokens/issues

**Pull request closed without merging**
