### PR TITLE
Add JETCoin logo and info

### PR DESCRIPTION
**Pull request by halloffameworld**
https://bscscan.com/tx/0xbbb9c0fce201b2e8262e8e1c271714a85a668e686a31c149621a0158ee22af9b
https://bscscan.com/tx/0xcbe7408cb94a8382de45e39c0b2a4146ab0fb39abac0d833ed91d72637d796b1

### CODE REVIEW

**Comment by opera0001** [comment]
The TPT hash value link was not submitted.

**Comment by halloffameworld** [comment]
BSC-JETCoin-0x666661228151A1cbdC4469dccCbaC139BaE12911-https://bscscan.com/tx/0xbbb9c0fce201b2e8262e8e1c271714a85a668e686a31c149621a0158ee22af9b

**Comment by halloffameworld** [comment]
https://bscscan.com/tx/0xcbe7408cb94a8382de45e39c0b2a4146ab0fb39abac0d833ed91d72637d796b1

**Comment by opera0001** [comment]
Abnormal token liquidity

**Pull request closed without merging**
