### PR TITLE
Add PECA logo and info

### PR DESCRIPTION
**Pull request by cwf404**

### CODE REVIEW

**Comment by cwf404** [comment]
BSC-TPT-0x47b5733b6714396397f5d861a5256933240b06587d113240247c727a4f054d5e-https://bscscan.com/tx/0x47b5733b6714396397f5d861a5256933240b06587d113240247c727a4f054d5e

**Comment by opera0001** [comment]
It is detected that the transaction rate can be modified, please explain what it does, thanks.

**Comment by cwf404** [comment]
Used as a trading slip point

**Comment by cwf404** [comment]
@opera0001 Used as a trading slip point

**Comment by cwf404** [comment]
> It is detected that the transaction rate can be modified, please explain what it does, thanks.

Used as a trading slip point

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Comment by cwf404** [comment]
@opera0001 Can I modify the token contract?

**Pull request merged**
