### PR TITLE
Add TPT logo and info 

### PR DESCRIPTION
**Pull request by jimmy13131313**
Sample

### CODE REVIEW

**Comment by jimmy13131313** [comment]
https://bscscan.com/tx/0x576fd2c86fe9ec17ca1fa7bbc57cf83734eb0d122549b72ec81412d6cd36d9f8

**Comment by opera0001** [comment]
The submitted (info.json) name and format are incorrect. Please review the tutorial content again: https://tphelp.gitbook.io/cn/wallet-operation/submit-token

Please re submit the logo application after adjustment or completion. Thank you for your support for tokenpocket.

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
