### PR TITLE
Add SWAN22 logo and info

### PR DESCRIPTION
**Pull request by MrMDC**
https://hecoinfo.com/tx/0xf571193b51fdb709f4572d77d1aa1ae2dc425c7be8d1b7f48d69c4f0693b2302

### CODE REVIEW

**Comment by logobaoguo** [comment]
专业提交logo！加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by sammvio** [comment]
Please submit the checksum address that includes uppercase and lowercase characters.

**Comment by MrMDC** [comment]
so i need to do the submit step one again?

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
