### PR TITLE
add CF logo

### PR DESCRIPTION
**Pull request by czmhxt**
https://bscscan.com/tx/0x4cc8b84ce6949e6dd7a635e338b2e553d67eee5d380297ffd83ad30520ef9c08

### CODE REVIEW

**Comment by opera0001** [comment]
The submitted logo is not 256x256 pixels, please modify it within 24 hours.

**Comment by czmhxt** [comment]
It has been resubmited  thank you



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年03月03日 11:41 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [TP-Lab/tokens] add CF logo (PR #5972) |

The submitted logo is not 256x256 pixels, please modify it within 24 hours.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by TokenPocket-JAN** [comment]
Professional expedited review. Please reply to the email if you need.
QQ112831047

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
