### PR TITLE
Add DreamDAO info and logo

### PR DESCRIPTION
**Pull request by DeFiProjectLaunch**
DreamDAO is a decentralized DeFi project initiated by community organizations to help ordinary people realize their dream of buying a house.

3000TPT transfer hash: 0x30e920abed8c84225d0209dc9b6af3b412e6758340758498b8f450dd56aa9c4a

### CODE REVIEW

**Comment by sammvio** [comment]
Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by SafuAuditOfficial** [comment]
> Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token

I can't submit token, cause it shows token repeatly, how should i do?

**Pull request closed without merging**
