### PR TITLE
RE Add TX logo and info

### PR DESCRIPTION
**Pull request by txcommon**
TRON-TX-THeqBTH8vfn2FT65PxzXUCKKFAAxV4ciXC-https://bscscan.com/tx/0x2990aff26e90d340866dcc75580d364dfa2cae5fca2a3dd290388354c38bca34

### CODE REVIEW

**Review by txcommon — COMMENTED** [review]
TRON-TX-THeqBTH8vfn2FT65PxzXUCKKFAAxV4ciXC-https://bscscan.com/tx/0x2990aff26e90d340866dcc75580d364dfa2cae5fca2a3dd290388354c38bca34

**Comment by txcommon** [comment]
Has been back online as required

**Comment by guoxintongsam** [comment]
Tron token logo upload is not allowed for now.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
