### PR TITLE
Add DHD info and logo

### PR DESCRIPTION
**Pull request by qy050957**
https://bscscan.com/tx/0x662b197e565ce4fab4560903e5499b904b0cd5c23e0273e58181ce9542f4812d

### CODE REVIEW

**Comment by qy050957** [comment]
Submitted two tokens, please help review

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3076439606

**Comment by sammvio** [comment]
The contract doesn’t verify and published. (No open-source)

**Comment by qy050957** [comment]
> The contract doesn’t verify and published. (No open-source)

Could you please tell me the specific reason? The contract is open source, and the tokens are also submitted to the bsc chain of TP

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
