### PR TITLE
ADD T0T logo and info (NEW)

### PR DESCRIPTION
**Pull request by L402325810**
3000 TPT  id:  https://bscscan.com/tx/0x2d57d7823478ab9ac841d3f7aa4be3286cbda7189f28fd1a2ffc9a47a9e4ab06

### CODE REVIEW

**Comment by opera0001** [comment]
0x847dc3409c91cA15CA2518eC64a72b1206EA9A21--There may be some risks if the ownership is not abandoned.
Please re submit the logo application after adjustment or optimization. Thank you for your support for tokenpocket.

0x4AeFDd11b4d69E64AB6903e1f9A26A7B9aA1fE06--done

**Comment by opera0001** [comment]
Two logo reviews, one TPT donation hash value, and no verification link was submitted.

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
