### PR TITLE
Add 1HT Logo And Info

### PR DESCRIPTION
**Pull request by TaurusCoin988**
0xada65e471d82102f0f1f3c056deb8bb0f2ceae56cd81f68fb6ae850cfa581eac

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Please re-submit your files attached TPT transfer link on [Commit changes].

**Comment by TaurusCoin988** [comment]
I have submitted the TPT link.



发自我的iPhone


------------------ Original ------------------
From: guoxintongsam ***@***.***&gt;
Date: Mon,Aug 30,2021 5:16 PM
To: TP-Lab/tokens ***@***.***&gt;
Cc: TaurusCoin988 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [TP-Lab/tokens] Add 1HT Logo And Info (#2944)





 
Please re-submit your files attached TPT transfer link on [Commit changes].
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by TaurusCoin988** [comment]
https://hecoinfo.com/tx/0xada65e471d82102f0f1f3c056deb8bb0f2ceae56cd81f68fb6ae850cfa581eac

**Comment by guoxintongsam** [comment]
Please re-submit your files to heco folder

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Pull request closed without merging**
