### PR TITLE
add MCU logo and info

### PR DESCRIPTION
**Pull request by logozhuanyong**
https://bscscan.com/tx/0x90b21f3b545b3bb00baa393ef3ab44248211c2945d1ad089307c8b1ba89f9c2d

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token

**Comment by logozhuanyong** [comment]
> Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token

之前就已经提交过了

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
