### PR TITLE
Add MBGB logo and info

### PR DESCRIPTION
**Pull request by MBGBToken**
0xf8b71d71bfc16bd047dcb83d51bb2a4a8d8a6c992ecb74a201522b0913687bfe
https://bscscan.com/tx/0x7d5ea15fc5f29673724c961318947fd6df5b48db3ff47b710ca53557a97e270f

### CODE REVIEW

**Comment by opera0001** [comment]
Unable to sell 100%, this issue must be notified to all participants and holders, otherwise the other party will think your tokens are unsellable and will report it as a scam.

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Comment by MBGBToken** [comment]
How to notify all holders？

**Comment by MBGBToken** [comment]
All current currency holders already know that the transfer cannot be 100% out. Do I need to do any other notices?

**Pull request merged**
