### PR TITLE
Add LOD logo

### PR DESCRIPTION
**Pull request by shgjasduwj**
https://www.bscscan.com/tx/0x04e69ea07e6c03b495fdc5b7c3afa3f4b851aeb69ef4791e495d53df424544ef

### CODE REVIEW

**Comment by opera0001** [comment]
The token logo submission is not 256x256 pixels. There is no problem with others. Please re submit the logo application after adjustment. Thank you for your support for tokenpocket.

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
