### PR TITLE
Add CALIT logo and info

### PR DESCRIPTION
**Pull request by gaoyuanme**
https://bscscan.com/tx/0x150d150fed57099ccb6b0ec60c3970f94aa67e3ca2306ea40da8dcac8ad4697d

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3579750034

**Comment by sammvio** [comment]
Please delete the wrong files.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
