### PR TITLE
Upload PennyWise Logo

### PR DESCRIPTION
**Pull request by adamsmithv6**
TPT - https://bscscan.com/tx/0x98c02d350d2431a6bb6f2bb0739895ddf5d3bff9b2f11de6e46bdeb46a302588
BNB - https://bscscan.com/tx/0x0792ed20554aefbc62807873facf9891d9b602a1c32dcd86cef9a258af14e17c

### CODE REVIEW

**Comment by opera0001** [comment]
The submitted logo is not 256x256 pixels, please adjust it.

**Comment by fomodaotoken** [comment]
logo png

**Comment by fomodaotoken** [comment]
@opera0001 logo size updated. Please check.

**Comment by adamsmithv6** [comment]
logo png

**Comment by adamsmithv6** [comment]
Logo size uploaded @opera0001

**Pull request merged**
