### PR TITLE
add sinsfeg info and logo

### PR DESCRIPTION
**Pull request by sinsfeg**
trade link: https://bscscan.com/tx/0x16898d09dcadf03f50b9578e22ac45602d65b3fe4f3696acaafdf0b1b853590b?utm_source=tokenpocket
hash link : https://bscscan.com/tx/0x16898d09dcadf03f50b9578e22ac45602d65b3fe4f3696acaafdf0b1b853590b

### CODE REVIEW

**Comment by opera0001** [comment]
1. Contract not open source
2. Working capital pool not viewed
3. There are currency holding and transaction data on the chain, and the circulation mode of tokens is unclear, so there are certain risks
Please re submit the logo after adjustment or optimization. Thank you for your support for tokenpocket.

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
