### PR TITLE
Add FIRE logo and info

### PR DESCRIPTION
**Pull request by ldzx2020**
https://bscscan.com/tx/0xc7c5066d738bf8a1faf93ecaf1e5a2901b771e6735cd784b791b6e126eef3dde?utm_source=tokenpocket

### CODE REVIEW

**Comment by guoxintongsam** [comment]
please resubmit website.

**Comment by ldzx2020** [comment]
Hello



发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年11月02日 10:46 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [TP-Lab/tokens] Add FIRE logo and info (PR #3778) |

please resubmit website.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
