### PR TITLE
Add TAXI logo and info

### PR DESCRIPTION
**Pull request by liu66331**
https://bscscan.com/tx/0xbc61b3e5c5616c3bfdbabc62ccc947333ec1cef98434937515d90bae9b39efe8

### CODE REVIEW

**Comment by opera0001** [comment]
1. Token contract is not open source, so the contract security cannot be verified
2. The contract does not give up control

**Comment by opera0001** [comment]
I sent you the problems in contract review 19 hours ago. So far, I haven't seen any changes in token contract, so I need to close the order. After closing the order, you need to submit it again. Please know that the TPT donation fee has increased to 30000.

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
