### PR TITLE
add logo and info

### PR DESCRIPTION
**Pull request by safedoge-bsc**
https://bscscan.com/tx/0xb472adafd33783a33a846f9cccafeef97622ed735d35440f9fff6481267a4808?utm_source=tokenpocket

### CODE REVIEW

**Comment by safedoge-bsc** [comment]
Good Evening/Morning, Thank you for taking the time to add logo and info to our BSC token. Please let me know if further information is needed.
Sincerely,
Froilan Sales

**Comment by safedoge-bsc** [comment]
logo

**Comment by zhujiayu03** [comment]
Added

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Pull request closed without merging**
