### PR TITLE
Add SPACE COIN logo

### PR DESCRIPTION
**Pull request by JasoniMatthewsF42l**
TPT
https://bscscan.com/tx/0x5a7d9c6c7543673b5344ec9a69727e956455c21969e985c00fa14c86f1ad4743

### CODE REVIEW

**Comment by opera0001** [comment]
1、It is detected that the token rate can be modified. Please explain the situation.
2、The submitted file is not saved in the BSC directory, please adjust it again.
image

**Comment by JasoniMatthewsF42l** [comment]
Done readjust, contract ownership renounced

**Comment by JasoniMatthewsF42l** [comment]
@opera0001

**Comment by opera0001** [comment]
If the logo is not appropriate after the collection, please pass it within 24 hours https://github.com/TP-Lab/tokens/issues Communicate with us and submit a new logo

**Comment by JasoniMatthewsF42l** [comment]
Please check the issue #7548 thank you!

**Comment by JasoniMatthewsF42l** [comment]
@opera0001

**Pull request merged**
