### PR TITLE
Add RPO logo and info

### PR DESCRIPTION
**Pull request by 15896209474**
HECO-RPO-0xe2e590a73b49383dd2dd2df8fd89ed3ac20b688f-https://hecoinfo.com/tx/0x1200d070ff98f8930e0813ff1a89ab16246dab261690efa71db737e1169f1d37

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3579750034

**Comment by sammvio** [comment]
Please re-submit these tokens separately and attach the TPT transfer link on [Commit changes].

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3579750034，审核失败的走加速审核包通过

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
