### PR TITLE
Add WZGL2 logo and info

### PR DESCRIPTION
**Pull request by smithrobert1419**
BSC-WZGL2-0x9005441C2206D0C2FCf15792cD24e0e8fAEb0bcC-https://bscscan.com/tx/0xc13553190c6549c52fa7ab2796ab2a511c63306f1e0cab836dbb4f15d951cafe

### CODE REVIEW

**Comment by opera0001** [comment]
It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

**Comment by smithrobert1419** [comment]
The submission I submitted has been open source, and the following address
has been submitted on github. Please manage and approve it, thank you.


https://github.com/TP-Lab/tokens/pull/7849/commits/0a7c93e82bf2779d3a96e52260dc192ccb3f3108


*Add WZGL2 logo and info*


*https://bscscan.com/tx/0xc13553190c6549c52fa7ab2796ab2a511c63306f1e0cab836dbb4f15d951cafe*
<https://bscscan.com/tx/0xc13553190c6549c52fa7ab2796ab2a511c63306f1e0cab836dbb4f15d951cafe>




*BSC-WZGL2-0x9005441C2206D0C2FCf15792cD24e0e8fAEb0bcC-*
*https://bscscan.com/tx/0xc13553190c6549c52fa7ab2796ab2a511c63306f1e0cab836dbb4f15d951cafe*
<https://bscscan.com/tx/0xc13553190c6549c52fa7ab2796ab2a511c63306f1e0cab836dbb4f15d951cafe>





opera0001 ***@***.***> 于2022年7月24日周日 00:20写道：

**Comment by opera0001** [comment]
Is there a security test report available after the open source is detected as a proxy contract?

**Comment by smithrobert1419** [comment]
The proxy contract is also open source, you can check it.

opera0001 ***@***.***> 于2022年7月26日周二 17:13写道：

**Comment by opera0001** [comment]
The order was submitted with a total of two contract addresses, one being 0xB6B149BF6BE92fedf792c74BF2aDB3FDc45eb9A8, which is not open source. The other is 0x9005441C2206D0C2FCf15792cD24e0e8fAEb0bcC This one has an agent contract.

**Comment by opera0001** [comment]
The order needs to be closed, the problem is still not solved, please go to issues and give us feedback.

https://github.com/TP-Lab/tokens/issues

**Pull request closed without merging**
