### PR TITLE
add Art logo and info

### PR DESCRIPTION
**Pull request by ZHANGMAZ1**
捐赠：https://bscscan.com/tx/0x090063b1cd2101a3cdc0ff9e373fc984d5afcfac7bf610e51b06838317db4511                                                                                                                  验证：https://bscscan.com/tx/0x83df8fefeaa112bc4caa6ea7d808f5104fa3b6c5c13d4ceed34fda711f86ee00

### CODE REVIEW

**Comment by opera0001** [comment]
The tokens cannot be sold 100%, please make them available to all participants or someone may report them.

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Comment by ZHANGMAZ1** [comment]
> 不能有 100% 的代币参与者都可以使用，否则有可能有人会使用。

Just to increase the holding address, the contract permission has been discarded, thank you

**Comment by opera0001** [comment]
image
The submitted file is not saved in the BSC directory, please adjust it again.

**Pull request closed without merging**
