### PR TITLE
add NB info and logo

### PR DESCRIPTION
**Pull request by hebi-xiaotiantian**
HECO - NB - 0x59420CDFD4Bc8F1BA448D3E71de54154cF0bF256 - https://hecoinfo.com/tx/0xedd96b3b6ef082af07646a21e55369eb3b36be17043af4592490a95184765bd7

### CODE REVIEW

**Comment by hebi-xiaotiantian** [comment]
Another stroke https://hecoinfo.com/tx/0x68f17ae0eef7471bf7b77eb07971b0f46360f890ccf16e78453bcc4f52819b03

**Comment by hebi-xiaotiantian** [comment]
Turned a total of two

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
