### PR TITLE
ADD MIS logo and info

### PR DESCRIPTION
**Pull request by WaterDrop-captical**
https://bscscan.com/tx/0x0a8dd3a8f0c3d757ca6745b61adcfa1375b643e597c59faee7d0ae5fb2ff033a
https://bscscan.com/tx/0x92c922ab96ae03a86db7b757fa943befdcd2ae58adb9a2e001c310e5aa142973

### CODE REVIEW

**Comment by opera0001** [comment]
Please don't worry. The audit is expected tomorrow. Please wait patiently.

**Comment by opera0001** [comment]
There may be risks if the token transaction is not started and the control right of the token contract is not discarded. Now the logo review cycle is relatively short. It is recommended that you discard the token ownership or resubmit the logo after the token transaction starts. I'm very sorry.

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request merged**
