### PR TITLE
Add sodk logo and info

### PR DESCRIPTION
**Pull request by FIF33578**
https://bscscan.com/tx/0x790cb97ad991ab58a2fd2ad3527664c077fb068be5c08c8f981fd473046fb7f7

### CODE REVIEW

**Comment by sammvio** [comment]
The project information is incomplete.

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
