### PR TITLE
Add CCC logo and info

### PR DESCRIPTION
**Pull request by panxianhai**
https://bscscan.com/tx/0x5e3b2b58f404e6c57622e31fd20ace0da5149588a001e2da610ad2449494f905

### CODE REVIEW

**Comment by panxianhai** [comment]
https://bscscan.com/tx/0xb2937433254f7464bf4d3ffaa191ed3a9398314972adaab7c9f99a2a37dcb3a7

**Comment by sammvio** [comment]
Tron token logo upload is not allowed for now

**Comment by panxianhai** [comment]
@sammvio When can I upload Tron token logo?

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
