### PR TITLE
Add SFTX logo and info

### PR DESCRIPTION
**Pull request by SafeFTX**
https://bscscan.com/tx/0x3bdf192c6dbf6fc2ecc54e25b7fcb7be008f2d81ae035575006ba3c119b0b022 https://bscscan.com/tx/0x5340b5645ead32e31bbe83f11b9bfe27309b8233333289ef58cd92380ac908fd

### CODE REVIEW

**Comment by SafeFTX** [comment]
pls add logo and token info as soon as possiable, thx :)

**Comment by opera0001** [comment]
0x07b5a6dD83C33F52f4cDa1fA1D2cf2868bc462f8 
Who is the holder of this address?

**Comment by SafeFTX** [comment]
> 
0x07b5a6dD83C33F52f4cDa1fA1D2cf2868bc462f8
this is pinksale presale contract address

**Comment by SafeFTX** [comment]
> 0x07b5a6dD83C33F52f4cDa1fA1D2cf2868bc462f8 Who is the holder of this address?

pls check

**Comment by SafeFTX** [comment]
> 0x07b5a6dD83C33F52f4cDa1fA1D2cf2868bc462f8 Who is the holder of this address?

https://www.pinksale.finance/launchpad/0x07b5a6dD83C33F52f4cDa1fA1D2cf2868bc462f8?chain=BSC

**Comment by SafeFTX** [comment]
> 0x07b5a6dD83C33F52f4cDa1fA1D2cf2868bc462f8 Who is the holder of this address?

pls add logo and token info as soon as possiable, thx :)

**Pull request merged**
