### PR TITLE
ADD NY logo and info

### PR DESCRIPTION
**Pull request by qww530**
https://bscscan.com/tx/0xa0502d0ae23a224b621f0126fdcf846786197e025cca367089b9cfea0169ce69

### CODE REVIEW

**Comment by qww530** [comment]
ADD NY logo and info

**Comment by qww530** [comment]
Before has not been uploaded successfully, please help to upload NY icon, thank you!

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3579750034，审核失败的走加速审核包通过

**Comment by qww530** [comment]
邮件已收到，谢谢！

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by qww530** [comment]
邮件已收到，谢谢！

**Pull request closed without merging**
