### PR TITLE
Add KGT logo and info

### PR DESCRIPTION
**Pull request by boboda12138**
BSC-KGT-0x3b3069b2e5467c834d32f676afcaf4d1d21e3fd8-https://bscscan.com/tx/0xc05f49668076b743ad4a7095686b6deb8fddeddb12c9f820011aca240f5dbc82

### CODE REVIEW

**Comment by nenrgy** [comment]
专业提交logo,代币，白皮书，诚住经营，值得信赖，价格全网最优！QQ:2099728898

**Comment by boboda12138** [comment]
123

**Comment by sammvio** [comment]
Please submit the checksum address that includes uppercase and lowercase characters.

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
