### PR TITLE
add BNBDOGE logo and info

### PR DESCRIPTION
**Pull request by raofu1**
https://bscscan.com/tx/0xda38e02d1d72bf9ffd2c81a7df903046547ac000c1516770b3bbeb2def5d07ee

### CODE REVIEW

**Comment by opera0001** [comment]
1. Low token liquidity
2. The number of currency holding addresses and transaction activity are low
Please re submit the logo after adjustment or optimization. Thank you for your support for tokenpocket.

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
