### PR TITLE
Add ANTI logo and info

### PR DESCRIPTION
**Pull request by AntiBet**
https://hecoinfo.com/tx/0x0b972adf50202af5059817a3e522cecad2a93769314e8867a3ddd3293e50207d

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Tron token logo is not allowed for now.

**Comment by AntiBet** [comment]
When is the Tron token logo can be allowed and shown?

**Comment by AntiBet** [comment]
> Tron token logo is not allowed for now.

When is the Tron token logo can be allowed and shown?

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
