### PR TITLE
Add QBT logo and info

### PR DESCRIPTION
**Pull request by Tywl5**
3000TPT:https://bscscan.com/tx/0x9f01d60872ff212495053eccf28cc24744ce01208fc063a8f952d943fcf977eb

### CODE REVIEW

**Comment by opera0001** [comment]
There may be some risks if the ownership of the contract is not abandoned. Please re submit the logo after adjustment or optimization. Thank you for your support for tokenpocket.

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
