### PR TITLE
Add koalabear Logo

### PR DESCRIPTION
**Pull request by Koalabear2**
https://koabear.net

### CODE REVIEW

**Comment by tiaojiaotubiaobaoguo** [comment]
代提交logo，24小时内包过，加QQ：2980874528

**Comment by sammvio** [comment]
Please donate 3000 TPT as required and submit the transfer link on [Commit changes].

**Comment by Koalabear2** [comment]
Where we have to donate 3000TPT token.Please guideR
      
        
        
          On Nov 26 2021, at 2:11 am, SS ***@***.***> wrote:
          
        
        
          
Please donate 3000 TPT as required and submit the transfer link on [Commit changes].

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
