### PR TITLE
Revert "Add WIFI logo and info" #6274

### PR DESCRIPTION
**Pull request by zhanglu0523**
Please help me change the logo to a new contract address. The previous contract address could not be used normally. New contract address: 0x2F65E2dc766EfFF81F97faB91B7E364a692C851E

### CODE REVIEW

**Comment by opera0001** [comment]
Modifying the contract address or logo requires the previously submitted GitHub account to submit the order, and also requires a new TPT hash value link.

**Comment by zhanglu0523** [comment]
Do you mean you need to repurchase TPT? Does the previously purchased TPT not take effect?

**Comment by zhanglu0523** [comment]
30,000 TPT TX: https://bscscan.com/tx/0x8517d36f546dfc5427cdeba47b95adffb3a1b373095cedf8c7966a1c1d4c69f8
Confirm TX: https://bscscan.com/tx/0x517a1b3d0d5b41525d2a51ccdc5549bee75d3138ef082dfbe41e3f68774263e9

**Comment by opera0001** [comment]
The previous TPT has been used for order consolidation, so the logo or contract address needs to be modified later, and a new TPT hash value needs to be submitted.

**Pull request closed without merging**
