### PR TITLE
add token VRH

### PR DESCRIPTION
**Pull request by VersaillesHeroes**
Introduction:

VRH (Versailles Heroes) is a DAO (DeFi) financial infrastructure on the Ethereum chain, aiming to build a fast-growing TVL financial environment for DeFi investment. VRH tokens are issued through ERC-20 contracts and by utilizing the DAO protocol to achieve an open, transparent, and fair governance. In addition, it is committed to promoting the ecological development of DeFi and blockchain games. Investors can lock up VRH for 1, 2, 3, and 4 years to obtain veVRH. veVRH can be used to vote on network proposals and can also be used by investors to create a guild or join a guild for mining. To participate in the internal competition of the guild, investors can burn game token (MOH) in exchange for GAS, which can accelerate the weight of their individual mining by up to 2.5 times. In this way, a competitive environment that promotes the growth of market value is established, and investors who participate in the competition by using GAS acceleration can obtain higher returns.

### CODE REVIEW

**Comment by opera0001** [comment]
1. 0xa59e341e8047498700ed244814b01b34547fb21b This contract has a setting for token increase issuance, please explain the role.
2. The submitted logo is not 256x256 pixels
3. A github account can only submit one json and logo file at a time
4, please submit a link to the tpt hash, a hash can only guarantee a logo review.

**Comment by VersaillesHeroes** [comment]
> 1. 0xa59e341e8047498700ed244814b01b34547fb21b This contract has a setting for token increase issuance, please explain the role.
> 2. The submitted logo is not 256x256 pixels
> 3. A github account can only submit one json and logo file at a time
>    4, please submit a link to the tpt hash, a hash can only guarantee a logo review.

@opera0001 I have only re-submit ERC20 token: VRH and its logo (256*256 pixels).
tpt Hash: https://bscscan.com/tx/0xfd81d31925485f421e425270b5e3a98003ca910fa3d66188f2cce9262fe63467

**Comment by VersaillesHeroes** [comment]
Dear TP-Lab/tokens support team,

@opera0001 <https://github.com/opera0001> I have only re-submit ERC20
token: VRH and its logo (256*256 pixels).
tpt Hash:
https://bscscan.com/tx/0xfd81d31925485f421e425270b5e3a98003ca910fa3d66188f2cce9262fe63467
bnb transfer hash:
https://bscscan.com/tx/0xdf2db436a528f9650d88c2ee837095f129277aaeac7ebf7a36b81dfca0424b8b

Regards,

Versailles Heroes Team

**Comment by VersaillesHeroes** [comment]
@opera0001 I still can't view my token VRH logo under TP wallet. When can I see its logo?

**Pull request merged**
