### PR TITLE
add minibull logo and info

### PR DESCRIPTION
**Pull request by ZHANGMAZ1**
0x6e179b31ee0b745e1d75e3e435ea7facad444f5dabb1b47529a21ae14d209aa7

### CODE REVIEW

**Comment by ZHANGMAZ1** [comment]
0x6e179b31ee0b745e1d75e3e435ea7facad444f5dabb1b47529a21ae14d209aa7

**Comment by ZHANGMAZ1** [comment]
0x6e179b31ee0b745e1d75e3e435ea7facad444f5dabb1b47529a21ae14d209aa7

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
