### PR TITLE
Add ROD logo and info

### PR DESCRIPTION
**Pull request by bscrod**
BSC-ROD-0x9a829d93b956193bb3c28182e72d1052f3ec4893-https://bscscan.com/tx/0x1dfc9a71ff927daee1ae18ad257e6e8cafffcd4b1050b5b43f39a5c027a752a4

### CODE REVIEW

**Comment by opera0001** [comment]
Now you need 30000 TPT donations to apply for logo inclusion. Please supplement the difference and submit the hash value corresponding to the supplemented difference to us through GitHub. Thank you.

**Comment by giki0318** [comment]
According to the DAO, the donation amount for a logo update has been updated to 30,000 TPT. [Click here for Details](https://snapshot.org/#/tptdao.eth/proposal/0x781abc1ade2ebd082aec4f57b7199d472a2b2850b3df46c8ec37e3b6a1a243c2)

**Comment by jjjgjk** [comment]
你好

**Comment by tplogotijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
