### PR TITLE
Add FTP logo and info

### PR DESCRIPTION
**Pull request by fptnft**
https://bscscan.com/tx/0xa0435f16f3fc5cccd860b315e42c99e53501c91ff87f8a068ee8e50e8a02528b

### CODE REVIEW

**Comment by opera0001** [comment]
What does this token have to do with FPT (#6050)? The logo is the same.

**Comment by fptnft** [comment]
This is a mistake. Please let me upload it again. Please.

**Comment by fptnft** [comment]
These two are uploaded by me, but they are all wrong uploads, but I can't find a way to close them. Please forgive me. I'm a novice. Please allow me to upload them again, please

**Comment by opera0001** [comment]
Then I'll restore both to the default, and then close the GitHub order. You can submit it again.

**Comment by tplogotijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by fptnft** [comment]
Thank you very much

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
