### PR TITLE
Add WK logo and info

### PR DESCRIPTION
**Pull request by Kelvinorin**
50,000TPT TX: https://bscscan.com/tx/0xb06c74d450e54f7d41a098e83f79a8fd697f5b15524c2db7c9e8c8017fcabbe2
Verification TX: https://bscscan.com/tx/0xffa5012ccc719e1d77c81a786af7301b9fb954dcd10caa1ac85b3dba8ef9d906

### CODE REVIEW

**Comment by opera0001** [comment]
It was detected that the tokens could not all be sold.

**Comment by Kelvinorin** [comment]
> It was detected that the tokens could not all be sold.
This the requirement of token design to keep the token hold member up.

**Comment by Kelvinorin** [comment]
> It was detected that the tokens could not all be sold.
This is the requirement of token design to keep the token hold member up.

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Pull request merged**
