### PR TITLE
add BHET logo and info

### PR DESCRIPTION
**Pull request by xwd1314191**
https://bscscan.com/tx/0x95f713f9721c6a18a8e690fc0633b745bcd5917f2cfa92dfb1db1041691e8d0c

BSC-BHET-0x530F5ae8CeD8fa82a3664E95771A42F6b944af0e-https://bscscan.com/tx/0x11c56cd3556ec62c66de63417120c1feff7b7e1c54d4db7d964fad30fb8d83f4

### CODE REVIEW

**Comment by opera0001** [comment]
The submitted hash has already been used by: https://github.com/TP-Lab/tokens/pull/10981. Please check.

**Comment by xwd1314191** [comment]
麻烦合并

**Comment by xwd1314191** [comment]
Use this logo instead

**Comment by opera0001** [comment]
Sorry, this order cannot be recorded because they are completely different contract addresses.

**Comment by xwd1314191** [comment]
已经在次转入了，请核查审批
交易哈希凭证：https://bscscan.com/tx/0x02479aec070462e93ab8c5606b4114f1acad05ca74572211761f7b0fdb7941c5

转账凭证哈希：BSC-BHET-0x530F5ae8CeD8fa82a3664E95771A42F6b944af0e-https://bscscan.com/tx/0x63847830731d7af8d0d70420a4e02af421d7eb2c32f3c76d3eda223a52b3ab2b

**Comment by xwd1314191** [comment]
已经在次转入了，请核查审批
交易哈希凭证：https://bscscan.com/tx/0x02479aec070462e93ab8c5606b4114f1acad05ca74572211761f7b0fdb7941c5

转账凭证哈希：BSC-BHET-0x530F5ae8CeD8fa82a3664E95771A42F6b944af0e-https://bscscan.com/tx/0x63847830731d7af8d0d70420a4e02af421d7eb2c32f3c76d3eda223a52b3ab2b

**Comment by xwd1314191** [comment]
微信图片_20240925110311

**Review by gsqtoken — APPROVED** [review]

**Review by gsqtoken — APPROVED** [review]

**Pull request merged**
