### PR TITLE
Add YOLK logo and info

### PR DESCRIPTION
**Pull request by asas1232**
Add YOLK logo and info

### CODE REVIEW

**Comment by asas1232** [comment]
Add YOLK logo and info
1000tpt https://hecoinfo.com/tx/0x68df665e831df19084e31258e26a4f2495188b2bfc5c5651cd988f4c7c5f2659

**Comment by zhujiayu03** [comment]
Please refer to the tutorial, and re-submit your files in the correct format.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
