### PR TITLE
add Tcoin logo and info

### PR DESCRIPTION
**Pull request by ToNFT**
https://bscscan.com/tx/0x3e4e2f7a25fc374e00cf01d1094d8755feb91790c091760224cf6867d789c3e3

### CODE REVIEW

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Comment by ToNFT** [comment]
> 申请已收到，请等待等待任何的消息，并保护自己的非官方广告宣传。

thanks. when can i see my avatar

**Comment by ToNFT** [comment]
tcoin正式合约地址是 : 0x247b7aa3c383a97643f5d35f0ba80f4290250672

**Comment by ToNFT** [comment]
tcoin正式合约地址是 : 0x247b7aa3c383a97643f5d35f0ba80f4290250672

我想知道是否可以上传头像

**Comment by ToNFT** [comment]
Hello, this is the contract address of my previous coin: Tcoin token open
source contract
0xc8dfa3379a00C00CF033CE566AD13b93f9ACB636

But recently I changed my address, the official tcoin contract address is:

0x247b7aa3c383a97643f5d35f0ba80f4290250672
Can you replace it for me?

**Comment by ToNFT** [comment]
Whether it is possible or not. Please give me a reply. thanks

**Comment by ToNFT** [comment]
I want to transfer my token Tcoin from the old address:
0xc8dfa3379a00C00CF033CE566AD13b93f9ACB636
change to new address
0x247B7aa3c383A97643f5d35f0bA80f4290250672
Please help me change it, thanks

**Pull request merged**
