### PR TITLE
add ShenShou info and logo

### PR DESCRIPTION
**Pull request by popoyang**
https://bscscan.com/tx/0x494eac382bb0703cc7e836a2b047d429ab4a2d77618da9223addd2b3dd9337c0

### CODE REVIEW

**Comment by opera0001** [comment]
image
The submitted file is not saved in the BSC directory, please adjust it again.

**Comment by popoyang** [comment]
adjust to bsc dir

**Comment by popoyang** [comment]
The ShenShow Token (0x8ec3b6c0a3b869a01dc884267495cda879f90608) logo is not   displayed in TokenPocket app. when does it work？

**Comment by opera0001** [comment]
1. Token trading can be suspended 
2. Token rates can be modified
3. Blacklist function exists 

Please explain the reasons for these problems.

**Comment by popoyang** [comment]
ShenShou is the public chain currency of Shan Hai Jing. The Shanhaijing（SHJ） public chain is being tested. In order to better test and find problems, we have not given up permissions now. After the Shanhaijing public chain test is completed, the authority of the Token will be given up, and the three problems 1, 2, and 3 will not exist

**Pull request merged**
