### PR TITLE
Add GORKXL logo and info

### PR DESCRIPTION
**Pull request by HebrewMan**
https://bscscan.com/tx/0x63a086221601e6ae81eff06a1ddb844d74cdbc9d578afb02d7dcbd313fe581dc

### CODE REVIEW

**Comment by opera0001** [comment]
The submitted logo is not 256x256 pixels; please make the necessary adjustments.

**Comment by opera0001** [comment]
If no response or changes are seen from you in the next 3 days, the order will need to be closed. You can reach out to me through the issues to continue the completion of this order.

https://github.com/TP-Lab/tokens/pulls

**Comment by HebrewMan** [comment]
Sorry, I have been too busy recently and forgot to reply to you. Now that I have the size of the logo figured out, how do I continue?

**Comment by HebrewMan** [comment]
I don’t know how to operate it now. I have prepared a 256*256 Logo. 我现在不知道应该如何操作 我已经准备好了 256*256的Logo

**Comment by HebrewMan** [comment]
logo

**Pull request closed without merging**
