### PR TITLE
Add CATCEO info and logo

### PR DESCRIPTION
**Pull request by BlackSpaceCreative**
Add CATCEO info and logo

### CODE REVIEW

**Comment by BlackSpaceCreative** [comment]
TPT hash https://bscscan.com/tx/0x421bd2aeec2aeeaef4d6c7ed0bf96cf0a2b7c1a10296caa2c4eec5a7bf088d40

**Comment by opera0001** [comment]
image
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Comment by opera0001** [comment]
The submitted file is not saved in the BSC directory, please adjust it again.

**Comment by BlackSpaceCreative** [comment]
> The submitted file is not saved in the BSC directory, please adjust it again.

Updated file and logo to bsc file, please check again. Thank you

**Pull request merged**
