### PR TITLE
Add FWS logo and info

### PR DESCRIPTION
**Pull request by FWSSS**
https://bscscan.com/tx/0x074382759b79e7a847342f1b9c14624f391f38c5cc6c52e367e9f948f8a7c545

### CODE REVIEW

**Comment by opera0001** [comment]
It is detected that the transaction can be suspended. Please explain.

**Comment by opera0001** [comment]
Please check the TPT submission quantity. Thank you.

**Comment by FWSSS** [comment]
the extra 20000 TPT was made up ,and the trade is open,transaction canwill not be suspended,please chek it again

**Comment by FWSSS** [comment]
The early coins closed the buy function to add the pool, and now the buy function has been opened. The sell function is not limited, and the contract authority will be discarded at the same time

**Pull request merged**
