### PR TITLE
Add MSW logo and info

### PR DESCRIPTION
**Pull request by MountainSeaWorlds**
exchange 50000 TPT：   https://bscscan.com/tx/0xa210013872dc766ae499f608d220ff1c3964a563100051fcfdbcefeff7ace269
verify hash:  https://bscscan.com/tx/0xe31a3aa620d5454182d5ba3a98166a9fdc10b37e87d080bb1cb08dc8869e2ea5

### CODE REVIEW

**Comment by opera0001** [comment]
It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

**Comment by MountainSeaWorlds** [comment]
> It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.


contract  code had been verified now

**Comment by opera0001** [comment]
Detected tokens exist hidden owenr contract, this has a lot of risk.

**Comment by MountainSeaWorlds** [comment]
> 检测到的代币存在隐藏的 owenr 合约，这有很大的风险。

ok， what should i do for it?

**Comment by MountainSeaWorlds** [comment]
> I'm sorry, the issuer is needed to deal with.

i know, how to deal it ? i transfer all the owner to zero address ?

**Comment by opera0001** [comment]
I'm sorry, I don't know how to adjust, but hidden owner exists, there will be a big risk, unless you have a formal security audit report

**Comment by MountainSeaWorlds** [comment]
> I'm sorry, I don't know how to adjust, but hidden owner exists, there will be a big risk, unless you have a formal security audit report
4511683169745_ pic
4501683169673_ pic


I have transfer all the owner to  zero address，you can let your technicians check it out
transfer hash:0x26c5f64240883c0283a0170bb6f4314135b7054b11c0611730be17ff596a1907,

**Pull request merged**
