### PR TITLE
Add deod token logo and info

### PR DESCRIPTION
**Pull request by mayureshpwr**
Description : Decentrawood is a metaverse token, designed and built on the Polygon network for enhanced scalability and efficiency in virtual worlds.

TPT : https://bscscan.com/tx/0x3ad989a0ccdf4ca999621c35581e2120b5e381dd70e2b8e442cd1687afe3a41f
BNB : https://bscscan.com/tx/0xd8d863f9ae338df5010e74bc1b5a8252e13f58ce7e570fac7174b1f56070eefc

### CODE REVIEW

**Comment by opera0001** [comment]
A setting has been detected in the contract that allows for the issuance of additional tokens. This could pose a risk, so please explain its purpose.

**Comment by mayureshpwr** [comment]
> A setting has been detected in the contract that allows for the issuance of additional tokens. This could pose a risk, so please explain its purpose.

As per the contract, Mint function logic is as follows. 
Maximum issuance of tokens possible (maximum supply) is 2 billion. Out of it 5% was minted at the time of deployment (1% is held by airdrop Wallet Address and 4% held by liquidity Wallet Address). There are four administrative wallet that has right to allot the tokens (admin, marketing Team Address, development Team Address, strategic  Alliance Team Address) up to 10% of the maximum supply i.e 200 million .  55% of the maximum supply i.e. 1.1 billion is available for allotment against payment of the USDT through the contract. Proceeds of which is going to 2 addresses of the creator of the platform equally. Allotted tokens will be available for minting to the allotee daily i.e. each 24 hours for 3 years period as per following logic. First year 40%, second and third year 30% each of the allotted tokens. we also audited the token contract link: https://app.solidproof.io/projects/decentrawood

**Comment by mayureshpwr** [comment]
how much time will it take ?

**Comment by mayureshpwr** [comment]
> A setting has been detected in the contract that allows for the issuance of additional tokens. This could pose a risk, so please explain its purpose.

i have already explained the purpose so how much time it will take ?

**Pull request merged**
