### PR TITLE
Add HOWG logo and info

### PR DESCRIPTION
**Pull request by 182418502**
https://www.bscscan.com/tx/0x4f3e1e1932806c8a682724c25677d39a3a0f051468be8eb1e82a509c15f2504c

### CODE REVIEW

**Comment by tubiaoyingji** [comment]
专业加快提交LOGO，20分钟内审核包过，QQ：1450001284

**Comment by sammvio** [comment]
Please submit the checksum address that includes uppercase and lowercase characters.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
