### PR TITLE
Add  GMC  logo

### PR DESCRIPTION
**Pull request by fsfadgst**
https://www.bscscan.com/tx/0xe03a6d7fa8acc0e41a22aff3c9d54b7992ba96157b2bdf2125fb6668d34a0dc0

### CODE REVIEW

**Comment by opera0001** [comment]
1. Not relinquishing ownership
2. Insufficient working capital pool
3. There is an additional issuance mechanism and there are risks
Please submit again after adjustment. Thank you for your support for tokenpocket

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
