### PR TITLE
Add UFC log and info

### PR DESCRIPTION
**Pull request by king0012-star**
0xd3acebda262c2a90b05e7b01777a906b4376b6eba445e44012ba7ae2f39c2dac

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Since we cannot find out the 100 TPT transfer record, please attach the record on Pr.

**Comment by king0012-star** [comment]
0xd3acebda262c2a90b05e7b01777a906b4376b6eba445e44012ba7ae2f39c2dac

**Comment by king0012-star** [comment]
bsc chain

**Comment by king0012-star** [comment]
https://bscscan.com/tx/0xd3acebda262c2a90b05e7b01777a906b4376b6eba445e44012ba7ae2f39c2dac

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
