### PR TITLE
Floki ($Floki) is a peer-to-peer cryptocurrency

### PR DESCRIPTION
**Pull request by werx111fds**
Floki ($Floki) is a peer-to-peer cryptocurrency with built-in ARF technology. It's a completely decentralized, point-to-point digital currency, completely controlled by its community. Each user is (in theory) the same owner and contributor of the network.

### CODE REVIEW

**Comment by GUOCAT** [comment]
oh Sorry, the information has not passed the review

**Comment by zhujiayu03** [comment]
Added

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
