### PR TITLE
Add JHT logo and info

### PR DESCRIPTION
**Pull request by jam00001**
50000TPT链接：https://bscscan.com/tx/0x4791b4fc5c425f4d5370677cad9701674705a1923fa31bb4411c07d84fea1a9e
验证链接：https://bscscan.com/tx/0xbd26a18e649bb9f2537ed1cffef1931acc8f0f6d550f743a9fdbe84b1be62e06

### CODE REVIEW

**Comment by opera0001** [comment]
It is detected that there is a switch to control token transactions. Please explain the situation.

**Comment by jam00001** [comment]
There is no switch to control token transactions.Just control whether to charge a fee

**Comment by opera0001** [comment]
It is detected that there may be a risk of suspension of transactions.

**Comment by opera0001** [comment]
We haven't received your reply after 3 days, and the order is closed. If you have any questions, you can pass the https://github.com/TP-Lab/tokens/issues Contact, thank you.

**Pull request closed without merging**
