### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by SSFSSF520520**
https://bscscan.com/tx/0xd5903c2fd2d44326dd1f747c0d971889b709f98c4b3a78ece6689c69f1e9cd30?utm_source=tokenpocket

### CODE REVIEW

**Comment by opera0001** [comment]
The token contract is detected to have hidden owner permissions, which pose the greatest risk. To consider inclusion, a code security audit report from a reputable security company is required.

**Comment by SSFSSF520520** [comment]
您好！权限还没有丢弃，目前在开发生态中，等DAPP开发完成后，会丢掉权限，麻烦给以通过，谢谢！
















At 2024-04-24 21:24:12, "opera0001" ***@***.***> wrote:

The token contract is detected to have hidden owner permissions, which pose the greatest risk. To consider inclusion, a code security audit report from a reputable security company is required.

**Comment by opera0001** [comment]
> 您好！权限还没有丢弃，目前在开发生态中，等DAPP开发完成后，会丢掉权限，麻烦给以通过，谢谢！ At 2024-04-24 21:24:12, "opera0001" ***@***.***> wrote: The token contract is detected to have hidden owner permissions, which pose the greatest risk. To consider inclusion, a code security audit report from a reputable security company is required. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

Dropping token control permissions does not disable the hidden owner functionality. Therefore, you need to provide a code audit report from a reputable security firm.

**Comment by opera0001** [comment]
Dropping token control permissions does not disable the hidden owner functionality. Therefore, you need to provide a code audit report from a reputable security firm.

**Comment by SSFSSF520520** [comment]
您好！影藏权限用于DAPP调用合约，这个后期挖矿都是铸造出来的，需要调用合约，麻烦给以通过，谢谢！













At 2024-04-26 09:46:42, "opera0001" ***@***.***> wrote:

Dropping token control permissions does not disable the hidden owner functionality. Therefore, you need to provide a code audit report from a reputable security firm.

**Comment by SSFSSF520520** [comment]
就是代币内嵌了2个分红的合约，因为是有持币分红和LP分红的




VISA买卖有滑点手续费分红，所以代币内嵌有分红合约逻辑，用于分配持币分红和LP分红的










At 2024-04-26 09:46:42, "opera0001" ***@***.***> wrote:

Dropping token control permissions does not disable the hidden owner functionality. Therefore, you need to provide a code audit report from a reputable security firm.

**Pull request merged**
