### PR TITLE
Add CBT logo and info

### PR DESCRIPTION
**Pull request by cbt-dao**
https://bscscan.com/tx/0xcfbf7bd62fdf8b8faff60efdffc95e1da5164c750b87e28ea8d30f3af04b115b

### CODE REVIEW

**Comment by cbt-dao** [comment]
https://bscscan.com/tx/0xcfbf7bd62fdf8b8faff60efdffc95e1da5164c750b87e28ea8d30f3af04b115b

**Comment by opera0001** [comment]
1. the tokens have not started trading, what is their plan 
3. the presence of a suspend trading setting is detected, what does it do

**Comment by cbt-dao** [comment]
Now it can be sold, but almost no one has sold it yet, so it can't be bought for the time being. The number of users has been increased, and we will open the buy function again. The buy function should have a switch when the transaction is suspended

**Comment by cbt-dao** [comment]
Please check it for me. Thank you

**Pull request merged**
