### PR TITLE
Add DOD and logo

### PR DESCRIPTION
**Pull request by DOD195450508**
Add DOD and logo

### CODE REVIEW

**Comment by tubiaoyingji** [comment]
专业加快提交LOGO，20分钟内审核包过，QQ：1450001284

**Comment by DOD195450508** [comment]
https://bscscan.com/tx/0x2908603568df53f6556055aca6cf2e8d79f436c574bc2220987451e5f35b2c27

https://bscscan.com/tx/0x243ed9f89326a9e76e1cdfac9305a56dab65c85b6d5392191a6deda63c84a05c

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by opera0001** [comment]
1. The submitted web address cannot be opened
2. Administrator privileges were not waived
3. Higher buying and selling rates
Please re submit the logo application after adjustment or optimization. Thank you for your support for tokenpocket.

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
