### PR TITLE
Add LionCoin logo and info

### PR DESCRIPTION
**Pull request by LionCoin2021com123**
https://bscscan.com/tx/0xacac1465b4fa8005731dacc02a82b805f959cfdd5b410b6396720ce6215a81a3

### CODE REVIEW

**Comment by LionCoin2021com123** [comment]
https://bscscan.com/tx/0xacac1465b4fa8005731dacc02a82b805f959cfdd5b410b6396720ce6215a81a3

**Comment by zhujiayu03** [comment]
Please refer to the tutorial and use the checksum contract address as the file name.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by daibilogo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
