### PR TITLE
Add ATOMBTC Logo And info

### PR DESCRIPTION
**Pull request by lytiesto**
https://bscscan.com/tx/0x019bbcbe2d6a483d4b62973b726cbd3493a5504766089fabb08fba4f88e40e4a

### CODE REVIEW

**Comment by lytiesto** [comment]
https://bscscan.com/tx/0x8598084f23e62fd099d4199191368ba3adb9a59320078555017526f54f68640f

**Comment by zhujiayu03** [comment]
Please check the ATOMBTC symbol again

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
