### PR TITLE
Add Fire

### PR DESCRIPTION
**Pull request by main1airdrop**

### CODE REVIEW

**Comment by main1airdrop** [comment]
https://bscscan.com/tx/0x4b162f27119e96b616645667088bba349f13cc9200abdc65fe8da7b930449c1d

https://bscscan.com/tx/0xd7d305e48dcf4decda907b93291110ccece6bb2647df448ed29a7fdb7a36e489

**Comment by main1airdrop** [comment]
@opera0001

**Comment by opera0001** [comment]
It has been detected that there is a setting for increasing token issuance in the token contract. In certain situations, this functionality can be risky.

**Comment by main1airdrop** [comment]
The contract's functionality is implemented such that token exchange can only be done through TTM. Please refer to https://bscscan.com/address/0xee9f8d288e8dd6cd29e59464f8ceb79d61cdcd8e for more information.

**Comment by main1airdrop** [comment]
image

**Comment by githu22b11231** [comment]
@opera0001

**Comment by main1airdrop** [comment]
@opera0001

**Pull request merged**
