### PR TITLE
Add BCN logo and info

### PR DESCRIPTION
**Pull request by bijanem**
BCN is the main token of the BEMEX exchange. This token is sold as an ICO.
In addition to being used in the Bemex exchange, this token is used in the payment gateway called (Bempay), in the game site called (bemgames) and in the ICO host project called (Bemchain) and many other projects.

https://www.bscscan.com/tx/0xcd2ce9f1df324f07cee6a7741cb924e6831fca976f476ec35b7308f37a6c8c0c

### CODE REVIEW

**Comment by sammvio** [comment]
Tron token logo upload is not allowed for now.

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
