### PR TITLE
ADD DISN LOGO INFO

### PR DESCRIPTION
**Pull request by Owen6663**
ADD DISN LOGO INFO

### CODE REVIEW

**Comment by Owen6663** [comment]
https://www.bscscan.com/tx/0xe3621367a40069f243a5e83ad8216f20aa3841ce9d6c1c2558cb4c94b8c0345a

**Comment by Owen6663** [comment]
https://www.bscscan.com/tx/0x938fddd1f3f4d6a97f172854d3174f0212a9b19db9749dd47e2208652502aa11

**Comment by Owen6663** [comment]
ADD DISN LOGO INFO
50000tpt https://www.bscscan.com/tx/0xe3621367a40069f243a5e83ad8216f20aa3841ce9d6c1c2558cb4c94b8c0345a
verify https://www.bscscan.com/tx/0x938fddd1f3f4d6a97f172854d3174f0212a9b19db9749dd47e2208652502aa11

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Pull request merged**
