### PR TITLE
Add LionCoin logo and info

### PR DESCRIPTION
**Pull request by loincoin00002155**
BSC-LionCoin-0x4dee35f1f0a2504117ab65d238823f6fa4f9b6b3-https://bscscan.com/tx/0x4dbf619617cc44e0ebb4c8a393bb136e7d1c6df7f0826b43cbc0df912f936d17

### CODE REVIEW

**Comment by loincoin00002155** [comment]
BSC-LionCoin-0x4dee35f1f0a2504117ab65d238823f6fa4f9b6b3-https://bscscan.com/tx/0x6a663e5cf1e15977c3da5378088339d88d5c93947d7de7ca98c7e6700030eb77

BSC-LionCoin-0x4dee35f1f0a2504117ab65d238823f6fa4f9b6b3-https://bscscan.com/tx/0x4dbf619617cc44e0ebb4c8a393bb136e7d1c6df7f0826b43cbc0df912f936d17

Lioncoin has paid TPT twice for this token. Please help me. Thank you

**Comment by loincoin00002155** [comment]
logo

**Comment by zhujiayu03** [comment]
Please refer to the tutorial and use the checksum contract address as the file name.

**Comment by loincoin00002155** [comment]
There is no error in using the contract address as the file name. Please handle it carefully

**Comment by loincoin00002155** [comment]
There is no error in using the contract address as the file name. Please handle it carefully

**Comment by loincoin00002155** [comment]
There is no error in using the contract address as the file name. Please handle it carefully

**Comment by loincoin00002155** [comment]
There is no error in using the contract address as the file name. Please handle it carefully

**Comment by loincoin00002155** [comment]
There is no error in using the contract address as the file name. Please handle it carefully

**Comment by loincoin00002155** [comment]
There is no error in using the contract address as the file name. Please handle it carefully

**Comment by loincoin00002155** [comment]
There is no error in using the contract address as the file name. Please handle it carefully

**Comment by loincoin00002155** [comment]
There is no error in using the contract address as the file name. Please handle it carefully

**Comment by loincoin00002155** [comment]
There is no error in using the contract address as the file name. Please handle it carefully

**Comment by loincoin00002155** [comment]
There is no error in using the contract address as the file name. Please handle it carefully

**Comment by loincoin00002155** [comment]
There is no error in using the contract address as the file name. Please handle it carefully

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
