### PR TITLE
Add LOVER logo and info 

### PR DESCRIPTION
**Pull request by jesaon**
#5369 https://bscscan.com/tx/0x2e2ff492cdd6cb0d692e15a16c508c346d2ac21dec6a217701ee41216c385369
Fist added to flow cell

### CODE REVIEW

**Comment by jesaon** [comment]
Submitted two, LOVER and ODIN

**Comment by opera0001** [comment]
0x0ae5Ce708D1CB1ae8EE3A6A8807340BC0e9b94cE
1. There may be a switch setting in the contract to close the transaction
2. The contract creator can blackmail the specified user
3. Wrong URL submitted
Please re submit the logo application after adjustment. Thank you for your support for tokenpocket.


0xe2578b3afcc78F87e2e07fFA5e402DC3629730D6
1. The liquidity of the capital pool is poor. If there are transactions through other non swap channels, there are certain risks.
2. Submission URL address error

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
