### PR TITLE
Add TNC logo and info

### PR DESCRIPTION
**Pull request by jgguo**
https://bscscan.com/tx/0x1825951b0314d2e6a950d13d87d8e229ff25e0553ea2a4a6dc8c9ebb937c759a

### CODE REVIEW

**Comment by guoxintongsam** [comment]
The official website cannot be opened, please resubmit.

**Comment by jgguo** [comment]
official website fixed

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
