### PR TITLE
create  0xae57fe379494B30Ec1E085Fb8a87d9C2FdcbcA2a logo again

### PR DESCRIPTION
**Pull request by goodgoodstudy8daydayup**
转账 50000TPT hash: https://bscscan.com/tx/0x283f8509819069773535915b000c98bfe8df9467bddba92788c539c437bbe5f1

验证hash: https://bscscan.com/tx/0x6589f471129186e80d02df32f9e15e844722b175205cb744cfe083a9c8f9043f

### CODE REVIEW

**Comment by opera0001** [comment]
It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

**Comment by phoenix33139** [comment]
合约已经开源

**Comment by goodgoodstudy8daydayup** [comment]
合约已经开源

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Pull request merged**
