### PR TITLE
add RST Token logo

### PR DESCRIPTION
**Pull request by lsf1227**

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3579750034

**Comment by sammvio** [comment]
Please donate 3000 TPT as required and submit the transfer link on [Commit changes].

**Comment by lsf1227** [comment]
https://bscscan.com/tx/0x85ca0191b98fca3dc1eff7df9da31c3eecb8a598bec3a6584dee5889f673f991

**Review by lsf1227 — COMMENTED** [review]
https://bscscan.com/tx/0x85ca0191b98fca3dc1eff7df9da31c3eecb8a598bec3a6584dee5889f673f991

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
