### PR TITLE
Add LoveDoge okexchain logo and info

### PR DESCRIPTION
**Pull request by lovedogeio**
https://bscscan.com/tx/0x3e043c1e6063c6c4d6515625415a9a4ee5a53ca2b313314110087349d5e24ee0

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token

**Comment by lovedogeio** [comment]
Hello, we have submitted the token information from https://www.tokenpocket.pro/zh/submit/token

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
