### PR TITLE
Add BBM logo and info

### PR DESCRIPTION
**Pull request by MengShengHua**
BBM defines a set of protocols for borrowers, guarantors, relayers, and investors to complete the cryptocurrency-based lending process (decentralization).
https://bscscan.com/tx/0x76e8b9c36db42b87232504d4078e9215fc0c0bebbe6f1d78fa668f2857c09ae0

### CODE REVIEW

**Comment by opera0001** [comment]
The token has been included, please do not submit it again.

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
