### PR TITLE
Add DNDB logo and info

### PR DESCRIPTION
**Pull request by 0XDaTang**
https://bscscan.com/tx/0x4f84b54b8ed027a070714a7e0a403e573885e3bbc2a3799868fceb71aa6050eb

https://bscscan.com/tx/0xd4bf19e82bae9683c28a7d9cd26a5507bc282d847557e434f0bb3febea1c50d0

### CODE REVIEW

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by opera0001** [comment]
0x4f857cFE2cd50C1a94eC88232EE0F5e3FD5Db1Ff--
The contract authority is not abandoned, and there may be control switch settings.

0x5324b1b8ffd63dae8ba2bd16796f339dc4df145c--
The submitted logo is not 256x256 pixels, please modify and resubmit.

**Comment by 0XDaTang** [comment]
现在就是这个像素的事对吗

**Comment by 0XDaTang** [comment]
是需要删了重新提交还是改掉再提交

**Review by 0XDaTang — COMMENTED** [review]
logo

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
