### PR TITLE
Add LickDog logo and info (Latest Version) 0xf6c29f93404f3f80a199ecae093b785bd073633a

### PR DESCRIPTION
**Pull request by Azjou**
Don't let your beloved girl treat you as a lick dog. Now you can buy LickDog coins in pancake and join the lickdog army!

### CODE REVIEW

**Comment by Azjou** [comment]
Please Note: Use e9e987d info.json and 1a31a89 logo.png! Because I upload the wrong file and I don't have authority to alter them!

**Comment by zhujiayu03** [comment]
Added

**Comment by Azjou** [comment]
> Added

you added the wrong logo for me!

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
