### PR TITLE
add ene and benz

### PR DESCRIPTION
**Pull request by zzz131519**
BSC-ENE-0x24B1FcF505e4c148fe44942A48c5d636009F8407-0xb57654f024e34e5ad60152519a047663d7dfdb82327949bab55fa6143970ab66

BSC-BENZ-0xAcFA30bB44BCEdDE6bF9b5cAC8BC2841e7ed1A82-0x4c6ef0b69bb46719201dff6e32afb3e19aad762f89ab97c637bdfb203428b9b0

### CODE REVIEW

**Comment by opera0001** [comment]
1. There may be some risks if the contract ownership is not abandoned.
2. There may be additional rights
Please re submit the logo after adjustment or optimization. Thank you for your support for tokenpocket.

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
