### PR TITLE
Add ZXS logo and info

### PR DESCRIPTION
**Pull request by SouphiW**

### CODE REVIEW

**Review by SouphiW — COMMENTED** [review]
TPT: https://bscscan.com/tx/0x296040ed647758582aa7e0fb552de77c3beb6625b2385e50ff4ce902e01ef46f
BNB:
https://bscscan.com/tx/0x9d3616e8ce5452c17ebfae2d84a56d3ac7629788e2d08295811aa4f8a0baf6e7

**Comment by SouphiW** [comment]
A long time ago, my GitHub account submitted a logo application, but that application failed. Now I want to apply for another logo. I hope this account can continue to be used. If not, please reply to me

**Comment by jjjgjk** [comment]
1212在吗

**Comment by jjjgjk** [comment]
你好

**Comment by tplogotijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request merged**
