### PR TITLE
已修改请尽快审核

### PR DESCRIPTION
**Pull request by ty3a**
已按要求重新修改。请审核。尽快显示图标

### CODE REVIEW

**Comment by ty3a** [comment]
https://bscscan.com/tx/0x2ee659d2380e625131baeebf549606379a7cf6f746470a22cea53c0309ea54d8

**Comment by guoxintongsam** [comment]
Tron token logo upload is not allowed for now.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
