### PR TITLE
Add FTP logo and info

### PR DESCRIPTION
**Pull request by ftprediction**
https://bscscan.com/tx/0x4fcf456c52b19cc749353fa92a9f698d9e0c24dbc4a38bab0a8488541f8af0a5

### CODE REVIEW

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by opera0001** [comment]
Do not submit with duplicate TPT hash values. #6050

**Comment by ftprediction** [comment]
https://github.com/TP-Lab/tokens/pull/6050
 My previous was closed. You allow me to upload again

This is my resubmission. Please let me pass

**Comment by opera0001** [comment]
done

**Comment by ftprediction** [comment]
https://github.com/TP-Lab/tokens/pull/6273 https://github.com/TP-Lab/tokens/pull/6050#issuecomment-1064862812   This is my resubmission. Please let me pass

**Comment by ftprediction** [comment]
I am really sorry to have bothered you a lot recently.I'm a novice. I'm too unprofessional. Please forgive me

**Pull request closed without merging**
