### PR TITLE
Add IONZ logo and info

### PR DESCRIPTION
**Pull request by kobe1234567890**
https://bscscan.com/tx/0xfb2caa8aa346fe8ff43f9411a40a67afba273f56b4920b07be503847a24f356b

### CODE REVIEW

**Comment by tiaojiaotubiaobaoguo** [comment]
代提交logo，24小时内包过，加QQ：2980874528

**Comment by sammvio** [comment]
The contract didn’t verify and publish. (No open-source)

**Comment by kobe1234567890** [comment]
> The contract didn’t verify and publish. (No open-source)

It's already open source, please review it again, tks

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
