### PR TITLE
Add JXRJ logo and info

### PR DESCRIPTION
**Pull request by laopowan**
https://bscscan.com/tx/0xf0a0d5e84d492c9379238f1c550234e49dc4e7f7be583d1863437569a06768cd?utm_source=tokenpocket

### CODE REVIEW

**Comment by opera0001** [comment]
1. Wrong URL submitted
2. Without increasing liquidity, what is the transaction mode?
3. The visual effect of the logo is poor and there is deformation. Please readjust it.

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
