### PR TITLE
Update FA logo

### PR DESCRIPTION
**Pull request by dao-fa-cash**
TPT transfer link: https://bscscan.com/tx/0xf5c4d5862be2bd7e6da16cfed83516db0c1952b6b2916916db758dcb8c50263f verify link: https://bscscan.com/tx/0xf4443e469928ba231e3dac641d76273a6fefcd17d18502c62798a5895498f440

FA Token Address: 0x5Ad04Ad0fDB383fe0e939690D8ce9fCbBE0E3CA8

Update FA logo, the previous log ratio is not correct.

Appreciate.

### CODE REVIEW

**Comment by opera0001** [comment]
Sorry, your hash value has already been #6372 used, so if you want to modify the logo or contract address, you need to submit a new hash value. Sorry, this problem is not caused by our collection work. I hope you understand.

**Comment by dao-fa-cash** [comment]
Do we need to donate 30,000 one more time, then submit the new transfer and verify hash, rignt?

**Comment by dao-fa-cash** [comment]
TPT transfer link: https://bscscan.com/tx/0x2f34b447da1cf343e46cd53763492758607e49fcb494be4a8d2be89a8fda23f5
verify link: https://bscscan.com/tx/0x3005b532ef091dee29ce28d88106096d7ea939eee45aab5ff66fd000c41847a1

FA Token Address: 0x5Ad04Ad0fDB383fe0e939690D8ce9fCbBE0E3CA8

We are trying to update the FA logo, the previous log ratio is not correct.
The new transfer and verify link is above, thanks for your work.

Appreciate.

**Comment by opera0001** [comment]
After receiving your reply, I will help you update the logo today.

**Comment by dao-fa-cash** [comment]
> After receiving your reply, I will help you update the logo today.

Thx, you can check the message links above.

**Comment by opera0001** [comment]
done

**Pull request closed without merging**
