### PR TITLE
add SKF info and logo

### PR DESCRIPTION
**Pull request by look888666**
https://bscscan.com/tx/0xe646a309c940c1c8074d0d4b84fb663a22e2ab89a3d9dc623f3f1897f252173c?utm_source=tokenpocket

### CODE REVIEW

**Comment by opera0001** [comment]
There may be some risks if the contract ownership is not abandoned.

Please re submit the logo after adjustment or optimization. Thank you for your support for tokenpocket.

**Comment by TPlogo** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
