### PR TITLE
Add DasBaby logo and Info

### PR DESCRIPTION
**Pull request by KevenNock**
TPT转账交易链接:https://bscscan.com/tx/0xdae3a6a416580d2330cdb7e06c5b31a8a167feb0db5ef9db45828b65b98245b5
验证交易链接:https://bscscan.com/tx/0x318235c10babeb47f10aa07c8052b4b56d159d44b0e381c54221158e5b512cc3

### CODE REVIEW

**Comment by opera0001** [comment]
It is detected that the transaction rate can be modified, please explain what it does.

**Comment by KevenNock** [comment]
Hi sir, it is used for auto  add LP  and community fund. buy and sell 3%, 1 % for add LP, 2% to community fund.
community fund is used for doing market activities.

**Comment by KevenNock** [comment]
Hi sir, it is used for auto  add LP  and community fund. buy and sell 3%, 1
% for add LP, 2% to community fund.
community fund is used for doing market activities.

**Comment by KevenNock** [comment]
in the future, we will cancel tax, and set it to zero. it depends on the project roadmap.

**Pull request merged**
