### PR TITLE
add test btcb logo and info

### PR DESCRIPTION
**Pull request by ninetalltrees**
https://bscscan.com/tx/0xcbfae499e3b9d36a7cb0d30435c01722f812e23a53de1bda7f81f9635d4fb875

### CODE REVIEW

**Comment by zhujiayu03** [comment]
logo infringement, please resend your image

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by ninetalltrees** [comment]
Can I change the name and logo at the same time?

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
