### PR TITLE
Add Uncp logo and info

### PR DESCRIPTION
**Pull request by fabianvogels**
BSC - Uncp - 0x41c68247eae9E29AA2be01E56A28C8864aa5AF09 - https://bscscan.com/tx/0x91daf6b1167524a5eac55f5b216351532cbedd48920ce276414b632be5a2e874

### CODE REVIEW

**Comment by opera0001** [comment]
The logo pixel of the token is not 256x256, please modify and resubmit.

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
