### PR TITLE
Add CNT logo and info

### PR DESCRIPTION
**Pull request by jefferywongo**
CNT will change the world.

### CODE REVIEW

**Comment by sammvio** [comment]
Please donate 3000 TPT as required and submit the transfer link on [Commit changes].

**Comment by jefferywongo** [comment]
Hello! 3000tpt has been donated to the relevant address. Please check the hash 0x9af913b26fa981e89291f76fb6e01cfd531807fef601bd53dad94d0a4081177e or https://bscscan.com/tx/0x9af913b26fa981e89291f76fb6e01cfd531807fef601bd53dad94d0a4081177e 
,The hash transferred with BNB is 0xe292ff7923dbc19694ea9f3af5ac9bffb9b878fbce156b73faeee14ab2f9a668, or https://bscscan.com/tx/0xe292ff7923dbc19694ea9f3af5ac9bffb9b878fbce156b73faeee14ab2f9a668 , please review the CNT token logo again, thank you! Looking forward to hearing from you~
| |
JefferyWong
|
|
***@***.***
|
签名由网易邮箱大师定制


On 01/19/2022 ***@***.***> wrote：

Closed #4943.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jefferywongo** [comment]
Please review the CNT token logo again，thanks.

**Comment by jefferywongo** [comment]
TPT hash ： https://bscscan.com/tx/0x9af913b26fa981e89291f76fb6e01cfd531807fef601bd53dad94d0a4081177e




| |
JefferyWong
|
|
***@***.***
|




On 01/19/2022 ***@***.***> wrote：

Closed #4943.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request closed without merging**
