### PR TITLE
Replace EGN

### PR DESCRIPTION
**Pull request by EGNtoken**
https://github.com/TP-Lab/tokens/pull/7633
https://github.com/TP-Lab/tokens/issues/7657
we submitted the contract address of the test token, our official version of the contract address should be 0x312104384dD59fab22506fE6A61736EE75d94C9E

### CODE REVIEW

**Comment by EGNtoken** [comment]
admin,Hope you have a nice day,

**Comment by opera0001** [comment]
Changing to a new contract address requires a new hash value, and the tokens of the new contract address cannot all be sold, how can this be known to all holders?

**Comment by EGNtoken** [comment]
> Changing to a new contract address requires a new hash value, and the tokens of the new contract address cannot all be sold, how can this be known to all holders?
Because of my work error, the contract address of the beta version was submitted for the first time, and the test contract address has no holder. I hope the admin can forgive my work error.

**Comment by EGNtoken** [comment]
> Changing to a new contract address requires a new hash value, and the tokens of the new contract address cannot all be sold, how can this be known to all holders?

Because of my work error, the contract address of the beta version was submitted for the first time, and the test contract address has no holder. I hope the admin can forgive my work error.

**Comment by EGNtoken** [comment]
The contract address submitted for the first time has not been used and the holder, because of my work mistakes, submitted an invalid contract, I hope the admin can sympathize with me

**Comment by opera0001** [comment]
Please check the path of the submitted json and logo.

**Comment by EGNtoken** [comment]
> Please check the path of the submitted json and logo.

The path is correct, my actions are 1. Delete the error (test contract) bsc/0xb6C723754f472582Ab662f5E581F039FF7F0fB0e directory
2. Add the normal contract address bsc/0x312104384dD59fab22506fE6A61736EE75d94C9E/

**Comment by opera0001** [comment]
image
This submission is clearly wrong, changing either the contract address or logo requires a new payment, a problem we did not cause, and it takes longer to go from tokens through review.

**Comment by opera0001** [comment]
Please let me know here after you modify it: https://github.com/TP-Lab/tokens/issues

**Pull request closed without merging**
