### PR TITLE
Add BABYCORGI logo and info 

### PR DESCRIPTION
**Pull request by daryl12345**
https://bscscan.com/tx/0xe49e3db8097c064d894e0467ca82dd819f09925be97d98ad7db63b547600c1d8

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token

**Comment by daryl12345** [comment]
Sorry, I submitted to the wrong chain. I have succeeded submit to my token.Please check it!

**Comment by daryl12345** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    hello:
        Sorry, I submitted to the wrong chain. I have succeeded submit to my token.Please check it!        
    
     
    
        
                    ***@***.***
        
    
    
        签名由网易邮箱大师定制
    
 

    On 9/10/2021 ***@***.***> wrote： 



Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
