### PR TITLE
Add DAPF logo and info

### PR DESCRIPTION
**Pull request by yaxray**
BSC - DAPF - 0x9c67ee6d0f3f12969abc92595b06cc1c93a60313 - https://bscscan.com/tx/0xd39aa0d1e401042993cbd024e200382eebc035c1dd4578ec0be72358b789f1e6

### CODE REVIEW

**Comment by guoxintongsam** [comment]
Please submit the checksum address that includes uppercase and lowercase characters.

**Comment by yaxray** [comment]
> Please submit the checksum address that includes uppercase and lowercase characters.

0x0168aE5F322431B0dFA5e898b1BEa9c029F43230

**Comment by yaxray** [comment]
New pull request https://github.com/TP-Lab/tokens/pull/3263

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
