### PR TITLE
Add TPT logo and info

### PR DESCRIPTION
**Pull request by orexzon**
sample

### CODE REVIEW

**Comment by orexzon** [comment]
https://hecoinfo.com/token/0x3DD95A6fc933d41493263DF988798F2b488659d3

**Comment by orexzon** [comment]
3000TPT tranfer
0x72a4Cfbd21BF175ca61B149ff1566855D56b102E


https://hecoinfo.com/token/0x3DD95A6fc933d41493263DF988798F2b488659d3

**Comment by orexzon** [comment]
SWAN22 logo and info not updated in TokenPocket.,please help !

3000TPT tranfer
0x72a4Cfbd21BF175ca61B149ff1566855D56b102E

https://hecoinfo.com/token/0x3DD95A6fc933d41493263DF988798F2b488659d3

**Comment by orexzon** [comment]
SWAN22 logo and info not updated in TokenPocket.,please help !
we are transfer TPT-3000 from 0x72a4Cfbd21BF175ca61B149ff1566855D56b102E

HECO-TPT-0x3DD95A6fc933d41493263DF988798F2b488659d3-https://hecoinfo.com/token/0x3DD95A6fc933d41493263DF988798F2b488659d3

**Comment by tubiaoyingji** [comment]
专业加快提交LOGO，20分钟内审核包过，QQ：1450001284

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Pull request closed without merging**
