### PR TITLE
Add FTN logo and info

### PR DESCRIPTION
**Pull request by Tonyhu1314**
{
 "name": "Fraternity Coin",
 "website": "https://ftndex.com/",
 "description": "Highly decentralized and charity DeFi platform.",
 "explorer": "https://bscscan.com/token/0x226039D64Cd91E06bdAcf67022b0369d47C2ba7A",
 "type": "BEP20",
 "symbol": "FTN",
 "decimals": 8,
 "status": "active",
 "id": "0x226039D64Cd91E06bdAcf67022b0369d47C2ba7A"
}

BSC - FTN - 0x226039D64Cd91E06bdAcf67022b0369d47C2ba7A - https://bscscan.com/tx/0x9a5ec4cd82c330b5784b7bf669530381ad5b0be682b3b8b0d1ed0f897c518791

### CODE REVIEW

**Comment by guoxintongsam** [comment]
The contract didn’t verify and publish.

**Comment by Tonyhu1314** [comment]
Hello, this contract has already been verified, please confirm and check. In case you need us to make a new pull request, please refer to this @sammvio 

> The contract didn’t verify and publish.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
