### PR TITLE
Add ANGEL Logo and Info

### PR DESCRIPTION
**Pull request by angelgopro**
Payment: https://bscscan.com/tx/0xe68c46e2a96db95e061934aaf0eb26e08fe4947e4f616212db2b8d8a0a0ce8a6
Info: https://bscscan.com/tx/0xce92982cffd51141de6f87cf90c2887921605b1856d7d369e6a066c88aa71508

### CODE REVIEW

**Comment by opera0001** [comment]
Detected transaction rate can be modified, please explain its function, thank you.

**Comment by angelgopro** [comment]
> 检测交易率可以修改，请说明其作用，谢谢。

因为项目方销毁计划会调整费率
机制

**Comment by angelgopro** [comment]
> 检测交易率可以修改，请说明其作用，谢谢。
除了黑洞外，流通总量剩余达到多少就会调整税率。

**Comment by angelgopro** [comment]
angel

**Comment by angelgopro** [comment]
In addition to the black hole, the tax rate is adjusted for the amount of total circulation remaining to be reached.

**Comment by angelgopro** [comment]
> 检测交易率可以修改，请说明其作用，谢谢。

Progressive reduction in tax rates, eventually to 0 tax.

**Comment by angelgopro** [comment]
Please review by admin, it's been 3 days since it was submitted.

**Pull request merged**
