### PR TITLE
ADD TPT logo and info

### PR DESCRIPTION
**Pull request by lcpliu**

### CODE REVIEW

**Comment by opera0001** [comment]
Dear, you submitted two contract addresses in one order, and the first contract address cannot be included, while the second one has been approved. Do you need to use the second one for the token logo inclusion?

**Comment by lcpliu** [comment]
Now I need the newly submitted TPT project, not the previous one.

**Comment by lcpliu** [comment]
> Dear, you submitted two contract addresses in one order, and the first contract address cannot be included, while the second one has been approved. Do you need to use the second one for the token logo inclusion?

Now I need the newly submitted TPT project, not the previous one.

**Comment by opera0001** [comment]
I'm sorry, the TPT token cannot be listed. You might consider listing another token.

**Comment by lcwypn** [comment]
> [@lcpliu ](/lcpliu)
> ` [ADD MAIH ](/TP-Lab/tokens/pull/10841/commits/0c42eb0be2cf6c27f86e3de662a7bbacaf4e7e1f)`

Please delete the MAIH project file and keep the TPT project. I only need to submit the TPT project

**Comment by lcwypn** [comment]
Please delete the MAIH project file and keep the TPT project. I only need to submit the TPT project

**Comment by lcpliu** [comment]
> I'm sorry, the TPT token cannot be listed. You might consider listing another token.

Please delete the MAIH project file and keep the TPT project. I only need to submit the TPT project

**Comment by lcpliu** [comment]
Please delete the MAIH project file and keep the TPT project. I only need to submit the TPT project

**Comment by opera0001** [comment]
TPT cannot be listed, I'm sorry. The donation hash value you submitted can be reused in future submissions.

**Comment by opera0001** [comment]
The TPT hash value you submitted will not expire; you can continue to use it for your next submission. Alternatively, if you change your mind and want to submit a different logo, please let me know through the issues.

**Pull request closed without merging**
