### PR TITLE
Add SafeMoon logo and info

### PR DESCRIPTION
**Pull request by zhao199579**
https://bscscan.com/tx/0x50875fb3f6e43c8809413e5d05ca863aef5c1a7f8b646ce1d15e9edadb3101dd

### CODE REVIEW

**Comment by zhao199579** [comment]
It has been communicated that this token is not misleading.

**Comment by opera0001** [comment]
A GitHub account can only submit one logo application at a time

**Comment by zhao199579** [comment]
> A GitHub account can only submit one logo application at a time

I only submitted one! The initial submission failed, but it can be submitted after communication, without misleading.

**Comment by zhao199579** [comment]
> A GitHub account can only submit one logo application at a time

I only submitted this one, because you failed to approve it. After communication, this token is not misleading

**Comment by zhao199579** [comment]
> A GitHub account can only submit one logo application at a time

I only submit this one. The other is an upload error. I have cancelled the request in time

**Comment by zhao199579** [comment]
确定

**Comment by jjjgjk** [comment]
1212在吗

**Comment by jjjgjk** [comment]
1212在吗

**Pull request closed without merging**
