### PR TITLE
Add FMC logo and info

### PR DESCRIPTION
**Pull request by lqxue**
BNB - https://bscscan.com/tx/0x81e7f3981f82f1097cfca68b49ca87e4a75d6052f43045f7310a1ba0e6604a7b TPT - https://bscscan.com/tx/0xb9b8df7915668ba4a6594e589fcd42c92031bdb9be36e69a080c9dd71cacfd7a

### CODE REVIEW

**Comment by opera0001** [comment]
It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

**Comment by lqxue** [comment]
The code has already been open-sourced.

https://bscscan.com/address/0x359158B4354Cd245C6958E98Ab3395D6266751e1#code

**Comment by opera0001** [comment]
Detected exist tokens, increase the function of the distribution, what is its function?

**Comment by wufannet** [comment]
> Detected exist tokens, increase the function of the distribution, what is its function?
which function ?

**Comment by wufannet** [comment]
> 

mint ?

**Comment by wufannet** [comment]
There is a method for Mint to increase circulation, which is the standard method of the erc20 protocol.

**Pull request merged**
