### PR TITLE
Add XPS logo and info

### PR DESCRIPTION
**Pull request by AuraSuper**
https://bscscan.com/tx/0x6073ce7b580a1f953eaf6c722cd367a750ae076f3c404c569932df28ad91e43c

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3579750034

**Comment by sammvio** [comment]
Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token

**Comment by AuraSuper** [comment]
> Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
