### PR TITLE
Add UPDT logo and info

### PR DESCRIPTION
**Pull request by UniallPay**
Sample

### CODE REVIEW

**Comment by opera0001** [comment]
Please provide the hash value link for TPT.

**Comment by UniallPay** [comment]
合并

**Comment by UniallPay** [comment]
0x407a4779fb61e6a36212e3bf0760f9172134c026e4f6fa27d461a10804f9b731

**Comment by UniallPay** [comment]
https://bscscan.com/tx/0x407a4779fb61e6a36212e3bf0760f9172134c026e4f6fa27d461a10804f9b731

**Comment by UniallPay** [comment]
ok钱包，没有那个高级纯文本证明，咋办



发自我的iPhone


------------------ Original ------------------
From: opera0001 ***@***.***&gt;
Date: Sat,Nov 25,2023 10:12 PM
To: TP-Lab/tokens ***@***.***&gt;
Cc: updt ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [TP-Lab/tokens] Add UPDT logo and info (PR #10057)





 
Please provide the hash value link for TPT.

**Comment by UniallPay** [comment]
感谢🙏，我还有很多代币需要提交、目前这个还没有显示，请领导审核



发自我的iPhone


------------------ Original ------------------
From: opera0001 ***@***.***&gt;
Date: Sun,Nov 26,2023 7:47 PM
To: TP-Lab/tokens ***@***.***&gt;
Cc: updt ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [TP-Lab/tokens] Add UPDT logo and info (PR #10057)





 
Merged #10057 into master.

**Comment by UniallPay** [comment]
你好，帮忙看看可以吗，好几天了





发自我的iPhone


------------------ Original ------------------
From: opera0001 ***@***.***&gt;
Date: Sun,Nov 26,2023 7:47 PM
To: TP-Lab/tokens ***@***.***&gt;
Cc: updt ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [TP-Lab/tokens] Add UPDT logo and info (PR #10057)





 
Merged #10057 into master.

**Comment by UniallPay** [comment]
你好，能帮忙看看吗
因为我还有个代币需要提交
只有这个提交成了，才能进行下一个，





发自我的iPhone


------------------ Original ------------------
From: opera0001 ***@***.***&gt;
Date: Sun,Nov 26,2023 7:47 PM
To: TP-Lab/tokens ***@***.***&gt;
Cc: updt ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [TP-Lab/tokens] Add UPDT logo and info (PR #10057)





 
Merged #10057 into master.

**Comment by UniallPay** [comment]
你好，需要再次提交吗？？
如果不用大概多久更新显示。



发自我的iPhone


------------------ Original ------------------
From: opera0001 ***@***.***&gt;
Date: Sun,Nov 26,2023 7:47 PM
To: TP-Lab/tokens ***@***.***&gt;
Cc: updt ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [TP-Lab/tokens] Add UPDT logo and info (PR #10057)





 
Merged #10057 into master.

**Comment by UniallPay** [comment]
> Please provide the hash value link for TPT.

https://bscscan.com/tx/0x407a4779fb61e6a36212e3bf0760f9172134c026e4f6fa27d461a10804f9b731

**Comment by UniallPay** [comment]
能帮我看看吗，大佬，还是没有显示啊





发自我的iPhone


------------------ Original ------------------
From: opera0001 ***@***.***&gt;
Date: Sun,Nov 26,2023 7:47 PM
To: TP-Lab/tokens ***@***.***&gt;
Cc: updt ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [TP-Lab/tokens] Add UPDT logo and info (PR #10057)





 
Merged #10057 into master.

**Comment by UniallPay** [comment]
你好，能帮忙看看吗



发自我的iPhone


------------------ Original ------------------
From: opera0001 ***@***.***&gt;
Date: Sun,Nov 26,2023 7:47 PM
To: TP-Lab/tokens ***@***.***&gt;
Cc: updt ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [TP-Lab/tokens] Add UPDT logo and info (PR #10057)





 
Merged #10057 into master.

**Pull request merged**
