### PR TITLE
Add RPC & USDA info and logo

### PR DESCRIPTION
**Pull request by lonely1215225**
50,000 TPT 的交易ID链接
https://bscscan.com/tx/0xddbc78d0e9ad2da95ada59e8444b28b22b17937d45454e862c5ce24af57f7e8d 0bnb
https://bscscan.com/tx/0x8e0c89ae10fa853e3c41910d3537dc4ea6169663c9ce933ab943eac3b27bd2fd

### CODE REVIEW

**Comment by lonely1215225** [comment]
Add USDA info and logo
50,000 TPT 的交易ID链接
https://bscscan.com/tx/0x0679bf05aa9fa5824346bae4b85bdb771232e4ccdd2b3af3fcb47cbd00ec78a7
0BNB
https://bscscan.com/tx/0xe095d4c7568d2454e47e68b454575a95d873e62319ea1402ebdbb02e3d62208c

**Review by Gemk83 — APPROVED** [review]

**Comment by mcdaolive** [comment]
> The circulating transaction fees for the token at 0x62238038AbeAe5A667cDe8769E708c5a07d7ADdB seem to be high and include some additional permissions. Please provide an explanation for this.

Sorry, this is not our contract address

**Comment by mcdaolive** [comment]
> The circulating transaction fees for the token at 0x62238038AbeAe5A667cDe8769E708c5a07d7ADdB seem to be high and include some additional permissions. Please provide an explanation for this.

this hash value did not appear during my operation.

**Comment by lonely1215225** [comment]
> The circulating transaction fees for the token at 0x62238038AbeAe5A667cDe8769E708c5a07d7ADdB seem to be high and include some additional permissions. Please provide an explanation for this.

image
this is not our tokens

**Comment by opera0001** [comment]
image

**Comment by opera0001** [comment]
The next submission requires one GitHub order per transaction. This submission is approved.

**Comment by lonely1215225** [comment]
> The next submission requires one GitHub order per transaction. This submission is approved.

got it！

**Pull request merged**
