### PR TITLE
Add DOD and info

### PR DESCRIPTION
**Pull request by DOD195450508**
Add DOD and info
paid TPT

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3579750034

**Comment by sammvio** [comment]
Please re-submit the TPT transfer link on [Commit changes].

**Comment by DOD195450508** [comment]
> Please re-submit the TPT transfer link on [Commit changes].

https://bscscan.com/tx/0x2908603568df53f6556055aca6cf2e8d79f436c574bc2220987451e5f35b2c27
https://bscscan.com/tx/0x243ed9f89326a9e76e1cdfac9305a56dab65c85b6d5392191a6deda63c84a05c

**Review by DOD195450508 — COMMENTED** [review]
Add DOD and info

https://bscscan.com/tx/0x2908603568df53f6556055aca6cf2e8d79f436c574bc2220987451e5f35b2c27
https://bscscan.com/tx/0x243ed9f89326a9e76e1cdfac9305a56dab65c85b6d5392191a6deda63c84a05c

**Review by DOD195450508 — COMMENTED** [review]
Add DOD and info

https://bscscan.com/tx/0x2908603568df53f6556055aca6cf2e8d79f436c574bc2220987451e5f35b2c27
https://bscscan.com/tx/0x243ed9f89326a9e76e1cdfac9305a56dab65c85b6d5392191a6deda63c84a05c

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request merged**
