### PR TITLE
BSC - Myth - 0xC9ddF5554AFcCD8e58d625e6a4084D7da74e16f5 - https://bscscan.com/token/0xc9ddf5554afccd8e58d625e6a4084d7da74e16f5

### PR DESCRIPTION
**Pull request by v587111**
0x7c937315ca341465a0a643e4a677eb705753a38df1000bc9d87925ceb8b8c54f

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3579750034

**Comment by v587111** [comment]
TPT Transaction Details ： 
https://bscscan.com/tx/0x7c937315ca341465a0a643e4a677eb705753a38df1000bc9d87925ceb8b8c54f

**Comment by sammvio** [comment]
Please re-submit your files to bsc folder

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
