### PR TITLE
Add BNBTiger Logo and Info

### PR DESCRIPTION
**Pull request by PinkPinkSnoop**
https://bscscan.com/tx/0xf4a507cc9c2998a5b7cc3cf08cd279a5810e30d7531ace4b7b8a5939f3d1010c

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3076439606

**Comment by sammvio** [comment]
Please submit the project website.

**Comment by PinkPinkSnoop** [comment]
Updated, please help.
Thank you!

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
