### PR TITLE
Add MTA JUB & sJUB info and Logo

### PR DESCRIPTION
**Pull request by NinoShima**
MTA 3000TPT: https://bscscan.com/tx/0xdff9ceb4c3974913d176549b7e532d2c5fa259ba71ce089168b477176862a7e6
BSC: https://bscscan.com/tx/0x4191e093844e1fce37581faf06200d2f7ef55315e08e984ceec0647e198c828b

JUB 300TPT: https://bscscan.com/tx/0x0dd6aaf86cb7e906c3d82115a01c5178990bed9ad528824795ae08b2f0e75ad0
BSC: https://bscscan.com/tx/0x03ed79918b9aaeeacc0251eeed580995ffe613ffd739ac271453eae720b44b48

sJUB 300TPT: https://bscscan.com/tx/0x8f72ce47a63f52307eb69149a71ccab55f7c091b12a0e1662e2ffd80dfe9e8f3
BSC: https://bscscan.com/tx/0x91927fc2f2cb4575862cf74db560779157c74a399829751f21ce8b43d37023a6

### CODE REVIEW

**Comment by tubiaoyingji** [comment]
专业加快提交LOGO，20分钟内审核包过，QQ：1450001284

**Comment by sammvio** [comment]
Please submit the checksum address that includes uppercase and lowercase characters.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
