### PR TITLE
Add nine logo and info

### PR DESCRIPTION
**Pull request by ouyuan1992**
sample

### CODE REVIEW

**Comment by ouyuan1992** [comment]
Add NGBZ logo and info

**Comment by zhujiayu03** [comment]
请附带TPT转账记录。

**Review by ouyuan1992 — COMMENTED** [review]
https://bscscan.com/tx/0x3b0a1923f158b94a53ff9be2d58833dab71706651606ced22e31a6b4091c4c4f

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Pull request closed without merging**
