### PR TITLE
Add PEPESport logo and info.

### PR DESCRIPTION
**Pull request by PEPESport**
Transaction link for 50,000 TPT:
https://bscscan.com/tx/0x1b8caa4117ef27e902b530e2a8767a0811cf164167956da30fc20855004fdec6

Verification link:
https://bscscan.com/tx/0x9a513981ac1e2ebc63248177e3e8dcb091738896c00665d6de4e2bb9ef9269c8

### CODE REVIEW

**Comment by PEPESport** [comment]
Team statement: PEPESport tokens will continue to be marketed and promoted to let more and more people know about PEPESport tokens.

**Comment by PEPESport** [comment]
The team gave up the ownership of the contract at the first time, and there is no hidden authority：
the hash check link: 
https://bscscan.com/tx/0x9ec8f5a3787607bcf362777e58c6af28d4dbd447617ec733605cb419056ee425

**Comment by PEPESport** [comment]
image

Please check, this is the developer wallet address. 0xC82405cA3e98433A071157826185c4D9FeBC8781   。At the same time, we also transfer liquidity to burn addresses.     

We are contracts that replicate other tokens. Didn't know there would be this detection issue. But it can be guaranteed that the current contract is safe. Because we relinquish ownership.      Please allow it, thank you very much.

**Comment by PEPESport** [comment]
> Detected hidden owner permissions in the token contract, which is a dangerous configuration unless you have a complete and reliable security certification from a security auditing organization. Without it, I believe it would be difficult for this token to be listed. The submitted TPT hash value link can be used for future logo order submissions. Unfortunately, I will give you one or two days, and if there is no reasonable explanation, the order will be closed.

Then please close this order. I resubmit with another token. Thanks

**Comment by PEPESport** [comment]
> Detected hidden owner permissions in the token contract, which is a dangerous configuration unless you have a complete and reliable security certification from a security auditing organization. Without it, I believe it would be difficult for this token to be listed. The submitted TPT hash value link can be used for future logo order submissions. Unfortunately, I will give you one or two days, and if there is no reasonable explanation, the order will be closed.

Please help with new orders. Many thanks 
Link：
https://github.com/TP-Lab/tokens/pull/9414

**Comment by opera0001** [comment]
Alright, I will go review them.

**Pull request closed without merging**
