### PR TITLE
Add AIR logo and info

### PR DESCRIPTION
**Pull request by Airstalker007**
Name：AIR
Type：BEP20
Symbol：AIR
Quantity：10000000000000000
Address：0xd8a2aE43Fd061d24acd538e3866Ffc2c05151b53
Website：https://aircoin.cool
Description：AIR is to mock the madness of the cryptocurrency market. AIR is everywhere, after buying AirCoin you get nothing but AIR
https://bscscan.com/tx/0xbda92fc04ef67c1777e054d693371263d6073ba1792eb9cf3ec83a78202f04b9

### CODE REVIEW

**Comment by tiaojiaotubiaobaoguo** [comment]
代提交logo，24小时内包过，加QQ：2980874528

**Comment by sammvio** [comment]
Please submit the logo.

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
