### PR TITLE
Add BTCking logo and info

### PR DESCRIPTION
**Pull request by binnerKing**
https://bscscan.com/tx/0x6e9520bc7d00e57cba02a67b0b4525581d03d0e878c1edc9fc673647f2b4e1ad

### CODE REVIEW

**Comment by opera0001** [comment]
1. The URL link submitted is not a regular link
2. There may be a blacklist mechanism to restrict normal transactions
3. There may be a switch setting that prohibits trading

**Comment by binnerKing** [comment]
Permission has been given up. Permission has been given up

**Comment by logobaoguo12** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TPtubiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
