### PR TITLE
Add SpacePi logo and info

### PR DESCRIPTION
**Pull request by caoliutoken**
HECO-SpacePi-0x4bEd97ff445C1dFD7B2C60aAeDE15dF0f1c25eD3-https://hecoinfo.com/tx/0xf382474708d35408d5672994170779e573d77389aeebea2b3ad52c44e6738c19

### CODE REVIEW

**Comment by jiasutijiao** [comment]
专业提交logo！加速审核2小时内包过！QQ:3579750034

**Comment by sammvio** [comment]
Please re-submit your files to heco folder

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034

**Comment by touxiangtijiao** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
