### PR TITLE
update logo and info

### PR DESCRIPTION
**Pull request by oko-token**
1000TPT transfer link: https://bscscan.com/tx/0x021d56d5c6d57ceffb83f67e09b2d9dbb7f1072075c939fb2444d10783be24e6

### CODE REVIEW

**Comment by oko-token** [comment]
The last submitted has not been merged, don't know what happened 
https://github.com/TP-Lab/tokens/pull/2691

**Comment by guoxintongsam** [comment]
Please refer to the tutorial and use the checksum contract address. The checksum contract address would contain upper and lower case letters.

**Comment by oko-token** [comment]
> 请参考教程并使用校验和合约地址。校验和合约地址将包含大写和小写字母。

Can you reopen this request? I'll update the file. Thank you very much. This action has been delayed for a long time. Thank you very much

**Comment by oko-token** [comment]
> > 请参考教程并使用证书和地址合约地址。和合约将包含大写和小写字母。
> 
> 你能重新打开这个请求吗？我会更新文件。非常感谢。这个动作已经推迟了很长时间。非常感谢



> > 请参考教程并使用证书和地址合约地址。和合约将包含大写和小写字母。
> 
> 你能重新打开这个请求吗？我会更新文件。非常感谢。这个动作已经推迟了很长时间。非常感谢

I see you merged this request into master， But I saw that the logo of the wallet was not updated、Is there any delay after the merger, or what do you need me to do? Thank you very much

**Comment by oko-token** [comment]
> 请参考教程并使用校验和合约地址。校验和合约地址将包含大写和小写字母。

I see you merged this request into master， But I saw that the logo of the wallet was not updated、Is there any delay after the merger, or what do you need me to do? Thank you very much

**Comment by oko-token** [comment]
> 请参考教程并使用校验和合约地址。校验和合约地址将包含大写和小写字母。




> Please refer to the tutorial and use the checksum contract address. The checksum contract address would contain upper and lower case letters.



> Please refer to the tutorial and use the checksum contract address. The checksum contract address would contain upper and lower case letters.

Hello dear audit,  I see you merged this request into master， But I saw that the logo of the wallet was not updated
This is to modify the action:  https://github.com/TP-Lab/tokens/pull/2844/commits/aaaf8dd777339d185c9bc71b9de9dd1dd3ba3f37
Is there any delay after the merger, or what do you need me to do? Thank you very much ， Looking forward to your reply .

**Pull request merged**
