### PR TITLE
Add AGC logo and info

### PR DESCRIPTION
**Pull request by agctoken**
https://bscscan.com/tx/0x98549f2dd85b45846739d3d5d935b96e9d8b6502ad998d214a4faf9d444a91d5 https://bscscan.com/tx/0xf8a43da2595e46c2873176ce2933cc9346e17a52abbaca3aedd1289448ad164a

### CODE REVIEW

**Comment by agctoken** [comment]
订单收到了吗？

**Comment by opera0001** [comment]
The order has been received. However, the token contract you submitted is not open source. We need you to open source it before we can proceed with the inspection of the token contract and provide the final outcome.

**Comment by agctoken** [comment]
好的

**Comment by agctoken** [comment]
代币合约开源以后我需要再次提交吗？是在这儿联系你吗？

**Comment by opera0001** [comment]
> 代币合约开源以后我需要再次提交吗？是在这儿联系你吗？

Please notify me once you've completed the open-source work. You don't need to resubmit; I will review it again upon receiving your response. If it's deemed safe, please patiently wait for about a day to complete the token logo inclusion.

**Comment by agctoken** [comment]
> > 代币合约开源以后我需要再次提交吗？是在这儿联系你吗？
> 
> Please notify me once you've completed the open-source work. You don't need to resubmit; I will review it again upon receiving your response. If it's deemed safe, please patiently wait for about a day to complete the token logo inclusion.

太感谢了，辛苦了。

**Comment by opera0001** [comment]
So far, there has been no information about the token contract being open-sourced

**Comment by agctoken** [comment]
我这边完成开源工作以后通知你。

**Comment by agctoken** [comment]
完成开源工作以后通知你。

**Comment by agctoken** [comment]
代币合约已经开源，请审查。

**Comment by agctoken** [comment]
> > 代币签约开源以后我需要再次提交吗？是在这儿联系你吗？
> 
> 完成开源工作后请通知我。您无需重新提交；收到您的回复后我会再次审核。如果认为安全，请耐心等待大约一天以完成令牌徽标包含。

代币合约已经开源，请审查。

**Comment by opera0001** [comment]
The transaction fee rate for the detected token can be modified, and there are both blacklist and whitelist functions in place. The contract's control permissions have not been relinquished, so please clarify the issue mentioned above.

**Comment by opera0001** [comment]
Furthermore, it has been detected that there is a hidden owner function within the token contract, which could be very dangerous.

**Comment by agctoken** [comment]
因为我们现在是全新的铸币模式，目前没有开放二级市场交易，生态还在持续建设中，前期只是早期布道者参与生态测试，后期会放弃权限。

**Comment by agctoken** [comment]
你这边可以再去检查一下合约代码，现在只是没有放弃所有权，并没有隐藏的所有者。

**Comment by agctoken** [comment]
> 所有者的隐藏和放弃所有权的决定没有直接关系。即使由于隐藏所有者的存在而放弃所有权，仍然存在重大风险。因此，很抱歉，我们无法为您添加徽标。您提交的TPT哈希值可以在以后的提交中继续使用。

请检查一下代码，没有隐藏的所有者。

**Pull request closed without merging**
