### PR TITLE
PANTHER logo and info

### PR DESCRIPTION
**Pull request by PANTHERTOKEN**
https://bscscan.com/tx/0xb53dcad54b37960337b6cfb1cfb5510a12a3366128a89801ae693fb7cc8e5af7

### CODE REVIEW

**Comment by PANTHERTOKEN** [comment]
https://bscscan.com/tx/0xb53dcad54b37960337b6cfb1cfb5510a12a3366128a89801ae693fb7cc8e5af7

**Comment by zhujiayu03** [comment]
Please re-submit your files to bsc folder

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by 542132364** [comment]
代提交logo，提交失败和加急提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
