### PR TITLE
add WNFT logo and info

### PR DESCRIPTION
**Pull request by lgkj123**
https://bscscan.com/tx/0x5ce7280aa69367921682b11e8c0eedf687c69f84d4b0e8acef26906263f63d81

### CODE REVIEW

**Comment by zhujiayu03** [comment]
Unlisted token, please submit your token first, https://www.tokenpocket.pro/zh/submit/token

**Comment by lgkj123** [comment]
ok, already submit

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
