### PR TITLE
Add BabyDogeV3 logo and info

### PR DESCRIPTION
**Pull request by nggngmgmgd**
https://bscscan.com/tx/0x406892d20a2dcff4905afdf20429ec772a83595fc29d8af34b42018d14a41b59
Hash Function：0x406892d20a2dcff4905afdf20429ec772a83595fc29d8af34b42018d14a41b59
BabyDogeV3 logo has been added. 1000TPT has been paid, please check

### CODE REVIEW

**Review by nggngmgmgd — COMMENTED** [review]
logo

**Comment by nggngmgmgd** [comment]
The picture above is the logo. I don't know why I can't the last logo file. I can only tell you through comments.

**Comment by nggngmgmgd** [comment]
This is the address I gave BNB ：0x9128806DD40558C5CBd822446A9451A8584c8482

**Comment by zhujiayu03** [comment]
Please refer to the tutorial, and re-submit your files in the correct format

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Pull request closed without merging**
