### PR TITLE
Add FB logo and info

### PR DESCRIPTION
**Pull request by lixingceng**
一种未来的趋势，世界的玩法

### CODE REVIEW

**Comment by lixingceng** [comment]
https://hecoinfo.com/tx/0xe582182b3d2c063ddc939183d7b7738deefd2be32ef3a0341b8fd7e8d7db185f

**Comment by zhujiayu03** [comment]
Tron token logo upload is not allowed for now.

**Comment by lixingceng** [comment]
那这怎么处理？那什么时候可以上传？还有就是下次上传还有继续付款吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TP-Lab/tokens"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月17日(星期二) 晚上9:18
***@***.***&gt;;
抄送:&nbsp;"获 奖 通 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [TP-Lab/tokens] Add FB logo and info (#2527)





 
Tron token logo upload is not allowed for now.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lixingceng** [comment]
那还有通过别的方式上传


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TP-Lab/tokens"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月17日(星期二) 晚上9:18
***@***.***&gt;;
抄送:&nbsp;"获 奖 通 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [TP-Lab/tokens] Add FB logo and info (#2527)





 
Tron token logo upload is not allowed for now.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lixingceng** [comment]
你好！这还可以通过别的方式上传吗？还是说要等这问题解决才能上传？下次上传是否需要支付，以前支付的怎么办？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TP-Lab/tokens"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月17日(星期二) 晚上9:18
***@***.***&gt;;
抄送:&nbsp;"获 奖 通 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [TP-Lab/tokens] Add FB logo and info (#2527)





 
Tron token logo upload is not allowed for now.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lixingceng** [comment]
什么时候可以恢复下？

**Comment by jiasutijiao** [comment]
专业提交logo！审核失败的走加速审核2小时内包过！价格显示问题！QQ:3076439606

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Comment by TpLoGotijiaobaoguo** [comment]
快速提交tp头像2小时内包过，需要联系QQ：2651964563

**Pull request closed without merging**
