### PR TITLE
Add YZF logo and info 

### PR DESCRIPTION
**Pull request by ztczsyb34**
https://bscscan.com/tx/0x4fc0fce967e8ad980e2f37c5786381d1983610066a832ca41b55c7b2f4611f9f

### CODE REVIEW

**Comment by opera0001** [comment]
It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

**Comment by opera0001** [comment]
A GitHub account can only submit one logo application at a time.

**Comment by ztczsyb34** [comment]
第一次（合约地址是错误），第二次才是正确的。请帮忙处理，谢谢！



---Original---
From: ***@***.***&gt;
Date: Sat, Apr 16, 2022 11:08 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TP-Lab/tokens] Add YZF logo and info  (PR #6725)




 
A GitHub account can only submit one logo application at a time.

**Comment by ztczsyb34** [comment]
把错误的删除了，麻烦再看看

**Comment by ztczsyb34** [comment]
请问本币（YZF）价格什么时候才可显示🙏



---Original---
From: ***@***.***&gt;
Date: Sun, Apr 17, 2022 17:10 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [TP-Lab/tokens] Add YZF logo and info  (PR #6725)




 
Merged #6725 into master.

**Pull request merged**
