### PR TITLE
Add BabyBTC logo and info

### PR DESCRIPTION
**Pull request by 264026152**
https://bscscan.com/tx/0xcba034b1c62bda901dbf7b5d6639075b4ec779672139d1ede3dc4a90dbea8f0b

### CODE REVIEW

**Comment by opera0001** [comment]
Hash value link has been #6382 used. Please explain the situation. Thank you.

**Comment by opera0001** [comment]
You can transfer 0.00006430 bnbs to the donation address for verification.

**Comment by 264026152** [comment]
> Hash value link has been #6382 used. Please explain the situation. Thank you.

https://bscscan.com/tx/0xcba034b1c62bda901dbf7b5d6639075b4ec779672139d1ede3dc4a90dbea8f0b

**Comment by 264026152** [comment]
> Hash value link has been #6382 used. Please explain the situation. Thank you.

https://bscscan.com/tx/0xcba034b1c62bda901dbf7b5d6639075b4ec779672139d1ede3dc4a90dbea8f0b

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Pull request merged**
